In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import random

import os, shutil, subprocess, json, sys
from importlib import reload
from joblib import Parallel, delayed

from IPython.display import display

import msprime, tskit

from pathlib import Path
sys.path.append(str(Path.cwd().parent))
import sims
import em_alg

# Visualization defaults
sns.set_theme(style="whitegrid", palette="colorblind")
plt.rcParams['figure.figsize'] = (10, 6)

Установлено NUMBA_NUM_THREADS=32

In [36]:
# parameters for simulation
params = {
    'chrom_length': 5e7,      # DNA sequence length in base pairs
    'recomb_rate': 1e-8,      # Recombination rate (per bp per generation)
    'mut_rate': 2e-8,      # Mutation rate (per bp per generation)
    'gen_time': 29.0,         # Years per generation
    'n_eu': 1,          # European samples
    'n_af': 200,         # African samples
    'n_nd': 10,      # Neanderthal sample number
    'ploidy' : 2
}

# effective pop sizes in demography
Ne = {
    'anc': 18500,      # Common AMH-Neanderthal ancestor
    'nd': 3400,     # Neanderthal population
    'amh': 23000,           # Anatomically modern humans (pre-OoA)
    'ooa': 1861,            # Out-of-Africa founders
    'af': 27600,       # African population
    'eu': 13377,      # European population
    'eu_bottleneck': 1080,  # European bottleneck size
    'eu_growth': 1450       # Post-bottleneck size
}

# split and migration times
# в поколениях
t = {
    't_nd_old_migration': 40000 / params['gen_time'],  # original, older
    't_nd_migration': 30000 / params['gen_time'],  # new_one, younger
    't_amh': 550000 / params['gen_time'],  # AMH-Neanderthal split  
    't_ooa': 73900 / params['gen_time'],   # Out-of-Africa migration
    't_nd_samples': 38000 / params['gen_time'],  # Neanderthal sampling time
    't_eu_growth': 31900 / params['gen_time'],  # European growth start
}

p_admix = {"old": 0.05, "young": 0.03}

OUTPUT_DIR = "sims"

# Проверяем, существует ли папка
if os.path.exists(OUTPUT_DIR):
    print(f"DIR '{OUTPUT_DIR}' exists already. Clean up old files...")
    shutil.rmtree(OUTPUT_DIR) # Удаляет папку рекурсивно вместе со всеми файлами
os.makedirs(OUTPUT_DIR, exist_ok=True)

N_CHR, N_JOBS = 10, 4  # number of chr, -1 use all cores, N use N cores
random_seeds = random.sample(range(1, 10**9), k=N_CHR)

DIR 'sims' exists already. Clean up old files...

In [ ]:
def generate_param_grid():
    p_vals = [0.3, 0.4, 0.5]
    delta_vals = [10000, 15000, 20000]  
    young_vals = [30000, 35000, 40000, 45000, 50000]

    grid = []
    for p_old in p_vals:
        for p_young in p_vals:
            for delta in delta_vals:
                for t_young_kya in young_vals:
                    t_old_kya = t_young_kya + delta
                    if t_old_kya <= 60000:
                        grid.append({
                            "p_old": p_old,
                            "p_young": p_young,
                            "t_young_kya": t_young_kya,
                            "t_old_kya": t_old_kya,
                            "delta_kya": delta
                        })
    return grid

In [ ]:
def run_one_experiment(exp_cfg, base_params, base_Ne, base_t, n_chromosomes=10, n_jobs=4, root_dir="grid_runs"):
    exp_name = (
        f"pold_{exp_cfg['p_old']:.1f}_"
        f"pyoung_{exp_cfg['p_young']:.1f}_"
        f"told_{exp_cfg['t_old_kya']}k_"
        f"tyoung_{exp_cfg['t_young_kya']}k"
    )
    out_dir = os.path.join(root_dir, exp_name)
    os.makedirs(out_dir, exist_ok=True)

    params = dict(base_params)
    Ne = dict(base_Ne)
    t = dict(base_t)

    t["t_nd_old_migration"] = exp_cfg["t_old_kya"] / params["gen_time"]
    t["t_nd_migration"] = exp_cfg["t_young_kya"] / params["gen_time"]

    p_admix = {
        "old": exp_cfg["p_old"],
        "young": exp_cfg["p_young"]
    }

    random.seed(42)
    random_seeds = random.sample(range(1, 10**9), k=n_chromosomes)

    # --- simulate ---
    print("Начались симуляции...")
    gt_parts = Parallel(n_jobs=n_jobs)(
        delayed(sims.process_one_chromosome)(seed, params, Ne, t, p_admix, out_dir)
        for seed in random_seeds
    )
    print("Закончились симуляции.")
    gt_df = pd.concat(gt_parts, ignore_index=True)
    gt_path = os.path.join(out_dir, "all.tracts.summary.csv")
    gt_df.to_csv(gt_path, sep="\t", index=False)

    # --- without EM ---
    print("Начался запуск WITHOUT EM...")
    pred_parts = Parallel(n_jobs=n_jobs)(
        delayed(sims.run_daiseg_task)(seed, out_dir)
        for seed in random_seeds
    )
    print("Закончился запуск WITHOUT EM.")
    pred_parts = [x for x in pred_parts if x is not None]
    if pred_parts:
        pred_df = pd.concat(pred_parts, ignore_index=True)
    else:
        pred_df = pd.DataFrame(columns=["Sample", "CHR", "Start", "End", "Length", "State"])

    pred_path = os.path.join(out_dir, "all.inferred.tracts.tsv")
    pred_df.to_csv(pred_path, sep="\t", index=False)

    metrics_noem = sims.calculate_class_metrics(gt_path, pred_path, int(params["chrom_length"]))
    cm_noem, labels = sims.build_confusion_matrix(gt_df, pred_df, chrom_length=int(params["chrom_length"]), window_size=1000)

    print("\nWITHOUT EM — метрики по классам")
    metrics_noem_df = pd.DataFrame(metrics_noem["Per_class"]).T
    display(metrics_noem_df[["Precision", "Recall", "F1"]])

    print("\nWITHOUT EM — confusion matrix")
    cm_noem_df = pd.DataFrame(cm_noem, index=labels, columns=labels)
    display(cm_noem_df)

    metrics_noem_df.to_csv(os.path.join(out_dir, "metrics_noem.tsv"), sep="\t")
    cm_noem_df.to_csv(os.path.join(out_dir, "cm_noem.tsv"), sep="\t")

    # --- with EM ---
    print("Начался запуск WITH EM...")
    json_files = sorted(str(p) for p in Path(out_dir).glob("config_seed_*.json"))
    em_out_path = os.path.join(out_dir, "all.inferred.EM.tsv")
    em_alg.run_batch_em_pipeline(
        json_files,
        output_combined_file=em_out_path,
        max_iter=15,
        tol=1e-6
    )
    print("Закончился запуск WITH EM.")

    em_df = pd.read_csv(em_out_path, sep="\t") if os.path.exists(em_out_path) else pd.DataFrame(
        columns=["Sample", "CHR", "Start", "End", "Length", "State"]
    )

    metrics_em = sims.calculate_class_metrics(gt_path, em_out_path, int(params["chrom_length"]))
    cm_em, _ = sims.build_confusion_matrix(gt_df, em_df, chrom_length=int(params["chrom_length"]), window_size=1000)

    print("\nWITH EM — метрики по классам")
    metrics_em_df = pd.DataFrame(metrics_em["Per_class"]).T
    display(metrics_em_df[["Precision", "Recall", "F1"]])

    print("\nWITH EM — confusion matrix")
    cm_em_df = pd.DataFrame(cm_em, index=labels, columns=labels)
    display(cm_em_df)

    metrics_em_df.to_csv(os.path.join(out_dir, "metrics_em.tsv"), sep="\t")
    cm_em_df.to_csv(os.path.join(out_dir, "cm_em.tsv"), sep="\t")

    # --- read learned params from file ---
    learned_params_path = em_out_path.replace(".tsv", ".learned_params.json")
    if os.path.exists(learned_params_path):
        with open(learned_params_path, "r", encoding="utf-8") as f:
            learned_params = json.load(f)
    else:
        learned_params = {
            "lambdas": [np.nan, np.nan, np.nan, np.nan],
            "A": None,
            "pi": None,
            "final_log_likelihood": np.nan
        }

    # --- save summary json ---
    summary = {
        "experiment": exp_cfg,
        "without_em": {
            "metrics": metrics_noem,
            "confusion_labels": labels,
            "confusion_matrix": cm_noem.tolist()
        },
        "with_em": {
            "metrics": metrics_em,
            "confusion_labels": labels,
            "confusion_matrix": cm_em.tolist(),
            "learned_lambdas": learned_params.get("lambdas"),
            "learned_A": learned_params.get("A"),
            "learned_pi": learned_params.get("pi"),
            "final_log_likelihood": learned_params.get("final_log_likelihood")
        }
    }

    summary_path = os.path.join(out_dir, "summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    row = {
        **exp_cfg,
        "noem_old_precision": metrics_noem["Per_class"].get("Archaic_old", {}).get("Precision", np.nan),
        "noem_old_recall": metrics_noem["Per_class"].get("Archaic_old", {}).get("Recall", np.nan),
        "noem_old_f1": metrics_noem["Per_class"].get("Archaic_old", {}).get("F1", np.nan),
        "noem_young_precision": metrics_noem["Per_class"].get("Archaic_young", {}).get("Precision", np.nan),
        "noem_young_recall": metrics_noem["Per_class"].get("Archaic_young", {}).get("Recall", np.nan),
        "noem_young_f1": metrics_noem["Per_class"].get("Archaic_young", {}).get("F1", np.nan),

        "em_old_precision": metrics_em["Per_class"].get("Archaic_old", {}).get("Precision", np.nan),
        "em_old_recall": metrics_em["Per_class"].get("Archaic_old", {}).get("Recall", np.nan),
        "em_old_f1": metrics_em["Per_class"].get("Archaic_old", {}).get("F1", np.nan),
        "em_young_precision": metrics_em["Per_class"].get("Archaic_young", {}).get("Precision", np.nan),
        "em_young_recall": metrics_em["Per_class"].get("Archaic_young", {}).get("Recall", np.nan),
        "em_young_f1": metrics_em["Per_class"].get("Archaic_young", {}).get("F1", np.nan),

        "learned_lambda_n": summary["with_em"]["learned_lambdas"][0],
        "learned_lambda_af": summary["with_em"]["learned_lambdas"][1],
        "learned_lambda_old": summary["with_em"]["learned_lambdas"][2],
        "learned_lambda_young": summary["with_em"]["learned_lambdas"][3],
        "summary_json": summary_path,
        "out_dir": out_dir
    }

    print("=" * 80)
    
    return row

In [ ]:
grid = generate_param_grid()
all_rows = Parallel(n_jobs=4)(
    delayed(run_one_experiment)(
        cfg,
        base_params=params,
        base_Ne=Ne,
        base_t=t,
        n_chromosomes=10,
        n_jobs=1,              
        root_dir="grid_runs"
    )
    for cfg in grid
)

os.makedirs("grid_runs", exist_ok=True)
results_df = pd.DataFrame(all_rows) # type: ignore
results_df.to_csv("grid_runs/summary_table.tsv", sep="\t", index=False)
results_df

RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5029  0.7774  0.6107
Archaic_young     0.4881  0.2123  0.2959

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         811977         1258            270
Archaic_old      1641        73568          19841
Archaic_young    1175        70940          19330

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1655006.72 | Rates: N=0.98405, AF=0.09571, OLD=0.04575, YOUNG=0.03517
A =
[[9.98259266e-01 1.00922182e-03 7.31512373e-04]
 [7.74219553e-03 9.91447084e-01 8.10720068e-04]
 [7.93808315e-03 1.16862982e-03 9.90893287e-01]]
pi = [0.70339955 0.16979821 0.12680224]
Iter 2: LL=-1307635.73 | Rates: N=0.98425, AF=0.09548, OLD=0.04866, YOUNG=0.03238
A =
[[9.98246657e-01 1.00837779e-03 7.44964895e-04]
 [8.11759277e-03 9.91041126e-01 8.41281187e-04]
 [7.51084685e-03 1.11444078e-03 9.91374712e-01]]
pi = [0.69896512 0.17798971 0.12304517]
Iter 3: LL=-1307593.46 | Rates: N=0.98426, AF=0.09546, OLD=0.05193, YOUNG=0.03010
A =
[[9.98245875e-01 9.92513286e-04 7.61612124e-04]
 [8.56982089e-03 9.90541987e-01 8.88191754e-04]
 [7.06257096e-03 1.07272982e-03 9.91864699e-01]]
pi = [0.69877246 0.18576529 0.11546225]
Iter 4: LL=-1307557.09 | Rates: N=0.98426, AF=0.09544, OLD=0.05487, YOUNG=0.02883
A =
[[9.98245075e-01 9.69895890e-04 7.85028859e-04]
 [9.01375962e-03 9.90029292e-01 9.56948289e-04]
 [6.73832987e-03 1.07425255e-03 9.92187418e-01]]
pi = [0.69860058 0.19248777 0.10891165]
Iter 5: LL=-1307535.81 | Rates: N=0.98426, AF=0.09542, OLD=0.05726, YOUNG=0.02835
A =
[[9.98244027e-01 9.41706157e-04 8.14267218e-04]
 [9.39954625e-03 9.89546415e-01 1.05403826e-03]
 [6.53948283e-03 1.11534855e-03 9.92345169e-01]]
pi = [0.69838568 0.19630664 0.10530768]
Iter 6: LL=-1307523.20 | Rates: N=0.98427, AF=0.09541, OLD=0.05925, YOUNG=0.02829
A =
[[9.98243064e-01 9.08938957e-04 8.47997221e-04]
 [9.73526259e-03 9.89082742e-01 1.18199565e-03]
 [6.42407502e-03 1.17870291e-03 9.92397222e-01]]
pi = [0.69818438 0.1969943  0.10482132]
Iter 7: LL=-1307513.27 | Rates: N=0.98427, AF=0.09540, OLD=0.06108, YOUNG=0.02844
A =
[[9.98242276e-01 8.72992153e-04 8.84731894e-04]
 [1.00429778e-02 9.88615110e-01 1.34191251e-03]
 [6.35931141e-03 1.25066413e-03 9.92390024e-01]]
pi = [0.69801765 0.1949399  0.10704245]
Iter 8: LL=-1307503.73 | Rates: N=0.98427, AF=0.09539, OLD=0.06292, YOUNG=0.02866
A =
[[9.98241615e-01 8.35144731e-04 9.23239866e-04]
 [1.03400334e-02 9.88123994e-01 1.53597258e-03]
 [6.32616141e-03 1.32337501e-03 9.92350464e-01]]
pi = [0.69788489 0.19052692 0.11158819]
Iter 9: LL=-1307493.90 | Rates: N=0.98427, AF=0.09538, OLD=0.06487, YOUNG=0.02892
A =
[[9.98241020e-01 7.96352535e-04 9.62627499e-04]
 [1.06374411e-02 9.87594688e-01 1.76787052e-03]
 [6.31420336e-03 1.39271082e-03 9.92293086e-01]]
pi = [0.69778181 0.18403336 0.11818483]
Iter 10: LL=-1307483.58 | Rates: N=0.98427, AF=0.09537, OLD=0.06699, YOUNG=0.02919
A =
[[9.98240446e-01 7.57296350e-04 1.00225802e-03]
 [1.09415122e-02 9.87016167e-01 2.04232068e-03]
 [6.31768490e-03 1.45653321e-03 9.92225782e-01]]
pi = [0.69770578 0.17570283 0.12659138]
Iter 11: LL=-1307472.69 | Rates: N=0.98428, AF=0.09536, OLD=0.06931, YOUNG=0.02947
A =
[[9.98239866e-01 7.18472149e-04 1.04166180e-03]
 [1.12550575e-02 9.86380629e-01 2.36431328e-03]
 [6.33333284e-03 1.51373994e-03 9.92152927e-01]]
pi = [0.69765576 0.16583156 0.13651268]
Iter 12: LL=-1307461.25 | Rates: N=0.98428, AF=0.09534, OLD=0.07188, YOUNG=0.02974
A =
[[9.98239268e-01 6.80256612e-04 1.08047586e-03]
 [1.15780410e-02 9.85683641e-01 2.73831799e-03]
 [6.35914020e-03 1.56381887e-03 9.92077041e-01]]
pi = [0.69763109 0.15482224 0.14754667]
Iter 13: LL=-1307449.32 | Rates: N=0.98428, AF=0.09533, OLD=0.07470, YOUNG=0.03001
A =
[[9.98238646e-01 6.42945218e-04 1.11840914e-03]
 [1.19082342e-02 9.84924120e-01 3.16764551e-03]
 [6.39362857e-03 1.60665121e-03 9.91999720e-01]]
pi = [0.69763016 0.14317915 0.15919069]
Iter 14: LL=-1307437.02 | Rates: N=0.98428, AF=0.09532, OLD=0.07779, YOUNG=0.03027
A =
[[9.98238003e-01 6.06773812e-04 1.15522312e-03]
 [1.22423435e-02 9.84103350e-01 3.65430619e-03]
 [6.43537795e-03 1.64241010e-03 9.91922212e-01]]
pi = [0.69764958 0.13143789 0.17091253]
Iter 15: LL=-1307424.51 | Rates: N=0.98428, AF=0.09530, OLD=0.08115, YOUNG=0.03053
A =
[[9.98237347e-01 5.71932337e-04 1.19072098e-03]
 [1.25776061e-02 9.83222793e-01 4.19960040e-03]
 [6.48279346e-03 1.67147529e-03 9.91845731e-01]]
pi = [0.69768416 0.12005997 0.18225587]
Final Global Rates (lambdas): [0.98428303 0.09530165 0.08114808 0.0305347 ]
Final transition matrix A:
[[9.98237347e-01 5.71932337e-04 1.19072098e-03]
 [1.25776061e-02 9.83222793e-01 4.19960040e-03]
 [6.48279346e-03 1.67147529e-03 9.91845731e-01]]
Final initial distribution pi:
[0.69768416 0.12005997 0.18225587]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.5077  0.1147  0.1871  10813858.0   10486142.0  83482413.0
Archaic_young     0.4863  0.8758  0.6253  79415593.0   83895407.0  11267050.0
Modern            0.0000  0.0000  0.0000         0.0  815389000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         812147          170           1188
Archaic_old      1872        10821          82357
Archaic_young    1370        10309          79766

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4490  0.6424  0.5286
Archaic_young     0.5802  0.3845  0.4624

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         795564         1424            448
Archaic_old      1511        57101          30628
Archaic_young    1910        68097          43317

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 18
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1652065.55 | Rates: N=0.98042, AF=0.09620, OLD=0.04558, YOUNG=0.03598
A =
[[9.97855824e-01 1.17840753e-03 9.65768780e-04]
 [8.76429362e-03 9.90187733e-01 1.04797381e-03]
 [8.61991693e-03 1.22505999e-03 9.90155023e-01]]
pi = [0.70455745 0.15688652 0.13855604]
Iter 2: LL=-1308521.11 | Rates: N=0.98067, AF=0.09600, OLD=0.04803, YOUNG=0.03302
A =
[[9.97839678e-01 1.17966316e-03 9.80658687e-04]
 [9.00513576e-03 9.89905925e-01 1.08893939e-03]
 [8.43409942e-03 1.14842043e-03 9.90417480e-01]]
pi = [0.70158016 0.15365382 0.14476602]
Iter 3: LL=-1308480.56 | Rates: N=0.98067, AF=0.09599, OLD=0.05115, YOUNG=0.03055
A =
[[9.97838829e-01 1.16928410e-03 9.91887252e-04]
 [9.25819632e-03 9.89598994e-01 1.14280955e-03]
 [8.20629732e-03 1.06178805e-03 9.90731915e-01]]
pi = [0.70150523 0.14837807 0.15011671]
Iter 4: LL=-1308443.51 | Rates: N=0.98067, AF=0.09598, OLD=0.05392, YOUNG=0.02896
A =
[[9.97838358e-01 1.15336168e-03 1.00828032e-03]
 [9.49767260e-03 9.89284582e-01 1.21774536e-03]
 [8.02983222e-03 9.89597898e-04 9.90980570e-01]]
pi = [0.70145203 0.1439827  0.15456527]
Iter 5: LL=-1308422.54 | Rates: N=0.98067, AF=0.09596, OLD=0.05600, YOUNG=0.02820
A =
[[9.97837745e-01 1.13358758e-03 1.02866767e-03]
 [9.67753245e-03 9.89006694e-01 1.31577340e-03]
 [7.93232347e-03 9.44354878e-04 9.91123322e-01]]
pi = [0.70141716 0.14112892 0.15745392]
Iter 6: LL=-1308412.98 | Rates: N=0.98067, AF=0.09595, OLD=0.05752, YOUNG=0.02795
A =
[[9.97837232e-01 1.11099103e-03 1.05177650e-03]
 [9.80006127e-03 9.88764849e-01 1.43508981e-03]
 [7.89258968e-03 9.19978531e-04 9.91187432e-01]]
pi = [0.70140465 0.13925258 0.15934277]
Iter 7: LL=-1308407.77 | Rates: N=0.98068, AF=0.09594, OLD=0.05870, YOUNG=0.02797
A =
[[9.97836890e-01 1.08654861e-03 1.07656101e-03]
 [9.88285890e-03 9.88545068e-01 1.57207342e-03]
 [7.88693266e-03 9.07813911e-04 9.91205253e-01]]
pi = [0.70140618 0.13771927 0.16087455]
Iter 8: LL=-1308403.79 | Rates: N=0.98068, AF=0.09594, OLD=0.05973, YOUNG=0.02810
A =
[[9.97836679e-01 1.06107314e-03 1.10224761e-03]
 [9.94019005e-03 9.88335902e-01 1.72390844e-03]
 [7.90034020e-03 9.02240446e-04 9.91197419e-01]]
pi = [0.7014143  0.13619675 0.16238895]
Iter 9: LL=-1308400.13 | Rates: N=0.98068, AF=0.09593, OLD=0.06069, YOUNG=0.02828
A =
[[9.97836550e-01 1.03512502e-03 1.12832509e-03]
 [9.98095499e-03 9.88129913e-01 1.88913161e-03]
 [7.92438991e-03 9.00273627e-04 9.91175336e-01]]
pi = [0.70142484 0.13456247 0.16401269]
Iter 10: LL=-1308396.56 | Rates: N=0.98068, AF=0.09593, OLD=0.06164, YOUNG=0.02847
A =
[[9.97836469e-01 1.00905698e-03 1.15447421e-03]
 [1.00104613e-02 9.87922268e-01 2.06727075e-03]
 [7.95436374e-03 9.00406406e-04 9.91145230e-01]]
pi = [0.7014358  0.13278445 0.16577975]
Iter 11: LL=-1308393.01 | Rates: N=0.98068, AF=0.09593, OLD=0.06259, YOUNG=0.02868
A =
[[9.97836416e-01 9.83085458e-04 1.18049837e-03]
 [1.00319578e-02 9.87709609e-01 2.25843295e-03]
 [7.98752275e-03 9.01864098e-04 9.91110613e-01]]
pi = [0.70144628 0.13085872 0.16769499]
Iter 12: LL=-1308389.47 | Rates: N=0.98068, AF=0.09592, OLD=0.06357, YOUNG=0.02888
A =
[[9.97836380e-01 9.57344281e-04 1.20627537e-03]
 [1.00475310e-02 9.87489434e-01 2.46303533e-03]
 [8.02220886e-03 9.04225663e-04 9.91073565e-01]]
pi = [0.70145589 0.12878444 0.16975966]
Iter 13: LL=-1308385.93 | Rates: N=0.98068, AF=0.09592, OLD=0.06459, YOUNG=0.02908
A =
[[9.97836354e-01 9.31917988e-04 1.23172784e-03]
 [1.00585944e-02 9.87259749e-01 2.68165679e-03]
 [8.05737876e-03 9.07245102e-04 9.91035376e-01]]
pi = [0.70146444 0.12655609 0.17197947]
Iter 14: LL=-1308382.39 | Rates: N=0.98068, AF=0.09591, OLD=0.06563, YOUNG=0.02927
A =
[[9.97836333e-01 9.06861284e-04 1.25680583e-03]
 [1.00661643e-02 9.87018872e-01 2.91496345e-03]
 [8.09235156e-03 9.10768814e-04 9.90996880e-01]]
pi = [0.7014718  0.12416209 0.17436611]
Iter 15: LL=-1308378.85 | Rates: N=0.98068, AF=0.09591, OLD=0.06672, YOUNG=0.02947
A =
[[9.97836313e-01 8.82210262e-04 1.28147666e-03]
 [1.00710271e-02 9.86765299e-01 3.16367397e-03]
 [8.12666494e-03 9.14696878e-04 9.90958638e-01]]
pi = [0.70147789 0.12158546 0.17693665]
Final Global Rates (lambdas): [0.98067776 0.09591069 0.06672386 0.02946977]
Final transition matrix A:
[[9.97836313e-01 8.82210262e-04 1.28147666e-03]
 [1.00710271e-02 9.86765299e-01 3.16367397e-03]
 [8.12666494e-03 9.14696878e-04 9.90958638e-01]]
Final initial distribution pi:
[0.70147789 0.12158546 0.17693665]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.3854  0.1933  0.2575  17112638.0   27291362.0  71395116.0
Archaic_young     0.5382  0.7524  0.6275  84468029.0   72485971.0  27793265.0
Modern            0.0000  0.0000  0.0000         0.0  798642000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         795549          526           1361
Archaic_old      1375        17174          70691
Archaic_young    1718        26704          84902

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4856  0.6100  0.5407
Archaic_young     0.5813  0.4573  0.5119

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         784967         1483            694
Archaic_old      1830        59418          36588
Archaic_young    1814        60920          52286

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1644249.63 | Rates: N=0.96913, AF=0.09660, OLD=0.04933, YOUNG=0.04021
A =
[[0.99759012 0.00129572 0.00111416]
 [0.00937221 0.98938892 0.00123887]
 [0.00897159 0.00136203 0.98966638]]
pi = [0.85302717 0.08277646 0.06419637]
Iter 2: LL=-1311284.41 | Rates: N=0.96938, AF=0.09645, OLD=0.05161, YOUNG=0.03723
A =
[[0.99758237 0.00129392 0.00112371]
 [0.00966064 0.98905078 0.00128858]
 [0.00869495 0.00129216 0.99001289]]
pi = [0.85590703 0.08943565 0.05465732]
Iter 3: LL=-1311245.03 | Rates: N=0.96938, AF=0.09644, OLD=0.05501, YOUNG=0.03466
A =
[[0.99758181 0.00128708 0.00113111]
 [0.01000899 0.98863888 0.00135213]
 [0.00840961 0.00121649 0.9903739 ]]
pi = [0.85606875 0.10173789 0.04219337]
Iter 4: LL=-1311202.58 | Rates: N=0.96938, AF=0.09642, OLD=0.05832, YOUNG=0.03282
A =
[[0.99758116 0.00127323 0.00114561]
 [0.01037535 0.98817933 0.00144532]
 [0.00816808 0.00115303 0.9906789 ]]
pi = [0.8558322  0.11567237 0.02849544]
Iter 5: LL=-1311173.58 | Rates: N=0.96939, AF=0.09640, OLD=0.06104, YOUNG=0.03183
A =
[[0.99758016 0.0012527  0.00116714]
 [0.01069475 0.98773223 0.00157302]
 [0.00801149 0.00111817 0.99087034]]
pi = [0.85543183 0.12751489 0.01705327]
Iter 6: LL=-1311158.14 | Rates: N=0.96939, AF=0.09639, OLD=0.06316, YOUNG=0.03145
A =
[[0.9975792  0.00122661 0.0011942 ]
 [0.01095274 0.98731425 0.00173301]
 [0.00792687 0.00110801 0.99096512]]
pi = [0.85501989 0.13561173 0.00936838]
Iter 7: LL=-1311149.13 | Rates: N=0.96939, AF=0.09637, OLD=0.06489, YOUNG=0.03140
A =
[[0.99757846 0.00119647 0.00122508]
 [0.01116216 0.98691877 0.00191907]
 [0.00788959 0.00111274 0.99099768]]
pi = [0.85469351 0.14041708 0.00488941]
Iter 8: LL=-1311142.30 | Rates: N=0.96939, AF=0.09636, OLD=0.06641, YOUNG=0.03151
A =
[[0.99757793 0.00116373 0.00125834]
 [0.01133771 0.98653696 0.00212533]
 [0.00788151 0.00112501 0.99099348]]
pi = [0.8544632  0.14305275 0.00248405]
Iter 9: LL=-1311136.15 | Rates: N=0.96939, AF=0.09636, OLD=0.06785, YOUNG=0.03169
A =
[[0.99757757 0.00112949 0.00129294]
 [0.01148964 0.98616266 0.0023477 ]
 [0.0078915  0.0011407  0.9909678 ]]
pi = [0.85430371 0.1444493  0.00124699]
Iter 10: LL=-1311130.28 | Rates: N=0.96939, AF=0.09635, OLD=0.06927, YOUNG=0.03191
A =
[[0.99757731 0.0010945  0.00132818]
 [0.01162452 0.98579181 0.00258367]
 [0.00791278 0.0011577  0.99092952]]
pi = [8.54189452e-01 1.45186614e-01 6.23933862e-04]
Iter 11: LL=-1311124.57 | Rates: N=0.96939, AF=0.09634, OLD=0.07070, YOUNG=0.03213
A =
[[0.99757713 0.00105927 0.0013636 ]
 [0.01174678 0.98542148 0.00283175]
 [0.00794108 0.00117495 0.99088397]]
pi = [8.54103297e-01 1.45583955e-01 3.12748436e-04]
Iter 12: LL=-1311119.02 | Rates: N=0.96939, AF=0.09634, OLD=0.07216, YOUNG=0.03235
A =
[[0.99757701 0.00102415 0.00139884]
 [0.01185967 0.98504925 0.00309108]
 [0.00797355 0.00119194 0.99083451]]
pi = [8.54035189e-01 1.45807273e-01 1.57537934e-04]
Iter 13: LL=-1311113.61 | Rates: N=0.96939, AF=0.09633, OLD=0.07365, YOUNG=0.03256
A =
[[9.97576925e-01 9.89379272e-04 1.43369539e-03]
 [1.19658064e-02 9.84672975e-01 3.36121846e-03]
 [8.00823156e-03 1.20842016e-03 9.90783348e-01]]
pi = [8.53979438e-01 1.45940654e-01 7.99079103e-05]
Iter 14: LL=-1311108.35 | Rates: N=0.96939, AF=0.09632, OLD=0.07518, YOUNG=0.03278
A =
[[9.97576867e-01 9.55147022e-04 1.46798637e-03]
 [1.20673699e-02 9.84290622e-01 3.64200764e-03]
 [8.04377407e-03 1.22426851e-03 9.90731957e-01]]
pi = [8.53932764e-01 1.46026365e-01 4.08718685e-05]
Iter 15: LL=-1311103.24 | Rates: N=0.96939, AF=0.09632, OLD=0.07676, YOUNG=0.03299
A =
[[9.97576822e-01 9.21584559e-04 1.50159295e-03]
 [1.21663084e-02 9.83900137e-01 3.93355457e-03]
 [8.07922063e-03 1.23945319e-03 9.90681326e-01]]
pi = [8.53893168e-01 1.46085729e-01 2.11031898e-05]
Final Global Rates (lambdas): [0.96939429 0.09631658 0.0767574  0.03298905]
Final transition matrix A:
[[9.97576822e-01 9.21584559e-04 1.50159295e-03]
 [1.21663084e-02 9.83900137e-01 3.93355457e-03]
 [8.07922063e-03 1.23945319e-03 9.90681326e-01]]
Final initial distribution pi:
[8.53893168e-01 1.46085729e-01 2.11031898e-05]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.5141  0.1870  0.2743  18136626.0   17144374.0  78844970.0
Archaic_young     0.5461  0.8464  0.6639  96368484.0   80088516.0  17494903.0
Modern            0.0000  0.0000  0.0000         0.0  788262000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         784953          534           1657
Archaic_old      1701        18230          77905
Archaic_young    1608        16517          96895

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4829  0.6621  0.5585
Archaic_young     0.5952  0.4070  0.4834

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         800413         1334            676
Archaic_old      2156        59223          28554
Archaic_young    2550        61559          43535

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1657113.67 | Rates: N=0.97876, AF=0.09488, OLD=0.05855, YOUNG=0.04766
A =
[[0.9976054  0.00128352 0.00111108]
 [0.01006491 0.98858235 0.00135274]
 [0.01012561 0.00157124 0.98830315]]
pi = [0.94834573 0.02454267 0.0271116 ]
Iter 2: LL=-1315304.27 | Rates: N=0.97903, AF=0.09468, OLD=0.06185, YOUNG=0.04346
A =
[[0.99760694 0.00126995 0.00112311]
 [0.01019539 0.98842903 0.00137558]
 [0.00989602 0.00150802 0.98859596]]
pi = [0.95609837 0.01519297 0.02870866]
Iter 3: LL=-1315245.98 | Rates: N=0.97903, AF=0.09466, OLD=0.06636, YOUNG=0.03981
A =
[[0.99760807 0.00124978 0.00114215]
 [0.01042534 0.98816198 0.00141269]
 [0.00966192 0.00143083 0.98890724]]
pi = [0.95651271 0.00791941 0.03556788]
Iter 4: LL=-1315187.96 | Rates: N=0.97903, AF=0.09463, OLD=0.07049, YOUNG=0.03742
A =
[[0.99760882 0.00122111 0.00117007]
 [0.01066346 0.98785184 0.0014847 ]
 [0.00946423 0.00137553 0.98916025]]
pi = [0.95559541 0.0029699  0.04143469]
Iter 5: LL=-1315154.04 | Rates: N=0.97903, AF=0.09460, OLD=0.07362, YOUNG=0.03628
A =
[[0.99760888 0.00118734 0.00120378]
 [0.01085283 0.98754985 0.00159732]
 [0.0093469  0.00136246 0.98929064]]
pi = [9.54903576e-01 8.79402195e-04 4.42170216e-02]
Iter 6: LL=-1315138.47 | Rates: N=0.97903, AF=0.09458, OLD=0.07593, YOUNG=0.03592
A =
[[0.99760871 0.00115045 0.00124084]
 [0.01099395 0.98726004 0.00174601]
 [0.00928832 0.00138137 0.9893303 ]]
pi = [9.54648024e-01 2.32125658e-04 4.51198499e-02]
Iter 7: LL=-1315129.68 | Rates: N=0.97903, AF=0.09457, OLD=0.07777, YOUNG=0.03596
A =
[[0.99760858 0.00111171 0.00127971]
 [0.01110598 0.98697019 0.00192383]
 [0.00926151 0.00141756 0.98932093]]
pi = [9.54622062e-01 5.84648130e-05 4.53194729e-02]
Iter 8: LL=-1315122.59 | Rates: N=0.97903, AF=0.09456, OLD=0.07942, YOUNG=0.03617
A =
[[0.99760853 0.00107199 0.00131948]
 [0.01120425 0.9866693  0.00212645]
 [0.00925056 0.0014616  0.98928784]]
pi = [9.54684140e-01 1.44619024e-05 4.53013982e-02]
Iter 9: LL=-1315115.80 | Rates: N=0.97903, AF=0.09456, OLD=0.08104, YOUNG=0.03646
A =
[[0.99760854 0.00103188 0.00135959]
 [0.01129786 0.98634963 0.00235251]
 [0.00924754 0.00150864 0.98924382]]
pi = [9.54776211e-01 3.55060964e-06 4.52202382e-02]
Iter 10: LL=-1315108.96 | Rates: N=0.97903, AF=0.09455, OLD=0.08268, YOUNG=0.03677
A =
[[9.97608567e-01 9.91732494e-04 1.39970053e-03]
 [1.13919595e-02 9.86005324e-01 2.60271669e-03]
 [9.24859676e-03 1.55631139e-03 9.89195092e-01]]
pi = [9.54877210e-01 8.67561651e-07 4.51219221e-02]
Iter 11: LL=-1315101.97 | Rates: N=0.97903, AF=0.09454, OLD=0.08441, YOUNG=0.03710
A =
[[9.97608613e-01 9.51781109e-04 1.43960539e-03]
 [1.14895429e-02 9.85631456e-01 2.87900112e-03]
 [9.25188761e-03 1.60337853e-03 9.89144734e-01]]
pi = [9.54979415e-01 2.10792524e-07 4.50203745e-02]
Iter 12: LL=-1315094.79 | Rates: N=0.97903, AF=0.09454, OLD=0.08624, YOUNG=0.03743
A =
[[9.97608668e-01 9.12176653e-04 1.47915547e-03]
 [1.15922781e-02 9.85223686e-01 3.18403583e-03]
 [9.25661081e-03 1.64910864e-03 9.89094281e-01]]
pi = [9.55079843e-01 5.07992679e-08 4.49201061e-02]
Iter 13: LL=-1315087.39 | Rates: N=0.97903, AF=0.09453, OLD=0.08821, YOUNG=0.03776
A =
[[9.97608726e-01 8.73040350e-04 1.51823319e-03]
 [1.17008803e-02 9.84778208e-01 3.52091213e-03]
 [9.26256253e-03 1.69296690e-03 9.89044471e-01]]
pi = [9.55177331e-01 1.21007397e-08 4.48226565e-02]
Iter 14: LL=-1315079.77 | Rates: N=0.97903, AF=0.09453, OLD=0.09031, YOUNG=0.03808
A =
[[9.97608787e-01 8.34483257e-04 1.55672956e-03]
 [1.18152821e-02 9.84291748e-01 3.89296995e-03]
 [9.26987256e-03 1.73450848e-03 9.88995619e-01]]
pi = [9.55271499e-01 2.83812816e-09 4.47284985e-02]
Iter 15: LL=-1315071.91 | Rates: N=0.97903, AF=0.09452, OLD=0.09258, YOUNG=0.03841
A =
[[9.97608849e-01 7.96619166e-04 1.59453228e-03]
 [1.19348044e-02 9.83761482e-01 4.30371381e-03]
 [9.27881537e-03 1.77335042e-03 9.88947834e-01]]
pi = [9.55362341e-01 6.52777489e-10 4.46376588e-02]
Final Global Rates (lambdas): [0.97902967 0.09451952 0.09257674 0.03840844]
Final transition matrix A:
[[9.97608849e-01 7.96619166e-04 1.59453228e-03]
 [1.19348044e-02 9.83761482e-01 4.30371381e-03]
 [9.27881537e-03 1.77335042e-03 9.88947834e-01]]
Final initial distribution pi:
[9.55362341e-01 6.52777489e-10 4.46376588e-02]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.5161  0.2009  0.2892  17895910.0   16778090.0  71170232.0
Archaic_young     0.5495  0.8243  0.6594  87721267.0   71930733.0  18692108.0
Modern            0.0000  0.0000  0.0000         0.0  805674000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         800641          100           1682
Archaic_old      2312        17905          69716
Archaic_young    2721        16669          88254

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4753  0.6053  0.5325
Archaic_young     0.5714  0.4081  0.4761

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         806877          255            651
Archaic_old      4441        52556          30737
Archaic_young    4377        57753          42353

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1667982.16 | Rates: N=0.98158, AF=0.09641, OLD=0.06432, YOUNG=0.05381
A =
[[0.99752211 0.00131741 0.00116048]
 [0.01094376 0.98752295 0.00153329]
 [0.01074387 0.00171694 0.98753919]]
pi = [0.79935796 0.10265716 0.09798487]
Iter 2: LL=-1322466.49 | Rates: N=0.98184, AF=0.09625, OLD=0.06748, YOUNG=0.04973
A =
[[0.99753806 0.00130212 0.00115982]
 [0.0112248  0.98719493 0.00158027]
 [0.01026    0.00164149 0.9880985 ]]
pi = [0.79903842 0.09496101 0.10600057]
Iter 3: LL=-1322414.17 | Rates: N=0.98184, AF=0.09624, OLD=0.07256, YOUNG=0.04604
A =
[[0.99753926 0.00129271 0.00116803]
 [0.01174939 0.98660513 0.00164548]
 [0.00980729 0.00155558 0.98863713]]
pi = [0.79901923 0.0828211  0.11815967]
Iter 4: LL=-1322350.53 | Rates: N=0.98184, AF=0.09620, OLD=0.07784, YOUNG=0.04336
A =
[[0.99753922 0.00127529 0.00118549]
 [0.01233988 0.98590536 0.00175476]
 [0.00941422 0.00149419 0.98909159]]
pi = [0.79898085 0.06682777 0.13419139]
Iter 5: LL=-1322303.83 | Rates: N=0.98184, AF=0.09616, OLD=0.08236, YOUNG=0.04196
A =
[[0.99753864 0.00124806 0.0012133 ]
 [0.01285977 0.98521666 0.00192357]
 [0.00916372 0.0014848  0.98935148]]
pi = [0.79894466 0.0499314  0.15112394]
Iter 6: LL=-1322277.64 | Rates: N=0.98184, AF=0.09613, OLD=0.08603, YOUNG=0.04144
A =
[[0.99753798 0.00121158 0.00125044]
 [0.01327658 0.98456946 0.00215396]
 [0.00903617 0.00151833 0.9894455 ]]
pi = [0.79893138 0.0348952  0.16617342]
Iter 7: LL=-1322261.04 | Rates: N=0.98184, AF=0.09610, OLD=0.08918, YOUNG=0.04139
A =
[[0.9975375  0.00116811 0.00129439]
 [0.01361509 0.98394545 0.00243946]
 [0.00898699 0.00157665 0.98943636]]
pi = [0.79893884 0.0229573  0.17810386]
Iter 8: LL=-1322247.22 | Rates: N=0.98184, AF=0.09608, OLD=0.09215, YOUNG=0.04155
A =
[[0.99753725 0.00112011 0.00134264]
 [0.01390507 0.98332079 0.00277415]
 [0.00898322 0.00164698 0.9893698 ]]
pi = [0.79895513 0.01423429 0.18681058]
Iter 9: LL=-1322233.84 | Rates: N=0.98184, AF=0.09606, OLD=0.09514, YOUNG=0.04180
A =
[[0.99753715 0.00106948 0.00139337]
 [0.01416867 0.98267538 0.00315596]
 [0.00900493 0.00172221 0.98927286]]
pi = [0.79897152 0.00830505 0.19272343]
Iter 10: LL=-1322220.21 | Rates: N=0.98184, AF=0.09603, OLD=0.09830, YOUNG=0.04210
A =
[[0.99753712 0.0010175  0.00144538]
 [0.014422   0.98199144 0.00358656]
 [0.00904047 0.00179854 0.98916099]]
pi = [0.79898415 0.00454822 0.19646764]
Iter 11: LL=-1322206.07 | Rates: N=0.98184, AF=0.09601, OLD=0.10171, YOUNG=0.04241
A =
[[9.97537100e-01 9.65004642e-04 1.49789515e-03]
 [1.46777781e-02 9.81251588e-01 4.07063376e-03]
 [9.08294969e-03 1.87371796e-03 9.89043332e-01]]
pi = [0.79899232 0.00233069 0.19867698]
Iter 12: LL=-1322191.28 | Rates: N=0.98184, AF=0.09599, OLD=0.10547, YOUNG=0.04274
A =
[[9.97537043e-01 9.12561294e-04 1.55039534e-03]
 [1.49467588e-02 9.80437961e-01 4.61527994e-03]
 [9.12829564e-03 1.94612901e-03 9.88925575e-01]]
pi = [0.79899684 0.00111336 0.19988981]
Iter 13: LL=-1322175.68 | Rates: N=0.98184, AF=0.09596, OLD=0.10963, YOUNG=0.04308
A =
[[9.97536928e-01 8.60590870e-04 1.60248113e-03]
 [1.52380447e-02 9.79532392e-01 5.22956293e-03]
 [9.17423646e-03 2.01438523e-03 9.88811378e-01]]
pi = [7.98998909e-01 4.93536058e-04 2.00507555e-01]
Iter 14: LL=-1322159.18 | Rates: N=0.98184, AF=0.09593, OLD=0.11426, YOUNG=0.04343
A =
[[9.97536752e-01 8.09455063e-04 1.65379264e-03]
 [1.55586942e-02 9.78517536e-01 5.92377019e-03]
 [9.21974108e-03 2.07716553e-03 9.88703093e-01]]
pi = [7.98999662e-01 2.01996626e-04 2.00798341e-01]
Iter 15: LL=-1322141.72 | Rates: N=0.98183, AF=0.09590, OLD=0.11943, YOUNG=0.04379
A =
[[9.97536509e-01 7.59527301e-04 1.70396403e-03]
 [1.59132367e-02 9.77378458e-01 6.70830490e-03]
 [9.26462883e-03 2.13322221e-03 9.88602149e-01]]
pi = [7.98999910e-01 7.59544907e-05 2.00924135e-01]
Final Global Rates (lambdas): [0.98183382 0.09590235 0.11942571 0.04379072]
Final transition matrix A:
[[9.97536509e-01 7.59527301e-04 1.70396403e-03]
 [1.59132367e-02 9.77378458e-01 6.70830490e-03]
 [9.26462883e-03 2.13322221e-03 9.88602149e-01]]
Final initial distribution pi:
[7.98999910e-01 7.59544907e-05 2.00924135e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.4449  0.1199  0.1889  10409112.0   12986888.0  76409620.0
Archaic_young     0.5358  0.8609  0.6605  88899335.0   77028665.0  14365638.0
Modern            0.0000  0.0000  0.0000         0.0  810676000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         805748          311           1724
Archaic_old      2550        10433          74751
Archaic_young    2378        12652          89453

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5185  0.7926  0.6269
Archaic_young     0.5824  0.2757  0.3743

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         815055         1466            237
Archaic_old      1807        72371          17619
Archaic_young    1208        65157          25080

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1655191.64 | Rates: N=0.98402, AF=0.09569, OLD=0.04618, YOUNG=0.03118
A =
[[9.98163084e-01 1.16779002e-03 6.69125523e-04]
 [8.57439239e-03 9.90676862e-01 7.48745640e-04]
 [8.12958727e-03 1.25139831e-03 9.90619014e-01]]
pi = [0.85622602 0.09291206 0.05086192]
Iter 2: LL=-1308163.64 | Rates: N=0.98424, AF=0.09550, OLD=0.04789, YOUNG=0.02930
A =
[[9.98151015e-01 1.16456328e-03 6.84421784e-04]
 [8.94672617e-03 9.90267631e-01 7.85642888e-04]
 [7.67841501e-03 1.17699540e-03 9.91144590e-01]]
pi = [0.8602663  0.09895756 0.04077614]
Iter 3: LL=-1308145.75 | Rates: N=0.98424, AF=0.09549, OLD=0.04955, YOUNG=0.02815
A =
[[9.98149953e-01 1.15471301e-03 6.95333661e-04]
 [9.24886480e-03 9.89929120e-01 8.22014884e-04]
 [7.35371952e-03 1.13838025e-03 9.91507900e-01]]
pi = [0.85987147 0.1074418  0.03268672]
Iter 4: LL=-1308135.59 | Rates: N=0.98425, AF=0.09548, OLD=0.05081, YOUNG=0.02756
A =
[[9.98149337e-01 1.14276373e-03 7.07899285e-04]
 [9.48543040e-03 9.89651382e-01 8.63187258e-04]
 [7.14563097e-03 1.13153127e-03 9.91722838e-01]]
pi = [0.85907963 0.1145419  0.02637847]
Iter 5: LL=-1308130.73 | Rates: N=0.98425, AF=0.09547, OLD=0.05172, YOUNG=0.02733
A =
[[9.98148810e-01 1.12903605e-03 7.22154309e-04]
 [9.66425475e-03 9.89425843e-01 9.09902550e-04]
 [7.01941158e-03 1.14765674e-03 9.91832932e-01]]
pi = [0.85845116 0.11979687 0.02175197]
Iter 6: LL=-1308128.16 | Rates: N=0.98425, AF=0.09547, OLD=0.05240, YOUNG=0.02729
A =
[[9.98148414e-01 1.11386737e-03 7.37719080e-04]
 [9.80271568e-03 9.89235543e-01 9.61741254e-04]
 [6.94304941e-03 1.17753045e-03 9.91879420e-01]]
pi = [0.8580109  0.12358119 0.0184079 ]
Iter 7: LL=-1308126.36 | Rates: N=0.98425, AF=0.09547, OLD=0.05296, YOUNG=0.02734
A =
[[9.98148132e-01 1.09769020e-03 7.54177938e-04]
 [9.91556473e-03 9.89066394e-01 1.01804093e-03]
 [6.89627034e-03 1.21486691e-03 9.91888863e-01]]
pi = [0.85769903 0.12633211 0.01596886]
Iter 8: LL=-1308124.79 | Rates: N=0.98425, AF=0.09546, OLD=0.05345, YOUNG=0.02743
A =
[[9.98147929e-01 1.08087743e-03 7.71193248e-04]
 [1.00125133e-02 9.88909140e-01 1.07834673e-03]
 [6.86744473e-03 1.25595867e-03 9.91876597e-01]]
pi = [0.85746531 0.12836831 0.01416638]
Iter 9: LL=-1308123.30 | Rates: N=0.98425, AF=0.09546, OLD=0.05391, YOUNG=0.02754
A =
[[9.98147777e-01 1.06370438e-03 7.88518364e-04]
 [1.00994577e-02 9.88758089e-01 1.14245317e-03]
 [6.84998710e-03 1.29870045e-03 9.91851312e-01]]
pi = [0.85727906 0.12989771 0.01282323]
Iter 10: LL=-1308121.83 | Rates: N=0.98425, AF=0.09546, OLD=0.05436, YOUNG=0.02765
A =
[[9.98147657e-01 1.04636521e-03 8.05977884e-04]
 [1.01799217e-02 9.88609751e-01 1.21032752e-03]
 [6.84008915e-03 1.34187885e-03 9.91818032e-01]]
pi = [0.8571229  0.13105382 0.01182327]
Iter 11: LL=-1308120.39 | Rates: N=0.98425, AF=0.09546, OLD=0.05481, YOUNG=0.02777
A =
[[9.98147557e-01 1.02899745e-03 8.23445817e-04]
 [1.02560300e-02 9.88461934e-01 1.28203568e-03]
 [6.83547385e-03 1.38476244e-03 9.91779764e-01]]
pi = [0.85698702 0.13192364 0.01108934]
Iter 12: LL=-1308118.96 | Rates: N=0.98425, AF=0.09546, OLD=0.05526, YOUNG=0.02788
A =
[[9.98147470e-01 1.01170095e-03 8.40829327e-04]
 [1.03290832e-02 9.88313223e-01 1.35769340e-03]
 [6.83472995e-03 1.42688384e-03 9.91738386e-01]]
pi = [0.85686574 0.13256482 0.01056944]
Iter 13: LL=-1308117.55 | Rates: N=0.98425, AF=0.09546, OLD=0.05571, YOUNG=0.02799
A =
[[9.98147391e-01 9.94550482e-04 8.58058031e-04]
 [1.03998860e-02 9.88162675e-01 1.43743860e-03]
 [6.83695160e-03 1.46792709e-03 9.91695121e-01]]
pi = [0.85675566 0.13301599 0.01022835]
Iter 14: LL=-1308116.16 | Rates: N=0.98425, AF=0.09546, OLD=0.05616, YOUNG=0.02809
A =
[[9.98147319e-01 9.77603522e-04 8.75077251e-04]
 [1.04689376e-02 9.88009646e-01 1.52141688e-03]
 [6.84153705e-03 1.50766962e-03 9.91650793e-01]]
pi = [0.85665466 0.13330289 0.01004245]
Iter 15: LL=-1308114.79 | Rates: N=0.98425, AF=0.09545, OLD=0.05663, YOUNG=0.02819
A =
[[9.98147251e-01 9.60905143e-04 8.91843793e-04]
 [1.05365462e-02 9.87853679e-01 1.60977490e-03]
 [6.84807203e-03 1.54595176e-03 9.91605976e-01]]
pi = [0.85656142 0.13344211 0.00999647]
Final Global Rates (lambdas): [0.98425092 0.09545417 0.05662611 0.02819435]
Final transition matrix A:
[[9.98147251e-01 9.60905143e-04 8.91843793e-04]
 [1.05365462e-02 9.87853679e-01 1.60977490e-03]
 [6.84807203e-03 1.54595176e-03 9.91605976e-01]]
Final initial distribution pi:
[0.85656142 0.13344211 0.00999647]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.4963  0.3735  0.4262  33965736.0   34475264.0  56971836.0
Archaic_young     0.4982  0.6253  0.5546  56706241.0   57114759.0  33976402.0
Modern            0.0000  0.0000  0.0000         0.0  817738000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         814962          900            896
Archaic_old      1678        34122          55997
Archaic_young    1098        33419          56928

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5186  0.7934  0.6272
Archaic_young     0.6816  0.3652  0.4756

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         785082         1780            369
Archaic_old      2247        78549          18649
Archaic_young    1703        70484          41137

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1639446.14 | Rates: N=0.96910, AF=0.09485, OLD=0.05038, YOUNG=0.03482
A =
[[9.97632411e-01 1.43577919e-03 9.31809581e-04]
 [9.19244180e-03 9.89878835e-01 9.28722709e-04]
 [8.81755575e-03 1.36759960e-03 9.89814845e-01]]
pi = [0.84769916 0.08576908 0.06653177]
Iter 2: LL=-1307315.55 | Rates: N=0.96937, AF=0.09464, OLD=0.05230, YOUNG=0.03235
A =
[[9.97615851e-01 1.42135685e-03 9.62792503e-04]
 [9.45813949e-03 9.89574988e-01 9.66872417e-04]
 [8.55649356e-03 1.28358526e-03 9.90159921e-01]]
pi = [0.84935191 0.08244609 0.068202  ]
Iter 3: LL=-1307290.34 | Rates: N=0.96937, AF=0.09463, OLD=0.05430, YOUNG=0.03089
A =
[[9.97614851e-01 1.39773179e-03 9.87416897e-04]
 [9.65268050e-03 9.89341164e-01 1.00615551e-03]
 [8.36656987e-03 1.22747157e-03 9.90405959e-01]]
pi = [0.84941071 0.07990789 0.07068141]
Iter 4: LL=-1307275.89 | Rates: N=0.96938, AF=0.09462, OLD=0.05586, YOUNG=0.03014
A =
[[0.99761455 0.0013708  0.00101465]
 [0.00980381 0.98914115 0.00105504]
 [0.00824731 0.00119626 0.99055643]]
pi = [0.84942192 0.07734136 0.07323673]
Iter 5: LL=-1307268.64 | Rates: N=0.96938, AF=0.09461, OLD=0.05704, YOUNG=0.02985
A =
[[0.9976143  0.00134183 0.00104387]
 [0.00991612 0.98897069 0.00111319]
 [0.00818294 0.00118486 0.99063221]]
pi = [0.84942976 0.07492148 0.07564876]
Iter 6: LL=-1307264.44 | Rates: N=0.96938, AF=0.09460, OLD=0.05797, YOUNG=0.02982
A =
[[0.99761413 0.00131145 0.00107442]
 [0.01000138 0.98881934 0.00117928]
 [0.00815236 0.00118586 0.99066178]]
pi = [0.84943479 0.0726976  0.07786761]
Iter 7: LL=-1307261.25 | Rates: N=0.96938, AF=0.09460, OLD=0.05877, YOUNG=0.02991
A =
[[0.99761402 0.00128019 0.00110579]
 [0.01006991 0.98867793 0.00125216]
 [0.00814124 0.00119391 0.99066485]]
pi = [0.84943722 0.07065579 0.07990699]
Iter 8: LL=-1307258.33 | Rates: N=0.96938, AF=0.09459, OLD=0.05951, YOUNG=0.03006
A =
[[0.99761397 0.00124842 0.00113761]
 [0.01012847 0.98854037 0.00133116]
 [0.00814129 0.00120584 0.99065286]]
pi = [0.84943753 0.06876917 0.0817933 ]
Iter 9: LL=-1307255.48 | Rates: N=0.96938, AF=0.09459, OLD=0.06022, YOUNG=0.03024
A =
[[0.99761394 0.00121643 0.00116963]
 [0.01018115 0.98840278 0.00141608]
 [0.00814788 0.00121992 0.9906322 ]]
pi = [0.84943622 0.06701299 0.08355079]
Iter 10: LL=-1307252.64 | Rates: N=0.96938, AF=0.09459, OLD=0.06094, YOUNG=0.03043
A =
[[0.99761393 0.00118439 0.00120167]
 [0.0102304  0.98826255 0.00150705]
 [0.00815836 0.00123518 0.99060646]]
pi = [0.84943366 0.06536688 0.08519946]
Iter 11: LL=-1307249.79 | Rates: N=0.96938, AF=0.09458, OLD=0.06166, YOUNG=0.03062
A =
[[0.99761394 0.00115245 0.00123362]
 [0.0102778  0.98811781 0.0016044 ]
 [0.00817118 0.00125108 0.99057774]]
pi = [0.84943015 0.06381412 0.08675573]
Iter 12: LL=-1307246.92 | Rates: N=0.96938, AF=0.09458, OLD=0.06241, YOUNG=0.03081
A =
[[0.99761395 0.00112068 0.00126537]
 [0.01032434 0.98796706 0.00170859]
 [0.0081854  0.00126729 0.99054731]]
pi = [0.84942589 0.06234083 0.08823328]
Iter 13: LL=-1307244.03 | Rates: N=0.96938, AF=0.09458, OLD=0.06318, YOUNG=0.03100
A =
[[0.99761397 0.00108916 0.00129687]
 [0.01037076 0.98780903 0.0018202 ]
 [0.00820042 0.00128361 0.99051597]]
pi = [0.84942105 0.06093535 0.08964361]
Iter 14: LL=-1307241.12 | Rates: N=0.96938, AF=0.09458, OLD=0.06397, YOUNG=0.03119
A =
[[0.99761399 0.00105796 0.00132805]
 [0.01041758 0.98764255 0.00193987]
 [0.00821588 0.00129989 0.99048424]]
pi = [0.84941575 0.05958787 0.09099638]
Iter 15: LL=-1307238.19 | Rates: N=0.96938, AF=0.09457, OLD=0.06480, YOUNG=0.03138
A =
[[0.99761401 0.0010271  0.00135889]
 [0.01046521 0.98746649 0.0020683 ]
 [0.00823151 0.00131601 0.99045248]]
pi = [0.8494101  0.05829007 0.09229983]
Final Global Rates (lambdas): [0.96937828 0.09457244 0.06479887 0.03137883]
Final transition matrix A:
[[0.99761401 0.0010271  0.00135889]
 [0.01046521 0.98746649 0.0020683 ]
 [0.00823151 0.00131601 0.99045248]]
Final initial distribution pi:
[0.8494101  0.05829007 0.09229983]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.5492  0.3386  0.4190  33379280.0   27393720.0  65187922.0
Archaic_young     0.5625  0.7546  0.6446  84715442.0   65884558.0  27545852.0
Modern            0.0000  0.0000  0.0000         0.0  788627000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         785017          615           1599
Archaic_old      2095        33499          63851
Archaic_young    1515        26659          85150

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4674  0.7548  0.5773
Archaic_young     0.7247  0.4189  0.5309

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         804745         1402            427
Archaic_old      2032        58854          17520
Archaic_young    2067        65075          47878

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1657767.87 | Rates: N=0.97834, AF=0.09664, OLD=0.05627, YOUNG=0.03844
A =
[[9.97725342e-01 1.34200839e-03 9.32649834e-04]
 [1.01029160e-02 9.88788171e-01 1.10891309e-03]
 [9.43331428e-03 1.49000555e-03 9.89076680e-01]]
pi = [0.84665656 0.1009084  0.05243504]
Iter 2: LL=-1315670.72 | Rates: N=0.97858, AF=0.09649, OLD=0.05971, YOUNG=0.03445
A =
[[9.97726554e-01 1.31319539e-03 9.60251086e-04]
 [1.04447569e-02 9.88391026e-01 1.16421703e-03]
 [9.00099979e-03 1.37425633e-03 9.89624744e-01]]
pi = [0.84813108 0.12047984 0.03138908]
Iter 3: LL=-1315613.04 | Rates: N=0.97859, AF=0.09648, OLD=0.06327, YOUNG=0.03213
A =
[[9.97726126e-01 1.28411396e-03 9.89759955e-04]
 [1.07317280e-02 9.88042125e-01 1.22614720e-03]
 [8.77437861e-03 1.30826833e-03 9.89917353e-01]]
pi = [0.84781469 0.13839184 0.01379347]
Iter 4: LL=-1315581.53 | Rates: N=0.97859, AF=0.09646, OLD=0.06587, YOUNG=0.03106
A =
[[0.99772541 0.00125102 0.00102357]
 [0.01092241 0.98776481 0.00131277]
 [0.00867593 0.00129106 0.99003301]]
pi = [0.84744815 0.14781004 0.00474181]
Iter 5: LL=-1315568.32 | Rates: N=0.97859, AF=0.09645, OLD=0.06769, YOUNG=0.03073
A =
[[0.99772488 0.00121579 0.00105933]
 [0.01103995 0.98753842 0.00142164]
 [0.00865166 0.00130663 0.99004171]]
pi = [0.8472204  0.15134776 0.00143184]
Iter 6: LL=-1315561.44 | Rates: N=0.97859, AF=0.09644, OLD=0.06908, YOUNG=0.03075
A =
[[0.9977246  0.00117985 0.00109555]
 [0.01111878 0.9873343  0.00154693]
 [0.00866022 0.00133829 0.99000149]]
pi = [8.47099991e-01 1.52489261e-01 4.10747206e-04]
Iter 7: LL=-1315556.24 | Rates: N=0.97859, AF=0.09644, OLD=0.07028, YOUNG=0.03092
A =
[[0.99772447 0.0011441  0.00113143]
 [0.01117961 0.98713618 0.00168421]
 [0.00868159 0.00137656 0.98994185]]
pi = [8.47029310e-01 1.52854585e-01 1.16105000e-04]
Iter 8: LL=-1315551.53 | Rates: N=0.97859, AF=0.09643, OLD=0.07140, YOUNG=0.03114
A =
[[0.99772442 0.00110903 0.00116655]
 [0.01123217 0.98693691 0.00183092]
 [0.00870743 0.00141701 0.98987556]]
pi = [8.46978056e-01 1.52989125e-01 3.28192194e-05]
Iter 9: LL=-1315547.09 | Rates: N=0.97859, AF=0.09643, OLD=0.07248, YOUNG=0.03138
A =
[[0.99772442 0.00107491 0.00120067]
 [0.01128066 0.9867336  0.00198574]
 [0.00873442 0.0014577  0.98980789]]
pi = [8.46934638e-01 1.53056032e-01 9.32988870e-06]
Iter 10: LL=-1315542.85 | Rates: N=0.97859, AF=0.09643, OLD=0.07355, YOUNG=0.03163
A =
[[0.99772443 0.00104188 0.00123369]
 [0.01132694 0.98652509 0.00214797]
 [0.00876116 0.00149779 0.98974105]]
pi = [8.46895044e-01 1.53102283e-01 2.67320796e-06]
Iter 11: LL=-1315538.82 | Rates: N=0.97859, AF=0.09643, OLD=0.07462, YOUNG=0.03187
A =
[[0.99772445 0.00101001 0.00126554]
 [0.01137188 0.98631088 0.00231724]
 [0.00878706 0.00153695 0.98967599]]
pi = [8.46857884e-01 1.53141343e-01 7.72587529e-07]
Iter 12: LL=-1315534.98 | Rates: N=0.97859, AF=0.09642, OLD=0.07569, YOUNG=0.03210
A =
[[9.97724475e-01 9.79317573e-04 1.29620752e-03]
 [1.14159854e-02 9.86090707e-01 2.49330752e-03]
 [8.81186050e-03 1.57501477e-03 9.89613125e-01]]
pi = [8.46822642e-01 1.53177133e-01 2.25294105e-07]
Iter 13: LL=-1315531.34 | Rates: N=0.97859, AF=0.09642, OLD=0.07676, YOUNG=0.03233
A =
[[9.97724505e-01 9.49822662e-04 1.32567207e-03]
 [1.14595883e-02 9.85864410e-01 2.67600176e-03]
 [8.83542336e-03 1.61192674e-03 9.89552650e-01]]
pi = [8.46789093e-01 1.53210840e-01 6.62958492e-08]
Iter 14: LL=-1315527.87 | Rates: N=0.97859, AF=0.09642, OLD=0.07784, YOUNG=0.03255
A =
[[9.97724538e-01 9.21517436e-04 1.35394494e-03]
 [1.15029451e-02 9.85631881e-01 2.86517417e-03]
 [8.85769453e-03 1.64766075e-03 9.89494645e-01]]
pi = [8.46757112e-01 1.53242868e-01 1.96869220e-08]
Iter 15: LL=-1315524.59 | Rates: N=0.97859, AF=0.09641, OLD=0.07892, YOUNG=0.03276
A =
[[9.97724571e-01 8.94385243e-04 1.38104398e-03]
 [1.15462660e-02 9.85393052e-01 3.06068147e-03]
 [8.87866417e-03 1.68220654e-03 9.89439129e-01]]
pi = [8.46726608e-01 1.53273386e-01 5.89983374e-09]
Final Global Rates (lambdas): [0.97858887 0.09641463 0.07891922 0.03275704]
Final transition matrix A:
[[9.97724571e-01 8.94385243e-04 1.38104398e-03]
 [1.15462660e-02 9.85393052e-01 3.06068147e-03]
 [8.87866417e-03 1.68220654e-03 9.89439129e-01]]
Final initial distribution pi:
[8.46726608e-01 1.53273386e-01 5.89983374e-09]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.5620  0.3604  0.4392  27970229.0   21800771.0  49636516.0
Archaic_young     0.6452  0.8039  0.7159  91538588.0   50337412.0  22324799.0
Modern            0.0000  0.0000  0.0000         0.0  808353000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         804720          540           1314
Archaic_old      1779        28068          48559
Archaic_young    1854        21163          92003

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5182  0.7070  0.5980
Archaic_young     0.5982  0.3588  0.4485

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         790965          281            531
Archaic_old      5232        70422          24925
Archaic_young    4165        65112          38367

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1660335.40 | Rates: N=0.97482, AF=0.09757, OLD=0.06197, YOUNG=0.04556
A =
[[0.9973742  0.0015359  0.0010899 ]
 [0.01057938 0.98814908 0.00127154]
 [0.01003739 0.00167155 0.98829106]]
pi = [0.94496864 0.03363985 0.02139151]
Iter 2: LL=-1321071.67 | Rates: N=0.97509, AF=0.09742, OLD=0.06446, YOUNG=0.04214
A =
[[0.99737835 0.00151819 0.00110346]
 [0.01091773 0.98773086 0.00135141]
 [0.00956428 0.00155988 0.98887584]]
pi = [0.94935856 0.03360121 0.01704024]
Iter 3: LL=-1321033.45 | Rates: N=0.97509, AF=0.09740, OLD=0.06758, YOUNG=0.03986
A =
[[0.99737821 0.00150684 0.00111495]
 [0.01126057 0.98729502 0.0014444 ]
 [0.00925322 0.00148113 0.98926565]]
pi = [0.94944731 0.03595875 0.01459394]
Iter 4: LL=-1321005.84 | Rates: N=0.97509, AF=0.09739, OLD=0.07022, YOUNG=0.03850
A =
[[0.99737742 0.00149253 0.00113005]
 [0.0115538  0.98687422 0.00157197]
 [0.00904428 0.0014362  0.98951953]]
pi = [0.94943273 0.03756062 0.01300665]
Iter 5: LL=-1320990.47 | Rates: N=0.97510, AF=0.09737, OLD=0.07226, YOUNG=0.03783
A =
[[0.99737648 0.00147493 0.00114859]
 [0.0117829  0.9864812  0.0017359 ]
 [0.00892371 0.00142389 0.9896524 ]]
pi = [0.94941873 0.038169   0.01241227]
Iter 6: LL=-1320981.89 | Rates: N=0.97510, AF=0.09735, OLD=0.07387, YOUNG=0.03760
A =
[[0.99737565 0.00145446 0.0011699 ]
 [0.01196133 0.98610604 0.00193263]
 [0.0088619  0.00143463 0.98970347]]
pi = [0.94941099 0.03780136 0.01278765]
Iter 7: LL=-1320975.80 | Rates: N=0.97510, AF=0.09734, OLD=0.07523, YOUNG=0.03760
A =
[[0.99737499 0.0014318  0.00119321]
 [0.0121067  0.98573565 0.00215765]
 [0.00883543 0.00145976 0.98970481]]
pi = [0.94940915 0.03648183 0.01410902]
Iter 8: LL=-1320970.41 | Rates: N=0.97510, AF=0.09734, OLD=0.07648, YOUNG=0.03771
A =
[[0.99737446 0.00140761 0.00121793]
 [0.01223201 0.98536049 0.0024075 ]
 [0.0088298  0.0014937  0.9896765 ]]
pi = [0.9494116 0.0341882 0.0164002]
Iter 9: LL=-1320965.15 | Rates: N=0.97510, AF=0.09733, OLD=0.07769, YOUNG=0.03786
A =
[[0.99737402 0.00138237 0.00124362]
 [0.01234559 0.98497433 0.00268008]
 [0.00883656 0.00153326 0.98963019]]
pi = [0.94941705 0.03089664 0.01968631]
Iter 10: LL=-1320959.86 | Rates: N=0.97510, AF=0.09732, OLD=0.07891, YOUNG=0.03805
A =
[[0.99737363 0.00135639 0.00126999]
 [0.01245265 0.98457309 0.00297426]
 [0.00885075 0.0015766  0.98957265]]
pi = [0.94942484 0.02667666 0.0238985 ]
Iter 11: LL=-1320954.52 | Rates: N=0.97510, AF=0.09732, OLD=0.08016, YOUNG=0.03823
A =
[[0.99737326 0.00132988 0.00129686]
 [0.01255651 0.98415396 0.00328953]
 [0.0088694  0.00162262 0.98950798]]
pi = [0.94943474 0.02178897 0.02877629]
Iter 12: LL=-1320949.13 | Rates: N=0.97510, AF=0.09731, OLD=0.08144, YOUNG=0.03843
A =
[[0.99737292 0.00130299 0.00132409]
 [0.01265932 0.98371491 0.00362577]
 [0.00889067 0.0016706  0.98943874]]
pi = [0.9494465  0.01670528 0.03384822]
Iter 13: LL=-1320943.69 | Rates: N=0.97510, AF=0.09730, OLD=0.08278, YOUNG=0.03862
A =
[[0.99737257 0.00127583 0.0013516 ]
 [0.01276246 0.98325445 0.00398309]
 [0.00891343 0.00172    0.98936657]]
pi = [0.94945936 0.01198526 0.03855538]
Iter 14: LL=-1320938.22 | Rates: N=0.97510, AF=0.09730, OLD=0.08417, YOUNG=0.03881
A =
[[0.99737223 0.00124848 0.00137929]
 [0.01286689 0.98277134 0.00436178]
 [0.00893697 0.0017704  0.98929263]]
pi = [0.94947194 0.00806686 0.0424612 ]
Iter 15: LL=-1320932.74 | Rates: N=0.97510, AF=0.09729, OLD=0.08561, YOUNG=0.03900
A =
[[0.99737188 0.00122103 0.00140709]
 [0.01297337 0.98226447 0.00476215]
 [0.00896078 0.00182144 0.98921778]]
pi = [0.94948273 0.00512806 0.0453892 ]
Final Global Rates (lambdas): [0.9751007  0.09729038 0.08560997 0.03899581]
Final transition matrix A:
[[0.99737188 0.00122103 0.00140709]
 [0.01297337 0.98226447 0.00476215]
 [0.00896078 0.00182144 0.98921778]]
Final initial distribution pi:
[0.94948273 0.00512806 0.0453892 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.5638  0.2627  0.3584  26147558.0   20229442.0  73391558.0
Archaic_young     0.5360  0.7939  0.6399  84481888.0   73137112.0  21931487.0
Modern            0.0000  0.0000  0.0000         0.0  796004000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         789946          196           1635
Archaic_old      3407        26169          71003
Archaic_young    2651        20012          84981

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5089  0.7212  0.5967
Archaic_young     0.6357  0.3644  0.4632

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         804115          218            432
Archaic_old      5071        64723          20958
Archaic_young    4458        62219          37806

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1665739.00 | Rates: N=0.97693, AF=0.09662, OLD=0.07010, YOUNG=0.05105
A =
[[0.99738368 0.00151224 0.00110408]
 [0.01140327 0.98719762 0.00139911]
 [0.01096581 0.00186425 0.98716994]]
pi = [0.76474185 0.12189262 0.11336553]
Iter 2: LL=-1324486.97 | Rates: N=0.97721, AF=0.09647, OLD=0.07418, YOUNG=0.04608
A =
[[0.99740606 0.00147308 0.00112087]
 [0.01176706 0.98676647 0.00146647]
 [0.01031108 0.00174559 0.98794334]]
pi = [0.75609632 0.10992446 0.13397922]
Iter 3: LL=-1324416.23 | Rates: N=0.97721, AF=0.09645, OLD=0.07896, YOUNG=0.04285
A =
[[0.99740649 0.00144439 0.00114912]
 [0.01220599 0.98625336 0.00154066]
 [0.00993123 0.00168641 0.98838237]]
pi = [0.75490989 0.09260145 0.15248866]
Iter 4: LL=-1324368.88 | Rates: N=0.97721, AF=0.09642, OLD=0.08281, YOUNG=0.04116
A =
[[0.99740514 0.00140914 0.00118572]
 [0.01256714 0.98578296 0.00164989]
 [0.0097054  0.00169652 0.98859808]]
pi = [0.75426835 0.07672345 0.1690082 ]
Iter 5: LL=-1324345.75 | Rates: N=0.97721, AF=0.09640, OLD=0.08569, YOUNG=0.04051
A =
[[0.99740386 0.00136831 0.00122783]
 [0.01284737 0.98535439 0.00179824]
 [0.00958419 0.0017598  0.988656  ]]
pi = [0.75387462 0.06340815 0.18271723]
Iter 6: LL=-1324333.04 | Rates: N=0.97721, AF=0.09638, OLD=0.08798, YOUNG=0.04041
A =
[[0.99740298 0.00132396 0.00127306]
 [0.01307846 0.9849404  0.00198114]
 [0.00951978 0.00185162 0.98862859]]
pi = [0.75365767 0.05229399 0.19404834]
Iter 7: LL=-1324323.28 | Rates: N=0.97721, AF=0.09637, OLD=0.08999, YOUNG=0.04055
A =
[[0.99740242 0.00127789 0.00131969]
 [0.01328412 0.98452236 0.00219352]
 [0.00948571 0.00195557 0.98855872]]
pi = [0.75354057 0.04292685 0.20353257]
Iter 8: LL=-1324314.23 | Rates: N=0.97721, AF=0.09636, OLD=0.09191, YOUNG=0.04080
A =
[[0.99740204 0.00123135 0.00136661]
 [0.01347676 0.98409068 0.00243256]
 [0.00946928 0.00206295 0.98846778]]
pi = [0.75347779 0.03498475 0.21153746]
Iter 9: LL=-1324305.42 | Rates: N=0.97721, AF=0.09636, OLD=0.09380, YOUNG=0.04108
A =
[[0.99740175 0.00118515 0.0014131 ]
 [0.01366246 0.98364012 0.00269743]
 [0.00946415 0.0021695  0.98836634]]
pi = [0.75344659 0.02824599 0.21830742]
Iter 10: LL=-1324296.76 | Rates: N=0.97721, AF=0.09635, OLD=0.09572, YOUNG=0.04138
A =
[[0.99740151 0.00113979 0.0014587 ]
 [0.01384438 0.98316714 0.00298847]
 [0.00946682 0.0022732  0.98825998]]
pi = [0.75343569 0.02254832 0.22401599]
Iter 11: LL=-1324288.24 | Rates: N=0.97721, AF=0.09634, OLD=0.09769, YOUNG=0.04168
A =
[[0.99740129 0.00109559 0.00150312]
 [0.01402453 0.98266871 0.00330676]
 [0.00947505 0.00237308 0.98815186]]
pi = [0.7534392  0.01776457 0.22879623]
Iter 12: LL=-1324279.87 | Rates: N=0.97721, AF=0.09633, OLD=0.09971, YOUNG=0.04198
A =
[[0.99740109 0.00105274 0.00154617]
 [0.01420447 0.98214174 0.00365379]
 [0.00948728 0.00246874 0.98804398]]
pi = [0.75345381 0.01378853 0.23275766]
Iter 13: LL=-1324271.64 | Rates: N=0.97721, AF=0.09633, OLD=0.10180, YOUNG=0.04227
A =
[[0.99740088 0.00101136 0.00158776]
 [0.0143857  0.98158296 0.00403134]
 [0.00950233 0.00256002 0.98793766]]
pi = [0.75347743 0.01052626 0.23599631]
Iter 14: LL=-1324263.55 | Rates: N=0.97721, AF=0.09632, OLD=0.10396, YOUNG=0.04256
A =
[[9.97400672e-01 9.71488229e-04 1.62784012e-03]
 [1.45697150e-02 9.80988762e-01 4.44152326e-03]
 [9.51930858e-03 2.64689686e-03 9.87833795e-01]]
pi = [0.75350862 0.00789078 0.2386006 ]
Iter 15: LL=-1324255.56 | Rates: N=0.97721, AF=0.09631, OLD=0.10621, YOUNG=0.04285
A =
[[9.97400452e-01 9.33144753e-04 1.66640335e-03]
 [1.47581184e-02 9.80355177e-01 4.88670435e-03]
 [9.53754157e-03 2.72942204e-03 9.87733036e-01]]
pi = [0.75354628 0.00579927 0.24065446]
Final Global Rates (lambdas): [0.97721315 0.09631165 0.10620745 0.0428489 ]
Final transition matrix A:
[[9.97400452e-01 9.33144753e-04 1.66640335e-03]
 [1.47581184e-02 9.80355177e-01 4.88670435e-03]
 [9.53754157e-03 2.72942204e-03 9.87733036e-01]]
Final initial distribution pi:
[0.75354628 0.00579927 0.24065446]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.5832  0.2547  0.3545  22850776.0   16333224.0  66867793.0
Archaic_young     0.5612  0.8292  0.6694  85629910.0   66960090.0  17635063.0
Modern            0.0000  0.0000  0.0000         0.0  808226000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         802869          300           1596
Archaic_old      3027        22893          64832
Archaic_young    2330        15991          86162

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5706  0.8396  0.6794
Archaic_young     0.6324  0.2936  0.4010

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         802157         1516            236
Archaic_old      2080        87412          15154
Archaic_young    1105        63635          26705

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1648036.92 | Rates: N=0.97624, AF=0.09506, OLD=0.05199, YOUNG=0.03059
A =
[[9.97961162e-01 1.40517109e-03 6.33667227e-04]
 [8.79808543e-03 9.90534651e-01 6.67263212e-04]
 [8.17013880e-03 1.38306870e-03 9.90446792e-01]]
pi = [0.9024383  0.05902283 0.03853887]
Iter 2: LL=-1308691.10 | Rates: N=0.97646, AF=0.09487, OLD=0.05377, YOUNG=0.02903
A =
[[9.97956067e-01 1.38091547e-03 6.63017294e-04]
 [9.14563173e-03 9.90134236e-01 7.20132478e-04]
 [7.61964738e-03 1.27287430e-03 9.91107478e-01]]
pi = [0.90485318 0.05698265 0.03816418]
Iter 3: LL=-1308674.27 | Rates: N=0.97646, AF=0.09486, OLD=0.05531, YOUNG=0.02846
A =
[[9.97955509e-01 1.35558603e-03 6.88905128e-04]
 [9.38588736e-03 9.89843988e-01 7.70124219e-04]
 [7.35521059e-03 1.22992055e-03 9.91414869e-01]]
pi = [0.90503501 0.05739554 0.03756945]
Iter 4: LL=-1308666.55 | Rates: N=0.97646, AF=0.09485, OLD=0.05645, YOUNG=0.02836
A =
[[9.97955172e-01 1.32827853e-03 7.16549679e-04]
 [9.55286761e-03 9.89622396e-01 8.24735906e-04]
 [7.22720664e-03 1.22141506e-03 9.91551378e-01]]
pi = [0.90507156 0.05821438 0.03671406]
Iter 5: LL=-1308662.04 | Rates: N=0.97646, AF=0.09484, OLD=0.05734, YOUNG=0.02849
A =
[[9.97954936e-01 1.29931071e-03 7.45753325e-04]
 [9.67579206e-03 9.89440144e-01 8.84064316e-04]
 [7.16967804e-03 1.23048294e-03 9.91599839e-01]]
pi = [0.905097   0.05900651 0.03589649]
Iter 6: LL=-1308658.42 | Rates: N=0.97646, AF=0.09484, OLD=0.05813, YOUNG=0.02871
A =
[[9.97954790e-01 1.26914563e-03 7.76064863e-04]
 [9.77444887e-03 9.89277856e-01 9.47695260e-04]
 [7.14806164e-03 1.24788023e-03 9.91604058e-01]]
pi = [0.90512044 0.05960137 0.03527819]
Iter 7: LL=-1308655.02 | Rates: N=0.97646, AF=0.09483, OLD=0.05886, YOUNG=0.02897
A =
[[9.97954703e-01 1.23819134e-03 8.07105614e-04]
 [9.86020513e-03 9.89124362e-01 1.01543267e-03]
 [7.14528303e-03 1.26903698e-03 9.91585680e-01]]
pi = [0.90514282 0.0599264  0.03493077]
Iter 8: LL=-1308651.67 | Rates: N=0.97646, AF=0.09483, OLD=0.05959, YOUNG=0.02923
A =
[[9.97954653e-01 1.20674688e-03 8.38600456e-04]
 [9.93933688e-03 9.88973312e-01 1.08735156e-03]
 [7.15277513e-03 1.29173847e-03 9.91555486e-01]]
pi = [0.90516415 0.05994893 0.03488692]
Iter 9: LL=-1308648.32 | Rates: N=0.97646, AF=0.09483, OLD=0.06034, YOUNG=0.02950
A =
[[9.97954623e-01 1.17502345e-03 8.70353588e-04]
 [1.00154030e-02 9.88820878e-01 1.16371948e-03]
 [7.16605118e-03 1.31488197e-03 9.91519067e-01]]
pi = [0.90518403 0.05965097 0.03516499]
Iter 10: LL=-1308644.98 | Rates: N=0.97646, AF=0.09482, OLD=0.06110, YOUNG=0.02975
A =
[[9.97954604e-01 1.14317379e-03 9.02221798e-04]
 [1.00905372e-02 9.88664533e-01 1.24493025e-03]
 [7.18264840e-03 1.33788495e-03 9.91479467e-01]]
pi = [0.90520182 0.0590185  0.03577968]
Iter 11: LL=-1308641.61 | Rates: N=0.97646, AF=0.09482, OLD=0.06189, YOUNG=0.03001
A =
[[9.97954591e-01 1.11131382e-03 9.34095321e-04]
 [1.01661025e-02 9.88502430e-01 1.33146764e-03]
 [7.20116225e-03 1.36041314e-03 9.91438425e-01]]
pi = [0.90521667 0.058037   0.03674633]
Iter 12: LL=-1308638.23 | Rates: N=0.97646, AF=0.09482, OLD=0.06271, YOUNG=0.03025
A =
[[9.97954578e-01 1.07953637e-03 9.65885595e-04]
 [1.02430231e-02 9.88333087e-01 1.42389026e-03]
 [7.22077350e-03 1.38225601e-03 9.91396970e-01]]
pi = [0.90522753 0.05669012 0.03808235]
Iter 13: LL=-1308634.83 | Rates: N=0.97646, AF=0.09481, OLD=0.06356, YOUNG=0.03049
A =
[[9.97954563e-01 1.04791957e-03 9.97517686e-04]
 [1.03219591e-02 9.88155212e-01 1.52282928e-03]
 [7.24100289e-03 1.40326889e-03 9.91355728e-01]]
pi = [0.90523321 0.05495989 0.0398069 ]
Iter 14: LL=-1308631.40 | Rates: N=0.97646, AF=0.09481, OLD=0.06445, YOUNG=0.03073
A =
[[0.99795454 0.00101653 0.00102893]
 [0.0104034  0.9879676  0.00162899]
 [0.00726158 0.00142335 0.99131508]]
pi = [0.9052324  0.05282838 0.04193922]
Iter 15: LL=-1308627.94 | Rates: N=0.97646, AF=0.09481, OLD=0.06539, YOUNG=0.03096
A =
[[9.97954515e-01 9.85435341e-04 1.06004997e-03]
 [1.04877476e-02 9.87769076e-01 1.74317614e-03]
 [7.28234314e-03 1.44240547e-03 9.91275251e-01]]
pi = [0.90522369 0.0502805  0.04449581]
Final Global Rates (lambdas): [0.97646106 0.09480595 0.06538801 0.03096452]
Final transition matrix A:
[[9.97954515e-01 9.85435341e-04 1.06004997e-03]
 [1.04877476e-02 9.87769076e-01 1.74317614e-03]
 [7.28234314e-03 1.44240547e-03 9.91275251e-01]]
Final initial distribution pi:
[0.90522369 0.0502805  0.04449581]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.6254  0.3780  0.4712  39193769.0   23472231.0  64483584.0
Archaic_young     0.5101  0.7443  0.6053  67497279.0   64829721.0  23185364.0
Modern            0.0000  0.0000  0.0000         0.0  805007000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         802095          658           1156
Archaic_old      1933        39361          63352
Archaic_young     979        22647          67819

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5184  0.7664  0.6185
Archaic_young     0.6253  0.3431  0.4431

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         778468         1727            389
Archaic_old      2662        80885          22545
Archaic_young    2021        72642          38661

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1642599.90 | Rates: N=0.96898, AF=0.09539, OLD=0.05591, YOUNG=0.03339
A =
[[9.97481971e-01 1.63715450e-03 8.80874852e-04]
 [9.64326767e-03 9.89485474e-01 8.71258287e-04]
 [8.59337004e-03 1.45864630e-03 9.89947984e-01]]
pi = [0.85051211 0.08022629 0.0692616 ]
Iter 2: LL=-1310254.47 | Rates: N=0.96927, AF=0.09519, OLD=0.05841, YOUNG=0.03095
A =
[[9.97464957e-01 1.60308262e-03 9.31960762e-04]
 [1.00903550e-02 9.88960287e-01 9.49358122e-04]
 [8.15310851e-03 1.34924337e-03 9.90497648e-01]]
pi = [0.85192462 0.06878268 0.07929271]
Iter 3: LL=-1310221.36 | Rates: N=0.96928, AF=0.09517, OLD=0.06074, YOUNG=0.02998
A =
[[9.97463084e-01 1.56366901e-03 9.73247082e-04]
 [1.03727133e-02 9.88596050e-01 1.03123713e-03]
 [7.94316237e-03 1.31651976e-03 9.90740318e-01]]
pi = [0.8521017  0.05971312 0.08818518]
Iter 4: LL=-1310205.69 | Rates: N=0.96928, AF=0.09516, OLD=0.06251, YOUNG=0.02972
A =
[[0.99746227 0.00152088 0.00101685]
 [0.01057666 0.98829384 0.0011295 ]
 [0.00784598 0.00132416 0.99082986]]
pi = [0.85219101 0.05194305 0.09586595]
Iter 5: LL=-1310196.41 | Rates: N=0.96928, AF=0.09515, OLD=0.06395, YOUNG=0.02981
A =
[[0.99746174 0.00147575 0.00106251]
 [0.01073779 0.98801987 0.00124234]
 [0.00780642 0.00135369 0.99083989]]
pi = [0.85223784 0.04488461 0.10287755]
Iter 6: LL=-1310188.81 | Rates: N=0.96928, AF=0.09514, OLD=0.06523, YOUNG=0.03005
A =
[[0.9974614  0.00142908 0.00110951]
 [0.01087873 0.98775349 0.00136778]
 [0.00779448 0.00139423 0.99081129]]
pi = [0.8522541  0.03819674 0.10954916]
Iter 7: LL=-1310181.56 | Rates: N=0.96928, AF=0.09513, OLD=0.06647, YOUNG=0.03035
A =
[[0.99746118 0.00138148 0.00115734]
 [0.01101194 0.98748317 0.00150489]
 [0.007796   0.00144017 0.99076383]]
pi = [0.85224905 0.03177575 0.1159752 ]
Iter 8: LL=-1310174.34 | Rates: N=0.96928, AF=0.09512, OLD=0.06773, YOUNG=0.03067
A =
[[0.99746102 0.00133338 0.0012056 ]
 [0.01114404 0.98720235 0.0016536 ]
 [0.00780436 0.0014887  0.99070694]]
pi = [0.85222733 0.02566004 0.12211263]
Iter 9: LL=-1310167.07 | Rates: N=0.96928, AF=0.09512, OLD=0.06902, YOUNG=0.03099
A =
[[0.9974609  0.00128505 0.00125405]
 [0.01127872 0.98690675 0.00181452]
 [0.00781635 0.00153823 0.99064542]]
pi = [0.85219065 0.01996683 0.12784252]
Iter 10: LL=-1310159.72 | Rates: N=0.96928, AF=0.09511, OLD=0.07038, YOUNG=0.03131
A =
[[0.99746082 0.00123671 0.00130247]
 [0.01141838 0.98659291 0.0019887 ]
 [0.00783031 0.00158779 0.9905819 ]]
pi = [0.85213981 0.01485148 0.13300871]
Iter 11: LL=-1310152.29 | Rates: N=0.96928, AF=0.09510, OLD=0.07180, YOUNG=0.03163
A =
[[0.99746076 0.00118851 0.00135074]
 [0.01156489 0.98625746 0.00217764]
 [0.00784533 0.00163666 0.99051801]]
pi = [0.85207606 0.01046959 0.13745435]
Iter 12: LL=-1310144.75 | Rates: N=0.96928, AF=0.09510, OLD=0.07331, YOUNG=0.03194
A =
[[0.99746071 0.00114058 0.0013987 ]
 [0.01172002 0.9858967  0.00238327]
 [0.00786086 0.00168426 0.99045488]]
pi = [0.85200194 0.00693483 0.14106323]
Iter 13: LL=-1310137.07 | Rates: N=0.96928, AF=0.09509, OLD=0.07492, YOUNG=0.03225
A =
[[0.99746069 0.00109304 0.00144627]
 [0.01188565 0.98550632 0.00260803]
 [0.00787656 0.00173009 0.99039336]]
pi = [0.85192138 0.00428097 0.14379765]
Iter 14: LL=-1310129.21 | Rates: N=0.96928, AF=0.09508, OLD=0.07664, YOUNG=0.03257
A =
[[0.99746067 0.00104596 0.00149336]
 [0.0120639  0.98508121 0.00285489]
 [0.00789222 0.00177368 0.99033409]]
pi = [0.85183918 0.00244527 0.14571555]
Iter 15: LL=-1310121.13 | Rates: N=0.96928, AF=0.09507, OLD=0.07850, YOUNG=0.03288
A =
[[0.99746067 0.00099943 0.0015399 ]
 [0.01225717 0.98461533 0.0031275 ]
 [0.00790778 0.00181462 0.9902776 ]]
pi = [0.85176004 0.00128467 0.14695529]
Final Global Rates (lambdas): [0.96928272 0.09507242 0.07849581 0.03287612]
Final transition matrix A:
[[0.99746067 0.00099943 0.0015399 ]
 [0.01225717 0.98461533 0.0031275 ]
 [0.00790778 0.00181462 0.9902776 ]]
Final initial distribution pi:
[0.85176004 0.00128467 0.14695529]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.5777  0.2552  0.3541  26806862.0   19594138.0  78219209.0
Archaic_young     0.5395  0.8221  0.6514  92289886.0   78789114.0  19971408.0
Modern            0.0000  0.0000  0.0000         0.0  782520000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         778402          608           1574
Archaic_old      2415        26939          76738
Archaic_young    1703        18854          92767

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5468  0.7912  0.6466
Archaic_young     0.7511  0.4288  0.5460

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         788173          257            454
Archaic_old      5303        75262          15531
Archaic_young    3918        62076          49026

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1650402.20 | Rates: N=0.97408, AF=0.09481, OLD=0.06095, YOUNG=0.03785
A =
[[9.97436224e-01 1.62566426e-03 9.38111700e-04]
 [1.04016098e-02 9.88564619e-01 1.03377138e-03]
 [9.20925707e-03 1.58895090e-03 9.89201792e-01]]
pi = [0.84874888 0.08181233 0.06943879]
Iter 2: LL=-1313372.26 | Rates: N=0.97436, AF=0.09463, OLD=0.06371, YOUNG=0.03467
A =
[[9.97439402e-01 1.59432489e-03 9.66272868e-04]
 [1.07677333e-02 9.88133570e-01 1.09869688e-03]
 [8.71607514e-03 1.47729024e-03 9.89806635e-01]]
pi = [0.84979174 0.07342107 0.07678719]
Iter 3: LL=-1313334.72 | Rates: N=0.97436, AF=0.09462, OLD=0.06611, YOUNG=0.03308
A =
[[9.97438669e-01 1.57263186e-03 9.88698890e-04]
 [1.10030980e-02 9.87834090e-01 1.16281171e-03]
 [8.51982451e-03 1.45126366e-03 9.90028912e-01]]
pi = [0.84981762 0.0652571  0.08492528]
Iter 4: LL=-1313319.48 | Rates: N=0.97436, AF=0.09460, OLD=0.06768, YOUNG=0.03238
A =
[[0.99743788 0.00155038 0.00101175]
 [0.01114169 0.98761402 0.00124429]
 [0.00844026 0.00147308 0.99008666]]
pi = [0.84982761 0.05662884 0.09354355]
Iter 5: LL=-1313313.48 | Rates: N=0.97436, AF=0.09459, OLD=0.06873, YOUNG=0.03214
A =
[[0.99743737 0.00152767 0.00103496]
 [0.01122608 0.98743347 0.00134046]
 [0.00841576 0.0015206  0.99006364]]
pi = [0.84983876 0.04798156 0.10217968]
Iter 6: LL=-1313310.09 | Rates: N=0.97436, AF=0.09459, OLD=0.06952, YOUNG=0.03212
A =
[[0.99743709 0.00150496 0.00105795]
 [0.01128511 0.98726729 0.0014476 ]
 [0.00841436 0.00157991 0.99000573]]
pi = [0.84984967 0.03973577 0.11041455]
Iter 7: LL=-1313307.34 | Rates: N=0.97436, AF=0.09459, OLD=0.07019, YOUNG=0.03220
A =
[[0.99743693 0.00148254 0.00108053]
 [0.01133343 0.98710329 0.00156328]
 [0.00842193 0.00164395 0.98993413]]
pi = [0.84985939 0.03220521 0.1179354 ]
Iter 8: LL=-1313304.77 | Rates: N=0.97436, AF=0.09458, OLD=0.07081, YOUNG=0.03231
A =
[[0.99743683 0.00146057 0.0011026 ]
 [0.01137759 0.98693626 0.00168615]
 [0.00843267 0.00170942 0.98985791]]
pi = [0.84986751 0.025583   0.12454948]
Iter 9: LL=-1313302.29 | Rates: N=0.97436, AF=0.09458, OLD=0.07140, YOUNG=0.03245
A =
[[0.99743675 0.00143909 0.00112415]
 [0.0114204  0.98676409 0.00181551]
 [0.0084443  0.00177482 0.98978088]]
pi = [0.84987395 0.01995095 0.1301751 ]
Iter 10: LL=-1313299.88 | Rates: N=0.97436, AF=0.09458, OLD=0.07198, YOUNG=0.03259
A =
[[0.99743668 0.00141814 0.00114518]
 [0.01146302 0.98658597 0.00195101]
 [0.00845595 0.00183948 0.98970457]]
pi = [0.84987877 0.01530041 0.13482083]
Iter 11: LL=-1313297.53 | Rates: N=0.97436, AF=0.09458, OLD=0.07257, YOUNG=0.03273
A =
[[0.99743661 0.00139769 0.0011657 ]
 [0.01150594 0.98640161 0.00209245]
 [0.00846729 0.0019031  0.9896296 ]]
pi = [0.84988212 0.01155874 0.13855914]
Iter 12: LL=-1313295.25 | Rates: N=0.97436, AF=0.09458, OLD=0.07315, YOUNG=0.03287
A =
[[0.99743654 0.00137774 0.00118572]
 [0.01154938 0.98621091 0.00223971]
 [0.00847824 0.00196554 0.98955622]]
pi = [0.84988422 0.00861573 0.14150005]
Iter 13: LL=-1313293.02 | Rates: N=0.97436, AF=0.09457, OLD=0.07374, YOUNG=0.03301
A =
[[0.99743647 0.00135826 0.00120527]
 [0.01159345 0.98601383 0.00239272]
 [0.00848876 0.00202673 0.98948451]]
pi = [0.84988531 0.0063459  0.14376879]
Iter 14: LL=-1313290.84 | Rates: N=0.97436, AF=0.09457, OLD=0.07434, YOUNG=0.03315
A =
[[0.99743639 0.00133923 0.00122437]
 [0.0116382  0.98581038 0.00255142]
 [0.00849887 0.00208664 0.98941449]]
pi = [0.84988561 0.00462472 0.14548966]
Iter 15: LL=-1313288.72 | Rates: N=0.97436, AF=0.09457, OLD=0.07494, YOUNG=0.03329
A =
[[0.99743631 0.00132064 0.00124305]
 [0.01168369 0.98560054 0.00271577]
 [0.00850859 0.00214526 0.98934615]]
pi = [0.84988535 0.00333858 0.14677608]
Final Global Rates (lambdas): [0.97436294 0.09456844 0.07493865 0.03328774]
Final transition matrix A:
[[0.99743631 0.00132064 0.00124305]
 [0.01168369 0.98560054 0.00271577]
 [0.00850859 0.00214526 0.98934615]]
Final initial distribution pi:
[0.84988535 0.00333858 0.14677608]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.6063  0.5133  0.5559  48810894.0   31693106.0  46281640.0
Archaic_young     0.6410  0.7240  0.6800  82441155.0   46179845.0  31422232.0
Modern            0.0000  0.0000  0.0000         0.0  790875000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         786601         1034           1249
Archaic_old      2561        49029          44506
Archaic_young    1713        30441          82866

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5361  0.7435  0.6230
Archaic_young     0.6701  0.3923  0.4949

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         794585          338            393
Archaic_old      5676        71379          19985
Archaic_young    4390        61336          41918

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1656863.90 | Rates: N=0.97309, AF=0.09570, OLD=0.06775, YOUNG=0.04340
A =
[[0.99729338 0.00168404 0.00102259]
 [0.0113576  0.98745133 0.00119107]
 [0.01026881 0.00175855 0.98797263]]
pi = [0.94881947 0.03090429 0.02027624]
Iter 2: LL=-1320038.05 | Rates: N=0.97338, AF=0.09555, OLD=0.07111, YOUNG=0.03971
A =
[[0.99730449 0.00163473 0.00106079]
 [0.0118036  0.98690048 0.00129592]
 [0.00964589 0.00160346 0.98875065]]
pi = [0.95770437 0.02539763 0.016898  ]
Iter 3: LL=-1319989.49 | Rates: N=0.97339, AF=0.09552, OLD=0.07452, YOUNG=0.03800
A =
[[0.99730387 0.00159647 0.00109966]
 [0.01215156 0.9864426  0.00140584]
 [0.00939181 0.00153841 0.98906978]]
pi = [0.95927122 0.023454   0.01727478]
Iter 4: LL=-1319965.34 | Rates: N=0.97339, AF=0.09550, OLD=0.07715, YOUNG=0.03737
A =
[[0.99730258 0.00155338 0.00114404]
 [0.01240182 0.98605384 0.00154434]
 [0.0092841  0.0015248  0.9891911 ]]
pi = [0.95957247 0.02094218 0.01948535]
Iter 5: LL=-1319952.37 | Rates: N=0.97339, AF=0.09548, OLD=0.07924, YOUNG=0.03732
A =
[[0.99730156 0.00150635 0.00119209]
 [0.01259144 0.98569965 0.0017089 ]
 [0.0092508  0.00154022 0.98920898]]
pi = [0.959484   0.01729679 0.02321921]
Iter 6: LL=-1319942.67 | Rates: N=0.97339, AF=0.09547, OLD=0.08109, YOUNG=0.03752
A =
[[0.99730085 0.00145694 0.00124221]
 [0.01275096 0.98535369 0.00189535]
 [0.00925244 0.00156967 0.98917789]]
pi = [0.95912475 0.01284619 0.02802907]
Iter 7: LL=-1319933.68 | Rates: N=0.97339, AF=0.09546, OLD=0.08286, YOUNG=0.03784
A =
[[0.99730034 0.00140632 0.00129334]
 [0.0128974  0.98500153 0.00210106]
 [0.00927055 0.00160524 0.98912421]]
pi = [0.95856792 0.00840633 0.03302575]
Iter 8: LL=-1319924.82 | Rates: N=0.97339, AF=0.09545, OLD=0.08464, YOUNG=0.03820
A =
[[0.99729992 0.00135526 0.00134483]
 [0.0130391  0.98463582 0.00232509]
 [0.00929685 0.00164309 0.98906006]]
pi = [0.95796761 0.00482281 0.03720958]
Iter 9: LL=-1319915.98 | Rates: N=0.97339, AF=0.09544, OLD=0.08648, YOUNG=0.03857
A =
[[0.99729953 0.00130424 0.00139623]
 [0.01318021 0.98425223 0.00256757]
 [0.00932743 0.00168132 0.98899124]]
pi = [0.95747432 0.00245637 0.0400693 ]
Iter 10: LL=-1319907.13 | Rates: N=0.97339, AF=0.09543, OLD=0.08840, YOUNG=0.03895
A =
[[0.99729916 0.00125361 0.00144723]
 [0.01332319 0.98384757 0.00282925]
 [0.0093602  0.00171899 0.98892081]]
pi = [0.95714777 0.00113504 0.04171719]
Iter 11: LL=-1319898.27 | Rates: N=0.97339, AF=0.09542, OLD=0.09041, YOUNG=0.03932
A =
[[0.99729879 0.00120361 0.0014976 ]
 [0.01346975 0.98341911 0.00311114]
 [0.00939392 0.00175553 0.98885056]]
pi = [9.56968572e-01 4.85844409e-04 4.25455839e-02]
Iter 12: LL=-1319889.41 | Rates: N=0.97339, AF=0.09541, OLD=0.09253, YOUNG=0.03968
A =
[[0.99729842 0.00115443 0.00154715]
 [0.01362117 0.98296448 0.00341435]
 [0.00942784 0.00179058 0.98878159]]
pi = [9.56891029e-01 1.95629042e-04 4.29133420e-02]
Iter 13: LL=-1319880.54 | Rates: N=0.97339, AF=0.09539, OLD=0.09477, YOUNG=0.04004
A =
[[0.99729803 0.00110622 0.00159574]
 [0.01377839 0.98248162 0.00373999]
 [0.0094615  0.00182389 0.9887146 ]]
pi = [9.56875434e-01 7.48426625e-05 4.30497235e-02]
Iter 14: LL=-1319871.66 | Rates: N=0.97339, AF=0.09538, OLD=0.09714, YOUNG=0.04039
A =
[[0.99729764 0.00105911 0.00164325]
 [0.01394212 0.98196872 0.00408916]
 [0.00949466 0.00185531 0.98865004]]
pi = [9.56895802e-01 2.73753508e-05 4.30768228e-02]
Iter 15: LL=-1319862.79 | Rates: N=0.97339, AF=0.09537, OLD=0.09965, YOUNG=0.04074
A =
[[0.99729724 0.00101319 0.00168957]
 [0.014113   0.98142401 0.00446299]
 [0.00952711 0.0018847  0.9885882 ]]
pi = [9.56937228e-01 9.61263963e-06 4.30531595e-02]
Final Global Rates (lambdas): [0.97339304 0.09536783 0.0996455  0.04073569]
Final transition matrix A:
[[0.99729724 0.00101319 0.00168957]
 [0.014113   0.98142401 0.00446299]
 [0.00952711 0.0018847  0.9885882 ]]
Final initial distribution pi:
[9.56937228e-01 9.61263963e-06 4.30531595e-02]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.6735  0.2656  0.3810  25480087.0   12353913.0  70450797.0
Archaic_young     0.5685  0.8708  0.6879  92660975.0   70324025.0  13752400.0
Modern            0.0000  0.0000  0.0000         0.0  799181000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         793341          346           1629
Archaic_old      3338        25538          68164
Archaic_young    2502        11950          93192

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5468  0.8633  0.6695
Archaic_young     0.7144  0.3049  0.4274

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         815627         1593            208
Archaic_old      2180        78182          10765
Archaic_young    1199        62518          27728

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1664387.68 | Rates: N=0.98811, AF=0.09557, OLD=0.05745, YOUNG=0.02946
A =
[[9.98039943e-01 1.43076699e-03 5.29290231e-04]
 [9.53247626e-03 9.89832856e-01 6.34667315e-04]
 [7.92111921e-03 1.48127504e-03 9.90597606e-01]]
pi = [0.79703651 0.12984403 0.07311946]
Iter 2: LL=-1313194.95 | Rates: N=0.98834, AF=0.09539, OLD=0.05972, YOUNG=0.02810
A =
[[9.98039881e-01 1.40104881e-03 5.59070612e-04]
 [1.00345924e-02 9.89244332e-01 7.21075437e-04]
 [7.15265899e-03 1.40977130e-03 9.91437570e-01]]
pi = [0.79698102 0.12850872 0.07451026]
Iter 3: LL=-1313174.07 | Rates: N=0.98834, AF=0.09537, OLD=0.06155, YOUNG=0.02785
A =
[[9.98038797e-01 1.37584763e-03 5.85355029e-04]
 [1.03726285e-02 9.88814036e-01 8.13335010e-04]
 [6.84550549e-03 1.45522950e-03 9.91699265e-01]]
pi = [0.79672486 0.12780122 0.07547393]
Iter 4: LL=-1313164.19 | Rates: N=0.98834, AF=0.09536, OLD=0.06292, YOUNG=0.02797
A =
[[9.98037993e-01 1.34809993e-03 6.13906934e-04]
 [1.06146255e-02 9.88463278e-01 9.22096633e-04]
 [6.70601414e-03 1.54418234e-03 9.91749804e-01]]
pi = [0.79647834 0.12648968 0.07703198]
Iter 5: LL=-1313156.99 | Rates: N=0.98834, AF=0.09535, OLD=0.06407, YOUNG=0.02821
A =
[[9.98037467e-01 1.31845687e-03 6.44076565e-04]
 [1.08040563e-02 9.88149432e-01 1.04651208e-03]
 [6.64645476e-03 1.64960659e-03 9.91703939e-01]]
pi = [0.79628405 0.12445685 0.0792591 ]
Iter 6: LL=-1313150.45 | Rates: N=0.98834, AF=0.09534, OLD=0.06514, YOUNG=0.02848
A =
[[9.98037115e-01 1.28780610e-03 6.75078733e-04]
 [1.09641336e-02 9.87849950e-01 1.18591636e-03]
 [6.62861291e-03 1.75937223e-03 9.91612015e-01]]
pi = [0.7961253  0.12173755 0.08213715]
Iter 7: LL=-1313144.14 | Rates: N=0.98834, AF=0.09534, OLD=0.06619, YOUNG=0.02875
A =
[[9.98036863e-01 1.25677820e-03 7.06358570e-04]
 [1.11068493e-02 9.87552901e-01 1.34025023e-03]
 [6.63451462e-03 1.86795701e-03 9.91497528e-01]]
pi = [0.79598824 0.11839684 0.08561492]
Iter 8: LL=-1313137.98 | Rates: N=0.98834, AF=0.09533, OLD=0.06725, YOUNG=0.02901
A =
[[9.98036668e-01 1.22577886e-03 7.37553383e-04]
 [1.12386326e-02 9.87251572e-01 1.50979537e-03]
 [6.65491208e-03 1.97278495e-03 9.91372303e-01]]
pi = [0.7958659  0.11451356 0.08962054]
Iter 9: LL=-1313131.95 | Rates: N=0.98834, AF=0.09533, OLD=0.06832, YOUNG=0.02927
A =
[[9.98036505e-01 1.19506583e-03 7.68428939e-04]
 [1.13632417e-02 9.86941770e-01 1.69498812e-03]
 [6.68457057e-03 2.07264536e-03 9.91242784e-01]]
pi = [0.79575529 0.11017773 0.09406698]
Iter 10: LL=-1313126.03 | Rates: N=0.98834, AF=0.09532, OLD=0.06942, YOUNG=0.02951
A =
[[9.98036362e-01 1.16480270e-03 7.98835122e-04]
 [1.14831441e-02 9.86620518e-01 1.89633761e-03]
 [6.72024921e-03 2.16699843e-03 9.91112752e-01]]
pi = [0.79565517 0.10548697 0.09885787]
Iter 11: LL=-1313120.22 | Rates: N=0.98835, AF=0.09532, OLD=0.07054, YOUNG=0.02975
A =
[[9.98036230e-01 1.13509143e-03 8.28678364e-04]
 [1.16001705e-02 9.86285428e-01 2.11440142e-03]
 [6.75978716e-03 2.25565234e-03 9.90984561e-01]]
pi = [0.79556483 0.10054051 0.10389466]
Iter 12: LL=-1313114.52 | Rates: N=0.98835, AF=0.09531, OLD=0.07170, YOUNG=0.02999
A =
[[9.98036104e-01 1.10599206e-03 8.57904371e-04]
 [1.17158249e-02 9.85934390e-01 2.34978542e-03]
 [6.80166671e-03 2.33859995e-03 9.90859733e-01]]
pi = [0.79548364 0.09543205 0.10908431]
Iter 13: LL=-1313108.90 | Rates: N=0.98835, AF=0.09531, OLD=0.07289, YOUNG=0.03023
A =
[[9.98035978e-01 1.07753536e-03 8.86486715e-04]
 [1.18314257e-02 9.85565425e-01 2.60314909e-03]
 [6.84479283e-03 2.41592795e-03 9.90739279e-01]]
pi = [0.79541082 0.09024302 0.11434616]
Iter 14: LL=-1313103.37 | Rates: N=0.98835, AF=0.09530, OLD=0.07412, YOUNG=0.03047
A =
[[9.98035850e-01 1.04973143e-03 9.14418764e-04]
 [1.19481598e-02 9.85176634e-01 2.87520652e-03]
 [6.88837522e-03 2.48776210e-03 9.90623863e-01]]
pi = [0.79534553 0.0850376  0.11961688]
Iter 15: LL=-1313097.90 | Rates: N=0.98835, AF=0.09530, OLD=0.07539, YOUNG=0.03071
A =
[[9.98035716e-01 1.02257619e-03 9.41707563e-04]
 [1.20670897e-02 9.84766192e-01 3.16671819e-03]
 [6.93186039e-03 2.55423309e-03 9.90513907e-01]]
pi = [0.79528704 0.07986029 0.12485267]
Final Global Rates (lambdas): [0.98834652 0.09529659 0.07539147 0.0307137 ]
Final transition matrix A:
[[9.98035716e-01 1.02257619e-03 9.41707563e-04]
 [1.20670897e-02 9.84766192e-01 3.16671819e-03]
 [6.93186039e-03 2.55423309e-03 9.90513907e-01]]
Final initial distribution pi:
[0.79528704 0.07986029 0.12485267]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old        0.667  0.4528  0.5394  40807290.0   20370710.0  49319671.0
Archaic_young      0.589  0.7808  0.6715  70806602.0   49400398.0  19876041.0
Modern             0.000  0.0000  0.0000         0.0  818615000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         815559          870            999
Archaic_old      1978        41027          48122
Archaic_young    1078        19281          71086

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5347  0.8434  0.6545
Archaic_young     0.8195  0.3971  0.5350

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         796459          181            355
Archaic_old      5547        74820           9314
Archaic_young    3733        64861          44730

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1655247.43 | Rates: N=0.97563, AF=0.09560, OLD=0.06396, YOUNG=0.03294
A =
[[9.97521628e-01 1.72337757e-03 7.54994655e-04]
 [1.06939898e-02 9.88487772e-01 8.18238235e-04]
 [8.90262026e-03 1.51241512e-03 9.89584965e-01]]
pi = [0.85020252 0.07835423 0.07144325]
Iter 2: LL=-1316039.66 | Rates: N=0.97593, AF=0.09538, OLD=0.06784, YOUNG=0.03078
A =
[[9.97510119e-01 1.67391548e-03 8.15965680e-04]
 [1.13976605e-02 9.87636933e-01 9.65406723e-04]
 [8.18686647e-03 1.32810801e-03 9.90485026e-01]]
pi = [0.85047693 0.05984838 0.0896747 ]
Iter 3: LL=-1315991.73 | Rates: N=0.97594, AF=0.09534, OLD=0.07102, YOUNG=0.03038
A =
[[9.97507287e-01 1.62538549e-03 8.67327400e-04]
 [1.18012209e-02 9.87065778e-01 1.13300080e-03]
 [7.98935729e-03 1.28079044e-03 9.90729852e-01]]
pi = [0.85036047 0.04657487 0.10306467]
Iter 4: LL=-1315969.39 | Rates: N=0.97594, AF=0.09531, OLD=0.07345, YOUNG=0.03058
A =
[[9.97505713e-01 1.57309582e-03 9.21190682e-04]
 [1.20463901e-02 9.86620889e-01 1.33272080e-03]
 [7.97999765e-03 1.28583336e-03 9.90734169e-01]]
pi = [0.85031678 0.03692936 0.11275387]
Iter 5: LL=-1315953.51 | Rates: N=0.97594, AF=0.09530, OLD=0.07554, YOUNG=0.03099
A =
[[9.97504800e-01 1.51849021e-03 9.76709783e-04]
 [1.22081178e-02 9.86232635e-01 1.55924762e-03]
 [8.04632656e-03 1.31319090e-03 9.90640483e-01]]
pi = [0.85030722 0.02942539 0.12026739]
Iter 6: LL=-1315939.37 | Rates: N=0.97594, AF=0.09528, OLD=0.07752, YOUNG=0.03143
A =
[[0.99750426 0.00146306 0.00103268]
 [0.01232541 0.98586579 0.0018088 ]
 [0.00814127 0.00135086 0.99050787]]
pi = [0.85030967 0.0231792  0.12651113]
Iter 7: LL=-1315926.03 | Rates: N=0.97594, AF=0.09527, OLD=0.07949, YOUNG=0.03188
A =
[[0.9975039  0.00140777 0.00108833]
 [0.01241892 0.98550149 0.0020796 ]
 [0.00824425 0.00139394 0.99036181]]
pi = [0.85031615 0.01777842 0.13190543]
Iter 8: LL=-1315913.24 | Rates: N=0.97595, AF=0.09526, OLD=0.08149, YOUNG=0.03232
A =
[[0.99750363 0.00135315 0.00114321]
 [0.01250065 0.98512821 0.00237114]
 [0.00834568 0.00144027 0.99021405]]
pi = [0.85032393 0.01308498 0.13659109]
Iter 9: LL=-1315900.92 | Rates: N=0.97595, AF=0.09525, OLD=0.08355, YOUNG=0.03274
A =
[[0.99750341 0.0012995  0.00119708]
 [0.01257843 0.98473783 0.00268374]
 [0.008441   0.00148872 0.99007028]]
pi = [0.85033226 0.00910891 0.14055883]
Iter 10: LL=-1315888.98 | Rates: N=0.97595, AF=0.09524, OLD=0.08570, YOUNG=0.03316
A =
[[0.9975032  0.00124698 0.00124982]
 [0.01265786 0.98432384 0.0030183 ]
 [0.00852815 0.0015386  0.98993325]]
pi = [0.85034132 0.00591391 0.14374476]
Iter 11: LL=-1315877.34 | Rates: N=0.97595, AF=0.09523, OLD=0.08794, YOUNG=0.03356
A =
[[0.99750298 0.00119567 0.00130136]
 [0.01274316 0.98388059 0.00337625]
 [0.00860643 0.00158943 0.98980415]]
pi = [0.85035169 0.00353546 0.14611284]
Iter 12: LL=-1315865.94 | Rates: N=0.97595, AF=0.09522, OLD=0.09029, YOUNG=0.03396
A =
[[0.99750273 0.00114561 0.00135166]
 [0.01283764 0.9834029  0.00375945]
 [0.00867591 0.00164083 0.98968326]]
pi = [0.85036397 0.00192577 0.14771026]
Iter 13: LL=-1315854.71 | Rates: N=0.97595, AF=0.09521, OLD=0.09276, YOUNG=0.03435
A =
[[0.99750245 0.00109685 0.0014007 ]
 [0.0129439  0.9828859  0.0041702 ]
 [0.00873711 0.00169254 0.98957035]]
pi = [0.85037849 0.00094846 0.14867305]
Iter 14: LL=-1315843.60 | Rates: N=0.97595, AF=0.09519, OLD=0.09538, YOUNG=0.03473
A =
[[0.99750211 0.00104943 0.00144846]
 [0.01306394 0.98232499 0.00461107]
 [0.00879076 0.00174436 0.98946489]]
pi = [8.50395177e-01 4.20356544e-04 1.49184467e-01]
Iter 15: LL=-1315832.56 | Rates: N=0.97595, AF=0.09518, OLD=0.09816, YOUNG=0.03511
A =
[[0.99750172 0.00100339 0.00149489]
 [0.01319935 0.98171584 0.00508481]
 [0.00883768 0.00179613 0.98936619]]
pi = [8.50413637e-01 1.67262142e-04 1.49419101e-01]
Final Global Rates (lambdas): [0.97594946 0.09518159 0.0981582  0.03510909]
Final transition matrix A:
[[0.99750172 0.00100339 0.00149489]
 [0.01319935 0.98171584 0.00508481]
 [0.00883768 0.00179613 0.98936619]]
Final initial distribution pi:
[8.50413637e-01 1.67262142e-04 1.49419101e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.6632  0.2949  0.4083  26149142.0   13280858.0  62509926.0
Archaic_young     0.6113  0.8724  0.7189  97937130.0   62282870.0  14324164.0
Modern            0.0000  0.0000  0.0000         0.0  800350000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         795280          200           1515
Archaic_old      3235        26175          60271
Archaic_young    1835        13055          98434

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5222  0.7985  0.6314
Archaic_young     0.8175  0.4752  0.6010

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         805469          252            438
Archaic_old      5159        62220          11442
Archaic_young    4143        56575          54302

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1659925.92 | Rates: N=0.97788, AF=0.09590, OLD=0.06798, YOUNG=0.03522
A =
[[9.97539826e-01 1.62152624e-03 8.38647497e-04]
 [1.16102921e-02 9.87362883e-01 1.02682446e-03]
 [9.14870250e-03 1.56552716e-03 9.89285770e-01]]
pi = [0.79763743 0.12712717 0.07523539]
Iter 2: LL=-1318395.46 | Rates: N=0.97816, AF=0.09576, OLD=0.07295, YOUNG=0.03212
A =
[[9.97552350e-01 1.54130571e-03 9.06344147e-04]
 [1.22947237e-02 9.86526575e-01 1.17870087e-03]
 [8.49665886e-03 1.40703394e-03 9.90096307e-01]]
pi = [0.79762213 0.14057526 0.0618026 ]
Iter 3: LL=-1318330.93 | Rates: N=0.97816, AF=0.09572, OLD=0.07716, YOUNG=0.03134
A =
[[9.97551119e-01 1.47623022e-03 9.72651095e-04]
 [1.27033847e-02 9.85945301e-01 1.35131393e-03]
 [8.38042512e-03 1.40743661e-03 9.90212138e-01]]
pi = [0.79748861 0.15704206 0.04546933]
Iter 4: LL=-1318300.62 | Rates: N=0.97816, AF=0.09569, OLD=0.08054, YOUNG=0.03144
A =
[[0.99754971 0.00140784 0.00104244]
 [0.01298602 0.98544108 0.0015729 ]
 [0.00840037 0.00146282 0.9901368 ]]
pi = [0.79730272 0.17076617 0.03193111]
Iter 5: LL=-1318277.92 | Rates: N=0.97816, AF=0.09565, OLD=0.08366, YOUNG=0.03184
A =
[[0.99754869 0.0013386  0.00111272]
 [0.0132202  0.98493896 0.00184085]
 [0.00846444 0.00153626 0.98999931]]
pi = [0.79714339 0.1807052  0.02215141]
Iter 6: LL=-1318256.65 | Rates: N=0.97817, AF=0.09562, OLD=0.08682, YOUNG=0.03234
A =
[[0.99754785 0.0012704  0.00118174]
 [0.01343728 0.98440804 0.00215468]
 [0.00854269 0.00161285 0.98984447]]
pi = [0.79702381 0.18748288 0.01549331]
Iter 7: LL=-1318235.80 | Rates: N=0.97817, AF=0.09559, OLD=0.09010, YOUNG=0.03286
A =
[[0.99754719 0.00120421 0.0012486 ]
 [0.0136474  0.98383599 0.00251662]
 [0.00862543 0.00168671 0.98968786]]
pi = [0.79693735 0.19199856 0.0110641 ]
Iter 8: LL=-1318215.35 | Rates: N=0.97817, AF=0.09557, OLD=0.09352, YOUNG=0.03339
A =
[[0.99754674 0.00114063 0.00131263]
 [0.01385196 0.9832183  0.00292974]
 [0.00870939 0.00175547 0.98953514]]
pi = [0.79687564 0.19498827 0.00813608]
Iter 9: LL=-1318195.49 | Rates: N=0.97817, AF=0.09554, OLD=0.09707, YOUNG=0.03391
A =
[[0.99754648 0.0010802  0.00137332]
 [0.01404997 0.98255331 0.00339671]
 [0.00879312 0.00181807 0.98938881]]
pi = [0.79683278 0.19696748 0.00619975]
Iter 10: LL=-1318176.39 | Rates: N=0.97817, AF=0.09552, OLD=0.10076, YOUNG=0.03442
A =
[[0.99754633 0.00102337 0.0014303 ]
 [0.01424117 0.98183894 0.00391988]
 [0.00887554 0.00187399 0.98925047]]
pi = [0.79680521 0.19827469 0.0049201 ]
Iter 11: LL=-1318158.10 | Rates: N=0.97817, AF=0.09550, OLD=0.10460, YOUNG=0.03492
A =
[[9.97546211e-01 9.70360053e-04 1.48342906e-03]
 [1.44269075e-02 9.81071325e-01 4.50176701e-03]
 [8.95567432e-03 1.92304903e-03 9.89121277e-01]]
pi = [0.79679074 0.1991253  0.00408396]
Iter 12: LL=-1318140.61 | Rates: N=0.97817, AF=0.09548, OLD=0.10861, YOUNG=0.03541
A =
[[9.97546042e-01 9.21186623e-04 1.53277168e-03]
 [1.46098247e-02 9.80244861e-01 5.14531414e-03]
 [9.03271248e-03 1.96548330e-03 9.89001804e-01]]
pi = [0.79678776 0.1996528  0.00355944]
Iter 13: LL=-1318123.84 | Rates: N=0.97817, AF=0.09546, OLD=0.11281, YOUNG=0.03590
A =
[[9.97545772e-01 8.75698116e-04 1.57853021e-03]
 [1.47934300e-02 9.79352859e-01 5.85371060e-03]
 [9.10600013e-03 2.00188598e-03 9.88892114e-01]]
pi = [0.79679491 0.19993573 0.00326936]
Iter 14: LL=-1318107.70 | Rates: N=0.97816, AF=0.09544, OLD=0.11723, YOUNG=0.03637
A =
[[9.97545364e-01 8.33639682e-04 1.62099582e-03]
 [1.49814851e-02 9.78388682e-01 6.62983250e-03]
 [9.17507166e-03 2.03308030e-03 9.88791848e-01]]
pi = [0.79681112 0.20001302 0.00317586]
Iter 15: LL=-1318092.10 | Rates: N=0.97816, AF=0.09542, OLD=0.12187, YOUNG=0.03683
A =
[[9.97544798e-01 7.94700210e-04 1.66050178e-03]
 [1.51774378e-02 9.77346986e-01 7.47557617e-03]
 [9.23967545e-03 2.05993638e-03 9.88700388e-01]]
pi = [0.79683558 0.19989032 0.0032741 ]
Final Global Rates (lambdas): [0.97816344 0.09542121 0.12187251 0.03682816]
Final transition matrix A:
[[9.97544798e-01 7.94700210e-04 1.66050178e-03]
 [1.51774378e-02 9.77346986e-01 7.47557617e-03]
 [9.23967545e-03 2.05993638e-03 9.88700388e-01]]
Final initial distribution pi:
[0.79683558 0.19989032 0.0032741 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.1_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.6560  0.2314  0.3421   18012361.0    9444639.0  59836633.0
Archaic_young     0.6328  0.9092  0.7462  103524405.0   60080595.0  10338982.0
Modern            0.0000  0.0000  0.0000          0.0  808938000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         804097          421           1641
Archaic_old      2839        18058          57924
Archaic_young    2002         8978         104040

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2457  0.1226  0.1636
Archaic_young     0.6846  0.8332  0.7516

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         721671          259           1728
Archaic_old      1270        10067          71342
Archaic_young    2161        30650         160852

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1604520.45 | Rates: N=0.94117, AF=0.09659, OLD=0.04603, YOUNG=0.03587
A =
[[0.99736905 0.00101987 0.00161108]
 [0.0069526  0.99143497 0.00161243]
 [0.00717238 0.00104419 0.99178343]]
pi = [0.70050541 0.1130463  0.18644829]
Iter 2: LL=-1297594.62 | Rates: N=0.94141, AF=0.09629, OLD=0.04951, YOUNG=0.03400
A =
[[0.99735196 0.00103414 0.00161391]
 [0.00723866 0.99111154 0.0016498 ]
 [0.00702485 0.00100576 0.99196939]]
pi = [0.7002765  0.10797669 0.19174681]
Iter 3: LL=-1297546.95 | Rates: N=0.94142, AF=0.09627, OLD=0.05341, YOUNG=0.03225
A =
[[9.97350876e-01 1.03983138e-03 1.60929294e-03]
 [7.60388621e-03 9.90681902e-01 1.71421225e-03]
 [6.82394446e-03 9.61450246e-04 9.92214605e-01]]
pi = [0.70027938 0.1030142  0.19670642]
Iter 4: LL=-1297502.08 | Rates: N=0.94142, AF=0.09625, OLD=0.05696, YOUNG=0.03109
A =
[[9.97349928e-01 1.03894086e-03 1.61113092e-03]
 [8.00606440e-03 9.90174649e-01 1.81928672e-03]
 [6.63738165e-03 9.28136041e-04 9.92434482e-01]]
pi = [0.70028179 0.09881212 0.20090609]
Iter 5: LL=-1297473.77 | Rates: N=0.94143, AF=0.09622, OLD=0.05983, YOUNG=0.03054
A =
[[9.97348581e-01 1.02935331e-03 1.62206593e-03]
 [8.38830245e-03 9.89640515e-01 1.97118270e-03]
 [6.49642922e-03 9.12739781e-04 9.92590831e-01]]
pi = [0.70028188 0.09531182 0.2044063 ]
Iter 6: LL=-1297458.24 | Rates: N=0.94143, AF=0.09620, OLD=0.06214, YOUNG=0.03038
A =
[[9.97347243e-01 1.01137010e-03 1.64138680e-03]
 [8.72401276e-03 9.89110068e-01 2.16591886e-03]
 [6.40317604e-03 9.11646993e-04 9.92685177e-01]]
pi = [0.70027823 0.09198329 0.20773848]
Iter 7: LL=-1297448.28 | Rates: N=0.94143, AF=0.09619, OLD=0.06412, YOUNG=0.03042
A =
[[9.97346130e-01 9.86927390e-04 1.66694232e-03]
 [9.00933044e-03 9.88594840e-01 2.39582969e-03]
 [6.34831649e-03 9.19427374e-04 9.92732256e-01]]
pi = [0.70027224 0.08833447 0.21139329]
Iter 8: LL=-1297440.28 | Rates: N=0.94144, AF=0.09617, OLD=0.06594, YOUNG=0.03054
A =
[[9.97345264e-01 9.58154408e-04 1.69658161e-03]
 [9.24986804e-03 9.88095504e-01 2.65462800e-03]
 [6.32124947e-03 9.32363060e-04 9.92746387e-01]]
pi = [0.7002663  0.08408499 0.21564871]
Iter 9: LL=-1297432.98 | Rates: N=0.94144, AF=0.09616, OLD=0.06771, YOUNG=0.03070
A =
[[9.97344600e-01 9.26753370e-04 1.72864700e-03]
 [9.45412666e-03 9.87607358e-01 2.93851555e-03]
 [6.31319465e-03 9.48359331e-04 9.92738446e-01]]
pi = [0.70026217 0.07913386 0.22060397]
Iter 10: LL=-1297425.98 | Rates: N=0.94144, AF=0.09615, OLD=0.06950, YOUNG=0.03087
A =
[[9.97344086e-01 8.93943130e-04 1.76197082e-03]
 [9.63077393e-03 9.87123617e-01 3.24560871e-03]
 [6.31761020e-03 9.66259601e-04 9.92716130e-01]]
pi = [0.70026078 0.07350051 0.22623872]
Iter 11: LL=-1297419.13 | Rates: N=0.94144, AF=0.09614, OLD=0.07132, YOUNG=0.03103
A =
[[9.97343680e-01 8.60569607e-04 1.79574994e-03]
 [9.78754831e-03 9.86637282e-01 3.57517000e-03]
 [6.32985423e-03 9.85382308e-04 9.92684763e-01]]
pi = [0.70026238 0.06728304 0.23245459]
Iter 12: LL=-1297412.40 | Rates: N=0.94144, AF=0.09613, OLD=0.07320, YOUNG=0.03119
A =
[[9.97343349e-01 8.27220576e-04 1.82942998e-03]
 [9.93089923e-03 9.86142048e-01 3.92705302e-03]
 [6.34672414e-03 1.00528134e-03 9.92647995e-01]]
pi = [0.70026686 0.06063092 0.23910222]
Iter 13: LL=-1297405.77 | Rates: N=0.94144, AF=0.09612, OLD=0.07514, YOUNG=0.03135
A =
[[9.97343067e-01 7.94309663e-04 1.86262308e-03]
 [1.00659842e-02 9.85632648e-01 4.30136734e-03]
 [6.36605394e-03 1.02563146e-03 9.92608315e-01]]
pi = [0.70027386 0.05372541 0.24600074]
Iter 14: LL=-1297399.27 | Rates: N=0.94144, AF=0.09612, OLD=0.07716, YOUNG=0.03150
A =
[[9.97342814e-01 7.62131912e-04 1.89505408e-03]
 [1.01968354e-02 9.85104867e-01 4.69829789e-03]
 [6.38640268e-03 1.04617494e-03 9.92567422e-01]]
pi = [0.70028287 0.04676277 0.25295436]
Iter 15: LL=-1297392.89 | Rates: N=0.94144, AF=0.09611, OLD=0.07925, YOUNG=0.03165
A =
[[9.97342574e-01 7.30899254e-04 1.92652661e-03]
 [1.03265987e-02 9.84555371e-01 5.11803049e-03]
 [6.40682543e-03 1.06669721e-03 9.92526477e-01]]
pi = [0.70029332 0.03993863 0.25976805]
Final Global Rates (lambdas): [0.94144335 0.0961064  0.07925201 0.03164648]
Final transition matrix A:
[[9.97342574e-01 7.30899254e-04 1.92652661e-03]
 [1.03265987e-02 9.84555371e-01 5.11803049e-03]
 [6.40682543e-03 1.06669721e-03 9.92526477e-01]]
Final initial distribution pi:
[0.70029332 0.03993863 0.25976805]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3147  0.0998  0.1515    8191291.0   17837709.0  73924213.0
Archaic_young     0.6962  0.9030  0.7863  173558364.0   75719636.0  18636230.0
Modern            0.0000  0.0000  0.0000          0.0  724693000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         721620          344           1694
Archaic_old      1158         8226          73295
Archaic_young    1915        17459         174289

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2618  0.0646  0.1037
Archaic_young     0.7212  0.9245  0.8103

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         716112          151           1980
Archaic_old      1166         4890          70044
Archaic_young    2594        13636         189427

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1606003.67 | Rates: N=0.94341, AF=0.09581, OLD=0.04716, YOUNG=0.03790
A =
[[0.99713281 0.00103216 0.00183503]
 [0.00763111 0.99033986 0.00202903]
 [0.00743381 0.00112927 0.99143692]]
pi = [0.79988021 0.06811223 0.13200757]
Iter 2: LL=-1297872.35 | Rates: N=0.94366, AF=0.09558, OLD=0.05037, YOUNG=0.03604
A =
[[0.99712767 0.00103795 0.00183438]
 [0.00785959 0.99011335 0.00202706]
 [0.00730007 0.00111101 0.99158892]]
pi = [0.8012042  0.05721351 0.14158229]
Iter 3: LL=-1297830.90 | Rates: N=0.94367, AF=0.09556, OLD=0.05431, YOUNG=0.03428
A =
[[0.99712759 0.00104324 0.00182917]
 [0.00817829 0.98979924 0.00202248]
 [0.00714473 0.00109363 0.99176163]]
pi = [0.80119618 0.043651   0.15515283]
Iter 4: LL=-1297787.44 | Rates: N=0.94367, AF=0.09554, OLD=0.05797, YOUNG=0.03296
A =
[[0.99712747 0.00104281 0.00182972]
 [0.00857331 0.98938078 0.00204591]
 [0.00697329 0.0010838  0.99194291]]
pi = [0.80114018 0.02995118 0.16890864]
Iter 5: LL=-1297757.95 | Rates: N=0.94367, AF=0.09553, OLD=0.06092, YOUNG=0.03223
A =
[[0.99712697 0.00103403 0.001839  ]
 [0.00899406 0.98889349 0.00211245]
 [0.00681846 0.00108942 0.99209211]]
pi = [0.80109207 0.01901889 0.17988904]
Iter 6: LL=-1297742.01 | Rates: N=0.94367, AF=0.09551, OLD=0.06321, YOUNG=0.03194
A =
[[0.99712629 0.00101698 0.00185673]
 [0.00939915 0.98837961 0.00222124]
 [0.00669642 0.00110931 0.99219427]]
pi = [0.80106426 0.01142476 0.18751097]
Iter 7: LL=-1297732.73 | Rates: N=0.94367, AF=0.09550, OLD=0.06508, YOUNG=0.03188
A =
[[9.97125617e-01 9.93318811e-04 1.88106434e-03]
 [9.76960583e-03 9.87865385e-01 2.36500887e-03]
 [6.60815149e-03 1.13849719e-03 9.92253351e-01]]
pi = [0.80104896 0.00652744 0.1924236 ]
Iter 8: LL=-1297725.94 | Rates: N=0.94367, AF=0.09549, OLD=0.06673, YOUNG=0.03194
A =
[[9.97125037e-01 9.65034654e-04 1.90992817e-03]
 [1.01017933e-02 9.87360602e-01 2.53760486e-03]
 [6.54826999e-03 1.17265873e-03 9.92279071e-01]]
pi = [0.80103893 0.00354426 0.1954168 ]
Iter 9: LL=-1297720.02 | Rates: N=0.94367, AF=0.09548, OLD=0.06828, YOUNG=0.03205
A =
[[9.97124564e-01 9.33821036e-04 1.94161463e-03]
 [1.03994058e-02 9.86864923e-01 2.73567132e-03]
 [6.51027669e-03 1.20894722e-03 9.92280776e-01]]
pi = [0.80103144 0.00182717 0.19714139]
Iter 10: LL=-1297714.41 | Rates: N=0.94367, AF=0.09547, OLD=0.06980, YOUNG=0.03217
A =
[[9.97124184e-01 9.00945669e-04 1.97486991e-03]
 [1.06686322e-02 9.86373365e-01 2.95800295e-03]
 [6.48855135e-03 1.24560127e-03 9.92265847e-01]]
pi = [0.80102571 0.00089424 0.19808005]
Iter 11: LL=-1297708.92 | Rates: N=0.94367, AF=0.09547, OLD=0.07135, YOUNG=0.03230
A =
[[9.97123877e-01 8.67314127e-04 2.00880925e-03]
 [1.09157881e-02 9.85879568e-01 3.20464381e-03]
 [6.47875652e-03 1.28152638e-03 9.92239717e-01]]
pi = [8.01021504e-01 4.15628146e-04 1.98562868e-01]
Iter 12: LL=-1297703.47 | Rates: N=0.94367, AF=0.09546, OLD=0.07293, YOUNG=0.03243
A =
[[9.97123621e-01 8.33564837e-04 2.04281428e-03]
 [1.11463666e-02 9.85377374e-01 3.47625896e-03]
 [6.47769533e-03 1.31603484e-03 9.92206270e-01]]
pi = [8.01018671e-01 1.83540600e-04 1.98797788e-01]
Iter 13: LL=-1297698.03 | Rates: N=0.94368, AF=0.09546, OLD=0.07457, YOUNG=0.03256
A =
[[9.97123400e-01 8.00147684e-04 2.07645216e-03]
 [1.13648123e-02 9.84861407e-01 3.77378055e-03]
 [6.48304504e-03 1.34869985e-03 9.92168255e-01]]
pi = [8.01017070e-01 7.70388830e-05 1.98905891e-01]
Iter 14: LL=-1297692.59 | Rates: N=0.94368, AF=0.09545, OLD=0.07628, YOUNG=0.03268
A =
[[9.97123201e-01 7.67380282e-04 2.10941915e-03]
 [1.15746178e-02 9.84327146e-01 4.09823610e-03]
 [6.49311170e-03 1.37927082e-03 9.92127617e-01]]
pi = [8.01016578e-01 3.07467950e-05 1.98952675e-01]
Iter 15: LL=-1297687.16 | Rates: N=0.94368, AF=0.09545, OLD=0.07806, YOUNG=0.03281
A =
[[9.97123011e-01 7.35486543e-04 2.14150249e-03]
 [1.17785315e-02 9.83770787e-01 4.45068152e-03]
 [6.50664171e-03 1.40761988e-03 9.92085738e-01]]
pi = [8.01017091e-01 1.16731738e-05 1.98971236e-01]
Final Global Rates (lambdas): [0.94367603 0.09544568 0.07805615 0.03280965]
Final transition matrix A:
[[9.97123011e-01 7.35486543e-04 2.14150249e-03]
 [1.17785315e-02 9.83770787e-01 4.45068152e-03]
 [6.50664171e-03 1.40761988e-03 9.92085738e-01]]
Final initial distribution pi:
[8.01017091e-01 1.16731738e-05 1.98971236e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2864  0.0993  0.1475    7510148.0   18709852.0  68117880.0
Archaic_young     0.7239  0.9024  0.8034  184052756.0   70198244.0  19905126.0
Modern            0.0000  0.0000  0.0000          0.0  719529000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         716044          389           1810
Archaic_old       996         7529          67575
Archaic_young    2489        18302         184866

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3816  0.0669  0.1138
Archaic_young     0.7302  0.9511  0.8261

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         700144           69           2311
Archaic_old      1433         5284          72674
Archaic_young    3034         8476         206575

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1595834.18 | Rates: N=0.93097, AF=0.09549, OLD=0.05136, YOUNG=0.04115
A =
[[0.99669738 0.00114539 0.00215723]
 [0.00819743 0.98938279 0.00241978]
 [0.00795075 0.0012322  0.99081706]]
pi = [0.74676905 0.09360787 0.15962309]
Iter 2: LL=-1299328.82 | Rates: N=0.93124, AF=0.09531, OLD=0.05576, YOUNG=0.03845
A =
[[0.99670142 0.0011495  0.00214908]
 [0.00828902 0.98928502 0.00242596]
 [0.00785995 0.00119478 0.99094527]]
pi = [0.7487635  0.09572347 0.15551303]
Iter 3: LL=-1299252.82 | Rates: N=0.93124, AF=0.09529, OLD=0.06116, YOUNG=0.03599
A =
[[0.99670279 0.00115752 0.00213969]
 [0.00842545 0.98913744 0.00243711]
 [0.00778933 0.00115238 0.99105829]]
pi = [0.74883503 0.10023373 0.15093124]
Iter 4: LL=-1299179.76 | Rates: N=0.93124, AF=0.09525, OLD=0.06577, YOUNG=0.03429
A =
[[0.99670368 0.00115666 0.00213967]
 [0.00860874 0.98887096 0.00252029]
 [0.00770609 0.00111666 0.99117725]]
pi = [0.74881674 0.10564509 0.14553817]
Iter 5: LL=-1299138.98 | Rates: N=0.93124, AF=0.09522, OLD=0.06920, YOUNG=0.03344
A =
[[0.99670392 0.00114539 0.00215068]
 [0.00880295 0.98850654 0.00269051]
 [0.00763265 0.00110118 0.99126617]]
pi = [0.74878042 0.11110553 0.14011404]
Iter 6: LL=-1299120.75 | Rates: N=0.93124, AF=0.09520, OLD=0.07176, YOUNG=0.03315
A =
[[0.99670376 0.00112574 0.0021705 ]
 [0.00898178 0.98808732 0.00293089]
 [0.00757924 0.00110361 0.99131714]]
pi = [0.74873323 0.11583384 0.13543293]
Iter 7: LL=-1299110.70 | Rates: N=0.93125, AF=0.09518, OLD=0.07384, YOUNG=0.03313
A =
[[0.99670346 0.00110031 0.00219622]
 [0.00913626 0.98764231 0.00322143]
 [0.00754519 0.00111731 0.99133749]]
pi = [0.74868513 0.1193434  0.13197147]
Iter 8: LL=-1299102.91 | Rates: N=0.93125, AF=0.09516, OLD=0.07570, YOUNG=0.03324
A =
[[0.99670317 0.00107128 0.00222555]
 [0.00926678 0.98718415 0.00354907]
 [0.00752629 0.00113739 0.99133632]]
pi = [0.74864424 0.12137932 0.12997644]
Iter 9: LL=-1299095.74 | Rates: N=0.93125, AF=0.09515, OLD=0.07749, YOUNG=0.03339
A =
[[0.99670292 0.00104018 0.0022569 ]
 [0.00937742 0.98671547 0.00390711]
 [0.0075182  0.00116098 0.99132082]]
pi = [0.748615   0.12179946 0.12958554]
Iter 10: LL=-1299088.75 | Rates: N=0.93125, AF=0.09514, OLD=0.07928, YOUNG=0.03356
A =
[[0.9967027  0.001008   0.0022893 ]
 [0.00947312 0.9862343  0.00429258]
 [0.00751743 0.00118646 0.99129612]]
pi = [0.748599  0.1205108 0.1308902]
Iter 11: LL=-1299081.85 | Rates: N=0.93125, AF=0.09513, OLD=0.08111, YOUNG=0.03373
A =
[[9.96702495e-01 9.75405971e-04 2.32209864e-03]
 [9.55847641e-03 9.85737149e-01 4.70437474e-03]
 [7.52137672e-03 1.21285974e-03 9.91265764e-01]]
pi = [0.74859598 0.11744768 0.13395635]
Iter 12: LL=-1299075.00 | Rates: N=0.93125, AF=0.09512, OLD=0.08300, YOUNG=0.03390
A =
[[9.96702300e-01 9.42827698e-04 2.35487249e-03]
 [9.63735965e-03 9.85220454e-01 5.14218641e-03]
 [7.52821858e-03 1.23957592e-03 9.91232205e-01]]
pi = [0.74860449 0.11257297 0.13882254]
Iter 13: LL=-1299068.20 | Rates: N=0.93125, AF=0.09511, OLD=0.08496, YOUNG=0.03408
A =
[[9.96702102e-01 9.10559018e-04 2.38733923e-03]
 [9.71288537e-03 9.84681156e-01 5.60595834e-03]
 [7.53667674e-03 1.26619907e-03 9.91197124e-01]]
pi = [0.74862234 0.10589446 0.1454832 ]
Iter 14: LL=-1299061.45 | Rates: N=0.93125, AF=0.09510, OLD=0.08700, YOUNG=0.03424
A =
[[9.96701895e-01 8.78803110e-04 2.41930177e-03]
 [9.78750305e-03 9.84116892e-01 6.09560528e-03]
 [7.54588154e-03 1.29244738e-03 9.91161671e-01]]
pi = [0.74864686 0.09749305 0.15386009]
Iter 15: LL=-1299054.76 | Rates: N=0.93125, AF=0.09509, OLD=0.08913, YOUNG=0.03441
A =
[[9.96701676e-01 8.47704508e-04 2.45061914e-03]
 [9.86309882e-03 9.83526022e-01 6.61087957e-03]
 [7.55525161e-03 1.31811906e-03 9.91126629e-01]]
pi = [0.74867514 0.0875573  0.16376756]
Final Global Rates (lambdas): [0.93124998 0.09508668 0.08913024 0.03440985]
Final transition matrix A:
[[9.96701676e-01 8.47704508e-04 2.45061914e-03]
 [9.86309882e-03 9.83526022e-01 6.61087957e-03]
 [7.55525161e-03 1.31811906e-03 9.91126629e-01]]
Final initial distribution pi:
[0.74867514 0.0875573  0.16376756]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3359  0.1163  0.1728    9175451.0   18141549.0  69701041.0
Archaic_young     0.7319  0.9064  0.8099  195939473.0   71781527.0  20227310.0
Modern            0.0000  0.0000  0.0000          0.0  704962000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         700294           70           2160
Archaic_old      1519         9178          68694
Archaic_young    3149        18069         196867

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3907  0.0517  0.0913
Archaic_young     0.6898  0.9522  0.8000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         714469           81           2424
Archaic_old      1666         4416          80029
Archaic_young    3543         6804         186568

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1612021.61 | Rates: N=0.93962, AF=0.09513, OLD=0.05765, YOUNG=0.04724
A =
[[0.99655121 0.00117501 0.00227378]
 [0.00915949 0.98812233 0.00271818]
 [0.00902365 0.00139145 0.9895849 ]]
pi = [0.59006422 0.16195528 0.24798049]
Iter 2: LL=-1307433.20 | Rates: N=0.93991, AF=0.09492, OLD=0.06241, YOUNG=0.04421
A =
[[0.99656403 0.00117137 0.0022646 ]
 [0.00916779 0.98814437 0.00268784]
 [0.00893305 0.00137787 0.98968908]]
pi = [0.57873742 0.19332388 0.2279387 ]
Iter 3: LL=-1307352.52 | Rates: N=0.93991, AF=0.09490, OLD=0.06866, YOUNG=0.04116
A =
[[0.99656575 0.00117295 0.00226129]
 [0.009268   0.98808554 0.00264646]
 [0.00887581 0.00136523 0.98975897]]
pi = [0.57271707 0.23785811 0.18942482]
Iter 4: LL=-1307263.42 | Rates: N=0.93991, AF=0.09488, OLD=0.07415, YOUNG=0.03890
A =
[[0.99656661 0.00116501 0.00226838]
 [0.00947424 0.98784556 0.00268021]
 [0.00877529 0.00136022 0.98986449]]
pi = [0.56551775 0.28413765 0.1503446 ]
Iter 5: LL=-1307210.93 | Rates: N=0.93991, AF=0.09485, OLD=0.07816, YOUNG=0.03773
A =
[[0.99656686 0.00114757 0.00228557]
 [0.00972353 0.98746069 0.00281578]
 [0.0086693  0.00138015 0.98995055]]
pi = [0.56033091 0.31735589 0.12231319]
Iter 6: LL=-1307188.41 | Rates: N=0.93991, AF=0.09483, OLD=0.08104, YOUNG=0.03728
A =
[[0.99656686 0.00112313 0.00231001]
 [0.00996113 0.98700341 0.00303546]
 [0.00858331 0.00142209 0.98999461]]
pi = [0.55751343 0.3363423  0.10614428]
Iter 7: LL=-1307177.00 | Rates: N=0.93991, AF=0.09482, OLD=0.08330, YOUNG=0.03719
A =
[[0.99656681 0.0010941  0.00233909]
 [0.01016894 0.98651494 0.00331613]
 [0.00852131 0.00147622 0.99000247]]
pi = [0.55598059 0.34558239 0.09843702]
Iter 8: LL=-1307168.60 | Rates: N=0.93991, AF=0.09481, OLD=0.08527, YOUNG=0.03725
A =
[[0.99656681 0.00106245 0.00237074]
 [0.01034623 0.98601095 0.00364282]
 [0.00847948 0.00153548 0.98998504]]
pi = [0.55503771 0.34881747 0.09614482]
Iter 9: LL=-1307160.98 | Rates: N=0.93991, AF=0.09480, OLD=0.08713, YOUNG=0.03737
A =
[[0.99656686 0.00102958 0.00240357]
 [0.01049759 0.98549445 0.00400796]
 [0.00845289 0.00159597 0.98995114]]
pi = [0.55437347 0.34833913 0.0972874 ]
Iter 10: LL=-1307153.60 | Rates: N=0.93991, AF=0.09479, OLD=0.08898, YOUNG=0.03751
A =
[[9.96566953e-01 9.96398195e-04 2.43664838e-03]
 [1.06282965e-02 9.84963397e-01 4.40830618e-03]
 [8.43740790e-03 1.65566127e-03 9.89906931e-01]]
pi = [0.55385409 0.34552588 0.10062003]
Iter 11: LL=-1307146.32 | Rates: N=0.93990, AF=0.09478, OLD=0.09086, YOUNG=0.03766
A =
[[9.96567084e-01 9.63495399e-04 2.46942094e-03]
 [1.07429127e-02 9.84414290e-01 4.84279739e-03]
 [8.42997203e-03 1.71350395e-03 9.89856524e-01]]
pi = [0.55341889 0.34125285 0.10532826]
Iter 12: LL=-1307139.10 | Rates: N=0.93990, AF=0.09477, OLD=0.09279, YOUNG=0.03781
A =
[[9.96567235e-01 9.31246502e-04 2.50151821e-03]
 [1.08450503e-02 9.83843584e-01 5.31136585e-03]
 [8.42835984e-03 1.76895997e-03 9.89802680e-01]]
pi = [0.55303762 0.33610385 0.11085854]
Iter 13: LL=-1307131.96 | Rates: N=0.93990, AF=0.09476, OLD=0.09478, YOUNG=0.03796
A =
[[9.96567399e-01 8.99895439e-04 2.53270594e-03]
 [1.09374919e-02 9.83248160e-01 5.81434805e-03]
 [8.43096613e-03 1.82177406e-03 9.89747260e-01]]
pi = [0.55269348 0.33047891 0.11682761]
Iter 14: LL=-1307124.88 | Rates: N=0.93990, AF=0.09475, OLD=0.09683, YOUNG=0.03810
A =
[[9.96567566e-01 8.69598484e-04 2.56283543e-03]
 [1.10224084e-02 9.82625403e-01 6.35218850e-03]
 [8.43660899e-03 1.87185785e-03 9.89691533e-01]]
pi = [0.5523762  0.32465652 0.12296728]
Iter 15: LL=-1307117.90 | Rates: N=0.93990, AF=0.09475, OLD=0.09896, YOUNG=0.03825
A =
[[9.96567732e-01 8.40451033e-04 2.59181715e-03]
 [1.11015635e-02 9.81973146e-01 6.92529055e-03]
 [8.44439458e-03 1.91922328e-03 9.89636382e-01]]
pi = [0.55207899 0.31883429 0.12908672]
Final Global Rates (lambdas): [0.93990233 0.09474648 0.09895865 0.03824848]
Final transition matrix A:
[[9.96567732e-01 8.40451033e-04 2.59181715e-03]
 [1.11015635e-02 9.81973146e-01 6.92529055e-03]
 [8.44439458e-03 1.91922328e-03 9.89636382e-01]]
Final initial distribution pi:
[0.55207899 0.31883429 0.12908672]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3900  0.1373  0.2031   11733652.0   18352348.0  73732868.0
Archaic_young     0.6973  0.8945  0.7837  174325156.0   75671844.0  20554784.0
Modern            0.0000  0.0000  0.0000          0.0  719917000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         714592          213           2169
Archaic_old      1824        11726          72561
Archaic_young    3501        18147         175267

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1928  0.0179  0.0328
Archaic_young     0.7022  0.9549  0.8093

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         710968           39           2950
Archaic_old      1439         1445          78110
Archaic_young    4260         5981         194808

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1615580.44 | Rates: N=0.93541, AF=0.09589, OLD=0.06441, YOUNG=0.05357
A =
[[0.99634057 0.00123546 0.00242397]
 [0.00954936 0.98739475 0.00305588]
 [0.00944195 0.00153042 0.98902764]]
pi = [0.80076527 0.06645767 0.13277705]
Iter 2: LL=-1314110.35 | Rates: N=0.93570, AF=0.09573, OLD=0.06973, YOUNG=0.05018
A =
[[0.99637658 0.00123019 0.00239323]
 [0.00953418 0.9874103  0.00305552]
 [0.00927698 0.00150231 0.98922071]]
pi = [0.8052996  0.05671236 0.13798805]
Iter 3: LL=-1314016.80 | Rates: N=0.93570, AF=0.09570, OLD=0.07732, YOUNG=0.04660
A =
[[0.99638049 0.0012439  0.00237561]
 [0.00965563 0.98729641 0.00304796]
 [0.00920049 0.00147062 0.98932889]]
pi = [0.80557727 0.04705621 0.14736652]
Iter 4: LL=-1313898.98 | Rates: N=0.93570, AF=0.09565, OLD=0.08445, YOUNG=0.04376
A =
[[0.99638197 0.0012508  0.00236722]
 [0.0098947  0.98696289 0.00314241]
 [0.00908204 0.00144575 0.98947221]]
pi = [0.80568803 0.03821095 0.15610102]
Iter 5: LL=-1313820.99 | Rates: N=0.93570, AF=0.09559, OLD=0.08992, YOUNG=0.04223
A =
[[0.99638196 0.00124555 0.00237249]
 [0.01019291 0.9864215  0.00338558]
 [0.00895839 0.00145409 0.98958752]]
pi = [0.805863   0.03154465 0.16259235]
Iter 6: LL=-1313785.05 | Rates: N=0.93570, AF=0.09555, OLD=0.09397, YOUNG=0.04164
A =
[[0.99638124 0.00122917 0.00238958]
 [0.01048438 0.98575693 0.00375869]
 [0.00885996 0.00149452 0.98964552]]
pi = [0.80603796 0.02691001 0.16705202]
Iter 7: LL=-1313765.95 | Rates: N=0.93570, AF=0.09552, OLD=0.09726, YOUNG=0.04153
A =
[[0.99638044 0.00120456 0.002415  ]
 [0.01074308 0.98502706 0.00422986]
 [0.00879167 0.00155405 0.98965428]]
pi = [0.80616731 0.02368408 0.17014861]
Iter 8: LL=-1313751.37 | Rates: N=0.93570, AF=0.09549, OLD=0.10022, YOUNG=0.04162
A =
[[0.99637976 0.00117466 0.00244558]
 [0.01096615 0.98425645 0.0047774 ]
 [0.00874842 0.00162266 0.98962891]]
pi = [0.80625261 0.0213872  0.17236019]
Iter 9: LL=-1313737.91 | Rates: N=0.93570, AF=0.09547, OLD=0.10309, YOUNG=0.04179
A =
[[0.99637919 0.00114179 0.00247902]
 [0.01115882 0.98345107 0.00539011]
 [0.00872368 0.00169462 0.9895817 ]]
pi = [0.80630736 0.01972323 0.17396941]
Iter 10: LL=-1313724.77 | Rates: N=0.93570, AF=0.09545, OLD=0.10600, YOUNG=0.04199
A =
[[0.99637869 0.00110755 0.00251376]
 [0.01132787 0.98260908 0.00606305]
 [0.00871199 0.00176669 0.98952132]]
pi = [0.80634157 0.01851164 0.17514678]
Iter 11: LL=-1313711.80 | Rates: N=0.93570, AF=0.09543, OLD=0.10899, YOUNG=0.04221
A =
[[0.99637822 0.00107301 0.00254877]
 [0.01147942 0.98172638 0.00679421]
 [0.00870932 0.00183696 0.98945372]]
pi = [0.80636087 0.01763758 0.17600155]
Iter 12: LL=-1313699.01 | Rates: N=0.93570, AF=0.09541, OLD=0.11209, YOUNG=0.04242
A =
[[0.99637774 0.0010389  0.00258336]
 [0.01161845 0.98079897 0.00758258]
 [0.00871281 0.00190417 0.98938302]]
pi = [0.80636831 0.01702392 0.17660777]
Iter 13: LL=-1313686.44 | Rates: N=0.93570, AF=0.09539, OLD=0.11532, YOUNG=0.04263
A =
[[0.99637723 0.00100571 0.00261706]
 [0.01174899 0.97982379 0.00842722]
 [0.0087204  0.00196748 0.98931212]]
pi = [0.80636575 0.01661613 0.17701812]
Iter 14: LL=-1313674.13 | Rates: N=0.93569, AF=0.09537, OLD=0.11868, YOUNG=0.04285
A =
[[9.96376657e-01 9.73770000e-04 2.64957320e-03]
 [1.18744642e-02 9.78798672e-01 9.32686362e-03]
 [8.73059314e-03 2.02628394e-03 9.89243123e-01]]
pi = [0.80635452 0.01637363 0.17727184]
Iter 15: LL=-1313662.14 | Rates: N=0.93569, AF=0.09535, OLD=0.12218, YOUNG=0.04307
A =
[[9.96376003e-01 9.43273630e-04 2.68072300e-03]
 [1.19981623e-02 9.77721878e-01 1.02799599e-02]
 [8.74224053e-03 2.08021738e-03 9.89177542e-01]]
pi = [0.80633574 0.01626471 0.17739956]
Final Global Rates (lambdas): [0.93569435 0.09534858 0.12217918 0.04306634]
Final transition matrix A:
[[9.96376003e-01 9.43273630e-04 2.68072300e-03]
 [1.19981623e-02 9.77721878e-01 1.02799599e-02]
 [8.74224053e-03 2.08021738e-03 9.89177542e-01]]
Final initial distribution pi:
[0.80633574 0.01626471 0.17739956]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2583  0.0842  0.1270    6769162.0   19439838.0  73603200.0
Archaic_young     0.7032  0.8905  0.7858  180674613.0   76269387.0  22206780.0
Modern            0.0000  0.0000  0.0000          0.0  716847000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         711077          304           2576
Archaic_old      1512         6777          72705
Archaic_young    4258        19128         181663

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3060  0.3775  0.3380
Archaic_young     0.7478  0.6862  0.7157

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         734399          521           1525
Archaic_old      1274        26234          42384
Archaic_young    2407        58795         132461

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1610050.98 | Rates: N=0.94721, AF=0.09529, OLD=0.05060, YOUNG=0.03244
A =
[[0.9974219  0.0011917  0.00138641]
 [0.00735114 0.99125477 0.00139409]
 [0.00746456 0.00118817 0.99134727]]
pi = [0.65178132 0.13782898 0.21038969]
Iter 2: LL=-1298172.82 | Rates: N=0.94744, AF=0.09503, OLD=0.05429, YOUNG=0.03034
A =
[[0.99741436 0.00118032 0.00140532]
 [0.00764625 0.99087234 0.00148141]
 [0.00722351 0.00111435 0.99166214]]
pi = [0.65062087 0.12323265 0.22614648]
Iter 3: LL=-1298125.76 | Rates: N=0.94745, AF=0.09500, OLD=0.05742, YOUNG=0.02927
A =
[[0.99741444 0.00115982 0.00142574]
 [0.00792493 0.99045835 0.00161672]
 [0.00704169 0.0010741  0.99188421]]
pi = [0.65059456 0.10896346 0.24044198]
Iter 4: LL=-1298101.56 | Rates: N=0.94745, AF=0.09498, OLD=0.05987, YOUNG=0.02890
A =
[[0.9974144  0.00113233 0.00145328]
 [0.00816427 0.99003281 0.00180292]
 [0.00692126 0.00106435 0.99201439]]
pi = [0.65057877 0.09608431 0.25333693]
Iter 5: LL=-1298087.78 | Rates: N=0.94745, AF=0.09496, OLD=0.06190, YOUNG=0.02888
A =
[[0.9974142  0.00109917 0.00148663]
 [0.0083615  0.98960717 0.00203132]
 [0.00684997 0.00107442 0.99207561]]
pi = [0.65056822 0.08446181 0.26496996]
Iter 6: LL=-1298077.16 | Rates: N=0.94745, AF=0.09495, OLD=0.06374, YOUNG=0.02902
A =
[[0.997414   0.00106193 0.00152407]
 [0.00852246 0.98918316 0.00229437]
 [0.00681298 0.0010958  0.99209122]]
pi = [0.65056086 0.07372784 0.2757113 ]
Iter 7: LL=-1298067.36 | Rates: N=0.94745, AF=0.09494, OLD=0.06551, YOUNG=0.02921
A =
[[0.99741385 0.00102202 0.00156413]
 [0.00865416 0.98875821 0.00258763]
 [0.00679907 0.00112355 0.99207738]]
pi = [0.65055483 0.06360694 0.28583823]
Iter 8: LL=-1298057.76 | Rates: N=0.94745, AF=0.09493, OLD=0.06731, YOUNG=0.02942
A =
[[9.97413760e-01 9.80525385e-04 1.60571500e-03]
 [8.76288020e-03 9.88328096e-01 2.90902377e-03]
 [6.80038174e-03 1.15495575e-03 9.92044663e-01]]
pi = [0.65054912 0.05397189 0.29547899]
Iter 9: LL=-1298048.21 | Rates: N=0.94745, AF=0.09493, OLD=0.06915, YOUNG=0.02964
A =
[[9.97413713e-01 9.38253408e-04 1.64803364e-03]
 [8.85401602e-03 9.87888132e-01 3.25785209e-03]
 [6.81143843e-03 1.18846904e-03 9.92000093e-01]]
pi = [0.65054335 0.04482378 0.30463286]
Iter 10: LL=-1298038.71 | Rates: N=0.94745, AF=0.09492, OLD=0.07106, YOUNG=0.02985
A =
[[9.97413701e-01 8.95817763e-04 1.69048150e-03]
 [8.93220752e-03 9.87433571e-01 3.63422107e-03]
 [6.82841353e-03 1.22309887e-03 9.91948488e-01]]
pi = [0.65053746 0.03625784 0.31320471]
Iter 11: LL=-1298029.26 | Rates: N=0.94745, AF=0.09491, OLD=0.07306, YOUNG=0.03005
A =
[[9.97413712e-01 8.53694336e-04 1.73259331e-03]
 [9.00145982e-03 9.86959807e-01 4.03873359e-03]
 [6.84862243e-03 1.25814737e-03 9.91893230e-01]]
pi = [0.65053156 0.02842552 0.32104292]
Iter 12: LL=-1298019.90 | Rates: N=0.94745, AF=0.09491, OLD=0.07514, YOUNG=0.03026
A =
[[9.97413738e-01 8.12264454e-04 1.77399748e-03]
 [9.06522652e-03 9.86462420e-01 4.47235328e-03]
 [6.87020310e-03 1.29306974e-03 9.91836727e-01]]
pi = [0.65052588 0.02149344 0.32798068]
Iter 13: LL=-1298010.64 | Rates: N=0.94745, AF=0.09490, OLD=0.07733, YOUNG=0.03046
A =
[[9.97413769e-01 7.71839753e-04 1.81439170e-03]
 [9.12647252e-03 9.85937197e-01 4.93633007e-03]
 [6.89189364e-03 1.32740667e-03 9.91780700e-01]]
pi = [0.65052068 0.01560099 0.33387833]
Iter 14: LL=-1298001.51 | Rates: N=0.94745, AF=0.09489, OLD=0.07961, YOUNG=0.03065
A =
[[9.97413795e-01 7.32676816e-04 1.85352852e-03]
 [9.18772557e-03 9.85380139e-01 5.43213501e-03]
 [6.91287275e-03 1.36074832e-03 9.91726379e-01]]
pi = [0.65051622 0.01082339 0.3386604 ]
Iter 15: LL=-1297992.54 | Rates: N=0.94746, AF=0.09488, OLD=0.08201, YOUNG=0.03085
A =
[[9.97413808e-01 6.94985324e-04 1.89120708e-03]
 [9.25111076e-03 9.84787513e-01 5.96137639e-03]
 [6.93264295e-03 1.39271377e-03 9.91674643e-01]]
pi = [0.65051271 0.00714969 0.3423376 ]
Final Global Rates (lambdas): [0.94745503 0.09488439 0.08201211 0.03084642]
Final transition matrix A:
[[9.97413808e-01 6.94985324e-04 1.89120708e-03]
 [9.25111076e-03 9.84787513e-01 5.96137639e-03]
 [6.93264295e-03 1.39271377e-03 9.91674643e-01]]
Final initial distribution pi:
[0.65051271 0.00714969 0.3423376 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3285  0.1416  0.1979    9816660.0   20063340.0  59533439.0
Archaic_young     0.7355  0.8896  0.8052  170983513.0   61494487.0  21211081.0
Modern            0.0000  0.0000  0.0000          0.0  737642000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         734361          240           1844
Archaic_old      1094         9852          58946
Archaic_young    2187        19788         171688

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3478  0.3779  0.3622
Archaic_young     0.7899  0.7704  0.7801

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         726770          557           1886
Archaic_old      1514        24445          39171
Archaic_young    2619        45178         157860

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1613328.46 | Rates: N=0.94677, AF=0.09549, OLD=0.05505, YOUNG=0.03648
A =
[[0.99709889 0.00125167 0.00164945]
 [0.00819135 0.99003947 0.00176918]
 [0.00792681 0.0012826  0.99079059]]
pi = [0.75231035 0.08633905 0.16135061]
Iter 2: LL=-1301897.85 | Rates: N=0.94703, AF=0.09525, OLD=0.05967, YOUNG=0.03376
A =
[[0.99709468 0.00124662 0.00165869]
 [0.00856721 0.98956827 0.00186452]
 [0.00766467 0.00121267 0.99112266]]
pi = [0.75216894 0.06265584 0.18517522]
Iter 3: LL=-1301828.38 | Rates: N=0.94703, AF=0.09522, OLD=0.06390, YOUNG=0.03225
A =
[[0.99709442 0.00123659 0.00166899]
 [0.00895784 0.98902174 0.00202042]
 [0.00745923 0.00117548 0.99136529]]
pi = [0.7519933  0.03810697 0.20989974]
Iter 4: LL=-1301790.22 | Rates: N=0.94703, AF=0.09519, OLD=0.06721, YOUNG=0.03164
A =
[[0.99709392 0.00121733 0.00168875]
 [0.00931522 0.98843141 0.00225337]
 [0.00731358 0.00117038 0.99151604]]
pi = [0.7518093  0.01979976 0.22839094]
Iter 5: LL=-1301770.11 | Rates: N=0.94703, AF=0.09517, OLD=0.06989, YOUNG=0.03152
A =
[[0.9970933  0.00118991 0.00171679]
 [0.00961771 0.98783041 0.00255188]
 [0.00722538 0.00118742 0.9915872 ]]
pi = [0.75168906 0.00923227 0.23907868]
Iter 6: LL=-1301756.12 | Rates: N=0.94703, AF=0.09515, OLD=0.07225, YOUNG=0.03162
A =
[[0.99709278 0.00115646 0.00175076]
 [0.00986728 0.98722944 0.00290328]
 [0.00718001 0.00121664 0.99160335]]
pi = [0.75163034 0.00402997 0.24433969]
Iter 7: LL=-1301743.91 | Rates: N=0.94704, AF=0.09513, OLD=0.07450, YOUNG=0.03180
A =
[[0.99709241 0.00111903 0.00178856]
 [0.01007226 0.98662899 0.00329875]
 [0.0071641  0.00125202 0.99158388]]
pi = [0.75160904 0.00169092 0.24670004]
Iter 8: LL=-1301732.28 | Rates: N=0.94704, AF=0.09512, OLD=0.07675, YOUNG=0.03200
A =
[[0.99709218 0.00107918 0.00182864]
 [0.01024119 0.98602592 0.00373289]
 [0.0071678  0.00129021 0.99154199]]
pi = [7.51607097e-01 6.91930418e-04 2.47700973e-01]
Iter 9: LL=-1301720.92 | Rates: N=0.94704, AF=0.09510, OLD=0.07905, YOUNG=0.03222
A =
[[0.99709208 0.001038   0.00186991]
 [0.01038164 0.98541592 0.00420244]
 [0.00718417 0.00132926 0.99148657]]
pi = [7.51614744e-01 2.78266416e-04 2.48106990e-01]
Iter 10: LL=-1301709.77 | Rates: N=0.94704, AF=0.09509, OLD=0.08143, YOUNG=0.03243
A =
[[9.97092090e-01 9.96296079e-04 1.91161419e-03]
 [1.05000147e-02 9.84794584e-01 4.70540176e-03]
 [7.20840301e-03 1.36789128e-03 9.91423706e-01]]
pi = [7.51627252e-01 1.10445365e-04 2.48262302e-01]
Iter 11: LL=-1301698.83 | Rates: N=0.94704, AF=0.09507, OLD=0.08391, YOUNG=0.03264
A =
[[9.97092181e-01 9.54636910e-04 1.95318185e-03]
 [1.06016873e-02 9.84157877e-01 5.24043526e-03]
 [7.23716506e-03 1.40518251e-03 9.91357652e-01]]
pi = [7.51642403e-01 4.33710077e-05 2.48314226e-01]
Iter 12: LL=-1301688.13 | Rates: N=0.94703, AF=0.09506, OLD=0.08650, YOUNG=0.03284
A =
[[9.97092339e-01 9.13461541e-04 1.99419923e-03]
 [1.06911288e-02 9.83502238e-01 5.80663298e-03]
 [7.26816492e-03 1.44044707e-03 9.91291388e-01]]
pi = [7.51659131e-01 1.68775464e-05 2.48323992e-01]
Iter 13: LL=-1301677.67 | Rates: N=0.94703, AF=0.09504, OLD=0.08920, YOUNG=0.03305
A =
[[9.97092544e-01 8.73099466e-04 2.03435643e-03]
 [1.07721293e-02 9.82824444e-01 6.40342661e-03]
 [7.29983713e-03 1.47317522e-03 9.91226988e-01]]
pi = [7.51676882e-01 6.51569920e-06 2.48316603e-01]
Iter 14: LL=-1301667.48 | Rates: N=0.94703, AF=0.09503, OLD=0.09203, YOUNG=0.03325
A =
[[9.97092775e-01 8.33800102e-04 2.07342521e-03]
 [1.08480508e-02 9.82121304e-01 7.03064472e-03]
 [7.33111239e-03 1.50301900e-03 9.91165869e-01]]
pi = [7.51695323e-01 2.49756118e-06 2.48302179e-01]
Iter 15: LL=-1301657.56 | Rates: N=0.94703, AF=0.09501, OLD=0.09499, YOUNG=0.03346
A =
[[9.97093008e-01 7.95750197e-04 2.11124186e-03]
 [1.09220546e-02 9.81389311e-01 7.68863472e-03]
 [7.36125873e-03 1.52978159e-03 9.91108960e-01]]
pi = [7.51714221e-01 9.51166169e-07 2.48284828e-01]
Final Global Rates (lambdas): [0.94703347 0.09500979 0.09498598 0.03345642]
Final transition matrix A:
[[9.97093008e-01 7.95750197e-04 2.11124186e-03]
 [1.09220546e-02 9.81389311e-01 7.68863472e-03]
 [7.36125873e-03 1.52978159e-03 9.91108960e-01]]
Final initial distribution pi:
[7.51714221e-01 9.51166169e-07 2.48284828e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4066  0.1584  0.2280   10232528.0   14935472.0  54354349.0
Archaic_young     0.7690  0.9184  0.8371  187320205.0   56257795.0  16637677.0
Modern            0.0000  0.0000  0.0000          0.0  731254000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         726942          138           2133
Archaic_old      1626        10228          53276
Archaic_young    2686        14802         188169

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3861  0.2686  0.3168
Archaic_young     0.7638  0.8451  0.8024

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         704199          448           2152
Archaic_old      1597        20066          53453
Archaic_young    3159        31359         183567

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1606312.55 | Rates: N=0.93507, AF=0.09737, OLD=0.05826, YOUNG=0.03942
A =
[[0.99667935 0.00134025 0.00198039]
 [0.00880347 0.98899927 0.00219726]
 [0.0079281  0.00133737 0.99073452]]
pi = [0.84945085 0.0490672  0.10148195]
Iter 2: LL=-1305066.06 | Rates: N=0.93533, AF=0.09722, OLD=0.06383, YOUNG=0.03624
A =
[[0.9966904  0.00133677 0.00197283]
 [0.0092682  0.98846697 0.00226483]
 [0.00762455 0.00125839 0.99111707]]
pi = [0.85348191 0.03257074 0.11394735]
Iter 3: LL=-1304969.94 | Rates: N=0.93533, AF=0.09719, OLD=0.06896, YOUNG=0.03439
A =
[[0.99669121 0.00133949 0.0019693 ]
 [0.00971975 0.98791741 0.00236284]
 [0.00742535 0.00121951 0.99135514]]
pi = [0.8534083  0.01721101 0.12938069]
Iter 4: LL=-1304919.86 | Rates: N=0.93533, AF=0.09716, OLD=0.07262, YOUNG=0.03358
A =
[[0.99669099 0.00133032 0.00197869]
 [0.01011868 0.9873429  0.00253842]
 [0.00728559 0.00121686 0.99149755]]
pi = [0.85314499 0.00713773 0.13971727]
Iter 5: LL=-1304899.11 | Rates: N=0.93533, AF=0.09713, OLD=0.07525, YOUNG=0.03337
A =
[[0.99669046 0.0013101  0.00199944]
 [0.01045811 0.98676198 0.00277991]
 [0.00719696 0.0012397  0.99156334]]
pi = [0.85297414 0.00251558 0.14451028]
Iter 6: LL=-1304887.82 | Rates: N=0.93533, AF=0.09712, OLD=0.07737, YOUNG=0.03344
A =
[[0.99668995 0.00128217 0.00202789]
 [0.01075075 0.98617926 0.00306999]
 [0.00714407 0.00127611 0.99157981]]
pi = [8.52899435e-01 8.06887819e-04 1.46293677e-01]
Iter 7: LL=-1304878.82 | Rates: N=0.93533, AF=0.09710, OLD=0.07930, YOUNG=0.03360
A =
[[0.99668953 0.00124945 0.00206102]
 [0.01101062 0.9855914  0.00339798]
 [0.00711476 0.00131897 0.99156627]]
pi = [8.52874133e-01 2.44545317e-04 1.46881322e-01]
Iter 8: LL=-1304870.33 | Rates: N=0.93533, AF=0.09709, OLD=0.08119, YOUNG=0.03381
A =
[[0.9966892  0.00121395 0.00209685]
 [0.01124889 0.98499196 0.00375915]
 [0.00710089 0.00136457 0.99153454]]
pi = [8.52868203e-01 7.12532145e-05 1.47060543e-01]
Iter 9: LL=-1304861.92 | Rates: N=0.93533, AF=0.09708, OLD=0.08311, YOUNG=0.03402
A =
[[0.99668894 0.00117695 0.00213411]
 [0.01147384 0.98437406 0.00415211]
 [0.00709723 0.00141096 0.9914918 ]]
pi = [8.52869015e-01 2.01161155e-05 1.47110868e-01]
Iter 10: LL=-1304853.51 | Rates: N=0.93533, AF=0.09707, OLD=0.08511, YOUNG=0.03423
A =
[[0.99668873 0.00113923 0.00217204]
 [0.01169139 0.98373161 0.004577  ]
 [0.00710045 0.001457   0.99144255]]
pi = [8.52872195e-01 5.52338930e-06 1.47122282e-01]
Iter 11: LL=-1304845.05 | Rates: N=0.93533, AF=0.09706, OLD=0.08720, YOUNG=0.03444
A =
[[0.99668856 0.00110132 0.00221012]
 [0.01190564 0.98305986 0.0050345 ]
 [0.0071084  0.00150196 0.99138964]]
pi = [8.52876473e-01 1.47796054e-06 1.47122049e-01]
Iter 12: LL=-1304836.58 | Rates: N=0.93533, AF=0.09705, OLD=0.08939, YOUNG=0.03464
A =
[[0.99668841 0.00106357 0.00224803]
 [0.0121192  0.98235549 0.00552531]
 [0.00711973 0.0015453  0.99133497]]
pi = [8.52881615e-01 3.85879581e-07 1.47117999e-01]
Iter 13: LL=-1304828.09 | Rates: N=0.93533, AF=0.09704, OLD=0.09169, YOUNG=0.03484
A =
[[0.99668827 0.00102621 0.00228552]
 [0.01233361 0.98161656 0.00604983]
 [0.00713354 0.00158665 0.99127981]]
pi = [8.52887680e-01 9.83886430e-08 1.47112222e-01]
Iter 14: LL=-1304819.62 | Rates: N=0.93533, AF=0.09703, OLD=0.09411, YOUNG=0.03504
A =
[[9.96688142e-01 9.89426322e-04 2.32243175e-03]
 [1.25496152e-02 9.80842290e-01 6.60809501e-03]
 [7.14923048e-03 1.62573757e-03 9.91225032e-01]]
pi = [8.52894787e-01 2.45148942e-08 1.47105188e-01]
Iter 15: LL=-1304811.21 | Rates: N=0.93533, AF=0.09702, OLD=0.09665, YOUNG=0.03523
A =
[[9.96688019e-01 9.53348036e-04 2.35863327e-03]
 [1.27675102e-02 9.80032744e-01 7.19974541e-03]
 [7.16634880e-03 1.66239741e-03 9.91171254e-01]]
pi = [8.52903049e-01 5.97242425e-09 1.47096945e-01]
Final Global Rates (lambdas): [0.93532629 0.09702061 0.09664557 0.03523147]
Final transition matrix A:
[[9.96688019e-01 9.53348036e-04 2.35863327e-03]
 [1.27675102e-02 9.80032744e-01 7.19974541e-03]
 [7.16634880e-03 1.66239741e-03 9.91171254e-01]]
Final initial distribution pi:
[8.52903049e-01 5.97242425e-09 1.47096945e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4217  0.1399  0.2101   10434340.0   14311660.0  64142385.0
Archaic_young     0.7516  0.9234  0.8287  199609639.0   65973361.0  16557144.0
Modern            0.0000  0.0000  0.0000          0.0  709671000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         704432          173           2194
Archaic_old      1844        10439          62833
Archaic_young    3395        14134         200556

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3955  0.2402  0.2988
Archaic_young     0.7334  0.8453  0.7854

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         723615          430           2358
Archaic_old      1798        18294          56590
Archaic_young    3812        27455         165648

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 18
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1621132.08 | Rates: N=0.94320, AF=0.09602, OLD=0.06568, YOUNG=0.04649
A =
[[0.99658273 0.00135914 0.00205813]
 [0.00977539 0.98778391 0.0024407 ]
 [0.00918676 0.00152606 0.98928718]]
pi = [0.70933566 0.12383738 0.16682696]
Iter 2: LL=-1312496.31 | Rates: N=0.94349, AF=0.09582, OLD=0.07152, YOUNG=0.04298
A =
[[0.99660196 0.00135204 0.002046  ]
 [0.01022549 0.98728515 0.00248936]
 [0.00882466 0.00144668 0.98972866]]
pi = [0.70627467 0.14058733 0.153138  ]
Iter 3: LL=-1312402.74 | Rates: N=0.94350, AF=0.09577, OLD=0.07740, YOUNG=0.04075
A =
[[0.99660172 0.00135471 0.00204357]
 [0.01076131 0.98666916 0.00256953]
 [0.00857216 0.00139914 0.99002869]]
pi = [0.70526043 0.15827694 0.13646263]
Iter 4: LL=-1312344.84 | Rates: N=0.94350, AF=0.09572, OLD=0.08194, YOUNG=0.03964
A =
[[0.99659981 0.00134645 0.00205374]
 [0.01127369 0.98598771 0.00273861]
 [0.00837961 0.00138915 0.99023124]]
pi = [0.70384544 0.17161942 0.12453514]
Iter 5: LL=-1312317.54 | Rates: N=0.94350, AF=0.09569, OLD=0.08535, YOUNG=0.03927
A =
[[0.99659796 0.00132615 0.0020759 ]
 [0.01171562 0.98529385 0.00299053]
 [0.00825292 0.00141083 0.99033624]]
pi = [0.70242773 0.17861097 0.1189613 ]
Iter 6: LL=-1312302.66 | Rates: N=0.94350, AF=0.09566, OLD=0.08811, YOUNG=0.03925
A =
[[0.99659654 0.00129653 0.00210694]
 [0.01208633 0.98460722 0.00330645]
 [0.00817791 0.00145215 0.99036995]]
pi = [0.70130487 0.18005195 0.11864318]
Iter 7: LL=-1312291.42 | Rates: N=0.94350, AF=0.09564, OLD=0.09057, YOUNG=0.03938
A =
[[0.99659553 0.0012608  0.00214367]
 [0.01240146 0.98392624 0.0036723 ]
 [0.00813806 0.00150452 0.99035743]]
pi = [0.70049872 0.17762992 0.12187136]
Iter 8: LL=-1312281.15 | Rates: N=0.94350, AF=0.09563, OLD=0.09295, YOUNG=0.03956
A =
[[0.99659482 0.00122144 0.00218373]
 [0.01267868 0.98324052 0.0040808 ]
 [0.00812058 0.00156305 0.99031636]]
pi = [0.6999277  0.17298388 0.12708842]
Iter 9: LL=-1312271.09 | Rates: N=0.94350, AF=0.09561, OLD=0.09534, YOUNG=0.03976
A =
[[0.99659433 0.00118013 0.00222554]
 [0.01293331 0.98253734 0.00452936]
 [0.00811673 0.00162503 0.99025825]]
pi = [0.69950247 0.16743485 0.13306268]
Iter 10: LL=-1312261.04 | Rates: N=0.94350, AF=0.09560, OLD=0.09780, YOUNG=0.03997
A =
[[0.99659396 0.00113796 0.00226808]
 [0.01317745 0.98180442 0.00501813]
 [0.00812077 0.00168883 0.9901904 ]]
pi = [0.69914872 0.16192303 0.13892826]
Iter 11: LL=-1312250.93 | Rates: N=0.94350, AF=0.09559, OLD=0.10037, YOUNG=0.04018
A =
[[0.99659369 0.00109564 0.00231066]
 [0.01342035 0.98103071 0.00554894]
 [0.0081291  0.00175344 0.99011746]]
pi = [0.69880868 0.15702241 0.14416891]
Iter 12: LL=-1312240.72 | Rates: N=0.94350, AF=0.09557, OLD=0.10307, YOUNG=0.04038
A =
[[0.99659349 0.00105367 0.00235285]
 [0.01366894 0.98020639 0.00612467]
 [0.00813952 0.00181815 0.99004233]]
pi = [0.69843971 0.15301173 0.14854857]
Iter 13: LL=-1312230.38 | Rates: N=0.94350, AF=0.09556, OLD=0.10594, YOUNG=0.04058
A =
[[0.99659332 0.00101236 0.00239432]
 [0.01392834 0.97932256 0.00674909]
 [0.00815072 0.00188241 0.98996687]]
pi = [0.69801204 0.14997091 0.15201706]
Iter 14: LL=-1312219.90 | Rates: N=0.94350, AF=0.09555, OLD=0.10897, YOUNG=0.04079
A =
[[9.96593187e-01 9.71956361e-04 2.43485704e-03]
 [1.42023415e-02 9.78370862e-01 7.42679694e-03]
 [8.16200437e-03 1.94577590e-03 9.89892220e-01]]
pi = [0.69750579 0.14786861 0.15462559]
Iter 15: LL=-1312209.26 | Rates: N=0.94350, AF=0.09553, OLD=0.11221, YOUNG=0.04099
A =
[[9.96593077e-01 9.32641542e-04 2.47428114e-03]
 [1.44937041e-02 9.77343115e-01 8.16318090e-03]
 [8.17308687e-03 2.00783869e-03 9.89819074e-01]]
pi = [0.69690761 0.14662353 0.15646885]
Final Global Rates (lambdas): [0.94349929 0.09553177 0.11220923 0.04098667]
Final transition matrix A:
[[9.96593077e-01 9.32641542e-04 2.47428114e-03]
 [1.44937041e-02 9.77343115e-01 8.16318090e-03]
 [8.17308687e-03 2.00783869e-03 9.89819074e-01]]
Final initial distribution pi:
[0.69690761 0.14662353 0.15646885]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4198  0.1374  0.2070   10443856.0   14434144.0  65592076.0
Archaic_young     0.7245  0.9140  0.8083  178128762.0   67722238.0  16751178.0
Modern            0.0000  0.0000  0.0000          0.0  729271000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         723601          459           2343
Archaic_old      1795        10459          64428
Archaic_young    3875        13960         179080

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3486  0.1893  0.2454
Archaic_young     0.7258  0.8491  0.7826

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         713456          215           2543
Archaic_old      2408        14749          61580
Archaic_young    4396        27418         173235

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1625909.47 | Rates: N=0.93900, AF=0.09754, OLD=0.07290, YOUNG=0.05221
A =
[[0.99622044 0.00146777 0.00231179]
 [0.0100844  0.98717894 0.00273665]
 [0.00979869 0.00170112 0.98850018]]
pi = [0.6551392  0.12074505 0.22411575]
Iter 2: LL=-1320158.27 | Rates: N=0.93929, AF=0.09738, OLD=0.07985, YOUNG=0.04778
A =
[[0.99626047 0.00144143 0.0022981 ]
 [0.01032944 0.98685607 0.00281448]
 [0.00946374 0.00164545 0.98889081]]
pi = [0.65324353 0.09965955 0.24709692]
Iter 3: LL=-1320029.61 | Rates: N=0.93929, AF=0.09733, OLD=0.08716, YOUNG=0.04486
A =
[[0.99626414 0.00142623 0.00230964]
 [0.01070361 0.98632167 0.00297472]
 [0.00926441 0.0016342  0.98910139]]
pi = [0.65331669 0.0735805  0.27310281]
Iter 4: LL=-1319944.93 | Rates: N=0.93929, AF=0.09727, OLD=0.09309, YOUNG=0.04339
A =
[[0.99626425 0.00139643 0.00233932]
 [0.01109614 0.98560951 0.00329434]
 [0.00910562 0.00167393 0.98922045]]
pi = [0.65350099 0.04881938 0.29767963]
Iter 5: LL=-1319900.52 | Rates: N=0.93928, AF=0.09722, OLD=0.09787, YOUNG=0.04286
A =
[[0.99626356 0.00135369 0.00238275]
 [0.01146229 0.98477657 0.00376115]
 [0.0089962  0.00175391 0.9892499 ]]
pi = [0.65366883 0.02987237 0.3164588 ]
Iter 6: LL=-1319871.30 | Rates: N=0.93928, AF=0.09718, OLD=0.10207, YOUNG=0.04281
A =
[[0.99626282 0.00130214 0.00243504]
 [0.01179445 0.9838587  0.00434685]
 [0.00892736 0.00185477 0.98921787]]
pi = [0.65377853 0.01729629 0.32892519]
Iter 7: LL=-1319846.10 | Rates: N=0.93928, AF=0.09715, OLD=0.10609, YOUNG=0.04296
A =
[[0.99626221 0.00124566 0.00249213]
 [0.01209789 0.98287186 0.00503025]
 [0.00888754 0.00196313 0.98914933]]
pi = [0.65383396 0.00964596 0.33652008]
Iter 8: LL=-1319822.04 | Rates: N=0.93928, AF=0.09712, OLD=0.11013, YOUNG=0.04320
A =
[[0.99626169 0.00118718 0.00255113]
 [0.01238047 0.98182074 0.0057988 ]
 [0.00886743 0.0020714  0.98906117]]
pi = [0.65385422 0.00524056 0.34090523]
Iter 9: LL=-1319798.65 | Rates: N=0.93928, AF=0.09709, OLD=0.11429, YOUNG=0.04348
A =
[[0.9962612  0.00112875 0.00261005]
 [0.01264978 0.98070469 0.00664554]
 [0.00886031 0.0021754  0.98896429]]
pi = [0.6538564 0.0027955 0.3433481]
Iter 10: LL=-1319775.95 | Rates: N=0.93928, AF=0.09707, OLD=0.11861, YOUNG=0.04377
A =
[[0.99626068 0.00107173 0.00266759]
 [0.01291298 0.9795202  0.00756683]
 [0.00886142 0.00227274 0.98886584]]
pi = [0.65385162 0.00147323 0.34467515]
Iter 11: LL=-1319754.02 | Rates: N=0.93928, AF=0.09704, OLD=0.12313, YOUNG=0.04406
A =
[[0.99626007 0.00101704 0.00272289]
 [0.01317733 0.97826142 0.00856125]
 [0.00886734 0.00236211 0.98877056]]
pi = [0.65384596 0.00077114 0.3453829 ]
Iter 12: LL=-1319732.88 | Rates: N=0.93928, AF=0.09701, OLD=0.12788, YOUNG=0.04437
A =
[[9.96259297e-01 9.65243296e-04 2.77545945e-03]
 [1.34506683e-02 9.76920029e-01 9.62930232e-03]
 [8.87558797e-03 2.44278649e-03 9.88681626e-01]]
pi = [6.53842238e-01 4.02854114e-04 3.45754908e-01]
Iter 13: LL=-1319712.43 | Rates: N=0.93927, AF=0.09698, OLD=0.13292, YOUNG=0.04468
A =
[[9.96258298e-01 9.16641504e-04 2.82506078e-03]
 [1.37417617e-02 9.75484785e-01 1.07734529e-02]
 [8.88438757e-03 2.51445490e-03 9.88601158e-01]]
pi = [6.53841371e-01 2.10984976e-04 3.45947644e-01]
Iter 14: LL=-1319692.48 | Rates: N=0.93927, AF=0.09694, OLD=0.13831, YOUNG=0.04499
A =
[[9.96256971e-01 8.71351791e-04 2.87167705e-03]
 [1.40608033e-02 9.73940629e-01 1.19985674e-02]
 [8.89246080e-03 2.57698149e-03 9.88530558e-01]]
pi = [6.53843350e-01 1.11225298e-04 3.46045425e-01]
Iter 15: LL=-1319672.71 | Rates: N=0.93927, AF=0.09690, OLD=0.14418, YOUNG=0.04531
A =
[[9.96255208e-01 8.29345170e-04 2.91544635e-03]
 [1.44200204e-02 9.72267164e-01 1.33128152e-02]
 [8.89890179e-03 2.63028450e-03 9.88470814e-01]]
pi = [6.53847773e-01 5.92364496e-05 3.46092991e-01]
Final Global Rates (lambdas): [0.93927184 0.09690085 0.14417594 0.04531095]
Final transition matrix A:
[[9.96255208e-01 8.29345170e-04 2.91544635e-03]
 [1.44200204e-02 9.72267164e-01 1.33128152e-02]
 [8.89890179e-03 2.63028450e-03 9.88470814e-01]]
Final initial distribution pi:
[6.53847773e-01 5.92364496e-05 3.46092991e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3752  0.0911  0.1466    7106196.0   11832804.0  70932067.0
Archaic_young     0.7211  0.9304  0.8125  188753572.0   72996428.0  14127821.0
Modern            0.0000  0.0000  0.0000          0.0  719311000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         713199          493           2522
Archaic_old      2178         7113          69446
Archaic_young    3934        11333         189782

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3256  0.5473  0.4083
Archaic_young     0.7638  0.5665  0.6505

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         730118         1104           1066
Archaic_old      1555        40326          32168
Archaic_young    2313        82026         109324

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1613486.32 | Rates: N=0.94903, AF=0.09565, OLD=0.05367, YOUNG=0.03124
A =
[[0.99734849 0.00138381 0.0012677 ]
 [0.00778345 0.99092921 0.00128735]
 [0.00712648 0.00130993 0.99156358]]
pi = [0.79997731 0.07663463 0.12338805]
Iter 2: LL=-1299861.76 | Rates: N=0.94927, AF=0.09544, OLD=0.05643, YOUNG=0.02982
A =
[[0.99734502 0.00137052 0.00128446]
 [0.00824141 0.99037283 0.00138576]
 [0.00674002 0.00126094 0.99199905]]
pi = [0.80100167 0.06074656 0.13825177]
Iter 3: LL=-1299832.99 | Rates: N=0.94927, AF=0.09542, OLD=0.05864, YOUNG=0.02926
A =
[[0.99734427 0.00135619 0.00129953]
 [0.00861036 0.98988925 0.00150039]
 [0.0065088  0.00126741 0.99222379]]
pi = [0.80097238 0.04804775 0.15097987]
Iter 4: LL=-1299819.29 | Rates: N=0.94927, AF=0.09540, OLD=0.06027, YOUNG=0.02912
A =
[[0.99734363 0.0013363  0.00132008]
 [0.00890558 0.98945489 0.00163953]
 [0.00636266 0.00130383 0.9923335 ]]
pi = [0.80094886 0.03800425 0.16104688]
Iter 5: LL=-1299811.21 | Rates: N=0.94927, AF=0.09539, OLD=0.06157, YOUNG=0.02918
A =
[[0.99734307 0.00131174 0.00134519]
 [0.00914607 0.98905457 0.00179936]
 [0.00627139 0.00135628 0.99237233]]
pi = [0.8009424  0.03018224 0.16887536]
Iter 6: LL=-1299804.86 | Rates: N=0.94927, AF=0.09538, OLD=0.06271, YOUNG=0.02932
A =
[[0.99734264 0.00128388 0.00137347]
 [0.00934933 0.9886737  0.00197697]
 [0.0062148  0.00141636 0.99236884]]
pi = [0.80094416 0.02407587 0.17497998]
Iter 7: LL=-1299799.05 | Rates: N=0.94927, AF=0.09537, OLD=0.06378, YOUNG=0.02948
A =
[[0.99734232 0.0012539  0.00140379]
 [0.0095281  0.98830091 0.002171  ]
 [0.00618054 0.00147945 0.99234001]]
pi = [0.80094911 0.01927323 0.17977766]
Iter 8: LL=-1299793.41 | Rates: N=0.94927, AF=0.09536, OLD=0.06485, YOUNG=0.02965
A =
[[0.99734206 0.00122261 0.00143533]
 [0.00969107 0.98792774 0.00238119]
 [0.00616105 0.00154298 0.99229597]]
pi = [0.800955   0.01546958 0.18357541]
Iter 9: LL=-1299787.82 | Rates: N=0.94927, AF=0.09536, OLD=0.06593, YOUNG=0.02982
A =
[[0.99734185 0.0011906  0.00146755]
 [0.00984417 0.98754787 0.00260795]
 [0.00615165 0.00160543 0.99224292]]
pi = [0.80096095 0.01244275 0.1865963 ]
Iter 10: LL=-1299782.25 | Rates: N=0.94927, AF=0.09535, OLD=0.06704, YOUNG=0.02998
A =
[[0.99734167 0.00115826 0.00150007]
 [0.00999151 0.98715645 0.00285204]
 [0.00614941 0.0016658  0.9921848 ]]
pi = [0.80096667 0.01002829 0.18900504]
Iter 11: LL=-1299776.66 | Rates: N=0.94927, AF=0.09535, OLD=0.06820, YOUNG=0.03015
A =
[[0.99734151 0.00112585 0.00153264]
 [0.01013593 0.98674962 0.00311445]
 [0.00615239 0.00172342 0.99212419]]
pi = [0.80097213 0.00810148 0.1909264 ]
Iter 12: LL=-1299771.06 | Rates: N=0.94927, AF=0.09534, OLD=0.06941, YOUNG=0.03031
A =
[[0.99734136 0.00109358 0.00156507]
 [0.01027953 0.98632417 0.0033963 ]
 [0.00615936 0.00177781 0.99206283]]
pi = [0.8009774  0.00656539 0.19245721]
Iter 13: LL=-1299765.42 | Rates: N=0.94927, AF=0.09533, OLD=0.07068, YOUNG=0.03047
A =
[[0.9973412  0.00106156 0.00159724]
 [0.01042384 0.9858773  0.00369887]
 [0.00616944 0.00182862 0.99200194]]
pi = [0.80098258 0.0053433  0.19367412]
Iter 14: LL=-1299759.75 | Rates: N=0.94927, AF=0.09533, OLD=0.07202, YOUNG=0.03063
A =
[[0.99734104 0.00102992 0.00162904]
 [0.01057006 0.98540638 0.00402356]
 [0.00618205 0.00187559 0.99194236]]
pi = [0.80098776 0.00437373 0.19463851]
Iter 15: LL=-1299754.02 | Rates: N=0.94928, AF=0.09532, OLD=0.07342, YOUNG=0.03080
A =
[[0.99734086 0.00099872 0.00166042]
 [0.0107192  0.98490889 0.00437191]
 [0.00619675 0.00191855 0.9918847 ]]
pi = [0.80099303 0.00360708 0.19539989]
Final Global Rates (lambdas): [0.94927501 0.09531867 0.0734194  0.03079778]
Final transition matrix A:
[[0.99734086 0.00099872 0.00166042]
 [0.0107192  0.98490889 0.00437191]
 [0.00619675 0.00191855 0.9918847 ]]
Final initial distribution pi:
[0.80099303 0.00360708 0.19539989]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3821  0.2302  0.2873   16906710.0   27335290.0  56541797.0
Archaic_young     0.7390  0.8538  0.7923  164104373.0   57951627.0  28090221.0
Modern            0.0000  0.0000  0.0000          0.0  733702000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         730103          567           1618
Archaic_old      1389        16974          55686
Archaic_young    2210        26701         164752

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3652  0.4835  0.4161
Archaic_young     0.7972  0.7091  0.7506

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         721866          762           1485
Archaic_old      1796        33744          34690
Archaic_young    2784        57641         145232

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1609217.55 | Rates: N=0.94382, AF=0.09516, OLD=0.05685, YOUNG=0.03408
A =
[[0.99697528 0.00142213 0.00160258]
 [0.00874033 0.9895592  0.00170047]
 [0.00775367 0.00133709 0.99090923]]
pi = [0.80019567 0.05483859 0.14496574]
Iter 2: LL=-1300909.70 | Rates: N=0.94409, AF=0.09496, OLD=0.06023, YOUNG=0.03203
A =
[[0.99697667 0.00139392 0.00162941]
 [0.00905516 0.98913971 0.00180513]
 [0.00752856 0.0012777  0.99119373]]
pi = [0.80199041 0.02691826 0.17109132]
Iter 3: LL=-1300870.37 | Rates: N=0.94410, AF=0.09494, OLD=0.06312, YOUNG=0.03111
A =
[[0.996976   0.00136794 0.00165606]
 [0.00929303 0.98876755 0.00193943]
 [0.0074209  0.0012642  0.99131489]]
pi = [0.80174831 0.01129762 0.18695407]
Iter 4: LL=-1300851.83 | Rates: N=0.94410, AF=0.09492, OLD=0.06531, YOUNG=0.03077
A =
[[0.99697522 0.00133598 0.00168881]
 [0.00948236 0.98839777 0.00211987]
 [0.00736057 0.00127433 0.9913651 ]]
pi = [0.80162116 0.00424549 0.19413334]
Iter 5: LL=-1300841.29 | Rates: N=0.94410, AF=0.09490, OLD=0.06710, YOUNG=0.03074
A =
[[0.99697455 0.00129991 0.00172554]
 [0.00963397 0.98802884 0.00233719]
 [0.00733203 0.00129789 0.99137008]]
pi = [0.80158834 0.0014785  0.19693317]
Iter 6: LL=-1300833.07 | Rates: N=0.94410, AF=0.09488, OLD=0.06870, YOUNG=0.03085
A =
[[0.99697405 0.0012615  0.00176445]
 [0.00975838 0.98765783 0.00258379]
 [0.00732373 0.00132813 0.99134814]]
pi = [8.01594701e-01 4.86231893e-04 1.97919067e-01]
Iter 7: LL=-1300825.47 | Rates: N=0.94410, AF=0.09487, OLD=0.07023, YOUNG=0.03100
A =
[[0.99697368 0.00122202 0.0018043 ]
 [0.00986368 0.987281   0.00285532]
 [0.00732806 0.00136143 0.99131051]]
pi = [8.01616986e-01 1.52667631e-04 1.98230346e-01]
Iter 8: LL=-1300818.07 | Rates: N=0.94410, AF=0.09486, OLD=0.07175, YOUNG=0.03118
A =
[[0.99697339 0.00118228 0.00184433]
 [0.00995589 0.98689435 0.00314976]
 [0.00734012 0.00139593 0.99126396]]
pi = [8.01645908e-01 4.60705710e-05 1.98308021e-01]
Iter 9: LL=-1300810.76 | Rates: N=0.94410, AF=0.09485, OLD=0.07331, YOUNG=0.03137
A =
[[0.99697317 0.00114279 0.00188404]
 [0.01003955 0.98649397 0.00346649]
 [0.00735668 0.00143066 0.99121265]]
pi = [8.01677624e-01 1.34201502e-05 1.98308956e-01]
Iter 10: LL=-1300803.52 | Rates: N=0.94411, AF=0.09484, OLD=0.07491, YOUNG=0.03155
A =
[[0.99697299 0.00110387 0.00192314]
 [0.01011817 0.98607616 0.00380568]
 [0.00737563 0.00146512 0.99115925]]
pi = [8.01710465e-01 3.78532374e-06 1.98285750e-01]
Iter 11: LL=-1300796.34 | Rates: N=0.94411, AF=0.09482, OLD=0.07657, YOUNG=0.03174
A =
[[0.99697285 0.0010657  0.00196145]
 [0.0101945  0.98563752 0.00416798]
 [0.00739555 0.00149901 0.99110544]]
pi = [8.01743655e-01 1.03645567e-06 1.98255308e-01]
Iter 12: LL=-1300789.21 | Rates: N=0.94411, AF=0.09481, OLD=0.07831, YOUNG=0.03192
A =
[[0.99697274 0.00102841 0.00199885]
 [0.01027071 0.98517494 0.00455435]
 [0.00741553 0.00153212 0.99105235]]
pi = [8.01776804e-01 2.76102849e-07 1.98222920e-01]
Iter 13: LL=-1300782.11 | Rates: N=0.94411, AF=0.09480, OLD=0.08011, YOUNG=0.03210
A =
[[9.96972663e-01 9.92043043e-04 2.03529354e-03]
 [1.03485230e-02 9.84685541e-01 4.96593651e-03]
 [7.43500326e-03 1.56433074e-03 9.91000666e-01]]
pi = [8.01809693e-01 7.17122322e-08 1.98190236e-01]
Iter 14: LL=-1300775.04 | Rates: N=0.94411, AF=0.09479, OLD=0.08201, YOUNG=0.03228
A =
[[9.96972615e-01 9.56627712e-04 2.07075757e-03]
 [1.04292730e-02 9.84166713e-01 5.40401432e-03]
 [7.45363133e-03 1.59551443e-03 9.90950854e-01]]
pi = [8.01842194e-01 1.81990809e-08 1.98157788e-01]
Iter 15: LL=-1300767.99 | Rates: N=0.94411, AF=0.09478, OLD=0.08400, YOUNG=0.03246
A =
[[9.96972594e-01 9.22152713e-04 2.10525314e-03]
 [1.05139865e-02 9.83616089e-01 5.86992496e-03]
 [7.47125951e-03 1.62555105e-03 9.90903189e-01]]
pi = [8.01874229e-01 4.52266756e-09 1.98125766e-01]
Final Global Rates (lambdas): [0.94410773 0.09477552 0.08399794 0.03246133]
Final transition matrix A:
[[9.96972594e-01 9.22152713e-04 2.10525314e-03]
 [1.05139865e-02 9.83616089e-01 5.86992496e-03]
 [7.47125951e-03 1.62555105e-03 9.90903189e-01]]
Final initial distribution pi:
[8.01874229e-01 4.52266756e-09 1.98125766e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5025  0.2407  0.3255   16753549.0   16585451.0  52850472.0
Archaic_young     0.7738  0.9094  0.8361  185484295.0   54220705.0  18473587.0
Modern            0.0000  0.0000  0.0000          0.0  726956000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         722060          113           1940
Archaic_old      1988        16760          51482
Archaic_young    2908        16466         186283

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3866  0.4489  0.4154
Archaic_young     0.7986  0.7561  0.7767

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         706042          797           1830
Archaic_old      1952        32650          38644
Archaic_young    3065        50834         164186

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1606079.05 | Rates: N=0.93598, AF=0.09552, OLD=0.06278, YOUNG=0.03856
A =
[[0.99653183 0.00156698 0.00190119]
 [0.00943143 0.98852534 0.00204323]
 [0.00821959 0.00144099 0.99033943]]
pi = [0.79776933 0.07340976 0.12882091]
Iter 2: LL=-1304779.69 | Rates: N=0.93626, AF=0.09535, OLD=0.06713, YOUNG=0.03583
A =
[[0.9965441  0.00155285 0.00190306]
 [0.00982773 0.98800933 0.00216294]
 [0.00792189 0.0013667  0.99071141]]
pi = [0.80266834 0.05931177 0.13801989]
Iter 3: LL=-1304718.78 | Rates: N=0.93626, AF=0.09533, OLD=0.07073, YOUNG=0.03447
A =
[[0.99654412 0.00154851 0.00190737]
 [0.01013479 0.98754612 0.00231908]
 [0.00777644 0.00135865 0.99086491]]
pi = [0.80281825 0.04703879 0.15014296]
Iter 4: LL=-1304692.11 | Rates: N=0.93626, AF=0.09530, OLD=0.07325, YOUNG=0.03388
A =
[[0.99654359 0.00153602 0.00192039]
 [0.01037517 0.98708528 0.00253954]
 [0.00768657 0.00139008 0.99092335]]
pi = [0.80269009 0.03614947 0.16116045]
Iter 5: LL=-1304679.52 | Rates: N=0.93626, AF=0.09528, OLD=0.07514, YOUNG=0.03369
A =
[[0.99654321 0.00151669 0.0019401 ]
 [0.01056621 0.9866241  0.00280969]
 [0.00763346 0.00144553 0.99092102]]
pi = [0.80258829 0.02726022 0.1701515 ]
Iter 6: LL=-1304670.90 | Rates: N=0.93626, AF=0.09526, OLD=0.07671, YOUNG=0.03368
A =
[[0.996543   0.00149271 0.00196429]
 [0.01072448 0.98615926 0.00311626]
 [0.00760348 0.00151417 0.99088235]]
pi = [0.80252415 0.02031901 0.17715684]
Iter 7: LL=-1304663.27 | Rates: N=0.93626, AF=0.09525, OLD=0.07816, YOUNG=0.03374
A =
[[0.99654291 0.00146579 0.0019913 ]
 [0.01086145 0.98568751 0.00345104]
 [0.00758797 0.0015899  0.99082213]]
pi = [0.80248473 0.01501288 0.18250239]
Iter 8: LL=-1304655.93 | Rates: N=0.93626, AF=0.09524, OLD=0.07956, YOUNG=0.03383
A =
[[0.9965429  0.00143708 0.00202002]
 [0.0109846  0.985206   0.00380941]
 [0.00758158 0.00166937 0.99074905]]
pi = [0.80245943 0.01100241 0.18653815]
Iter 9: LL=-1304648.73 | Rates: N=0.93626, AF=0.09523, OLD=0.08095, YOUNG=0.03394
A =
[[0.99654294 0.00140733 0.00204973]
 [0.01109872 0.98471257 0.00418871]
 [0.00758103 0.00175061 0.99066836]]
pi = [0.80244216 0.00799567 0.18956217]
Iter 10: LL=-1304641.67 | Rates: N=0.93626, AF=0.09522, OLD=0.08236, YOUNG=0.03405
A =
[[0.996543   0.00137707 0.00207993]
 [0.01120693 0.98420585 0.00458723]
 [0.00758427 0.00183234 0.99058339]]
pi = [0.80242975 0.00575877 0.19181149]
Iter 11: LL=-1304634.79 | Rates: N=0.93626, AF=0.09521, OLD=0.08378, YOUNG=0.03416
A =
[[0.99654308 0.00134666 0.00211027]
 [0.01131124 0.98368508 0.00500367]
 [0.00759    0.00191367 0.99049634]]
pi = [0.80242064 0.00410841 0.19347096]
Iter 12: LL=-1304628.09 | Rates: N=0.93626, AF=0.09520, OLD=0.08522, YOUNG=0.03427
A =
[[0.99654316 0.00131637 0.00214048]
 [0.01141301 0.98315004 0.00543695]
 [0.00759736 0.00199391 0.99040874]]
pi = [0.80241403 0.00290192 0.19468405]
Iter 13: LL=-1304621.62 | Rates: N=0.93626, AF=0.09519, OLD=0.08667, YOUNG=0.03438
A =
[[0.99654323 0.00128641 0.00217036]
 [0.01151315 0.98260079 0.00588606]
 [0.00760576 0.00207256 0.99032168]]
pi = [0.80240947 0.00202868 0.19556185]
Iter 14: LL=-1304615.38 | Rates: N=0.93626, AF=0.09519, OLD=0.08814, YOUNG=0.03449
A =
[[0.9965433  0.00125693 0.00219977]
 [0.01161236 0.9820375  0.00635014]
 [0.00761479 0.00214924 0.99023598]]
pi = [0.80240665 0.00140329 0.19619006]
Iter 15: LL=-1304609.40 | Rates: N=0.93626, AF=0.09518, OLD=0.08962, YOUNG=0.03460
A =
[[0.99654336 0.00122805 0.00222858]
 [0.01171121 0.98146039 0.0068284 ]
 [0.00762413 0.00222367 0.9901522 ]]
pi = [0.80240535 0.00096032 0.19663433]
Final Global Rates (lambdas): [0.93625588 0.09517842 0.08961908 0.03459536]
Final transition matrix A:
[[0.99654336 0.00122805 0.00222858]
 [0.01171121 0.98146039 0.0068284 ]
 [0.00762413 0.00222367 0.9901522 ]]
Final initial distribution pi:
[0.80240535 0.00096032 0.19663433]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old        0.463  0.2702  0.3413   19609882.0   22744118.0  52962246.0
Archaic_young      0.779  0.8844  0.8283  191179453.0   54249547.0  24987330.0
Modern             0.000  0.0000  0.0000          0.0  712217000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         706406          198           2065
Archaic_old      2337        19595          51314
Archaic_young    3474        22561         192050

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4630  0.4465  0.4546
Archaic_young     0.7677  0.7671  0.7674

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         719162          160           1931
Archaic_old      3168        36171          42493
Archaic_young    4770        41834         150311

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1624572.60 | Rates: N=0.94124, AF=0.09740, OLD=0.07309, YOUNG=0.04436
A =
[[0.99641292 0.00159084 0.00199624]
 [0.01012754 0.98766678 0.00220569]
 [0.00930924 0.00166093 0.98902983]]
pi = [0.7360928  0.13280884 0.13109836]
Iter 2: LL=-1316899.20 | Rates: N=0.94154, AF=0.09723, OLD=0.07995, YOUNG=0.04042
A =
[[0.99643726 0.00154551 0.00201723]
 [0.01064272 0.98705731 0.00229997]
 [0.00886958 0.00156768 0.98956274]]
pi = [0.73687578 0.16181145 0.10131277]
Iter 3: LL=-1316787.07 | Rates: N=0.94154, AF=0.09718, OLD=0.08565, YOUNG=0.03871
A =
[[0.99643895 0.00151106 0.00204999]
 [0.01110534 0.98644171 0.00245295]
 [0.00864657 0.00156291 0.98979052]]
pi = [0.73516864 0.18593866 0.0788927 ]
Iter 4: LL=-1316740.15 | Rates: N=0.94153, AF=0.09712, OLD=0.08977, YOUNG=0.03821
A =
[[0.99643858 0.00146635 0.00209506]
 [0.01149583 0.98580527 0.0026989 ]
 [0.00851166 0.00160684 0.98988149]]
pi = [0.73321599 0.20044106 0.06634295]
Iter 5: LL=-1316717.28 | Rates: N=0.94153, AF=0.09709, OLD=0.09305, YOUNG=0.03826
A =
[[0.9964381  0.0014142  0.0021477 ]
 [0.01182459 0.98515993 0.00301548]
 [0.00843541 0.00167265 0.98989194]]
pi = [0.73172721 0.20843286 0.05983993]
Iter 6: LL=-1316700.27 | Rates: N=0.94153, AF=0.09706, OLD=0.09600, YOUNG=0.03851
A =
[[0.99643781 0.00135817 0.00220403]
 [0.012108   0.98450643 0.00338557]
 [0.00839667 0.00174485 0.98985848]]
pi = [0.73060955 0.21298625 0.0564042 ]
Iter 7: LL=-1316684.74 | Rates: N=0.94153, AF=0.09704, OLD=0.09887, YOUNG=0.03883
A =
[[0.99643769 0.00130075 0.00226157]
 [0.01235983 0.983839   0.00380117]
 [0.00838182 0.00181653 0.98980165]]
pi = [0.72968692 0.21583657 0.0544765 ]
Iter 8: LL=-1316669.74 | Rates: N=0.94153, AF=0.09701, OLD=0.10179, YOUNG=0.03917
A =
[[0.99643767 0.00124346 0.00231887]
 [0.01259128 0.98314861 0.00426011]
 [0.00838208 0.00188488 0.98973304]]
pi = [0.72885557 0.21782902 0.05331541]
Iter 9: LL=-1316655.00 | Rates: N=0.94153, AF=0.09699, OLD=0.10483, YOUNG=0.03951
A =
[[0.99643768 0.0011872  0.00237511]
 [0.01281171 0.98242479 0.0047635 ]
 [0.00839167 0.00194889 0.98965944]]
pi = [0.72806314 0.21935861 0.05257825]
Iter 10: LL=-1316640.39 | Rates: N=0.94153, AF=0.09697, OLD=0.10802, YOUNG=0.03985
A =
[[0.99643768 0.00113249 0.00242983]
 [0.01302916 0.98165658 0.00531426]
 [0.00840679 0.00200826 0.98958496]]
pi = [0.727282   0.22060545 0.05211255]
Iter 11: LL=-1316625.82 | Rates: N=0.94153, AF=0.09695, OLD=0.11140, YOUNG=0.04018
A =
[[0.99643761 0.00107961 0.00248279]
 [0.01325059 0.98083287 0.00591654]
 [0.00842488 0.00206301 0.98951211]]
pi = [0.72649578 0.22164535 0.05185888]
Iter 12: LL=-1316611.17 | Rates: N=0.94153, AF=0.09692, OLD=0.11502, YOUNG=0.04052
A =
[[0.99643743 0.00102872 0.00253385]
 [0.0134822  0.97994239 0.00657541]
 [0.00844428 0.0021133  0.98944243]]
pi = [0.72569361 0.2225001  0.0518063 ]
Iter 13: LL=-1316596.36 | Rates: N=0.94153, AF=0.09690, OLD=0.11891, YOUNG=0.04085
A =
[[9.96437117e-01 9.79942044e-04 2.58294089e-03]
 [1.37295971e-02 9.78973590e-01 7.29681288e-03]
 [8.46388974e-03 2.15932027e-03 9.89376790e-01]]
pi = [0.72486767 0.22316018 0.05197216]
Iter 14: LL=-1316581.28 | Rates: N=0.94152, AF=0.09687, OLD=0.12311, YOUNG=0.04118
A =
[[9.96436642e-01 9.33322029e-04 2.63003644e-03]
 [1.39979832e-02 9.77914252e-01 8.08776478e-03]
 [8.48304043e-03 2.20131294e-03 9.89315647e-01]]
pi = [0.72401213 0.22359466 0.05239321]
Iter 15: LL=-1316565.80 | Rates: N=0.94152, AF=0.09684, OLD=0.12769, YOUNG=0.04151
A =
[[9.96435974e-01 8.88915468e-04 2.67511069e-03]
 [1.42925077e-02 9.76750781e-01 8.95671180e-03]
 [8.50132951e-03 2.23950341e-03 9.89259167e-01]]
pi = [0.72312255 0.22375535 0.0531221 ]
Final Global Rates (lambdas): [0.94152308 0.09683574 0.12768774 0.04150928]
Final transition matrix A:
[[9.96435974e-01 8.88915468e-04 2.67511069e-03]
 [1.42925077e-02 9.76750781e-01 8.95671180e-03]
 [8.50132951e-03 2.23950341e-03 9.89259167e-01]]
Final initial distribution pi:
[0.72312255 0.22375535 0.0531221 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5786  0.1931  0.2895   15648485.0   11398515.0  65398499.0
Archaic_young     0.7299  0.9290  0.8175  181037549.0   66989451.0  13842391.0
Modern            0.0000  0.0000  0.0000          0.0  724926000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         718716          240           2297
Archaic_old      2432        15670          63730
Archaic_young    3778        11137         182000

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3531  0.6363  0.4542
Archaic_young     0.7894  0.5424  0.6430

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         726770         1558           1051
Archaic_old      1911        48682          26365
Archaic_young    2008        87012         104643

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1619286.68 | Rates: N=0.94958, AF=0.09636, OLD=0.05926, YOUNG=0.03030
A =
[[0.99705583 0.00167787 0.0012663 ]
 [0.00876754 0.99001074 0.00122173]
 [0.00748419 0.00138855 0.99112726]]
pi = [0.69730233 0.13323501 0.16946266]
Iter 2: LL=-1304736.35 | Rates: N=0.94984, AF=0.09615, OLD=0.06259, YOUNG=0.02924
A =
[[0.99704865 0.00163799 0.00131337]
 [0.00938121 0.98923817 0.00138061]
 [0.00701797 0.00131548 0.99166655]]
pi = [0.69704261 0.12301627 0.17994112]
Iter 3: LL=-1304699.91 | Rates: N=0.94984, AF=0.09611, OLD=0.06536, YOUNG=0.02914
A =
[[0.99704721 0.00159378 0.001359  ]
 [0.0098213  0.98862599 0.00155271]
 [0.00680143 0.00132252 0.99187605]]
pi = [0.69708519 0.11569335 0.18722146]
Iter 4: LL=-1304679.50 | Rates: N=0.94985, AF=0.09609, OLD=0.06765, YOUNG=0.02937
A =
[[0.9970463  0.00153993 0.00141377]
 [0.01017423 0.98807332 0.00175245]
 [0.00669362 0.00136231 0.99194407]]
pi = [0.69710106 0.10883607 0.19406287]
Iter 5: LL=-1304663.19 | Rates: N=0.94985, AF=0.09607, OLD=0.06977, YOUNG=0.02972
A =
[[0.99704566 0.00147935 0.00147499]
 [0.01048069 0.98754015 0.00197916]
 [0.00664369 0.00141797 0.99193834]]
pi = [0.69710522 0.10159204 0.20130274]
Iter 6: LL=-1304647.59 | Rates: N=0.94985, AF=0.09605, OLD=0.07191, YOUNG=0.03010
A =
[[0.99704522 0.00141459 0.00154019]
 [0.01076761 0.98699792 0.00223447]
 [0.0066248  0.00148125 0.99189394]]
pi = [0.69710704 0.09358016 0.2093128 ]
Iter 7: LL=-1304631.76 | Rates: N=0.94985, AF=0.09603, OLD=0.07416, YOUNG=0.03047
A =
[[0.99704489 0.00134745 0.00160766]
 [0.01105293 0.9864248  0.00252226]
 [0.00662289 0.00154786 0.99182925]]
pi = [0.6971118  0.08462975 0.21825845]
Iter 8: LL=-1304615.35 | Rates: N=0.94985, AF=0.09602, OLD=0.07659, YOUNG=0.03084
A =
[[0.99704461 0.00127917 0.00167622]
 [0.01134919 0.98580263 0.00284819]
 [0.00663051 0.00161523 0.99175426]]
pi = [0.69712234 0.0746835  0.22819416]
Iter 9: LL=-1304598.18 | Rates: N=0.94985, AF=0.09601, OLD=0.07925, YOUNG=0.03121
A =
[[0.99704434 0.00121066 0.001745  ]
 [0.01166572 0.98511494 0.00321934]
 [0.00664372 0.00168159 0.99167469]]
pi = [0.6971403  0.06379126 0.23906845]
Iter 10: LL=-1304580.09 | Rates: N=0.94985, AF=0.09599, OLD=0.08219, YOUNG=0.03157
A =
[[0.99704407 0.0011426  0.00181333]
 [0.01200974 0.9843462  0.00364406]
 [0.00666057 0.00174555 0.99159389]]
pi = [0.69716654 0.05216205 0.25067141]
Iter 11: LL=-1304560.98 | Rates: N=0.94985, AF=0.09597, OLD=0.08547, YOUNG=0.03192
A =
[[0.9970438  0.00107554 0.00188066]
 [0.01238619 0.98348233 0.00413148]
 [0.00668028 0.00180598 0.99151374]]
pi = [0.69720107 0.04024778 0.26255116]
Iter 12: LL=-1304540.74 | Rates: N=0.94985, AF=0.09595, OLD=0.08914, YOUNG=0.03227
A =
[[0.99704355 0.00100993 0.00194652]
 [0.01279703 0.98251213 0.00469084]
 [0.0067029  0.00186196 0.99143515]]
pi = [0.69724244 0.02879632 0.27396124]
Iter 13: LL=-1304519.32 | Rates: N=0.94985, AF=0.09593, OLD=0.09325, YOUNG=0.03262
A =
[[9.97043368e-01 9.46143818e-04 2.01048848e-03]
 [1.32408229e-02 9.81428411e-01 5.33076573e-03]
 [6.72880614e-03 1.91281184e-03 9.91358382e-01]]
pi = [0.6972871  0.01875486 0.28395804]
Iter 14: LL=-1304496.77 | Rates: N=0.94985, AF=0.09590, OLD=0.09786, YOUNG=0.03295
A =
[[9.97043260e-01 8.84520603e-04 2.07221977e-03]
 [1.37137796e-02 9.80227057e-01 6.05916349e-03]
 [6.75849043e-03 1.95803727e-03 9.91283472e-01]]
pi = [0.6973292  0.01094467 0.29172613]
Iter 15: LL=-1304473.29 | Rates: N=0.94985, AF=0.09587, OLD=0.10295, YOUNG=0.03328
A =
[[9.97043149e-01 8.25449421e-04 2.13140197e-03]
 [1.42116409e-02 9.78905038e-01 6.88332078e-03]
 [6.79228316e-03 1.99716376e-03 9.91210553e-01]]
pi = [0.6973621  0.00566976 0.29696814]
Final Global Rates (lambdas): [0.94984874 0.09587253 0.10295475 0.03327703]
Final transition matrix A:
[[9.97043149e-01 8.25449421e-04 2.13140197e-03]
 [1.42116409e-02 9.78905038e-01 6.88332078e-03]
 [6.79228316e-03 1.99716376e-03 9.91210553e-01]]
Final initial distribution pi:
[0.6973621  0.00566976 0.29696814]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4282  0.1535  0.2259   11688088.0   15610912.0  64476961.0
Archaic_young     0.7274  0.9135  0.8099  175563310.0   65791690.0  16631284.0
Modern            0.0000  0.0000  0.0000          0.0  731346000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         726867          448           2064
Archaic_old      2250        11706          63002
Archaic_young    2229        15145         176289

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4286  0.5728  0.4903
Archaic_young     0.8092  0.6912  0.7456

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         712822          340           1413
Archaic_old      3246        45286          31236
Archaic_young    4028        60065         141564

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1602410.86 | Rates: N=0.93679, AF=0.09456, OLD=0.06257, YOUNG=0.03325
A =
[[0.9968254  0.00162559 0.00154901]
 [0.00918214 0.9892015  0.00161636]
 [0.00734541 0.00141263 0.99124197]]
pi = [0.75014169 0.1177638  0.13209451]
Iter 2: LL=-1300709.79 | Rates: N=0.93706, AF=0.09438, OLD=0.06665, YOUNG=0.03157
A =
[[0.99683476 0.00156985 0.00159539]
 [0.009756   0.98848333 0.00176067]
 [0.00697994 0.00135839 0.99166167]]
pi = [0.75077328 0.12234673 0.12688   ]
Iter 3: LL=-1300663.75 | Rates: N=0.93706, AF=0.09434, OLD=0.07000, YOUNG=0.03112
A =
[[0.99683314 0.00152181 0.00164505]
 [0.01019084 0.98788433 0.00192483]
 [0.00682671 0.00137538 0.99179792]]
pi = [0.75071535 0.12438715 0.12489749]
Iter 4: LL=-1300640.97 | Rates: N=0.93707, AF=0.09431, OLD=0.07265, YOUNG=0.03115
A =
[[0.99683153 0.00146681 0.00170166]
 [0.01054147 0.98733156 0.00212697]
 [0.00675275 0.0014158  0.99183145]]
pi = [0.75066191 0.12286885 0.12646924]
Iter 5: LL=-1300625.18 | Rates: N=0.93707, AF=0.09429, OLD=0.07495, YOUNG=0.03138
A =
[[0.99683042 0.00140836 0.00176122]
 [0.01083308 0.98680883 0.00235809]
 [0.00672467 0.00146332 0.991812  ]]
pi = [0.75063063 0.11883762 0.13053175]
Iter 6: LL=-1300611.72 | Rates: N=0.93707, AF=0.09427, OLD=0.07709, YOUNG=0.03166
A =
[[0.99682967 0.00134935 0.00182098]
 [0.01108288 0.98630466 0.00261246]
 [0.00672383 0.00151057 0.99176559]]
pi = [0.7506165  0.11328726 0.13609624]
Iter 7: LL=-1300599.47 | Rates: N=0.93707, AF=0.09425, OLD=0.07918, YOUNG=0.03195
A =
[[0.99682913 0.00129156 0.0018793 ]
 [0.0113019  0.98581071 0.00288739]
 [0.0067395  0.00155462 0.99170589]]
pi = [0.75061454 0.10699963 0.14238584]
Iter 8: LL=-1300588.13 | Rates: N=0.93707, AF=0.09424, OLD=0.08125, YOUNG=0.03224
A =
[[0.99682874 0.00123598 0.00193529]
 [0.01149732 0.98532077 0.00318192]
 [0.00676526 0.00159451 0.99164023]]
pi = [0.75062079 0.10056339 0.14881583]
Iter 9: LL=-1300577.58 | Rates: N=0.93707, AF=0.09423, OLD=0.08334, YOUNG=0.03252
A =
[[0.99682843 0.00118311 0.00198846]
 [0.01167404 0.98483006 0.0034959 ]
 [0.00679714 0.00163015 0.99157271]]
pi = [0.75063196 0.0943941  0.15497395]
Iter 10: LL=-1300567.73 | Rates: N=0.93707, AF=0.09422, OLD=0.08544, YOUNG=0.03278
A =
[[0.99682819 0.00113317 0.00203864]
 [0.01183566 0.98433475 0.00382959]
 [0.00683258 0.00166181 0.99150561]]
pi = [0.75064527 0.08875177 0.16060296]
Iter 11: LL=-1300558.52 | Rates: N=0.93707, AF=0.09420, OLD=0.08757, YOUNG=0.03303
A =
[[0.99682799 0.00108621 0.0020858 ]
 [0.01198496 0.9838316  0.00418344]
 [0.00686989 0.00168991 0.9914402 ]]
pi = [0.75065848 0.08376861 0.16557291]
Iter 12: LL=-1300549.88 | Rates: N=0.93707, AF=0.09419, OLD=0.08973, YOUNG=0.03327
A =
[[0.99682782 0.00104214 0.00213003]
 [0.01212429 0.9833177  0.00455801]
 [0.00690793 0.00171489 0.99137717]]
pi = [0.75066993 0.07948582 0.16984425]
Iter 13: LL=-1300541.73 | Rates: N=0.93707, AF=0.09418, OLD=0.09192, YOUNG=0.03350
A =
[[0.99682769 0.00100082 0.00217149]
 [0.01225571 0.98279034 0.00495395]
 [0.00694591 0.00173722 0.99131687]]
pi = [0.75067854 0.07588986 0.17343159]
Iter 14: LL=-1300534.01 | Rates: N=0.93707, AF=0.09416, OLD=0.09416, YOUNG=0.03372
A =
[[9.96827571e-01 9.62052096e-04 2.21037721e-03]
 [1.23811266e-02 9.82246882e-01 5.37199094e-03]
 [6.98328490e-03 1.75729740e-03 9.91259418e-01]]
pi = [0.75068368 0.07294084 0.17637549]
Iter 15: LL=-1300526.66 | Rates: N=0.93707, AF=0.09415, OLD=0.09644, YOUNG=0.03393
A =
[[9.96827474e-01 9.25624952e-04 2.24690096e-03]
 [1.25022910e-02 9.81684775e-01 5.81293386e-03]
 [7.01967967e-03 1.77550513e-03 9.91204815e-01]]
pi = [0.75068499 0.07059062 0.17872439]
Final Global Rates (lambdas): [0.93707198 0.09415197 0.09644302 0.03392856]
Final transition matrix A:
[[9.96827474e-01 9.25624952e-04 2.24690096e-03]
 [1.25022910e-02 9.81684775e-01 5.81293386e-03]
 [7.01967967e-03 1.77550513e-03 9.91204815e-01]]
Final initial distribution pi:
[0.75068499 0.07059062 0.17872439]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5485  0.2503  0.3437   19791600.0   16292400.0  59278618.0
Archaic_young     0.7541  0.9125  0.8258  186120296.0   60684704.0  17837586.0
Modern            0.0000  0.0000  0.0000          0.0  717111000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         712113          373           2089
Archaic_old      2189        19802          57777
Archaic_young    2809        15909         186939

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4067  0.5450  0.4658
Archaic_young     0.8165  0.7053  0.7568

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         703293          238           1496
Archaic_old      3303        41519          32066
Archaic_young    4510        60423         153152

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1606708.68 | Rates: N=0.93508, AF=0.09602, OLD=0.06669, YOUNG=0.03695
A =
[[0.99649942 0.00169362 0.00180697]
 [0.00958478 0.98840449 0.00201073]
 [0.00790578 0.00148516 0.99060907]]
pi = [0.85282722 0.04880776 0.09836502]
Iter 2: LL=-1306002.06 | Rates: N=0.93537, AF=0.09590, OLD=0.07057, YOUNG=0.03451
A =
[[0.99652463 0.00165235 0.00182301]
 [0.0098215  0.98796387 0.00221463]
 [0.00767973 0.00141662 0.99090365]]
pi = [0.85718787 0.03182638 0.11098574]
Iter 3: LL=-1305953.94 | Rates: N=0.93537, AF=0.09587, OLD=0.07359, YOUNG=0.03351
A =
[[0.99652582 0.0016317  0.00184248]
 [0.00995448 0.98759218 0.00245334]
 [0.00763743 0.00142584 0.99093673]]
pi = [0.85714025 0.01892841 0.12393133]
Iter 4: LL=-1305934.62 | Rates: N=0.93537, AF=0.09585, OLD=0.07570, YOUNG=0.03316
A =
[[0.99652576 0.00160631 0.00186793]
 [0.01004305 0.98721149 0.00274546]
 [0.00763119 0.0014667  0.99090211]]
pi = [0.85685437 0.01023399 0.13291164]
Iter 5: LL=-1305923.76 | Rates: N=0.93537, AF=0.09584, OLD=0.07735, YOUNG=0.03311
A =
[[0.99652567 0.00157761 0.00189672]
 [0.01010715 0.98682049 0.00307236]
 [0.0076411  0.00152342 0.99083549]]
pi = [0.85665128 0.00519469 0.13815404]
Iter 6: LL=-1305915.12 | Rates: N=0.93537, AF=0.09583, OLD=0.07878, YOUNG=0.03319
A =
[[0.99652565 0.0015471  0.00192725]
 [0.0101591  0.98641865 0.00342225]
 [0.00765779 0.00158738 0.99075483]]
pi = [0.85653316 0.00253144 0.1409354 ]
Iter 7: LL=-1305907.24 | Rates: N=0.93537, AF=0.09582, OLD=0.08013, YOUNG=0.03332
A =
[[0.99652568 0.0015157  0.00195862]
 [0.01020601 0.98600492 0.00378907]
 [0.00767664 0.00165425 0.99066912]]
pi = [0.85646925 0.00119929 0.14233146]
Iter 8: LL=-1305899.78 | Rates: N=0.93537, AF=0.09582, OLD=0.08146, YOUNG=0.03347
A =
[[0.99652572 0.00148396 0.00199032]
 [0.01025198 0.98557803 0.00416998]
 [0.00769539 0.00172177 0.99058284]]
pi = [8.56435895e-01 5.56009502e-04 1.43008095e-01]
Iter 9: LL=-1305892.66 | Rates: N=0.93537, AF=0.09581, OLD=0.08279, YOUNG=0.03363
A =
[[0.99652577 0.00145217 0.00202206]
 [0.01029943 0.98513684 0.00456373]
 [0.00771297 0.0017887  0.99049833]]
pi = [8.56419319e-01 2.53118229e-04 1.43327563e-01]
Iter 10: LL=-1305885.83 | Rates: N=0.93537, AF=0.09580, OLD=0.08414, YOUNG=0.03380
A =
[[0.99652582 0.00142052 0.00205366]
 [0.01034979 0.98468036 0.00496985]
 [0.00772894 0.00185424 0.99041682]]
pi = [8.56412205e-01 1.13357033e-04 1.43474438e-01]
Iter 11: LL=-1305879.26 | Rates: N=0.93537, AF=0.09580, OLD=0.08551, YOUNG=0.03397
A =
[[0.99652587 0.00138912 0.00208501]
 [0.01040391 0.98420785 0.00538824]
 [0.00774317 0.00191788 0.99033895]]
pi = [8.56410778e-01 4.99947625e-05 1.43539227e-01]
Iter 12: LL=-1305872.94 | Rates: N=0.93537, AF=0.09579, OLD=0.08691, YOUNG=0.03414
A =
[[0.99652591 0.00135806 0.00211604]
 [0.01046228 0.98371874 0.00581898]
 [0.00775573 0.00197921 0.99026505]]
pi = [8.56413064e-01 2.17295392e-05 1.43565206e-01]
Iter 13: LL=-1305866.82 | Rates: N=0.93536, AF=0.09579, OLD=0.08834, YOUNG=0.03431
A =
[[0.99652594 0.00132737 0.0021467 ]
 [0.01052515 0.9832126  0.00626225]
 [0.00776676 0.00203797 0.99019526]]
pi = [8.56417981e-01 9.31179306e-06 1.43572707e-01]
Iter 14: LL=-1305860.90 | Rates: N=0.93536, AF=0.09578, OLD=0.08980, YOUNG=0.03448
A =
[[0.99652596 0.00129708 0.00217697]
 [0.01059263 0.98268906 0.00671831]
 [0.00777644 0.00209395 0.9901296 ]]
pi = [8.56424884e-01 3.93569916e-06 1.43571181e-01]
Iter 15: LL=-1305855.16 | Rates: N=0.93536, AF=0.09577, OLD=0.09131, YOUNG=0.03465
A =
[[0.99652597 0.0012672  0.00220682]
 [0.01066475 0.98214782 0.00718743]
 [0.00778497 0.00214701 0.99006803]]
pi = [8.56433347e-01 1.64105402e-06 1.43565012e-01]
Final Global Rates (lambdas): [0.93536406 0.09577294 0.09130556 0.03465475]
Final transition matrix A:
[[0.99652597 0.0012672  0.00220682]
 [0.01066475 0.98214782 0.00718743]
 [0.00778497 0.00214701 0.99006803]]
Final initial distribution pi:
[8.56433347e-01 1.64105402e-06 1.43565012e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.2_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4803  0.2780  0.3521   21194788.0   22930212.0  55057880.0
Archaic_young     0.7730  0.8832  0.8244  190909717.0   56070283.0  25257066.0
Modern            0.0000  0.0000  0.0000          0.0  708895000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         702785          170           2072
Archaic_old      2605        21188          53095
Archaic_young    3505        22767         191813

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1991  0.0352  0.0599
Archaic_young     0.7931  0.9577  0.8677

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         623496           59           2315
Archaic_old       932         2613          70971
Archaic_young    3073        10458         286083

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1549954.47 | Rates: N=0.89979, AF=0.09587, OLD=0.04711, YOUNG=0.03677
A =
[[9.96445398e-01 9.86170178e-04 2.56843152e-03]
 [5.89565804e-03 9.91758151e-01 2.34619101e-03]
 [6.21377778e-03 9.46000595e-04 9.92840222e-01]]
pi = [0.40229013 0.16847007 0.4292398 ]
Iter 2: LL=-1280909.34 | Rates: N=0.90002, AF=0.09554, OLD=0.05106, YOUNG=0.03524
A =
[[9.96430814e-01 1.00530673e-03 2.56387966e-03]
 [5.97011153e-03 9.91688640e-01 2.34124858e-03]
 [6.19221427e-03 9.44693834e-04 9.92863092e-01]]
pi = [0.39666857 0.15029819 0.45303324]
Iter 3: LL=-1280855.06 | Rates: N=0.90003, AF=0.09551, OLD=0.05530, YOUNG=0.03367
A =
[[9.96430102e-01 1.02166236e-03 2.54823528e-03]
 [6.13205565e-03 9.91484868e-01 2.38307619e-03]
 [6.12739443e-03 9.42784229e-04 9.92929821e-01]]
pi = [0.39649471 0.12491087 0.47859442]
Iter 4: LL=-1280803.48 | Rates: N=0.90003, AF=0.09548, OLD=0.05908, YOUNG=0.03253
A =
[[9.96429586e-01 1.03388104e-03 2.53653338e-03]
 [6.38163291e-03 9.91116569e-01 2.50179809e-03]
 [6.03227021e-03 9.49320570e-04 9.93018409e-01]]
pi = [0.39647759 0.0978709  0.5056515 ]
Iter 5: LL=-1280769.83 | Rates: N=0.90004, AF=0.09545, OLD=0.06212, YOUNG=0.03190
A =
[[9.96428650e-01 1.03887507e-03 2.53247483e-03]
 [6.67808388e-03 9.90621779e-01 2.70013702e-03]
 [5.93152089e-03 9.69573016e-04 9.93098906e-01]]
pi = [0.3964875  0.07354499 0.52996751]
Iter 6: LL=-1280750.39 | Rates: N=0.90004, AF=0.09542, OLD=0.06457, YOUNG=0.03163
A =
[[0.99642759 0.00103586 0.00253654]
 [0.00698242 0.99005302 0.00296456]
 [0.00584195 0.00100144 0.99315661]]
pi = [0.39652398 0.05381616 0.54965985]
Iter 7: LL=-1280737.51 | Rates: N=0.90004, AF=0.09539, OLD=0.06664, YOUNG=0.03155
A =
[[0.9964266  0.0010258  0.0025476 ]
 [0.00727344 0.98944568 0.00328087]
 [0.00576943 0.00104058 0.99318998]]
pi = [0.39657642 0.03864738 0.5647762 ]
Iter 8: LL=-1280727.18 | Rates: N=0.90005, AF=0.09537, OLD=0.06853, YOUNG=0.03158
A =
[[0.99642572 0.00101028 0.002564  ]
 [0.00754305 0.98881731 0.00363964]
 [0.00571379 0.00108355 0.99320266]]
pi = [0.39663236 0.027299   0.57606864]
Iter 9: LL=-1280717.91 | Rates: N=0.90005, AF=0.09535, OLD=0.07034, YOUNG=0.03165
A =
[[9.96424952e-01 9.90836236e-04 2.58421182e-03]
 [7.78997492e-03 9.88174027e-01 4.03599786e-03]
 [5.67261625e-03 1.12816656e-03 9.93199217e-01]]
pi = [0.3966837  0.01895429 0.58436201]
Iter 10: LL=-1280709.17 | Rates: N=0.90005, AF=0.09533, OLD=0.07213, YOUNG=0.03174
A =
[[9.96424278e-01 9.68710425e-04 2.60701196e-03]
 [8.01608482e-03 9.87515723e-01 4.46819186e-03]
 [5.64314711e-03 1.17304371e-03 9.93183809e-01]]
pi = [0.3967267  0.01291203 0.59036126]
Iter 11: LL=-1280700.74 | Rates: N=0.90005, AF=0.09531, OLD=0.07395, YOUNG=0.03184
A =
[[9.96423683e-01 9.44839753e-04 2.63147761e-03]
 [8.22441940e-03 9.86839321e-01 4.93625974e-03]
 [5.62289406e-03 1.21727597e-03 9.93159830e-01]]
pi = [0.39676037 0.00861117 0.59462846]
Iter 12: LL=-1280692.50 | Rates: N=0.90005, AF=0.09530, OLD=0.07582, YOUNG=0.03194
A =
[[9.96423151e-01 9.19920572e-04 2.65692880e-03]
 [8.41823438e-03 9.86140589e-01 5.44117704e-03]
 [5.60983118e-03 1.26022074e-03 9.93129948e-01]]
pi = [0.39678517 0.00561054 0.59760429]
Iter 13: LL=-1280684.39 | Rates: N=0.90005, AF=0.09528, OLD=0.07775, YOUNG=0.03204
A =
[[9.96422666e-01 8.94466825e-04 2.68286674e-03]
 [8.60052769e-03 9.85415157e-01 5.98431544e-03]
 [5.60237387e-03 1.30140124e-03 9.93096225e-01]]
pi = [0.3968022  0.00356479 0.599633  ]
Iter 14: LL=-1280676.40 | Rates: N=0.90005, AF=0.09527, OLD=0.07976, YOUNG=0.03214
A =
[[9.96422217e-01 8.68857853e-04 2.70892546e-03]
 [8.77382697e-03 9.84659080e-01 6.56709346e-03]
 [5.59930700e-03 1.34045259e-03 9.93060240e-01]]
pi = [0.39681277 0.00220548 0.60098175]
Iter 15: LL=-1280668.49 | Rates: N=0.90006, AF=0.09525, OLD=0.08184, YOUNG=0.03224
A =
[[9.96421790e-01 8.43374595e-04 2.73483538e-03]
 [8.94011681e-03 9.83869155e-01 7.19072830e-03]
 [5.59970581e-03 1.37709123e-03 9.93023203e-01]]
pi = [0.39681816 0.0013271  0.60185474]
Final Global Rates (lambdas): [0.90005536 0.09525495 0.08184054 0.03224301]
Final transition matrix A:
[[9.96421790e-01 8.43374595e-04 2.73483538e-03]
 [8.94011681e-03 9.83869155e-01 7.19072830e-03]
 [5.59970581e-03 1.37709123e-03 9.93023203e-01]]
Final initial distribution pi:
[0.39681816 0.0013271  0.60185474]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1687  0.0504  0.0776    3737156.0   18420844.0  70451248.0
Archaic_young     0.7914  0.9328  0.8563  277623349.0   73183651.0  19994925.0
Modern            0.0000  0.0000  0.0000          0.0  627035000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         623414          257           2199
Archaic_old       801         3746          69969
Archaic_young    2820        18155         278639

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1940  0.0136  0.0254
Archaic_young     0.7979  0.9784  0.8790

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         616598           14           2604
Archaic_old      1099         1000          71749
Archaic_young    3482         4143         299311

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1548488.53 | Rates: N=0.89653, AF=0.09649, OLD=0.04789, YOUNG=0.03806
A =
[[9.96074223e-01 9.88038749e-04 2.93773778e-03]
 [6.71449200e-03 9.90256004e-01 3.02950376e-03]
 [6.50729291e-03 9.92586743e-04 9.92500120e-01]]
pi = [0.70332036 0.07755528 0.21912436]
Iter 2: LL=-1282783.73 | Rates: N=0.89678, AF=0.09626, OLD=0.05235, YOUNG=0.03636
A =
[[9.96069573e-01 1.00323140e-03 2.92719557e-03]
 [6.79942649e-03 9.90210116e-01 2.99045776e-03]
 [6.46596326e-03 9.88714596e-04 9.92545322e-01]]
pi = [0.70509314 0.06670051 0.22820634]
Iter 3: LL=-1282719.21 | Rates: N=0.89678, AF=0.09624, OLD=0.05763, YOUNG=0.03466
A =
[[9.96069930e-01 1.02255062e-03 2.90751917e-03]
 [6.94438183e-03 9.90094381e-01 2.96123676e-03]
 [6.41670583e-03 9.87624531e-04 9.92595670e-01]]
pi = [0.70513887 0.05254567 0.24231547]
Iter 4: LL=-1282653.34 | Rates: N=0.89678, AF=0.09622, OLD=0.06225, YOUNG=0.03338
A =
[[9.96070109e-01 1.03407526e-03 2.89581600e-03]
 [7.18250260e-03 9.89791469e-01 3.02602860e-03]
 [6.34268347e-03 9.90687249e-04 9.92666629e-01]]
pi = [0.70506924 0.03729283 0.25763793]
Iter 5: LL=-1282612.83 | Rates: N=0.89678, AF=0.09620, OLD=0.06579, YOUNG=0.03269
A =
[[0.99606983 0.00103314 0.00289703]
 [0.00747618 0.98931883 0.00320499]
 [0.0062632  0.00100441 0.99273239]]
pi = [0.70496116 0.0243524  0.27068645]
Iter 6: LL=-1282592.37 | Rates: N=0.89678, AF=0.09618, OLD=0.06853, YOUNG=0.03242
A =
[[0.99606943 0.00102084 0.00290972]
 [0.0077774  0.98874668 0.00347592]
 [0.00619468 0.00102844 0.99277688]]
pi = [0.70485802 0.01503676 0.28010522]
Iter 7: LL=-1282580.03 | Rates: N=0.89678, AF=0.09617, OLD=0.07083, YOUNG=0.03237
A =
[[0.99606908 0.00100009 0.00293082]
 [0.00805986 0.98812726 0.00381288]
 [0.00614256 0.00105912 0.99279833]]
pi = [0.70478233 0.00895322 0.28626444]
Iter 8: LL=-1282570.29 | Rates: N=0.89678, AF=0.09615, OLD=0.07291, YOUNG=0.03241
A =
[[9.96068834e-01 9.73690251e-04 2.95747549e-03]
 [8.31509889e-03 9.87486009e-01 4.19889225e-03]
 [6.10582221e-03 1.09332280e-03 9.92800855e-01]]
pi = [0.70473674 0.00519813 0.29006513]
Iter 9: LL=-1282561.45 | Rates: N=0.89678, AF=0.09614, OLD=0.07493, YOUNG=0.03249
A =
[[9.96068684e-01 9.43766566e-04 2.98754906e-03]
 [8.54381792e-03 9.86831181e-01 4.62500153e-03]
 [6.08142424e-03 1.12904021e-03 9.92789536e-01]]
pi = [0.70471536 0.00295899 0.29232565]
Iter 10: LL=-1282552.99 | Rates: N=0.89678, AF=0.09613, OLD=0.07696, YOUNG=0.03259
A =
[[9.96068622e-01 9.11849249e-04 3.01952891e-03]
 [8.75035703e-03 9.86162609e-01 5.08703383e-03]
 [6.06623890e-03 1.16501385e-03 9.92768747e-01]]
pi = [0.70471109 0.00165549 0.29363342]
Iter 11: LL=-1282544.75 | Rates: N=0.89678, AF=0.09612, OLD=0.07902, YOUNG=0.03269
A =
[[9.96068628e-01 8.79011044e-04 3.05236092e-03]
 [8.93984316e-03 9.85476953e-01 5.58320398e-03]
 [6.05770002e-03 1.20042560e-03 9.92741874e-01]]
pi = [0.70471813 0.00091124 0.29437063]
Iter 12: LL=-1282536.69 | Rates: N=0.89678, AF=0.09612, OLD=0.08115, YOUNG=0.03280
A =
[[9.96068683e-01 8.46011368e-04 3.08530575e-03]
 [9.11695178e-03 9.84770347e-01 6.11270121e-03]
 [6.05387358e-03 1.23471734e-03 9.92711409e-01]]
pi = [7.04732344e-01 4.93658723e-04 2.94773997e-01]
Iter 13: LL=-1282528.79 | Rates: N=0.89678, AF=0.09611, OLD=0.08334, YOUNG=0.03290
A =
[[9.96068766e-01 8.13394592e-04 3.11783910e-03]
 [9.28551963e-03 9.84039521e-01 6.67495986e-03]
 [6.05335420e-03 1.26750205e-03 9.92679144e-01]]
pi = [7.04750914e-01 2.63266929e-04 2.94985819e-01]
Iter 14: LL=-1282521.08 | Rates: N=0.89678, AF=0.09610, OLD=0.08562, YOUNG=0.03300
A =
[[9.96068859e-01 7.81555335e-04 3.14958601e-03]
 [9.44857323e-03 9.83282089e-01 7.26933814e-03]
 [6.05512971e-03 1.29851814e-03 9.92646352e-01]]
pi = [7.04771958e-01 1.38234920e-04 2.95089807e-01]
Iter 15: LL=-1282513.57 | Rates: N=0.89678, AF=0.09609, OLD=0.08797, YOUNG=0.03310
A =
[[9.96068941e-01 7.50781236e-04 3.18027790e-03]
 [9.60852241e-03 9.82496450e-01 7.89502729e-03]
 [6.05846388e-03 1.32760210e-03 9.92613934e-01]]
pi = [7.04794215e-01 7.14814730e-05 2.95134303e-01]
Final Global Rates (lambdas): [0.89678353 0.09608758 0.08797003 0.03309914]
Final transition matrix A:
[[9.96068941e-01 7.50781236e-04 3.18027790e-03]
 [9.60852241e-03 9.82496450e-01 7.89502729e-03]
 [6.05846388e-03 1.32760210e-03 9.92613934e-01]]
Final initial distribution pi:
[7.04794215e-01 7.14814730e-05 2.95134303e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2952  0.0702  0.1135    5162885.0   12324115.0  68356184.0
Archaic_young     0.8031  0.9517  0.8711  290010952.0   71118048.0  14720201.0
Modern            0.0000  0.0000  0.0000          0.0  621384000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         616700           47           2469
Archaic_old      1159         5158          67531
Archaic_young    3525        12282         291129

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2521  0.0114  0.0218
Archaic_young     0.8197  0.9850  0.8947

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         604675            5           2843
Archaic_old      1102          766          65699
Archaic_young    3732         2268         318910

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1545710.43 | Rates: N=0.89167, AF=0.09598, OLD=0.05107, YOUNG=0.04074
A =
[[0.99561847 0.00104639 0.00333515]
 [0.00727797 0.98909043 0.0036316 ]
 [0.00691188 0.00107974 0.99200838]]
pi = [0.63645793 0.10073992 0.26280214]
Iter 2: LL=-1284722.48 | Rates: N=0.89193, AF=0.09581, OLD=0.05704, YOUNG=0.03842
A =
[[0.99562698 0.00106268 0.00331034]
 [0.00724033 0.98920733 0.00355234]
 [0.00688257 0.00107661 0.99204082]]
pi = [0.6398574  0.10297943 0.25716317]
Iter 3: LL=-1284610.19 | Rates: N=0.89193, AF=0.09579, OLD=0.06431, YOUNG=0.03603
A =
[[0.99563026 0.00108999 0.00327975]
 [0.00721707 0.98932401 0.00345892]
 [0.00687897 0.00107982 0.99204121]]
pi = [0.63990047 0.110262   0.24983752]
Iter 4: LL=-1284495.17 | Rates: N=0.89193, AF=0.09576, OLD=0.07020, YOUNG=0.03431
A =
[[0.99563292 0.00110463 0.00326245]
 [0.00732137 0.98914973 0.0035289 ]
 [0.00683983 0.00108725 0.99207292]]
pi = [0.63929247 0.12193607 0.23877146]
Iter 5: LL=-1284435.69 | Rates: N=0.89193, AF=0.09573, OLD=0.07429, YOUNG=0.03347
A =
[[0.99563396 0.00110372 0.00326232]
 [0.00750464 0.98871669 0.00377867]
 [0.00678602 0.00110867 0.99210531]]
pi = [0.63825113 0.136455   0.22529387]
Iter 6: LL=-1284411.44 | Rates: N=0.89193, AF=0.09571, OLD=0.07721, YOUNG=0.03318
A =
[[0.99563418 0.00109165 0.00327417]
 [0.00769086 0.98816178 0.00414736]
 [0.00674044 0.00114204 0.99211751]]
pi = [0.63691728 0.15146681 0.21161591]
Iter 7: LL=-1284398.38 | Rates: N=0.89193, AF=0.09570, OLD=0.07952, YOUNG=0.03312
A =
[[0.99563421 0.0010726  0.0032932 ]
 [0.00784614 0.98756936 0.0045845 ]
 [0.00670961 0.00118167 0.99210872]]
pi = [0.63552693 0.16513139 0.19934168]
Iter 8: LL=-1284388.55 | Rates: N=0.89193, AF=0.09569, OLD=0.08153, YOUNG=0.03316
A =
[[0.99563424 0.00104956 0.0033162 ]
 [0.00796415 0.98697438 0.00506147]
 [0.00669201 0.00122373 0.99208426]]
pi = [0.6342477  0.17646181 0.18929049]
Iter 9: LL=-1284380.02 | Rates: N=0.89192, AF=0.09568, OLD=0.08339, YOUNG=0.03324
A =
[[0.99563433 0.00102448 0.00334118]
 [0.00804922 0.9863874  0.00556339]
 [0.00668421 0.00126622 0.99204957]]
pi = [0.6331536  0.18511511 0.18173129]
Iter 10: LL=-1284372.33 | Rates: N=0.89192, AF=0.09567, OLD=0.08517, YOUNG=0.03332
A =
[[0.99563448 0.00099861 0.00336691]
 [0.00810839 0.98580933 0.00608228]
 [0.00668303 0.0013081  0.99200887]]
pi = [0.63225963 0.19112547 0.1766149 ]
Iter 11: LL=-1284365.29 | Rates: N=0.89192, AF=0.09566, OLD=0.08691, YOUNG=0.03341
A =
[[9.95634660e-01 9.72704970e-04 3.39263541e-03]
 [8.14837442e-03 9.85238166e-01 6.61345994e-03]
 [6.68605503e-03 1.34881071e-03 9.91965134e-01]]
pi = [0.6315529  0.19471197 0.17373513]
Iter 12: LL=-1284358.83 | Rates: N=0.89192, AF=0.09565, OLD=0.08861, YOUNG=0.03350
A =
[[9.95634872e-01 9.47239166e-04 3.41788861e-03]
 [8.17466589e-03 9.84671564e-01 7.15376989e-03]
 [6.69158020e-03 1.38802865e-03 9.91920391e-01]]
pi = [0.63101049 0.19616492 0.17282459]
Iter 13: LL=-1284352.89 | Rates: N=0.89192, AF=0.09565, OLD=0.09029, YOUNG=0.03358
A =
[[9.95635103e-01 9.22502567e-04 3.44239436e-03]
 [8.19147993e-03 9.84107724e-01 7.70079581e-03]
 [6.69846285e-03 1.42557066e-03 9.91875966e-01]]
pi = [0.6306082  0.19578791 0.1736039 ]
Iter 14: LL=-1284347.42 | Rates: N=0.89192, AF=0.09564, OLD=0.09195, YOUNG=0.03366
A =
[[9.95635343e-01 8.98665243e-04 3.46599184e-03]
 [8.20193164e-03 9.83545555e-01 8.25251343e-03]
 [6.70595289e-03 1.46133705e-03 9.91832710e-01]]
pi = [0.63032411 0.19387293 0.17580296]
Iter 15: LL=-1284342.38 | Rates: N=0.89192, AF=0.09563, OLD=0.09360, YOUNG=0.03374
A =
[[9.95635584e-01 8.75821134e-04 3.48859466e-03]
 [8.20827685e-03 9.82984599e-01 8.80712397e-03]
 [6.71357191e-03 1.49528366e-03 9.91791144e-01]]
pi = [0.63013949 0.1906921  0.17916841]
Final Global Rates (lambdas): [0.89192139 0.09563421 0.09359594 0.03374144]
Final transition matrix A:
[[9.95635584e-01 8.75821134e-04 3.48859466e-03]
 [8.20827685e-03 9.82984599e-01 8.80712397e-03]
 [6.71357191e-03 1.49528366e-03 9.91791144e-01]]
Final initial distribution pi:
[0.63013949 0.1906921  0.17916841]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1954  0.0712  0.1044    4786924.0   19705076.0  62466558.0
Archaic_young     0.8208  0.9308  0.8723  300089172.0   65500828.0  22326633.0
Modern            0.0000  0.0000  0.0000          0.0  609918000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         604832           58           2633
Archaic_old      1180         4786          61601
Archaic_young    3906        19648         301356

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1552  0.0035  0.0069
Archaic_young     0.8092  0.9849  0.8884

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         631402            1           3151
Archaic_old      1192          232          64433
Archaic_young    4462         1265         293862

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1576663.50 | Rates: N=0.90709, AF=0.09731, OLD=0.05855, YOUNG=0.04806
A =
[[0.99558521 0.00104175 0.00337304]
 [0.0081157  0.98781921 0.00406508]
 [0.0078707  0.00122065 0.99090866]]
pi = [0.69747529 0.07351992 0.22900479]
Iter 2: LL=-1300922.80 | Rates: N=0.90736, AF=0.09716, OLD=0.06438, YOUNG=0.04571
A =
[[0.99561695 0.00104758 0.00333547]
 [0.00806474 0.98794817 0.00398709]
 [0.00778979 0.00121804 0.99099217]]
pi = [0.70087557 0.05767809 0.24144634]
Iter 3: LL=-1300831.52 | Rates: N=0.90736, AF=0.09714, OLD=0.07215, YOUNG=0.04323
A =
[[0.99562056 0.00107302 0.00330643]
 [0.0081106  0.98800765 0.00388174]
 [0.00776376 0.0012225  0.99101374]]
pi = [0.70088787 0.0387711  0.26034104]
Iter 4: LL=-1300721.87 | Rates: N=0.90736, AF=0.09709, OLD=0.07924, YOUNG=0.04123
A =
[[0.9956224  0.00109286 0.00328474]
 [0.00833698 0.9877366  0.00392642]
 [0.00768762 0.00123129 0.99108109]]
pi = [0.70063043 0.02139172 0.27797785]
Iter 5: LL=-1300649.85 | Rates: N=0.90735, AF=0.09704, OLD=0.08484, YOUNG=0.04014
A =
[[0.99562342 0.00109782 0.00327877]
 [0.00870077 0.9871186  0.00418064]
 [0.00758244 0.00125644 0.99116112]]
pi = [0.70038663 0.01004199 0.28957138]
Iter 6: LL=-1300612.74 | Rates: N=0.90735, AF=0.09699, OLD=0.08933, YOUNG=0.03970
A =
[[0.99562385 0.0010878  0.00328835]
 [0.00911185 0.98627684 0.00461131]
 [0.00748294 0.0012983  0.99121876]]
pi = [0.70026148 0.00424063 0.29549789]
Iter 7: LL=-1300589.45 | Rates: N=0.90735, AF=0.09695, OLD=0.09327, YOUNG=0.03960
A =
[[0.99562392 0.00106601 0.00331007]
 [0.00951608 0.98530862 0.0051753 ]
 [0.00740446 0.00135059 0.99124495]]
pi = [0.70023212 0.00167581 0.29809207]
Iter 8: LL=-1300570.22 | Rates: N=0.90735, AF=0.09691, OLD=0.09700, YOUNG=0.03966
A =
[[0.99562386 0.0010361  0.00334003]
 [0.00988843 0.98426843 0.00584314]
 [0.00734896 0.001408   0.99124304]]
pi = [7.00248828e-01 6.32882053e-04 2.99118290e-01]
Iter 9: LL=-1300552.26 | Rates: N=0.90735, AF=0.09688, OLD=0.10072, YOUNG=0.03977
A =
[[0.99562382 0.00100105 0.00337513]
 [0.01022053 0.98318084 0.00659863]
 [0.00731327 0.00146715 0.99121958]]
pi = [7.00281176e-01 2.30651469e-04 2.99488173e-01]
Iter 10: LL=-1300534.90 | Rates: N=0.90734, AF=0.09686, OLD=0.10452, YOUNG=0.03991
A =
[[9.95623823e-01 9.63088214e-04 3.41308876e-03]
 [1.05129509e-02 9.82052779e-01 7.43427015e-03]
 [7.29306817e-03 1.52590486e-03 9.91181027e-01]]
pi = [7.00316273e-01 8.14853399e-05 2.99602242e-01]
Iter 11: LL=-1300517.98 | Rates: N=0.90734, AF=0.09683, OLD=0.10845, YOUNG=0.04006
A =
[[9.95623872e-01 9.23880340e-04 3.45224808e-03]
 [1.07707725e-02 9.80881519e-01 8.34770797e-03]
 [7.28431104e-03 1.58280781e-03 9.91132881e-01]]
pi = [7.00349840e-01 2.79758531e-05 2.99622184e-01]
Iter 12: LL=-1300501.42 | Rates: N=0.90734, AF=0.09680, OLD=0.11256, YOUNG=0.04021
A =
[[9.95623922e-01 8.84646189e-04 3.49143186e-03]
 [1.10011866e-02 9.79659157e-01 9.33965658e-03]
 [7.28366549e-03 1.63678202e-03 9.91079552e-01]]
pi = [7.00380888e-01 9.35187243e-06 2.99609760e-01]
Iter 13: LL=-1300485.09 | Rates: N=0.90734, AF=0.09676, OLD=0.11698, YOUNG=0.04036
A =
[[9.95623868e-01 8.46310025e-04 3.52982186e-03]
 [1.12127001e-02 9.78373601e-01 1.04136987e-02]
 [7.28851860e-03 1.68693241e-03 9.91024549e-01]]
pi = [7.00409389e-01 3.04881616e-06 2.99587562e-01]
Iter 14: LL=-1300468.46 | Rates: N=0.90734, AF=0.09671, OLD=0.12198, YOUNG=0.04052
A =
[[9.95623540e-01 8.09440580e-04 3.56701909e-03]
 [1.14168681e-02 9.77001831e-01 1.15813012e-02]
 [7.29680728e-03 1.73213683e-03 9.90971056e-01]]
pi = [7.00435216e-01 9.69895906e-07 2.99563814e-01]
Iter 15: LL=-1300450.55 | Rates: N=0.90733, AF=0.09665, OLD=0.12763, YOUNG=0.04069
A =
[[9.95623098e-01 7.73404878e-04 3.60349742e-03]
 [1.16322464e-02 9.75494155e-01 1.28735984e-02]
 [7.30678042e-03 1.77040750e-03 9.90922812e-01]]
pi = [7.00457917e-01 3.00456626e-07 2.99541783e-01]
Final Global Rates (lambdas): [0.9073322  0.09664564 0.12763462 0.04068922]
Final transition matrix A:
[[9.95623098e-01 7.73404878e-04 3.60349742e-03]
 [1.16322464e-02 9.75494155e-01 1.28735984e-02]
 [7.30678042e-03 1.77040750e-03 9.90922812e-01]]
Final initial distribution pi:
[7.00457917e-01 3.00456626e-07 2.99541783e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2604  0.0647  0.1036    4237687.0   12036313.0  61286276.0
Archaic_young     0.8135  0.9499  0.8764  282046665.0   64644335.0  14887817.0
Modern            0.0000  0.0000  0.0000          0.0  637035000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         631385          302           2867
Archaic_old      1170         4240          60447
Archaic_young    4480        11732         283377

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0000  0.0000  0.0000
Archaic_young     0.7848  0.9879  0.8747

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         616579            0           3187
Archaic_old      1448            0          76381
Archaic_young    4569          338         297498

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1569536.61 | Rates: N=0.89456, AF=0.09683, OLD=0.06431, YOUNG=0.05372
A =
[[0.995154   0.00112438 0.00372162]
 [0.00839789 0.98699594 0.00460617]
 [0.00813398 0.0013347  0.99053132]]
pi = [0.36597496 0.17507867 0.45894636]
Iter 2: LL=-1304683.02 | Rates: N=0.89484, AF=0.09671, OLD=0.07064, YOUNG=0.05121
A =
[[0.99521151 0.00113214 0.00365635]
 [0.00833881 0.98708465 0.00457654]
 [0.00800688 0.00132522 0.9906679 ]]
pi = [0.34518264 0.18636193 0.46845543]
Iter 3: LL=-1304577.64 | Rates: N=0.89483, AF=0.09667, OLD=0.08010, YOUNG=0.04830
A =
[[0.9952191  0.0011751  0.0036058 ]
 [0.00838072 0.98711588 0.0045034 ]
 [0.00797294 0.00132396 0.9907031 ]]
pi = [0.34378257 0.19668232 0.45953511]
Iter 4: LL=-1304423.92 | Rates: N=0.89483, AF=0.09659, OLD=0.08929, YOUNG=0.04574
A =
[[0.99522352 0.0012189  0.00355758]
 [0.00862348 0.98677151 0.00460501]
 [0.00788601 0.00132213 0.99079186]]
pi = [0.34369297 0.20627592 0.45003111]
Iter 5: LL=-1304312.13 | Rates: N=0.89483, AF=0.09652, OLD=0.09651, YOUNG=0.04431
A =
[[0.99522487 0.00124522 0.00352991]
 [0.00904539 0.98597373 0.00498089]
 [0.00776578 0.00133752 0.9908967 ]]
pi = [0.34364573 0.21291317 0.4434411 ]
Iter 6: LL=-1304256.42 | Rates: N=0.89482, AF=0.09646, OLD=0.10207, YOUNG=0.04376
A =
[[0.9952244  0.001251   0.0035246 ]
 [0.0095209  0.98490189 0.00557721]
 [0.00765609 0.00137645 0.99096746]]
pi = [0.3435095  0.21648364 0.44000687]
Iter 7: LL=-1304224.77 | Rates: N=0.89482, AF=0.09642, OLD=0.10671, YOUNG=0.04364
A =
[[0.99522341 0.00124003 0.00353655]
 [0.00997    0.98371039 0.00631962]
 [0.00757435 0.00143255 0.9909931 ]]
pi = [0.3433093  0.21753975 0.43915095]
Iter 8: LL=-1304200.93 | Rates: N=0.89482, AF=0.09638, OLD=0.11091, YOUNG=0.04371
A =
[[0.99522246 0.00121732 0.00356022]
 [0.01036431 0.9824749  0.00716079]
 [0.00751982 0.00149922 0.99098096]]
pi = [0.34309421 0.21676771 0.44013808]
Iter 9: LL=-1304180.17 | Rates: N=0.89482, AF=0.09635, OLD=0.11494, YOUNG=0.04383
A =
[[0.9952217  0.00118707 0.00359123]
 [0.01070249 0.98122038 0.00807713]
 [0.00748625 0.00157212 0.99094162]]
pi = [0.34289454 0.21474887 0.4423566 ]
Iter 10: LL=-1304161.08 | Rates: N=0.89482, AF=0.09632, OLD=0.11894, YOUNG=0.04397
A =
[[0.99522113 0.00115236 0.00362651]
 [0.0109941  0.97994714 0.00905876]
 [0.00746728 0.00164841 0.99088431]]
pi = [0.34272127 0.21191158 0.44536715]
Iter 11: LL=-1304143.13 | Rates: N=0.89481, AF=0.09629, OLD=0.12299, YOUNG=0.04411
A =
[[0.99522069 0.00111533 0.00366397]
 [0.01125149 0.97864591 0.0101026 ]
 [0.00745794 0.001726   0.99081606]]
pi = [0.3425745  0.20856195 0.44886355]
Iter 12: LL=-1304126.01 | Rates: N=0.89481, AF=0.09626, OLD=0.12713, YOUNG=0.04424
A =
[[0.9952203  0.00107746 0.00370225]
 [0.01148651 0.97730477 0.01120872]
 [0.00745472 0.00180321 0.99074208]]
pi = [0.34244974 0.20492149 0.45262877]
Iter 13: LL=-1304109.53 | Rates: N=0.89481, AF=0.09623, OLD=0.13142, YOUNG=0.04438
A =
[[0.99521988 0.00103967 0.00374045]
 [0.01170948 0.97591175 0.01237876]
 [0.00745523 0.00187867 0.99066611]]
pi = [0.34234121 0.20115297 0.45650583]
Iter 14: LL=-1304093.55 | Rates: N=0.89481, AF=0.09619, OLD=0.13590, YOUNG=0.04452
A =
[[0.99521938 0.00100255 0.00377806]
 [0.01192911 0.97445539 0.0136155 ]
 [0.00745787 0.00195123 0.9905909 ]]
pi = [0.34224326 0.19737628 0.46038045]
Iter 15: LL=-1304077.96 | Rates: N=0.89480, AF=0.09616, OLD=0.14059, YOUNG=0.04466
A =
[[9.95218809e-01 9.66432390e-04 3.81475849e-03]
 [1.21525856e-02 9.72925048e-01 1.49223666e-02]
 [7.46158249e-03 2.01999683e-03 9.90518421e-01]]
pi = [0.34215097 0.19368006 0.46416896]
Final Global Rates (lambdas): [0.89480281 0.09615758 0.14058825 0.04466348]
Final transition matrix A:
[[9.95218809e-01 9.66432390e-04 3.81475849e-03]
 [1.21525856e-02 9.72925048e-01 1.49223666e-02]
 [7.46158249e-03 2.01999683e-03 9.90518421e-01]]
Final initial distribution pi:
[0.34215097 0.19368006 0.46416896]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2345  0.0566  0.0912    4386937.0   14319063.0  73085490.0
Archaic_young     0.7873  0.9420  0.8577  282181236.0   76231764.0  17371235.0
Modern            0.0000  0.0000  0.0000          0.0  622881000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         616657          242           2867
Archaic_old      1550         4389          71890
Archaic_young    4674        14075         283656

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1822  0.1722  0.1771
Archaic_young     0.7983  0.8108  0.8045

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         626847          363           2100
Archaic_old       939        12180          57957
Archaic_young    3093        54292         242229

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1554314.88 | Rates: N=0.90099, AF=0.09716, OLD=0.05135, YOUNG=0.03387
A =
[[0.99644964 0.00125083 0.00229952]
 [0.00609951 0.99190832 0.00199217]
 [0.00627143 0.00111707 0.9926115 ]]
pi = [0.45414924 0.18025166 0.3655991 ]
Iter 2: LL=-1283848.98 | Rates: N=0.90120, AF=0.09692, OLD=0.05488, YOUNG=0.03223
A =
[[0.9964467  0.00124841 0.00230489]
 [0.00628351 0.9916542  0.00206229]
 [0.0061516  0.0011018  0.9927466 ]]
pi = [0.45170812 0.17391091 0.37438096]
Iter 3: LL=-1283803.74 | Rates: N=0.90120, AF=0.09690, OLD=0.05788, YOUNG=0.03124
A =
[[0.99644663 0.00123933 0.00231404]
 [0.00650499 0.99130493 0.00219008]
 [0.00604306 0.00110462 0.99285233]]
pi = [0.45166686 0.16883989 0.37949324]
Iter 4: LL=-1283778.52 | Rates: N=0.90121, AF=0.09688, OLD=0.06022, YOUNG=0.03078
A =
[[0.99644642 0.00122222 0.00233135]
 [0.00672842 0.99089293 0.00237865]
 [0.00594883 0.0011249  0.99292627]]
pi = [0.45164544 0.16555462 0.38279995]
Iter 5: LL=-1283764.16 | Rates: N=0.90121, AF=0.09687, OLD=0.06213, YOUNG=0.03063
A =
[[0.99644612 0.00119828 0.00235561]
 [0.00693662 0.99044598 0.00261741]
 [0.00587533 0.00115772 0.99296695]]
pi = [0.45163093 0.16364747 0.3847216 ]
Iter 6: LL=-1283753.72 | Rates: N=0.90121, AF=0.09686, OLD=0.06380, YOUNG=0.03063
A =
[[0.99644583 0.00116917 0.00238501]
 [0.00712467 0.98997852 0.00289681]
 [0.00582119 0.00119776 0.99298105]]
pi = [0.45162275 0.16259064 0.38578661]
Iter 7: LL=-1283744.48 | Rates: N=0.90121, AF=0.09685, OLD=0.06538, YOUNG=0.03070
A =
[[0.99644558 0.0011365  0.00241792]
 [0.00729315 0.98949595 0.0032109 ]
 [0.00578286 0.00124145 0.99297569]]
pi = [0.45161898 0.16190724 0.38647378]
Iter 8: LL=-1283735.59 | Rates: N=0.90121, AF=0.09684, OLD=0.06693, YOUNG=0.03080
A =
[[0.99644539 0.00110155 0.00245305]
 [0.00744458 0.98899877 0.00355665]
 [0.00575677 0.00128667 0.99295655]]
pi = [0.45161778 0.16122707 0.38715515]
Iter 9: LL=-1283726.83 | Rates: N=0.90121, AF=0.09683, OLD=0.06852, YOUNG=0.03091
A =
[[0.99644525 0.00106529 0.00248946]
 [0.00758198 0.98848518 0.00393284]
 [0.00573994 0.00133213 0.99292793]]
pi = [0.45161774 0.16029541 0.38808685]
Iter 10: LL=-1283718.12 | Rates: N=0.90121, AF=0.09682, OLD=0.07014, YOUNG=0.03103
A =
[[0.99644515 0.00102842 0.00252643]
 [0.0077083  0.98795251 0.00433918]
 [0.00573001 0.00137699 0.992893  ]]
pi = [0.45161788 0.1589619  0.38942022]
Iter 11: LL=-1283709.46 | Rates: N=0.90121, AF=0.09681, OLD=0.07183, YOUNG=0.03114
A =
[[9.96445072e-01 9.91467519e-04 2.56346067e-03]
 [7.82626097e-03 9.87397921e-01 4.77581795e-03]
 [5.72513527e-03 1.42069832e-03 9.92854166e-01]]
pi = [0.45161751 0.15716152 0.39122097]
Iter 12: LL=-1283700.87 | Rates: N=0.90121, AF=0.09680, OLD=0.07358, YOUNG=0.03125
A =
[[9.96445015e-01 9.54837003e-04 2.60014795e-03]
 [7.93826219e-03 9.86818762e-01 5.24297549e-03]
 [5.72393000e-03 1.46282203e-03 9.92813248e-01]]
pi = [0.45161618 0.15489355 0.39349027]
Iter 13: LL=-1283692.36 | Rates: N=0.90121, AF=0.09679, OLD=0.07540, YOUNG=0.03137
A =
[[9.96444968e-01 9.18830187e-04 2.63620178e-03]
 [8.04644670e-03 9.86212752e-01 5.74080081e-03]
 [5.72531790e-03 1.50304372e-03 9.92771638e-01]]
pi = [0.45161362 0.15220155 0.39618482]
Iter 14: LL=-1283683.96 | Rates: N=0.90121, AF=0.09678, OLD=0.07730, YOUNG=0.03148
A =
[[9.96444923e-01 8.83675697e-04 2.67140171e-03]
 [8.15268338e-03 9.85578113e-01 6.26920410e-03]
 [5.72848140e-03 1.54110652e-03 9.92730412e-01]]
pi = [0.45160968 0.14915594 0.39923438]
Iter 15: LL=-1283675.71 | Rates: N=0.90121, AF=0.09677, OLD=0.07926, YOUNG=0.03159
A =
[[9.96444872e-01 8.49543735e-04 2.70558465e-03]
 [8.25855855e-03 9.84913714e-01 6.82772734e-03]
 [5.73280559e-03 1.57680149e-03 9.92690393e-01]]
pi = [0.4516043  0.14583959 0.40255611]
Final Global Rates (lambdas): [0.9012107  0.09677382 0.07926467 0.03159266]
Final transition matrix A:
[[9.96444872e-01 8.49543735e-04 2.70558465e-03]
 [8.25855855e-03 9.84913714e-01 6.82772734e-03]
 [5.73280559e-03 1.57680149e-03 9.92690393e-01]]
Final initial distribution pi:
[0.4516043  0.14583959 0.40255611]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2310  0.0869  0.1263    6147185.0   20458815.0  64575436.0
Archaic_young     0.8036  0.9258  0.8604  275547630.0   67334370.0  22070644.0
Modern            0.0000  0.0000  0.0000          0.0  630512000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         626797          295           2218
Archaic_old       792         6162          64122
Archaic_young    2923        20149         276542

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall     F1
Archaic_old       0.2831  0.1194  0.168
Archaic_young     0.7923  0.9144  0.849

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         610235          202           2309
Archaic_old      1152         9535          69631
Archaic_young    3196        23955         279785

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 19
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1543433.07 | Rates: N=0.89369, AF=0.09516, OLD=0.05437, YOUNG=0.03561
A =
[[0.99593046 0.00125344 0.0028161 ]
 [0.00695289 0.99040936 0.00263775]
 [0.00648695 0.00112348 0.99238957]]
pi = [0.59507678 0.1268252  0.27809803]
Iter 2: LL=-1280746.12 | Rates: N=0.89395, AF=0.09492, OLD=0.05986, YOUNG=0.03324
A =
[[0.99593239 0.00124979 0.00281781]
 [0.00711918 0.99025573 0.00262508]
 [0.00639364 0.00111748 0.99248888]]
pi = [0.5954597 0.1304127 0.2741276]
Iter 3: LL=-1280655.87 | Rates: N=0.89396, AF=0.09488, OLD=0.06441, YOUNG=0.03188
A =
[[0.99593286 0.00123655 0.00283059]
 [0.00736589 0.98993293 0.00270118]
 [0.00630373 0.00113727 0.992559  ]]
pi = [0.59528979 0.13682532 0.26788489]
Iter 4: LL=-1280611.81 | Rates: N=0.89396, AF=0.09485, OLD=0.06775, YOUNG=0.03128
A =
[[0.99593259 0.00120911 0.00285829]
 [0.0076519  0.98946171 0.00288639]
 [0.00621638 0.00117834 0.99260528]]
pi = [0.5950415  0.1433301  0.26162841]
Iter 5: LL=-1280590.69 | Rates: N=0.89396, AF=0.09482, OLD=0.07036, YOUNG=0.03112
A =
[[0.9959321  0.00117226 0.00289565]
 [0.00793632 0.98891001 0.00315367]
 [0.00614572 0.00123157 0.99262271]]
pi = [0.59478489 0.14816199 0.25705312]
Iter 6: LL=-1280576.46 | Rates: N=0.89396, AF=0.09480, OLD=0.07262, YOUNG=0.03115
A =
[[0.99593164 0.00113018 0.00293818]
 [0.00820204 0.98831726 0.0034807 ]
 [0.00609369 0.00128868 0.99261763]]
pi = [0.5945417  0.15060376 0.25485454]
Iter 7: LL=-1280564.13 | Rates: N=0.89396, AF=0.09479, OLD=0.07475, YOUNG=0.03125
A =
[[0.99593127 0.00108579 0.00298294]
 [0.00844469 0.98770037 0.00385494]
 [0.0060578  0.00134507 0.99259713]]
pi = [0.59432124 0.15066082 0.25501793]
Iter 8: LL=-1280552.55 | Rates: N=0.89396, AF=0.09477, OLD=0.07685, YOUNG=0.03138
A =
[[0.995931   0.00104093 0.00302807]
 [0.00866517 0.98706459 0.00427024]
 [0.0060347  0.00139855 0.99256674]]
pi = [0.59412726 0.14865792 0.25721483]
Iter 9: LL=-1280541.44 | Rates: N=0.89396, AF=0.09476, OLD=0.07898, YOUNG=0.03153
A =
[[0.99593078 0.00099674 0.00307248]
 [0.00886619 0.98641023 0.00472358]
 [0.00602138 0.00144817 0.99253045]]
pi = [0.59396077 0.14501723 0.26102199]
Iter 10: LL=-1280530.73 | Rates: N=0.89396, AF=0.09475, OLD=0.08116, YOUNG=0.03167
A =
[[9.95930609e-01 9.53904077e-04 3.11548730e-03]
 [9.05067925e-03 9.85736201e-01 5.21311966e-03]
 [6.01542344e-03 1.49350744e-03 9.92491069e-01]]
pi = [0.59382131 0.14016034 0.26601835]
Iter 11: LL=-1280520.42 | Rates: N=0.89396, AF=0.09474, OLD=0.08339, YOUNG=0.03181
A =
[[9.95930460e-01 9.12831115e-04 3.15670878e-03]
 [9.22121057e-03 9.85041596e-01 5.73719369e-03]
 [6.01497155e-03 1.53443157e-03 9.92450597e-01]]
pi = [0.59370741 0.13446699 0.2718256 ]
Iter 12: LL=-1280510.53 | Rates: N=0.89396, AF=0.09472, OLD=0.08568, YOUNG=0.03195
A =
[[9.95930324e-01 8.73750809e-04 3.19592507e-03]
 [9.37985876e-03 9.84326261e-01 6.29388066e-03]
 [6.01861546e-03 1.57096766e-03 9.92410417e-01]]
pi = [0.59361707 0.12825832 0.27812461]
Iter 13: LL=-1280501.07 | Rates: N=0.89396, AF=0.09471, OLD=0.08803, YOUNG=0.03209
A =
[[9.95930192e-01 8.36773123e-04 3.23303462e-03]
 [9.52829987e-03 9.83590816e-01 6.88088427e-03]
 [6.02526675e-03 1.60324116e-03 9.92371492e-01]]
pi = [0.59354799 0.12179201 0.28466   ]
Iter 14: LL=-1280492.06 | Rates: N=0.89396, AF=0.09470, OLD=0.09044, YOUNG=0.03223
A =
[[9.95930059e-01 8.01927902e-04 3.26801327e-03]
 [9.66798810e-03 9.82836422e-01 7.49558962e-03]
 [6.03406710e-03 1.63144801e-03 9.92334485e-01]]
pi = [0.59349783 0.11526423 0.29123793]
Iter 15: LL=-1280483.52 | Rates: N=0.89396, AF=0.09468, OLD=0.09290, YOUNG=0.03236
A =
[[9.95929920e-01 7.69190505e-04 3.30088983e-03]
 [9.80033352e-03 9.82064454e-01 8.13521204e-03]
 [6.04432314e-03 1.65583353e-03 9.92299843e-01]]
pi = [0.59346443 0.10881594 0.29771963]
Final Global Rates (lambdas): [0.89396251 0.09468399 0.09290461 0.0323603 ]
Final transition matrix A:
[[9.95929920e-01 7.69190505e-04 3.30088983e-03]
 [9.80033352e-03 9.82064454e-01 8.13521204e-03]
 [6.04432314e-03 1.65583353e-03 9.92299843e-01]]
Final initial distribution pi:
[0.59346443 0.10881594 0.29771963]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3503  0.1026  0.1587    8195793.0   15199207.0  71714723.0
Archaic_young     0.7945  0.9430  0.8624  287348678.0   74334322.0  17382475.0
Modern            0.0000  0.0000  0.0000          0.0  614922000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         610365           77           2304
Archaic_old      1241         8187          70890
Archaic_young    3316        15131         288489

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3142  0.1127  0.1658
Archaic_young     0.8382  0.9455  0.8886

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         609320          120           2985
Archaic_old      1126         7023          54516
Archaic_young    3511        15195         306204

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1551864.80 | Rates: N=0.89316, AF=0.09716, OLD=0.05794, YOUNG=0.03953
A =
[[0.99557808 0.00126538 0.00315654]
 [0.00763557 0.9891298  0.00323463]
 [0.00703977 0.00119489 0.99176533]]
pi = [0.65161497 0.11041707 0.23796796]
Iter 2: LL=-1288941.11 | Rates: N=0.89341, AF=0.09703, OLD=0.06373, YOUNG=0.03692
A =
[[0.99559775 0.001261   0.00314125]
 [0.00761888 0.98917037 0.00321075]
 [0.00698256 0.00117898 0.99183846]]
pi = [0.65266893 0.12265675 0.22467433]
Iter 3: LL=-1288844.54 | Rates: N=0.89341, AF=0.09699, OLD=0.06891, YOUNG=0.03523
A =
[[0.99560117 0.00125909 0.00313975]
 [0.00767285 0.98905845 0.0032687 ]
 [0.00695609 0.00118326 0.99186066]]
pi = [0.65254589 0.13827887 0.20917524]
Iter 4: LL=-1288791.70 | Rates: N=0.89341, AF=0.09696, OLD=0.07265, YOUNG=0.03435
A =
[[0.99560273 0.0012442  0.00315307]
 [0.00779432 0.98874068 0.003465  ]
 [0.00691633 0.00120256 0.99188111]]
pi = [0.65240519 0.15180646 0.19578835]
Iter 5: LL=-1288768.78 | Rates: N=0.89341, AF=0.09694, OLD=0.07536, YOUNG=0.03402
A =
[[0.99560326 0.00122004 0.0031767 ]
 [0.00793584 0.98829927 0.00376489]
 [0.00687924 0.00123437 0.99188639]]
pi = [0.65230796 0.16142505 0.18626699]
Iter 6: LL=-1288756.33 | Rates: N=0.89341, AF=0.09692, OLD=0.07752, YOUNG=0.03395
A =
[[0.9956034  0.00119021 0.00320639]
 [0.00806979 0.9877982  0.00413201]
 [0.00685133 0.00127312 0.99187555]]
pi = [0.65224635 0.16725287 0.18050078]
Iter 7: LL=-1288746.74 | Rates: N=0.89341, AF=0.09691, OLD=0.07943, YOUNG=0.03401
A =
[[0.99560343 0.00115715 0.00323942]
 [0.0081868  0.98726936 0.00454384]
 [0.00683294 0.0013148  0.99185226]]
pi = [0.65220654 0.16993233 0.17786113]
Iter 8: LL=-1288738.05 | Rates: N=0.89341, AF=0.09690, OLD=0.08123, YOUNG=0.03411
A =
[[0.99560344 0.0011224  0.00327415]
 [0.00828617 0.98672545 0.00498838]
 [0.00682234 0.0013572  0.99182047]]
pi = [0.65217997 0.1700967  0.17772333]
Iter 9: LL=-1288729.81 | Rates: N=0.89341, AF=0.09689, OLD=0.08301, YOUNG=0.03423
A =
[[0.99560348 0.00108694 0.00330959]
 [0.00837054 0.98616997 0.00545949]
 [0.00681746 0.00139916 0.99178339]]
pi = [0.65216201 0.16827316 0.17956483]
Iter 10: LL=-1288721.92 | Rates: N=0.89341, AF=0.09689, OLD=0.08479, YOUNG=0.03436
A =
[[0.99560353 0.00105137 0.0033451 ]
 [0.00844346 0.98560248 0.00595407]
 [0.00681651 0.00144003 0.99174346]]
pi = [0.65215001 0.16490329 0.1829467 ]
Iter 11: LL=-1288714.32 | Rates: N=0.89341, AF=0.09688, OLD=0.08659, YOUNG=0.03449
A =
[[0.99560359 0.00101611 0.0033803 ]
 [0.00850841 0.98502101 0.00647058]
 [0.00681811 0.00147943 0.99170246]]
pi = [0.65214225 0.16037553 0.18748222]
Iter 12: LL=-1288707.01 | Rates: N=0.89341, AF=0.09687, OLD=0.08842, YOUNG=0.03461
A =
[[9.95603651e-01 9.81415962e-04 3.41493352e-03]
 [8.56850337e-03 9.84423114e-01 7.00838293e-03]
 [6.82123112e-03 1.51709757e-03 9.91661671e-01]]
pi = [0.65213746 0.15504528 0.19281726]
Iter 13: LL=-1288699.95 | Rates: N=0.89341, AF=0.09687, OLD=0.09029, YOUNG=0.03474
A =
[[9.95603715e-01 9.47456918e-04 3.44882826e-03]
 [8.62638034e-03 9.83806256e-01 7.56736343e-03]
 [6.82512716e-03 1.55285810e-03 9.91622015e-01]]
pi = [0.65213465 0.14924059 0.19862476]
Iter 14: LL=-1288693.11 | Rates: N=0.89341, AF=0.09686, OLD=0.09222, YOUNG=0.03487
A =
[[9.95603773e-01 9.14342837e-04 3.48188376e-03]
 [8.68426273e-03 9.83167942e-01 8.14779530e-03]
 [6.82928522e-03 1.58659106e-03 9.91584124e-01]]
pi = [0.65213296 0.14325733 0.2046097 ]
Iter 15: LL=-1288686.49 | Rates: N=0.89341, AF=0.09685, OLD=0.09420, YOUNG=0.03499
A =
[[9.95603822e-01 8.82141206e-04 3.51403679e-03]
 [8.74400410e-03 9.82505776e-01 8.75021960e-03]
 [6.83335482e-03 1.61821159e-03 9.91548434e-01]]
pi = [0.65213167 0.13734928 0.21051905]
Final Global Rates (lambdas): [0.89340675 0.09685204 0.09420103 0.03499229]
Final transition matrix A:
[[9.95603822e-01 8.82141206e-04 3.51403679e-03]
 [8.74400410e-03 9.82505776e-01 8.75021960e-03]
 [6.83335482e-03 1.61821159e-03 9.91548434e-01]]
Final initial distribution pi:
[0.65213167 0.13734928 0.21051905]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3738  0.1525  0.2166    9498263.0   15911737.0  52799705.0
Archaic_young     0.8441  0.9429  0.8908  304007106.0   56149894.0  18408699.0
Modern            0.0000  0.0000  0.0000          0.0  614433000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         609483           43           2899
Archaic_old      1268         9495          51902
Archaic_young    3682        15872         305356

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3531  0.0992  0.1549
Archaic_young     0.8081  0.9461  0.8716

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         626283          106           2922
Archaic_old      1630         7010          62460
Archaic_young    4591        12730         282268

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1573945.64 | Rates: N=0.90296, AF=0.09641, OLD=0.06863, YOUNG=0.04704
A =
[[0.99539541 0.00132877 0.00327582]
 [0.00853314 0.98789647 0.00357038]
 [0.00794619 0.00136628 0.99068753]]
pi = [0.74371033 0.08376827 0.1725214 ]
Iter 2: LL=-1301859.15 | Rates: N=0.90324, AF=0.09620, OLD=0.07758, YOUNG=0.04344
A =
[[0.99543001 0.00134487 0.00322512]
 [0.0088519  0.98761679 0.0035313 ]
 [0.00772228 0.00133673 0.99094099]]
pi = [0.75073167 0.09582783 0.1534405 ]
Iter 3: LL=-1301687.01 | Rates: N=0.90324, AF=0.09613, OLD=0.08566, YOUNG=0.04109
A =
[[0.995432   0.00136364 0.00320435]
 [0.0093339  0.98707277 0.00359332]
 [0.00755435 0.0013447  0.99110096]]
pi = [0.7503293  0.11669455 0.13297616]
Iter 4: LL=-1301591.63 | Rates: N=0.90324, AF=0.09605, OLD=0.09161, YOUNG=0.04002
A =
[[0.99543104 0.00135748 0.00321148]
 [0.00986716 0.98629441 0.00383842]
 [0.00740343 0.00139174 0.99120483]]
pi = [0.74955709 0.13561962 0.1148233 ]
Iter 5: LL=-1301549.26 | Rates: N=0.90324, AF=0.09598, OLD=0.09615, YOUNG=0.03970
A =
[[0.99542963 0.00133009 0.00324028]
 [0.01037582 0.98539824 0.00422594]
 [0.00729005 0.00146393 0.99124601]]
pi = [0.74895945 0.14843232 0.10260822]
Iter 6: LL=-1301524.10 | Rates: N=0.90324, AF=0.09593, OLD=0.10001, YOUNG=0.03971
A =
[[0.99542847 0.00128918 0.00328235]
 [0.0108369  0.98445021 0.0047129 ]
 [0.00721254 0.00154583 0.99124163]]
pi = [0.74855525 0.15574109 0.09570366]
Iter 7: LL=-1301503.75 | Rates: N=0.90323, AF=0.09589, OLD=0.10361, YOUNG=0.03985
A =
[[0.99542766 0.00124121 0.00333114]
 [0.01125088 0.98347546 0.00527365]
 [0.00716263 0.00162878 0.99120859]]
pi = [0.74828168 0.15930226 0.09241605]
Iter 8: LL=-1301485.18 | Rates: N=0.90323, AF=0.09585, OLD=0.10714, YOUNG=0.04004
A =
[[0.99542711 0.00119045 0.00338244]
 [0.01162651 0.98247785 0.00589564]
 [0.0071323  0.00170857 0.99115913]]
pi = [0.74808544 0.16052864 0.09138592]
Iter 9: LL=-1301467.67 | Rates: N=0.90323, AF=0.09582, OLD=0.11072, YOUNG=0.04024
A =
[[0.99542674 0.00113955 0.00343371]
 [0.01197397 0.98145288 0.00657316]
 [0.0071154  0.00178318 0.99110142]]
pi = [0.74793023 0.16036539 0.09170438]
Iter 10: LL=-1301451.02 | Rates: N=0.90323, AF=0.09579, OLD=0.11437, YOUNG=0.04044
A =
[[0.99542647 0.00109007 0.00348345]
 [0.01230199 0.98039449 0.00730352]
 [0.00710765 0.00185166 0.99104069]]
pi = [0.74779085 0.15944167 0.09276748]
Iter 11: LL=-1301435.14 | Rates: N=0.90323, AF=0.09576, OLD=0.11813, YOUNG=0.04065
A =
[[0.99542625 0.00104293 0.00353082]
 [0.01261701 0.97929794 0.00808504]
 [0.00710622 0.00191358 0.9909802 ]]
pi = [0.74764926 0.15819252 0.09415822]
Iter 12: LL=-1301420.01 | Rates: N=0.90323, AF=0.09573, OLD=0.12200, YOUNG=0.04085
A =
[[0.99542602 0.00099859 0.00357538]
 [0.01292331 0.97816041 0.00891628]
 [0.00710925 0.00196884 0.99092191]]
pi = [0.7474931  0.156923   0.09558389]
Iter 13: LL=-1301405.59 | Rates: N=0.90322, AF=0.09570, OLD=0.12600, YOUNG=0.04105
A =
[[9.95425756e-01 9.57270196e-04 3.61697340e-03]
 [1.32236333e-02 9.76980431e-01 9.79593558e-03]
 [7.11552733e-03 2.01752032e-03 9.90866952e-01]]
pi = [0.74731502 0.15583705 0.09684793]
Iter 14: LL=-1301391.85 | Rates: N=0.90322, AF=0.09567, OLD=0.13013, YOUNG=0.04125
A =
[[9.95425419e-01 9.18986748e-04 3.65559416e-03]
 [1.35200388e-02 9.75756644e-01 1.07233169e-02]
 [7.12422527e-03 2.05985507e-03 9.90815920e-01]]
pi = [0.74711161 0.15505319 0.0978352 ]
Iter 15: LL=-1301378.70 | Rates: N=0.90322, AF=0.09564, OLD=0.13443, YOUNG=0.04144
A =
[[9.95424981e-01 8.83652311e-04 3.69136714e-03]
 [1.38146990e-02 9.74486414e-01 1.16988866e-02]
 [7.13472963e-03 2.09615461e-03 9.90769116e-01]]
pi = [0.74688216 0.15461995 0.09849789]
Final Global Rates (lambdas): [0.90321822 0.09564098 0.13442924 0.04144387]
Final transition matrix A:
[[9.95424981e-01 8.83652311e-04 3.69136714e-03]
 [1.38146990e-02 9.74486414e-01 1.16988866e-02]
 [7.13472963e-03 2.09615461e-03 9.90769116e-01]]
Final initial distribution pi:
[0.74688216 0.15461995 0.09849789]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3329  0.0963  0.1494    6805131.0   13638869.0  63832546.0
Archaic_young     0.8078  0.9442  0.8707  280355683.0   66690317.0  16578799.0
Modern            0.0000  0.0000  0.0000          0.0  632510000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         626331          237           2743
Archaic_old      1654         6808          62638
Archaic_young    4525        13399         281665

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2384  0.0759  0.1152
Archaic_young     0.8259  0.9384  0.8786

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         633596           39           3080
Archaic_old      1554         4588          54738
Archaic_young    5225        14650         282530

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1580945.15 | Rates: N=0.90148, AF=0.09703, OLD=0.07433, YOUNG=0.05254
A =
[[0.99526326 0.00131931 0.00341744]
 [0.00891402 0.98703151 0.00405447]
 [0.00852484 0.0014819  0.98999326]]
pi = [0.55534354 0.11628367 0.32837279]
Iter 2: LL=-1309514.36 | Rates: N=0.90175, AF=0.09689, OLD=0.08362, YOUNG=0.04859
A =
[[0.99532995 0.00132735 0.00334271]
 [0.00898287 0.98701753 0.00399959]
 [0.00831323 0.00143215 0.99025462]]
pi = [0.55237094 0.09351281 0.35411625]
Iter 3: LL=-1309339.99 | Rates: N=0.90175, AF=0.09680, OLD=0.09239, YOUNG=0.04598
A =
[[0.99533673 0.00135106 0.00331222]
 [0.00928312 0.98666787 0.00404901]
 [0.00819058 0.00140215 0.99040727]]
pi = [0.5522832  0.06918656 0.37853024]
Iter 4: LL=-1309238.96 | Rates: N=0.90174, AF=0.09670, OLD=0.09894, YOUNG=0.04477
A =
[[0.99533758 0.0013534  0.00330902]
 [0.00970271 0.98597849 0.0043188 ]
 [0.00806133 0.00140153 0.99053715]]
pi = [0.5522915  0.04881999 0.39888851]
Iter 5: LL=-1309194.66 | Rates: N=0.90174, AF=0.09662, OLD=0.10398, YOUNG=0.04443
A =
[[0.99533684 0.00133591 0.00332725]
 [0.01013235 0.98510336 0.00476429]
 [0.00795812 0.00142641 0.99061547]]
pi = [0.55229852 0.03342619 0.41427529]
Iter 6: LL=-1309169.05 | Rates: N=0.90174, AF=0.09656, OLD=0.10831, YOUNG=0.04448
A =
[[0.99533582 0.00130456 0.00335963]
 [0.01052012 0.98414682 0.00533307]
 [0.00788892 0.00146505 0.99064603]]
pi = [0.55229682 0.02228488 0.4254183 ]
Iter 7: LL=-1309148.26 | Rates: N=0.90174, AF=0.09652, OLD=0.11240, YOUNG=0.04466
A =
[[0.99533486 0.00126467 0.00340047]
 [0.01085276 0.98315259 0.00599466]
 [0.00784887 0.00150985 0.99064128]]
pi = [0.55229252 0.01453389 0.43317359]
Iter 8: LL=-1309128.93 | Rates: N=0.90173, AF=0.09647, OLD=0.11649, YOUNG=0.04490
A =
[[0.99533402 0.00122011 0.00344587]
 [0.0111342  0.98213044 0.00673536]
 [0.00783032 0.00155703 0.99061265]]
pi = [0.55229084 0.00934403 0.43836513]
Iter 9: LL=-1309110.22 | Rates: N=0.90173, AF=0.09643, OLD=0.12069, YOUNG=0.04514
A =
[[0.99533323 0.0011735  0.00349327]
 [0.01137523 0.98107357 0.0075512 ]
 [0.00782633 0.00160475 0.99056892]]
pi = [0.55229289 0.00597213 0.44173497]
Iter 10: LL=-1309091.83 | Rates: N=0.90173, AF=0.09639, OLD=0.12507, YOUNG=0.04538
A =
[[0.99533243 0.00112657 0.003541  ]
 [0.01158873 0.97996756 0.00844371]
 [0.0078315  0.00165206 0.99051645]]
pi = [0.55229766 0.00382289 0.44387946]
Iter 11: LL=-1309073.58 | Rates: N=0.90173, AF=0.09635, OLD=0.12969, YOUNG=0.04562
A =
[[0.99533152 0.00108049 0.00358798]
 [0.01178773 0.97879419 0.00941808]
 [0.00784186 0.00169843 0.99045971]]
pi = [0.55230371 0.00246493 0.44523136]
Iter 12: LL=-1309055.31 | Rates: N=0.90173, AF=0.09630, OLD=0.13463, YOUNG=0.04585
A =
[[0.99533042 0.001036   0.00363358]
 [0.01198503 0.97753251 0.01048246]
 [0.00785461 0.00174351 0.99040188]]
pi = [0.55230987 0.0016073  0.44608282]
Iter 13: LL=-1309036.77 | Rates: N=0.90172, AF=0.09626, OLD=0.13997, YOUNG=0.04609
A =
[[9.95329016e-01 9.93536466e-04 3.67744769e-03]
 [1.21932965e-02 9.76158973e-01 1.16477308e-02]
 [7.86777001e-03 1.78697886e-03 9.90345251e-01]]
pi = [0.55231533 0.00106253 0.44662213]
Iter 14: LL=-1309017.69 | Rates: N=0.90172, AF=0.09620, OLD=0.14583, YOUNG=0.04632
A =
[[9.95327175e-01 9.53366206e-04 3.71945900e-03]
 [1.24253608e-02 9.74647357e-01 1.29272821e-02]
 [7.88007068e-03 1.82839085e-03 9.90291538e-01]]
pi = [0.55231956 0.00071298 0.44696745]
Iter 15: LL=-1308997.69 | Rates: N=0.90172, AF=0.09614, OLD=0.15235, YOUNG=0.04656
A =
[[9.95324736e-01 9.15618630e-04 3.75964519e-03]
 [1.26946761e-02 9.72968474e-01 1.43368496e-02]
 [7.89073146e-03 1.86716553e-03 9.90242103e-01]]
pi = [5.52322262e-01 4.85780392e-04 4.47191957e-01]
Final Global Rates (lambdas): [0.90171676 0.09613886 0.15234548 0.04656495]
Final transition matrix A:
[[9.95324736e-01 9.15618630e-04 3.75964519e-03]
 [1.26946761e-02 9.72968474e-01 1.43368496e-02]
 [7.89073146e-03 1.86716553e-03 9.90242103e-01]]
Final initial distribution pi:
[5.52322262e-01 4.85780392e-04 4.47191957e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2538  0.0863  0.1288    5225495.0   15364505.0  55297654.0
Archaic_young     0.8277  0.9380  0.8794  280969779.0   58483221.0  18582692.0
Modern            0.0000  0.0000  0.0000          0.0  639957000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         633527          296           2892
Archaic_old      1443         5230          54207
Archaic_young    4987        15064         282354

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old        0.223  0.3114  0.2599
Archaic_young      0.799  0.7205  0.7577

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         621755          747           1882
Archaic_old      1229        23549          51224
Archaic_young    3122        81234         215258

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1550489.12 | Rates: N=0.89706, AF=0.09664, OLD=0.05441, YOUNG=0.03248
A =
[[0.99626734 0.0015328  0.00219985]
 [0.00660411 0.99157003 0.00182585]
 [0.00624633 0.00121887 0.9925348 ]]
pi = [0.5992315  0.15897324 0.24179526]
Iter 2: LL=-1283793.23 | Rates: N=0.89729, AF=0.09641, OLD=0.05704, YOUNG=0.03145
A =
[[0.99626452 0.001513   0.00222248]
 [0.00691077 0.99115763 0.0019316 ]
 [0.00605492 0.00118526 0.99275983]]
pi = [0.59892478 0.17175846 0.22931676]
Iter 3: LL=-1283767.48 | Rates: N=0.89729, AF=0.09639, OLD=0.05926, YOUNG=0.03103
A =
[[0.99626441 0.00148949 0.0022461 ]
 [0.00718819 0.99074643 0.00206538]
 [0.00592524 0.00118043 0.99289432]]
pi = [0.59888243 0.18444813 0.21666944]
Iter 4: LL=-1283752.94 | Rates: N=0.89729, AF=0.09637, OLD=0.06106, YOUNG=0.03092
A =
[[0.99626417 0.00145817 0.00227766]
 [0.00743848 0.9903278  0.00223372]
 [0.00583104 0.00119122 0.99297774]]
pi = [0.59882096 0.19515521 0.20602383]
Iter 5: LL=-1283742.85 | Rates: N=0.89729, AF=0.09636, OLD=0.06262, YOUNG=0.03097
A =
[[0.99626384 0.00142075 0.00231541]
 [0.00766115 0.98990837 0.00243048]
 [0.00576576 0.00121163 0.99302261]]
pi = [0.59875359 0.20341048 0.19783593]
Iter 6: LL=-1283734.30 | Rates: N=0.89729, AF=0.09635, OLD=0.06407, YOUNG=0.03109
A =
[[0.99626353 0.00137907 0.00235741]
 [0.00785968 0.98948901 0.00265131]
 [0.00572227 0.00123746 0.99304027]]
pi = [0.59868847 0.20918249 0.19212904]
Iter 7: LL=-1283726.28 | Rates: N=0.89729, AF=0.09634, OLD=0.06547, YOUNG=0.03124
A =
[[0.99626326 0.00133468 0.00240206]
 [0.00803855 0.98906756 0.00289388]
 [0.0056947  0.00126613 0.99303916]]
pi = [0.59863008 0.2125877  0.18878223]
Iter 8: LL=-1283718.46 | Rates: N=0.89729, AF=0.09633, OLD=0.06688, YOUNG=0.03139
A =
[[0.99626305 0.00128877 0.00244817]
 [0.00820202 0.98864076 0.00315722]
 [0.00567871 0.00129604 0.99302525]]
pi = [0.59858061 0.21377563 0.18764377]
Iter 9: LL=-1283710.74 | Rates: N=0.89729, AF=0.09632, OLD=0.06832, YOUNG=0.03155
A =
[[0.99626289 0.00124225 0.00249486]
 [0.00835367 0.98820521 0.00344112]
 [0.00567109 0.00132615 0.99300276]]
pi = [0.59854096 0.21289057 0.18856846]
Iter 10: LL=-1283703.08 | Rates: N=0.89729, AF=0.09632, OLD=0.06979, YOUNG=0.03171
A =
[[0.99626276 0.00119577 0.00254146]
 [0.0084964  0.98775786 0.00374575]
 [0.00566956 0.00135577 0.99297467]]
pi = [0.59851138 0.2100607  0.19142792]
Iter 11: LL=-1283695.51 | Rates: N=0.89729, AF=0.09631, OLD=0.07132, YOUNG=0.03186
A =
[[0.99626266 0.00114985 0.00258749]
 [0.00863242 0.98729613 0.00407146]
 [0.00567248 0.00138438 0.99294314]]
pi = [0.59849173 0.20539677 0.19611149]
Iter 12: LL=-1283688.02 | Rates: N=0.89729, AF=0.09630, OLD=0.07289, YOUNG=0.03201
A =
[[0.99626258 0.00110485 0.00263257]
 [0.0087634  0.98681795 0.00441865]
 [0.00567867 0.00141163 0.9929097 ]]
pi = [0.59848175 0.19899505 0.2025232 ]
Iter 13: LL=-1283680.66 | Rates: N=0.89729, AF=0.09630, OLD=0.07451, YOUNG=0.03216
A =
[[0.99626251 0.00106105 0.00267644]
 [0.00889054 0.9863217  0.00478776]
 [0.00568727 0.00143726 0.99287547]]
pi = [0.59848111 0.19094304 0.21057585]
Iter 14: LL=-1283673.42 | Rates: N=0.89729, AF=0.09629, OLD=0.07618, YOUNG=0.03230
A =
[[0.99626245 0.00101866 0.0027189 ]
 [0.0090147  0.98580609 0.00517921]
 [0.00569766 0.00146108 0.99284126]]
pi = [0.59848943 0.18132799 0.22018258]
Iter 15: LL=-1283666.34 | Rates: N=0.89729, AF=0.09628, OLD=0.07791, YOUNG=0.03244
A =
[[9.96262388e-01 9.77814859e-04 2.75979677e-03]
 [9.13648256e-03 9.85270060e-01 5.59345790e-03]
 [5.70938910e-03 1.48297413e-03 9.92807637e-01]]
pi = [0.59850632 0.17024788 0.2312458 ]
Final Global Rates (lambdas): [0.89729235 0.09628292 0.07790906 0.03244318]
Final transition matrix A:
[[9.96262388e-01 9.77814859e-04 2.75979677e-03]
 [9.13648256e-03 9.85270060e-01 5.59345790e-03]
 [5.70938910e-03 1.48297413e-03 9.92807637e-01]]
Final initial distribution pi:
[0.59850632 0.17024788 0.2312458 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2812  0.1181  0.1663    8922075.0   22810925.0  66642501.0
Archaic_young     0.7979  0.9185  0.8539  273360482.0   69255518.0  24257792.0
Modern            0.0000  0.0000  0.0000          0.0  625651000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         621702          373           2309
Archaic_old      1128         8939          65935
Archaic_young    2821        22421         274372

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3231  0.2703  0.2944
Archaic_young     0.8203  0.8549  0.8373

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         614829          422           2472
Archaic_old      1551        20261          53529
Archaic_young    3395        41957         261584

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1551852.36 | Rates: N=0.89735, AF=0.09636, OLD=0.05896, YOUNG=0.03461
A =
[[0.99587552 0.00148266 0.00264182]
 [0.00755757 0.98997384 0.00246858]
 [0.00651503 0.00118812 0.99229686]]
pi = [0.71605574 0.1502197  0.13372455]
Iter 2: LL=-1285450.49 | Rates: N=0.89760, AF=0.09618, OLD=0.06353, YOUNG=0.03276
A =
[[0.99588535 0.00146568 0.00264897]
 [0.00785898 0.98956075 0.00258027]
 [0.00635964 0.00113694 0.99250342]]
pi = [0.71896477 0.18733943 0.0936958 ]
Iter 3: LL=-1285392.65 | Rates: N=0.89760, AF=0.09614, OLD=0.06715, YOUNG=0.03200
A =
[[0.99588593 0.00144717 0.0026669 ]
 [0.00812574 0.98911298 0.00276128]
 [0.00627708 0.00112292 0.99260001]]
pi = [0.71619948 0.21424398 0.06955654]
Iter 4: LL=-1285367.17 | Rates: N=0.89760, AF=0.09610, OLD=0.06990, YOUNG=0.03178
A =
[[0.99588595 0.00141594 0.00269812]
 [0.00836486 0.98861446 0.00302068]
 [0.0062232  0.00112812 0.99264868]]
pi = [0.71441904 0.23108199 0.05449897]
Iter 5: LL=-1285352.34 | Rates: N=0.89760, AF=0.09607, OLD=0.07221, YOUNG=0.03182
A =
[[0.99588584 0.00137554 0.00273862]
 [0.00857623 0.98808665 0.00333712]
 [0.006192   0.00114418 0.99266382]]
pi = [0.71338057 0.24169138 0.04492804]
Iter 6: LL=-1285340.22 | Rates: N=0.89760, AF=0.09605, OLD=0.07437, YOUNG=0.03196
A =
[[0.99588574 0.00132932 0.00278494]
 [0.00876473 0.9875386  0.00369667]
 [0.0061769  0.00116594 0.99265717]]
pi = [0.71271334 0.24860236 0.03868429]
Iter 7: LL=-1285328.73 | Rates: N=0.89760, AF=0.09604, OLD=0.07651, YOUNG=0.03214
A =
[[0.9958857  0.00127958 0.00283472]
 [0.00893668 0.98697076 0.00409255]
 [0.00617253 0.0011906  0.99263687]]
pi = [0.71224449 0.25319342 0.03456209]
Iter 8: LL=-1285317.33 | Rates: N=0.89760, AF=0.09602, OLD=0.07872, YOUNG=0.03234
A =
[[0.99588574 0.00122781 0.00288645]
 [0.0090984  0.98637913 0.00452246]
 [0.00617503 0.00121662 0.99260835]]
pi = [0.71189695 0.25619556 0.03190749]
Iter 9: LL=-1285305.83 | Rates: N=0.89760, AF=0.09600, OLD=0.08105, YOUNG=0.03254
A =
[[0.99588586 0.00117495 0.00293919]
 [0.00925535 0.98575814 0.00498651]
 [0.00618178 0.001243   0.99257522]]
pi = [0.71163406 0.25799274 0.0303732 ]
Iter 10: LL=-1285294.15 | Rates: N=0.89760, AF=0.09598, OLD=0.08354, YOUNG=0.03274
A =
[[0.99588606 0.00112161 0.00299233]
 [0.00941189 0.98510198 0.00548613]
 [0.0061911  0.001269   0.99253989]]
pi = [0.71143693 0.25877481 0.02978826]
Iter 11: LL=-1285282.23 | Rates: N=0.89760, AF=0.09596, OLD=0.08621, YOUNG=0.03294
A =
[[0.99588633 0.00106824 0.00304543]
 [0.00957137 0.98440504 0.00602359]
 [0.00620199 0.00129401 0.992504  ]]
pi = [0.7112951 0.258617  0.0300879]
Iter 12: LL=-1285270.04 | Rates: N=0.89760, AF=0.09594, OLD=0.08909, YOUNG=0.03314
A =
[[0.99588662 0.00101523 0.00309815]
 [0.00973629 0.98366217 0.00660154]
 [0.0062139  0.00131747 0.99246863]]
pi = [0.71120184 0.25752956 0.0312686 ]
Iter 13: LL=-1285257.62 | Rates: N=0.89760, AF=0.09592, OLD=0.09216, YOUNG=0.03333
A =
[[9.95886857e-01 9.63026571e-04 3.15011670e-03]
 [9.90824649e-03 9.82869164e-01 7.22258966e-03]
 [6.22656439e-03 1.33893049e-03 9.92434505e-01]]
pi = [0.71115137 0.25550234 0.03334629]
Iter 14: LL=-1285245.07 | Rates: N=0.89760, AF=0.09590, OLD=0.09544, YOUNG=0.03353
A =
[[9.95886998e-01 9.12128116e-04 3.20087408e-03]
 [1.00878537e-02 9.82023396e-01 7.88875039e-03]
 [6.23980565e-03 1.35811377e-03 9.92402081e-01]]
pi = [0.71113713 0.25255429 0.03630858]
Iter 15: LL=-1285232.50 | Rates: N=0.89760, AF=0.09588, OLD=0.09892, YOUNG=0.03372
A =
[[9.95887045e-01 8.63007126e-04 3.24994769e-03]
 [1.02752423e-02 9.81122977e-01 8.60178050e-03]
 [6.25339342e-03 1.37492006e-03 9.92371687e-01]]
pi = [0.7111518  0.24878117 0.04006704]
Final Global Rates (lambdas): [0.8975993  0.09588282 0.09891617 0.03372445]
Final transition matrix A:
[[9.95887045e-01 8.63007126e-04 3.24994769e-03]
 [1.02752423e-02 9.81122977e-01 8.60178050e-03]
 [6.25339342e-03 1.37492006e-03 9.92371687e-01]]
Final initial distribution pi:
[0.7111518  0.24878117 0.04006704]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3918  0.1200  0.1837    8982064.0   13942936.0  65895024.0
Archaic_young     0.8083  0.9469  0.8721  288540885.0   68412115.0  16190268.0
Modern            0.0000  0.0000  0.0000          0.0  620122000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         614895          177           2651
Archaic_old      1758         8980          64603
Archaic_young    3469        13768         289699

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3335  0.2336  0.2747
Archaic_young     0.8575  0.9076  0.8818

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         612034          326           2828
Archaic_old      1417        13908          44577
Archaic_young    3625        27427         293858

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1560382.73 | Rates: N=0.89946, AF=0.09766, OLD=0.06279, YOUNG=0.03778
A =
[[0.99546199 0.00149474 0.00304327]
 [0.00847937 0.98842698 0.00309365]
 [0.00707469 0.0012494  0.99167591]]
pi = [0.65132593 0.10052506 0.24814901]
Iter 2: LL=-1291838.37 | Rates: N=0.89972, AF=0.09758, OLD=0.06845, YOUNG=0.03521
A =
[[0.99548332 0.0014883  0.00302837]
 [0.00867732 0.98813241 0.00319027]
 [0.00694847 0.00121792 0.99183361]]
pi = [0.65266976 0.09105629 0.25627395]
Iter 3: LL=-1291753.32 | Rates: N=0.89972, AF=0.09754, OLD=0.07289, YOUNG=0.03395
A =
[[0.995484   0.00148676 0.00302924]
 [0.00885683 0.98777095 0.00337222]
 [0.00689455 0.00123069 0.99187476]]
pi = [0.6526964  0.08630518 0.26099842]
Iter 4: LL=-1291718.16 | Rates: N=0.89972, AF=0.09751, OLD=0.07596, YOUNG=0.03343
A =
[[0.99548347 0.00147075 0.00304578]
 [0.0090427  0.98728982 0.00366748]
 [0.00685295 0.00126583 0.99188122]]
pi = [0.65269986 0.08357524 0.2637249 ]
Iter 5: LL=-1291702.09 | Rates: N=0.89972, AF=0.09748, OLD=0.07828, YOUNG=0.03329
A =
[[0.99548305 0.00144482 0.00307213]
 [0.00921471 0.98674846 0.00403683]
 [0.00682471 0.00131394 0.99186135]]
pi = [0.65270681 0.08147977 0.26581342]
Iter 6: LL=-1291691.06 | Rates: N=0.89972, AF=0.09747, OLD=0.08025, YOUNG=0.03331
A =
[[0.99548284 0.00141292 0.00310424]
 [0.00936725 0.9861797  0.00445305]
 [0.00680786 0.00136823 0.99182391]]
pi = [0.65271277 0.0794298  0.26785743]
Iter 7: LL=-1291681.38 | Rates: N=0.89972, AF=0.09745, OLD=0.08209, YOUNG=0.03339
A =
[[0.9954828  0.00137758 0.00313962]
 [0.00950206 0.98559628 0.00490167]
 [0.00679943 0.00142499 0.99177558]]
pi = [0.652718  0.0772898 0.2699922]
Iter 8: LL=-1291672.24 | Rates: N=0.89972, AF=0.09744, OLD=0.08389, YOUNG=0.03350
A =
[[0.99548288 0.00134034 0.00317678]
 [0.00962313 0.98500124 0.00537563]
 [0.00679677 0.00148232 0.9917209 ]]
pi = [0.65272319 0.07508802 0.27218879]
Iter 9: LL=-1291663.47 | Rates: N=0.89972, AF=0.09743, OLD=0.08569, YOUNG=0.03361
A =
[[0.99548305 0.00130218 0.00321477]
 [0.00973465 0.98439361 0.00587175]
 [0.00679787 0.00153919 0.99166295]]
pi = [0.65272856 0.07289033 0.27438112]
Iter 10: LL=-1291654.99 | Rates: N=0.89972, AF=0.09742, OLD=0.08751, YOUNG=0.03373
A =
[[0.99548328 0.0012637  0.00325301]
 [0.00984025 0.98377101 0.00638874]
 [0.00680127 0.00159493 0.9916038 ]]
pi = [0.65273405 0.07075891 0.27650704]
Iter 11: LL=-1291646.78 | Rates: N=0.89972, AF=0.09741, OLD=0.08938, YOUNG=0.03385
A =
[[0.99548357 0.00122534 0.00329109]
 [0.00994289 0.98313076 0.00692636]
 [0.00680598 0.00164912 0.9915449 ]]
pi = [0.6527395  0.06874275 0.27851775]
Iter 12: LL=-1291638.82 | Rates: N=0.89972, AF=0.09739, OLD=0.09130, YOUNG=0.03397
A =
[[0.9954839  0.00118735 0.00332875]
 [0.01004488 0.98247016 0.00748496]
 [0.00681135 0.00170141 0.99148724]]
pi = [0.65274469 0.06687777 0.28037754]
Iter 13: LL=-1291631.06 | Rates: N=0.89972, AF=0.09738, OLD=0.09328, YOUNG=0.03409
A =
[[0.99548428 0.00114993 0.0033658 ]
 [0.01014805 0.9817866  0.00806535]
 [0.00681696 0.00175153 0.99143151]]
pi = [0.65274943 0.06518912 0.28206145]
Iter 14: LL=-1291623.49 | Rates: N=0.89972, AF=0.09737, OLD=0.09532, YOUNG=0.03421
A =
[[0.99548469 0.00111319 0.00340212]
 [0.01025383 0.9810774  0.00866877]
 [0.00682253 0.00179924 0.99137823]]
pi = [0.65275352 0.06369352 0.28355296]
Iter 15: LL=-1291616.06 | Rates: N=0.89972, AF=0.09735, OLD=0.09745, YOUNG=0.03433
A =
[[0.99548515 0.0010772  0.00343765]
 [0.01036343 0.98033972 0.00929685]
 [0.00682793 0.00184434 0.99132773]]
pi = [0.6527568  0.06240108 0.28484213]
Final Global Rates (lambdas): [0.89971775 0.09735289 0.09745279 0.03432691]
Final transition matrix A:
[[0.99548515 0.0010772  0.00343765]
 [0.01036343 0.98033972 0.00929685]
 [0.00682793 0.00184434 0.99132773]]
Final initial distribution pi:
[0.6527568  0.06240108 0.28484213]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3834  0.1691  0.2347   10056317.0   16175683.0  49421050.0
Archaic_young     0.8528  0.9417  0.8951  303630541.0   52417459.0  18785264.0
Modern            0.0000  0.0000  0.0000          0.0  617720000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         612229           87           2872
Archaic_old      1570        10052          48280
Archaic_young    3921        16093         304896

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3197  0.2042  0.2493
Archaic_young     0.8392  0.8993  0.8682

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         636323          151           2745
Archaic_old      1586        12391          47215
Archaic_young    5033        26283         268273

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1576959.88 | Rates: N=0.90615, AF=0.09659, OLD=0.07176, YOUNG=0.04400
A =
[[0.99550665 0.00145062 0.00304273]
 [0.00916541 0.98745936 0.00337523]
 [0.00785483 0.00142561 0.99071956]]
pi = [0.78767751 0.04506072 0.16726178]
Iter 2: LL=-1302155.31 | Rates: N=0.90643, AF=0.09645, OLD=0.07952, YOUNG=0.04089
A =
[[0.99555217 0.00143446 0.00301337]
 [0.00963939 0.9869573  0.00340331]
 [0.00756194 0.00138096 0.9910571 ]]
pi = [0.79777965 0.0207731  0.18144725]
Iter 3: LL=-1302034.18 | Rates: N=0.90643, AF=0.09636, OLD=0.08615, YOUNG=0.03945
A =
[[0.99555479 0.00142497 0.00302024]
 [0.01019157 0.98627184 0.00353659]
 [0.00739122 0.00138813 0.99122065]]
pi = [0.79810705 0.00761284 0.19428011]
Iter 4: LL=-1301977.30 | Rates: N=0.90643, AF=0.09628, OLD=0.09129, YOUNG=0.03898
A =
[[0.99555343 0.00139413 0.00305243]
 [0.01075694 0.98541747 0.00382559]
 [0.00726433 0.00142211 0.99131356]]
pi = [0.79809908 0.0022958  0.19960512]
Iter 5: LL=-1301946.58 | Rates: N=0.90643, AF=0.09620, OLD=0.09565, YOUNG=0.03898
A =
[[0.99555147 0.00134725 0.00310128]
 [0.01128993 0.98448033 0.00422975]
 [0.00718139 0.00146946 0.99134915]]
pi = [7.98150053e-01 6.16024594e-04 2.01233923e-01]
Iter 6: LL=-1301923.06 | Rates: N=0.90644, AF=0.09615, OLD=0.09973, YOUNG=0.03916
A =
[[0.99554984 0.00129048 0.00315968]
 [0.0117764  0.98350472 0.00471888]
 [0.00713377 0.00152108 0.99134515]]
pi = [7.98213930e-01 1.53693089e-04 2.01632377e-01]
Iter 7: LL=-1301901.60 | Rates: N=0.90644, AF=0.09610, OLD=0.10379, YOUNG=0.03941
A =
[[0.99554866 0.00122857 0.00322277]
 [0.01221816 0.98250438 0.00527746]
 [0.00711184 0.00157241 0.99131575]]
pi = [7.98269790e-01 3.63889999e-05 2.01693821e-01]
Iter 8: LL=-1301881.02 | Rates: N=0.90643, AF=0.09605, OLD=0.10795, YOUNG=0.03968
A =
[[0.99554783 0.00116478 0.00328739]
 [0.01262307 0.98147836 0.00589857]
 [0.00710764 0.00162126 0.9912711 ]]
pi = [7.98314847e-01 8.25499637e-06 2.01676898e-01]
Iter 9: LL=-1301861.01 | Rates: N=0.90643, AF=0.09601, OLD=0.11227, YOUNG=0.03995
A =
[[0.9955472  0.00110127 0.00335153]
 [0.01300077 0.98041926 0.00657996]
 [0.00711523 0.00166658 0.99121818]]
pi = [7.98350805e-01 1.80351625e-06 2.01647392e-01]
Iter 10: LL=-1301841.49 | Rates: N=0.90643, AF=0.09597, OLD=0.11681, YOUNG=0.04021
A =
[[0.99554666 0.00103938 0.00341396]
 [0.01336135 0.97931611 0.00732253]
 [0.00713036 0.00170789 0.99116175]]
pi = [7.98379829e-01 3.80731041e-07 2.01619790e-01]
Iter 11: LL=-1301822.35 | Rates: N=0.90643, AF=0.09593, OLD=0.12162, YOUNG=0.04047
A =
[[9.95546095e-01 9.79957324e-04 3.47394792e-03]
 [1.37154880e-02 9.78154307e-01 8.13020505e-03]
 [7.14997987e-03 1.74495881e-03 9.91105061e-01]]
pi = [7.98403709e-01 7.78624988e-08 2.01596213e-01]
Iter 12: LL=-1301803.41 | Rates: N=0.90643, AF=0.09589, OLD=0.12678, YOUNG=0.04073
A =
[[9.95545386e-01 9.23508305e-04 3.53110527e-03]
 [1.40750293e-02 9.76914631e-01 9.01033969e-03]
 [7.17199455e-03 1.77761866e-03 9.91050387e-01]]
pi = [7.98423774e-01 1.54602711e-08 2.01576211e-01]
Iter 13: LL=-1301784.35 | Rates: N=0.90643, AF=0.09584, OLD=0.13241, YOUNG=0.04100
A =
[[9.95544415e-01 8.70248930e-04 3.58533618e-03]
 [1.44536309e-02 9.75571645e-01 9.97472388e-03]
 [7.19497481e-03 1.80559266e-03 9.90999433e-01]]
pi = [7.98440948e-01 2.98638469e-09 2.01559049e-01]
Iter 14: LL=-1301764.74 | Rates: N=0.90642, AF=0.09578, OLD=0.13863, YOUNG=0.04127
A =
[[9.95543177e-01 8.20086249e-04 3.63673705e-03]
 [1.48661871e-02 9.74092868e-01 1.10409454e-02]
 [7.21802412e-03 1.82842022e-03 9.90953556e-01]]
pi = [7.98455858e-01 5.62243226e-10 2.01544141e-01]
Iter 15: LL=-1301744.23 | Rates: N=0.90642, AF=0.09573, OLD=0.14551, YOUNG=0.04154
A =
[[9.95541796e-01 7.72759041e-04 3.68544457e-03]
 [1.53264802e-02 9.72442231e-01 1.22312886e-02]
 [7.24069868e-03 1.84563091e-03 9.90913670e-01]]
pi = [7.98468992e-01 1.03421398e-10 2.01531008e-01]
Final Global Rates (lambdas): [0.90641871 0.09572638 0.14551417 0.0415427 ]
Final transition matrix A:
[[9.95541796e-01 7.72759041e-04 3.68544457e-03]
 [1.53264802e-02 9.72442231e-01 1.22312886e-02]
 [7.24069868e-03 1.84563091e-03 9.90913670e-01]]
Final initial distribution pi:
[7.98468992e-01 1.03421398e-10 2.01531008e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3588  0.1063  0.1641    6463520.0   11551480.0  54319861.0
Archaic_young     0.8313  0.9516  0.8874  282574641.0   57351359.0  14359841.0
Modern            0.0000  0.0000  0.0000          0.0  642059000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         636102          381           2736
Archaic_old      1379         6471          53342
Archaic_young    4578        11163         283848

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2685  0.5231  0.3549
Archaic_young     0.8583  0.6777  0.7574

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         630282         1011           1708
Archaic_old      1465        35066          30854
Archaic_young    2945        94254         202415

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1559256.93 | Rates: N=0.90278, AF=0.09643, OLD=0.05850, YOUNG=0.03146
A =
[[0.99623973 0.001737   0.00202328]
 [0.00719349 0.99102906 0.00177745]
 [0.00628643 0.00132059 0.99239298]]
pi = [0.60779761 0.13496345 0.25723894]
Iter 2: LL=-1287563.71 | Rates: N=0.90303, AF=0.09621, OLD=0.06110, YOUNG=0.03071
A =
[[0.99623586 0.00171062 0.00205352]
 [0.00758878 0.99041399 0.00199723]
 [0.00605491 0.00129813 0.99264696]]
pi = [0.60408486 0.12155563 0.27435951]
Iter 3: LL=-1287537.37 | Rates: N=0.90304, AF=0.09618, OLD=0.06340, YOUNG=0.03052
A =
[[0.99623452 0.00168294 0.00208254]
 [0.00789903 0.98985401 0.00224697]
 [0.00592693 0.00131682 0.99275625]]
pi = [0.6040304  0.11103245 0.28493715]
Iter 4: LL=-1287519.89 | Rates: N=0.90304, AF=0.09615, OLD=0.06537, YOUNG=0.03056
A =
[[0.99623356 0.00164677 0.00211967]
 [0.00815799 0.98930577 0.00253624]
 [0.00584902 0.00135238 0.9927986 ]]
pi = [0.60406511 0.1030084  0.29292649]
Iter 5: LL=-1287505.58 | Rates: N=0.90304, AF=0.09613, OLD=0.06718, YOUNG=0.03069
A =
[[0.9962328  0.00160452 0.00216268]
 [0.0083766  0.98876437 0.00285903]
 [0.00580512 0.00139734 0.99279753]]
pi = [0.60409202 0.09676455 0.29914343]
Iter 6: LL=-1287492.50 | Rates: N=0.90304, AF=0.09611, OLD=0.06893, YOUNG=0.03086
A =
[[0.99623224 0.0015584  0.00220936]
 [0.0085653  0.98822277 0.00321193]
 [0.0057834  0.00144745 0.99276915]]
pi = [0.60410624 0.09172368 0.30417008]
Iter 7: LL=-1287479.98 | Rates: N=0.90305, AF=0.09609, OLD=0.07068, YOUNG=0.03103
A =
[[0.99623184 0.0015101  0.00225806]
 [0.00873292 0.98767361 0.00359346]
 [0.00577587 0.00150025 0.99272388]]
pi = [0.60410933 0.0874883  0.30840237]
Iter 8: LL=-1287467.80 | Rates: N=0.90305, AF=0.09608, OLD=0.07246, YOUNG=0.03119
A =
[[0.99623155 0.00146083 0.00230762]
 [0.00888627 0.98711051 0.00400321]
 [0.00577732 0.00155429 0.99266839]]
pi = [0.60410415 0.08380454 0.31209131]
Iter 9: LL=-1287455.88 | Rates: N=0.90305, AF=0.09606, OLD=0.07429, YOUNG=0.03135
A =
[[0.99623134 0.00141146 0.0023572 ]
 [0.00903043 0.98652838 0.00444119]
 [0.00578434 0.00160862 0.99260704]]
pi = [0.60409336 0.08051807 0.31538858]
Iter 10: LL=-1287444.21 | Rates: N=0.90305, AF=0.09605, OLD=0.07618, YOUNG=0.03151
A =
[[0.99623117 0.00136261 0.00240622]
 [0.00916913 0.98592337 0.0049075 ]
 [0.00579471 0.00166259 0.99254269]]
pi = [0.60407898 0.07753831 0.31838271]
Iter 11: LL=-1287432.81 | Rates: N=0.90305, AF=0.09604, OLD=0.07813, YOUNG=0.03166
A =
[[0.99623102 0.00131473 0.00245426]
 [0.00930508 0.98529273 0.00540219]
 [0.00580698 0.00171576 0.99247726]]
pi = [0.60406246 0.074813   0.32112455]
Iter 12: LL=-1287421.69 | Rates: N=0.90305, AF=0.09602, OLD=0.08013, YOUNG=0.03181
A =
[[0.99623087 0.00126814 0.002501  ]
 [0.00944029 0.98463452 0.00592519]
 [0.00582017 0.00176776 0.99241207]]
pi = [0.60404477 0.07231134 0.3236439 ]
Iter 13: LL=-1287410.89 | Rates: N=0.90305, AF=0.09601, OLD=0.08220, YOUNG=0.03195
A =
[[0.99623071 0.00122308 0.00254622]
 [0.00957628 0.98394743 0.00647629]
 [0.00583362 0.00181835 0.99234802]]
pi = [0.60402656 0.07001347 0.32595997]
Iter 14: LL=-1287400.44 | Rates: N=0.90305, AF=0.09599, OLD=0.08432, YOUNG=0.03209
A =
[[0.99623053 0.00117973 0.00258974]
 [0.00971424 0.98323057 0.00705519]
 [0.00584691 0.00186735 0.99228574]]
pi = [0.60400828 0.06790434 0.32808739]
Iter 15: LL=-1287390.35 | Rates: N=0.90305, AF=0.09598, OLD=0.08650, YOUNG=0.03223
A =
[[0.99623032 0.00113821 0.00263147]
 [0.00985512 0.98248341 0.00766147]
 [0.00585973 0.0019146  0.99222566]]
pi = [0.60399023 0.06597032 0.33003945]
Final Global Rates (lambdas): [0.90305024 0.09597736 0.08650239 0.03223072]
Final transition matrix A:
[[0.99623032 0.00113821 0.00263147]
 [0.00985512 0.98248341 0.00766147]
 [0.00585973 0.0019146  0.99222566]]
Final initial distribution pi:
[0.60399023 0.06597032 0.33003945]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3759  0.1994  0.2606   13339675.0   22148325.0  53563842.0
Archaic_young     0.8315  0.9188  0.8730  273461776.0   55429224.0  24156498.0
Modern            0.0000  0.0000  0.0000          0.0  635621000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         630525          223           2253
Archaic_old      1838        13336          52211
Archaic_young    3258        21929         274427

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3624  0.4418  0.3982
Archaic_young     0.8706  0.8337  0.8517

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         625608          849           2206
Archaic_old      1511        28287          34603
Archaic_young    3178        48755         255003

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 10
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1556881.48 | Rates: N=0.89908, AF=0.09669, OLD=0.06135, YOUNG=0.03394
A =
[[0.99587678 0.00165262 0.0024706 ]
 [0.00835384 0.98923114 0.00241501]
 [0.00654256 0.00126114 0.9921963 ]]
pi = [0.84017454 0.0535895  0.10623596]
Iter 2: LL=-1288817.11 | Rates: N=0.89933, AF=0.09659, OLD=0.06433, YOUNG=0.03259
A =
[[0.99589252 0.00163434 0.00247315]
 [0.00869059 0.98872295 0.00258645]
 [0.00636622 0.00123942 0.99239435]]
pi = [0.84932682 0.04868765 0.10198553]
Iter 3: LL=-1288788.63 | Rates: N=0.89934, AF=0.09656, OLD=0.06675, YOUNG=0.03207
A =
[[0.99589176 0.00162635 0.0024819 ]
 [0.00893644 0.988273   0.00279055]
 [0.00629246 0.00126178 0.99244575]]
pi = [0.84962464 0.04716094 0.10321443]
Iter 4: LL=-1288775.15 | Rates: N=0.89934, AF=0.09653, OLD=0.06861, YOUNG=0.03190
A =
[[0.99589054 0.0016092  0.00250026]
 [0.00914525 0.9878036  0.00305115]
 [0.0062464  0.00129927 0.99245433]]
pi = [0.84962094 0.04542844 0.10495062]
Iter 5: LL=-1288766.00 | Rates: N=0.89934, AF=0.09650, OLD=0.07019, YOUNG=0.03188
A =
[[0.9958896  0.00158515 0.00252525]
 [0.0093265  0.98731773 0.00335576]
 [0.00621922 0.00134467 0.99243611]]
pi = [0.84960839 0.04335987 0.10703174]
Iter 6: LL=-1288757.91 | Rates: N=0.89934, AF=0.09648, OLD=0.07167, YOUNG=0.03194
A =
[[0.99588889 0.00155642 0.00255468]
 [0.00948803 0.98681563 0.00369634]
 [0.00620514 0.00139402 0.99240084]]
pi = [0.84959643 0.04100073 0.10940285]
Iter 7: LL=-1288749.97 | Rates: N=0.89934, AF=0.09647, OLD=0.07313, YOUNG=0.03203
A =
[[0.99588835 0.00152453 0.00258712]
 [0.00963617 0.98629503 0.0040688 ]
 [0.00620006 0.00144516 0.99235478]]
pi = [0.84958501 0.03841016 0.11200483]
Iter 8: LL=-1288741.98 | Rates: N=0.89935, AF=0.09645, OLD=0.07462, YOUNG=0.03214
A =
[[0.99588791 0.00149046 0.00262163]
 [0.00977575 0.98575294 0.00447131]
 [0.00620118 0.00149685 0.99230197]]
pi = [0.84957389 0.03563739 0.11478872]
Iter 9: LL=-1288733.88 | Rates: N=0.89935, AF=0.09644, OLD=0.07616, YOUNG=0.03225
A =
[[0.99588755 0.00145488 0.00265757]
 [0.00991029 0.98518662 0.00490309]
 [0.00620658 0.0015483  0.99224512]]
pi = [0.84956291 0.03272221 0.11771488]
Iter 10: LL=-1288725.69 | Rates: N=0.89935, AF=0.09642, OLD=0.07777, YOUNG=0.03236
A =
[[0.99588725 0.00141825 0.0026945 ]
 [0.01004228 0.98459401 0.00536371]
 [0.00621494 0.00159899 0.99218607]]
pi = [0.84955205 0.02970139 0.12074656]
Iter 11: LL=-1288717.43 | Rates: N=0.89935, AF=0.09641, OLD=0.07945, YOUNG=0.03248
A =
[[0.995887   0.00138095 0.00273205]
 [0.0101735  0.98397366 0.00585285]
 [0.00622533 0.00164854 0.99212613]]
pi = [0.84954145 0.02661455 0.123844  ]
Iter 12: LL=-1288709.15 | Rates: N=0.89935, AF=0.09639, OLD=0.08121, YOUNG=0.03259
A =
[[0.99588679 0.00134327 0.00276994]
 [0.01030525 0.9833246  0.00637016]
 [0.00623707 0.00169664 0.99206629]]
pi = [0.84953133 0.02350764 0.12696103]
Iter 13: LL=-1288700.87 | Rates: N=0.89935, AF=0.09638, OLD=0.08303, YOUNG=0.03271
A =
[[0.99588661 0.00130544 0.00280795]
 [0.01043859 0.98264608 0.00691533]
 [0.00624966 0.00174305 0.99200729]]
pi = [0.84952201 0.02043362 0.13004438]
Iter 14: LL=-1288692.63 | Rates: N=0.89935, AF=0.09637, OLD=0.08494, YOUNG=0.03283
A =
[[0.99588646 0.00126768 0.00284586]
 [0.01057452 0.98193733 0.00748816]
 [0.0062627  0.00178758 0.99194972]]
pi = [0.84951382 0.01745078 0.13303541]
Iter 15: LL=-1288684.45 | Rates: N=0.89935, AF=0.09635, OLD=0.08692, YOUNG=0.03295
A =
[[0.99588634 0.00123014 0.00288352]
 [0.01071402 0.98119736 0.00808862]
 [0.00627589 0.00183006 0.99189405]]
pi = [0.84950708 0.01461923 0.1358737 ]
Final Global Rates (lambdas): [0.89934856 0.09635418 0.0869244  0.03295462]
Final transition matrix A:
[[0.99588634 0.00123014 0.00288352]
 [0.01071402 0.98119736 0.00808862]
 [0.00627589 0.00183006 0.99189405]]
Final initial distribution pi:
[0.84950708 0.01461923 0.1358737 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5043  0.2552  0.3389   16306721.0   16029279.0  47581715.0
Archaic_young     0.8520  0.9407  0.8941  286653804.0   49812196.0  18077349.0
Modern            0.0000  0.0000  0.0000          0.0  631198000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         625936          228           2499
Archaic_old      1871        16308          46222
Archaic_young    3391        15800         287745

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.3, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3777  0.3485  0.3625
Archaic_young     0.8500  0.8617  0.8558

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         599093          207           2475
Archaic_old      2601        25342          45372
Archaic_young    4315        41585         279010

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1548902.23 | Rates: N=0.88833, AF=0.09697, OLD=0.06888, YOUNG=0.03671
A =
[[0.99519898 0.00176714 0.00303388]
 [0.008913   0.98815234 0.00293466]
 [0.00686028 0.0013127  0.99182702]]
pi = [0.6519044  0.12378847 0.22430713]
Iter 2: LL=-1290192.75 | Rates: N=0.88860, AF=0.09688, OLD=0.07500, YOUNG=0.03434
A =
[[0.99522893 0.00173801 0.00303306]
 [0.00929053 0.98757604 0.00313343]
 [0.00667339 0.00127649 0.99205011]]
pi = [0.65311407 0.13694673 0.2099392 ]
Iter 3: LL=-1290106.41 | Rates: N=0.88860, AF=0.09682, OLD=0.07959, YOUNG=0.03349
A =
[[0.99522924 0.0017147  0.00305606]
 [0.00959921 0.98696015 0.00344064]
 [0.00660204 0.00130174 0.99209622]]
pi = [0.65310721 0.14783724 0.19905555]
Iter 4: LL=-1290072.05 | Rates: N=0.88860, AF=0.09677, OLD=0.08300, YOUNG=0.03329
A =
[[0.99522811 0.00167511 0.00309678]
 [0.00987395 0.98626403 0.00386202]
 [0.00656384 0.00135063 0.99208553]]
pi = [0.65308149 0.1536542  0.19326431]
Iter 5: LL=-1290050.99 | Rates: N=0.88860, AF=0.09674, OLD=0.08590, YOUNG=0.03335
A =
[[0.99522727 0.0016259  0.00314683]
 [0.01011064 0.98553112 0.00435823]
 [0.00654848 0.00141002 0.9920415 ]]
pi = [0.65306525 0.15543139 0.19150336]
Iter 6: LL=-1290033.04 | Rates: N=0.88860, AF=0.09671, OLD=0.08863, YOUNG=0.03350
A =
[[0.99522677 0.00157189 0.00320134]
 [0.01031425 0.98477787 0.00490788]
 [0.00654826 0.0014731  0.99197863]]
pi = [0.65305761 0.15440543 0.19253696]
Iter 7: LL=-1290016.19 | Rates: N=0.88860, AF=0.09668, OLD=0.09135, YOUNG=0.03367
A =
[[0.9952265  0.0015159  0.00325761]
 [0.01049239 0.98400666 0.00550095]
 [0.00655763 0.00153651 0.99190586]]
pi = [0.65305656 0.15155654 0.19538691]
Iter 8: LL=-1290000.05 | Rates: N=0.88860, AF=0.09665, OLD=0.09411, YOUNG=0.03385
A =
[[0.99522635 0.00145952 0.00331413]
 [0.01065254 0.98321481 0.00613266]
 [0.00657277 0.00159843 0.99182879]]
pi = [0.65305986 0.14761828 0.19932186]
Iter 9: LL=-1289984.51 | Rates: N=0.88860, AF=0.09663, OLD=0.09694, YOUNG=0.03403
A =
[[0.99522624 0.00140373 0.00337003]
 [0.01080118 0.98239853 0.00680028]
 [0.00659111 0.00165785 0.99175104]]
pi = [0.65306551 0.14314541 0.20378907]
Iter 10: LL=-1289969.58 | Rates: N=0.88860, AF=0.09660, OLD=0.09986, YOUNG=0.03421
A =
[[0.99522612 0.00134912 0.00342477]
 [0.01094377 0.98155444 0.00750179]
 [0.00661091 0.00171413 0.99167496]]
pi = [0.65307188 0.13855739 0.20837073]
Iter 11: LL=-1289955.24 | Rates: N=0.88860, AF=0.09657, OLD=0.10287, YOUNG=0.03439
A =
[[0.99522595 0.00129606 0.00347799]
 [0.01108483 0.98067976 0.00823542]
 [0.00663095 0.00176692 0.99160213]]
pi = [0.65307778 0.13415791 0.21276431]
Iter 12: LL=-1289941.49 | Rates: N=0.88860, AF=0.09655, OLD=0.10597, YOUNG=0.03457
A =
[[0.99522571 0.00124481 0.00352949]
 [0.01122829 0.97977207 0.00899965]
 [0.0066504  0.001816   0.9915336 ]]
pi = [0.65308245 0.13014608 0.21677147]
Iter 13: LL=-1289928.31 | Rates: N=0.88860, AF=0.09652, OLD=0.10917, YOUNG=0.03474
A =
[[0.99522539 0.0011955  0.00357911]
 [0.01137767 0.97882895 0.00979338]
 [0.00666869 0.00186128 0.99147003]]
pi = [0.65308548 0.12663018 0.22028434]
Iter 14: LL=-1289915.66 | Rates: N=0.88860, AF=0.09649, OLD=0.11249, YOUNG=0.03492
A =
[[0.995225   0.00114824 0.00362677]
 [0.01153625 0.97784769 0.01061606]
 [0.00668546 0.00190271 0.99141182]]
pi = [0.65308665 0.12364627 0.22326707]
Iter 15: LL=-1289903.49 | Rates: N=0.88859, AF=0.09646, OLD=0.11593, YOUNG=0.03510
A =
[[0.99522451 0.00110306 0.00367244]
 [0.01170717 0.976825   0.01146783]
 [0.00670049 0.00194033 0.99135919]]
pi = [0.65308594 0.12117845 0.22573561]
Final Global Rates (lambdas): [0.88859439 0.09646223 0.11592517 0.03510119]
Final transition matrix A:
[[0.99522451 0.00110306 0.00367244]
 [0.01170717 0.976825   0.01146783]
 [0.00670049 0.00194033 0.99135919]]
Final initial distribution pi:
[0.65308594 0.12117845 0.22573561]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.3_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5080  0.1784  0.2641   12979697.0   12573303.0  59770007.0
Archaic_young     0.8318  0.9547  0.8891  307819719.0   62224281.0  14596086.0
Modern            0.0000  0.0000  0.0000          0.0  604403000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         598592          390           2793
Archaic_old      2193        12998          58124
Archaic_young    3618        12165         309127

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0542  0.0044  0.0082
Archaic_young     0.8477  0.9811  0.9096

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         535867           13           2632
Archaic_old       619          289          65405
Archaic_young    3384         5083         386708

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1505174.21 | Rates: N=0.86211, AF=0.09841, OLD=0.04925, YOUNG=0.03753
A =
[[9.95634497e-01 9.04715887e-04 3.46078760e-03]
 [5.06010272e-03 9.91889975e-01 3.04992262e-03]
 [5.29375456e-03 8.27939060e-04 9.93878306e-01]]
pi = [0.46185627 0.11869374 0.41944999]
Iter 2: LL=-1267618.62 | Rates: N=0.86229, AF=0.09809, OLD=0.05525, YOUNG=0.03581
A =
[[9.95634693e-01 9.38448451e-04 3.42685888e-03]
 [5.03212133e-03 9.91986555e-01 2.98132380e-03]
 [5.28336492e-03 8.39037880e-04 9.93877597e-01]]
pi = [0.45775094 0.09518191 0.44706716]
Iter 3: LL=-1267514.78 | Rates: N=0.86230, AF=0.09803, OLD=0.06131, YOUNG=0.03408
A =
[[9.95638390e-01 9.75549945e-04 3.38605988e-03]
 [5.13484908e-03 9.91843534e-01 3.02161678e-03]
 [5.24705992e-03 8.54416782e-04 9.93898523e-01]]
pi = [0.45763234 0.06597897 0.47638869]
Iter 4: LL=-1267428.57 | Rates: N=0.86230, AF=0.09799, OLD=0.06622, YOUNG=0.03297
A =
[[9.95640476e-01 1.00233564e-03 3.35718835e-03]
 [5.36998762e-03 9.91373632e-01 3.25638030e-03]
 [5.17612723e-03 8.82239073e-04 9.93941634e-01]]
pi = [0.4576965  0.04131417 0.50098933]
Iter 5: LL=-1267381.05 | Rates: N=0.86230, AF=0.09796, OLD=0.07001, YOUNG=0.03245
A =
[[9.95641267e-01 1.01419928e-03 3.34453338e-03]
 [5.65358816e-03 9.90686895e-01 3.65951722e-03]
 [5.10179759e-03 9.25928940e-04 9.93972273e-01]]
pi = [0.45773239 0.0248385  0.51742912]
Iter 6: LL=-1267353.36 | Rates: N=0.86230, AF=0.09793, OLD=0.07311, YOUNG=0.03225
A =
[[9.95641543e-01 1.01237413e-03 3.34608303e-03]
 [5.92163229e-03 9.89900077e-01 4.17829084e-03]
 [5.04242113e-03 9.80872032e-04 9.93976707e-01]]
pi = [0.45774198 0.01480036 0.52745767]
Iter 7: LL=-1267332.92 | Rates: N=0.86230, AF=0.09791, OLD=0.07583, YOUNG=0.03219
A =
[[0.99564169 0.00100007 0.00335825]
 [0.00614889 0.98907697 0.00477414]
 [0.0050011  0.00104201 0.99395689]]
pi = [0.45774607 0.0088216  0.53343233]
Iter 8: LL=-1267315.62 | Rates: N=0.86230, AF=0.09789, OLD=0.07837, YOUNG=0.03220
A =
[[9.95641844e-01 9.80499814e-04 3.37765610e-03]
 [6.33243687e-03 9.88243144e-01 5.42441890e-03]
 [4.97477964e-03 1.10602888e-03 9.93919191e-01]]
pi = [0.4577576  0.00526541 0.53697699]
Iter 9: LL=-1267300.20 | Rates: N=0.86230, AF=0.09788, OLD=0.08080, YOUNG=0.03224
A =
[[9.95642062e-01 9.56280662e-04 3.40165693e-03]
 [6.47831818e-03 9.87405217e-01 6.11646445e-03]
 [4.95934576e-03 1.17083637e-03 9.93869818e-01]]
pi = [0.45777993 0.00314568 0.53907439]
Iter 10: LL=-1267286.18 | Rates: N=0.86230, AF=0.09786, OLD=0.08318, YOUNG=0.03228
A =
[[9.95642341e-01 9.29344517e-04 3.42831459e-03]
 [6.59472106e-03 9.86562337e-01 6.84294234e-03]
 [4.95132524e-03 1.23505467e-03 9.93813620e-01]]
pi = [0.45781159 0.00188075 0.54030766]
Iter 11: LL=-1267273.31 | Rates: N=0.86230, AF=0.09785, OLD=0.08553, YOUNG=0.03233
A =
[[9.95642664e-01 9.01084543e-04 3.45625184e-03]
 [6.68924668e-03 9.85711589e-01 7.59916434e-03]
 [4.94816428e-03 1.29770945e-03 9.93754126e-01]]
pi = [0.45784967 0.00112591 0.54102442]
Iter 12: LL=-1267261.46 | Rates: N=0.86230, AF=0.09783, OLD=0.08786, YOUNG=0.03239
A =
[[9.95643012e-01 8.72483669e-04 3.48450443e-03]
 [6.76809675e-03 9.84850141e-01 8.38176199e-03]
 [4.94809209e-03 1.35809206e-03 9.93693816e-01]]
pi = [0.45789129 0.00067558 0.54143313]
Iter 13: LL=-1267250.54 | Rates: N=0.86230, AF=0.09782, OLD=0.09018, YOUNG=0.03244
A =
[[9.95643370e-01 8.44222901e-04 3.51240727e-03]
 [6.83602506e-03 9.83975922e-01 9.18805259e-03]
 [4.94991816e-03 1.41568337e-03 9.93634398e-01]]
pi = [4.57934083e-01 4.06833372e-04 5.41659084e-01]
Iter 14: LL=-1267240.47 | Rates: N=0.86230, AF=0.09781, OLD=0.09250, YOUNG=0.03250
A =
[[9.95643726e-01 8.16763028e-04 3.53951134e-03]
 [6.89654372e-03 9.83087714e-01 1.00157418e-02]
 [4.95285916e-03 1.47010793e-03 9.93577033e-01]]
pi = [4.57976264e-01 2.46232975e-04 5.41777503e-01]
Iter 15: LL=-1267231.19 | Rates: N=0.86230, AF=0.09780, OLD=0.09482, YOUNG=0.03256
A =
[[9.95644071e-01 7.90405209e-04 3.56552362e-03]
 [6.95218327e-03 9.82185036e-01 1.08627809e-02]
 [4.95640966e-03 1.52110426e-03 9.93522486e-01]]
pi = [4.58016569e-01 1.49994699e-04 5.41833437e-01]
Final Global Rates (lambdas): [0.86229516 0.09780051 0.09481746 0.03256291]
Final transition matrix A:
[[9.95644071e-01 7.90405209e-04 3.56552362e-03]
 [6.95218327e-03 9.82185036e-01 1.08627809e-02]
 [4.95640966e-03 1.52110426e-03 9.93522486e-01]]
Final initial distribution pi:
[4.58016569e-01 1.49994699e-04 5.41833437e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1747  0.0505  0.0784    3341419.0   15786581.0  62799547.0
Archaic_young     0.8503  0.9540  0.8992  374839072.0   65999928.0  18073304.0
Modern            0.0000  0.0000  0.0000          0.0  540033000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         535920           69           2523
Archaic_old       658         3336          62319
Archaic_young    3455        15723         375997

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3371  0.0036  0.0070
Archaic_young     0.8747  0.9933  0.9302

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         536134            3           2891
Archaic_old       712          192          53251
Archaic_young    3446          374         402997

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1501087.04 | Rates: N=0.85988, AF=0.09720, OLD=0.04833, YOUNG=0.03809
A =
[[9.95263351e-01 8.64123533e-04 3.87252596e-03]
 [5.89615878e-03 9.90072599e-01 4.03124239e-03]
 [5.64489801e-03 8.50504356e-04 9.93504598e-01]]
pi = [0.54940596 0.11806331 0.33253073]
Iter 2: LL=-1266925.19 | Rates: N=0.86008, AF=0.09702, OLD=0.05412, YOUNG=0.03651
A =
[[9.95270720e-01 8.89455428e-04 3.83982437e-03]
 [5.77439960e-03 9.90312908e-01 3.91269283e-03]
 [5.64413904e-03 8.54419132e-04 9.93501442e-01]]
pi = [0.54972296 0.14756886 0.30270818]
Iter 3: LL=-1266835.30 | Rates: N=0.86008, AF=0.09699, OLD=0.06070, YOUNG=0.03481
A =
[[9.95272980e-01 9.29665573e-04 3.79735417e-03]
 [5.69369305e-03 9.90509142e-01 3.79716494e-03]
 [5.65747985e-03 8.59925559e-04 9.93482595e-01]]
pi = [0.54907782 0.18643256 0.26448962]
Iter 4: LL=-1266746.48 | Rates: N=0.86009, AF=0.09695, OLD=0.06595, YOUNG=0.03356
A =
[[9.95274564e-01 9.63101676e-04 3.76233396e-03]
 [5.76452249e-03 9.90380283e-01 3.85519447e-03]
 [5.63687055e-03 8.63539363e-04 9.93499590e-01]]
pi = [0.54862148 0.21392923 0.23744929]
Iter 5: LL=-1266699.83 | Rates: N=0.86009, AF=0.09691, OLD=0.06966, YOUNG=0.03293
A =
[[9.95275036e-01 9.81823104e-04 3.74314079e-03]
 [5.93630917e-03 9.89969087e-01 4.09460414e-03]
 [5.59596288e-03 8.73632483e-04 9.93530405e-01]]
pi = [0.54851165 0.22501095 0.2264774 ]
Iter 6: LL=-1266679.60 | Rates: N=0.86009, AF=0.09689, OLD=0.07238, YOUNG=0.03270
A =
[[9.95274826e-01 9.87352564e-04 3.73782138e-03]
 [6.13395362e-03 9.89411021e-01 4.45502498e-03]
 [5.55482742e-03 8.92043171e-04 9.93553129e-01]]
pi = [0.54849351 0.22627688 0.22522961]
Iter 7: LL=-1266668.06 | Rates: N=0.86009, AF=0.09686, OLD=0.07461, YOUNG=0.03265
A =
[[9.95274444e-01 9.83101889e-04 3.74245371e-03]
 [6.31953078e-03 9.88790570e-01 4.88989876e-03]
 [5.52156923e-03 9.16691710e-04 9.93561739e-01]]
pi = [0.54845848 0.22349869 0.22804283]
Iter 8: LL=-1266659.00 | Rates: N=0.86009, AF=0.09684, OLD=0.07664, YOUNG=0.03268
A =
[[9.95274079e-01 9.71986266e-04 3.75393463e-03]
 [6.48196525e-03 9.88142517e-01 5.37551779e-03]
 [5.49706525e-03 9.45465021e-04 9.93557470e-01]]
pi = [0.54840723 0.21959344 0.23199934]
Iter 9: LL=-1266650.74 | Rates: N=0.86009, AF=0.09683, OLD=0.07861, YOUNG=0.03273
A =
[[9.95273774e-01 9.56121120e-04 3.77010510e-03]
 [6.62209736e-03 9.87475701e-01 5.90220149e-03]
 [5.47976812e-03 9.76908438e-04 9.93543323e-01]]
pi = [0.54835376 0.21571567 0.23593058]
Iter 10: LL=-1266642.77 | Rates: N=0.86009, AF=0.09681, OLD=0.08059, YOUNG=0.03280
A =
[[9.95273526e-01 9.36986648e-04 3.78948745e-03]
 [6.74492165e-03 9.86787693e-01 6.46738561e-03]
 [5.46775802e-03 1.01003114e-03 9.93522211e-01]]
pi = [0.54830436 0.21220406 0.23949158]
Iter 11: LL=-1266634.87 | Rates: N=0.86009, AF=0.09679, OLD=0.08265, YOUNG=0.03287
A =
[[9.95273318e-01 9.15624720e-04 3.81105758e-03]
 [6.85633614e-03 9.86071658e-01 7.07200628e-03]
 [5.45938148e-03 1.04411300e-03 9.93496506e-01]]
pi = [0.54826006 0.20907842 0.24266152]
Iter 12: LL=-1266626.94 | Rates: N=0.86009, AF=0.09677, OLD=0.08480, YOUNG=0.03295
A =
[[9.95273126e-01 8.92779471e-04 3.83409478e-03]
 [6.96199673e-03 9.85319147e-01 7.71885663e-03]
 [5.45336473e-03 1.07859815e-03 9.93468037e-01]]
pi = [0.54821994 0.20625961 0.24552045]
Iter 13: LL=-1266618.88 | Rates: N=0.86009, AF=0.09675, OLD=0.08708, YOUNG=0.03302
A =
[[9.95272925e-01 8.68987634e-04 3.85808775e-03]
 [7.06705339e-03 9.84521042e-01 8.41190504e-03]
 [5.44876854e-03 1.11303905e-03 9.93438192e-01]]
pi = [0.54818267 0.20365549 0.24816184]
Iter 14: LL=-1266610.63 | Rates: N=0.86009, AF=0.09673, OLD=0.08952, YOUNG=0.03310
A =
[[9.95272690e-01 8.44637104e-04 3.88267288e-03]
 [7.17620446e-03 9.83667766e-01 9.15602993e-03]
 [5.44491213e-03 1.14706456e-03 9.93408023e-01]]
pi = [0.54814696 0.20118925 0.25066379]
Iter 15: LL=-1266602.13 | Rates: N=0.86010, AF=0.09670, OLD=0.09213, YOUNG=0.03318
A =
[[9.95272403e-01 8.20006415e-04 3.90759018e-03]
 [7.29381955e-03 9.82749278e-01 9.95690275e-03]
 [5.44130478e-03 1.18035973e-03 9.93378335e-01]]
pi = [0.54811166 0.19880523 0.25308311]
Final Global Rates (lambdas): [0.86009586 0.09670346 0.0921338  0.03317594]
Final transition matrix A:
[[9.95272403e-01 8.20006415e-04 3.90759018e-03]
 [7.29381955e-03 9.82749278e-01 9.95690275e-03]
 [5.44130478e-03 1.18035973e-03 9.93378335e-01]]
Final initial distribution pi:
[0.54811166 0.19880523 0.25308311]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1125  0.0352  0.0536    1899158.0   14979842.0  52121070.0
Archaic_young     0.8744  0.9572  0.9139  386990412.0   55607588.0  17316348.0
Modern            0.0000  0.0000  0.0000          0.0  540523000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         536241           52           2735
Archaic_old       722         1898          51535
Archaic_young    3560        14929         388328

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0000  0.0000  0.0000
Archaic_young     0.8657  0.9937  0.9253

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         518373            0           3216
Archaic_old       792            0          59299
Archaic_young    3817            0         414503

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1496002.24 | Rates: N=0.85101, AF=0.09753, OLD=0.05140, YOUNG=0.04120
A =
[[9.94659663e-01 9.18815979e-04 4.42152106e-03]
 [6.37281187e-03 9.88789383e-01 4.83780530e-03]
 [5.91319827e-03 9.27904483e-04 9.93158897e-01]]
pi = [0.50159626 0.10415933 0.39424441]
Iter 2: LL=-1269369.79 | Rates: N=0.85121, AF=0.09746, OLD=0.05825, YOUNG=0.03937
A =
[[9.94688757e-01 9.44746586e-04 4.36649653e-03]
 [6.25709412e-03 9.89059479e-01 4.68342645e-03]
 [5.88143417e-03 9.38698942e-04 9.93179867e-01]]
pi = [0.50153006 0.09602412 0.40244581]
Iter 3: LL=-1269247.01 | Rates: N=0.85121, AF=0.09743, OLD=0.06704, YOUNG=0.03723
A =
[[9.94693714e-01 9.99320531e-04 4.30696554e-03]
 [6.16224506e-03 9.89367752e-01 4.47000275e-03]
 [5.88933023e-03 9.63371113e-04 9.93147299e-01]]
pi = [0.50157887 0.08544116 0.41297997]
Iter 4: LL=-1269103.68 | Rates: N=0.85121, AF=0.09738, OLD=0.07415, YOUNG=0.03560
A =
[[9.94697370e-01 1.04579783e-03 4.25683193e-03]
 [6.28554474e-03 9.89201606e-01 4.51284913e-03]
 [5.85431878e-03 9.84204678e-04 9.93161477e-01]]
pi = [0.50169651 0.07322502 0.42507847]
Iter 5: LL=-1269028.39 | Rates: N=0.85121, AF=0.09733, OLD=0.07909, YOUNG=0.03484
A =
[[0.9946987  0.00107133 0.00422997]
 [0.00656914 0.98859196 0.0048389 ]
 [0.00579295 0.00100752 0.99319952]]
pi = [0.50190281 0.0611753  0.43692189]
Iter 6: LL=-1268997.06 | Rates: N=0.85121, AF=0.09730, OLD=0.08275, YOUNG=0.03461
A =
[[0.99469871 0.00107869 0.0042226 ]
 [0.00689336 0.98776607 0.00534057]
 [0.0057343  0.0010366  0.9932291 ]]
pi = [0.50213519 0.04994298 0.44792183]
Iter 7: LL=-1268978.83 | Rates: N=0.85121, AF=0.09727, OLD=0.08583, YOUNG=0.03460
A =
[[0.99469835 0.00107268 0.00422898]
 [0.00720062 0.98685734 0.00594204]
 [0.00568869 0.00106961 0.9932417 ]]
pi = [0.50236386 0.03985128 0.45778487]
Iter 8: LL=-1268964.34 | Rates: N=0.85121, AF=0.09725, OLD=0.08868, YOUNG=0.03468
A =
[[0.99469796 0.0010573  0.00424474]
 [0.0074751  0.98591854 0.00660636]
 [0.00565616 0.00110462 0.99323922]]
pi = [0.50258353 0.03119139 0.46622508]
Iter 9: LL=-1268951.40 | Rates: N=0.85121, AF=0.09723, OLD=0.09147, YOUNG=0.03478
A =
[[0.99469764 0.00103553 0.00426683]
 [0.00771829 0.98496427 0.00731744]
 [0.00563389 0.00114029 0.99322582]]
pi = [0.50278916 0.02408884 0.47312201]
Iter 10: LL=-1268939.38 | Rates: N=0.85121, AF=0.09722, OLD=0.09427, YOUNG=0.03489
A =
[[0.99469742 0.00100951 0.00429307]
 [0.00793699 0.98399464 0.00806837]
 [0.00561901 0.00117565 0.99320534]]
pi = [0.50297355 0.01847286 0.47855359]
Iter 11: LL=-1268928.00 | Rates: N=0.85121, AF=0.09720, OLD=0.09713, YOUNG=0.03501
A =
[[9.94697280e-01 9.80831199e-04 4.32188920e-03]
 [8.13853044e-03 9.83005681e-01 8.85578832e-03]
 [5.60924279e-03 1.20995177e-03 9.93180805e-01]]
pi = [0.50313133 0.01414578 0.48272289]
Iter 12: LL=-1268917.14 | Rates: N=0.85121, AF=0.09718, OLD=0.10006, YOUNG=0.03512
A =
[[9.94697206e-01 9.50678943e-04 4.35211516e-03]
 [8.32909846e-03 9.81993527e-01 9.67737450e-03]
 [5.60294549e-03 1.24264813e-03 9.93154406e-01]]
pi = [0.50326079 0.01086515 0.48587405]
Iter 13: LL=-1268906.77 | Rates: N=0.85121, AF=0.09717, OLD=0.10307, YOUNG=0.03524
A =
[[9.94697174e-01 9.19944761e-04 4.38288099e-03]
 [8.51337420e-03 9.80955785e-01 1.05308409e-02]
 [5.59899634e-03 1.27333752e-03 9.93127666e-01]]
pi = [0.50336336 0.00839851 0.48823813]
Iter 14: LL=-1268896.85 | Rates: N=0.85121, AF=0.09715, OLD=0.10617, YOUNG=0.03535
A =
[[9.94697164e-01 8.89297895e-04 4.41353763e-03]
 [8.69467951e-03 9.79891753e-01 1.14135677e-02]
 [5.59663260e-03 1.30175840e-03 9.93101609e-01]]
pi = [0.50344232 0.00654837 0.49000932]
Iter 15: LL=-1268887.41 | Rates: N=0.85120, AF=0.09714, OLD=0.10935, YOUNG=0.03546
A =
[[9.94697158e-01 8.59236745e-04 4.44360525e-03]
 [8.87527056e-03 9.78802182e-01 1.23225473e-02]
 [5.59534009e-03 1.32776378e-03 9.93076896e-01]]
pi = [0.50350156 0.00515803 0.49134041]
Final Global Rates (lambdas): [0.85120424 0.09713681 0.10934968 0.03545662]
Final transition matrix A:
[[9.94697158e-01 8.59236745e-04 4.44360525e-03]
 [8.87527056e-03 9.78802182e-01 1.23225473e-02]
 [5.59534009e-03 1.32776378e-03 9.93076896e-01]]
Final initial distribution pi:
[0.50350156 0.00515803 0.49134041]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2209  0.0607  0.0953    3641168.0   12843832.0  56313682.0
Archaic_young     0.8695  0.9631  0.9139  400206386.0   60091614.0  15342242.0
Modern            0.0000  0.0000  0.0000          0.0  523217000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         518478          146           2965
Archaic_old       816         3638          55637
Archaic_young    3923        12701         401696

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0000  0.0000  0.0000
Archaic_young     0.8627  0.9911  0.9225

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         535507            0           3340
Archaic_old       870            0          58019
Archaic_young    4751          232         397281

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1521096.22 | Rates: N=0.86181, AF=0.09820, OLD=0.05854, YOUNG=0.04732
A =
[[9.94391488e-01 9.50308229e-04 4.65820419e-03]
 [7.22962806e-03 9.87276364e-01 5.49400753e-03]
 [6.68697824e-03 1.03213511e-03 9.92280887e-01]]
pi = [0.74366956 0.05473046 0.20159998]
Iter 2: LL=-1284722.34 | Rates: N=0.86203, AF=0.09817, OLD=0.06743, YOUNG=0.04505
A =
[[9.94440875e-01 9.86492019e-04 4.57263276e-03]
 [7.26832879e-03 9.87379905e-01 5.35176585e-03]
 [6.59309603e-03 1.03234782e-03 9.92374556e-01]]
pi = [0.75122683 0.05022954 0.19854363]
Iter 3: LL=-1284550.78 | Rates: N=0.86203, AF=0.09811, OLD=0.07977, YOUNG=0.04230
A =
[[0.99444801 0.00107559 0.0044764 ]
 [0.00740947 0.98747893 0.0051116 ]
 [0.00654256 0.00105091 0.99240653]]
pi = [0.75143148 0.04497595 0.20359257]
Iter 4: LL=-1284326.45 | Rates: N=0.86203, AF=0.09799, OLD=0.09030, YOUNG=0.04015
A =
[[0.9944522  0.00116498 0.00438281]
 [0.00785806 0.98692143 0.00522051]
 [0.0064345  0.00107837 0.99248713]]
pi = [0.75135278 0.03829126 0.21035595]
Iter 5: LL=-1284197.70 | Rates: N=0.86203, AF=0.09787, OLD=0.09789, YOUNG=0.03916
A =
[[0.99445272 0.00122403 0.00432324]
 [0.00848311 0.98576323 0.00575366]
 [0.00631314 0.00112676 0.9925601 ]]
pi = [0.75123133 0.03242664 0.21634203]
Iter 6: LL=-1284138.97 | Rates: N=0.86203, AF=0.09777, OLD=0.10368, YOUNG=0.03883
A =
[[0.9944512  0.00125297 0.00429583]
 [0.00909247 0.98434298 0.00656454]
 [0.00621921 0.00119426 0.99258653]]
pi = [0.75114488 0.0275093  0.22134582]
Iter 7: LL=-1284102.93 | Rates: N=0.86203, AF=0.09769, OLD=0.10859, YOUNG=0.03877
A =
[[0.9944494  0.00125966 0.00429094]
 [0.00961209 0.98284403 0.00754388]
 [0.00615768 0.00127264 0.99256968]]
pi = [0.75109419 0.02324636 0.22565945]
Iter 8: LL=-1284074.64 | Rates: N=0.86203, AF=0.09763, OLD=0.11310, YOUNG=0.03880
A =
[[0.99444794 0.00125159 0.00430047]
 [0.01003645 0.98132967 0.00863388]
 [0.00612118 0.00135603 0.99252279]]
pi = [0.75106598 0.01948924 0.22944478]
Iter 9: LL=-1284050.17 | Rates: N=0.86202, AF=0.09757, OLD=0.11745, YOUNG=0.03886
A =
[[0.9944469  0.0012342  0.00431889]
 [0.01038368 0.97981152 0.0098048 ]
 [0.00610153 0.00144081 0.99245766]]
pi = [0.7510514  0.01617163 0.23277697]
Iter 10: LL=-1284028.17 | Rates: N=0.86202, AF=0.09752, OLD=0.12175, YOUNG=0.03894
A =
[[0.9944462  0.0012112  0.0043426 ]
 [0.0106762  0.97828294 0.01104086]
 [0.00609247 0.00152459 0.99238294]]
pi = [0.75104531 0.01325365 0.23570104]
Iter 11: LL=-1284008.01 | Rates: N=0.86202, AF=0.09747, OLD=0.12608, YOUNG=0.03902
A =
[[0.99444572 0.001185   0.00436928]
 [0.01093397 0.97673278 0.01233326]
 [0.00608975 0.00160569 0.99230456]]
pi = [0.75104463 0.01070401 0.23825136]
Iter 12: LL=-1283989.30 | Rates: N=0.86202, AF=0.09743, OLD=0.13049, YOUNG=0.03910
A =
[[0.99444535 0.00115714 0.00439752]
 [0.01117283 0.97515047 0.0136767 ]
 [0.0060906  0.00168285 0.99222656]]
pi = [0.75104747 0.00849612 0.24045641]
Iter 13: LL=-1283971.78 | Rates: N=0.86201, AF=0.09738, OLD=0.13502, YOUNG=0.03920
A =
[[0.99444502 0.00112857 0.00442641]
 [0.01140476 0.97352755 0.01506769]
 [0.00609329 0.00175515 0.99215155]]
pi = [0.75105266 0.00660726 0.24234008]
Iter 14: LL=-1283955.29 | Rates: N=0.86201, AF=0.09733, OLD=0.13968, YOUNG=0.03929
A =
[[0.99444468 0.00109988 0.00445545]
 [0.01163853 0.97185813 0.01650334]
 [0.00609677 0.00182198 0.99208125]]
pi = [0.75105943 0.00501747 0.2439231 ]
Iter 15: LL=-1283939.68 | Rates: N=0.86201, AF=0.09729, OLD=0.14449, YOUNG=0.03940
A =
[[0.99444429 0.00107141 0.0044843 ]
 [0.01188041 0.97013892 0.01798067]
 [0.00610041 0.00188295 0.99201664]]
pi = [0.75106732 0.00370748 0.2452252 ]
Final Global Rates (lambdas): [0.86200667 0.09728822 0.14449364 0.03939975]
Final transition matrix A:
[[0.99444429 0.00107141 0.0044843 ]
 [0.01188041 0.97013892 0.01798067]
 [0.00610041 0.00188295 0.99201664]]
Final initial distribution pi:
[0.75106732 0.00370748 0.2452252 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1942  0.0573  0.0885    3362961.0   13958039.0  55345751.0
Archaic_young     0.8659  0.9575  0.9094  382276115.0   59226885.0  16966409.0
Modern            0.0000  0.0000  0.0000          0.0  541176000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         535496          289           3062
Archaic_old       883         3360          54646
Archaic_young    4797        13672         383795

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0000  0.0000  0.0000
Archaic_young     0.8536  0.9893  0.9165

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         536898            0           3584
Archaic_old      1225            0          61519
Archaic_young    5705            0         391069

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1531840.97 | Rates: N=0.86253, AF=0.09751, OLD=0.06570, YOUNG=0.05426
A =
[[9.94113588e-01 9.74859841e-04 4.91155209e-03]
 [7.51765323e-03 9.86415338e-01 6.06700853e-03]
 [7.13786906e-03 1.15444064e-03 9.91707690e-01]]
pi = [0.35442961 0.14294829 0.5026221 ]
Iter 2: LL=-1294449.85 | Rates: N=0.86276, AF=0.09747, OLD=0.07480, YOUNG=0.05184
A =
[[9.94194718e-01 9.89349586e-04 4.81593275e-03]
 [7.38128763e-03 9.86802880e-01 5.81583269e-03]
 [7.03142685e-03 1.17473456e-03 9.91793839e-01]]
pi = [0.34326019 0.1486995  0.5080403 ]
Iter 3: LL=-1294278.27 | Rates: N=0.86275, AF=0.09739, OLD=0.08792, YOUNG=0.04868
A =
[[0.994209   0.00105109 0.00473991]
 [0.00729872 0.98733812 0.00536315]
 [0.00701903 0.0012268  0.99175417]]
pi = [0.34266877 0.15371901 0.50361223]
Iter 4: LL=-1294032.80 | Rates: N=0.86275, AF=0.09725, OLD=0.09909, YOUNG=0.04603
A =
[[0.99421786 0.00111083 0.00467131]
 [0.00755037 0.98719526 0.00525436]
 [0.00694078 0.00128327 0.99177595]]
pi = [0.34269362 0.15433562 0.50297076]
Iter 5: LL=-1293890.86 | Rates: N=0.86274, AF=0.09711, OLD=0.10703, YOUNG=0.04477
A =
[[0.99421924 0.00114631 0.00463445]
 [0.00807587 0.98631462 0.00560951]
 [0.00682067 0.00135073 0.99182859]]
pi = [0.34271701 0.14828014 0.50900286]
Iter 6: LL=-1293830.00 | Rates: N=0.86274, AF=0.09700, OLD=0.11313, YOUNG=0.04437
A =
[[0.99421747 0.00115925 0.00462328]
 [0.0086733  0.98505899 0.00626771]
 [0.00670834 0.00143111 0.99186055]]
pi = [0.34269794 0.136901   0.52040106]
Iter 7: LL=-1293792.79 | Rates: N=0.86274, AF=0.09689, OLD=0.11852, YOUNG=0.04432
A =
[[0.99421541 0.00115503 0.00462956]
 [0.00924923 0.98363098 0.00711979]
 [0.00661999 0.00151794 0.99186207]]
pi = [0.3426778  0.12209331 0.53522889]
Iter 8: LL=-1293761.47 | Rates: N=0.86273, AF=0.09680, OLD=0.12380, YOUNG=0.04440
A =
[[0.99421385 0.00113869 0.00464746]
 [0.00978046 0.98209893 0.00812061]
 [0.00655495 0.00160647 0.99183858]]
pi = [0.34268877 0.10550581 0.55180542]
Iter 9: LL=-1293731.82 | Rates: N=0.86273, AF=0.09671, OLD=0.12925, YOUNG=0.04454
A =
[[0.99421285 0.00111408 0.00467307]
 [0.01027139 0.98047113 0.00925748]
 [0.00650837 0.00169396 0.99179767]]
pi = [0.34273987 0.08845699 0.56880314]
Iter 10: LL=-1293702.54 | Rates: N=0.86272, AF=0.09662, OLD=0.13503, YOUNG=0.04469
A =
[[0.99421221 0.0010841  0.0047037 ]
 [0.01073533 0.97873411 0.01053056]
 [0.00647551 0.00177865 0.99174584]]
pi = [0.3428255 0.0719858 0.5851887]
Iter 11: LL=-1293673.04 | Rates: N=0.86272, AF=0.09653, OLD=0.14128, YOUNG=0.04486
A =
[[0.99421167 0.00105094 0.00473739]
 [0.01118699 0.97686892 0.01194409]
 [0.00645251 0.00185932 0.99168817]]
pi = [0.34293383 0.05686517 0.600201  ]
Iter 12: LL=-1293642.93 | Rates: N=0.86271, AF=0.09644, OLD=0.14810, YOUNG=0.04504
A =
[[0.99421114 0.00101611 0.00477276]
 [0.01164011 0.97485432 0.01350557]
 [0.00643642 0.00193495 0.99162862]]
pi = [0.34305194 0.04358876 0.6133593 ]
Iter 13: LL=-1293611.94 | Rates: N=0.86270, AF=0.09635, OLD=0.15559, YOUNG=0.04523
A =
[[9.94210527e-01 9.80590189e-04 4.80888317e-03]
 [1.21073722e-02 9.72666155e-01 1.52264731e-02]
 [6.42520356e-03 2.00466751e-03 9.91570129e-01]]
pi = [0.34316861 0.0323927  0.62443869]
Iter 14: LL=-1293579.85 | Rates: N=0.86268, AF=0.09624, OLD=0.16391, YOUNG=0.04544
A =
[[9.94209592e-01 9.45338543e-04 4.84506935e-03]
 [1.26024669e-02 9.70276257e-01 1.71212765e-02]
 [6.41735813e-03 2.06786051e-03 9.91514781e-01]]
pi = [0.34327526 0.02330595 0.6334188 ]
Iter 15: LL=-1293545.97 | Rates: N=0.86266, AF=0.09611, OLD=0.17342, YOUNG=0.04565
A =
[[9.94207926e-01 9.11238576e-04 4.88083496e-03]
 [1.31464012e-02 9.67639913e-01 1.92136855e-02]
 [6.41151611e-03 2.12381931e-03 9.91464665e-01]]
pi = [0.34336615 0.01619533 0.64043852]
Final Global Rates (lambdas): [0.86266459 0.09611414 0.17342065 0.04565264]
Final transition matrix A:
[[9.94207926e-01 9.11238576e-04 4.88083496e-03]
 [1.31464012e-02 9.67639913e-01 1.92136855e-02]
 [6.41151611e-03 2.12381931e-03 9.91464665e-01]]
Final initial distribution pi:
[0.34336615 0.01619533 0.64043852]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2015  0.0498  0.0798    3113020.0   12339980.0  59449668.0
Archaic_young     0.8565  0.9596  0.9052  377668075.0   63251925.0  15898881.0
Modern            0.0000  0.0000  0.0000          0.0  543627000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         536887          379           3216
Archaic_old      1214         3109          58421
Archaic_young    5526        11965         379283

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1398  0.1065  0.1209
Archaic_young     0.8751  0.9061  0.8904

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         548571          205           2384
Archaic_old       727         5691          47247
Archaic_young    3155        34819         357201

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1509336.73 | Rates: N=0.86511, AF=0.09761, OLD=0.05315, YOUNG=0.03548
A =
[[0.99570778 0.00121017 0.00308205]
 [0.00539012 0.99208516 0.00252472]
 [0.00544745 0.00101252 0.99354003]]
pi = [0.29235294 0.19693017 0.51071689]
Iter 2: LL=-1269621.22 | Rates: N=0.86529, AF=0.09736, OLD=0.05702, YOUNG=0.03415
A =
[[0.99571271 0.00122753 0.00305976]
 [0.00561443 0.99179464 0.00259093]
 [0.00533338 0.00101227 0.99365435]]
pi = [0.2818201  0.19023002 0.52794988]
Iter 3: LL=-1269573.80 | Rates: N=0.86530, AF=0.09734, OLD=0.06036, YOUNG=0.03328
A =
[[0.9957138  0.0012394  0.00304679]
 [0.0059013  0.99136849 0.00273021]
 [0.0052296  0.00102464 0.99374575]]
pi = [0.28149922 0.18157305 0.53692773]
Iter 4: LL=-1269544.62 | Rates: N=0.86529, AF=0.09731, OLD=0.06302, YOUNG=0.03283
A =
[[0.99571426 0.00124048 0.00304525]
 [0.00619948 0.9908546  0.00294593]
 [0.00513593 0.00104988 0.99381419]]
pi = [0.28167834 0.17392524 0.54439643]
Iter 5: LL=-1269527.05 | Rates: N=0.86529, AF=0.09730, OLD=0.06519, YOUNG=0.03264
A =
[[0.99571439 0.00123129 0.00305432]
 [0.00648197 0.99029315 0.00322488]
 [0.00506077 0.00108504 0.99385419]]
pi = [0.28178679 0.16734122 0.55087199]
Iter 6: LL=-1269514.54 | Rates: N=0.86529, AF=0.09728, OLD=0.06706, YOUNG=0.03259
A =
[[0.99571437 0.00121399 0.00307164]
 [0.00673715 0.98970924 0.00355361]
 [0.00500462 0.00112651 0.99386887]]
pi = [0.28182081 0.16146153 0.55671766]
Iter 7: LL=-1269504.04 | Rates: N=0.86529, AF=0.09727, OLD=0.06879, YOUNG=0.03261
A =
[[0.99571434 0.00119088 0.00309477]
 [0.00696262 0.98911459 0.00392279]
 [0.00496467 0.00117162 0.99386371]]
pi = [0.28181425 0.15589084 0.56229491]
Iter 8: LL=-1269494.43 | Rates: N=0.86529, AF=0.09726, OLD=0.07045, YOUNG=0.03266
A =
[[0.99571435 0.00116391 0.00312173]
 [0.00716046 0.98851261 0.00432693]
 [0.00493743 0.00121869 0.99384388]]
pi = [0.2817907  0.1503066  0.56790271]
Iter 9: LL=-1269485.32 | Rates: N=0.86529, AF=0.09725, OLD=0.07209, YOUNG=0.03271
A =
[[0.99571442 0.00113455 0.00315103]
 [0.00733444 0.98790256 0.004763  ]
 [0.0049198  0.00126661 0.99381358]]
pi = [0.28176275 0.14448318 0.57375408]
Iter 10: LL=-1269476.54 | Rates: N=0.86529, AF=0.09724, OLD=0.07374, YOUNG=0.03277
A =
[[0.99571456 0.00110386 0.00318159]
 [0.00748859 0.98728212 0.00522929]
 [0.00490931 0.00131462 0.99377607]]
pi = [0.28173656 0.13828463 0.57997881]
Iter 11: LL=-1269468.03 | Rates: N=0.86529, AF=0.09723, OLD=0.07542, YOUNG=0.03283
A =
[[0.99571475 0.00107262 0.00321263]
 [0.00762659 0.9866487  0.00572471]
 [0.00490406 0.00136215 0.99373379]]
pi = [0.28171518 0.13164744 0.58663738]
Iter 12: LL=-1269459.76 | Rates: N=0.86529, AF=0.09722, OLD=0.07712, YOUNG=0.03289
A =
[[0.99571502 0.00104136 0.00324362]
 [0.00775158 0.98599994 0.00624848]
 [0.00490264 0.00140874 0.99368862]]
pi = [0.2817002  0.12456215 0.59373766]
Iter 13: LL=-1269451.74 | Rates: N=0.86529, AF=0.09721, OLD=0.07886, YOUNG=0.03295
A =
[[0.99571534 0.00101044 0.00327422]
 [0.00786623 0.98533384 0.00679993]
 [0.00490399 0.00145403 0.99364198]]
pi = [0.28169255 0.11705741 0.60125003]
Iter 14: LL=-1269443.93 | Rates: N=0.86529, AF=0.09720, OLD=0.08065, YOUNG=0.03301
A =
[[9.95715734e-01 9.80083033e-04 3.30418298e-03]
 [7.97280088e-03 9.84648645e-01 7.37855413e-03]
 [4.90732538e-03 1.49769104e-03 9.93594984e-01]]
pi = [0.28169275 0.10918789 0.60911936]
Iter 15: LL=-1269436.34 | Rates: N=0.86529, AF=0.09719, OLD=0.08249, YOUNG=0.03307
A =
[[9.95716173e-01 9.50419444e-04 3.33340791e-03]
 [8.07325459e-03 9.83942758e-01 7.98398771e-03]
 [4.91208836e-03 1.53944549e-03 9.93548466e-01]]
pi = [0.28170097 0.10102666 0.61727236]
Final Global Rates (lambdas): [0.86529108 0.09718574 0.08249437 0.03306527]
Final transition matrix A:
[[9.95716173e-01 9.50419444e-04 3.33340791e-03]
 [8.07325459e-03 9.83942758e-01 7.98398771e-03]
 [4.91208836e-03 1.53944549e-03 9.93548466e-01]]
Final initial distribution pi:
[0.28170097 0.10102666 0.61727236]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1621  0.0739  0.1015    3948534.0   20411466.0  49488396.0
Archaic_young     0.8758  0.9440  0.9086  370897803.0   52603197.0  22014573.0
Modern            0.0000  0.0000  0.0000          0.0  552139000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         548513          252           2395
Archaic_old       672         3954          49039
Archaic_young    2954        20154         372067

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1886  0.0684  0.1003
Archaic_young     0.8787  0.9547  0.9151

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         536719           74           2707
Archaic_old       797         3659          49227
Archaic_young    3833        15657         387327

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1505245.19 | Rates: N=0.86126, AF=0.09776, OLD=0.05591, YOUNG=0.03644
A =
[[9.95130283e-01 1.15624961e-03 3.71346723e-03]
 [6.38459640e-03 9.90186591e-01 3.42881254e-03]
 [5.72379167e-03 9.77368462e-04 9.93298840e-01]]
pi = [0.51897637 0.09640252 0.3846211 ]
Iter 2: LL=-1269651.02 | Rates: N=0.86146, AF=0.09759, OLD=0.06255, YOUNG=0.03428
A =
[[9.95143741e-01 1.18687034e-03 3.66938831e-03]
 [6.54643979e-03 9.90139386e-01 3.31417454e-03]
 [5.63846260e-03 9.76456264e-04 9.93385081e-01]]
pi = [0.52249407 0.06417965 0.41332628]
Iter 3: LL=-1269541.59 | Rates: N=0.86146, AF=0.09752, OLD=0.06787, YOUNG=0.03298
A =
[[9.95146724e-01 1.20965345e-03 3.64362279e-03]
 [6.83283228e-03 9.89852597e-01 3.31457030e-03]
 [5.55479616e-03 9.88080919e-04 9.93457123e-01]]
pi = [0.52326496 0.03699973 0.43973531]
Iter 4: LL=-1269490.46 | Rates: N=0.86147, AF=0.09747, OLD=0.07147, YOUNG=0.03243
A =
[[0.99514718 0.00121097 0.00364184]
 [0.00718107 0.98936358 0.00345535]
 [0.00547187 0.00100987 0.99351826]]
pi = [0.52362342 0.0188743  0.45750228]
Iter 5: LL=-1269470.15 | Rates: N=0.86147, AF=0.09744, OLD=0.07403, YOUNG=0.03229
A =
[[0.99514676 0.00119628 0.00365695]
 [0.00751589 0.9888022  0.00368191]
 [0.00540671 0.0010391  0.99355419]]
pi = [0.52376657 0.00880216 0.46743127]
Iter 6: LL=-1269459.17 | Rates: N=0.86147, AF=0.09741, OLD=0.07608, YOUNG=0.03231
A =
[[0.99514627 0.00117151 0.00368222]
 [0.00780866 0.9882342  0.00395714]
 [0.00536103 0.00107168 0.9935673 ]]
pi = [0.52380851 0.00385139 0.47234011]
Iter 7: LL=-1269450.96 | Rates: N=0.86147, AF=0.09740, OLD=0.07789, YOUNG=0.03240
A =
[[0.9951459  0.00114088 0.00371322]
 [0.00805667 0.98767948 0.00426385]
 [0.00533123 0.00110506 0.99356371]]
pi = [0.52382617 0.00161    0.47456383]
Iter 8: LL=-1269443.81 | Rates: N=0.86147, AF=0.09738, OLD=0.07962, YOUNG=0.03250
A =
[[0.99514568 0.00110708 0.00374724]
 [0.00826614 0.98713836 0.0045955 ]
 [0.00531321 0.00113795 0.99354884]]
pi = [0.52384808 0.00065062 0.47550129]
Iter 9: LL=-1269437.20 | Rates: N=0.86147, AF=0.09737, OLD=0.08133, YOUNG=0.03260
A =
[[0.9951456  0.0010718  0.0037826 ]
 [0.00844511 0.98660449 0.0049504 ]
 [0.00530361 0.00116968 0.9935267 ]]
pi = [5.23878916e-01 2.56090524e-04 4.75864994e-01]
Iter 10: LL=-1269430.87 | Rates: N=0.86147, AF=0.09735, OLD=0.08305, YOUNG=0.03271
A =
[[0.99514561 0.00103612 0.00381827]
 [0.00860088 0.98607027 0.00532886]
 [0.00530001 0.00119988 0.99350011]]
pi = [5.23916137e-01 9.86605295e-05 4.75985203e-01]
Iter 11: LL=-1269424.73 | Rates: N=0.86147, AF=0.09734, OLD=0.08480, YOUNG=0.03281
A =
[[0.99514569 0.00100071 0.0038536 ]
 [0.0087394  0.98552863 0.00573197]
 [0.00530066 0.00122834 0.99347099]]
pi = [5.23956243e-01 3.73281933e-05 4.76006429e-01]
Iter 12: LL=-1269418.71 | Rates: N=0.86147, AF=0.09733, OLD=0.08661, YOUNG=0.03290
A =
[[9.95145814e-01 9.65998098e-04 3.88818757e-03]
 [8.86528104e-03 9.84973624e-01 6.16109515e-03]
 [5.30436086e-03 1.25499967e-03 9.93440639e-01]]
pi = [5.23996399e-01 1.39039806e-05 4.75989697e-01]
Iter 13: LL=-1269412.76 | Rates: N=0.86147, AF=0.09732, OLD=0.08848, YOUNG=0.03300
A =
[[9.95145962e-01 9.32254586e-04 3.92178374e-03]
 [8.98201518e-03 9.84400404e-01 6.61758108e-03]
 [5.31023870e-03 1.27981719e-03 9.93409944e-01]]
pi = [5.24034641e-01 5.10842414e-06 4.75960250e-01]
Iter 14: LL=-1269406.87 | Rates: N=0.86147, AF=0.09730, OLD=0.09041, YOUNG=0.03309
A =
[[9.95146114e-01 8.99647047e-04 3.95423862e-03]
 [9.09223094e-03 9.83805114e-01 7.10265496e-03]
 [5.31767890e-03 1.30281526e-03 9.93379506e-01]]
pi = [5.24069723e-01 1.85433460e-06 4.75928422e-01]
Iter 15: LL=-1269401.01 | Rates: N=0.86147, AF=0.09729, OLD=0.09242, YOUNG=0.03319
A =
[[9.95146261e-01 8.68274550e-04 3.98546493e-03]
 [9.19790509e-03 9.83184758e-01 7.61733680e-03]
 [5.32622664e-03 1.32403519e-03 9.93349738e-01]]
pi = [5.24100922e-01 6.66011218e-07 4.75898412e-01]
Final Global Rates (lambdas): [0.86146807 0.09729315 0.09241639 0.03318818]
Final transition matrix A:
[[9.95146261e-01 8.68274550e-04 3.98546493e-03]
 [9.19790509e-03 9.83184758e-01 7.61733680e-03]
 [5.32622664e-03 1.32403519e-03 9.93349738e-01]]
Final initial distribution pi:
[5.24100922e-01 6.66011218e-07 4.75898412e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1996  0.0908  0.1248    4856654.0   19474346.0  48648098.0
Archaic_young     0.8806  0.9452  0.9117  382146895.0   51818105.0  22159865.0
Modern            0.0000  0.0000  0.0000          0.0  541704000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         536825           82           2593
Archaic_old       921         4848          47914
Archaic_young    3958        19401         383458

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1451  0.0293  0.0487
Archaic_young     0.8602  0.9677  0.9108

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         514836           86           3158
Archaic_old      1105         1851          60644
Archaic_young    3753        10846         403721

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1497271.29 | Rates: N=0.85102, AF=0.09698, OLD=0.06182, YOUNG=0.04003
A =
[[0.99450938 0.00119953 0.00429109]
 [0.00672852 0.98908912 0.00418236]
 [0.00591536 0.00104675 0.99303789]]
pi = [0.59576065 0.09193981 0.31229954]
Iter 2: LL=-1270530.39 | Rates: N=0.85123, AF=0.09685, OLD=0.07153, YOUNG=0.03705
A =
[[0.99454639 0.00123448 0.00421913]
 [0.00677021 0.98923059 0.0039992 ]
 [0.00583227 0.00105537 0.99311236]]
pi = [0.59891775 0.08416796 0.31691429]
Iter 3: LL=-1270333.24 | Rates: N=0.85123, AF=0.09679, OLD=0.07887, YOUNG=0.03529
A =
[[0.99454933 0.00125998 0.0041907 ]
 [0.00698967 0.98895854 0.00405179]
 [0.00577119 0.00108037 0.99314845]]
pi = [0.59898726 0.07819542 0.32281732]
Iter 4: LL=-1270251.56 | Rates: N=0.85123, AF=0.09674, OLD=0.08369, YOUNG=0.03461
A =
[[0.99454881 0.00125793 0.00419326]
 [0.00729128 0.98834104 0.00436768]
 [0.00570833 0.00112127 0.9931704 ]]
pi = [0.599007   0.07264531 0.32834769]
Iter 5: LL=-1270220.99 | Rates: N=0.85123, AF=0.09669, OLD=0.08722, YOUNG=0.03445
A =
[[0.99454796 0.00123812 0.00421392]
 [0.00758303 0.98757218 0.00484479]
 [0.00566052 0.00117198 0.9931675 ]]
pi = [0.5990396  0.06676174 0.33419866]
Iter 6: LL=-1270202.12 | Rates: N=0.85123, AF=0.09666, OLD=0.09027, YOUNG=0.03449
A =
[[0.99454741 0.00120851 0.00424408]
 [0.00783738 0.98673982 0.0054228 ]
 [0.00562922 0.00122559 0.99314519]]
pi = [0.59907676 0.06052706 0.34039617]
Iter 7: LL=-1270185.87 | Rates: N=0.85123, AF=0.09663, OLD=0.09317, YOUNG=0.03459
A =
[[0.99454718 0.00117392 0.0042789 ]
 [0.00805369 0.98587126 0.00607505]
 [0.00561098 0.00127853 0.99311049]]
pi = [0.59911583 0.05425436 0.3466298 ]
Iter 8: LL=-1270170.52 | Rates: N=0.85123, AF=0.09660, OLD=0.09610, YOUNG=0.03472
A =
[[0.99454718 0.00113707 0.00431575]
 [0.00823834 0.98497163 0.00679002]
 [0.00560214 0.00132908 0.99306878]]
pi = [0.59915563 0.04824487 0.35259949]
Iter 9: LL=-1270155.70 | Rates: N=0.85123, AF=0.09658, OLD=0.09910, YOUNG=0.03485
A =
[[0.99454736 0.00109952 0.00435312]
 [0.00839795 0.98404051 0.00756154]
 [0.00559989 0.00137634 0.99302377]]
pi = [0.59919516 0.04270344 0.3581014 ]
Iter 10: LL=-1270141.36 | Rates: N=0.85122, AF=0.09655, OLD=0.10219, YOUNG=0.03498
A =
[[0.99454769 0.00106219 0.00439012]
 [0.00853764 0.98307775 0.0083846 ]
 [0.00560223 0.00141975 0.99297802]]
pi = [0.59923345 0.03774475 0.36302179]
Iter 11: LL=-1270127.54 | Rates: N=0.85122, AF=0.09653, OLD=0.10539, YOUNG=0.03512
A =
[[0.99454812 0.0010257  0.00442619]
 [0.00866119 0.98208481 0.009254  ]
 [0.00560774 0.00145895 0.9929333 ]]
pi = [0.59926956 0.03341515 0.36731529]
Iter 12: LL=-1270114.30 | Rates: N=0.85122, AF=0.09650, OLD=0.10869, YOUNG=0.03525
A =
[[9.94548638e-01 9.90429396e-04 4.46093300e-03]
 [8.77154986e-03 9.81064424e-01 1.01640259e-02]
 [5.61537368e-03 1.49377296e-03 9.92890853e-01]]
pi = [0.59930258 0.02971228 0.37098514]
Iter 13: LL=-1270101.72 | Rates: N=0.85122, AF=0.09648, OLD=0.11208, YOUNG=0.03538
A =
[[9.94549219e-01 9.56657650e-04 4.49412320e-03]
 [8.87127232e-03 9.80020025e-01 1.11087023e-02]
 [5.62432929e-03 1.52412417e-03 9.92851547e-01]]
pi = [0.59933171 0.02660141 0.37406688]
Iter 14: LL=-1270089.82 | Rates: N=0.85122, AF=0.09645, OLD=0.11556, YOUNG=0.03551
A =
[[9.94549841e-01 9.24547048e-04 4.52561156e-03]
 [8.96274905e-03 9.78955293e-01 1.20819579e-02]
 [5.63399661e-03 1.55002197e-03 9.92815981e-01]]
pi = [0.59935639 0.02402893 0.37661468]
Iter 15: LL=-1270078.62 | Rates: N=0.85121, AF=0.09642, OLD=0.11913, YOUNG=0.03564
A =
[[9.94550481e-01 8.94184416e-04 4.55533414e-03]
 [9.04826099e-03 9.77873898e-01 1.30778407e-02]
 [5.64390886e-03 1.57154949e-03 9.92784542e-01]]
pi = [0.59937627 0.02193317 0.37869056]
Final Global Rates (lambdas): [0.8512133  0.09642452 0.11912572 0.03564326]
Final transition matrix A:
[[9.94550481e-01 8.94184416e-04 4.55533414e-03]
 [9.04826099e-03 9.77873898e-01 1.30778407e-02]
 [5.64390886e-03 1.57154949e-03 9.92784542e-01]]
Final initial distribution pi:
[0.59937627 0.02193317 0.37869056]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2139  0.0635  0.0980    4029190.0   14807810.0  59380841.0
Archaic_young     0.8635  0.9588  0.9087  398419015.0   62962985.0  17129613.0
Modern            0.0000  0.0000  0.0000          0.0  519781000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         514851          284           2945
Archaic_old      1095         4027          58478
Archaic_young    3835        14526         399959

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2528  0.0255  0.0463
Archaic_young     0.8485  0.9788  0.9090

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         526596           55           3292
Archaic_old      1167         1721          64905
Archaic_young    4842         5029         392393

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1511201.42 | Rates: N=0.85446, AF=0.09657, OLD=0.06626, YOUNG=0.04578
A =
[[0.99421365 0.0012127  0.00457365]
 [0.00741776 0.98767053 0.00491171]
 [0.00659128 0.00114134 0.99226739]]
pi = [0.7983124  0.04499118 0.15669641]
Iter 2: LL=-1281427.29 | Rates: N=0.85470, AF=0.09648, OLD=0.07582, YOUNG=0.04286
A =
[[0.99427103 0.00126276 0.00446621]
 [0.00741631 0.98779411 0.00478958]
 [0.00648685 0.00114182 0.99237133]]
pi = [0.8103104  0.03909172 0.15059788]
Iter 3: LL=-1281245.36 | Rates: N=0.85469, AF=0.09641, OLD=0.08444, YOUNG=0.04074
A =
[[0.9942785  0.00133047 0.00439103]
 [0.0076319  0.9874968  0.0048713 ]
 [0.00641757 0.00115927 0.99242316]]
pi = [0.8112554  0.03709123 0.15165338]
Iter 4: LL=-1281137.59 | Rates: N=0.85469, AF=0.09635, OLD=0.09067, YOUNG=0.03965
A =
[[0.99428009 0.0013748  0.00434511]
 [0.00800836 0.98669922 0.00529241]
 [0.00633134 0.00119567 0.99247299]]
pi = [0.81151588 0.03701276 0.15147136]
Iter 5: LL=-1281088.74 | Rates: N=0.85468, AF=0.09630, OLD=0.09532, YOUNG=0.03924
A =
[[0.99427989 0.00139544 0.00432467]
 [0.0084112  0.98562989 0.00595891]
 [0.0062571  0.0012524  0.9924905 ]]
pi = [0.81168459 0.03848184 0.14983357]
Iter 6: LL=-1281059.35 | Rates: N=0.85468, AF=0.09626, OLD=0.09923, YOUNG=0.03912
A =
[[0.99427943 0.00139846 0.00432211]
 [0.00877637 0.98443644 0.00678719]
 [0.00620369 0.00132284 0.99247348]]
pi = [0.81175104 0.04110113 0.14714783]
Iter 7: LL=-1281035.34 | Rates: N=0.85468, AF=0.09622, OLD=0.10285, YOUNG=0.03912
A =
[[0.99427921 0.00138939 0.00433139]
 [0.0090877  0.98318114 0.00773115]
 [0.00616896 0.00140144 0.9924296 ]]
pi = [0.8117167 0.0445735 0.1437098]
Iter 8: LL=-1281013.34 | Rates: N=0.85467, AF=0.09619, OLD=0.10640, YOUNG=0.03915
A =
[[0.99427935 0.00137222 0.00434842]
 [0.00934767 0.98188547 0.00876687]
 [0.00614842 0.00148458 0.992367  ]]
pi = [0.81160109 0.04864966 0.13974925]
Iter 9: LL=-1280992.52 | Rates: N=0.85467, AF=0.09615, OLD=0.10995, YOUNG=0.03920
A =
[[0.99427985 0.0013497  0.00437045]
 [0.00956434 0.9805552  0.00988046]
 [0.00613793 0.00156981 0.99229226]]
pi = [0.81142819 0.05307512 0.13549669]
Iter 10: LL=-1280972.69 | Rates: N=0.85467, AF=0.09612, OLD=0.11356, YOUNG=0.03925
A =
[[0.99428064 0.00132375 0.0043956 ]
 [0.00974672 0.97919106 0.01106222]
 [0.00613432 0.00165527 0.99221041]]
pi = [0.81122301 0.05758034 0.13119666]
Iter 11: LL=-1280953.82 | Rates: N=0.85466, AF=0.09609, OLD=0.11723, YOUNG=0.03930
A =
[[0.99428166 0.00129572 0.00442262]
 [0.00990327 0.97779253 0.0123042 ]
 [0.00613522 0.00173954 0.99212524]]
pi = [0.81100962 0.06190156 0.12708882]
Iter 12: LL=-1280935.94 | Rates: N=0.85466, AF=0.09605, OLD=0.12097, YOUNG=0.03936
A =
[[0.9942828  0.00126659 0.00445061]
 [0.01004156 0.97635913 0.01359931]
 [0.00613894 0.0018215  0.99203957]]
pi = [0.81080853 0.06581097 0.1233805 ]
Iter 13: LL=-1280919.07 | Rates: N=0.85466, AF=0.09602, OLD=0.12477, YOUNG=0.03942
A =
[[0.99428396 0.00123705 0.00447899]
 [0.0101682  0.97489066 0.01494114]
 [0.00614426 0.00190028 0.99195545]]
pi = [0.8106347  0.06913834 0.12022697]
Iter 14: LL=-1280903.20 | Rates: N=0.85465, AF=0.09598, OLD=0.12864, YOUNG=0.03949
A =
[[0.99428505 0.00120763 0.00450732]
 [0.01028891 0.97338722 0.01632387]
 [0.00615035 0.00197526 0.99187438]]
pi = [0.81049713 0.07177649 0.11772639]
Iter 15: LL=-1280888.31 | Rates: N=0.85465, AF=0.09595, OLD=0.13258, YOUNG=0.03955
A =
[[0.99428598 0.00117871 0.0045353 ]
 [0.01040862 0.97184893 0.01774245]
 [0.00615661 0.002046   0.99179739]]
pi = [0.81039978 0.07367262 0.1159276 ]
Final Global Rates (lambdas): [0.85464618 0.09594951 0.13257895 0.03955415]
Final transition matrix A:
[[0.99428598 0.00117871 0.0045353 ]
 [0.01040862 0.97184893 0.01774245]
 [0.00615661 0.002046   0.99179739]]
Final initial distribution pi:
[0.81039978 0.07367262 0.1159276 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2415  0.0634  0.1005    4286922.0   13462078.0  63292926.0
Archaic_young     0.8511  0.9581  0.9014  382498513.0   66925487.0  16744011.0
Modern            0.0000  0.0000  0.0000          0.0  532827000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         526672          171           3100
Archaic_old      1210         4287          62296
Archaic_young    4945        13291         384028

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1854  0.0244  0.0431
Archaic_young     0.8713  0.9744  0.9200

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         545789           19           3337
Archaic_old      1114         1309          51658
Archaic_young    5910         5744         385120

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1545679.60 | Rates: N=0.86992, AF=0.09921, OLD=0.07691, YOUNG=0.05323
A =
[[0.99407768 0.00122933 0.00469299]
 [0.00806294 0.98660482 0.00533224]
 [0.00736409 0.00129243 0.99134348]]
pi = [0.40356671 0.19206051 0.40437278]
Iter 2: LL=-1301086.80 | Rates: N=0.87015, AF=0.09916, OLD=0.09019, YOUNG=0.04924
A =
[[0.99416708 0.00127695 0.00455596]
 [0.00821371 0.98667205 0.00511425]
 [0.00716733 0.00129782 0.99153484]]
pi = [0.39892549 0.26277763 0.33829688]
Iter 3: LL=-1300794.79 | Rates: N=0.87014, AF=0.09898, OLD=0.10265, YOUNG=0.04640
A =
[[0.99417866 0.00134402 0.00447732]
 [0.00869192 0.98616528 0.00514279]
 [0.00702243 0.00133059 0.99164699]]
pi = [0.39877295 0.3089754  0.29225165]
Iter 4: LL=-1300620.86 | Rates: N=0.87014, AF=0.09881, OLD=0.11183, YOUNG=0.04515
A =
[[0.99417958 0.00137354 0.00444688]
 [0.00937496 0.98501745 0.00560759]
 [0.0068723  0.00138811 0.99173958]]
pi = [0.39883674 0.32369769 0.27746557]
Iter 5: LL=-1300544.52 | Rates: N=0.87013, AF=0.09868, OLD=0.11889, YOUNG=0.04482
A =
[[0.99417692 0.00136994 0.00445314]
 [0.01006224 0.98357583 0.00636192]
 [0.00675951 0.00146555 0.99177493]]
pi = [0.3988244  0.32174918 0.27942642]
Iter 6: LL=-1300499.06 | Rates: N=0.87013, AF=0.09857, OLD=0.12502, YOUNG=0.04485
A =
[[0.99417415 0.00134518 0.00448066]
 [0.0106697  0.98203871 0.00729158]
 [0.00668678 0.00155169 0.99176154]]
pi = [0.39874548 0.31375152 0.287503  ]
Iter 7: LL=-1300462.82 | Rates: N=0.87013, AF=0.09848, OLD=0.13087, YOUNG=0.04499
A =
[[0.99417205 0.00130874 0.00451922]
 [0.01118769 0.9804685  0.00834381]
 [0.00664406 0.00163951 0.99171642]]
pi = [0.39865254 0.30462297 0.29672449]
Iter 8: LL=-1300430.44 | Rates: N=0.87012, AF=0.09839, OLD=0.13673, YOUNG=0.04516
A =
[[0.99417038 0.00126673 0.00456289]
 [0.0116349  0.97886484 0.00950027]
 [0.00662146 0.00172536 0.99165318]]
pi = [0.39856937 0.29623388 0.30519675]
Iter 9: LL=-1300400.23 | Rates: N=0.87012, AF=0.09830, OLD=0.14274, YOUNG=0.04534
A =
[[0.99416872 0.00122303 0.00460824]
 [0.01203693 0.97720548 0.01075759]
 [0.00661169 0.00180723 0.99158109]]
pi = [0.39849958 0.28906496 0.31243545]
Iter 10: LL=-1300371.56 | Rates: N=0.87011, AF=0.09821, OLD=0.14895, YOUNG=0.04553
A =
[[0.99416682 0.00118014 0.00465303]
 [0.01241535 0.97546827 0.01211638]
 [0.00660972 0.00188416 0.99150612]]
pi = [0.39843952 0.2830381  0.31852238]
Iter 11: LL=-1300344.06 | Rates: N=0.87010, AF=0.09813, OLD=0.15546, YOUNG=0.04572
A =
[[0.99416455 0.0011395  0.00469595]
 [0.01278747 0.97363362 0.01357891]
 [0.0066122  0.00195567 0.99143213]]
pi = [0.39838518 0.27786292 0.32375191]
Iter 12: LL=-1300317.30 | Rates: N=0.87010, AF=0.09803, OLD=0.16237, YOUNG=0.04591
A =
[[0.99416173 0.00110184 0.00473644]
 [0.01316944 0.97168034 0.01515022]
 [0.00661694 0.00202146 0.9913616 ]]
pi = [0.39833365 0.27318479 0.32848156]
Iter 13: LL=-1300290.79 | Rates: N=0.87009, AF=0.09793, OLD=0.16982, YOUNG=0.04611
A =
[[0.9941581  0.00106748 0.00477442]
 [0.01357816 0.96958258 0.01683927]
 [0.00662253 0.00208122 0.99129625]]
pi = [0.39828273 0.26864815 0.33306912]
Iter 14: LL=-1300263.94 | Rates: N=0.87008, AF=0.09782, OLD=0.17798, YOUNG=0.04631
A =
[[0.99415348 0.00103643 0.00481009]
 [0.01403157 0.9673079  0.01866052]
 [0.00662803 0.00213457 0.99123739]]
pi = [0.3982306  0.26391631 0.33785309]
Iter 15: LL=-1300236.11 | Rates: N=0.87007, AF=0.09770, OLD=0.18700, YOUNG=0.04653
A =
[[0.9941479  0.00100839 0.00484371]
 [0.01454708 0.96481754 0.02063538]
 [0.00663288 0.00218106 0.99118606]]
pi = [0.39817576 0.25868524 0.343139  ]
Final Global Rates (lambdas): [0.87006938 0.09769814 0.18699599 0.04653307]
Final transition matrix A:
[[0.9941479  0.00100839 0.00484371]
 [0.01454708 0.96481754 0.02063538]
 [0.00663288 0.00218106 0.99118606]]
Final initial distribution pi:
[0.39817576 0.25868524 0.343139  ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1997  0.0679  0.1014    3657777.0   14654223.0  50196875.0
Archaic_young     0.8744  0.9539  0.9124  375428068.0   53949932.0  18138888.0
Modern            0.0000  0.0000  0.0000          0.0  552310000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         545613          497           3035
Archaic_old      1061         3667          49353
Archaic_young    5636        14148         376990

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1596  0.2298  0.1884
Archaic_young     0.8748  0.8205  0.8468

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         544928          477           2195
Archaic_old      1218        13081          42926
Archaic_young    3321        68427         323427

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1509962.39 | Rates: N=0.86837, AF=0.09626, OLD=0.05595, YOUNG=0.03323
A =
[[0.99557557 0.0014973  0.00292713]
 [0.00574282 0.99195796 0.00229922]
 [0.00541662 0.00112685 0.99345654]]
pi = [0.3996905  0.19715274 0.40315675]
Iter 2: LL=-1268339.91 | Rates: N=0.86858, AF=0.09600, OLD=0.05892, YOUNG=0.03216
A =
[[0.99557964 0.001499   0.00292136]
 [0.00597895 0.99160769 0.00241336]
 [0.00528536 0.0011341  0.99358054]]
pi = [0.39834489 0.207043   0.39461211]
Iter 3: LL=-1268309.21 | Rates: N=0.86858, AF=0.09597, OLD=0.06127, YOUNG=0.03163
A =
[[0.99557967 0.00149688 0.00292344]
 [0.00622507 0.99119334 0.00258159]
 [0.00518792 0.00116447 0.99364761]]
pi = [0.39832811 0.21720006 0.38447183]
Iter 4: LL=-1268292.43 | Rates: N=0.86858, AF=0.09594, OLD=0.06310, YOUNG=0.03141
A =
[[0.99557922 0.00148588 0.0029349 ]
 [0.00645714 0.99074134 0.00280151]
 [0.0051088  0.00120833 0.99368287]]
pi = [0.3983132  0.22635472 0.37533207]
Iter 5: LL=-1268281.15 | Rates: N=0.86858, AF=0.09591, OLD=0.06464, YOUNG=0.03134
A =
[[0.99557867 0.00146755 0.00295378]
 [0.00666637 0.99027226 0.00306137]
 [0.00504821 0.00126032 0.99369146]]
pi = [0.39829218 0.23372245 0.36798537]
Iter 6: LL=-1268271.83 | Rates: N=0.86858, AF=0.09589, OLD=0.06602, YOUNG=0.03135
A =
[[0.99557814 0.00144378 0.00297808]
 [0.00685224 0.98979416 0.0033536 ]
 [0.00500336 0.00131674 0.9936799 ]]
pi = [0.39826832 0.23880607 0.36292561]
Iter 7: LL=-1268263.25 | Rates: N=0.86858, AF=0.09588, OLD=0.06734, YOUNG=0.03139
A =
[[0.9955777  0.00141617 0.00300613]
 [0.00701778 0.98930786 0.00367436]
 [0.00497087 0.00137532 0.99365382]]
pi = [0.39824457 0.24131574 0.36043969]
Iter 8: LL=-1268254.97 | Rates: N=0.86859, AF=0.09586, OLD=0.06864, YOUNG=0.03145
A =
[[0.99557734 0.00138596 0.0030367 ]
 [0.00716719 0.98881052 0.00402229]
 [0.00494773 0.00143472 0.99361755]]
pi = [0.3982231  0.24111269 0.36066421]
Iter 9: LL=-1268246.80 | Rates: N=0.86859, AF=0.09584, OLD=0.06996, YOUNG=0.03151
A =
[[0.99557704 0.00135405 0.00306891]
 [0.00730473 0.98829772 0.00439755]
 [0.00493155 0.00149409 0.99357436]]
pi = [0.39820526 0.23817521 0.36361952]
Iter 10: LL=-1268238.65 | Rates: N=0.86859, AF=0.09583, OLD=0.07132, YOUNG=0.03158
A =
[[0.99557679 0.00132108 0.00310213]
 [0.0074343  0.98776445 0.00480125]
 [0.0049205  0.00155286 0.99352665]]
pi = [0.39819183 0.23257767 0.36923051]
Iter 11: LL=-1268230.45 | Rates: N=0.86859, AF=0.09582, OLD=0.07274, YOUNG=0.03165
A =
[[0.99557657 0.00128751 0.00313592]
 [0.00755932 0.98720556 0.00523512]
 [0.00491318 0.00161062 0.9934762 ]]
pi = [0.39818314 0.22447722 0.37733965]
Iter 12: LL=-1268222.16 | Rates: N=0.86859, AF=0.09580, OLD=0.07422, YOUNG=0.03172
A =
[[0.99557637 0.00125364 0.00316999]
 [0.00768276 0.98661584 0.0057014 ]
 [0.00490859 0.00166706 0.99342435]]
pi = [0.39817927 0.21410481 0.38771592]
Iter 13: LL=-1268213.73 | Rates: N=0.86859, AF=0.09579, OLD=0.07578, YOUNG=0.03179
A =
[[0.99557618 0.00121969 0.00320413]
 [0.0078072  0.98599013 0.00620267]
 [0.00490597 0.00172192 0.99337211]]
pi = [0.39818011 0.20175646 0.40006343]
Iter 14: LL=-1268205.13 | Rates: N=0.86859, AF=0.09577, OLD=0.07743, YOUNG=0.03187
A =
[[0.99557597 0.00118581 0.00323821]
 [0.00793491 0.98532328 0.00674182]
 [0.00490478 0.00177495 0.99332027]]
pi = [0.39818543 0.18778177 0.4140328 ]
Iter 15: LL=-1268196.31 | Rates: N=0.86859, AF=0.09575, OLD=0.07919, YOUNG=0.03195
A =
[[0.99557576 0.0011521  0.00327214]
 [0.00806782 0.98461019 0.00732199]
 [0.00490464 0.00182592 0.99326944]]
pi = [0.39819492 0.17256813 0.42923695]
Final Global Rates (lambdas): [0.86859056 0.0957512  0.07918587 0.03195396]
Final transition matrix A:
[[0.99557576 0.0011521  0.00327214]
 [0.00806782 0.98461019 0.00732199]
 [0.00490464 0.00182592 0.99326944]]
Final initial distribution pi:
[0.39819492 0.17256813 0.42923695]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2344  0.1377  0.1735    7840928.0   25610072.0  49097574.0
Archaic_young     0.8760  0.9308  0.9025  365722654.0   51787346.0  27189722.0
Modern            0.0000  0.0000  0.0000          0.0  549039000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         544904          354           2342
Archaic_old      1053         7853          48319
Archaic_young    3082        25244         366849

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2613  0.1874  0.2183
Archaic_young     0.8777  0.9164  0.8967

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         530199          358           2594
Archaic_old      1059        11195          47778
Archaic_young    3768        31286         371763

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1506846.71 | Rates: N=0.86314, AF=0.09686, OLD=0.06162, YOUNG=0.03529
A =
[[0.9949348  0.00145773 0.00360746]
 [0.00683247 0.99003443 0.0031331 ]
 [0.00565639 0.00106785 0.99327576]]
pi = [0.6478559  0.06454884 0.28759526]
Iter 2: LL=-1269994.43 | Rates: N=0.86336, AF=0.09667, OLD=0.06783, YOUNG=0.03344
A =
[[0.9949485  0.00146578 0.00358572]
 [0.00721072 0.98957545 0.00321384]
 [0.00551545 0.00104553 0.99343902]]
pi = [0.65142721 0.03278507 0.31578772]
Iter 3: LL=-1269908.26 | Rates: N=0.86336, AF=0.09661, OLD=0.07248, YOUNG=0.03270
A =
[[0.99494958 0.001457   0.00359342]
 [0.00759628 0.9889859  0.00341782]
 [0.00542464 0.00105353 0.99352183]]
pi = [0.65132873 0.01404995 0.33462131]
Iter 4: LL=-1269872.53 | Rates: N=0.86336, AF=0.09657, OLD=0.07592, YOUNG=0.03253
A =
[[0.99494952 0.00142388 0.00362661]
 [0.00795283 0.98831771 0.00372946]
 [0.00536374 0.00107632 0.99355994]]
pi = [0.65124822 0.00533635 0.34341543]
Iter 5: LL=-1269852.75 | Rates: N=0.86336, AF=0.09654, OLD=0.07878, YOUNG=0.03258
A =
[[0.99494937 0.00137558 0.00367505]
 [0.00825999 0.98763496 0.00410505]
 [0.00532895 0.00110601 0.99356505]]
pi = [0.65123473 0.00187035 0.34689492]
Iter 6: LL=-1269837.36 | Rates: N=0.86336, AF=0.09651, OLD=0.08141, YOUNG=0.03272
A =
[[0.99494942 0.0013191  0.00373148]
 [0.00852004 0.98695857 0.00452139]
 [0.00531271 0.00113805 0.99354924]]
pi = [6.51247585e-01 6.17561038e-04 3.48134854e-01]
Iter 7: LL=-1269823.55 | Rates: N=0.86336, AF=0.09649, OLD=0.08398, YOUNG=0.03288
A =
[[0.9949497  0.00125882 0.00379148]
 [0.00874266 0.98628838 0.00496896]
 [0.00530858 0.00117022 0.9935212 ]]
pi = [6.51268425e-01 1.94020269e-04 3.48537555e-01]
Iter 8: LL=-1269810.56 | Rates: N=0.86336, AF=0.09648, OLD=0.08658, YOUNG=0.03304
A =
[[0.99495018 0.0011974  0.00385241]
 [0.00893815 0.98561689 0.00544496]
 [0.00531202 0.00120143 0.99348655]]
pi = [6.51291000e-01 5.82959069e-05 3.48650704e-01]
Iter 9: LL=-1269798.10 | Rates: N=0.86336, AF=0.09646, OLD=0.08925, YOUNG=0.03320
A =
[[0.99495083 0.00113643 0.00391273]
 [0.00911519 0.98493526 0.00594955]
 [0.00532003 0.0012311  0.99344888]]
pi = [6.51313487e-01 1.68030777e-05 3.48669710e-01]
Iter 10: LL=-1269786.03 | Rates: N=0.86336, AF=0.09644, OLD=0.09202, YOUNG=0.03336
A =
[[0.99495161 0.00107689 0.0039715 ]
 [0.0092805  0.98423531 0.00648419]
 [0.00533067 0.00125893 0.9934104 ]]
pi = [6.51335456e-01 4.65695297e-06 3.48659887e-01]
Iter 11: LL=-1269774.26 | Rates: N=0.86336, AF=0.09642, OLD=0.09491, YOUNG=0.03351
A =
[[0.9949525  0.00101935 0.00402815]
 [0.00943912 0.98350992 0.00705095]
 [0.00534273 0.00128479 0.99337248]]
pi = [6.51356855e-01 1.24356269e-06 3.48641902e-01]
Iter 12: LL=-1269762.72 | Rates: N=0.86335, AF=0.09640, OLD=0.09795, YOUNG=0.03366
A =
[[9.94953466e-01 9.64154004e-04 4.08238025e-03]
 [9.59497891e-03 9.82752646e-01 7.65237502e-03]
 [5.35540163e-03 1.30863730e-03 9.93335961e-01]]
pi = [6.51377707e-01 3.20591539e-07 3.48621973e-01]
Iter 13: LL=-1269751.36 | Rates: N=0.86335, AF=0.09637, OLD=0.10115, YOUNG=0.03380
A =
[[9.94954483e-01 9.11496496e-04 4.13402013e-03]
 [9.75138701e-03 9.81957192e-01 8.29142071e-03]
 [5.36817893e-03 1.33047078e-03 9.93301350e-01]]
pi = [6.51398037e-01 7.99521753e-08 3.48601883e-01]
Iter 14: LL=-1269740.10 | Rates: N=0.86335, AF=0.09635, OLD=0.10454, YOUNG=0.03394
A =
[[9.94955515e-01 8.61479645e-04 4.18300558e-03]
 [9.91146326e-03 9.81116910e-01 8.97162637e-03]
 [5.38071808e-03 1.35032485e-03 9.93268957e-01]]
pi = [6.51417861e-01 1.93287285e-08 3.48582120e-01]
Iter 15: LL=-1269728.88 | Rates: N=0.86335, AF=0.09632, OLD=0.10814, YOUNG=0.03409
A =
[[9.94956505e-01 8.14161979e-04 4.22933295e-03]
 [1.00783787e-02 9.80224378e-01 9.69724379e-03]
 [5.39280817e-03 1.36821580e-03 9.93238976e-01]]
pi = [6.51437191e-01 4.53952018e-09 3.48562805e-01]
Final Global Rates (lambdas): [0.86334769 0.09631715 0.10813939 0.03408547]
Final transition matrix A:
[[9.94956505e-01 8.14161979e-04 4.22933295e-03]
 [1.00783787e-02 9.80224378e-01 9.69724379e-03]
 [5.39280817e-03 1.36821580e-03 9.93238976e-01]]
Final initial distribution pi:
[6.51437191e-01 4.53952018e-09 3.48562805e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2788  0.0943  0.1409    5630042.0   14562958.0  54092961.0
Archaic_young     0.8712  0.9581  0.9126  387376901.0   57292099.0  16929859.0
Modern            0.0000  0.0000  0.0000          0.0  535138000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         530315          158           2678
Archaic_old      1078         5632          53322
Archaic_young    3745        14403         388669

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall     F1
Archaic_old       0.1920   0.096  0.128
Archaic_young     0.8684   0.934  0.900

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         517150          200           3199
Archaic_old      1139         5832          54160
Archaic_young    4330        24408         389582

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1502380.19 | Rates: N=0.85536, AF=0.09669, OLD=0.06600, YOUNG=0.03882
A =
[[0.99447288 0.00142065 0.00410647]
 [0.00711861 0.98902954 0.00385186]
 [0.00590962 0.001134   0.99295639]]
pi = [0.60222961 0.10732731 0.29044308]
Iter 2: LL=-1272202.39 | Rates: N=0.85558, AF=0.09659, OLD=0.07330, YOUNG=0.03627
A =
[[0.99451693 0.00142067 0.0040624 ]
 [0.00717294 0.98902318 0.00380389]
 [0.00581581 0.00114642 0.99303777]]
pi = [0.60555359 0.10671693 0.28772947]
Iter 3: LL=-1272083.59 | Rates: N=0.85558, AF=0.09654, OLD=0.07851, YOUNG=0.03506
A =
[[0.99452111 0.00141454 0.00406435]
 [0.00734303 0.98870662 0.00395036]
 [0.00576617 0.00118878 0.99304505]]
pi = [0.60566672 0.10128316 0.29305012]
Iter 4: LL=-1272039.61 | Rates: N=0.85558, AF=0.09650, OLD=0.08207, YOUNG=0.03462
A =
[[0.99452182 0.00138886 0.00408933]
 [0.00756737 0.98815373 0.0042789 ]
 [0.00571977 0.00124399 0.99303623]]
pi = [0.60569933 0.09243317 0.30186749]
Iter 5: LL=-1272019.21 | Rates: N=0.85558, AF=0.09647, OLD=0.08487, YOUNG=0.03454
A =
[[0.99452197 0.00135258 0.00412545]
 [0.00779011 0.98749332 0.00471657]
 [0.00568441 0.00130379 0.9930118 ]]
pi = [0.60573328 0.08246131 0.31180541]
Iter 6: LL=-1272004.07 | Rates: N=0.85558, AF=0.09644, OLD=0.08736, YOUNG=0.03459
A =
[[0.99452209 0.00131145 0.00416646]
 [0.00799054 0.98678749 0.00522197]
 [0.00566099 0.00136303 0.99297599]]
pi = [0.60576869 0.07235764 0.32187367]
Iter 7: LL=-1271990.48 | Rates: N=0.85558, AF=0.09642, OLD=0.08975, YOUNG=0.03468
A =
[[0.99452227 0.00126866 0.00420907]
 [0.00816395 0.98606125 0.0057748 ]
 [0.00564761 0.00141944 0.99293295]]
pi = [0.60580608 0.06247331 0.33172061]
Iter 8: LL=-1271977.81 | Rates: N=0.85558, AF=0.09640, OLD=0.09211, YOUNG=0.03479
A =
[[0.9945225  0.001226   0.0042515 ]
 [0.00831172 0.98532356 0.00636472]
 [0.00564192 0.0014722  0.99288588]]
pi = [0.60584552 0.05295658 0.34119789]
Iter 9: LL=-1271965.94 | Rates: N=0.85558, AF=0.09638, OLD=0.09447, YOUNG=0.03491
A =
[[0.99452277 0.00118447 0.00429276]
 [0.00843728 0.98457693 0.00698579]
 [0.00564182 0.00152109 0.99283709]]
pi = [0.60588643 0.04393379 0.35017978]
Iter 10: LL=-1271954.82 | Rates: N=0.85558, AF=0.09636, OLD=0.09684, YOUNG=0.03502
A =
[[0.99452306 0.00114466 0.00433228]
 [0.00854448 0.98382158 0.00763395]
 [0.00564564 0.00156612 0.99278825]]
pi = [0.60592763 0.03555983 0.35851254]
Iter 11: LL=-1271944.43 | Rates: N=0.85558, AF=0.09635, OLD=0.09922, YOUNG=0.03513
A =
[[0.99452335 0.0011069  0.00436975]
 [0.00863704 0.98305694 0.00830602]
 [0.00565206 0.00160744 0.9927405 ]]
pi = [0.60596757 0.02800686 0.36602557]
Iter 12: LL=-1271934.73 | Rates: N=0.85558, AF=0.09633, OLD=0.10161, YOUNG=0.03523
A =
[[0.99452364 0.00107134 0.00440503]
 [0.00871831 0.98228227 0.00899942]
 [0.00566011 0.00164524 0.99269465]]
pi = [0.60600448 0.02142668 0.37256884]
Iter 13: LL=-1271925.68 | Rates: N=0.85557, AF=0.09631, OLD=0.10402, YOUNG=0.03534
A =
[[0.99452392 0.00103799 0.0044381 ]
 [0.0087913  0.98149674 0.00971196]
 [0.00566905 0.00167974 0.99265121]]
pi = [0.60603675 0.01591158 0.37805167]
Iter 14: LL=-1271917.23 | Rates: N=0.85557, AF=0.09629, OLD=0.10645, YOUNG=0.03544
A =
[[0.99452419 0.0010068  0.00446902]
 [0.00885869 0.98069934 0.01044197]
 [0.00567834 0.00171116 0.9926105 ]]
pi = [0.60606313 0.01147202 0.38246485]
Iter 15: LL=-1271909.34 | Rates: N=0.85557, AF=0.09627, OLD=0.10889, YOUNG=0.03555
A =
[[9.94524440e-01 9.77669799e-04 4.49789021e-03]
 [8.92288532e-03 9.79888838e-01 1.11882768e-02]
 [5.68758402e-03 1.73972190e-03 9.92572694e-01]]
pi = [0.60608304 0.00803836 0.3858786 ]
Final Global Rates (lambdas): [0.85557243 0.09626998 0.10889157 0.03554597]
Final transition matrix A:
[[9.94524440e-01 9.77669799e-04 4.49789021e-03]
 [8.92288532e-03 9.79888838e-01 1.11882768e-02]
 [5.68758402e-03 1.73972190e-03 9.92572694e-01]]
Final initial distribution pi:
[0.60608304 0.00803836 0.3858786 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2354  0.0869  0.1269    5288880.0   17180120.0  55575934.0
Archaic_young     0.8697  0.9515  0.9088  395403764.0   59226236.0  20144864.0
Modern            0.0000  0.0000  0.0000          0.0  522901000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         517157          265           3127
Archaic_old      1212         5286          54633
Archaic_young    4532        16918         396870

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2399  0.1033  0.1444
Archaic_young     0.8838  0.9485  0.9150

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         542416          128           3059
Archaic_old      1568         5357          45208
Archaic_young    5208        16856         380200

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1527165.04 | Rates: N=0.86289, AF=0.09832, OLD=0.07545, YOUNG=0.04478
A =
[[0.99430455 0.00144994 0.00424552]
 [0.00804584 0.98753704 0.00441712]
 [0.00680284 0.00125907 0.99193809]]
pi = [0.71903989 0.06585765 0.21510246]
Iter 2: LL=-1289315.08 | Rates: N=0.86311, AF=0.09825, OLD=0.08619, YOUNG=0.04133
A =
[[0.99436954 0.001495   0.00413546]
 [0.00831121 0.98717692 0.00451186]
 [0.00661204 0.00125247 0.99213549]]
pi = [0.73652255 0.05267287 0.21080459]
Iter 3: LL=-1289109.65 | Rates: N=0.86311, AF=0.09815, OLD=0.09454, YOUNG=0.03958
A =
[[0.99437422 0.00153957 0.00408621]
 [0.00873147 0.98636641 0.00490213]
 [0.00649935 0.00129615 0.9922045 ]]
pi = [0.73837483 0.04298729 0.21863788]
Iter 4: LL=-1289020.61 | Rates: N=0.86311, AF=0.09806, OLD=0.10048, YOUNG=0.03894
A =
[[0.99437377 0.00155105 0.00407518]
 [0.00918096 0.98525177 0.00556728]
 [0.00641113 0.00136931 0.99221956]]
pi = [0.73870939 0.03362397 0.22766664]
Iter 5: LL=-1288977.27 | Rates: N=0.86310, AF=0.09799, OLD=0.10511, YOUNG=0.03880
A =
[[0.99437285 0.00153898 0.00408817]
 [0.00957715 0.98403749 0.00638536]
 [0.00635388 0.00145672 0.9921894 ]]
pi = [0.73892506 0.02500133 0.23607361]
Iter 6: LL=-1288947.25 | Rates: N=0.86310, AF=0.09794, OLD=0.10911, YOUNG=0.03884
A =
[[0.9943722  0.0015131  0.00411469]
 [0.00990425 0.98281339 0.00728236]
 [0.00632125 0.00154809 0.99213066]]
pi = [0.73915787 0.01768377 0.24315836]
Iter 7: LL=-1288922.78 | Rates: N=0.86310, AF=0.09790, OLD=0.11280, YOUNG=0.03894
A =
[[0.99437188 0.00147993 0.00414818]
 [0.0101718  0.98160777 0.00822043]
 [0.00630503 0.00163832 0.99205665]]
pi = [0.73939426 0.01194776 0.24865798]
Iter 8: LL=-1288901.85 | Rates: N=0.86310, AF=0.09786, OLD=0.11631, YOUNG=0.03905
A =
[[0.99437181 0.00144346 0.00418473]
 [0.01039481 0.98042497 0.00918022]
 [0.00629889 0.00172498 0.99197612]]
pi = [0.7396036  0.00775396 0.25264244]
Iter 9: LL=-1288883.65 | Rates: N=0.86309, AF=0.09783, OLD=0.11970, YOUNG=0.03917
A =
[[0.99437189 0.00140611 0.004222  ]
 [0.01058704 0.9792617  0.01015125]
 [0.00629854 0.00180697 0.99189448]]
pi = [0.73976636 0.00486239 0.25537125]
Iter 10: LL=-1288867.70 | Rates: N=0.86309, AF=0.09780, OLD=0.12301, YOUNG=0.03928
A =
[[0.99437204 0.00136933 0.00425863]
 [0.01075939 0.97811306 0.01112755]
 [0.00630126 0.00188382 0.99181493]]
pi = [0.73987826 0.00296269 0.25715905]
Iter 11: LL=-1288853.63 | Rates: N=0.86309, AF=0.09777, OLD=0.12625, YOUNG=0.03939
A =
[[0.99437222 0.00133394 0.00429384]
 [0.01091993 0.97697444 0.01210563]
 [0.00630535 0.0019554  0.99173924]]
pi = [0.73994552 0.00176272 0.25829175]
Iter 12: LL=-1288841.13 | Rates: N=0.86308, AF=0.09774, OLD=0.12943, YOUNG=0.03950
A =
[[0.99437239 0.00130039 0.00432722]
 [0.01107448 0.97584194 0.01308358]
 [0.00630982 0.00202184 0.99166834]]
pi = [0.73997874 0.00102845 0.25899281]
Iter 13: LL=-1288829.97 | Rates: N=0.86308, AF=0.09772, OLD=0.13257, YOUNG=0.03961
A =
[[0.99437251 0.0012689  0.00435859]
 [0.0112272  0.97471218 0.01406062]
 [0.00631408 0.00208333 0.99160259]]
pi = [7.39988553e-01 5.90510580e-04 2.59420936e-01]
Iter 14: LL=-1288819.92 | Rates: N=0.86308, AF=0.09769, OLD=0.13568, YOUNG=0.03971
A =
[[0.99437257 0.00123951 0.00438792]
 [0.01138104 0.97358218 0.01503678]
 [0.00631782 0.00214017 0.99154201]]
pi = [7.39983586e-01 3.34660465e-04 2.59681754e-01]
Iter 15: LL=-1288810.80 | Rates: N=0.86308, AF=0.09766, OLD=0.13877, YOUNG=0.03982
A =
[[0.99437256 0.00121217 0.00441527]
 [0.01153813 0.97244916 0.01601271]
 [0.00632091 0.00219264 0.99148645]]
pi = [7.39970030e-01 1.87662983e-04 2.59842307e-01]
Final Global Rates (lambdas): [0.86307599 0.09766332 0.1387736  0.03981732]
Final transition matrix A:
[[0.99437256 0.00121217 0.00441527]
 [0.01153813 0.97244916 0.01601271]
 [0.00632091 0.00219264 0.99148645]]
Final initial distribution pi:
[7.39970030e-01 1.87662983e-04 2.59842307e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2760  0.1257  0.1728    6522423.0   17111577.0  45349723.0
Archaic_young     0.8865  0.9491  0.9168  378935123.0   48500877.0  20307401.0
Modern            0.0000  0.0000  0.0000          0.0  548930000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         542342          345           2916
Archaic_old      1485         6533          44115
Archaic_young    5103        16756         380405

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2379  0.4189  0.3035
Archaic_young     0.8767  0.7608  0.8146

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         532511          691           2074
Archaic_old      1535        28981          39033
Archaic_young    3281        92004         299890

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 18
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1502023.30 | Rates: N=0.85964, AF=0.09609, OLD=0.05974, YOUNG=0.03221
A =
[[0.99527209 0.00183812 0.00288979]
 [0.00609347 0.99173945 0.00216708]
 [0.00535564 0.00121921 0.99342515]]
pi = [0.39862567 0.17615433 0.42522001]
Iter 2: LL=-1267754.08 | Rates: N=0.85986, AF=0.09588, OLD=0.06227, YOUNG=0.03149
A =
[[0.99527792 0.00181364 0.00290843]
 [0.0063496  0.99130214 0.00234826]
 [0.00521473 0.00121997 0.9935653 ]]
pi = [0.39708926 0.1512603  0.45165044]
Iter 3: LL=-1267731.05 | Rates: N=0.85986, AF=0.09586, OLD=0.06429, YOUNG=0.03128
A =
[[0.99527834 0.00178748 0.00293418]
 [0.00657159 0.99086175 0.00256665]
 [0.00513307 0.00124867 0.99361826]]
pi = [0.39710332 0.12836004 0.47453664]
Iter 4: LL=-1267717.10 | Rates: N=0.85986, AF=0.09584, OLD=0.06596, YOUNG=0.03128
A =
[[0.99527842 0.00175268 0.0029689 ]
 [0.00676479 0.99041074 0.00282447]
 [0.00507686 0.00128777 0.99363537]]
pi = [0.39713649 0.10736466 0.49549885]
Iter 5: LL=-1267705.81 | Rates: N=0.85986, AF=0.09582, OLD=0.06746, YOUNG=0.03137
A =
[[0.9952785  0.00171193 0.00300957]
 [0.00693179 0.98995494 0.00311327]
 [0.00503993 0.00133164 0.99362844]]
pi = [0.39717063 0.08826306 0.51456631]
Iter 6: LL=-1267695.41 | Rates: N=0.85986, AF=0.09581, OLD=0.06891, YOUNG=0.03149
A =
[[0.99527864 0.00166742 0.00305394]
 [0.00707709 0.9894942  0.00342871]
 [0.0050171  0.00137725 0.99360565]]
pi = [0.39720322 0.07103049 0.53176629]
Iter 7: LL=-1267685.38 | Rates: N=0.85986, AF=0.09580, OLD=0.07035, YOUNG=0.03162
A =
[[0.99527884 0.00162067 0.00310048]
 [0.00720524 0.98902591 0.00376885]
 [0.00500443 0.001423   0.99357257]]
pi = [0.39723286 0.05571666 0.54705048]
Iter 8: LL=-1267675.57 | Rates: N=0.85986, AF=0.09579, OLD=0.07181, YOUNG=0.03176
A =
[[0.99527911 0.00157275 0.00314814]
 [0.00732021 0.98854677 0.00413302]
 [0.004999   0.001468   0.993533  ]]
pi = [0.39725865 0.04242092 0.56032043]
Iter 9: LL=-1267665.92 | Rates: N=0.85986, AF=0.09578, OLD=0.07331, YOUNG=0.03189
A =
[[0.99527941 0.00152441 0.00319617]
 [0.00742525 0.98805365 0.0045211 ]
 [0.00499871 0.00151171 0.99348958]]
pi = [0.39727996 0.03123023 0.57148981]
Iter 10: LL=-1267656.41 | Rates: N=0.85985, AF=0.09577, OLD=0.07485, YOUNG=0.03201
A =
[[0.99527975 0.0014762  0.00324405]
 [0.00752297 0.98754388 0.00493315]
 [0.00500205 0.00155381 0.99344414]]
pi = [0.39729641 0.02215909 0.5805445 ]
Iter 11: LL=-1267647.05 | Rates: N=0.85985, AF=0.09576, OLD=0.07644, YOUNG=0.03214
A =
[[0.9952801  0.00142851 0.00329139]
 [0.00761543 0.98701524 0.00536933]
 [0.0050079  0.0015941  0.99339799]]
pi = [0.39730793 0.01511368 0.58757839]
Iter 12: LL=-1267637.86 | Rates: N=0.85985, AF=0.09575, OLD=0.07809, YOUNG=0.03226
A =
[[0.99528045 0.00138165 0.00333789]
 [0.00770426 0.98646597 0.00582977]
 [0.00501547 0.00163249 0.99335204]]
pi = [0.39731476 0.00988958 0.59279566]
Iter 13: LL=-1267628.83 | Rates: N=0.85985, AF=0.09574, OLD=0.07979, YOUNG=0.03238
A =
[[0.99528081 0.00133587 0.00338332]
 [0.00779077 0.9858946  0.00631463]
 [0.00502415 0.00166894 0.99330691]]
pi = [0.39731747 0.00620001 0.59648252]
Iter 14: LL=-1267620.00 | Rates: N=0.85985, AF=0.09573, OLD=0.08154, YOUNG=0.03250
A =
[[0.99528115 0.00129134 0.00342751]
 [0.00787602 0.98529996 0.00682402]
 [0.0050335  0.00170345 0.99326305]]
pi = [0.3973168  0.00372102 0.59896218]
Iter 15: LL=-1267611.36 | Rates: N=0.85985, AF=0.09572, OLD=0.08334, YOUNG=0.03262
A =
[[0.99528148 0.0012482  0.00347032]
 [0.00796091 0.98468104 0.00735805]
 [0.00504317 0.00173609 0.99322074]]
pi = [0.3973136  0.00213706 0.60054934]
Final Global Rates (lambdas): [0.85985251 0.09572056 0.08334425 0.03261703]
Final transition matrix A:
[[0.99528148 0.0012482  0.00347032]
 [0.00796091 0.98468104 0.00735805]
 [0.00504317 0.00173609 0.99322074]]
Final initial distribution pi:
[0.3973136  0.00213706 0.60054934]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3611  0.1928  0.2514   13324013.0   23576987.0  55781781.0
Archaic_young     0.8631  0.9360  0.8981  367747877.0   58329123.0  25164499.0
Modern            0.0000  0.0000  0.0000          0.0  537022000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         532502          346           2428
Archaic_old      1423        13348          54778
Archaic_young    3097        23207         368871

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2945  0.3193  0.3064
Archaic_young     0.8868  0.8784  0.8826

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         527412          618           2618
Archaic_old      1150        19870          41515
Archaic_young    3579        46918         356320

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1504970.34 | Rates: N=0.85993, AF=0.09669, OLD=0.06544, YOUNG=0.03458
A =
[[0.99475861 0.00174011 0.00350128]
 [0.00736068 0.98963809 0.00300124]
 [0.00561185 0.00113583 0.99325232]]
pi = [0.54013334 0.09254359 0.36732307]
Iter 2: LL=-1270831.76 | Rates: N=0.86016, AF=0.09655, OLD=0.07071, YOUNG=0.03313
A =
[[0.99477893 0.00173486 0.0034862 ]
 [0.00783572 0.98894159 0.00322269]
 [0.00544216 0.00111166 0.99344618]]
pi = [0.54318233 0.06244102 0.39437664]
Iter 3: LL=-1270767.33 | Rates: N=0.86016, AF=0.09648, OLD=0.07495, YOUNG=0.03267
A =
[[0.99477806 0.0017214  0.00350054]
 [0.00827107 0.98817604 0.00355289]
 [0.00535213 0.00112725 0.99352063]]
pi = [0.54363593 0.04817379 0.40819028]
Iter 4: LL=-1270734.52 | Rates: N=0.86016, AF=0.09642, OLD=0.07841, YOUNG=0.03261
A =
[[0.99477603 0.00168626 0.00353771]
 [0.00865923 0.9873531  0.00398766]
 [0.00529961 0.0011578  0.99354259]]
pi = [0.54391178 0.04207785 0.41401036]
Iter 5: LL=-1270711.05 | Rates: N=0.86016, AF=0.09637, OLD=0.08154, YOUNG=0.03270
A =
[[0.99477432 0.00163761 0.00358807]
 [0.00898686 0.98651955 0.00449359]
 [0.00527587 0.00119516 0.99352898]]
pi = [0.54407758 0.03987514 0.41604729]
Iter 6: LL=-1270690.81 | Rates: N=0.86017, AF=0.09633, OLD=0.08453, YOUNG=0.03284
A =
[[0.9947731  0.00158181 0.00364508]
 [0.00925759 0.98569202 0.00505039]
 [0.00527182 0.00123481 0.99349337]]
pi = [0.54414104 0.03951559 0.41634338]
Iter 7: LL=-1270672.36 | Rates: N=0.86017, AF=0.09630, OLD=0.08749, YOUNG=0.03299
A =
[[0.9947723  0.00152303 0.00370467]
 [0.00948126 0.98487289 0.00564585]
 [0.00528026 0.0012743  0.99344544]]
pi = [0.54413428 0.04001325 0.41585247]
Iter 8: LL=-1270655.34 | Rates: N=0.86017, AF=0.09626, OLD=0.09044, YOUNG=0.03314
A =
[[0.99477179 0.00146392 0.00376429]
 [0.00966859 0.98405979 0.00627162]
 [0.00529608 0.00131221 0.99339171]]
pi = [0.5440872  0.04087199 0.41504082]
Iter 9: LL=-1270639.62 | Rates: N=0.86017, AF=0.09623, OLD=0.09340, YOUNG=0.03328
A =
[[0.99477147 0.00140613 0.0038224 ]
 [0.00982919 0.98324962 0.00692118]
 [0.00531581 0.00134778 0.99333641]]
pi = [0.54402044 0.04184264 0.41413692]
Iter 10: LL=-1270625.18 | Rates: N=0.86017, AF=0.09619, OLD=0.09637, YOUNG=0.03342
A =
[[0.99477127 0.00135062 0.0038781 ]
 [0.00997111 0.98243981 0.00758908]
 [0.00533717 0.00138061 0.99328222]]
pi = [0.54394642 0.04280829 0.41324529]
Iter 11: LL=-1270611.94 | Rates: N=0.86017, AF=0.09616, OLD=0.09935, YOUNG=0.03356
A =
[[0.99477114 0.00129794 0.00393093]
 [0.01010079 0.98162856 0.00827065]
 [0.00535869 0.00141054 0.99323077]]
pi = [0.54387184 0.04372168 0.41240648]
Iter 12: LL=-1270599.86 | Rates: N=0.86017, AF=0.09613, OLD=0.10233, YOUNG=0.03369
A =
[[0.99477103 0.0012483  0.00398067]
 [0.01022328 0.98081474 0.00896198]
 [0.00537946 0.00143759 0.99318294]]
pi = [0.54379993 0.04456953 0.41163054]
Iter 13: LL=-1270588.83 | Rates: N=0.86016, AF=0.09610, OLD=0.10532, YOUNG=0.03382
A =
[[0.99477092 0.00120177 0.00402731]
 [0.01034244 0.9799978  0.00965976]
 [0.00539897 0.00146188 0.99313914]]
pi = [0.54373201 0.045353   0.410915  ]
Iter 14: LL=-1270578.79 | Rates: N=0.86016, AF=0.09607, OLD=0.10832, YOUNG=0.03395
A =
[[0.9947708  0.00115827 0.00407092]
 [0.0104612  0.97917756 0.01036124]
 [0.00541694 0.00148359 0.99309947]]
pi = [0.5436684  0.04607806 0.41025354]
Iter 15: LL=-1270569.62 | Rates: N=0.86016, AF=0.09604, OLD=0.11131, YOUNG=0.03408
A =
[[0.99477065 0.00111769 0.00411166]
 [0.01058187 0.97835386 0.01106427]
 [0.00543325 0.00150291 0.99306384]]
pi = [0.54360896 0.0467514  0.40963964]
Final Global Rates (lambdas): [0.8601635  0.09603834 0.1113133  0.03407674]
Final transition matrix A:
[[0.99477065 0.00111769 0.00411166]
 [0.01058187 0.97835386 0.01106427]
 [0.00543325 0.00150291 0.99306384]]
Final initial distribution pi:
[0.54360896 0.0467514  0.40963964]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3596  0.1404  0.2019    8725463.0   15541537.0  53428449.0
Archaic_young     0.8721  0.9565  0.9123  386715244.0   56722756.0  17591516.0
Modern            0.0000  0.0000  0.0000          0.0  532295000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         527401          371           2876
Archaic_old      1277         8730          52528
Archaic_young    3617        15166         388034

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.4, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3074  0.2507  0.2761
Archaic_young     0.8827  0.9063  0.8943

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         515429           81           2825
Archaic_old      1744        15761          45840
Archaic_young    4817        35509         377994

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1508526.55 | Rates: N=0.85630, AF=0.09824, OLD=0.07128, YOUNG=0.03808
A =
[[0.99414833 0.0017493  0.00410237]
 [0.00781794 0.9884851  0.00369696]
 [0.00607457 0.00119443 0.992731  ]]
pi = [0.56151327 0.12214241 0.31634432]
Iter 2: LL=-1276996.55 | Rates: N=0.85654, AF=0.09819, OLD=0.07794, YOUNG=0.03582
A =
[[0.99418982 0.00174675 0.00406344]
 [0.00799481 0.98811444 0.00389074]
 [0.00596418 0.00117946 0.99285635]]
pi = [0.56201558 0.12614012 0.3118443 ]
Iter 3: LL=-1276901.36 | Rates: N=0.85654, AF=0.09812, OLD=0.08276, YOUNG=0.03495
A =
[[0.99419359 0.00174076 0.00406566]
 [0.00817112 0.98757924 0.00424964]
 [0.00592572 0.00120898 0.9928653 ]]
pi = [0.5617059  0.12983251 0.3084616 ]
Iter 4: LL=-1276864.47 | Rates: N=0.85653, AF=0.09806, OLD=0.08629, YOUNG=0.03471
A =
[[0.9941942  0.00171297 0.00409282]
 [0.00835412 0.98688574 0.00476014]
 [0.00590294 0.00125544 0.99284162]]
pi = [0.56147266 0.13013609 0.30839126]
Iter 5: LL=-1276842.38 | Rates: N=0.85653, AF=0.09802, OLD=0.08927, YOUNG=0.03472
A =
[[0.99419443 0.00167289 0.00413268]
 [0.00852387 0.98611241 0.00536372]
 [0.00589201 0.00130976 0.99279823]]
pi = [0.56134307 0.12749506 0.31116188]
Iter 6: LL=-1276823.60 | Rates: N=0.85653, AF=0.09799, OLD=0.09208, YOUNG=0.03483
A =
[[0.99419469 0.00162659 0.00417871]
 [0.00867791 0.9852922  0.00602989]
 [0.00588912 0.00136693 0.99274395]]
pi = [0.56128513 0.1228273  0.31588756]
Iter 7: LL=-1276805.98 | Rates: N=0.85653, AF=0.09797, OLD=0.09486, YOUNG=0.03497
A =
[[0.99419504 0.00157746 0.0042275 ]
 [0.00881968 0.98443556 0.00674476]
 [0.00589123 0.00142437 0.9926844 ]]
pi = [0.56127184 0.11695581 0.32177235]
Iter 8: LL=-1276789.14 | Rates: N=0.85653, AF=0.09794, OLD=0.09770, YOUNG=0.03512
A =
[[0.99419546 0.00152739 0.00427715]
 [0.00895357 0.9835443  0.00750212]
 [0.00589622 0.00148069 0.99262309]]
pi = [0.56128624 0.11053747 0.32817629]
Iter 9: LL=-1276772.98 | Rates: N=0.85653, AF=0.09791, OLD=0.10062, YOUNG=0.03526
A =
[[0.99419595 0.00147749 0.00432656]
 [0.00908345 0.98261732 0.00829923]
 [0.00590271 0.00153501 0.99256229]]
pi = [0.56131713 0.10408226 0.33460061]
Iter 10: LL=-1276757.44 | Rates: N=0.85653, AF=0.09789, OLD=0.10364, YOUNG=0.03541
A =
[[0.99419651 0.00142842 0.00437507]
 [0.00921233 0.98165269 0.00913498]
 [0.00590984 0.00158671 0.99250345]]
pi = [0.56135582 0.0979669  0.34067729]
Iter 11: LL=-1276742.45 | Rates: N=0.85652, AF=0.09786, OLD=0.10678, YOUNG=0.03556
A =
[[0.99419714 0.00138056 0.0044223 ]
 [0.00934245 0.98064815 0.0100094 ]
 [0.00591712 0.00163533 0.99244755]]
pi = [0.56139492 0.09244192 0.34616317]
Iter 12: LL=-1276727.92 | Rates: N=0.85652, AF=0.09782, OLD=0.11007, YOUNG=0.03571
A =
[[0.99419784 0.00133406 0.0044681 ]
 [0.00947566 0.97960084 0.01092351]
 [0.00592428 0.00168048 0.99239525]]
pi = [0.56142809 0.08764436 0.35092754]
Iter 13: LL=-1276713.74 | Rates: N=0.85652, AF=0.09779, OLD=0.11352, YOUNG=0.03586
A =
[[0.99419857 0.00128896 0.00451247]
 [0.00961381 0.97850718 0.01187901]
 [0.00593118 0.00172188 0.99234694]]
pi = [0.56145039 0.08362021 0.3549294 ]
Iter 14: LL=-1276699.87 | Rates: N=0.85652, AF=0.09775, OLD=0.11714, YOUNG=0.03601
A =
[[0.99419925 0.00124527 0.00455548]
 [0.00975883 0.97736388 0.01287728]
 [0.0059378  0.00175934 0.99230286]]
pi = [0.56145862 0.08035186 0.35818952]
Iter 15: LL=-1276686.31 | Rates: N=0.85651, AF=0.09771, OLD=0.12091, YOUNG=0.03616
A =
[[0.99419982 0.00120306 0.00459712]
 [0.00991221 0.97616962 0.01391817]
 [0.0059441  0.00179286 0.99226304]]
pi = [0.56145144 0.07778123 0.36076733]
Final Global Rates (lambdas): [0.85651353 0.09771289 0.12090815 0.03616003]
Final transition matrix A:
[[0.99419982 0.00120306 0.00459712]
 [0.00991221 0.97616962 0.01391817]
 [0.0059441  0.00179286 0.99226304]]
Final initial distribution pi:
[0.56145144 0.07778123 0.36076733]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.4_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3874  0.1378  0.2033    8674108.0   13715892.0  54286717.0
Archaic_young     0.8738  0.9599  0.9149  398902073.0   57597927.0  16646555.0
Modern            0.0000  0.0000  0.0000          0.0  521110000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         515242          176           2917
Archaic_old      1443         8672          53230
Archaic_young    4425        13542         400353

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3527  0.0136  0.0263
Archaic_young     0.9049  0.9924  0.9466

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         449835            3           2443
Archaic_old       392          670          48023
Archaic_young    3551         1225         493858

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1454122.46 | Rates: N=0.82659, AF=0.09792, OLD=0.04963, YOUNG=0.03764
A =
[[9.94919888e-01 7.83274773e-04 4.29683738e-03]
 [4.26063555e-03 9.91968355e-01 3.77100896e-03]
 [4.33301449e-03 6.94969152e-04 9.94972016e-01]]
pi = [0.35183047 0.13818733 0.5099822 ]
Iter 2: LL=-1246153.17 | Rates: N=0.82673, AF=0.09764, OLD=0.05664, YOUNG=0.03609
A =
[[9.94932936e-01 8.24322868e-04 4.24274126e-03]
 [4.10498168e-03 9.92328948e-01 3.56606991e-03]
 [4.33886079e-03 7.19948241e-04 9.94941191e-01]]
pi = [0.35059848 0.13661916 0.51278236]
Iter 3: LL=-1246028.05 | Rates: N=0.82673, AF=0.09758, OLD=0.06352, YOUNG=0.03441
A =
[[9.94937668e-01 8.76005426e-04 4.18632630e-03]
 [4.09049831e-03 9.92416813e-01 3.49268821e-03]
 [4.33874144e-03 7.50004356e-04 9.94911254e-01]]
pi = [0.35058943 0.11856127 0.5308493 ]
Iter 4: LL=-1245926.78 | Rates: N=0.82673, AF=0.09750, OLD=0.06889, YOUNG=0.03336
A =
[[9.94942014e-01 9.15277636e-04 4.14270794e-03]
 [4.24840317e-03 9.92059205e-01 3.69239201e-03]
 [4.29814462e-03 7.84725465e-04 9.94917130e-01]]
pi = [0.35057869 0.0879904  0.56143091]
Iter 5: LL=-1245874.77 | Rates: N=0.82673, AF=0.09741, OLD=0.07305, YOUNG=0.03289
A =
[[9.94945736e-01 9.35663233e-04 4.11860105e-03]
 [4.48336430e-03 9.91406939e-01 4.10969621e-03]
 [4.24370517e-03 8.27119164e-04 9.94929176e-01]]
pi = [0.35055945 0.05794159 0.59149896]
Iter 6: LL=-1245844.72 | Rates: N=0.82673, AF=0.09734, OLD=0.07654, YOUNG=0.03274
A =
[[9.94948364e-01 9.39364000e-04 4.11227170e-03]
 [4.72533333e-03 9.90606607e-01 4.66805999e-03]
 [4.19570097e-03 8.74803617e-04 9.94929495e-01]]
pi = [0.35055853 0.03518338 0.61425809]
Iter 7: LL=-1245821.91 | Rates: N=0.82673, AF=0.09729, OLD=0.07971, YOUNG=0.03272
A =
[[9.94950340e-01 9.30831441e-04 4.11882888e-03]
 [4.94301790e-03 9.89738767e-01 5.31821558e-03]
 [4.15956521e-03 9.24971781e-04 9.94915463e-01]]
pi = [0.35057661 0.02025747 0.62916592]
Iter 8: LL=-1245802.16 | Rates: N=0.82672, AF=0.09724, OLD=0.08276, YOUNG=0.03275
A =
[[9.94952037e-01 9.13922026e-04 4.13404054e-03]
 [5.12827861e-03 9.88836675e-01 6.03504597e-03]
 [4.13431774e-03 9.75724953e-04 9.94889957e-01]]
pi = [0.35060331 0.01126742 0.63812927]
Iter 9: LL=-1245784.24 | Rates: N=0.82672, AF=0.09720, OLD=0.08579, YOUNG=0.03280
A =
[[9.94953629e-01 8.91517609e-04 4.15485327e-03]
 [5.28330926e-03 9.87909307e-01 6.80738366e-03]
 [4.11745793e-03 1.02586841e-03 9.94856674e-01]]
pi = [0.35063065 0.00612963 0.64323971]
Iter 10: LL=-1245767.64 | Rates: N=0.82672, AF=0.09717, OLD=0.08883, YOUNG=0.03287
A =
[[9.94955152e-01 8.65731025e-04 4.17911702e-03]
 [5.41383533e-03 9.86955129e-01 7.63103607e-03]
 [4.10663387e-03 1.07462402e-03 9.94818742e-01]]
pi = [0.35065494 0.00328882 0.64605623]
Iter 11: LL=-1245752.08 | Rates: N=0.82672, AF=0.09713, OLD=0.09192, YOUNG=0.03294
A =
[[9.94956592e-01 8.38116666e-04 4.20529109e-03]
 [5.52597063e-03 9.85969145e-01 8.50488398e-03]
 [4.10001230e-03 1.12149219e-03 9.94778496e-01]]
pi = [0.35067511 0.00175035 0.64757454]
Iter 12: LL=-1245737.37 | Rates: N=0.82672, AF=0.09710, OLD=0.09508, YOUNG=0.03301
A =
[[9.94957943e-01 8.09794037e-04 4.23226312e-03]
 [5.62499753e-03 9.84945971e-01 9.42903139e-03]
 [4.09624765e-03 1.16617220e-03 9.94737580e-01]]
pi = [0.35069125 0.00092765 0.64838111]
Iter 13: LL=-1245723.40 | Rates: N=0.82672, AF=0.09707, OLD=0.09832, YOUNG=0.03309
A =
[[9.94959218e-01 7.81526741e-04 4.25925487e-03]
 [5.71511193e-03 9.83880719e-01 1.04041686e-02]
 [4.09437789e-03 1.20848156e-03 9.94697141e-01]]
pi = [3.50703797e-01 4.90821691e-04 6.48805381e-01]
Iter 14: LL=-1245710.06 | Rates: N=0.82671, AF=0.09705, OLD=0.10166, YOUNG=0.03316
A =
[[9.94960448e-01 7.53797408e-04 4.28575503e-03]
 [5.79951499e-03 9.82769124e-01 1.14313610e-02]
 [4.09373253e-03 1.24828246e-03 9.94657985e-01]]
pi = [3.50713237e-01 2.59646779e-04 6.49027116e-01]
Iter 15: LL=-1245697.26 | Rates: N=0.82671, AF=0.09702, OLD=0.10512, YOUNG=0.03324
A =
[[9.94961664e-01 7.26882889e-04 4.31145346e-03]
 [5.88055955e-03 9.81607581e-01 1.25118591e-02]
 [4.09385871e-03 1.28543376e-03 9.94620708e-01]]
pi = [3.50719969e-01 1.37406654e-04 6.49142624e-01]
Final Global Rates (lambdas): [0.8267128  0.0970157  0.10511504 0.0332427 ]
Final transition matrix A:
[[9.94961664e-01 7.26882889e-04 4.31145346e-03]
 [5.88055955e-03 9.81607581e-01 1.25118591e-02]
 [4.09385871e-03 1.28543376e-03 9.94620708e-01]]
Final initial distribution pi:
[3.50719969e-01 1.37406654e-04 6.49142624e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1019  0.0294  0.0456    1442268.0   12714732.0  47607569.0
Archaic_young     0.9044  0.9702  0.9361  481497774.0   50889226.0  14806189.0
Modern            0.0000  0.0000  0.0000          0.0  453456000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         449831          129           2321
Archaic_old       362         1440          47283
Archaic_young    3263        12588         482783

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0000  0.0000  0.0000
Archaic_young     0.8826  0.9953  0.9356

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         428923            0           2771
Archaic_old       523            0          62331
Archaic_young    3516            0         501936

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1443153.09 | Rates: N=0.81806, AF=0.09727, OLD=0.04966, YOUNG=0.03869
A =
[[9.94084479e-01 7.93625239e-04 5.12189541e-03]
 [4.94269856e-03 9.90106039e-01 4.95126259e-03]
 [4.56258376e-03 7.19752686e-04 9.94717664e-01]]
pi = [0.64943805 0.06000053 0.29056142]
Iter 2: LL=-1243412.90 | Rates: N=0.81821, AF=0.09713, OLD=0.05728, YOUNG=0.03723
A =
[[9.94103885e-01 8.21449030e-04 5.07466633e-03]
 [4.81226173e-03 9.90551523e-01 4.63621539e-03]
 [4.55065819e-03 7.44836253e-04 9.94704506e-01]]
pi = [0.65593443 0.04814008 0.29592549]
Iter 3: LL=-1243284.07 | Rates: N=0.81821, AF=0.09708, OLD=0.06560, YOUNG=0.03557
A =
[[9.94110967e-01 8.62556413e-04 5.02647698e-03]
 [4.76308059e-03 9.90920582e-01 4.31633770e-03]
 [4.54813995e-03 7.83839653e-04 9.94668020e-01]]
pi = [0.65610101 0.03503293 0.30886606]
Iter 4: LL=-1243165.73 | Rates: N=0.81821, AF=0.09702, OLD=0.07182, YOUNG=0.03447
A =
[[9.94115669e-01 8.82822870e-04 5.00150765e-03]
 [4.95178336e-03 9.90736842e-01 4.31137513e-03]
 [4.50914682e-03 8.22875750e-04 9.94667977e-01]]
pi = [0.65599484 0.023265   0.32074016]
Iter 5: LL=-1243111.44 | Rates: N=0.81821, AF=0.09697, OLD=0.07625, YOUNG=0.03401
A =
[[9.94117175e-01 8.79564676e-04 5.00326050e-03]
 [5.28836857e-03 9.90126178e-01 4.58545375e-03]
 [4.45343020e-03 8.63681465e-04 9.94682888e-01]]
pi = [0.65588709 0.01454884 0.32956408]
Iter 6: LL=-1243085.71 | Rates: N=0.81821, AF=0.09694, OLD=0.07980, YOUNG=0.03389
A =
[[9.94117415e-01 8.61309688e-04 5.02127540e-03]
 [5.66171087e-03 9.89312950e-01 5.02533900e-03]
 [4.40202731e-03 9.06327259e-04 9.94691645e-01]]
pi = [0.65580763 0.00854635 0.33564602]
Iter 7: LL=-1243067.47 | Rates: N=0.81821, AF=0.09691, OLD=0.08298, YOUNG=0.03389
A =
[[9.94117437e-01 8.34615042e-04 5.04794813e-03]
 [6.01736688e-03 9.88416211e-01 5.56642225e-03]
 [4.36187889e-03 9.49162441e-04 9.94688959e-01]]
pi = [0.6557465  0.00465832 0.33959518]
Iter 8: LL=-1243051.77 | Rates: N=0.81821, AF=0.09688, OLD=0.08604, YOUNG=0.03394
A =
[[9.94117535e-01 8.03557202e-04 5.07890736e-03]
 [6.33612526e-03 9.87484700e-01 6.17917462e-03]
 [4.33298718e-03 9.91005425e-04 9.94676007e-01]]
pi = [0.65569897 0.00233536 0.34196566]
Iter 9: LL=-1243037.57 | Rates: N=0.81821, AF=0.09686, OLD=0.08904, YOUNG=0.03400
A =
[[9.94117781e-01 7.70665180e-04 5.11155428e-03]
 [6.61487084e-03 9.86535370e-01 6.84975914e-03]
 [4.31331499e-03 1.03117021e-03 9.94655515e-01]]
pi = [0.65566443 0.00107331 0.34326226]
Iter 10: LL=-1243024.52 | Rates: N=0.81821, AF=0.09684, OLD=0.09204, YOUNG=0.03407
A =
[[9.94118174e-01 7.37556029e-04 5.14427041e-03]
 [6.85704549e-03 9.85572668e-01 7.57028622e-03]
 [4.30062865e-03 1.06923875e-03 9.94630133e-01]]
pi = [6.55641966e-01 4.52746706e-04 3.43905287e-01]
Iter 11: LL=-1243012.47 | Rates: N=0.81821, AF=0.09682, OLD=0.09504, YOUNG=0.03413
A =
[[9.94118690e-01 7.05279153e-04 5.17603065e-03]
 [7.06828365e-03 9.84596831e-01 8.33488565e-03]
 [4.29302691e-03 1.10495153e-03 9.94602022e-01]]
pi = [6.55629582e-01 1.76013052e-04 3.44194405e-01]
Iter 12: LL=-1243001.33 | Rates: N=0.81821, AF=0.09680, OLD=0.09805, YOUNG=0.03419
A =
[[9.94119297e-01 6.74503470e-04 5.20619910e-03]
 [7.25456927e-03 9.83606965e-01 9.13846546e-03]
 [4.28902000e-03 1.13816411e-03 9.94572816e-01]]
pi = [6.55624851e-01 6.34423983e-05 3.44311707e-01]
Iter 13: LL=-1242991.03 | Rates: N=0.81821, AF=0.09678, OLD=0.10108, YOUNG=0.03425
A =
[[9.94119963e-01 6.45629066e-04 5.23440833e-03]
 [7.42155088e-03 9.82601937e-01 9.97651195e-03]
 [4.28747897e-03 1.16882269e-03 9.94543698e-01]]
pi = [6.55625580e-01 2.13497395e-05 3.44353070e-01]
Iter 14: LL=-1242981.49 | Rates: N=0.81821, AF=0.09676, OLD=0.10413, YOUNG=0.03432
A =
[[9.94120658e-01 6.18861313e-04 5.26048041e-03]
 [7.57433591e-03 9.81580481e-01 1.08451826e-02]
 [4.28756190e-03 1.19694204e-03 9.94515496e-01]]
pi = [6.55630059e-01 6.75842391e-06 3.44363183e-01]
Iter 15: LL=-1242972.65 | Rates: N=0.81820, AF=0.09673, OLD=0.10721, YOUNG=0.03438
A =
[[9.94121364e-01 5.94264412e-04 5.28437169e-03]
 [7.71745868e-03 9.80541126e-01 1.17414151e-02]
 [4.28864843e-03 1.22258307e-03 9.94488768e-01]]
pi = [6.55637035e-01 2.02797428e-06 3.44360938e-01]
Final Global Rates (lambdas): [0.81820483 0.09673401 0.10720873 0.03437579]
Final transition matrix A:
[[9.94121364e-01 5.94264412e-04 5.28437169e-03]
 [7.71745868e-03 9.80541126e-01 1.17414151e-02]
 [4.28864843e-03 1.22258307e-03 9.94488768e-01]]
Final initial distribution pi:
[6.55637035e-01 2.02797428e-06 3.44360938e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1836  0.0372  0.0618    2336229.0   10391771.0  60508318.0
Archaic_young     0.8844  0.9748  0.9274  490185640.0   64056360.0  12651136.0
Modern            0.0000  0.0000  0.0000          0.0  433030000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         428958           95           2641
Archaic_old       533         2336          59985
Archaic_young    3539        10297         491616

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old        0.000  0.0000  0.0000
Archaic_young      0.905  0.9949  0.9478

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         425798            0           3267
Archaic_old       573            0          49257
Archaic_young    3859            0         517246

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1443902.77 | Rates: N=0.81339, AF=0.09698, OLD=0.05251, YOUNG=0.04173
A =
[[9.93609540e-01 8.06079140e-04 5.58438086e-03]
 [5.41338385e-03 9.88587761e-01 5.99885532e-03]
 [4.87816321e-03 7.76828786e-04 9.94345008e-01]]
pi = [0.38824474 0.1121776  0.49957766]
Iter 2: LL=-1248152.40 | Rates: N=0.81354, AF=0.09698, OLD=0.06125, YOUNG=0.04010
A =
[[9.93658419e-01 8.43228236e-04 5.49835307e-03]
 [5.20129569e-03 9.89145814e-01 5.65289020e-03]
 [4.85113968e-03 7.98042608e-04 9.94350818e-01]]
pi = [0.38819204 0.10996342 0.50184453]
Iter 3: LL=-1247988.17 | Rates: N=0.81354, AF=0.09689, OLD=0.07217, YOUNG=0.03797
A =
[[9.93668685e-01 9.23083901e-04 5.40823111e-03]
 [4.97936338e-03 9.89847647e-01 5.17298989e-03]
 [4.86964298e-03 8.45453064e-04 9.94284904e-01]]
pi = [0.38828831 0.10233418 0.5093775 ]
Iter 4: LL=-1247794.99 | Rates: N=0.81354, AF=0.09674, OLD=0.08048, YOUNG=0.03634
A =
[[9.93675966e-01 9.91120146e-04 5.33291401e-03]
 [5.05965081e-03 9.89791905e-01 5.14844399e-03]
 [4.84539648e-03 8.94499022e-04 9.94260104e-01]]
pi = [0.38841781 0.08684365 0.52473854]
Iter 5: LL=-1247702.02 | Rates: N=0.81354, AF=0.09664, OLD=0.08608, YOUNG=0.03562
A =
[[9.93678832e-01 1.02638844e-03 5.29477924e-03]
 [5.34062880e-03 9.89092318e-01 5.56705296e-03]
 [4.79386143e-03 9.46273534e-04 9.94259865e-01]]
pi = [0.38858229 0.06944543 0.54197228]
Iter 6: LL=-1247663.64 | Rates: N=0.81354, AF=0.09659, OLD=0.09029, YOUNG=0.03540
A =
[[0.99367975 0.00103643 0.00528383]
 [0.00566219 0.98810918 0.00622863]
 [0.00474446 0.00100205 0.99425349]]
pi = [0.38875201 0.05428748 0.55696051]
Iter 7: LL=-1247639.25 | Rates: N=0.81354, AF=0.09655, OLD=0.09394, YOUNG=0.03537
A =
[[0.99368017 0.0010302  0.00528963]
 [0.00595931 0.98702066 0.00702003]
 [0.00470646 0.00105908 0.99423446]]
pi = [0.38892363 0.04207746 0.56899891]
Iter 8: LL=-1247619.01 | Rates: N=0.81354, AF=0.09652, OLD=0.09738, YOUNG=0.03541
A =
[[0.99368053 0.00101379 0.00530568]
 [0.00621686 0.98589184 0.0078913 ]
 [0.00467965 0.00111508 0.99420528]]
pi = [0.38908932 0.03242808 0.57848261]
Iter 9: LL=-1247600.97 | Rates: N=0.81353, AF=0.09649, OLD=0.10075, YOUNG=0.03548
A =
[[9.93680933e-01 9.91190882e-04 5.32787613e-03]
 [6.43668426e-03 9.84744095e-01 8.81922093e-03]
 [4.66158075e-03 1.16868271e-03 9.94169737e-01]]
pi = [0.38924224 0.02482718 0.58593058]
Iter 10: LL=-1247584.58 | Rates: N=0.81353, AF=0.09646, OLD=0.10410, YOUNG=0.03555
A =
[[9.93681413e-01 9.65027594e-04 5.35355945e-03]
 [6.62556990e-03 9.83583345e-01 9.79108545e-03]
 [4.64981924e-03 1.21912420e-03 9.94131057e-01]]
pi = [0.38937777 0.01884984 0.59177239]
Iter 11: LL=-1247569.62 | Rates: N=0.81353, AF=0.09644, OLD=0.10745, YOUNG=0.03564
A =
[[9.93681945e-01 9.37080421e-04 5.38097499e-03]
 [6.79108824e-03 9.82410449e-01 1.07984631e-02]
 [4.64240697e-03 1.26598243e-03 9.94091611e-01]]
pi = [0.38949361 0.01417006 0.59633633]
Iter 12: LL=-1247555.94 | Rates: N=0.81353, AF=0.09641, OLD=0.11082, YOUNG=0.03572
A =
[[9.93682493e-01 9.08559463e-04 5.40894786e-03]
 [6.94030351e-03 9.81224677e-01 1.18350197e-02]
 [4.63787782e-03 1.30907791e-03 9.94053044e-01]]
pi = [0.38958921 0.01053515 0.59987564]
Iter 13: LL=-1247543.41 | Rates: N=0.81353, AF=0.09639, OLD=0.11420, YOUNG=0.03580
A =
[[9.93683018e-01 8.80285448e-04 5.43669625e-03]
 [7.07943455e-03 9.80024708e-01 1.28958578e-02]
 [4.63516278e-03 1.34839473e-03 9.94016442e-01]]
pi = [0.38966529 0.00774223 0.60259248]
Iter 14: LL=-1247531.91 | Rates: N=0.81353, AF=0.09637, OLD=0.11761, YOUNG=0.03589
A =
[[9.93683483e-01 8.52806429e-04 5.46371037e-03]
 [7.21385151e-03 9.78808773e-01 1.39773759e-02]
 [4.63349625e-03 1.38402368e-03 9.93982480e-01]]
pi = [0.38972338 0.0056234  0.60465322]
Iter 15: LL=-1247521.31 | Rates: N=0.81353, AF=0.09634, OLD=0.12106, YOUNG=0.03597
A =
[[9.93683850e-01 8.26476070e-04 5.48967394e-03]
 [7.34820325e-03 9.77574514e-01 1.50772828e-02]
 [4.63233870e-03 1.41611680e-03 9.93951545e-01]]
pi = [0.3897655  0.00403777 0.60619674]
Final Global Rates (lambdas): [0.81352534 0.09634186 0.12105523 0.03597211]
Final transition matrix A:
[[9.93683850e-01 8.26476070e-04 5.48967394e-03]
 [7.34820325e-03 9.77574514e-01 1.50772828e-02]
 [4.63233870e-03 1.41611680e-03 9.93951545e-01]]
Final initial distribution pi:
[0.3897655  0.00403777 0.60619674]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1208  0.0353  0.0547    1759734.0   12809266.0  48053378.0
Archaic_young     0.9059  0.9704  0.9371  502908509.0   52231491.0  15337038.0
Modern            0.0000  0.0000  0.0000          0.0  430291000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         425860           90           3115
Archaic_old       527         1755          47548
Archaic_young    3904        12724         504477

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old        0.000   0.000  0.0000
Archaic_young      0.904   0.993  0.9464

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         438979            0           3421
Archaic_old       527            0          48206
Archaic_young    5002            0         503865

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1466593.89 | Rates: N=0.81766, AF=0.09918, OLD=0.05944, YOUNG=0.04809
A =
[[9.93140570e-01 8.47669916e-04 6.01175999e-03]
 [6.13497969e-03 9.87046245e-01 6.81877510e-03]
 [5.55827575e-03 8.66562332e-04 9.93575162e-01]]
pi = [0.59160881 0.0717631  0.33662809]
Iter 2: LL=-1266190.15 | Rates: N=0.81781, AF=0.09930, OLD=0.06953, YOUNG=0.04623
A =
[[9.93211474e-01 8.89036600e-04 5.89948924e-03]
 [6.02353689e-03 9.87440605e-01 6.53585830e-03]
 [5.49599716e-03 8.83412394e-04 9.93620590e-01]]
pi = [0.60011078 0.06271086 0.33717835]
Iter 3: LL=-1265999.62 | Rates: N=0.81780, AF=0.09920, OLD=0.08386, YOUNG=0.04370
A =
[[9.93224792e-01 9.95634323e-04 5.77957360e-03]
 [5.90328659e-03 9.88009103e-01 6.08761056e-03]
 [5.49028132e-03 9.33595431e-04 9.93576123e-01]]
pi = [0.60042706 0.04671895 0.35285399]
Iter 4: LL=-1265728.81 | Rates: N=0.81780, AF=0.09894, OLD=0.09613, YOUNG=0.04165
A =
[[9.93237381e-01 1.10005508e-03 5.66256356e-03]
 [6.13312780e-03 9.87658246e-01 6.20862668e-03]
 [5.43211256e-03 9.89125929e-04 9.93578762e-01]]
pi = [0.60046536 0.02472976 0.37480489]
Iter 5: LL=-1265572.52 | Rates: N=0.81779, AF=0.09872, OLD=0.10534, YOUNG=0.04077
A =
[[0.99324344 0.00115986 0.00559671]
 [0.00662521 0.98641578 0.00695901]
 [0.00534901 0.00104842 0.99360257]]
pi = [0.60041434 0.00964241 0.38994325]
Iter 6: LL=-1265495.99 | Rates: N=0.81778, AF=0.09855, OLD=0.11305, YOUNG=0.04054
A =
[[0.99324488 0.00117976 0.00557536]
 [0.00716822 0.98474018 0.0080916 ]
 [0.00528001 0.00111339 0.99360661]]
pi = [0.60038504 0.00320295 0.39641201]
Iter 7: LL=-1265441.95 | Rates: N=0.81778, AF=0.09839, OLD=0.12043, YOUNG=0.04057
A =
[[0.99324478 0.00117244 0.00558278]
 [0.00767472 0.98285686 0.00946841]
 [0.00523268 0.00118022 0.9935871 ]]
pi = [0.60039519 0.00099026 0.39861455]
Iter 8: LL=-1265394.06 | Rates: N=0.81778, AF=0.09824, OLD=0.12807, YOUNG=0.04069
A =
[[0.99324437 0.00114747 0.00560816]
 [0.00813334 0.98082146 0.01104519]
 [0.005203   0.00124493 0.99355206]]
pi = [6.00415401e-01 2.94759793e-04 3.99289839e-01]
Iter 9: LL=-1265348.43 | Rates: N=0.81777, AF=0.09811, OLD=0.13617, YOUNG=0.04085
A =
[[0.99324395 0.00111175 0.0056443 ]
 [0.00855707 0.97862661 0.01281632]
 [0.0051858  0.0013046  0.9935096 ]]
pi = [6.00434889e-01 8.54864126e-05 3.99479625e-01]
Iter 10: LL=-1265304.02 | Rates: N=0.81776, AF=0.09799, OLD=0.14490, YOUNG=0.04103
A =
[[0.9932434  0.00107075 0.00568585]
 [0.00896205 0.97625233 0.01478562]
 [0.00517707 0.00135729 0.99346564]]
pi = [6.00452217e-01 2.42930506e-05 3.99523490e-01]
Iter 11: LL=-1265260.34 | Rates: N=0.81776, AF=0.09787, OLD=0.15444, YOUNG=0.04123
A =
[[0.99324231 0.00102871 0.00572898]
 [0.0093662  0.97367454 0.01695927]
 [0.00517382 0.00140189 0.99342429]]
pi = [6.00467380e-01 6.78910038e-06 3.99525831e-01]
Iter 12: LL=-1265216.68 | Rates: N=0.81775, AF=0.09773, OLD=0.16510, YOUNG=0.04145
A =
[[9.93240043e-01 9.88716352e-04 5.77124036e-03]
 [9.79351600e-03 9.70859556e-01 1.93469278e-02]
 [5.17366875e-03 1.43791602e-03 9.93388415e-01]]
pi = [6.00480358e-01 1.87048327e-06 3.99517772e-01]
Iter 13: LL=-1265171.77 | Rates: N=0.81774, AF=0.09756, OLD=0.17731, YOUNG=0.04167
A =
[[9.93235953e-01 9.52687576e-04 5.81135923e-03]
 [1.02762113e-02 9.67756234e-01 2.19675543e-02]
 [5.17474197e-03 1.46512628e-03 9.93360132e-01]]
pi = [6.00491202e-01 5.08613055e-07 3.99508289e-01]
Iter 14: LL=-1265124.08 | Rates: N=0.81772, AF=0.09736, OLD=0.19141, YOUNG=0.04190
A =
[[9.93230447e-01 9.20742561e-04 5.84881029e-03]
 [1.08443645e-02 9.64296777e-01 2.48588584e-02]
 [5.17565622e-03 1.48331688e-03 9.93341027e-01]]
pi = [6.00500144e-01 1.36462959e-07 3.99499719e-01]
Iter 15: LL=-1265073.07 | Rates: N=0.81770, AF=0.09717, OLD=0.20751, YOUNG=0.04214
A =
[[9.93224590e-01 8.92012883e-04 5.88339702e-03]
 [1.15139153e-02 9.60422228e-01 2.80638564e-02]
 [5.17588687e-03 1.49287023e-03 9.93331243e-01]]
pi = [6.00507683e-01 3.61251803e-08 3.99492281e-01]
Final Global Rates (lambdas): [0.81770216 0.09717234 0.20751182 0.04214088]
Final transition matrix A:
[[9.93224590e-01 8.92012883e-04 5.88339702e-03]
 [1.15139153e-02 9.60422228e-01 2.80638564e-02]
 [5.17588687e-03 1.49287023e-03 9.93331243e-01]]
Final initial distribution pi:
[6.00507683e-01 3.61251803e-08 3.99492281e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.0809  0.0174  0.0286     846636.0    9621364.0  47855486.0
Archaic_young     0.9043  0.9755  0.9386  493311143.0   52186857.0  12393614.0
Modern            0.0000  0.0000  0.0000          0.0  444034000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         438757          489           3154
Archaic_old       492          847          47394
Archaic_young    4785         9132         494950

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0000  0.0000  0.0000
Archaic_young     0.9019  0.9919  0.9447

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         441709            0           3398
Archaic_old       702            0          48934
Archaic_young    5641            0         499616

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1478525.29 | Rates: N=0.81864, AF=0.09850, OLD=0.06587, YOUNG=0.05413
A =
[[9.92782423e-01 8.66081318e-04 6.35149552e-03]
 [6.52621014e-03 9.85864326e-01 7.60946337e-03]
 [5.96046511e-03 9.57828104e-04 9.93081707e-01]]
pi = [0.20596988 0.14625636 0.64777377]
Iter 2: LL=-1277001.11 | Rates: N=0.81881, AF=0.09858, OLD=0.07701, YOUNG=0.05211
A =
[[9.92891586e-01 8.96420889e-04 6.21199350e-03]
 [6.40153551e-03 9.86384130e-01 7.21433495e-03]
 [5.86299069e-03 9.83657480e-04 9.93153352e-01]]
pi = [0.19911421 0.14992165 0.65096414]
Iter 3: LL=-1276788.81 | Rates: N=0.81880, AF=0.09850, OLD=0.09311, YOUNG=0.04914
A =
[[0.99290889 0.00099614 0.00609497]
 [0.006272   0.98725717 0.00647083]
 [0.00585338 0.00105813 0.99308848]]
pi = [0.19892148 0.15313846 0.64794006]
Iter 4: LL=-1276475.43 | Rates: N=0.81879, AF=0.09833, OLD=0.10583, YOUNG=0.04666
A =
[[0.99292171 0.00109249 0.0059858 ]
 [0.00655633 0.98713317 0.00631049]
 [0.00578299 0.00114786 0.99306914]]
pi = [0.19892835 0.1544701  0.64660155]
Iter 5: LL=-1276310.86 | Rates: N=0.81877, AF=0.09815, OLD=0.11451, YOUNG=0.04553
A =
[[0.99292643 0.00114722 0.00592635]
 [0.00714853 0.98604006 0.00681141]
 [0.00567638 0.00124704 0.99307658]]
pi = [0.19892151 0.1560748  0.64500369]
Iter 6: LL=-1276241.21 | Rates: N=0.81876, AF=0.09802, OLD=0.12113, YOUNG=0.04517
A =
[[0.99292667 0.00116679 0.00590654]
 [0.00779664 0.98451692 0.00768645]
 [0.00558139 0.00135232 0.99306629]]
pi = [0.19887748 0.15838871 0.64273381]
Iter 7: LL=-1276197.19 | Rates: N=0.81876, AF=0.09792, OLD=0.12690, YOUNG=0.04510
A =
[[0.99292554 0.00116309 0.00591137]
 [0.00839307 0.98283407 0.00877286]
 [0.00551101 0.00145721 0.99303177]]
pi = [0.19880614 0.16047269 0.64072118]
Iter 8: LL=-1276161.34 | Rates: N=0.81875, AF=0.09783, OLD=0.13240, YOUNG=0.04514
A =
[[0.99292433 0.00114506 0.00593061]
 [0.00891115 0.98109033 0.00999852]
 [0.00546285 0.00155795 0.9929792 ]]
pi = [0.19872319 0.16147534 0.63980147]
Iter 9: LL=-1276129.69 | Rates: N=0.81875, AF=0.09775, OLD=0.13786, YOUNG=0.04521
A =
[[0.99292332 0.00111863 0.00595805]
 [0.00935628 0.97931174 0.01133197]
 [0.0054315  0.00165262 0.99291588]]
pi = [0.19864178 0.16084137 0.64051685]
Iter 10: LL=-1276100.80 | Rates: N=0.81874, AF=0.09767, OLD=0.14343, YOUNG=0.04530
A =
[[0.99292248 0.00108767 0.00598985]
 [0.00974449 0.97749633 0.01275918]
 [0.00541205 0.00174031 0.99284765]]
pi = [0.19857069 0.15829862 0.64313069]
Iter 11: LL=-1276073.84 | Rates: N=0.81874, AF=0.09758, OLD=0.14921, YOUNG=0.04539
A =
[[0.99292163 0.00105469 0.00602368]
 [0.01009477 0.97563041 0.01427481]
 [0.00540059 0.00182061 0.99277879]]
pi = [0.19851477 0.15379702 0.64768821]
Iter 12: LL=-1276048.12 | Rates: N=0.81873, AF=0.09749, OLD=0.15533, YOUNG=0.04550
A =
[[0.9929205  0.00102136 0.00605815]
 [0.01042664 0.97369427 0.01587908]
 [0.00539427 0.00189334 0.99271239]]
pi = [0.19847582 0.14743372 0.65409046]
Iter 13: LL=-1276023.01 | Rates: N=0.81872, AF=0.09739, OLD=0.16193, YOUNG=0.04562
A =
[[9.92918746e-01 9.88787810e-04 6.09246633e-03]
 [1.07597124e-02 9.71663541e-01 1.75767470e-02]
 [5.39101084e-03 1.95828732e-03 9.92650702e-01]]
pi = [0.19845361 0.13938287 0.66216352]
Iter 14: LL=-1275997.85 | Rates: N=0.81871, AF=0.09726, OLD=0.16915, YOUNG=0.04575
A =
[[9.92916054e-01 9.57743860e-04 6.12620180e-03]
 [1.11137923e-02 9.69508780e-01 1.93774280e-02]
 [5.38931378e-03 2.01515151e-03 9.92595535e-01]]
pi = [0.19844675 0.12984209 0.67171116]
Iter 15: LL=-1275971.95 | Rates: N=0.81870, AF=0.09712, OLD=0.17717, YOUNG=0.04589
A =
[[9.92912296e-01 9.28599010e-04 6.15910546e-03]
 [1.15077889e-02 9.67196310e-01 2.12959008e-02]
 [5.38812817e-03 2.06352936e-03 9.92548342e-01]]
pi = [0.19845361 0.11900576 0.68254063]
Final Global Rates (lambdas): [0.8186993  0.09712332 0.17716603 0.04588665]
Final transition matrix A:
[[9.92912296e-01 9.28599010e-04 6.15910546e-03]
 [1.15077889e-02 9.67196310e-01 2.12959008e-02]
 [5.38812817e-03 2.06352936e-03 9.92548342e-01]]
Final initial distribution pi:
[0.19845361 0.11900576 0.68254063]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1137  0.0341  0.0525    1692945.0   13193055.0  47912251.0
Archaic_young     0.9029  0.9666  0.9337  485110107.0   52145893.0  16772078.0
Modern            0.0000  0.0000  0.0000          0.0  447858000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         441631          325           3151
Archaic_old       692         1694          47250
Archaic_young    5535        12867         486855

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0962  0.0801  0.0874
Archaic_young     0.9113  0.9268  0.9190

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         453502          174           2394
Archaic_old       469         3610          41217
Archaic_young    3641        33834         461159

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1451640.92 | Rates: N=0.82220, AF=0.09799, OLD=0.05668, YOUNG=0.03504
A =
[[9.94796629e-01 1.15981539e-03 4.04355585e-03]
 [4.46360895e-03 9.92577361e-01 2.95902978e-03]
 [4.50306621e-03 8.79403664e-04 9.94617530e-01]]
pi = [0.4044656  0.15784331 0.4376911 ]
Iter 2: LL=-1247035.13 | Rates: N=0.82235, AF=0.09767, OLD=0.06340, YOUNG=0.03311
A =
[[9.94812319e-01 1.17611448e-03 4.01156630e-03]
 [4.53251885e-03 9.92505328e-01 2.96215363e-03]
 [4.44946345e-03 9.04963950e-04 9.94645573e-01]]
pi = [0.40388005 0.15639388 0.43972606]
Iter 3: LL=-1246917.28 | Rates: N=0.82235, AF=0.09757, OLD=0.06852, YOUNG=0.03211
A =
[[9.94816614e-01 1.17004298e-03 4.01334260e-03]
 [4.73661498e-03 9.92066060e-01 3.19732520e-03]
 [4.38644287e-03 9.44265246e-04 9.94669292e-01]]
pi = [0.40391306 0.1446988  0.45138814]
Iter 4: LL=-1246862.66 | Rates: N=0.82235, AF=0.09751, OLD=0.07244, YOUNG=0.03176
A =
[[0.99481842 0.00114325 0.00403834]
 [0.00496885 0.99142014 0.00361101]
 [0.0043286  0.0009965  0.99467489]]
pi = [0.40394573 0.1288098  0.46724447]
Iter 5: LL=-1246830.44 | Rates: N=0.82235, AF=0.09746, OLD=0.07579, YOUNG=0.03171
A =
[[0.99481936 0.00110329 0.00407735]
 [0.00518065 0.99067519 0.00414415]
 [0.00428709 0.00105424 0.99465866]]
pi = [0.40396307 0.11199388 0.48404304]
Iter 6: LL=-1246804.35 | Rates: N=0.82235, AF=0.09742, OLD=0.07894, YOUNG=0.03177
A =
[[0.99482011 0.00105635 0.00412354]
 [0.00535837 0.98987837 0.00476326]
 [0.00426104 0.00111233 0.99462663]]
pi = [0.40397571 0.09531313 0.50071116]
Iter 7: LL=-1246780.61 | Rates: N=0.82235, AF=0.09739, OLD=0.08206, YOUNG=0.03187
A =
[[0.99482087 0.0010066  0.00417253]
 [0.00550312 0.98904533 0.00545155]
 [0.00424657 0.00116821 0.99458522]]
pi = [0.40398741 0.07907978 0.51693281]
Iter 8: LL=-1246758.41 | Rates: N=0.82235, AF=0.09736, OLD=0.08521, YOUNG=0.03197
A =
[[9.94821682e-01 9.56681633e-04 4.22163642e-03]
 [5.62061696e-03 9.88179730e-01 6.19965336e-03]
 [4.23999179e-03 1.22065619e-03 9.94539352e-01]]
pi = [0.40399763 0.06353396 0.53246842]
Iter 9: LL=-1246737.59 | Rates: N=0.82235, AF=0.09734, OLD=0.08842, YOUNG=0.03209
A =
[[9.94822545e-01 9.08191801e-04 4.26926366e-03]
 [5.71722456e-03 9.87282042e-01 7.00073385e-03]
 [4.23849517e-03 1.26909477e-03 9.94492410e-01]]
pi = [0.40400442 0.04904532 0.54695026]
Iter 10: LL=-1246718.13 | Rates: N=0.82235, AF=0.09731, OLD=0.09170, YOUNG=0.03220
A =
[[9.94823446e-01 8.62076787e-04 4.31447704e-03]
 [5.79872256e-03 9.86352673e-01 7.84860395e-03]
 [4.24006333e-03 1.31328511e-03 9.94446652e-01]]
pi = [0.40400605 0.03610038 0.55989357]
Iter 11: LL=-1246700.07 | Rates: N=0.82235, AF=0.09728, OLD=0.09503, YOUNG=0.03231
A =
[[9.94824374e-01 8.18845790e-04 4.35678055e-03]
 [5.87004985e-03 9.85392603e-01 8.73734752e-03]
 [4.24329967e-03 1.35319656e-03 9.94403504e-01]]
pi = [0.40400182 0.02517504 0.57082314]
Iter 12: LL=-1246683.40 | Rates: N=0.82235, AF=0.09726, OLD=0.09841, YOUNG=0.03243
A =
[[9.94825318e-01 7.78714909e-04 4.39596742e-03]
 [5.93532910e-03 9.84403173e-01 9.66149778e-03]
 [4.24725986e-03 1.38893368e-03 9.94363806e-01]]
pi = [0.40399244 0.01656509 0.57944247]
Iter 13: LL=-1246668.07 | Rates: N=0.82235, AF=0.09724, OLD=0.10184, YOUNG=0.03254
A =
[[9.94826272e-01 7.41700950e-04 4.43202683e-03]
 [5.99794782e-03 9.83385727e-01 1.06163255e-02]
 [4.25132794e-03 1.42068373e-03 9.94327988e-01]]
pi = [0.40397967 0.01027146 0.58574887]
Iter 14: LL=-1246654.01 | Rates: N=0.82234, AF=0.09721, OLD=0.10531, YOUNG=0.03265
A =
[[9.94827233e-01 7.07688438e-04 4.46507890e-03]
 [6.06063901e-03 9.82341318e-01 1.15980432e-02]
 [4.25512534e-03 1.44867453e-03 9.94296200e-01]]
pi = [0.40396564 0.00601013 0.59002422]
Iter 15: LL=-1246641.10 | Rates: N=0.82234, AF=0.09719, OLD=0.10882, YOUNG=0.03276
A =
[[9.94828194e-01 6.76479707e-04 4.49532585e-03]
 [6.12555638e-03 9.81270578e-01 1.26038660e-02]
 [4.25844238e-03 1.47314223e-03 9.94268415e-01]]
pi = [0.4039521  0.00332961 0.5927183 ]
Final Global Rates (lambdas): [0.82234341 0.09718606 0.10882468 0.03276332]
Final transition matrix A:
[[9.94828194e-01 6.76479707e-04 4.49532585e-03]
 [6.12555638e-03 9.81270578e-01 1.26038660e-02]
 [4.25844238e-03 1.47314223e-03 9.94268415e-01]]
Final initial distribution pi:
[0.4039521  0.00332961 0.5927183 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1019  0.0416  0.0591    1879580.0   16565420.0  43310334.0
Archaic_young     0.9112  0.9624  0.9361  477635415.0   46571585.0  18668548.0
Modern            0.0000  0.0000  0.0000          0.0  457348000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         453507          138           2425
Archaic_old       482         1880          42934
Archaic_young    3359        16427         478848

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1882  0.0404  0.0665
Archaic_young     0.9017  0.9773  0.9380

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         439631           52           2931
Archaic_old       648         2091          49195
Archaic_young    3627         8982         492843

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 10
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1449389.80 | Rates: N=0.81825, AF=0.09881, OLD=0.05857, YOUNG=0.03743
A =
[[9.94051728e-01 1.11887091e-03 4.82940105e-03]
 [5.43364379e-03 9.90382758e-01 4.18359778e-03]
 [4.73475421e-03 8.40624409e-04 9.94424621e-01]]
pi = [0.64907717 0.07309041 0.27783243]
Iter 2: LL=-1248710.80 | Rates: N=0.81840, AF=0.09868, OLD=0.06710, YOUNG=0.03528
A =
[[9.94078368e-01 1.18521161e-03 4.73642060e-03]
 [5.46993207e-03 9.90480245e-01 4.04982247e-03]
 [4.68216434e-03 8.57248423e-04 9.94460587e-01]]
pi = [0.65056809 0.06786657 0.28156534]
Iter 3: LL=-1248558.07 | Rates: N=0.81840, AF=0.09856, OLD=0.07370, YOUNG=0.03399
A =
[[9.94084484e-01 1.23393179e-03 4.68158411e-03]
 [5.66342759e-03 9.90150528e-01 4.18604481e-03]
 [4.63223437e-03 8.83570789e-04 9.94484195e-01]]
pi = [0.65057649 0.06040759 0.28901592]
Iter 4: LL=-1248488.62 | Rates: N=0.81840, AF=0.09846, OLD=0.07839, YOUNG=0.03347
A =
[[9.94087565e-01 1.24738431e-03 4.66505110e-03]
 [5.93777608e-03 9.89473980e-01 4.58824355e-03]
 [4.58031771e-03 9.18347208e-04 9.94501335e-01]]
pi = [0.65057593 0.05189354 0.29753054]
Iter 5: LL=-1248456.73 | Rates: N=0.81840, AF=0.09839, OLD=0.08207, YOUNG=0.03335
A =
[[9.94088909e-01 1.23594867e-03 4.67514228e-03]
 [6.21433623e-03 9.88632736e-01 5.15292749e-03]
 [4.54089184e-03 9.58928305e-04 9.94500180e-01]]
pi = [0.65057474 0.0436042  0.30582106]
Iter 6: LL=-1248434.74 | Rates: N=0.81840, AF=0.09835, OLD=0.08536, YOUNG=0.03339
A =
[[0.99408973 0.00120951 0.00470076]
 [0.00646105 0.98772377 0.00581517]
 [0.00451524 0.00100198 0.99448278]]
pi = [0.65057463 0.03574592 0.31367945]
Iter 7: LL=-1248415.76 | Rates: N=0.81840, AF=0.09832, OLD=0.08851, YOUNG=0.03347
A =
[[0.99409048 0.00117446 0.00473506]
 [0.00667354 0.98678126 0.0065452 ]
 [0.00450028 0.00104552 0.99445421]]
pi = [0.65057554 0.02832337 0.32110109]
Iter 8: LL=-1248398.26 | Rates: N=0.81840, AF=0.09829, OLD=0.09166, YOUNG=0.03358
A =
[[0.99409129 0.00113473 0.00477398]
 [0.00685773 0.98581103 0.00733124]
 [0.00449263 0.00108844 0.99441892]]
pi = [0.65057689 0.02146204 0.32796107]
Iter 9: LL=-1248381.77 | Rates: N=0.81840, AF=0.09826, OLD=0.09487, YOUNG=0.03368
A =
[[0.99409216 0.00109284 0.00481501]
 [0.00702171 0.98480897 0.00816931]
 [0.0044897  0.00113008 0.99438022]]
pi = [0.65057813 0.01540822 0.33401365]
Iter 10: LL=-1248366.09 | Rates: N=0.81840, AF=0.09823, OLD=0.09815, YOUNG=0.03379
A =
[[0.99409308 0.00105042 0.0048565 ]
 [0.0071727  0.98376891 0.00905839]
 [0.00448968 0.00116992 0.99434039]]
pi = [0.65057892 0.01041713 0.33900395]
Iter 11: LL=-1248351.12 | Rates: N=0.81839, AF=0.09821, OLD=0.10154, YOUNG=0.03389
A =
[[0.99409402 0.00100857 0.00489741]
 [0.00731621 0.98268565 0.00999815]
 [0.0044914  0.00120761 0.994301  ]]
pi = [0.65057929 0.00662353 0.34279718]
Iter 12: LL=-1248336.81 | Rates: N=0.81839, AF=0.09819, OLD=0.10503, YOUNG=0.03400
A =
[[9.94094973e-01 9.67992251e-04 4.93703471e-03]
 [7.45611910e-03 9.81555923e-01 1.09879578e-02]
 [4.49411348e-03 1.24283691e-03 9.94263050e-01]]
pi = [0.65057949 0.00397617 0.34544434]
Iter 13: LL=-1248323.15 | Rates: N=0.81839, AF=0.09816, OLD=0.10863, YOUNG=0.03411
A =
[[9.94095908e-01 9.29153494e-04 4.97493825e-03]
 [7.59502120e-03 9.80378435e-01 1.20265434e-02]
 [4.49737360e-03 1.27541674e-03 9.94227210e-01]]
pi = [0.65057979 0.00227206 0.34714814]
Iter 14: LL=-1248310.13 | Rates: N=0.81839, AF=0.09814, OLD=0.11234, YOUNG=0.03421
A =
[[9.94096815e-01 8.92334523e-04 5.01085063e-03]
 [7.73468138e-03 9.79153187e-01 1.31121317e-02]
 [4.50089127e-03 1.30522049e-03 9.94193888e-01]]
pi = [0.65058036 0.00124912 0.34817052]
Iter 15: LL=-1248297.73 | Rates: N=0.81839, AF=0.09811, OLD=0.11617, YOUNG=0.03431
A =
[[9.94097682e-01 8.57693359e-04 5.04462477e-03]
 [7.87646258e-03 9.77880561e-01 1.42429761e-02]
 [4.50447921e-03 1.33218670e-03 9.94163334e-01]]
pi = [0.65058122 0.00066834 0.34875044]
Final Global Rates (lambdas): [0.81838765 0.09811408 0.11617391 0.03431418]
Final transition matrix A:
[[9.94097682e-01 8.57693359e-04 5.04462477e-03]
 [7.87646258e-03 9.77880561e-01 1.42429761e-02]
 [4.50447921e-03 1.33218670e-03 9.94163334e-01]]
Final initial distribution pi:
[0.65058122 0.00066834 0.34875044]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1860  0.0553  0.0853    2868979.0   12556021.0  48996894.0
Archaic_young     0.9027  0.9703  0.9353  487904827.0   52561173.0  14931949.0
Modern            0.0000  0.0000  0.0000          0.0  444109000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         439711          142           2761
Archaic_old       680         2864          48390
Archaic_young    3718        12419         489315

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old        0.130  0.0193  0.0337
Archaic_young      0.926  0.9854  0.9548

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         438360           14           3001
Archaic_old       538          723          36259
Archaic_young    4072         4835         512198

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1454014.74 | Rates: N=0.81975, AF=0.09726, OLD=0.06158, YOUNG=0.04055
A =
[[9.93634932e-01 1.05686326e-03 5.30820462e-03]
 [5.94989100e-03 9.88838781e-01 5.21132837e-03]
 [5.04692353e-03 8.77386782e-04 9.94075690e-01]]
pi = [0.49432711 0.09316007 0.41251282]
Iter 2: LL=-1252993.40 | Rates: N=0.81993, AF=0.09720, OLD=0.07156, YOUNG=0.03812
A =
[[9.93683505e-01 1.11944229e-03 5.19705298e-03]
 [5.77893045e-03 9.89312637e-01 4.90843285e-03]
 [5.00881337e-03 9.07579288e-04 9.94083607e-01]]
pi = [0.49711772 0.07849343 0.42438885]
Iter 3: LL=-1252806.24 | Rates: N=0.81992, AF=0.09711, OLD=0.07940, YOUNG=0.03644
A =
[[9.93691689e-01 1.17862477e-03 5.12968590e-03]
 [5.82279476e-03 9.89248383e-01 4.92882197e-03]
 [4.98494085e-03 9.50380673e-04 9.94064678e-01]]
pi = [0.49720094 0.06172689 0.44107217]
Iter 4: LL=-1252716.64 | Rates: N=0.81991, AF=0.09704, OLD=0.08465, YOUNG=0.03568
A =
[[0.99369607 0.00120376 0.00510017]
 [0.00601773 0.98866369 0.00531858]
 [0.00494503 0.00099794 0.99405703]]
pi = [0.49718254 0.04626632 0.45655114]
Iter 5: LL=-1252680.80 | Rates: N=0.81991, AF=0.09698, OLD=0.08852, YOUNG=0.03543
A =
[[0.99369866 0.00120459 0.00509675]
 [0.00623685 0.98784901 0.00591414]
 [0.00491015 0.00104904 0.99404081]]
pi = [0.49716995 0.03399506 0.46883498]
Iter 6: LL=-1252659.43 | Rates: N=0.81991, AF=0.09694, OLD=0.09176, YOUNG=0.03538
A =
[[0.9937004  0.00119089 0.00510871]
 [0.00642885 0.98695641 0.00661473]
 [0.00488641 0.00110034 0.99401325]]
pi = [0.4971699  0.02486485 0.47796525]
Iter 7: LL=-1252642.41 | Rates: N=0.81990, AF=0.09691, OLD=0.09472, YOUNG=0.03542
A =
[[0.99370182 0.001169   0.00512917]
 [0.00658277 0.9860449  0.00737233]
 [0.00487251 0.00114995 0.99397754]]
pi = [0.49717584 0.01824998 0.48457418]
Iter 8: LL=-1252627.59 | Rates: N=0.81990, AF=0.09688, OLD=0.09756, YOUNG=0.03548
A =
[[0.99370318 0.00114271 0.00515411]
 [0.0067025  0.98513239 0.00816511]
 [0.00486568 0.00119702 0.9939373 ]]
pi = [0.49718299 0.01348846 0.48932855]
Iter 9: LL=-1252614.33 | Rates: N=0.81990, AF=0.09685, OLD=0.10034, YOUNG=0.03555
A =
[[0.99370456 0.00111425 0.00518119]
 [0.00679585 0.98422083 0.00898332]
 [0.00486346 0.00124125 0.99389529]]
pi = [0.49718932 0.01004562 0.49276507]
Iter 10: LL=-1252602.29 | Rates: N=0.81990, AF=0.09683, OLD=0.10311, YOUNG=0.03562
A =
[[0.993706   0.00108497 0.00520903]
 [0.0068705  0.98330664 0.00982286]
 [0.00486406 0.00128252 0.99385342]]
pi = [0.49719431 0.00753139 0.4952743 ]
Iter 11: LL=-1252591.22 | Rates: N=0.81990, AF=0.09680, OLD=0.10589, YOUNG=0.03570
A =
[[0.99370748 0.00105566 0.00523686]
 [0.00693289 0.98238469 0.01068243]
 [0.00486626 0.00132082 0.99381292]]
pi = [0.49719812 0.00567331 0.49712857]
Iter 12: LL=-1252580.96 | Rates: N=0.81989, AF=0.09678, OLD=0.10869, YOUNG=0.03578
A =
[[0.99370895 0.00102677 0.00526428]
 [0.00698816 0.98145008 0.01156176]
 [0.00486929 0.0013562  0.99377451]]
pi = [0.49720104 0.00428413 0.49851482]
Iter 13: LL=-1252571.38 | Rates: N=0.81989, AF=0.09675, OLD=0.11151, YOUNG=0.03586
A =
[[0.99371036 0.00099858 0.00529106]
 [0.00704025 0.9804993  0.01246046]
 [0.00487267 0.00138876 0.99373857]]
pi = [0.49720338 0.00323536 0.49956126]
Iter 14: LL=-1252562.44 | Rates: N=0.81989, AF=0.09673, OLD=0.11435, YOUNG=0.03594
A =
[[9.93711647e-01 9.71289443e-04 5.31706384e-03]
 [7.09192299e-03 9.79530709e-01 1.33773677e-02]
 [4.87606765e-03 1.41867790e-03 9.93705254e-01]]
pi = [0.49720535 0.00243802 0.50035663]
Iter 15: LL=-1252554.10 | Rates: N=0.81989, AF=0.09671, OLD=0.11721, YOUNG=0.03602
A =
[[9.93712813e-01 9.45031161e-04 5.34215633e-03]
 [7.14503601e-03 9.78544192e-01 1.43107719e-02]
 [4.87929159e-03 1.44615661e-03 9.93674552e-01]]
pi = [0.49720714 0.00182946 0.5009634 ]
Final Global Rates (lambdas): [0.81988577 0.09671259 0.11720835 0.0360201 ]
Final transition matrix A:
[[9.93712813e-01 9.45031161e-04 5.34215633e-03]
 [7.14503601e-03 9.78544192e-01 1.43107719e-02]
 [4.87929159e-03 1.44615661e-03 9.93674552e-01]]
Final initial distribution pi:
[0.49720714 0.00182946 0.5009634 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1169  0.0526  0.0726    1970081.0   14878919.0  35489939.0
Archaic_young     0.9273  0.9664  0.9464  500830586.0   39291414.0  17414961.0
Modern            0.0000  0.0000  0.0000          0.0  443029000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         438414          152           2809
Archaic_old       556         1969          34995
Archaic_young    4059        14728         502318

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0023  0.0002  0.0003
Archaic_young     0.9227  0.9875  0.9540

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         450221           18           3326
Archaic_old       735            5          36828
Archaic_young    5192         2609         501066

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1469780.05 | Rates: N=0.82081, AF=0.09806, OLD=0.06799, YOUNG=0.04655
A =
[[9.93335011e-01 1.06632567e-03 5.59866342e-03]
 [6.60660813e-03 9.87388499e-01 6.00489335e-03]
 [5.58634834e-03 9.66778373e-04 9.93446873e-01]]
pi = [0.50263422 0.09361067 0.40375511]
Iter 2: LL=-1267070.36 | Rates: N=0.82098, AF=0.09810, OLD=0.07956, YOUNG=0.04380
A =
[[0.99341636 0.0011464  0.00543724]
 [0.00651242 0.98787501 0.00561257]
 [0.00549773 0.00099851 0.99350376]]
pi = [0.50525614 0.08211594 0.41262792]
Iter 3: LL=-1266843.54 | Rates: N=0.82097, AF=0.09797, OLD=0.08952, YOUNG=0.04160
A =
[[0.99342946 0.00125162 0.00531892]
 [0.00664404 0.98786482 0.00549114]
 [0.00544366 0.00105564 0.9935007 ]]
pi = [0.50523152 0.06735294 0.42741555]
Iter 4: LL=-1266709.76 | Rates: N=0.82096, AF=0.09783, OLD=0.09631, YOUNG=0.04045
A =
[[0.99343568 0.0013251  0.00523922]
 [0.00700572 0.98714262 0.00585166]
 [0.00536426 0.00112452 0.99351121]]
pi = [0.50514048 0.05388699 0.44097252]
Iter 5: LL=-1266653.45 | Rates: N=0.82095, AF=0.09772, OLD=0.10119, YOUNG=0.04000
A =
[[0.99343849 0.00136675 0.00519477]
 [0.00743058 0.98605093 0.00651848]
 [0.00528986 0.00120424 0.9935059 ]]
pi = [0.505126   0.04402381 0.45085019]
Iter 6: LL=-1266621.26 | Rates: N=0.82095, AF=0.09764, OLD=0.10520, YOUNG=0.03985
A =
[[0.99343978 0.00138541 0.00517481]
 [0.00782839 0.9848171  0.00735451]
 [0.0052327  0.0012899  0.9934774 ]]
pi = [0.50517283 0.03710257 0.4577246 ]
Iter 7: LL=-1266596.09 | Rates: N=0.82094, AF=0.09757, OLD=0.10884, YOUNG=0.03982
A =
[[0.99344065 0.00138845 0.0051709 ]
 [0.00817252 0.98353681 0.00829067]
 [0.00519235 0.00137768 0.99342997]]
pi = [0.50524175 0.03217084 0.46258741]
Iter 8: LL=-1266574.10 | Rates: N=0.82094, AF=0.09751, OLD=0.11232, YOUNG=0.03983
A =
[[0.99344148 0.00138096 0.00517756]
 [0.0084641  0.9822408  0.0092951 ]
 [0.00516507 0.00146526 0.99336967]]
pi = [0.50531262 0.02856196 0.46612542]
Iter 9: LL=-1266554.20 | Rates: N=0.82094, AF=0.09746, OLD=0.11575, YOUNG=0.03985
A =
[[0.99344236 0.00136641 0.00519123]
 [0.00871328 0.98093381 0.01035292]
 [0.00514717 0.00155116 0.99330167]]
pi = [0.50537761 0.02584535 0.46877704]
Iter 10: LL=-1266535.93 | Rates: N=0.82093, AF=0.09741, OLD=0.11916, YOUNG=0.03989
A =
[[0.99344329 0.00134721 0.0052095 ]
 [0.00893137 0.97961225 0.01145638]
 [0.00513576 0.00163437 0.99322987]]
pi = [0.50543386 0.02373531 0.47083083]
Iter 11: LL=-1266519.01 | Rates: N=0.82093, AF=0.09736, OLD=0.12258, YOUNG=0.03993
A =
[[0.99344421 0.00132508 0.00523071]
 [0.00912815 0.97827116 0.01260068]
 [0.00512874 0.00171417 0.99315709]]
pi = [0.50548057 0.02203389 0.47248554]
Iter 12: LL=-1266503.27 | Rates: N=0.82092, AF=0.09731, OLD=0.12603, YOUNG=0.03999
A =
[[0.9934451  0.00130126 0.00525364]
 [0.00931131 0.97690636 0.01378233]
 [0.00512463 0.00179005 0.99308532]]
pi = [0.50551804 0.02059905 0.47388291]
Iter 13: LL=-1266488.54 | Rates: N=0.82092, AF=0.09727, OLD=0.12953, YOUNG=0.04004
A =
[[0.99344591 0.00127663 0.00527746]
 [0.00948668 0.97551459 0.01499872]
 [0.00512245 0.0018616  0.99301596]]
pi = [0.50554713 0.01932683 0.47512605]
Iter 14: LL=-1266474.70 | Rates: N=0.82092, AF=0.09722, OLD=0.13311, YOUNG=0.04010
A =
[[0.99344662 0.00125179 0.00530159]
 [0.00965873 0.97409314 0.01624813]
 [0.0051215  0.00192851 0.99295   ]]
pi = [0.50556901 0.0181408  0.47629018]
Iter 15: LL=-1266461.60 | Rates: N=0.82091, AF=0.09717, OLD=0.13678, YOUNG=0.04017
A =
[[0.99344721 0.00122712 0.00532567]
 [0.00983093 0.97263921 0.01752986]
 [0.00512134 0.00199052 0.99288814]]
pi = [0.5055849  0.01698562 0.47742947]
Final Global Rates (lambdas): [0.82091147 0.09717438 0.13677578 0.0401713 ]
Final transition matrix A:
[[0.99344721 0.00122712 0.00532567]
 [0.00983093 0.97263921 0.01752986]
 [0.00512134 0.00199052 0.99288814]]
Final initial distribution pi:
[0.5055849  0.01698562 0.47742947]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.0793  0.0385  0.0518    1445240.0   16786760.0  36080597.0
Archaic_young     0.9237  0.9597  0.9414  485314703.0   40072297.0  20390054.0
Modern            0.0000  0.0000  0.0000          0.0  456381000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         450251          236           3078
Archaic_old       734         1441          35393
Archaic_young    5396        16555         486916

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0472  0.0033  0.0062
Archaic_young     0.8915  0.9840  0.9354

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         435438           12           3645
Archaic_old       845          184          54619
Archaic_young    5851         3704         495702

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 18
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1480544.14 | Rates: N=0.81634, AF=0.09972, OLD=0.07857, YOUNG=0.05371
A =
[[0.99258411 0.00116229 0.0062536 ]
 [0.00660827 0.98677464 0.00661709]
 [0.0059356  0.00108382 0.99298058]]
pi = [0.24667338 0.1520332  0.60129341]
Iter 2: LL=-1279955.70 | Rates: N=0.81648, AF=0.09978, OLD=0.09405, YOUNG=0.05004
A =
[[0.99271605 0.00124859 0.00603536]
 [0.00632551 0.987494   0.00618049]
 [0.00584122 0.00112413 0.99303465]]
pi = [0.23151202 0.15779872 0.61068927]
Iter 3: LL=-1279595.84 | Rates: N=0.81647, AF=0.09950, OLD=0.10735, YOUNG=0.04728
A =
[[0.99273733 0.00135189 0.00591078]
 [0.00641672 0.98735409 0.00622919]
 [0.00579169 0.00119046 0.99301784]]
pi = [0.22990493 0.14880405 0.62129102]
Iter 4: LL=-1279398.95 | Rates: N=0.81646, AF=0.09929, OLD=0.11670, YOUNG=0.04607
A =
[[0.9927434  0.00140486 0.00585174]
 [0.00679629 0.98625176 0.00695195]
 [0.00571206 0.00127496 0.99301298]]
pi = [0.22977302 0.13179904 0.63842794]
Iter 5: LL=-1279313.55 | Rates: N=0.81645, AF=0.09913, OLD=0.12410, YOUNG=0.04571
A =
[[0.99274602 0.00141732 0.00583665]
 [0.00723108 0.98469602 0.0080729 ]
 [0.00564074 0.00137601 0.99298325]]
pi = [0.22982445 0.11591779 0.65425776]
Iter 6: LL=-1279256.14 | Rates: N=0.81644, AF=0.09901, OLD=0.13083, YOUNG=0.04567
A =
[[0.99274771 0.00140361 0.00584869]
 [0.00763525 0.98293298 0.00943176]
 [0.00558872 0.00148398 0.9929273 ]]
pi = [0.22992277 0.10370383 0.6663734 ]
Iter 7: LL=-1279206.46 | Rates: N=0.81643, AF=0.09890, OLD=0.13746, YOUNG=0.04574
A =
[[0.9927491  0.001374   0.0058769 ]
 [0.007993   0.98105004 0.01095696]
 [0.00555355 0.00159242 0.99285403]]
pi = [0.23002166 0.09489772 0.67508062]
Iter 8: LL=-1279160.95 | Rates: N=0.81642, AF=0.09880, OLD=0.14415, YOUNG=0.04585
A =
[[0.99275039 0.00133538 0.00591423]
 [0.00831148 0.97907432 0.0126142 ]
 [0.00553039 0.00169752 0.99277209]]
pi = [0.23009448 0.08843474 0.68147078]
Iter 9: LL=-1279118.92 | Rates: N=0.81641, AF=0.09870, OLD=0.15098, YOUNG=0.04597
A =
[[0.9927515  0.00129253 0.00595597]
 [0.00860462 0.97701371 0.01438167]
 [0.00551495 0.00179707 0.99268798]]
pi = [0.23013671 0.08330986 0.68655343]
Iter 10: LL=-1279080.04 | Rates: N=0.81640, AF=0.09861, OLD=0.15802, YOUNG=0.04611
A =
[[0.99275224 0.00124881 0.00599894]
 [0.00888798 0.97486975 0.01624227]
 [0.00550393 0.00188969 0.99260638]]
pi = [0.23015696 0.07880597 0.69103706]
Iter 11: LL=-1279043.80 | Rates: N=0.81639, AF=0.09850, OLD=0.16539, YOUNG=0.04625
A =
[[0.99275241 0.0012064  0.00604119]
 [0.00917688 0.9726402  0.01818292]
 [0.00549495 0.0019744  0.99253065]]
pi = [0.23016698 0.07445764 0.69537538]
Iter 12: LL=-1279009.55 | Rates: N=0.81637, AF=0.09838, OLD=0.17320, YOUNG=0.04641
A =
[[0.99275197 0.00116635 0.00608168]
 [0.00948542 0.97031786 0.02019673]
 [0.00548642 0.0020504  0.99246318]]
pi = [0.23017696 0.0699599  0.69986315]
Iter 13: LL=-1278976.63 | Rates: N=0.81635, AF=0.09825, OLD=0.18154, YOUNG=0.04657
A =
[[0.99275104 0.00112893 0.00612003]
 [0.00982593 0.96788966 0.02228441]
 [0.00547736 0.00211714 0.99240549]]
pi = [0.23019502 0.06509945 0.70470554]
Iter 14: LL=-1278944.44 | Rates: N=0.81633, AF=0.09810, OLD=0.19055, YOUNG=0.04674
A =
[[0.99274948 0.00109429 0.00615623]
 [0.01021064 0.96533644 0.02445292]
 [0.00546735 0.00217437 0.99235827]]
pi = [0.23022794 0.05971673 0.71005532]
Iter 15: LL=-1278912.20 | Rates: N=0.81631, AF=0.09793, OLD=0.20045, YOUNG=0.04693
A =
[[0.99274687 0.00106278 0.00619035]
 [0.01065489 0.96262693 0.02671818]
 [0.00545621 0.00222193 0.99232186]]
pi = [0.23028104 0.05368305 0.71603591]
Final Global Rates (lambdas): [0.81630809 0.09792642 0.20045315 0.04692674]
Final transition matrix A:
[[0.99274687 0.00106278 0.00619035]
 [0.01065489 0.96262693 0.02671818]
 [0.00545621 0.00222193 0.99232186]]
Final initial distribution pi:
[0.23028104 0.05368305 0.71603591]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1148  0.0312  0.0490    1734091.0   13369909.0  53894286.0
Archaic_young     0.8928  0.9668  0.9284  485242849.0   58236151.0  16639336.0
Modern            0.0000  0.0000  0.0000          0.0  441417000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         435131          626           3338
Archaic_old       820         1740          53088
Archaic_young    5466        12738         487053

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1664   0.216  0.1880
Archaic_young     0.9031   0.875  0.8889

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         442640          441           2364
Archaic_old       835        12035          43051
Archaic_young    3332        59879         435423

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1450297.48 | Rates: N=0.82060, AF=0.09846, OLD=0.05878, YOUNG=0.03393
A =
[[0.99451896 0.00155544 0.00392559]
 [0.00482316 0.99245891 0.00271792]
 [0.00442375 0.00099865 0.9945776 ]]
pi = [0.39973264 0.17801323 0.42225413]
Iter 2: LL=-1247096.38 | Rates: N=0.82074, AF=0.09826, OLD=0.06310, YOUNG=0.03283
A =
[[0.99453322 0.00155497 0.00391181]
 [0.00506152 0.99202032 0.00291816]
 [0.00431885 0.00100881 0.99467234]]
pi = [0.39964896 0.18363324 0.41671781]
Iter 3: LL=-1247042.07 | Rates: N=0.82074, AF=0.09821, OLD=0.06661, YOUNG=0.03235
A =
[[0.99453465 0.00154264 0.00392271]
 [0.00533273 0.99142228 0.00324499]
 [0.00424492 0.00103843 0.99471664]]
pi = [0.39958497 0.18477601 0.41563902]
Iter 4: LL=-1247009.72 | Rates: N=0.82074, AF=0.09817, OLD=0.06958, YOUNG=0.03221
A =
[[0.99453501 0.00151483 0.00395016]
 [0.00559006 0.99073155 0.00367839]
 [0.00419054 0.00107939 0.99473006]]
pi = [0.39949854 0.18262422 0.41787724]
Iter 5: LL=-1246984.91 | Rates: N=0.82074, AF=0.09814, OLD=0.07229, YOUNG=0.03222
A =
[[0.99453524 0.00147625 0.0039885 ]
 [0.00581838 0.9899852  0.00419642]
 [0.00415489 0.00112656 0.99471855]]
pi = [0.39941217 0.17849294 0.42209489]
Iter 6: LL=-1246962.62 | Rates: N=0.82074, AF=0.09811, OLD=0.07493, YOUNG=0.03229
A =
[[0.99453553 0.0014311  0.00403338]
 [0.00601595 0.98919662 0.00478743]
 [0.00413404 0.00117675 0.99468921]]
pi = [0.39933417 0.17314972 0.42751611]
Iter 7: LL=-1246941.43 | Rates: N=0.82074, AF=0.09809, OLD=0.07758, YOUNG=0.03237
A =
[[0.99453589 0.00138243 0.00408169]
 [0.00618624 0.98836737 0.00544639]
 [0.00412393 0.0012281  0.99464797]]
pi = [0.3992669 0.167025  0.4337081]
Iter 8: LL=-1246920.90 | Rates: N=0.82074, AF=0.09806, OLD=0.08030, YOUNG=0.03247
A =
[[0.99453631 0.00133242 0.00413127]
 [0.00633437 0.98749401 0.00617162]
 [0.00412126 0.00127949 0.99459925]]
pi = [0.39921022 0.16038244 0.44040734]
Iter 9: LL=-1246900.93 | Rates: N=0.82074, AF=0.09804, OLD=0.08311, YOUNG=0.03256
A =
[[0.99453676 0.00128257 0.00418067]
 [0.00646563 0.9865716  0.00696278]
 [0.00412351 0.00133015 0.99454634]]
pi = [0.39916308 0.15340542 0.4474315 ]
Iter 10: LL=-1246881.49 | Rates: N=0.82074, AF=0.09802, OLD=0.08601, YOUNG=0.03266
A =
[[0.99453722 0.00123392 0.00422887]
 [0.00658488 0.98559538 0.00781974]
 [0.00412886 0.00137949 0.99449164]]
pi = [0.39912419 0.1462385  0.45463731]
Iter 11: LL=-1246862.65 | Rates: N=0.82074, AF=0.09800, OLD=0.08902, YOUNG=0.03275
A =
[[0.99453765 0.00118713 0.00427522]
 [0.00669624 0.98456193 0.00874183]
 [0.00413601 0.00142705 0.99443694]]
pi = [0.39909226 0.13900936 0.46189838]
Iter 12: LL=-1246844.43 | Rates: N=0.82074, AF=0.09798, OLD=0.09215, YOUNG=0.03285
A =
[[0.99453805 0.00114262 0.00431932]
 [0.00680294 0.98346965 0.00972741]
 [0.00414406 0.00147241 0.99438353]]
pi = [0.39906609 0.1318386  0.46909531]
Iter 13: LL=-1246826.89 | Rates: N=0.82073, AF=0.09796, OLD=0.09539, YOUNG=0.03294
A =
[[0.99453842 0.00110059 0.00436099]
 [0.00690746 0.98231872 0.01077382]
 [0.00415242 0.00151524 0.99433234]]
pi = [0.39904454 0.12483827 0.47611718]
Iter 14: LL=-1246810.03 | Rates: N=0.82073, AF=0.09793, OLD=0.09877, YOUNG=0.03304
A =
[[0.99453874 0.00106109 0.00440017]
 [0.00701188 0.98111013 0.01187799]
 [0.00416067 0.00155526 0.99428407]]
pi = [0.39902655 0.11810055 0.48287291]
Iter 15: LL=-1246793.79 | Rates: N=0.82073, AF=0.09789, OLD=0.10232, YOUNG=0.03314
A =
[[0.99453901 0.001024   0.00443699]
 [0.00711855 0.97984394 0.0130375 ]
 [0.0041685  0.00159222 0.99423928]]
pi = [0.39901092 0.11168205 0.48930703]
Final Global Rates (lambdas): [0.82073189 0.0978945  0.10231866 0.03313522]
Final transition matrix A:
[[0.99453901 0.001024   0.00443699]
 [0.00711855 0.97984394 0.0130375 ]
 [0.0041685  0.00159222 0.99423928]]
Final initial distribution pi:
[0.39901092 0.11168205 0.48930703]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2806  0.0887  0.1348    4944631.0   12675369.0  50784314.0
Archaic_young     0.8994  0.9701  0.9334  481472461.0   53847539.0  14831502.0
Modern            0.0000  0.0000  0.0000          0.0  447060000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         442760          157           2528
Archaic_old       903         4947          50071
Archaic_young    3397        12516         482721

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1667  0.1180  0.1382
Archaic_young     0.9219  0.9468  0.9342

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         449719          189           2694
Archaic_old       730         4930          36286
Archaic_young    3559        24448         477445

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 18
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1456177.21 | Rates: N=0.82538, AF=0.09783, OLD=0.06237, YOUNG=0.03562
A =
[[9.94130283e-01 1.34583961e-03 4.52387722e-03]
 [6.05614871e-03 9.90161964e-01 3.78188774e-03]
 [4.73393271e-03 9.27372859e-04 9.94338694e-01]]
pi = [0.64963327 0.05494486 0.29542187]
Iter 2: LL=-1250351.69 | Rates: N=0.82554, AF=0.09774, OLD=0.06903, YOUNG=0.03381
A =
[[9.94161387e-01 1.37440022e-03 4.46421244e-03]
 [6.31680049e-03 9.89948156e-01 3.73504346e-03]
 [4.62793440e-03 9.52912318e-04 9.94419153e-01]]
pi = [0.65722908 0.02793142 0.3148395 ]
Iter 3: LL=-1250258.13 | Rates: N=0.82553, AF=0.09769, OLD=0.07371, YOUNG=0.03301
A =
[[0.9941648  0.00138458 0.00445061]
 [0.00669446 0.98942002 0.00388552]
 [0.00454649 0.00099779 0.99445573]]
pi = [0.65712462 0.01214634 0.33072904]
Iter 4: LL=-1250221.32 | Rates: N=0.82553, AF=0.09765, OLD=0.07705, YOUNG=0.03276
A =
[[0.99416547 0.00136936 0.00446517]
 [0.00710615 0.98870138 0.00419247]
 [0.00447756 0.00105048 0.99447196]]
pi = [0.65688121 0.00481462 0.33830418]
Iter 5: LL=-1250201.42 | Rates: N=0.82553, AF=0.09762, OLD=0.07977, YOUNG=0.03273
A =
[[0.99416557 0.0013387  0.00449572]
 [0.00749787 0.98791115 0.00459098]
 [0.0044261  0.00110586 0.99446804]]
pi = [0.65678884 0.00183564 0.34137552]
Iter 6: LL=-1250186.03 | Rates: N=0.82553, AF=0.09759, OLD=0.08224, YOUNG=0.03279
A =
[[0.99416564 0.00129956 0.0045348 ]
 [0.00785217 0.98709969 0.00504814]
 [0.00439027 0.00116096 0.99444877]]
pi = [0.65677854 0.00068914 0.34253232]
Iter 7: LL=-1250172.41 | Rates: N=0.82553, AF=0.09757, OLD=0.08463, YOUNG=0.03287
A =
[[0.99416581 0.00125613 0.00457806]
 [0.00816798 0.98628278 0.00554924]
 [0.00436661 0.00121438 0.99441901]]
pi = [6.56802416e-01 2.57014560e-04 3.42940570e-01]
Iter 8: LL=-1250159.89 | Rates: N=0.82553, AF=0.09755, OLD=0.08699, YOUNG=0.03295
A =
[[0.99416611 0.00121095 0.00462294]
 [0.00844985 0.98546271 0.00608744]
 [0.00435197 0.00126545 0.99438258]]
pi = [6.56839412e-01 9.55345337e-05 3.43065053e-01]
Iter 9: LL=-1250148.20 | Rates: N=0.82553, AF=0.09753, OLD=0.08935, YOUNG=0.03303
A =
[[0.99416653 0.00116558 0.00466789]
 [0.00870354 0.98463772 0.00665873]
 [0.0043439  0.00131382 0.99434228]]
pi = [6.56881010e-01 3.54388051e-05 3.43083551e-01]
Iter 10: LL=-1250137.25 | Rates: N=0.82553, AF=0.09752, OLD=0.09173, YOUNG=0.03311
A =
[[0.99416705 0.00112104 0.00471192]
 [0.00893431 0.98380572 0.00725996]
 [0.00434056 0.00135931 0.99430014]]
pi = [6.56923701e-01 1.31285509e-05 3.43063170e-01]
Iter 11: LL=-1250126.97 | Rates: N=0.82553, AF=0.09750, OLD=0.09413, YOUNG=0.03319
A =
[[0.99416763 0.00107795 0.00475442]
 [0.00914654 0.98296529 0.00788817]
 [0.0043406  0.00140185 0.99425755]]
pi = [6.56965936e-01 4.85975560e-06 3.43029205e-01]
Iter 12: LL=-1250117.33 | Rates: N=0.82553, AF=0.09748, OLD=0.09655, YOUNG=0.03326
A =
[[0.99416827 0.00103671 0.00479503]
 [0.00934374 0.98211583 0.00854043]
 [0.00434304 0.00144145 0.99421551]]
pi = [6.57006960e-01 1.79851785e-06 3.42991241e-01]
Iter 13: LL=-1250108.32 | Rates: N=0.82552, AF=0.09746, OLD=0.09898, YOUNG=0.03333
A =
[[0.99416893 0.00099754 0.00483352]
 [0.00952878 0.98125731 0.00921391]
 [0.00434714 0.00147817 0.9941747 ]]
pi = [6.57046369e-01 6.65852937e-07 3.42952965e-01]
Iter 14: LL=-1250099.91 | Rates: N=0.82552, AF=0.09745, OLD=0.10142, YOUNG=0.03340
A =
[[9.94169615e-01 9.60591184e-04 4.86979344e-03]
 [9.70398877e-03 9.80390021e-01 9.90599064e-03]
 [4.35235191e-03 1.51208290e-03 9.94135565e-01]]
pi = [6.57083929e-01 2.46764602e-07 3.42915825e-01]
Iter 15: LL=-1250092.07 | Rates: N=0.82552, AF=0.09743, OLD=0.10387, YOUNG=0.03347
A =
[[9.94170302e-01 9.25896396e-04 4.90380152e-03]
 [9.87132344e-03 9.79514411e-01 1.06142659e-02]
 [4.35828113e-03 1.54331261e-03 9.94098406e-01]]
pi = [6.57119501e-01 9.16045751e-08 3.42880407e-01]
Final Global Rates (lambdas): [0.82552103 0.09743085 0.10387082 0.03347382]
Final transition matrix A:
[[9.94170302e-01 9.25896396e-04 4.90380152e-03]
 [9.87132344e-03 9.79514411e-01 1.06142659e-02]
 [4.35828113e-03 1.54331261e-03 9.94098406e-01]]
Final initial distribution pi:
[6.57119501e-01 9.16045751e-08 3.42880407e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1970  0.1031  0.1354    4309510.0   17568490.0  37483111.0
Archaic_young     0.9219  0.9602  0.9407  482815788.0   40882212.0  20020988.0
Modern            0.0000  0.0000  0.0000          0.0  454424000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         449835          101           2666
Archaic_old       764         4311          36871
Archaic_young    3825        17466         484161

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2979  0.1206  0.1717
Archaic_young     0.9127  0.9673  0.9392

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         425342          104           3095
Archaic_old      1011         6046          43297
Archaic_young    4090        14168         502847

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1445420.85 | Rates: N=0.81119, AF=0.09730, OLD=0.06763, YOUNG=0.03961
A =
[[9.93315351e-01 1.38221039e-03 5.30243832e-03]
 [6.30943905e-03 9.89003760e-01 4.68680057e-03]
 [4.92912877e-03 9.63850649e-04 9.94107021e-01]]
pi = [0.49634926 0.10429861 0.39935213]
Iter 2: LL=-1250997.44 | Rates: N=0.81135, AF=0.09727, OLD=0.07608, YOUNG=0.03726
A =
[[9.93375259e-01 1.44436258e-03 5.18037850e-03]
 [6.35207194e-03 9.89121661e-01 4.52626735e-03]
 [4.84171099e-03 9.89477572e-04 9.94168811e-01]]
pi = [0.50253819 0.09035209 0.40710972]
Iter 3: LL=-1250857.00 | Rates: N=0.81135, AF=0.09717, OLD=0.08192, YOUNG=0.03607
A =
[[0.99338218 0.00148719 0.00513063]
 [0.00656798 0.98877043 0.00466159]
 [0.00478528 0.00103647 0.99417825]]
pi = [0.50289557 0.07285144 0.42425299]
Iter 4: LL=-1250805.05 | Rates: N=0.81135, AF=0.09709, OLD=0.08581, YOUNG=0.03561
A =
[[0.99338366 0.00149497 0.00512136]
 [0.00684331 0.9881197  0.00503699]
 [0.00473543 0.00109349 0.99417107]]
pi = [0.50290157 0.05504381 0.44205462]
Iter 5: LL=-1250781.84 | Rates: N=0.81135, AF=0.09704, OLD=0.08877, YOUNG=0.03548
A =
[[0.99338417 0.00148147 0.00513436]
 [0.0071017  0.98735723 0.00554107]
 [0.00469925 0.00115494 0.99414581]]
pi = [0.50289006 0.03976376 0.45734618]
Iter 6: LL=-1250765.53 | Rates: N=0.81135, AF=0.09699, OLD=0.09135, YOUNG=0.03547
A =
[[0.99338466 0.0014563  0.00515904]
 [0.00732201 0.98656229 0.0061157 ]
 [0.00467578 0.00121687 0.99410735]]
pi = [0.50288912 0.02777559 0.46933529]
Iter 7: LL=-1250751.53 | Rates: N=0.81134, AF=0.09695, OLD=0.09376, YOUNG=0.03551
A =
[[0.99338532 0.00142502 0.00518967]
 [0.0075046  0.98576154 0.00673386]
 [0.00466193 0.00127731 0.99406076]]
pi = [0.50289538 0.01887433 0.47823029]
Iter 8: LL=-1250738.85 | Rates: N=0.81134, AF=0.09692, OLD=0.09610, YOUNG=0.03556
A =
[[0.99338615 0.00139078 0.00522307]
 [0.00765598 0.98496126 0.00738277]
 [0.00465483 0.00133534 0.99400983]]
pi = [0.50290279 0.01251992 0.48457729]
Iter 9: LL=-1250727.19 | Rates: N=0.81134, AF=0.09689, OLD=0.09841, YOUNG=0.03562
A =
[[0.99338712 0.00135546 0.00525742]
 [0.00778341 0.98416064 0.00805595]
 [0.0046523  0.0013905  0.9939572 ]]
pi = [0.50290787 0.00812416 0.48896797]
Iter 10: LL=-1250716.41 | Rates: N=0.81134, AF=0.09685, OLD=0.10071, YOUNG=0.03568
A =
[[0.99338819 0.00132019 0.00529162]
 [0.00789331 0.9833568  0.0087499 ]
 [0.00465279 0.00144255 0.99390466]]
pi = [0.50290967 0.00516495 0.49192538]
Iter 11: LL=-1250706.41 | Rates: N=0.81134, AF=0.09682, OLD=0.10300, YOUNG=0.03574
A =
[[0.99338932 0.00128565 0.00532503]
 [0.00799091 0.9825464  0.00946268]
 [0.00465521 0.0014914  0.99385339]]
pi = [0.50290861 0.00322122 0.49387016]
Iter 12: LL=-1250697.09 | Rates: N=0.81134, AF=0.09679, OLD=0.10530, YOUNG=0.03580
A =
[[0.99339047 0.00125226 0.00535727]
 [0.00808039 0.98172627 0.01019334]
 [0.00465881 0.00153705 0.99380414]]
pi = [0.50290561 0.00197316 0.49512123]
Iter 13: LL=-1250688.36 | Rates: N=0.81133, AF=0.09677, OLD=0.10762, YOUNG=0.03586
A =
[[0.99339163 0.00122023 0.00538815]
 [0.00816501 0.9808934  0.0109416 ]
 [0.00466307 0.00157954 0.9937574 ]]
pi = [0.50290157 0.00118851 0.49590991]
Iter 14: LL=-1250680.15 | Rates: N=0.81133, AF=0.09674, OLD=0.10997, YOUNG=0.03593
A =
[[0.99339278 0.00118964 0.00541758]
 [0.00824736 0.98004491 0.01170773]
 [0.00466763 0.00161894 0.99371343]]
pi = [0.50289722 0.00070477 0.496398  ]
Iter 15: LL=-1250672.38 | Rates: N=0.81133, AF=0.09671, OLD=0.11235, YOUNG=0.03600
A =
[[0.9933939  0.00116052 0.00544558]
 [0.0083295  0.97917799 0.01249251]
 [0.00467227 0.00165534 0.99367239]]
pi = [5.02893042e-01 4.11905851e-04 4.96695053e-01]
Final Global Rates (lambdas): [0.81132953 0.0967075  0.11234682 0.03599945]
Final transition matrix A:
[[0.9933939  0.00116052 0.00544558]
 [0.0083295  0.97917799 0.01249251]
 [0.00467227 0.00165534 0.99367239]]
Final initial distribution pi:
[5.02893042e-01 4.11905851e-04 4.96695053e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2961  0.1378  0.1880    6915232.0   16441768.0  43284832.0
Archaic_young     0.9140  0.9629  0.9378  499013591.0   46938409.0  19231956.0
Modern            0.0000  0.0000  0.0000          0.0  430691000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         425439          108           2994
Archaic_old      1035         6912          42407
Archaic_young    4217        16337         500551

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2002  0.0538  0.0848
Archaic_young     0.9092  0.9727  0.9399

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         440060           31           3382
Archaic_old      1046         2551          44063
Archaic_young    5124        10203         493540

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1470022.25 | Rates: N=0.82039, AF=0.09840, OLD=0.07539, YOUNG=0.04534
A =
[[0.99306299 0.00136337 0.00557363]
 [0.00686383 0.98775256 0.00538361]
 [0.00548767 0.00107387 0.99343846]]
pi = [0.60100555 0.09035315 0.3086413 ]
Iter 2: LL=-1267508.64 | Rates: N=0.82056, AF=0.09842, OLD=0.08613, YOUNG=0.04236
A =
[[0.99315793 0.00143172 0.00541035]
 [0.00687412 0.98794159 0.00518429]
 [0.00536512 0.00112442 0.99351046]]
pi = [0.60754571 0.09288613 0.29956816]
Iter 3: LL=-1267308.62 | Rates: N=0.82055, AF=0.09830, OLD=0.09384, YOUNG=0.04070
A =
[[0.99316641 0.0014915  0.00534209]
 [0.00713212 0.98749597 0.00537191]
 [0.00529346 0.00120586 0.99350068]]
pi = [0.60766367 0.0937087  0.29862763]
Iter 4: LL=-1267227.01 | Rates: N=0.82055, AF=0.09820, OLD=0.09896, YOUNG=0.04001
A =
[[0.99316642 0.00151358 0.00532   ]
 [0.00749529 0.98661741 0.0058873 ]
 [0.00522457 0.00130012 0.99347531]]
pi = [0.60764565 0.09074345 0.3016109 ]
Iter 5: LL=-1267190.49 | Rates: N=0.82055, AF=0.09812, OLD=0.10278, YOUNG=0.03977
A =
[[0.99316545 0.00151077 0.00532378]
 [0.00785037 0.98558308 0.00656655]
 [0.00517026 0.00139879 0.99343095]]
pi = [0.60766334 0.08559983 0.30673684]
Iter 6: LL=-1267166.04 | Rates: N=0.82055, AF=0.09806, OLD=0.10600, YOUNG=0.03972
A =
[[0.99316464 0.00149351 0.00534185]
 [0.00816114 0.98451661 0.00732225]
 [0.00513157 0.00149603 0.9933724 ]]
pi = [0.60770144 0.07956888 0.31272967]
Iter 7: LL=-1267146.29 | Rates: N=0.82054, AF=0.09801, OLD=0.10891, YOUNG=0.03973
A =
[[0.9931641  0.00146825 0.00536766]
 [0.00842399 0.9834621  0.00811391]
 [0.00510542 0.00158908 0.9933055 ]]
pi = [0.60774835 0.07341226 0.31883939]
Iter 8: LL=-1267129.50 | Rates: N=0.82054, AF=0.09796, OLD=0.11164, YOUNG=0.03976
A =
[[0.99316377 0.00143885 0.00539738]
 [0.00864562 0.98243179 0.00892259]
 [0.00508841 0.00167676 0.99323483]]
pi = [0.60779777 0.06754393 0.3246583 ]
Iter 9: LL=-1267114.96 | Rates: N=0.82054, AF=0.09793, OLD=0.11425, YOUNG=0.03980
A =
[[0.9931636  0.00140766 0.00542874]
 [0.00883473 0.98142633 0.00973895]
 [0.00507778 0.00175866 0.99316355]]
pi = [0.60784619 0.06217125 0.32998255]
Iter 10: LL=-1267102.26 | Rates: N=0.82054, AF=0.09789, OLD=0.11676, YOUNG=0.03985
A =
[[0.99316354 0.00137611 0.00546034]
 [0.00899937 0.98044241 0.01055822]
 [0.00507153 0.00183474 0.99309372]]
pi = [0.60789168 0.05737711 0.33473121]
Iter 11: LL=-1267091.08 | Rates: N=0.82054, AF=0.09786, OLD=0.11919, YOUNG=0.03990
A =
[[0.99316356 0.00134506 0.00549138]
 [0.00914622 0.97947562 0.01137815]
 [0.00506822 0.00190517 0.99302661]]
pi = [0.60793319 0.05316972 0.33889709]
Iter 12: LL=-1267081.13 | Rates: N=0.82054, AF=0.09782, OLD=0.12157, YOUNG=0.03996
A =
[[0.99316362 0.001315   0.00552138]
 [0.00928063 0.97852135 0.01219802]
 [0.00506684 0.00197022 0.99296294]]
pi = [0.60797023 0.04951511 0.34251466]
Iter 13: LL=-1267072.22 | Rates: N=0.82053, AF=0.09779, OLD=0.12391, YOUNG=0.04001
A =
[[0.99316371 0.00128617 0.00555012]
 [0.00940677 0.97757507 0.01301816]
 [0.00506671 0.00203023 0.99290306]]
pi = [0.60800268 0.04635853 0.3456388 ]
Iter 14: LL=-1267064.14 | Rates: N=0.82053, AF=0.09777, OLD=0.12623, YOUNG=0.04007
A =
[[0.99316382 0.00125867 0.00557751]
 [0.00952792 0.97663239 0.01383969]
 [0.00506735 0.00208554 0.99284711]]
pi = [0.60803063 0.0436378  0.34833156]
Iter 15: LL=-1267056.74 | Rates: N=0.82053, AF=0.09774, OLD=0.12854, YOUNG=0.04014
A =
[[0.99316393 0.00123248 0.00560358]
 [0.00964662 0.97568906 0.01466432]
 [0.00506845 0.00213649 0.99279506]]
pi = [0.60805436 0.04129106 0.35065457]
Final Global Rates (lambdas): [0.82053032 0.09773706 0.12853555 0.04013755]
Final transition matrix A:
[[0.99316393 0.00123248 0.00560358]
 [0.00964662 0.97568906 0.01466432]
 [0.00506845 0.00213649 0.99279506]]
Final initial distribution pi:
[0.60805436 0.04129106 0.35065457]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2136  0.1023  0.1383    4866317.0   17920683.0  42697075.0
Archaic_young     0.9123  0.9581  0.9346  484533800.0   46593200.0  21170957.0
Modern            0.0000  0.0000  0.0000          0.0  446086000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         440007          303           3163
Archaic_old       969         4859          41832
Archaic_young    5110        17625         486132

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1655  0.3315  0.2208
Archaic_young     0.9170  0.8241  0.8681

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         446888          573           2210
Archaic_old       904        17058          33733
Archaic_young    3157        85418         410059

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1451207.70 | Rates: N=0.82166, AF=0.09731, OLD=0.06156, YOUNG=0.03264
A =
[[0.9945254  0.00183542 0.00363918]
 [0.00524043 0.99217229 0.00258728]
 [0.00434487 0.00105606 0.99459907]]
pi = [0.30082531 0.21126711 0.48790758]
Iter 2: LL=-1247641.84 | Rates: N=0.82181, AF=0.09715, OLD=0.06481, YOUNG=0.03191
A =
[[0.99454992 0.00183157 0.00361851]
 [0.00547018 0.9917039  0.00282592]
 [0.00423477 0.00105122 0.99471401]]
pi = [0.29974277 0.21935843 0.4808988 ]
Iter 3: LL=-1247609.83 | Rates: N=0.82181, AF=0.09712, OLD=0.06730, YOUNG=0.03169
A =
[[0.99455094 0.00182024 0.00362883]
 [0.00567864 0.99118775 0.00313362]
 [0.00418209 0.00106948 0.99474843]]
pi = [0.29968435 0.22758594 0.47272971]
Iter 4: LL=-1247591.32 | Rates: N=0.82181, AF=0.09709, OLD=0.06934, YOUNG=0.03169
A =
[[0.99455092 0.00179364 0.00365545]
 [0.0058483  0.99065627 0.00349543]
 [0.00415207 0.00109805 0.99474988]]
pi = [0.29963012 0.23387935 0.46649053]
Iter 5: LL=-1247576.84 | Rates: N=0.82181, AF=0.09707, OLD=0.07117, YOUNG=0.03176
A =
[[0.99455102 0.00175693 0.00369205]
 [0.00598207 0.99012386 0.00389406]
 [0.00413781 0.00113226 0.99472992]]
pi = [0.29957976 0.23803835 0.4623819 ]
Iter 6: LL=-1247563.88 | Rates: N=0.82181, AF=0.09705, OLD=0.07291, YOUNG=0.03186
A =
[[0.9945513  0.00171407 0.00373463]
 [0.00608737 0.98959183 0.0043208 ]
 [0.00413397 0.00116954 0.9946965 ]]
pi = [0.29953531 0.24036355 0.46010114]
Iter 7: LL=-1247551.77 | Rates: N=0.82181, AF=0.09704, OLD=0.07463, YOUNG=0.03197
A =
[[0.99455172 0.00166771 0.00378057]
 [0.00617172 0.98905662 0.00477166]
 [0.00413662 0.00120839 0.99465499]]
pi = [0.29949664 0.24125687 0.4592465 ]
Iter 8: LL=-1247540.26 | Rates: N=0.82181, AF=0.09702, OLD=0.07635, YOUNG=0.03207
A =
[[0.99455226 0.00161962 0.00382812]
 [0.00624152 0.98851363 0.00524485]
 [0.0041431  0.00124789 0.99460902]]
pi = [0.29946277 0.24108694 0.45945029]
Iter 9: LL=-1247529.25 | Rates: N=0.82181, AF=0.09701, OLD=0.07809, YOUNG=0.03217
A =
[[0.9945529  0.00157101 0.00387609]
 [0.0063017  0.98795877 0.00573953]
 [0.00415163 0.00128736 0.99456101]]
pi = [0.29943257 0.24015307 0.46041435]
Iter 10: LL=-1247518.68 | Rates: N=0.82181, AF=0.09700, OLD=0.07985, YOUNG=0.03227
A =
[[0.9945536  0.00152271 0.00392368]
 [0.00635589 0.987389   0.00625511]
 [0.0041611  0.00132631 0.99451259]]
pi = [0.29940503 0.23868308 0.46191189]
Iter 11: LL=-1247508.55 | Rates: N=0.82181, AF=0.09699, OLD=0.08164, YOUNG=0.03237
A =
[[0.99455435 0.00147532 0.00397033]
 [0.00640664 0.98680233 0.00679103]
 [0.00417081 0.00136436 0.99446483]]
pi = [0.29937931 0.2368427  0.46377799]
Iter 12: LL=-1247498.86 | Rates: N=0.82180, AF=0.09698, OLD=0.08346, YOUNG=0.03246
A =
[[0.99455513 0.00142922 0.00401564]
 [0.00645565 0.98619775 0.0073466 ]
 [0.00418036 0.0014012  0.99441844]]
pi = [0.29935478 0.23474819 0.46589703]
Iter 13: LL=-1247489.59 | Rates: N=0.82180, AF=0.09696, OLD=0.08530, YOUNG=0.03256
A =
[[0.99455593 0.00138472 0.00405935]
 [0.00650406 0.98557496 0.00792098]
 [0.00418951 0.00143661 0.99437388]]
pi = [0.299331   0.23247858 0.46819042]
Iter 14: LL=-1247480.76 | Rates: N=0.82180, AF=0.09695, OLD=0.08718, YOUNG=0.03265
A =
[[0.99455673 0.00134199 0.00410127]
 [0.0065526  0.98493419 0.00851321]
 [0.00419816 0.00147041 0.99433143]]
pi = [0.29930767 0.23008619 0.47060614]
Iter 15: LL=-1247472.36 | Rates: N=0.82180, AF=0.09694, OLD=0.08908, YOUNG=0.03274
A =
[[0.99455754 0.00130114 0.00414132]
 [0.00660177 0.98427599 0.00912224]
 [0.00420625 0.00150247 0.99429128]]
pi = [0.29928461 0.22760485 0.47311054]
Final Global Rates (lambdas): [0.82180136 0.09694095 0.0890781  0.03273922]
Final transition matrix A:
[[0.99455754 0.00130114 0.00414132]
 [0.00660177 0.98427599 0.00912224]
 [0.00420625 0.00150247 0.99429128]]
Final initial distribution pi:
[0.29928461 0.22760485 0.47311054]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2423  0.1558  0.1897    8016778.0   25066222.0  43442074.0
Archaic_young     0.9102  0.9449  0.9272  468980148.0   46278852.0  27323815.0
Modern            0.0000  0.0000  0.0000          0.0  451658000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         447073          139           2459
Archaic_old      1060         8007          42628
Archaic_young    3525        24937         470172

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1926  0.2100  0.2010
Archaic_young     0.9229  0.9179  0.9204

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         446675          315           2719
Archaic_old       902         9384          34553
Archaic_young    3661        38932         462859

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1456386.15 | Rates: N=0.82394, AF=0.09775, OLD=0.06549, YOUNG=0.03519
A =
[[0.99392103 0.00163814 0.00444082]
 [0.00640541 0.99006336 0.00353123]
 [0.00474194 0.00101351 0.99424455]]
pi = [0.60194006 0.0664995  0.33156044]
Iter 2: LL=-1251720.54 | Rates: N=0.82411, AF=0.09769, OLD=0.07013, YOUNG=0.03381
A =
[[0.99395486 0.00163082 0.00441432]
 [0.00660437 0.98978527 0.00361035]
 [0.0046497  0.00104489 0.99430541]]
pi = [0.60707941 0.03840814 0.35451245]
Iter 3: LL=-1251669.61 | Rates: N=0.82411, AF=0.09765, OLD=0.07340, YOUNG=0.03325
A =
[[0.99395567 0.00161657 0.00442776]
 [0.0068489  0.98932895 0.00382215]
 [0.00459811 0.00109898 0.99430291]]
pi = [0.60703972 0.02140232 0.37155796]
Iter 4: LL=-1251647.93 | Rates: N=0.82411, AF=0.09762, OLD=0.07583, YOUNG=0.03306
A =
[[0.99395506 0.00158673 0.00445821]
 [0.00710022 0.98876165 0.00413813]
 [0.00455699 0.0011589  0.99428411]]
pi = [0.60691582 0.01177502 0.38130916]
Iter 5: LL=-1251634.00 | Rates: N=0.82411, AF=0.09760, OLD=0.07785, YOUNG=0.03303
A =
[[0.99395463 0.00154904 0.00449632]
 [0.00733401 0.98815009 0.0045159 ]
 [0.00452677 0.00121971 0.99425351]]
pi = [0.60685841 0.00649283 0.38664876]
Iter 6: LL=-1251622.35 | Rates: N=0.82411, AF=0.09758, OLD=0.07970, YOUNG=0.03306
A =
[[0.99395441 0.00150816 0.00453743]
 [0.0075438  0.98752301 0.00493319]
 [0.00450592 0.00127906 0.99421502]]
pi = [0.60684292 0.00359854 0.38955854]
Iter 7: LL=-1251611.84 | Rates: N=0.82411, AF=0.09757, OLD=0.08147, YOUNG=0.03311
A =
[[0.99395433 0.00146657 0.00457909]
 [0.00773014 0.98689124 0.00537862]
 [0.00449237 0.00133595 0.99417168]]
pi = [0.60684969 0.00200267 0.39114764]
Iter 8: LL=-1251602.20 | Rates: N=0.82411, AF=0.09755, OLD=0.08319, YOUNG=0.03317
A =
[[0.99395435 0.00142567 0.00461998]
 [0.00789592 0.98625833 0.00584575]
 [0.00448428 0.00138999 0.99412573]]
pi = [0.60686779 0.00111719 0.39201502]
Iter 9: LL=-1251593.32 | Rates: N=0.82411, AF=0.09754, OLD=0.08488, YOUNG=0.03323
A =
[[0.99395444 0.00138619 0.00465937]
 [0.00804449 0.98562516 0.00633035]
 [0.00448017 0.00144107 0.99407876]]
pi = [0.60689132 0.00062374 0.39248494]
Iter 10: LL=-1251585.14 | Rates: N=0.82411, AF=0.09752, OLD=0.08654, YOUNG=0.03329
A =
[[0.99395458 0.00134855 0.00469687]
 [0.00817899 0.98499189 0.00682912]
 [0.0044789  0.00148921 0.99403188]]
pi = [6.06917093e-01 3.48106927e-04 3.92734800e-01]
Iter 11: LL=-1251577.61 | Rates: N=0.82411, AF=0.09751, OLD=0.08818, YOUNG=0.03334
A =
[[0.99395475 0.00131295 0.00473229]
 [0.00830211 0.98435871 0.00733918]
 [0.00447963 0.00153449 0.99398588]]
pi = [6.06943348e-01 1.94037270e-04 3.92862615e-01]
Iter 12: LL=-1251570.70 | Rates: N=0.82411, AF=0.09750, OLD=0.08979, YOUNG=0.03340
A =
[[0.99395495 0.00127946 0.00476559]
 [0.00841607 0.98372604 0.00785789]
 [0.00448173 0.001577   0.99394127]]
pi = [6.06969118e-01 1.07960806e-04 3.92922921e-01]
Iter 13: LL=-1251564.36 | Rates: N=0.82410, AF=0.09748, OLD=0.09138, YOUNG=0.03345
A =
[[0.99395517 0.00124806 0.00479678]
 [0.00852264 0.98309459 0.00838277]
 [0.00448473 0.00161686 0.99389841]]
pi = [6.06993883e-01 5.99362558e-05 3.92946181e-01]
Iter 14: LL=-1251558.55 | Rates: N=0.82410, AF=0.09747, OLD=0.09294, YOUNG=0.03350
A =
[[0.99395539 0.00121869 0.00482593]
 [0.00862322 0.98246534 0.00891144]
 [0.00448829 0.00165421 0.9938575 ]]
pi = [6.07017379e-01 3.31935478e-05 3.92949427e-01]
Iter 15: LL=-1251553.24 | Rates: N=0.82410, AF=0.09746, OLD=0.09448, YOUNG=0.03356
A =
[[0.99395561 0.00119124 0.00485315]
 [0.00871891 0.98183939 0.0094417 ]
 [0.00449218 0.00168916 0.99381866]]
pi = [6.07039498e-01 1.83358999e-05 3.92942166e-01]
Final Global Rates (lambdas): [0.82410354 0.09745815 0.09447752 0.03355658]
Final transition matrix A:
[[0.99395561 0.00119124 0.00485315]
 [0.00871891 0.98183939 0.0094417 ]
 [0.00449218 0.00168916 0.99381866]]
Final initial distribution pi:
[6.07039498e-01 1.83358999e-05 3.92942166e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2957  0.1656  0.2123    7386840.0   17596160.0  37222564.0
Archaic_young     0.9225  0.9597  0.9407  482588280.0   40546720.0  20248496.0
Modern            0.0000  0.0000  0.0000          0.0  451882000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         446841           63           2805
Archaic_old      1063         7383          36393
Archaic_young    3978        17537         483937

================================================================================
RUN: {'p_old': 0.1, 'p_young': 0.5, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1921  0.1422  0.1634
Archaic_young     0.9177  0.9398  0.9286

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         428655          122           2880
Archaic_old      1289         6686          39263
Archaic_young    4403        28088         488614

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1449561.22 | Rates: N=0.81525, AF=0.09684, OLD=0.07203, YOUNG=0.03847
A =
[[0.99340491 0.00159408 0.00500102]
 [0.00660179 0.98891674 0.00448147]
 [0.004828   0.00101442 0.99415758]]
pi = [0.45046093 0.12683914 0.42269994]
Iter 2: LL=-1252130.81 | Rates: N=0.81542, AF=0.09683, OLD=0.07894, YOUNG=0.03639
A =
[[0.99348161 0.0016306  0.00488779]
 [0.00654162 0.98891076 0.00454762]
 [0.00475178 0.00103286 0.99421535]]
pi = [0.45217482 0.12173522 0.42608996]
Iter 3: LL=-1252035.02 | Rates: N=0.81541, AF=0.09677, OLD=0.08341, YOUNG=0.03553
A =
[[0.99348695 0.00165442 0.00485863]
 [0.00662165 0.98850871 0.00486964]
 [0.00473065 0.00107679 0.99419256]]
pi = [0.45223777 0.11351886 0.43424337]
Iter 4: LL=-1252002.90 | Rates: N=0.81541, AF=0.09672, OLD=0.08646, YOUNG=0.03524
A =
[[0.99348746 0.00165213 0.00486042]
 [0.00675262 0.98788394 0.00536344]
 [0.00471338 0.00112959 0.99415703]]
pi = [0.45228306 0.10334652 0.44437042]
Iter 5: LL=-1251985.59 | Rates: N=0.81541, AF=0.09669, OLD=0.08890, YOUNG=0.03519
A =
[[0.99348762 0.00163565 0.00487673]
 [0.00688649 0.98717557 0.00593794]
 [0.00470107 0.00118587 0.99411306]]
pi = [0.45234307 0.09253554 0.4551214 ]
Iter 6: LL=-1251971.73 | Rates: N=0.81541, AF=0.09666, OLD=0.09110, YOUNG=0.03521
A =
[[0.99348783 0.00161177 0.0049004 ]
 [0.00700956 0.98643936 0.00655108]
 [0.00469339 0.00124256 0.99406405]]
pi = [0.45240682 0.08164457 0.46594861]
Iter 7: LL=-1251959.41 | Rates: N=0.81541, AF=0.09664, OLD=0.09319, YOUNG=0.03527
A =
[[0.99348813 0.00158399 0.00492788]
 [0.0071201  0.98569526 0.00718464]
 [0.00468923 0.00129814 0.99401263]]
pi = [0.45246868 0.07097695 0.47655437]
Iter 8: LL=-1251948.25 | Rates: N=0.81541, AF=0.09662, OLD=0.09522, YOUNG=0.03533
A =
[[0.99348849 0.00155428 0.00495723]
 [0.00721978 0.9849499  0.00783032]
 [0.00468752 0.00135184 0.99396064]]
pi = [0.4525255  0.06076131 0.48671319]
Iter 9: LL=-1251938.09 | Rates: N=0.81540, AF=0.09660, OLD=0.09721, YOUNG=0.03539
A =
[[0.99348889 0.00152383 0.00498728]
 [0.00731088 0.98420529 0.00848383]
 [0.00468746 0.00140323 0.9939093 ]]
pi = [0.45257546 0.05119417 0.49623037]
Iter 10: LL=-1251928.84 | Rates: N=0.81540, AF=0.09659, OLD=0.09917, YOUNG=0.03546
A =
[[0.99348932 0.00149339 0.00501729]
 [0.00739546 0.98346205 0.00914248]
 [0.00468847 0.00145208 0.99385945]]
pi = [0.45261782 0.04243815 0.50494403]
Iter 11: LL=-1251920.41 | Rates: N=0.81540, AF=0.09657, OLD=0.10111, YOUNG=0.03553
A =
[[0.99348976 0.00146345 0.00504679]
 [0.00747521 0.9827205  0.0098043 ]
 [0.00469015 0.00149827 0.99381158]]
pi = [0.45265272 0.03461053 0.51273675]
Iter 12: LL=-1251912.71 | Rates: N=0.81540, AF=0.09656, OLD=0.10301, YOUNG=0.03559
A =
[[0.99349018 0.00143434 0.00507547]
 [0.00755144 0.98198089 0.01046767]
 [0.00469222 0.00154175 0.99376603]]
pi = [0.45268091 0.02777508 0.51954401]
Iter 13: LL=-1251905.70 | Rates: N=0.81540, AF=0.09654, OLD=0.10489, YOUNG=0.03565
A =
[[0.9934906  0.00140627 0.00510314]
 [0.00762522 0.9812435  0.01113128]
 [0.00469447 0.00158255 0.99372298]]
pi = [0.45270347 0.02194143 0.5253551 ]
Iter 14: LL=-1251899.29 | Rates: N=0.81540, AF=0.09653, OLD=0.10674, YOUNG=0.03572
A =
[[0.99349099 0.00137934 0.00512968]
 [0.00769741 0.98050858 0.01179401]
 [0.00469677 0.00162073 0.9936825 ]]
pi = [0.45272153 0.01707153 0.53020694]
Iter 15: LL=-1251893.42 | Rates: N=0.81540, AF=0.09652, OLD=0.10857, YOUNG=0.03578
A =
[[0.99349135 0.00135361 0.00515504]
 [0.00776872 0.97977633 0.01245495]
 [0.00469903 0.00165638 0.9936446 ]]
pi = [0.45273612 0.01309071 0.53417318]
Final Global Rates (lambdas): [0.81539686 0.09651754 0.1085691  0.03578156]
Final transition matrix A:
[[0.99349135 0.00135361 0.00515504]
 [0.00776872 0.97977633 0.01245495]
 [0.00469903 0.00165638 0.9936446 ]]
Final initial distribution pi:
[0.45273612 0.01309071 0.53417318]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.1_pyoung_0.5_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2591  0.1346  0.1771    6341776.0   18131224.0  40787249.0
Archaic_young     0.9186  0.9599  0.9388  497471907.0   44105093.0  20773640.0
Modern            0.0000  0.0000  0.0000          0.0  433950000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         428567          245           2845
Archaic_old      1194         6334          39710
Archaic_young    4189        17894         499022

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6490  0.9885  0.7836
Archaic_young     0.7228  0.0080  0.0159

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         733294         1990              3
Archaic_old      2390       170603            275
Archaic_young    1267        89449            729

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1616481.36 | Rates: N=0.95145, AF=0.09674, OLD=0.04301, YOUNG=0.03346
A =
[[9.97479897e-01 1.83184553e-03 6.88257021e-04]
 [7.18104320e-03 9.91988569e-01 8.30388113e-04]
 [7.30697130e-03 2.27212823e-03 9.90420900e-01]]
pi = [0.65260063 0.24231111 0.10508826]
Iter 2: LL=-1300090.29 | Rates: N=0.95168, AF=0.09649, OLD=0.04447, YOUNG=0.03040
A =
[[9.97470247e-01 1.82361943e-03 7.06133594e-04]
 [7.33650230e-03 9.91805676e-01 8.57822076e-04]
 [6.93061913e-03 2.14763956e-03 9.90921741e-01]]
pi = [0.6513608  0.23412177 0.11451743]
Iter 3: LL=-1300053.52 | Rates: N=0.95169, AF=0.09648, OLD=0.04634, YOUNG=0.02765
A =
[[9.97469843e-01 1.79857462e-03 7.31582402e-04]
 [7.53482203e-03 9.91570352e-01 8.94826161e-04]
 [6.53832654e-03 2.00135354e-03 9.91460320e-01]]
pi = [0.65133288 0.22353366 0.12513346]
Iter 4: LL=-1300016.39 | Rates: N=0.95169, AF=0.09647, OLD=0.04812, YOUNG=0.02579
A =
[[9.97469716e-01 1.76606192e-03 7.64221953e-04]
 [7.71477594e-03 9.91347344e-01 9.37879675e-04]
 [6.26974433e-03 1.89307033e-03 9.91837185e-01]]
pi = [0.651307   0.21320904 0.13548396]
Iter 5: LL=-1299993.21 | Rates: N=0.95169, AF=0.09645, OLD=0.04951, YOUNG=0.02479
A =
[[9.97469478e-01 1.73063724e-03 7.99884378e-04]
 [7.83584963e-03 9.91177247e-01 9.86903441e-04]
 [6.14405704e-03 1.84526890e-03 9.92010674e-01]]
pi = [0.65129092 0.20435707 0.14435201]
Iter 6: LL=-1299982.22 | Rates: N=0.95169, AF=0.09644, OLD=0.05051, YOUNG=0.02436
A =
[[9.97469313e-01 1.69429772e-03 8.36389591e-04]
 [7.90651636e-03 9.91050256e-01 1.04322799e-03]
 [6.10594206e-03 1.84193122e-03 9.92052127e-01]]
pi = [0.65128534 0.19684014 0.15187451]
Iter 7: LL=-1299976.54 | Rates: N=0.95169, AF=0.09644, OLD=0.05126, YOUNG=0.02425
A =
[[9.97469271e-01 1.65792959e-03 8.72799358e-04]
 [7.94916808e-03 9.90944261e-01 1.10657074e-03]
 [6.10775725e-03 1.86274840e-03 9.92029494e-01]]
pi = [0.65128532 0.19014668 0.15856799]
Iter 8: LL=-1299972.56 | Rates: N=0.95169, AF=0.09643, OLD=0.05188, YOUNG=0.02429
A =
[[9.97469311e-01 1.62198261e-03 9.08706641e-04]
 [7.97969575e-03 9.90844324e-01 1.17597997e-03]
 [6.12419316e-03 1.89467599e-03 9.91981131e-01]]
pi = [0.65128748 0.18391031 0.16480221]
Iter 9: LL=-1299969.09 | Rates: N=0.95169, AF=0.09643, OLD=0.05243, YOUNG=0.02441
A =
[[9.97469387e-01 1.58666234e-03 9.43951142e-04]
 [8.00626690e-03 9.90743064e-01 1.25066881e-03]
 [6.14426333e-03 1.93090030e-03 9.91924836e-01]]
pi = [0.65129034 0.17793962 0.17077004]
Iter 10: LL=-1299965.81 | Rates: N=0.95169, AF=0.09643, OLD=0.05295, YOUNG=0.02457
A =
[[9.97469473e-01 1.55204309e-03 9.78484069e-04]
 [8.03243683e-03 9.90637399e-01 1.33016447e-03]
 [6.16388114e-03 1.96816366e-03 9.91867955e-01]]
pi = [0.65129338 0.17214633 0.17656029]
Iter 11: LL=-1299962.63 | Rates: N=0.95169, AF=0.09642, OLD=0.05347, YOUNG=0.02474
A =
[[0.99746956 0.00151814 0.0010123 ]
 [0.00805952 0.99052624 0.00141423]
 [0.00618187 0.00200499 0.99181314]]
pi = [0.65129642 0.16649197 0.18221161]
Iter 12: LL=-1299959.53 | Rates: N=0.95169, AF=0.09642, OLD=0.05398, YOUNG=0.02492
A =
[[0.99746964 0.00148494 0.00104542]
 [0.00808787 0.99040934 0.00150279]
 [0.00619817 0.00204074 0.99176109]]
pi = [0.65129941 0.16096001 0.18774058]
Iter 13: LL=-1299956.50 | Rates: N=0.95169, AF=0.09642, OLD=0.05450, YOUNG=0.02511
A =
[[0.99746972 0.00145244 0.00107784]
 [0.00811744 0.99028671 0.00159584]
 [0.00621304 0.00207518 0.99171178]]
pi = [0.65130232 0.15554316 0.19315451]
Iter 14: LL=-1299953.53 | Rates: N=0.95169, AF=0.09642, OLD=0.05502, YOUNG=0.02529
A =
[[0.99746979 0.00142063 0.00110959]
 [0.0081481  0.99015845 0.00169345]
 [0.0062268  0.00210825 0.99166496]]
pi = [0.65130516 0.15023788 0.19845696]
Iter 15: LL=-1299950.63 | Rates: N=0.95169, AF=0.09641, OLD=0.05555, YOUNG=0.02547
A =
[[0.99746985 0.00138948 0.00114067]
 [0.00817968 0.99002463 0.00179569]
 [0.00623972 0.00213994 0.99162034]]
pi = [0.65130791 0.14504216 0.20364993]
Final Global Rates (lambdas): [0.95169079 0.09641447 0.05554976 0.02546857]
Final transition matrix A:
[[0.99746985 0.00138948 0.00114067]
 [0.00817968 0.99002463 0.00179569]
 [0.00623972 0.00213994 0.99162034]]
Final initial distribution pi:
[0.65130791 0.14504216 0.20364993]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.6342  0.4663  0.5375  80233679.0   46268321.0  91813896.0
Archaic_young     0.3301  0.4986  0.3972  45212909.0   91761091.0  45469734.0
Modern            0.0000  0.0000  0.0000         0.0  736524000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         733212         1108            967
Archaic_old      2168        80511          90589
Archaic_young    1144        44883          45418

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6111  0.9888  0.7553
Archaic_young     1.0000  0.0041  0.0081

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         701306         2491              0
Archaic_old      2801       180078              0
Archaic_young    1548       111318            458

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1594551.69 | Rates: N=0.93359, AF=0.09511, OLD=0.04479, YOUNG=0.03602
A =
[[9.96890412e-01 2.20157560e-03 9.08012653e-04]
 [7.65060489e-03 9.91310090e-01 1.03930554e-03]
 [7.50644123e-03 2.47632157e-03 9.90017237e-01]]
pi = [0.70554249 0.20240008 0.09205743]
Iter 2: LL=-1295867.02 | Rates: N=0.93385, AF=0.09488, OLD=0.04595, YOUNG=0.03315
A =
[[9.96885860e-01 2.18812141e-03 9.26018225e-04]
 [7.76510577e-03 9.91165470e-01 1.06942435e-03]
 [7.22619472e-03 2.36196108e-03 9.90411844e-01]]
pi = [0.7045251  0.1950306  0.10044429]
Iter 3: LL=-1295835.40 | Rates: N=0.93385, AF=0.09487, OLD=0.04765, YOUNG=0.03065
A =
[[9.96885976e-01 2.16334440e-03 9.50679340e-04]
 [7.93069704e-03 9.90960696e-01 1.10860701e-03]
 [6.92882386e-03 2.22382573e-03 9.90847350e-01]]
pi = [0.70453879 0.18238458 0.11307663]
Iter 4: LL=-1295802.22 | Rates: N=0.93385, AF=0.09486, OLD=0.04936, YOUNG=0.02882
A =
[[9.96886199e-01 2.12949258e-03 9.84308510e-04]
 [8.10584010e-03 9.90736547e-01 1.15761278e-03]
 [6.67956193e-03 2.09574235e-03 9.91224696e-01]]
pi = [0.70461751 0.16564993 0.12973256]
Iter 5: LL=-1295778.35 | Rates: N=0.93385, AF=0.09485, OLD=0.05081, YOUNG=0.02777
A =
[[0.9968862  0.00209022 0.00102358]
 [0.00825108 0.990535   0.00121391]
 [0.00652593 0.00200659 0.99146748]]
pi = [0.70477075 0.14773945 0.14748979]
Iter 6: LL=-1295765.07 | Rates: N=0.93385, AF=0.09484, OLD=0.05194, YOUNG=0.02728
A =
[[0.9968861  0.00204778 0.00106612]
 [0.00835663 0.99036621 0.00127717]
 [0.0064522  0.00195499 0.99159281]]
pi = [0.70498896 0.13155977 0.16345127]
Iter 7: LL=-1295757.65 | Rates: N=0.93385, AF=0.09483, OLD=0.05283, YOUNG=0.02714
A =
[[0.99688603 0.00200335 0.00111062]
 [0.00843233 0.99022047 0.00134721]
 [0.006427   0.00192813 0.99164488]]
pi = [0.70522874 0.11844308 0.17632819]
Iter 8: LL=-1295752.47 | Rates: N=0.93385, AF=0.09482, OLD=0.05357, YOUNG=0.02718
A =
[[0.99688602 0.00195766 0.00115632]
 [0.00849036 0.99008609 0.00142355]
 [0.00642726 0.00191499 0.99165775]]
pi = [0.70544572 0.10837407 0.18618021]
Iter 9: LL=-1295747.99 | Rates: N=0.93385, AF=0.09482, OLD=0.05424, YOUNG=0.02732
A =
[[0.99688606 0.00191123 0.00120272]
 [0.00853921 0.98995505 0.00150574]
 [0.00643997 0.00190888 0.99165115]]
pi = [0.70561602 0.10077915 0.19360482]
Iter 10: LL=-1295743.69 | Rates: N=0.93385, AF=0.09482, OLD=0.05488, YOUNG=0.02751
A =
[[0.99688612 0.00186437 0.00124951]
 [0.00858376 0.98982266 0.00159358]
 [0.00645848 0.00190622 0.9916353 ]]
pi = [0.70573514 0.09502446 0.19924041]
Iter 11: LL=-1295739.43 | Rates: N=0.93385, AF=0.09482, OLD=0.05551, YOUNG=0.02772
A =
[[0.9968862  0.00181732 0.00129647]
 [0.00862667 0.98968624 0.00168709]
 [0.00647954 0.0019052  0.99161527]]
pi = [0.70580881 0.09059135 0.20359985]
Iter 12: LL=-1295735.17 | Rates: N=0.93385, AF=0.09481, OLD=0.05615, YOUNG=0.02794
A =
[[0.9968863  0.00177023 0.00134347]
 [0.00866937 0.98954416 0.00178648]
 [0.00650155 0.00190494 0.99159351]]
pi = [0.70584596 0.08709859 0.20705546]
Iter 13: LL=-1295730.89 | Rates: N=0.93385, AF=0.09481, OLD=0.05681, YOUNG=0.02816
A =
[[0.9968864  0.00172321 0.00139039]
 [0.00871265 0.98939527 0.00189208]
 [0.00652374 0.00190501 0.99157125]]
pi = [0.70585516 0.08427749 0.20986735]
Iter 14: LL=-1295726.58 | Rates: N=0.93385, AF=0.09481, OLD=0.05749, YOUNG=0.02838
A =
[[0.9968865  0.00167634 0.00143716]
 [0.00875702 0.98923866 0.00200432]
 [0.00654571 0.00190522 0.99154907]]
pi = [0.70584347 0.08194128 0.21221525]
Iter 15: LL=-1295722.24 | Rates: N=0.93385, AF=0.09481, OLD=0.05819, YOUNG=0.02860
A =
[[0.99688661 0.0016297  0.00148369]
 [0.00880282 0.98907349 0.00212369]
 [0.00656725 0.00190546 0.99152729]]
pi = [0.7058163  0.07996013 0.21422357]
Final Global Rates (lambdas): [0.93385272 0.09480622 0.05818986 0.02859754]
Final transition matrix A:
[[0.99688661 0.0016297  0.00148369]
 [0.00880282 0.98907349 0.00212369]
 [0.00656725 0.00190546 0.99152729]]
Final initial distribution pi:
[0.7058163  0.07996013 0.21422357]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.6428  0.4229  0.5102  76804800.0   42684200.0  104811660.0
Archaic_young     0.4004  0.6257  0.4883  70238311.0  105186689.0   42022983.0
Modern            0.0000  0.0000  0.0000         0.0  705086000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         701227         1098           1472
Archaic_old      2480        77057         103342
Archaic_young    1379        41334          70611

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6357  0.9856  0.7729
Archaic_young     0.0000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         673514         2824              2
Archaic_old      3601       204706            333
Archaic_young    1414       113606              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 18
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1584614.70 | Rates: N=0.91923, AF=0.09655, OLD=0.04747, YOUNG=0.03913
A =
[[0.9962243  0.00263    0.00114569]
 [0.00829606 0.99045733 0.0012466 ]
 [0.00782602 0.00270753 0.98946646]]
pi = [0.64956432 0.24668251 0.10375317]
Iter 2: LL=-1298608.68 | Rates: N=0.91951, AF=0.09640, OLD=0.04848, YOUNG=0.03610
A =
[[0.99622322 0.00261744 0.00115934]
 [0.00847652 0.99023033 0.00129315]
 [0.00744449 0.00258237 0.98997314]]
pi = [0.64819536 0.2536073  0.09819734]
Iter 3: LL=-1298571.59 | Rates: N=0.91952, AF=0.09640, OLD=0.05043, YOUNG=0.03342
A =
[[0.99622304 0.00260052 0.00117644]
 [0.00873634 0.989912   0.00135167]
 [0.00704697 0.00244072 0.99051231]]
pi = [0.64814277 0.26157523 0.090282  ]
Iter 4: LL=-1298526.98 | Rates: N=0.91952, AF=0.09638, OLD=0.05256, YOUNG=0.03131
A =
[[0.99622258 0.00257396 0.00120346]
 [0.00903183 0.98953865 0.00142952]
 [0.00669272 0.00231074 0.99099654]]
pi = [0.64809132 0.2697207  0.08218799]
Iter 5: LL=-1298490.51 | Rates: N=0.91952, AF=0.09636, OLD=0.05446, YOUNG=0.02999
A =
[[0.99622168 0.00253944 0.00123888]
 [0.00929972 0.98917506 0.00152522]
 [0.0064526  0.00223137 0.99131603]]
pi = [0.64801652 0.27672199 0.07526149]
Iter 6: LL=-1298468.66 | Rates: N=0.91952, AF=0.09634, OLD=0.05598, YOUNG=0.02932
A =
[[0.99622069 0.00249856 0.00128076]
 [0.00951275 0.98884846 0.00163879]
 [0.00631876 0.00220459 0.99147665]]
pi = [0.64794147 0.28181467 0.07024386]
Iter 7: LL=-1298456.31 | Rates: N=0.91952, AF=0.09632, OLD=0.05720, YOUNG=0.02906
A =
[[0.99621989 0.00245275 0.00132735]
 [0.0096789  0.98855145 0.00176965]
 [0.00625505 0.00221365 0.9915313 ]]
pi = [0.64788469 0.28484687 0.06726845]
Iter 8: LL=-1298447.85 | Rates: N=0.91952, AF=0.09631, OLD=0.05822, YOUNG=0.02902
A =
[[0.99621936 0.00240345 0.00137719]
 [0.00981486 0.98826885 0.00191629]
 [0.00623184 0.0022426  0.99152556]]
pi = [0.64784906 0.28597664 0.0661743 ]
Iter 9: LL=-1298440.60 | Rates: N=0.91952, AF=0.09630, OLD=0.05915, YOUNG=0.02910
A =
[[0.99621902 0.00235186 0.00142912]
 [0.00993358 0.98798915 0.00207727]
 [0.00623132 0.00228119 0.9914875 ]]
pi = [0.64782984 0.28541989 0.06675027]
Iter 10: LL=-1298433.64 | Rates: N=0.91952, AF=0.09629, OLD=0.06004, YOUNG=0.02923
A =
[[0.99621882 0.0022988  0.00148238]
 [0.01004289 0.98770541 0.0022517 ]
 [0.00624383 0.00232371 0.99143246]]
pi = [0.64782138 0.28335624 0.06882238]
Iter 11: LL=-1298426.70 | Rates: N=0.91952, AF=0.09628, OLD=0.06092, YOUNG=0.02939
A =
[[0.99621869 0.00224485 0.00153646]
 [0.01014708 0.98741372 0.00243919]
 [0.00626426 0.00236718 0.99136856]]
pi = [0.64781924 0.27992239 0.07225836]
Iter 12: LL=-1298419.71 | Rates: N=0.91952, AF=0.09628, OLD=0.06183, YOUNG=0.02956
A =
[[0.99621863 0.00219039 0.00159099]
 [0.01024845 0.98711183 0.00263972]
 [0.00628981 0.00241005 0.99130014]]
pi = [0.64782035 0.2752334  0.07694624]
Iter 13: LL=-1298412.67 | Rates: N=0.91953, AF=0.09627, OLD=0.06276, YOUNG=0.02973
A =
[[0.9962186  0.00213568 0.00164572]
 [0.01034819 0.98679835 0.00285346]
 [0.00631888 0.00245155 0.99122958]]
pi = [0.64782275 0.26940595 0.0827713 ]
Iter 14: LL=-1298405.58 | Rates: N=0.91953, AF=0.09626, OLD=0.06372, YOUNG=0.02990
A =
[[0.99621861 0.00208093 0.00170046]
 [0.01044698 0.98647234 0.00308068]
 [0.00635046 0.00249124 0.9911583 ]]
pi = [0.64782544 0.26257428 0.08960028]
Iter 15: LL=-1298398.44 | Rates: N=0.91953, AF=0.09626, OLD=0.06472, YOUNG=0.03008
A =
[[0.99621865 0.0020263  0.00175505]
 [0.01054518 0.98613307 0.00332175]
 [0.00638387 0.00252891 0.99108722]]
pi = [0.64782814 0.25489567 0.09727619]
Final Global Rates (lambdas): [0.91952531 0.0962562  0.06471674 0.0300758 ]
Final transition matrix A:
[[0.99621865 0.0020263  0.00175505]
 [0.01054518 0.98613307 0.00332175]
 [0.00638387 0.00252891 0.99108722]]
Final initial distribution pi:
[0.64782814 0.25489567 0.09727619]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.7003  0.3769  0.4900  78057472.0   33405528.0  129067438.0
Archaic_young     0.3869  0.7152  0.5022  81435045.0  129023955.0   32428342.0
Modern            0.0000  0.0000  0.0000         0.0  678078000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         673484         1277           1579
Archaic_old      3276        78379         126985
Archaic_young    1318        31807          81895

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6065  0.9834  0.7503
Archaic_young     0.0000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         717367         2717              0
Archaic_old      3808       168464              0
Archaic_young    1987       105657              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 18
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1618213.56 | Rates: N=0.93856, AF=0.09706, OLD=0.05627, YOUNG=0.04675
A =
[[0.99647078 0.002457   0.00107221]
 [0.00948075 0.989137   0.00138224]
 [0.00930256 0.00308522 0.98761222]]
pi = [0.79941242 0.14746219 0.05312539]
Iter 2: LL=-1313527.55 | Rates: N=0.93884, AF=0.09691, OLD=0.05768, YOUNG=0.04269
A =
[[0.99648875 0.00242974 0.00108151]
 [0.0095855  0.98897748 0.00143702]
 [0.00887899 0.00293495 0.98818606]]
pi = [0.80196373 0.15701756 0.0410187 ]
Iter 3: LL=-1313480.41 | Rates: N=0.93884, AF=0.09690, OLD=0.06033, YOUNG=0.03890
A =
[[0.99649011 0.00240563 0.00110426]
 [0.00983816 0.98864306 0.00151878]
 [0.00845039 0.00274156 0.98880806]]
pi = [0.80187235 0.17022926 0.02789838]
Iter 4: LL=-1313420.09 | Rates: N=0.93884, AF=0.09688, OLD=0.06328, YOUNG=0.03598
A =
[[0.99649015 0.00236965 0.0011402 ]
 [0.01013771 0.98822306 0.00163923]
 [0.00807026 0.00255574 0.989374  ]]
pi = [0.8016222  0.18166358 0.01671421]
Iter 5: LL=-1313370.53 | Rates: N=0.93884, AF=0.09685, OLD=0.06593, YOUNG=0.03426
A =
[[0.99648949 0.00232598 0.00118453]
 [0.01039526 0.98780777 0.00179697]
 [0.00784358 0.00244045 0.98971596]]
pi = [0.80137341 0.18944343 0.00918316]
Iter 6: LL=-1313341.32 | Rates: N=0.93884, AF=0.09682, OLD=0.06805, YOUNG=0.03345
A =
[[0.99648854 0.00227775 0.00123371]
 [0.01058015 0.98742893 0.00199092]
 [0.00775076 0.00239733 0.98985191]]
pi = [0.80118531 0.19396587 0.00484882]
Iter 7: LL=-1313324.41 | Rates: N=0.93885, AF=0.09680, OLD=0.06976, YOUNG=0.03320
A =
[[0.99648773 0.00222654 0.00128573]
 [0.01070979 0.98707164 0.00221857]
 [0.00773527 0.00240097 0.98986376]]
pi = [0.80106209 0.19639152 0.00254639]
Iter 8: LL=-1313312.01 | Rates: N=0.93885, AF=0.09679, OLD=0.07124, YOUNG=0.03323
A =
[[0.99648715 0.00217352 0.00133933]
 [0.01080836 0.98671489 0.00247674]
 [0.00775678 0.00242962 0.9898136 ]]
pi = [0.80098323 0.19766094 0.00135583]
Iter 9: LL=-1313300.86 | Rates: N=0.93885, AF=0.09678, OLD=0.07261, YOUNG=0.03340
A =
[[0.99648673 0.00211953 0.00139374]
 [0.01089241 0.98634435 0.00276324]
 [0.00779397 0.00247041 0.98973562]]
pi = [8.00929718e-01 1.98331426e-01 7.38855228e-04]
Iter 10: LL=-1313289.95 | Rates: N=0.93885, AF=0.09677, OLD=0.07397, YOUNG=0.03364
A =
[[0.9964864  0.00206509 0.00144851]
 [0.01097114 0.98595164 0.00307722]
 [0.00783679 0.00251662 0.98964659]]
pi = [8.00890030e-01 1.98696065e-01 4.13904988e-04]
Iter 11: LL=-1313278.99 | Rates: N=0.93885, AF=0.09676, OLD=0.07535, YOUNG=0.03392
A =
[[0.99648611 0.00201052 0.00150337]
 [0.01104941 0.98553173 0.00341887]
 [0.00788075 0.00256485 0.98955441]]
pi = [8.00858210e-01 1.98902933e-01 2.38857369e-04]
Iter 12: LL=-1313267.93 | Rates: N=0.93885, AF=0.09675, OLD=0.07679, YOUNG=0.03420
A =
[[0.99648581 0.001956   0.00155818]
 [0.01112974 0.98508117 0.00378908]
 [0.00792394 0.00261333 0.98946273]]
pi = [8.00831356e-01 1.99026500e-01 1.42144227e-04]
Iter 13: LL=-1313256.73 | Rates: N=0.93885, AF=0.09674, OLD=0.07829, YOUNG=0.03450
A =
[[0.9964855  0.00190166 0.00161284]
 [0.01121354 0.98459724 0.00418922]
 [0.00796562 0.00266114 0.98937323]]
pi = [8.00808081e-01 1.99104639e-01 8.72795577e-05]
Iter 14: LL=-1313245.38 | Rates: N=0.93885, AF=0.09673, OLD=0.07987, YOUNG=0.03480
A =
[[0.99648517 0.00184756 0.00166726]
 [0.0113016  0.98407741 0.00462099]
 [0.00800559 0.00270772 0.98928669]]
pi = [8.00787719e-01 1.99156971e-01 5.53108104e-05]
Iter 15: LL=-1313233.87 | Rates: N=0.93885, AF=0.09672, OLD=0.08154, YOUNG=0.03509
A =
[[0.99648482 0.0017938  0.00172139]
 [0.01139444 0.98351923 0.00508633]
 [0.00804387 0.00275269 0.98920344]]
pi = [8.00769932e-01 1.99193889e-01 3.61795009e-05]
Final Global Rates (lambdas): [0.93884859 0.09672179 0.08154485 0.035094  ]
Final transition matrix A:
[[0.99648482 0.0017938  0.00172139]
 [0.01139444 0.98351923 0.00508633]
 [0.00804387 0.00275269 0.98920344]]
Final initial distribution pi:
[8.00769932e-01 1.99193889e-01 3.61795009e-05]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.6712  0.3182  0.4318  54340238.0   26623762.0  116408838.0
Archaic_young     0.4076  0.7526  0.5288  80082113.0  116398887.0   26331262.0
Modern            0.0000  0.0000  0.0000         0.0  722555000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         717316         1085           1683
Archaic_old      3476        54586         114210
Archaic_young    1763        25293          80588

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall     F1
Archaic_old       0.6134  0.9816  0.755
Archaic_young     0.0000  0.0000  0.000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         719385         2837              0
Archaic_old      4180       169115              0
Archaic_young    1818       102665              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1621849.99 | Rates: N=0.93939, AF=0.09553, OLD=0.06249, YOUNG=0.05221
A =
[[0.99625668 0.00258937 0.00115396]
 [0.01020582 0.98825051 0.00154367]
 [0.01000911 0.00340564 0.98658525]]
pi = [0.67800973 0.22160063 0.10038964]
Iter 2: LL=-1316808.81 | Rates: N=0.93971, AF=0.09536, OLD=0.06433, YOUNG=0.04721
A =
[[0.99628842 0.00254846 0.00116312]
 [0.01031383 0.98808747 0.0015987 ]
 [0.00947289 0.00324027 0.98728684]]
pi = [0.67254146 0.22299939 0.10445915]
Iter 3: LL=-1316742.45 | Rates: N=0.93971, AF=0.09534, OLD=0.06780, YOUNG=0.04251
A =
[[0.9962909  0.00251387 0.00119524]
 [0.01064163 0.98767688 0.00168149]
 [0.00893748 0.00301515 0.98804737]]
pi = [0.67224068 0.22134527 0.10641405]
Iter 4: LL=-1316656.13 | Rates: N=0.93971, AF=0.09530, OLD=0.07165, YOUNG=0.03908
A =
[[0.99629114 0.00246208 0.00124678]
 [0.01102556 0.98717581 0.00179862]
 [0.00848862 0.00280955 0.98870183]]
pi = [0.67217111 0.22038061 0.10744828]
Iter 5: LL=-1316589.78 | Rates: N=0.93971, AF=0.09526, OLD=0.07499, YOUNG=0.03724
A =
[[0.99629052 0.00239906 0.00131041]
 [0.01134092 0.98671274 0.00194634]
 [0.00824492 0.00270074 0.98905434]]
pi = [0.67203165 0.21985917 0.10810918]
Iter 6: LL=-1316554.10 | Rates: N=0.93971, AF=0.09522, OLD=0.07759, YOUNG=0.03654
A =
[[0.99628972 0.00232919 0.00138109]
 [0.01156445 0.98630933 0.00212622]
 [0.00815458 0.00267519 0.98917023]]
pi = [0.67185621 0.21851358 0.10963021]
Iter 7: LL=-1316533.95 | Rates: N=0.93971, AF=0.09520, OLD=0.07970, YOUNG=0.03644
A =
[[0.99628917 0.00225508 0.00145575]
 [0.01172929 0.98593369 0.00233701]
 [0.00814281 0.00269439 0.9891628 ]]
pi = [0.67170536 0.21552473 0.11276991]
Iter 8: LL=-1316518.63 | Rates: N=0.93971, AF=0.09517, OLD=0.08156, YOUNG=0.03664
A =
[[0.99628888 0.00217878 0.00153234]
 [0.01186607 0.98555814 0.00257579]
 [0.00816588 0.00273187 0.98910225]]
pi = [0.67160032 0.21067067 0.11772901]
Iter 9: LL=-1316504.48 | Rates: N=0.93971, AF=0.09516, OLD=0.08334, YOUNG=0.03697
A =
[[0.99628873 0.00210169 0.00160958]
 [0.01199212 0.9851672  0.00284068]
 [0.00820352 0.00277418 0.9890223 ]]
pi = [0.67153888 0.20402035 0.12444077]
Iter 10: LL=-1316490.53 | Rates: N=0.93971, AF=0.09514, OLD=0.08514, YOUNG=0.03736
A =
[[0.99628863 0.00202466 0.00168671]
 [0.01211613 0.98475258 0.00313129]
 [0.00824697 0.00281523 0.9889378 ]]
pi = [0.67151404 0.19575378 0.13273218]
Iter 11: LL=-1316476.55 | Rates: N=0.93971, AF=0.09513, OLD=0.08700, YOUNG=0.03778
A =
[[0.99628853 0.00194817 0.0017633 ]
 [0.01224246 0.98430916 0.00344838]
 [0.00829245 0.00285248 0.98885507]]
pi = [0.6715198  0.18610121 0.14237899]
Iter 12: LL=-1316462.45 | Rates: N=0.93971, AF=0.09511, OLD=0.08895, YOUNG=0.03821
A =
[[0.9962884  0.00187253 0.00183907]
 [0.01237364 0.9838329  0.00379346]
 [0.00833826 0.002885   0.98877674]]
pi = [0.67155142 0.1753241  0.15312449]
Iter 13: LL=-1316448.18 | Rates: N=0.93971, AF=0.09510, OLD=0.09103, YOUNG=0.03864
A =
[[0.99628821 0.00179793 0.00191386]
 [0.01251141 0.98332005 0.00416854]
 [0.00838359 0.00291254 0.98870387]]
pi = [0.6716048  0.16370195 0.16469325]
Iter 14: LL=-1316433.71 | Rates: N=0.93970, AF=0.09508, OLD=0.09323, YOUNG=0.03908
A =
[[0.99628796 0.00172449 0.00198755]
 [0.01265724 0.98276671 0.00457605]
 [0.00842803 0.00293514 0.98863683]]
pi = [0.67167605 0.15151654 0.17680741]
Iter 15: LL=-1316418.99 | Rates: N=0.93970, AF=0.09506, OLD=0.09559, YOUNG=0.03951
A =
[[0.99628762 0.00165229 0.00206008]
 [0.01281248 0.98216874 0.00501878]
 [0.0084714  0.00295297 0.98857563]]
pi = [0.67176138 0.13903503 0.18920358]
Final Global Rates (lambdas): [0.9397049  0.09505852 0.09559364 0.03951357]
Final transition matrix A:
[[0.99628762 0.00165229 0.00206008]
 [0.01281248 0.98216874 0.00501878]
 [0.0084714  0.00295297 0.98857563]]
Final initial distribution pi:
[0.67176138 0.13903503 0.18920358]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.6965  0.2696  0.3887  46265893.0   20160107.0  125341262.0
Archaic_young     0.3971  0.7900  0.5286  81577270.0  123833730.0   21687703.0
Modern            0.0000  0.0000  0.0000         0.0  728163000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         720106          196           1920
Archaic_old      5638        46294         121363
Archaic_young    2419        19936          82128

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6697  0.9643  0.7905
Archaic_young     0.3581  0.0279  0.0518

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         714089         2292             15
Archaic_old      3190       184450           4519
Archaic_young    1165        87745           2535

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1603877.12 | Rates: N=0.93722, AF=0.09695, OLD=0.04601, YOUNG=0.03053
A =
[[9.97023936e-01 2.30525819e-03 6.70805529e-04]
 [7.81812382e-03 9.91429423e-01 7.52452881e-04]
 [7.51732013e-03 2.47492938e-03 9.90007750e-01]]
pi = [0.74655216 0.1814343  0.07201353]
Iter 2: LL=-1300772.70 | Rates: N=0.93747, AF=0.09674, OLD=0.04726, YOUNG=0.02789
A =
[[9.97015170e-01 2.28117632e-03 7.03653584e-04]
 [8.02200755e-03 9.91169806e-01 8.08186144e-04]
 [6.97806696e-03 2.24816388e-03 9.90773769e-01]]
pi = [0.74788909 0.17279456 0.07931635]
Iter 3: LL=-1300743.02 | Rates: N=0.93747, AF=0.09673, OLD=0.04867, YOUNG=0.02630
A =
[[9.97014588e-01 2.24915438e-03 7.36257573e-04]
 [8.19902577e-03 9.90934270e-01 8.66704468e-04]
 [6.64372123e-03 2.08992754e-03 9.91266351e-01]]
pi = [0.747936   0.16540924 0.08665476]
Iter 4: LL=-1300725.13 | Rates: N=0.93747, AF=0.09672, OLD=0.04978, YOUNG=0.02550
A =
[[9.97014274e-01 2.21520137e-03 7.70524269e-04]
 [8.32117659e-03 9.90748879e-01 9.29944348e-04]
 [6.48351985e-03 2.00249816e-03 9.91513982e-01]]
pi = [0.74793938 0.15806346 0.09399716]
Iter 5: LL=-1300716.24 | Rates: N=0.93747, AF=0.09671, OLD=0.05061, YOUNG=0.02518
A =
[[9.97014018e-01 2.18047224e-03 8.05509670e-04]
 [8.39454714e-03 9.90607734e-01 9.97718673e-04]
 [6.43264609e-03 1.96574872e-03 9.91601605e-01]]
pi = [0.74794136 0.1503856  0.10167305]
Iter 6: LL=-1300711.20 | Rates: N=0.93747, AF=0.09671, OLD=0.05124, YOUNG=0.02512
A =
[[9.97013886e-01 2.14521920e-03 8.40895173e-04]
 [8.43782596e-03 9.90492341e-01 1.06983295e-03]
 [6.43590537e-03 1.95783913e-03 9.91606256e-01]]
pi = [0.7479448  0.14212548 0.10992973]
Iter 7: LL=-1300707.37 | Rates: N=0.93747, AF=0.09670, OLD=0.05177, YOUNG=0.02519
A =
[[9.97013852e-01 2.10962636e-03 8.76521446e-04]
 [8.46571515e-03 9.90388385e-01 1.14590016e-03]
 [6.46225554e-03 1.96506922e-03 9.91572675e-01]]
pi = [0.74794992 0.13321181 0.11883827]
Iter 8: LL=-1300703.91 | Rates: N=0.93747, AF=0.09670, OLD=0.05226, YOUNG=0.02533
A =
[[9.97013876e-01 2.07383504e-03 9.12289244e-04]
 [8.48673532e-03 9.90287669e-01 1.22559530e-03]
 [6.49665750e-03 1.98018912e-03 9.91523153e-01]]
pi = [0.74795628 0.12370145 0.12834227]
Iter 9: LL=-1300700.57 | Rates: N=0.93747, AF=0.09670, OLD=0.05272, YOUNG=0.02550
A =
[[9.97013928e-01 2.03793486e-03 9.48137612e-04]
 [8.50529045e-03 9.90185978e-01 1.30873110e-03]
 [6.53234372e-03 1.99957904e-03 9.91468077e-01]]
pi = [0.74796349 0.11372965 0.13830686]
Iter 10: LL=-1300697.28 | Rates: N=0.93747, AF=0.09670, OLD=0.05317, YOUNG=0.02568
A =
[[9.97013992e-01 2.00197870e-03 9.84029038e-04]
 [8.52356173e-03 9.90081203e-01 1.39523478e-03]
 [6.56645705e-03 2.02144854e-03 9.91412094e-01]]
pi = [0.7479713  0.10347735 0.14855135]
Iter 11: LL=-1300694.03 | Rates: N=0.93747, AF=0.09670, OLD=0.05363, YOUNG=0.02587
A =
[[0.99701406 0.001966   0.00101994]
 [0.00854262 0.98997227 0.00148511]
 [0.00659791 0.00204489 0.99135719]]
pi = [0.74797956 0.09314748 0.15887296]
Iter 12: LL=-1300690.80 | Rates: N=0.93747, AF=0.09669, OLD=0.05409, YOUNG=0.02606
A =
[[0.99701413 0.00193002 0.00105585]
 [0.00856301 0.98985858 0.00157841]
 [0.00662642 0.00206942 0.99130416]]
pi = [0.74798813 0.08294551 0.16906635]
Iter 13: LL=-1300687.60 | Rates: N=0.93747, AF=0.09669, OLD=0.05457, YOUNG=0.02625
A =
[[0.99701421 0.00189405 0.00109174]
 [0.00858501 0.98973976 0.00167522]
 [0.006652   0.00209476 0.99125324]]
pi = [0.74799689 0.07306314 0.17893997]
Iter 14: LL=-1300684.41 | Rates: N=0.93747, AF=0.09669, OLD=0.05505, YOUNG=0.02644
A =
[[0.99701428 0.00185812 0.0011276 ]
 [0.00860879 0.98961556 0.00177565]
 [0.00667484 0.00212071 0.99120445]]
pi = [0.74800568 0.06366589 0.18832843]
Iter 15: LL=-1300681.25 | Rates: N=0.93747, AF=0.09669, OLD=0.05555, YOUNG=0.02662
A =
[[0.99701436 0.00182225 0.0011634 ]
 [0.00863446 0.98948574 0.0018798 ]
 [0.00669515 0.00214714 0.99115771]]
pi = [0.74801436 0.05488531 0.19710033]
Final Global Rates (lambdas): [0.93747214 0.09668838 0.05554564 0.02662205]
Final transition matrix A:
[[0.99701436 0.00182225 0.0011634 ]
 [0.00863446 0.98948574 0.0018798 ]
 [0.00669515 0.00214714 0.99115771]]
Final initial distribution pi:
[0.74801436 0.05488531 0.19710033]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.7015  0.5638  0.6251  107475636.0   45735364.0  83159906.0
Archaic_young     0.3601  0.5119  0.4228   46418354.0   82481646.0  44264289.0
Modern            0.0000  0.0000  0.0000          0.0  717889000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         714025         1502            869
Archaic_old      2832       107900          81427
Archaic_young    1032        43809          46604

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6189  0.9731  0.7566
Archaic_young     0.6338  0.0387  0.0730

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         698047         2570             20
Archaic_old      3351       180208           2480
Archaic_young    1552       107411           4361

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1597735.20 | Rates: N=0.93013, AF=0.09567, OLD=0.05066, YOUNG=0.03463
A =
[[9.96552330e-01 2.60670611e-03 8.40964344e-04]
 [8.47897153e-03 9.90585611e-01 9.35417554e-04]
 [7.89379827e-03 2.72522170e-03 9.89380980e-01]]
pi = [0.80006346 0.14103175 0.05890479]
Iter 2: LL=-1301744.69 | Rates: N=0.93041, AF=0.09545, OLD=0.05229, YOUNG=0.03134
A =
[[9.96547801e-01 2.56996271e-03 8.82236328e-04]
 [8.74825101e-03 9.90245710e-01 1.00603911e-03]
 [7.26293964e-03 2.48881745e-03 9.90248243e-01]]
pi = [0.80158724 0.13186686 0.0665459 ]
Iter 3: LL=-1301697.91 | Rates: N=0.93042, AF=0.09544, OLD=0.05428, YOUNG=0.02933
A =
[[9.96547139e-01 2.52554375e-03 9.27317575e-04]
 [9.01554982e-03 9.89903223e-01 1.08122733e-03]
 [6.85112509e-03 2.32769350e-03 9.90821181e-01]]
pi = [0.80163968 0.12242231 0.075938  ]
Iter 4: LL=-1301667.07 | Rates: N=0.93042, AF=0.09542, OLD=0.05594, YOUNG=0.02833
A =
[[9.96546507e-01 2.47595054e-03 9.77542224e-04]
 [9.22497592e-03 9.89609887e-01 1.16513711e-03]
 [6.63178236e-03 2.24797668e-03 9.91120241e-01]]
pi = [0.80166992 0.11316531 0.08516477]
Iter 5: LL=-1301650.76 | Rates: N=0.93042, AF=0.09540, OLD=0.05722, YOUNG=0.02797
A =
[[0.99654592 0.00242333 0.00103074]
 [0.00937403 0.98936791 0.00125805]
 [0.00654012 0.00222714 0.99123274]]
pi = [0.80170364 0.10505912 0.09323724]
Iter 6: LL=-1301641.06 | Rates: N=0.93042, AF=0.09539, OLD=0.05824, YOUNG=0.02795
A =
[[0.99654554 0.0023687  0.00108576]
 [0.00948385 0.98915627 0.00135988]
 [0.00651487 0.00223778 0.99124736]]
pi = [0.80173279 0.09817074 0.10009646]
Iter 7: LL=-1301633.49 | Rates: N=0.93042, AF=0.09538, OLD=0.05913, YOUNG=0.02809
A =
[[0.99654533 0.00231283 0.00114184]
 [0.00957296 0.98895704 0.00147001]
 [0.00652099 0.00226245 0.99121656]]
pi = [0.80175429 0.09224376 0.10600195]
Iter 8: LL=-1301626.52 | Rates: N=0.93042, AF=0.09537, OLD=0.05995, YOUNG=0.02832
A =
[[0.99654522 0.00225631 0.00119847]
 [0.00965224 0.98875982 0.00158794]
 [0.00654155 0.00229214 0.99116631]]
pi = [0.8017689 0.0870129 0.1112182]
Iter 9: LL=-1301619.75 | Rates: N=0.93042, AF=0.09537, OLD=0.06076, YOUNG=0.02858
A =
[[0.99654518 0.00219951 0.00125531]
 [0.00972725 0.98855928 0.00171347]
 [0.00656883 0.00232255 0.99110862]]
pi = [0.80177836 0.08227804 0.1159436 ]
Iter 10: LL=-1301613.07 | Rates: N=0.93042, AF=0.09536, OLD=0.06157, YOUNG=0.02885
A =
[[0.99654516 0.00214269 0.00131215]
 [0.00980062 0.98835276 0.00184663]
 [0.00659939 0.00235173 0.99104887]]
pi = [0.80178419 0.07790042 0.1203154 ]
Iter 11: LL=-1301606.45 | Rates: N=0.93042, AF=0.09536, OLD=0.06240, YOUNG=0.02913
A =
[[0.99654517 0.00208602 0.00136881]
 [0.00987358 0.98813882 0.0019876 ]
 [0.00663167 0.00237888 0.99098946]]
pi = [0.8017875  0.07378552 0.12442698]
Iter 12: LL=-1301599.88 | Rates: N=0.93042, AF=0.09535, OLD=0.06324, YOUNG=0.02940
A =
[[0.99654519 0.00202963 0.00142518]
 [0.00994669 0.98791662 0.00213669]
 [0.00666491 0.00240366 0.99093143]]
pi = [0.80178903 0.06986861 0.12834236]
Iter 13: LL=-1301593.36 | Rates: N=0.93042, AF=0.09535, OLD=0.06412, YOUNG=0.02967
A =
[[0.99654522 0.00197363 0.00148115]
 [0.01002021 0.98768553 0.00229426]
 [0.00669873 0.00242603 0.99087524]]
pi = [0.80178931 0.06610459 0.1321061 ]
Iter 14: LL=-1301586.89 | Rates: N=0.93042, AF=0.09534, OLD=0.06502, YOUNG=0.02994
A =
[[0.99654525 0.00191811 0.00153664]
 [0.01009427 0.98744503 0.0024607 ]
 [0.00673289 0.00244604 0.99082108]]
pi = [0.80178868 0.06246141 0.13574991]
Iter 15: LL=-1301580.47 | Rates: N=0.93042, AF=0.09534, OLD=0.06595, YOUNG=0.03020
A =
[[0.9965453  0.00186315 0.00159156]
 [0.01016896 0.9871946  0.00263643]
 [0.00676722 0.00246377 0.99076902]]
pi = [0.80178737 0.05891566 0.13929697]
Final Global Rates (lambdas): [0.93042163 0.09533621 0.06594918 0.03020154]
Final transition matrix A:
[[0.9965453  0.00186315 0.00159156]
 [0.01016896 0.9871946  0.00263643]
 [0.00676722 0.00246377 0.99076902]]
Final initial distribution pi:
[0.80178737 0.05891566 0.13929697]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.6808  0.4255  0.5237  78535496.0   36822504.0  106043201.0
Archaic_young     0.4189  0.6798  0.5183  76317035.0  105883965.0   35944259.0
Modern            0.0000  0.0000  0.0000         0.0  702441000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         698036         1225           1376
Archaic_old      3047        78876         104116
Archaic_young    1358        35257          76709

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5998  0.9665  0.7402
Archaic_young     0.7161  0.0733  0.1329

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         712364         2780             37
Archaic_old      3271       163287           3241
Archaic_young    1512       105138           8370

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1616371.95 | Rates: N=0.94176, AF=0.09654, OLD=0.05469, YOUNG=0.03820
A =
[[9.96487759e-01 2.60138894e-03 9.10852547e-04]
 [9.38286943e-03 9.89488474e-01 1.12865658e-03]
 [8.44309152e-03 2.93678573e-03 9.88620123e-01]]
pi = [0.7256291  0.19788569 0.07648521]
Iter 2: LL=-1309323.12 | Rates: N=0.94205, AF=0.09639, OLD=0.05662, YOUNG=0.03415
A =
[[9.96499344e-01 2.55321947e-03 9.47436432e-04]
 [9.71093714e-03 9.89078909e-01 1.21015419e-03]
 [7.68789819e-03 2.66042763e-03 9.89651674e-01]]
pi = [0.72128557 0.20474766 0.07396676]
Iter 3: LL=-1309261.36 | Rates: N=0.94205, AF=0.09637, OLD=0.05912, YOUNG=0.03169
A =
[[9.96499436e-01 2.51158317e-03 9.88980585e-04]
 [1.00512561e-02 9.88661050e-01 1.28769365e-03]
 [7.23899517e-03 2.48445151e-03 9.90276553e-01]]
pi = [0.72076598 0.21330935 0.06592467]
Iter 4: LL=-1309221.91 | Rates: N=0.94205, AF=0.09634, OLD=0.06114, YOUNG=0.03042
A =
[[0.99649874 0.00246509 0.00103616]
 [0.01030139 0.98832477 0.00137384]
 [0.0070174  0.00241158 0.99057102]]
pi = [0.72043435 0.2235805  0.05598515]
Iter 5: LL=-1309203.09 | Rates: N=0.94205, AF=0.09632, OLD=0.06260, YOUNG=0.02991
A =
[[0.99649815 0.00241517 0.00108668]
 [0.01046644 0.98806177 0.00147179]
 [0.00693606 0.00241106 0.99065288]]
pi = [0.72004799 0.23350221 0.0464498 ]
Iter 6: LL=-1309193.21 | Rates: N=0.94205, AF=0.09631, OLD=0.06372, YOUNG=0.02980
A =
[[0.99649785 0.00236309 0.00113906]
 [0.0105818  0.98783658 0.00158162]
 [0.00692193 0.00244812 0.99062995]]
pi = [0.71968736 0.24196201 0.03835062]
Iter 7: LL=-1309186.00 | Rates: N=0.94205, AF=0.09630, OLD=0.06466, YOUNG=0.02989
A =
[[0.99649775 0.00230991 0.00119234]
 [0.01067408 0.98762375 0.00170217]
 [0.00693621 0.00250153 0.99056226]]
pi = [0.71939078 0.24877061 0.03183861]
Iter 8: LL=-1309179.49 | Rates: N=0.94205, AF=0.09629, OLD=0.06552, YOUNG=0.03007
A =
[[0.99649776 0.00225629 0.00124595]
 [0.0107576  0.9874099  0.0018325 ]
 [0.00696141 0.00256059 0.990478  ]]
pi = [0.71915512 0.25412489 0.02671999]
Iter 9: LL=-1309173.18 | Rates: N=0.94205, AF=0.09629, OLD=0.06636, YOUNG=0.03030
A =
[[0.99649782 0.00220261 0.00129957]
 [0.01083911 0.9871887  0.00197218]
 [0.00699027 0.00262027 0.99038946]]
pi = [0.71896607 0.25830419 0.02272974]
Iter 10: LL=-1309166.92 | Rates: N=0.94205, AF=0.09628, OLD=0.06721, YOUNG=0.03055
A =
[[0.9964979  0.00214905 0.00135305]
 [0.01092164 0.98695718 0.00212118]
 [0.00701995 0.0026783  0.99030175]]
pi = [0.71881069 0.26156158 0.01962774]
Iter 11: LL=-1309160.70 | Rates: N=0.94205, AF=0.09627, OLD=0.06807, YOUNG=0.03080
A =
[[0.99649799 0.00209573 0.00140628]
 [0.01100644 0.9867139  0.00227966]
 [0.00704951 0.00273367 0.99021682]]
pi = [0.71867979 0.26409912 0.01722109]
Iter 12: LL=-1309154.49 | Rates: N=0.94205, AF=0.09627, OLD=0.06895, YOUNG=0.03105
A =
[[0.99649807 0.00204273 0.0014592 ]
 [0.01109397 0.98645811 0.00244792]
 [0.00707871 0.00278597 0.99013532]]
pi = [0.71856733 0.26607048 0.01536219]
Iter 13: LL=-1309148.28 | Rates: N=0.94205, AF=0.09626, OLD=0.06986, YOUNG=0.03131
A =
[[0.99649815 0.00199011 0.00151174]
 [0.01118432 0.98618939 0.00262629]
 [0.00710761 0.00283506 0.99005733]]
pi = [0.7184694  0.26758989 0.0139407 ]
Iter 14: LL=-1309142.09 | Rates: N=0.94205, AF=0.09626, OLD=0.07081, YOUNG=0.03156
A =
[[0.99649823 0.00193791 0.00156386]
 [0.01127739 0.98590752 0.00281509]
 [0.00713637 0.00288089 0.98998274]]
pi = [0.71838354 0.26874087 0.01287559]
Iter 15: LL=-1309135.91 | Rates: N=0.94205, AF=0.09625, OLD=0.07179, YOUNG=0.03181
A =
[[0.99649829 0.0018862  0.0016155 ]
 [0.01137299 0.98561239 0.00301463]
 [0.00716516 0.00292349 0.98991135]]
pi = [0.7183082  0.26958311 0.01210869]
Final Global Rates (lambdas): [0.94205185 0.09625272 0.07178559 0.03181322]
Final transition matrix A:
[[0.99649829 0.0018862  0.0016155 ]
 [0.01137299 0.98561239 0.00301463]
 [0.00716516 0.00292349 0.98991135]]
Final initial distribution pi:
[0.7183082  0.26958311 0.01210869]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.7044  0.4635  0.5591  78008518.0   32740482.0  90296628.0
Archaic_young     0.4765  0.7215  0.5739  82149853.0   90267147.0  31713534.0
Modern            0.0000  0.0000  0.0000         0.0  716834000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         712345         1391           1445
Archaic_old      3031        78381          88387
Archaic_young    1458        30977          82585

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6363  0.9735  0.7696
Archaic_young     0.7400  0.0413  0.0782

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         699831         2703             15
Archaic_old      4589       183706           1512
Archaic_young    1916       101322           4406

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1617573.67 | Rates: N=0.93392, AF=0.09693, OLD=0.06396, YOUNG=0.04552
A =
[[0.99615044 0.00285023 0.00099933]
 [0.00956503 0.98918963 0.00124534]
 [0.0091652  0.00338658 0.98744822]]
pi = [0.84623878 0.10810952 0.0456517 ]
Iter 2: LL=-1316866.18 | Rates: N=0.93423, AF=0.09675, OLD=0.06652, YOUNG=0.04019
A =
[[0.99617662 0.00278464 0.00103874]
 [0.00983406 0.98880806 0.00135788]
 [0.00832217 0.00304224 0.98863559]]
pi = [0.84960377 0.09966578 0.05073044]
Iter 3: LL=-1316773.76 | Rates: N=0.93423, AF=0.09673, OLD=0.06997, YOUNG=0.03677
A =
[[0.99617854 0.00272915 0.0010923 ]
 [0.01018964 0.98831537 0.00149499]
 [0.00779916 0.00278938 0.98941146]]
pi = [0.84966532 0.09133073 0.05900395]
Iter 4: LL=-1316707.27 | Rates: N=0.93423, AF=0.09669, OLD=0.07289, YOUNG=0.03505
A =
[[0.99617847 0.00266878 0.00115275]
 [0.01045535 0.98787925 0.00166541]
 [0.00755945 0.00267389 0.98976665]]
pi = [0.84966511 0.08137584 0.06895905]
Iter 5: LL=-1316673.23 | Rates: N=0.93423, AF=0.09666, OLD=0.07512, YOUNG=0.03441
A =
[[0.99617813 0.00260564 0.00121624]
 [0.01062032 0.98751016 0.00186952]
 [0.0074988  0.00265985 0.98984135]]
pi = [0.84967228 0.07078006 0.07954766]
Iter 6: LL=-1316653.94 | Rates: N=0.93423, AF=0.09664, OLD=0.07688, YOUNG=0.03431
A =
[[0.99617797 0.00254097 0.00128106]
 [0.01072465 0.98717141 0.00210394]
 [0.00751987 0.0026977  0.98978242]]
pi = [0.84968643 0.06029413 0.09001945]
Iter 7: LL=-1316639.06 | Rates: N=0.93423, AF=0.09662, OLD=0.07841, YOUNG=0.03447
A =
[[0.99617801 0.00247588 0.00134611]
 [0.01079979 0.98683592 0.00236429]
 [0.00757233 0.00275785 0.98966982]]
pi = [0.8497023  0.05031616 0.09998154]
Iter 8: LL=-1316625.44 | Rates: N=0.93423, AF=0.09661, OLD=0.07985, YOUNG=0.03475
A =
[[0.99617817 0.00241107 0.00141076]
 [0.01086219 0.98649037 0.00264744]
 [0.00763459 0.00282599 0.98953942]]
pi = [0.84971608 0.04103274 0.10925118]
Iter 9: LL=-1316612.32 | Rates: N=0.93423, AF=0.09660, OLD=0.08126, YOUNG=0.03507
A =
[[0.99617836 0.00234695 0.00147469]
 [0.01091941 0.986129   0.00295159]
 [0.00769805 0.00289577 0.98940618]]
pi = [0.84972584 0.0325564  0.11771775]
Iter 10: LL=-1316599.56 | Rates: N=0.93423, AF=0.09659, OLD=0.08268, YOUNG=0.03542
A =
[[0.99617858 0.00228368 0.00153774]
 [0.0109748  0.98574943 0.00327577]
 [0.00775951 0.00296444 0.98927605]]
pi = [0.84973075 0.02499278 0.12527646]
Iter 11: LL=-1316587.11 | Rates: N=0.93423, AF=0.09658, OLD=0.08413, YOUNG=0.03577
A =
[[0.99617879 0.00222137 0.00159984]
 [0.01102992 0.98535054 0.00361954]
 [0.00781784 0.00303088 0.98915127]]
pi = [0.84973057 0.0184513  0.13181813]
Iter 12: LL=-1316574.96 | Rates: N=0.93423, AF=0.09657, OLD=0.08562, YOUNG=0.03612
A =
[[0.996179   0.00216003 0.00166096]
 [0.0110856  0.9849316  0.00398281]
 [0.00787269 0.00309471 0.9890326 ]]
pi = [0.84972549 0.01302199 0.13725251]
Iter 13: LL=-1316563.09 | Rates: N=0.93422, AF=0.09656, OLD=0.08714, YOUNG=0.03647
A =
[[0.99617921 0.0020997  0.00172109]
 [0.01114246 0.98449185 0.00436569]
 [0.00792398 0.00315582 0.9889202 ]]
pi = [0.84971613 0.00873928 0.14154459]
Iter 14: LL=-1316551.50 | Rates: N=0.93422, AF=0.09655, OLD=0.08871, YOUNG=0.03681
A =
[[0.99617941 0.00204037 0.00178022]
 [0.01120109 0.98403042 0.00476849]
 [0.0079717  0.00321428 0.98881402]]
pi = [0.84970344 0.00555455 0.144742  ]
Iter 15: LL=-1316540.15 | Rates: N=0.93422, AF=0.09654, OLD=0.09032, YOUNG=0.03715
A =
[[0.99617961 0.00198204 0.00183835]
 [0.01126211 0.98354626 0.00519164]
 [0.00801591 0.00327018 0.98871391]]
pi = [0.84968861 0.00333461 0.14697678]
Final Global Rates (lambdas): [0.93422274 0.09653916 0.09032097 0.03715173]
Final transition matrix A:
[[0.99617961 0.00198204 0.00183835]
 [0.01126211 0.98354626 0.00519164]
 [0.00801591 0.00327018 0.98871391]]
Final initial distribution pi:
[0.84968861 0.00333461 0.14697678]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.7124  0.3561  0.4749  66986875.0   27039125.0  121101719.0
Archaic_young     0.3960  0.7313  0.5138  77816754.0  118694246.0   28596621.0
Modern            0.0000  0.0000  0.0000         0.0  709463000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         700600          249           1700
Archaic_old      6289        67022         116496
Archaic_young    2574        26755          78315

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6588  0.9481  0.7774
Archaic_young     0.6960  0.0352  0.0670

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         695926          514             26
Archaic_old     10573       186928           1550
Archaic_young    4530        96305           3648

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1620481.94 | Rates: N=0.93414, AF=0.09586, OLD=0.06934, YOUNG=0.05106
A =
[[0.99586338 0.0030323  0.00110432]
 [0.01003974 0.98854928 0.00141097]
 [0.00954634 0.00369089 0.98676277]]
pi = [0.60415553 0.28934747 0.10649699]
Iter 2: LL=-1319906.70 | Rates: N=0.93446, AF=0.09571, OLD=0.07184, YOUNG=0.04549
A =
[[0.995913   0.00295448 0.00113252]
 [0.01028198 0.98820083 0.00151719]
 [0.00863049 0.00334172 0.98802779]]
pi = [0.59883584 0.30004168 0.10112248]
Iter 3: LL=-1319814.71 | Rates: N=0.93446, AF=0.09568, OLD=0.07545, YOUNG=0.04172
A =
[[0.99591606 0.00290227 0.00118168]
 [0.0106688  0.98769664 0.00163457]
 [0.00805581 0.00306579 0.98887841]]
pi = [0.59858692 0.31022413 0.09118895]
Iter 4: LL=-1319743.62 | Rates: N=0.93446, AF=0.09563, OLD=0.07861, YOUNG=0.03968
A =
[[0.99591565 0.00284208 0.00124227]
 [0.01097901 0.98724725 0.00177373]
 [0.00775974 0.00291802 0.98932223]]
pi = [0.59845576 0.32114136 0.08040288]
Iter 5: LL=-1319706.28 | Rates: N=0.93445, AF=0.09558, OLD=0.08104, YOUNG=0.03886
A =
[[0.99591494 0.00277548 0.00130958]
 [0.01118606 0.98687571 0.00193823]
 [0.0076558  0.00287625 0.98946795]]
pi = [0.59830474 0.33082704 0.07086822]
Iter 6: LL=-1319686.47 | Rates: N=0.93445, AF=0.09555, OLD=0.08294, YOUNG=0.03870
A =
[[0.99591455 0.00270476 0.00138069]
 [0.01132749 0.98654452 0.00212798]
 [0.00764621 0.00289189 0.9894619 ]]
pi = [0.59817546 0.33838461 0.06343993]
Iter 7: LL=-1319672.21 | Rates: N=0.93445, AF=0.09552, OLD=0.08457, YOUNG=0.03884
A =
[[0.99591447 0.00263199 0.00145354]
 [0.0114372  0.98622228 0.00234051]
 [0.00767621 0.00293289 0.9893909 ]]
pi = [0.59807854 0.3438742  0.05804726]
Iter 8: LL=-1319659.42 | Rates: N=0.93445, AF=0.09550, OLD=0.08610, YOUNG=0.03914
A =
[[0.99591458 0.00255857 0.00152685]
 [0.01153377 0.98589243 0.00257379]
 [0.00772118 0.00298318 0.98929564]]
pi = [0.59800603 0.34764353 0.05435045]
Iter 9: LL=-1319647.01 | Rates: N=0.93445, AF=0.09548, OLD=0.08760, YOUNG=0.03949
A =
[[0.99591477 0.00248532 0.00159991]
 [0.01162595 0.98554712 0.00282693]
 [0.00777095 0.00303549 0.98919356]]
pi = [0.59794858 0.35002284 0.05202858]
Iter 10: LL=-1319634.74 | Rates: N=0.93445, AF=0.09547, OLD=0.08913, YOUNG=0.03987
A =
[[0.99591501 0.00241266 0.00167233]
 [0.01171768 0.98518236 0.00309997]
 [0.00782147 0.00308671 0.98909182]]
pi = [0.5978998  0.35125524 0.05084496]
Iter 11: LL=-1319622.51 | Rates: N=0.93445, AF=0.09545, OLD=0.09071, YOUNG=0.04026
A =
[[0.99591527 0.00234082 0.00174391]
 [0.01181084 0.98479561 0.00339355]
 [0.00787114 0.00313563 0.98899323]]
pi = [0.59785584 0.35150155 0.05064261]
Iter 12: LL=-1319610.30 | Rates: N=0.93445, AF=0.09543, OLD=0.09235, YOUNG=0.04066
A =
[[0.99591554 0.00226994 0.00181452]
 [0.01190655 0.98438465 0.0037088 ]
 [0.0079193  0.00318184 0.98889886]]
pi = [0.59781434 0.35085849 0.05132717]
Iter 13: LL=-1319598.07 | Rates: N=0.93444, AF=0.09541, OLD=0.09406, YOUNG=0.04105
A =
[[0.99591582 0.00220007 0.0018841 ]
 [0.01200569 0.9839471  0.00404721]
 [0.00796564 0.0032253  0.98880906]]
pi = [0.59777371 0.34937452 0.05285178]
Iter 14: LL=-1319585.78 | Rates: N=0.93444, AF=0.09539, OLD=0.09586, YOUNG=0.04144
A =
[[0.9959161  0.00213126 0.00195265]
 [0.01210918 0.98348023 0.00441059]
 [0.00800997 0.00326611 0.98872392]]
pi = [0.59773279 0.34706101 0.0552062 ]
Iter 15: LL=-1319573.40 | Rates: N=0.93444, AF=0.09537, OLD=0.09775, YOUNG=0.04183
A =
[[0.99591636 0.00206349 0.00202015]
 [0.01221808 0.9829808  0.00480112]
 [0.00805218 0.00330443 0.98864339]]
pi = [0.59769065 0.34389983 0.05840953]
Final Global Rates (lambdas): [0.93444132 0.09537047 0.09774987 0.04182764]
Final transition matrix A:
[[0.99591636 0.00206349 0.00202015]
 [0.01221808 0.9829808  0.00480112]
 [0.00805218 0.00330443 0.98864339]]
Final initial distribution pi:
[0.59769065 0.34389983 0.05840953]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.7257  0.3514  0.4735  69290132.0   26185868.0  127880615.0
Archaic_young     0.3767  0.7333  0.4977  75719592.0  125298408.0   27545381.0
Modern            0.0000  0.0000  0.0000         0.0  703506000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         694214          459           1793
Archaic_old      6695        69353         123003
Archaic_young    2597        25664          76222

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6821  0.9528  0.7951
Archaic_young     0.5224  0.0820  0.1417

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         711347         2217             44
Archaic_old      3347       184861           6739
Archaic_young    1025        82968           7452

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1602802.04 | Rates: N=0.93702, AF=0.09489, OLD=0.05064, YOUNG=0.02881
A =
[[9.96873702e-01 2.52109046e-03 6.05207267e-04]
 [8.20008550e-03 9.91099368e-01 7.00546826e-04]
 [7.37933364e-03 2.64177147e-03 9.89978895e-01]]
pi = [0.84905519 0.09845721 0.0524876 ]
Iter 2: LL=-1300735.80 | Rates: N=0.93728, AF=0.09470, OLD=0.05216, YOUNG=0.02640
A =
[[9.96878392e-01 2.46184539e-03 6.59762452e-04]
 [8.41287627e-03 9.90806220e-01 7.80903368e-04]
 [6.73785642e-03 2.36756463e-03 9.90894579e-01]]
pi = [0.85047112 0.0728856  0.07664329]
Iter 3: LL=-1300703.07 | Rates: N=0.93728, AF=0.09468, OLD=0.05365, YOUNG=0.02540
A =
[[9.96878397e-01 2.40938590e-03 7.12217396e-04]
 [8.57168173e-03 9.90569797e-01 8.58521742e-04]
 [6.50082220e-03 2.25600578e-03 9.91243172e-01]]
pi = [0.85046448 0.04710053 0.10243499]
Iter 4: LL=-1300687.00 | Rates: N=0.93728, AF=0.09467, OLD=0.05475, YOUNG=0.02512
A =
[[9.96878226e-01 2.35641606e-03 7.65358010e-04]
 [8.66574781e-03 9.90391915e-01 9.42337381e-04]
 [6.44101722e-03 2.22951934e-03 9.91329463e-01]]
pi = [0.85044761 0.02669785 0.12285454]
Iter 5: LL=-1300677.34 | Rates: N=0.93728, AF=0.09466, OLD=0.05563, YOUNG=0.02518
A =
[[9.96878158e-01 2.30280409e-03 8.19038347e-04]
 [8.72338844e-03 9.90242872e-01 1.03373924e-03]
 [6.45607315e-03 2.24292109e-03 9.91301006e-01]]
pi = [0.85043399 0.01375126 0.13581476]
Iter 6: LL=-1300669.45 | Rates: N=0.93728, AF=0.09466, OLD=0.05640, YOUNG=0.02540
A =
[[9.96878186e-01 2.24869306e-03 8.73121439e-04]
 [8.76504648e-03 9.90101855e-01 1.13309892e-03]
 [6.49751858e-03 2.27249626e-03 9.91229985e-01]]
pi = [0.85042096 0.00663553 0.14294351]
Iter 7: LL=-1300662.03 | Rates: N=0.93728, AF=0.09465, OLD=0.05713, YOUNG=0.02568
A =
[[9.96878263e-01 2.19424648e-03 9.27490413e-04]
 [8.80129162e-03 9.89958070e-01 1.24063838e-03]
 [6.54546686e-03 2.30747785e-03 9.91147055e-01]]
pi = [0.8504088  0.00306015 0.14653105]
Iter 8: LL=-1300654.72 | Rates: N=0.93728, AF=0.09465, OLD=0.05785, YOUNG=0.02600
A =
[[9.96878359e-01 2.13957487e-03 9.82065842e-04]
 [8.83699113e-03 9.89806314e-01 1.35669536e-03]
 [6.59251121e-03 2.34322502e-03 9.91064264e-01]]
pi = [0.85039811 0.00136438 0.14823751]
Iter 9: LL=-1300647.44 | Rates: N=0.93728, AF=0.09464, OLD=0.05860, YOUNG=0.02633
A =
[[0.99687846 0.00208474 0.0010368 ]
 [0.00887428 0.98964397 0.00148175]
 [0.00663631 0.00237778 0.99098592]]
pi = [8.50389047e-01 5.91722402e-04 1.49019230e-01]
Iter 10: LL=-1300640.13 | Rates: N=0.93728, AF=0.09464, OLD=0.05937, YOUNG=0.02667
A =
[[0.99687856 0.00202979 0.00109165]
 [0.00891407 0.98946956 0.00161637]
 [0.00667647 0.00241033 0.9909132 ]]
pi = [8.50381454e-01 2.50401836e-04 1.49368144e-01]
Iter 11: LL=-1300632.77 | Rates: N=0.93728, AF=0.09464, OLD=0.06017, YOUNG=0.02701
A =
[[0.99687865 0.00197475 0.0011466 ]
 [0.0089567  0.98928206 0.00176124]
 [0.00671335 0.00244054 0.99084611]]
pi = [8.50375120e-01 1.03546012e-04 1.49521334e-01]
Iter 12: LL=-1300625.34 | Rates: N=0.93728, AF=0.09463, OLD=0.06101, YOUNG=0.02734
A =
[[0.99687873 0.00191965 0.00120161]
 [0.00900225 0.98908069 0.00191707]
 [0.00674751 0.0024683  0.99078419]]
pi = [8.50369847e-01 4.18672860e-05 1.49588285e-01]
Iter 13: LL=-1300617.83 | Rates: N=0.93728, AF=0.09463, OLD=0.06189, YOUNG=0.02768
A =
[[0.99687882 0.00186453 0.00125666]
 [0.00905064 0.98886473 0.00208462]
 [0.00677956 0.00249357 0.99072687]]
pi = [8.50365480e-01 1.65552667e-05 1.49617965e-01]
Iter 14: LL=-1300610.22 | Rates: N=0.93728, AF=0.09462, OLD=0.06282, YOUNG=0.02801
A =
[[0.99687889 0.0018094  0.0013117 ]
 [0.00910173 0.98863357 0.00226471]
 [0.00681006 0.00251636 0.99067358]]
pi = [8.50361898e-01 6.40157463e-06 1.49631700e-01]
Iter 15: LL=-1300602.51 | Rates: N=0.93728, AF=0.09462, OLD=0.06379, YOUNG=0.02833
A =
[[0.99687897 0.00175433 0.0013667 ]
 [0.00915528 0.98838659 0.00245813]
 [0.00683951 0.00253668 0.99062381]]
pi = [8.50359011e-01 2.42012500e-06 1.49638569e-01]
Final Global Rates (lambdas): [0.93728007 0.09461945 0.06379203 0.02833286]
Final transition matrix A:
[[0.99687897 0.00175433 0.0013667 ]
 [0.00915528 0.98838659 0.00245813]
 [0.00683951 0.00253668 0.99062381]]
Final initial distribution pi:
[8.50359011e-01 2.42012500e-06 1.49638569e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.7373  0.5064  0.6004  97901936.0   34881064.0  95421806.0
Archaic_young     0.3746  0.6276  0.4692  56910420.0   95001580.0  33772223.0
Modern            0.0000  0.0000  0.0000         0.0  715305000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         711306         1202           1100
Archaic_old      3037        98265          93645
Archaic_young     962        33316          57167

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6271  0.9620  0.7593
Archaic_young     0.7239  0.0977  0.1722

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         700117         2682             80
Archaic_old      3851       175875           4071
Archaic_young    1505       100816          11003

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1611353.96 | Rates: N=0.93502, AF=0.09773, OLD=0.05556, YOUNG=0.03319
A =
[[9.96394818e-01 2.84583612e-03 7.59346344e-04]
 [9.08354907e-03 9.90039928e-01 8.76522501e-04]
 [8.00092860e-03 2.87478264e-03 9.89124289e-01]]
pi = [0.70253209 0.20819053 0.08927738]
Iter 2: LL=-1309866.29 | Rates: N=0.93532, AF=0.09756, OLD=0.05736, YOUNG=0.03012
A =
[[9.96399528e-01 2.78180241e-03 8.18670012e-04]
 [9.38454570e-03 9.89636573e-01 9.78880949e-04]
 [7.25990479e-03 2.54307892e-03 9.90197016e-01]]
pi = [0.7016498  0.18607087 0.11227933]
Iter 3: LL=-1309819.82 | Rates: N=0.93532, AF=0.09754, OLD=0.05931, YOUNG=0.02877
A =
[[9.96398429e-01 2.72566053e-03 8.75910546e-04]
 [9.62616621e-03 9.89296671e-01 1.07716241e-03]
 [6.95053420e-03 2.38213053e-03 9.90667335e-01]]
pi = [0.70165546 0.16282847 0.13551607]
Iter 4: LL=-1309796.14 | Rates: N=0.93532, AF=0.09752, OLD=0.06082, YOUNG=0.02832
A =
[[9.96397138e-01 2.66766053e-03 9.35201533e-04]
 [9.78421399e-03 9.89032091e-01 1.18369508e-03]
 [6.85043412e-03 2.31920146e-03 9.90830364e-01]]
pi = [0.70173988 0.14207186 0.15618827]
Iter 5: LL=-1309783.03 | Rates: N=0.93532, AF=0.09750, OLD=0.06199, YOUNG=0.02831
A =
[[9.96396264e-01 2.60810889e-03 9.95627071e-04]
 [9.88661281e-03 9.88813916e-01 1.29947086e-03]
 [6.84976268e-03 2.30729923e-03 9.90842938e-01]]
pi = [0.70185868 0.12468649 0.17345483]
Iter 6: LL=-1309773.27 | Rates: N=0.93532, AF=0.09749, OLD=0.06298, YOUNG=0.02851
A =
[[0.99639577 0.00254776 0.00105647]
 [0.00995976 0.98861609 0.00142414]
 [0.00689013 0.00231886 0.99079101]]
pi = [0.70197698 0.11011956 0.18790346]
Iter 7: LL=-1309764.52 | Rates: N=0.93532, AF=0.09748, OLD=0.06390, YOUNG=0.02879
A =
[[0.99639549 0.00248728 0.00111722]
 [0.010019   0.98842375 0.00155725]
 [0.00694529 0.00234071 0.990714  ]]
pi = [0.70207895 0.09759346 0.20032759]
Iter 8: LL=-1309756.20 | Rates: N=0.93533, AF=0.09747, OLD=0.06478, YOUNG=0.02910
A =
[[0.99639533 0.00242711 0.00117756]
 [0.01007197 0.98822945 0.00169858]
 [0.00700419 0.00236695 0.99062885]]
pi = [0.70216155 0.0864875  0.21135095]
Iter 9: LL=-1309748.15 | Rates: N=0.93533, AF=0.09747, OLD=0.06566, YOUNG=0.02942
A =
[[0.99639522 0.00236752 0.00123726]
 [0.01012239 0.98802943 0.00184818]
 [0.00706229 0.00239504 0.99054267]]
pi = [0.70222609 0.07637553 0.22139838]
Iter 10: LL=-1309740.32 | Rates: N=0.93533, AF=0.09746, OLD=0.06655, YOUNG=0.02974
A =
[[0.99639514 0.00230867 0.00129619]
 [0.0101721  0.98782168 0.00200622]
 [0.00711779 0.00242385 0.99045836]]
pi = [0.70227443 0.06698553 0.23074004]
Iter 11: LL=-1309732.70 | Rates: N=0.93533, AF=0.09746, OLD=0.06746, YOUNG=0.03006
A =
[[0.99639507 0.00225066 0.00135427]
 [0.01022205 0.98760495 0.002173  ]
 [0.00717011 0.00245287 0.99037702]]
pi = [0.70230778 0.0581585  0.23953372]
Iter 12: LL=-1309725.26 | Rates: N=0.93533, AF=0.09745, OLD=0.06838, YOUNG=0.03037
A =
[[0.99639501 0.00219357 0.00141142]
 [0.0102728  0.98737833 0.00234886]
 [0.00721912 0.00248186 0.99029902]]
pi = [0.70232657 0.04981937 0.24785405]
Iter 13: LL=-1309717.98 | Rates: N=0.93533, AF=0.09744, OLD=0.06933, YOUNG=0.03067
A =
[[0.99639495 0.00213743 0.00146762]
 [0.01032471 0.9871411  0.00253419]
 [0.00726493 0.00251068 0.99022439]]
pi = [0.70233062 0.04195765 0.25571173]
Iter 14: LL=-1309710.85 | Rates: N=0.93533, AF=0.09744, OLD=0.07030, YOUNG=0.03097
A =
[[0.9963949  0.00208228 0.00152282]
 [0.01037799 0.98689262 0.00272939]
 [0.00730775 0.00253924 0.99015301]]
pi = [0.70231942 0.03461271 0.26306786]
Iter 15: LL=-1309703.86 | Rates: N=0.93533, AF=0.09743, OLD=0.07129, YOUNG=0.03125
A =
[[0.99639485 0.00202813 0.00157702]
 [0.0104328  0.98663231 0.00293488]
 [0.00734781 0.00256744 0.99008474]]
pi = [0.70229258 0.02785938 0.26984804]
Final Global Rates (lambdas): [0.93532717 0.09743199 0.07128932 0.03125355]
Final transition matrix A:
[[0.99639485 0.00202813 0.00157702]
 [0.0104328  0.98663231 0.00293488]
 [0.00734781 0.00256744 0.99008474]]
Final initial distribution pi:
[0.70229258 0.02785938 0.26984804]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.7139  0.4948  0.5845  90104896.0   36104104.0  91996960.0
Archaic_young     0.4579  0.6875  0.5497  77182687.0   91365313.0  35078607.0
Modern            0.0000  0.0000  0.0000         0.0  705243000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         700100         1411           1368
Archaic_old      3669        90529          89599
Archaic_young    1474        34269          77581

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6317  0.9429  0.7566
Archaic_young     0.6964  0.1477  0.2437

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         697909         2915             95
Archaic_old      4265       172612           7184
Archaic_young    1504        96649          16867

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1607227.22 | Rates: N=0.92810, AF=0.09658, OLD=0.06136, YOUNG=0.03688
A =
[[9.96141531e-01 2.98912034e-03 8.69348589e-04]
 [9.76703643e-03 9.89178573e-01 1.05439042e-03]
 [8.21974965e-03 3.08509734e-03 9.88695153e-01]]
pi = [0.80552936 0.15300509 0.04146555]
Iter 2: LL=-1312315.39 | Rates: N=0.92839, AF=0.09645, OLD=0.06421, YOUNG=0.03274
A =
[[9.96166369e-01 2.89992269e-03 9.33708091e-04]
 [1.02169112e-02 9.88600632e-01 1.18245672e-03]
 [7.23301961e-03 2.68447907e-03 9.90082501e-01]]
pi = [0.80870405 0.16048988 0.03080607]
Iter 3: LL=-1312231.16 | Rates: N=0.92840, AF=0.09641, OLD=0.06712, YOUNG=0.03096
A =
[[0.99616659 0.00283347 0.00099994]
 [0.01058297 0.98811321 0.00130382]
 [0.00686061 0.00254285 0.99059654]]
pi = [0.80823245 0.16962267 0.02214489]
Iter 4: LL=-1312192.57 | Rates: N=0.92840, AF=0.09637, OLD=0.06925, YOUNG=0.03038
A =
[[0.99616545 0.00276396 0.00107059]
 [0.01081506 0.98774073 0.0014442 ]
 [0.0067522  0.0025424  0.9907054 ]]
pi = [0.80767802 0.17635604 0.01596594]
Iter 5: LL=-1312173.00 | Rates: N=0.92840, AF=0.09634, OLD=0.07087, YOUNG=0.03034
A =
[[0.99616475 0.00269178 0.00114347]
 [0.0109695  0.98742467 0.00160583]
 [0.00675418 0.00260513 0.9906407 ]]
pi = [0.80727247 0.1810093  0.01171824]
Iter 6: LL=-1312158.51 | Rates: N=0.92840, AF=0.09632, OLD=0.07225, YOUNG=0.03053
A =
[[0.99616449 0.00261886 0.00121665]
 [0.01108741 0.98712587 0.00178672]
 [0.00679841 0.00269075 0.99051084]]
pi = [0.80697641 0.18423702 0.00878657]
Iter 7: LL=-1312145.41 | Rates: N=0.92840, AF=0.09631, OLD=0.07354, YOUNG=0.03082
A =
[[0.99616445 0.00254655 0.001289  ]
 [0.01118878 0.98682609 0.00198513]
 [0.00685805 0.00278161 0.99036034]]
pi = [0.80674769 0.18652122 0.00673109]
Iter 8: LL=-1312132.95 | Rates: N=0.92840, AF=0.09630, OLD=0.07479, YOUNG=0.03114
A =
[[0.99616452 0.00247562 0.00135987]
 [0.01128212 0.98651774 0.00220014]
 [0.00692288 0.0028704  0.99020672]]
pi = [0.80656151 0.18817359 0.00526491]
Iter 9: LL=-1312120.96 | Rates: N=0.92840, AF=0.09629, OLD=0.07604, YOUNG=0.03147
A =
[[0.99616461 0.00240644 0.00142894]
 [0.01137095 0.98619773 0.00243131]
 [0.00698897 0.00295425 0.99005678]]
pi = [0.80640417 0.18939348 0.00420235]
Iter 10: LL=-1312109.43 | Rates: N=0.92840, AF=0.09628, OLD=0.07730, YOUNG=0.03181
A =
[[0.99616472 0.00233923 0.00149605]
 [0.01145674 0.98586479 0.00267847]
 [0.00705474 0.00303218 0.98991309]]
pi = [0.80626789 0.19031053 0.00342158]
Iter 11: LL=-1312098.32 | Rates: N=0.92840, AF=0.09627, OLD=0.07857, YOUNG=0.03214
A =
[[0.99616483 0.00227406 0.00156111]
 [0.01154023 0.98551823 0.00294154]
 [0.00711943 0.00310399 0.98977658]]
pi = [0.80614801 0.19101087 0.00284112]
Iter 12: LL=-1312087.61 | Rates: N=0.92840, AF=0.09627, OLD=0.07987, YOUNG=0.03247
A =
[[0.99616493 0.00221096 0.00162412]
 [0.01162194 0.98515753 0.00322053]
 [0.00718259 0.00316987 0.98964754]]
pi = [0.80604158 0.19155286 0.00240556]
Iter 13: LL=-1312077.30 | Rates: N=0.92840, AF=0.09626, OLD=0.08118, YOUNG=0.03279
A =
[[0.99616502 0.00214991 0.00168508]
 [0.0117024  0.98478211 0.00351549]
 [0.00724388 0.00323015 0.98952598]]
pi = [0.80594663 0.19197672 0.00207665]
Iter 14: LL=-1312067.34 | Rates: N=0.92840, AF=0.09625, OLD=0.08252, YOUNG=0.03311
A =
[[0.9961651  0.00209086 0.00174404]
 [0.0117822  0.98439126 0.00382654]
 [0.00730302 0.0032852  0.98941177]]
pi = [0.80586175 0.19231057 0.00182767]
Iter 15: LL=-1312057.72 | Rates: N=0.92840, AF=0.09624, OLD=0.08388, YOUNG=0.03343
A =
[[0.99616516 0.00203376 0.00180108]
 [0.01186197 0.98398417 0.00415386]
 [0.00735979 0.00333544 0.98930477]]
pi = [0.80578591 0.19257429 0.0016398 ]
Final Global Rates (lambdas): [0.92839569 0.09624035 0.08388181 0.0334297 ]
Final transition matrix A:
[[0.99616516 0.00203376 0.00180108]
 [0.01186197 0.98398417 0.00415386]
 [0.00735979 0.00333544 0.98930477]]
Final initial distribution pi:
[0.80578591 0.19257429 0.0016398 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.7559  0.4491  0.5635  81894960.0   26446040.0  100454577.0
Archaic_young     0.4699  0.7770  0.5856  88468853.0   99810147.0   25394534.0
Modern            0.0000  0.0000  0.0000         0.0  703380000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         697898         1444           1577
Archaic_old      4018        82262          97781
Archaic_young    1464        24635          88921

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6445  0.9282  0.7607
Archaic_young     0.6746  0.0978  0.1708

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         707519          401             52
Archaic_old      9951       169496           4937
Archaic_young    4189        93017          10438

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1627828.99 | Rates: N=0.93898, AF=0.09765, OLD=0.06846, YOUNG=0.04356
A =
[[9.96003310e-01 3.07773927e-03 9.18950473e-04]
 [1.03300529e-02 9.88490324e-01 1.17962292e-03]
 [9.29834984e-03 3.52765567e-03 9.87173994e-01]]
pi = [0.85541194 0.10971828 0.03486978]
Iter 2: LL=-1322093.50 | Rates: N=0.93930, AF=0.09756, OLD=0.07100, YOUNG=0.03890
A =
[[9.96046713e-01 2.97886644e-03 9.74420785e-04]
 [1.06613587e-02 9.88008934e-01 1.32970706e-03]
 [8.26139704e-03 3.07771739e-03 9.88660886e-01]]
pi = [0.86506291 0.10169695 0.03324014]
Iter 3: LL=-1322015.68 | Rates: N=0.93930, AF=0.09753, OLD=0.07402, YOUNG=0.03670
A =
[[0.99604884 0.00291559 0.00103557]
 [0.01099838 0.9875198  0.00148182]
 [0.00783813 0.00285668 0.98930519]]
pi = [0.86620332 0.0980579  0.03573878]
Iter 4: LL=-1321974.63 | Rates: N=0.93929, AF=0.09749, OLD=0.07639, YOUNG=0.03588
A =
[[0.99604846 0.00284946 0.00110208]
 [0.01122402 0.98712034 0.00165564]
 [0.00769495 0.002781   0.98952405]]
pi = [0.8663548  0.09234792 0.04129728]
Iter 5: LL=-1321952.79 | Rates: N=0.93929, AF=0.09746, OLD=0.07826, YOUNG=0.03577
A =
[[0.9960482  0.00277907 0.00117273]
 [0.01137419 0.98677414 0.00185167]
 [0.00768168 0.00278336 0.98953495]]
pi = [0.86624996 0.08347908 0.05027096]
Iter 6: LL=-1321936.82 | Rates: N=0.93929, AF=0.09744, OLD=0.07987, YOUNG=0.03597
A =
[[0.99604823 0.00270542 0.00124635]
 [0.01148875 0.98644341 0.00206784]
 [0.0077193  0.00282215 0.98945855]]
pi = [0.86588672 0.07111152 0.06300177]
Iter 7: LL=-1321922.20 | Rates: N=0.93929, AF=0.09742, OLD=0.08140, YOUNG=0.03632
A =
[[0.99604845 0.00262952 0.00132203]
 [0.01159084 0.98610663 0.00230253]
 [0.00777307 0.00287697 0.98934996]]
pi = [0.86520288 0.05573467 0.07906246]
Iter 8: LL=-1321907.77 | Rates: N=0.93929, AF=0.09740, OLD=0.08292, YOUNG=0.03673
A =
[[0.99604877 0.00255206 0.00139918]
 [0.01169188 0.98575288 0.00255525]
 [0.00782907 0.00293834 0.98923259]]
pi = [0.86422181 0.03917407 0.09660411]
Iter 9: LL=-1321893.28 | Rates: N=0.93929, AF=0.09739, OLD=0.08448, YOUNG=0.03717
A =
[[0.99604913 0.00247346 0.00147742]
 [0.01179711 0.98537652 0.00282638]
 [0.00788242 0.00300163 0.98911595]]
pi = [0.86310187 0.02422913 0.112669  ]
Iter 10: LL=-1321878.68 | Rates: N=0.93929, AF=0.09737, OLD=0.08612, YOUNG=0.03761
A =
[[0.9960495  0.00239403 0.00155646]
 [0.01190882 0.98497432 0.00311686]
 [0.00793196 0.00306439 0.98900366]]
pi = [0.86206391 0.01312053 0.12481557]
Iter 11: LL=-1321863.97 | Rates: N=0.93929, AF=0.09736, OLD=0.08783, YOUNG=0.03805
A =
[[0.99604988 0.00231405 0.00163607]
 [0.0120281  0.98454396 0.00342795]
 [0.00797782 0.00312524 0.98889694]]
pi = [0.86125702 0.00627116 0.13247182]
Iter 12: LL=-1321849.13 | Rates: N=0.93928, AF=0.09734, OLD=0.08965, YOUNG=0.03849
A =
[[0.99605025 0.00223376 0.001716  ]
 [0.01215561 0.98408332 0.00376107]
 [0.00802048 0.00318339 0.98879613]]
pi = [0.86070771 0.00268247 0.13660982]
Iter 13: LL=-1321834.15 | Rates: N=0.93928, AF=0.09733, OLD=0.09156, YOUNG=0.03893
A =
[[0.99605059 0.0021534  0.00179601]
 [0.0122919  0.98359032 0.00411777]
 [0.00806043 0.00323834 0.98870123]]
pi = [0.86036778 0.00104015 0.13859208]
Iter 14: LL=-1321819.01 | Rates: N=0.93928, AF=0.09731, OLD=0.09360, YOUNG=0.03936
A =
[[0.99605092 0.00207322 0.00187586]
 [0.01243743 0.98306294 0.00449963]
 [0.00809814 0.00328975 0.98861211]]
pi = [8.60174785e-01 3.69106132e-04 1.39456108e-01]
Iter 15: LL=-1321803.69 | Rates: N=0.93928, AF=0.09729, OLD=0.09575, YOUNG=0.03979
A =
[[0.99605121 0.00199349 0.0019553 ]
 [0.01259249 0.98249926 0.00490825]
 [0.00813406 0.00333741 0.98852853]]
pi = [8.60080667e-01 1.20682461e-04 1.39798651e-01]
Final Global Rates (lambdas): [0.93927942 0.09729169 0.09575319 0.03979054]
Final transition matrix A:
[[0.99605121 0.00199349 0.0019553 ]
 [0.01259249 0.98249926 0.00490825]
 [0.00813406 0.00333741 0.98852853]]
Final initial distribution pi:
[8.60080667e-01 1.20682461e-04 1.39798651e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.7820  0.3719  0.5040  67881997.0   18922003.0  114664322.0
Archaic_young     0.4346  0.8106  0.5659  86261091.0  112206909.0   20152284.0
Modern            0.0000  0.0000  0.0000         0.0  714728000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         705819          272           1881
Archaic_old      6654        67945         109785
Archaic_young    2255        18587          86802

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6691  0.9557  0.7871
Archaic_young     0.6959  0.1257  0.2129

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         730351         2423             66
Archaic_old      3803       167029           4883
Archaic_young     957        79057          11431

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1623503.14 | Rates: N=0.94578, AF=0.09720, OLD=0.05684, YOUNG=0.02843
A =
[[9.96874195e-01 2.62190652e-03 5.03898070e-04]
 [9.23375873e-03 9.90106075e-01 6.60166535e-04]
 [7.31564371e-03 2.73625022e-03 9.89948106e-01]]
pi = [0.79507062 0.13230194 0.07262744]
Iter 2: LL=-1311898.34 | Rates: N=0.94605, AF=0.09703, OLD=0.05892, YOUNG=0.02669
A =
[[9.96887062e-01 2.55537919e-03 5.57558734e-04]
 [9.64896683e-03 9.89576287e-01 7.74745720e-04]
 [6.26280145e-03 2.35209801e-03 9.91385101e-01]]
pi = [0.79791453 0.08601005 0.11607542]
Iter 3: LL=-1311857.72 | Rates: N=0.94605, AF=0.09700, OLD=0.06076, YOUNG=0.02649
A =
[[9.96885801e-01 2.50640999e-03 6.07788639e-04]
 [9.95965464e-03 9.89164547e-01 8.75798751e-04]
 [5.92982826e-03 2.23953570e-03 9.91830636e-01]]
pi = [0.79814387 0.04652513 0.155331  ]
Iter 4: LL=-1311839.09 | Rates: N=0.94606, AF=0.09697, OLD=0.06213, YOUNG=0.02681
A =
[[9.96884364e-01 2.45465229e-03 6.60984210e-04]
 [1.01709900e-02 9.88848643e-01 9.80367195e-04]
 [5.84110601e-03 2.22341360e-03 9.91935480e-01]]
pi = [0.79837971 0.02190674 0.17971355]
Iter 5: LL=-1311826.37 | Rates: N=0.94606, AF=0.09696, OLD=0.06327, YOUNG=0.02728
A =
[[9.96883521e-01 2.39967501e-03 7.16804428e-04]
 [1.03297015e-02 9.88579036e-01 1.09126270e-03]
 [5.84967045e-03 2.24216552e-03 9.91908164e-01]]
pi = [0.79855248 0.00948765 0.19195987]
Iter 6: LL=-1311815.24 | Rates: N=0.94606, AF=0.09694, OLD=0.06432, YOUNG=0.02778
A =
[[9.96883064e-01 2.34258189e-03 7.74353974e-04]
 [1.04621261e-02 9.88328453e-01 1.20942135e-03]
 [5.89939865e-03 2.27248694e-03 9.91828114e-01]]
pi = [0.79863991 0.00390061 0.19745948]
Iter 7: LL=-1311804.72 | Rates: N=0.94606, AF=0.09693, OLD=0.06535, YOUNG=0.02827
A =
[[9.96882817e-01 2.28427350e-03 8.32909970e-04]
 [1.05809409e-02 9.88083413e-01 1.33564594e-03]
 [5.96745711e-03 2.30558230e-03 9.91726961e-01]]
pi = [0.79867187 0.00154604 0.19978209]
Iter 8: LL=-1311794.57 | Rates: N=0.94606, AF=0.09692, OLD=0.06639, YOUNG=0.02874
A =
[[9.96882684e-01 2.22535453e-03 8.91961200e-04]
 [1.06923811e-02 9.87836741e-01 1.47087762e-03]
 [6.04372820e-03 2.33803949e-03 9.91618232e-01]]
pi = [7.98675567e-01 5.94968045e-04 2.00729465e-01]
Iter 9: LL=-1311784.66 | Rates: N=0.94606, AF=0.09692, OLD=0.06746, YOUNG=0.02919
A =
[[9.96882620e-01 2.16623269e-03 9.51146972e-04]
 [1.07997843e-02 9.87584027e-01 1.61618863e-03]
 [6.12334638e-03 2.36850125e-03 9.91508152e-01]]
pi = [7.98666423e-01 2.22990653e-04 2.01110586e-01]
Iter 10: LL=-1311774.94 | Rates: N=0.94606, AF=0.09691, OLD=0.06855, YOUNG=0.02962
A =
[[0.9968826  0.00210719 0.00101021]
 [0.01090512 0.98732213 0.00177275]
 [0.00620383 0.00239644 0.99139973]]
pi = [7.98651880e-01 8.15004203e-05 2.01266620e-01]
Iter 11: LL=-1311765.36 | Rates: N=0.94606, AF=0.09690, OLD=0.06969, YOUNG=0.03004
A =
[[0.99688261 0.00204845 0.00106895]
 [0.01100963 0.98704855 0.00194182]
 [0.00628389 0.0024217  0.99129441]]
pi = [7.98635297e-01 2.90627140e-05 2.01335640e-01]
Iter 12: LL=-1311755.87 | Rates: N=0.94606, AF=0.09689, OLD=0.07088, YOUNG=0.03044
A =
[[0.99688263 0.00199014 0.00112722]
 [0.01111413 0.98676115 0.00212472]
 [0.00636288 0.00244428 0.99119285]]
pi = [7.98618133e-01 1.01133837e-05 2.01371753e-01]
Iter 13: LL=-1311746.44 | Rates: N=0.94606, AF=0.09688, OLD=0.07211, YOUNG=0.03084
A =
[[0.99688267 0.0019324  0.00118493]
 [0.01121915 0.986458   0.00232285]
 [0.00644049 0.0024643  0.99109521]]
pi = [7.98601000e-01 3.43450219e-06 2.01395566e-01]
Iter 14: LL=-1311737.04 | Rates: N=0.94606, AF=0.09687, OLD=0.07339, YOUNG=0.03122
A =
[[0.99688271 0.00187532 0.00124197]
 [0.011325   0.98613735 0.00253765]
 [0.00651665 0.00248192 0.99100143]]
pi = [7.98584135e-01 1.13826082e-06 2.01414726e-01]
Iter 15: LL=-1311727.64 | Rates: N=0.94606, AF=0.09686, OLD=0.07474, YOUNG=0.03159
A =
[[0.99688276 0.00181896 0.00129829]
 [0.01143183 0.98579752 0.00277065]
 [0.00659138 0.00249733 0.99091129]]
pi = [7.98567618e-01 3.68159709e-07 2.01432014e-01]
Final Global Rates (lambdas): [0.94606026 0.09686164 0.07473968 0.03159336]
Final transition matrix A:
[[0.99688276 0.00181896 0.00129829]
 [0.01143183 0.98579752 0.00277065]
 [0.00659138 0.00249733 0.99091129]]
Final initial distribution pi:
[7.98567618e-01 3.68159709e-07 2.01432014e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.7816  0.4873  0.6004  84793853.0   23694147.0  89199074.0
Archaic_young     0.4366  0.7542  0.5530  68389443.0   88247557.0  22293200.0
Modern            0.0000  0.0000  0.0000         0.0  734875000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         730331         1378           1131
Archaic_old      3622        85262          86831
Archaic_young     922        21848          68675

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6321  0.9515  0.7596
Archaic_young     0.7465  0.1518  0.2522

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         704060         2916             93
Archaic_old      4014       169946           5647
Archaic_young    1355        94886          17083

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1613434.89 | Rates: N=0.93670, AF=0.09618, OLD=0.05993, YOUNG=0.03224
A =
[[9.96308528e-01 3.00075434e-03 6.90717900e-04]
 [9.66872551e-03 9.89473364e-01 8.57910402e-04]
 [7.72975202e-03 2.96409379e-03 9.89306154e-01]]
pi = [0.65606923 0.25539424 0.08853653]
Iter 2: LL=-1310995.14 | Rates: N=0.93700, AF=0.09605, OLD=0.06191, YOUNG=0.02989
A =
[[9.96333162e-01 2.91254557e-03 7.54292548e-04]
 [1.00269638e-02 9.88967051e-01 1.00598513e-03]
 [6.86461567e-03 2.60879421e-03 9.90526590e-01]]
pi = [0.65651105 0.24138492 0.10210402]
Iter 3: LL=-1310951.17 | Rates: N=0.93700, AF=0.09603, OLD=0.06391, YOUNG=0.02919
A =
[[9.96333282e-01 2.85387496e-03 8.12843128e-04]
 [1.03043885e-02 9.88547225e-01 1.14838612e-03]
 [6.59694205e-03 2.49568114e-03 9.90907377e-01]]
pi = [0.65524868 0.22926805 0.11548327]
Iter 4: LL=-1310929.46 | Rates: N=0.93700, AF=0.09601, OLD=0.06544, YOUNG=0.02917
A =
[[9.96332451e-01 2.79403289e-03 8.73516104e-04]
 [1.04910253e-02 9.88206592e-01 1.30238256e-03]
 [6.53349211e-03 2.48213935e-03 9.90984369e-01]]
pi = [0.65421476 0.21776363 0.12802162]
Iter 5: LL=-1310914.85 | Rates: N=0.93700, AF=0.09600, OLD=0.06671, YOUNG=0.02942
A =
[[9.96331934e-01 2.73194716e-03 9.36118680e-04]
 [1.06282537e-02 9.87903835e-01 1.46791154e-03]
 [6.55162456e-03 2.51344230e-03 9.90934933e-01]]
pi = [0.65361981 0.2071307  0.13924949]
Iter 6: LL=-1310902.21 | Rates: N=0.93700, AF=0.09599, OLD=0.06786, YOUNG=0.02978
A =
[[0.99633167 0.00266829 0.00100003]
 [0.01074299 0.98761284 0.00164417]
 [0.0065998  0.0025644  0.99083579]]
pi = [0.65324578 0.19752886 0.14922536]
Iter 7: LL=-1310890.28 | Rates: N=0.93700, AF=0.09598, OLD=0.06896, YOUNG=0.03017
A =
[[0.99633155 0.0026037  0.00106475]
 [0.01084901 0.98732021 0.00183078]
 [0.0066571  0.00262382 0.99071908]]
pi = [0.65296945 0.18889013 0.15814041]
Iter 8: LL=-1310878.73 | Rates: N=0.93700, AF=0.09597, OLD=0.07007, YOUNG=0.03056
A =
[[0.99633149 0.00253857 0.00112994]
 [0.01095302 0.98701928 0.0020277 ]
 [0.0067152  0.00268653 0.99059827]]
pi = [0.6527404  0.18106111 0.16619849]
Iter 9: LL=-1310867.48 | Rates: N=0.93700, AF=0.09596, OLD=0.07120, YOUNG=0.03096
A =
[[0.99633146 0.00247319 0.00119535]
 [0.01105832 0.98670657 0.00223511]
 [0.006771   0.00274995 0.99047905]]
pi = [0.65253983 0.1738825  0.17357767]
Iter 10: LL=-1310856.48 | Rates: N=0.93700, AF=0.09596, OLD=0.07235, YOUNG=0.03134
A =
[[0.99633144 0.00240775 0.00126081]
 [0.01116656 0.98638018 0.00245326]
 [0.00682356 0.00281261 0.99036383]]
pi = [0.652361   0.16721899 0.18042002]
Iter 11: LL=-1310845.70 | Rates: N=0.93700, AF=0.09595, OLD=0.07354, YOUNG=0.03171
A =
[[0.99633142 0.00234242 0.00132616]
 [0.01127854 0.98603904 0.00268242]
 [0.00687282 0.00287358 0.9902536 ]]
pi = [0.65220134 0.16096614 0.18683252]
Iter 12: LL=-1310835.14 | Rates: N=0.93700, AF=0.09594, OLD=0.07476, YOUNG=0.03208
A =
[[0.9963314  0.00227732 0.00139128]
 [0.01139463 0.98568256 0.0029228 ]
 [0.00691912 0.00293219 0.99014869]]
pi = [0.65205952 0.15504837 0.19289211]
Iter 13: LL=-1310824.77 | Rates: N=0.93700, AF=0.09594, OLD=0.07602, YOUNG=0.03244
A =
[[0.99633138 0.00221259 0.00145603]
 [0.01151491 0.98531049 0.0031746 ]
 [0.0069629  0.00298796 0.99004914]]
pi = [0.65193441 0.14941389 0.1986517 ]
Iter 14: LL=-1310814.60 | Rates: N=0.93699, AF=0.09593, OLD=0.07731, YOUNG=0.03279
A =
[[0.99633135 0.00214834 0.00152031]
 [0.01163933 0.98492275 0.00343792]
 [0.00700459 0.00304054 0.98995488]]
pi = [0.65182476 0.14402923 0.20414601]
Iter 15: LL=-1310804.64 | Rates: N=0.93699, AF=0.09592, OLD=0.07865, YOUNG=0.03313
A =
[[0.99633132 0.00208469 0.00158398]
 [0.01176774 0.98451944 0.00371282]
 [0.00704457 0.00308967 0.98986576]]
pi = [0.65172917 0.13887423 0.2093966 ]
Final Global Rates (lambdas): [0.9369944  0.09592192 0.07864658 0.03312969]
Final transition matrix A:
[[0.99633132 0.00208469 0.00158398]
 [0.01176774 0.98451944 0.00371282]
 [0.00704457 0.00308967 0.98986576]]
Final initial distribution pi:
[0.65172917 0.13887423 0.2093966 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.7572  0.4804  0.5878  85442791.0   27395209.0  92422724.0
Archaic_young     0.4842  0.7671  0.5937  86119593.0   91723407.0  26141701.0
Modern            0.0000  0.0000  0.0000         0.0  709319000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         704044         1483           1542
Archaic_old      3956        85878          89773
Archaic_young    1319        25477          86528

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6460  0.9054  0.7540
Archaic_young     0.7272  0.2121  0.3284

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         706665          404            146
Archaic_old      9523       159400           8842
Archaic_young    3946        86853          24221

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1615220.21 | Rates: N=0.93468, AF=0.09608, OLD=0.06481, YOUNG=0.03488
A =
[[9.96105668e-01 3.08835017e-03 8.05981644e-04]
 [1.03401710e-02 9.88616933e-01 1.04289621e-03]
 [8.07336136e-03 3.08165883e-03 9.88844980e-01]]
pi = [0.70150194 0.22696606 0.07153199]
Iter 2: LL=-1314555.50 | Rates: N=0.93500, AF=0.09601, OLD=0.06743, YOUNG=0.03129
A =
[[9.96146001e-01 2.97170611e-03 8.82293019e-04]
 [1.06995063e-02 9.88104327e-01 1.19616668e-03]
 [7.27656620e-03 2.67103876e-03 9.90052395e-01]]
pi = [0.70106156 0.23154039 0.06739804]
Iter 3: LL=-1314490.33 | Rates: N=0.93500, AF=0.09598, OLD=0.06987, YOUNG=0.02999
A =
[[9.96146890e-01 2.90080035e-03 9.52309639e-04]
 [1.09098346e-02 9.87760306e-01 1.32985887e-03]
 [7.16086458e-03 2.55663093e-03 9.90282504e-01]]
pi = [0.701032   0.23586947 0.06309853]
Iter 4: LL=-1314464.46 | Rates: N=0.93500, AF=0.09595, OLD=0.07157, YOUNG=0.02964
A =
[[0.99614646 0.00283135 0.00102219]
 [0.01099995 0.98752343 0.00147662]
 [0.00723064 0.00255031 0.99021905]]
pi = [0.70103111 0.23810584 0.06086305]
Iter 5: LL=-1314449.98 | Rates: N=0.93500, AF=0.09593, OLD=0.07287, YOUNG=0.02971
A =
[[0.99614645 0.00276286 0.00109069]
 [0.0110383  0.98732518 0.00163652]
 [0.00735247 0.00258558 0.99006195]]
pi = [0.70104477 0.23845905 0.06049619]
Iter 6: LL=-1314438.50 | Rates: N=0.93500, AF=0.09592, OLD=0.07399, YOUNG=0.02995
A =
[[0.99614668 0.00269629 0.00115702]
 [0.01105854 0.98713408 0.00180738]
 [0.00747949 0.00263523 0.98988528]]
pi = [0.70106404 0.23730499 0.06163098]
Iter 7: LL=-1314428.17 | Rates: N=0.93500, AF=0.09591, OLD=0.07504, YOUNG=0.03026
A =
[[0.99614699 0.00263205 0.00122095]
 [0.0110741  0.98693822 0.00198768]
 [0.00759719 0.00268884 0.98971397]]
pi = [0.70108325 0.23492948 0.06398728]
Iter 8: LL=-1314418.58 | Rates: N=0.93500, AF=0.09590, OLD=0.07606, YOUNG=0.03061
A =
[[0.99614731 0.00257019 0.0012825 ]
 [0.01108984 0.98673352 0.00217663]
 [0.00770237 0.00274265 0.98955498]]
pi = [0.70109953 0.23153119 0.06736928]
Iter 9: LL=-1314409.59 | Rates: N=0.93500, AF=0.09590, OLD=0.07706, YOUNG=0.03096
A =
[[0.9961476  0.00251061 0.00134179]
 [0.01110739 0.98651875 0.00237385]
 [0.00779544 0.00279543 0.98940913]]
pi = [0.70111159 0.22725903 0.07162937]
Iter 10: LL=-1314401.10 | Rates: N=0.93500, AF=0.09589, OLD=0.07807, YOUNG=0.03132
A =
[[0.99614787 0.00245317 0.00139896]
 [0.01112726 0.98629352 0.00257921]
 [0.00787774 0.00284687 0.9892754 ]]
pi = [0.70111896 0.22224182 0.07663922]
Iter 11: LL=-1314393.05 | Rates: N=0.93499, AF=0.09588, OLD=0.07908, YOUNG=0.03167
A =
[[0.99614812 0.0023977  0.00145418]
 [0.01114961 0.98605764 0.00279276]
 [0.00795066 0.00289697 0.98915237]]
pi = [0.70112162 0.2166061  0.08227228]
Iter 12: LL=-1314385.38 | Rates: N=0.93499, AF=0.09588, OLD=0.08009, YOUNG=0.03201
A =
[[0.99614834 0.00234406 0.0015076 ]
 [0.0111745  0.98581087 0.00301463]
 [0.00801545 0.00294582 0.98903873]]
pi = [0.7011199  0.21048399 0.08839611]
Iter 13: LL=-1314378.06 | Rates: N=0.93499, AF=0.09587, OLD=0.08111, YOUNG=0.03235
A =
[[0.99614854 0.0022921  0.00155936]
 [0.01120202 0.98555292 0.00324506]
 [0.00807318 0.00299349 0.98893333]]
pi = [0.70111437 0.20401308 0.09487255]
Iter 14: LL=-1314371.02 | Rates: N=0.93499, AF=0.09586, OLD=0.08215, YOUNG=0.03268
A =
[[0.99614873 0.00224168 0.00160959]
 [0.01123224 0.98528341 0.00348434]
 [0.00812473 0.00304002 0.98883525]]
pi = [0.70110576 0.19733073 0.10156352]
Iter 15: LL=-1314364.23 | Rates: N=0.93499, AF=0.09586, OLD=0.08319, YOUNG=0.03301
A =
[[0.99614889 0.0021927  0.00165841]
 [0.01126524 0.98500195 0.00373281]
 [0.00817088 0.00308543 0.98874369]]
pi = [0.70109485 0.19056554 0.10833961]
Final Global Rates (lambdas): [0.9349932  0.09585785 0.0831933  0.03300624]
Final transition matrix A:
[[0.99614889 0.0021927  0.00165841]
 [0.01126524 0.98500195 0.00373281]
 [0.00817088 0.00308543 0.98874369]]
Final initial distribution pi:
[0.70109485 0.19056554 0.10833961]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.1_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP          FN
Archaic_old       0.7400   0.538  0.6230  94685009.0   33263991.0  81307394.0
Archaic_young     0.5038   0.717  0.5918  81636809.0   80398191.0  32226578.0
Modern            0.0000   0.000  0.0000         0.0  710016000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         704235         1438           1542
Archaic_old      4232        95102          78431
Archaic_young    1549        31409          82062

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4114  0.6907  0.5157
Archaic_young     0.5516  0.2784  0.3700

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         661456         1850            626
Archaic_old      1742        98010          42653
Archaic_young    2119       137817          53727

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1573219.68 | Rates: N=0.91628, AF=0.09655, OLD=0.04410, YOUNG=0.03508
A =
[[0.99669646 0.00182386 0.00147968]
 [0.00661335 0.99175653 0.00163012]
 [0.00682055 0.00207268 0.99110677]]
pi = [0.69936241 0.15978978 0.1408478 ]
Iter 2: LL=-1289294.58 | Rates: N=0.91652, AF=0.09627, OLD=0.04578, YOUNG=0.03317
A =
[[0.99668485 0.00182392 0.00149123]
 [0.00671949 0.99162065 0.00165986]
 [0.00669409 0.00202546 0.99128045]]
pi = [0.70017849 0.14662036 0.15320115]
Iter 3: LL=-1289264.71 | Rates: N=0.91652, AF=0.09625, OLD=0.04774, YOUNG=0.03135
A =
[[0.99668476 0.00181252 0.00150272]
 [0.00685108 0.99144282 0.00170609]
 [0.00654232 0.00197226 0.99148542]]
pi = [0.70018795 0.12993991 0.16987214]
Iter 4: LL=-1289233.99 | Rates: N=0.91652, AF=0.09624, OLD=0.04966, YOUNG=0.02989
A =
[[0.99668512 0.00179505 0.00151983]
 [0.00699392 0.99123083 0.00177526]
 [0.00639541 0.00192898 0.99167561]]
pi = [0.7001878  0.11043437 0.18937783]
Iter 5: LL=-1289210.44 | Rates: N=0.91652, AF=0.09622, OLD=0.05132, YOUNG=0.02890
A =
[[0.99668525 0.00177316 0.0015416 ]
 [0.007127   0.99100308 0.00186992]
 [0.00627787 0.00190935 0.99181278]]
pi = [0.70019392 0.09041672 0.20938936]
Iter 6: LL=-1289195.73 | Rates: N=0.91652, AF=0.09620, OLD=0.05267, YOUNG=0.02833
A =
[[0.99668518 0.00174792 0.0015669 ]
 [0.00724023 0.99076985 0.00198992]
 [0.00619379 0.00191456 0.99189165]]
pi = [0.70020774 0.07207642 0.22771584]
Iter 7: LL=-1289186.80 | Rates: N=0.91652, AF=0.09619, OLD=0.05376, YOUNG=0.02805
A =
[[0.99668505 0.00172007 0.00159487]
 [0.00733418 0.99053293 0.0021329 ]
 [0.0061367  0.00193844 0.99192486]]
pi = [0.70022655 0.05655351 0.24321995]
Iter 8: LL=-1289180.55 | Rates: N=0.91653, AF=0.09618, OLD=0.05468, YOUNG=0.02794
A =
[[0.99668493 0.00169027 0.00162479]
 [0.00741335 0.99029075 0.0022959 ]
 [0.0060987  0.00197389 0.99192742]]
pi = [0.70024629 0.04400185 0.25575186]
Iter 9: LL=-1289175.30 | Rates: N=0.91653, AF=0.09617, OLD=0.05550, YOUNG=0.02794
A =
[[0.99668484 0.00165907 0.00165609]
 [0.0074822  0.9900413  0.0024765 ]
 [0.00607371 0.00201556 0.99191073]]
pi = [0.70026408 0.03407492 0.265661  ]
Iter 10: LL=-1289170.35 | Rates: N=0.91653, AF=0.09616, OLD=0.05627, YOUNG=0.02799
A =
[[0.99668478 0.0016269  0.00168832]
 [0.00754401 0.98978286 0.00267313]
 [0.00605769 0.00206005 0.99188226]]
pi = [0.70027869 0.02629472 0.2734266 ]
Iter 11: LL=-1289165.45 | Rates: N=0.91653, AF=0.09616, OLD=0.05703, YOUNG=0.02808
A =
[[0.99668474 0.00159409 0.00172117]
 [0.007601   0.98951404 0.00288496]
 [0.00604805 0.00210532 0.99184663]]
pi = [0.70028991 0.02021662 0.27949347]
Iter 12: LL=-1289160.54 | Rates: N=0.91653, AF=0.09615, OLD=0.05779, YOUNG=0.02817
A =
[[0.99668471 0.0015609  0.00175439]
 [0.00765462 0.98923366 0.00311172]
 [0.00604309 0.00215021 0.9918067 ]]
pi = [0.70029802 0.01547503 0.28422694]
Iter 13: LL=-1289155.57 | Rates: N=0.91653, AF=0.09614, OLD=0.05856, YOUNG=0.02828
A =
[[0.9966847  0.00152748 0.00178782]
 [0.00770585 0.98894065 0.0033535 ]
 [0.00604168 0.00219403 0.99176428]]
pi = [0.70030347 0.01178211 0.28791442]
Iter 14: LL=-1289150.55 | Rates: N=0.91653, AF=0.09614, OLD=0.05936, YOUNG=0.02840
A =
[[0.99668468 0.00149399 0.00182133]
 [0.00775539 0.988634   0.00361061]
 [0.00604302 0.00223643 0.99172055]]
pi = [0.70030669 0.00891369 0.29077961]
Iter 15: LL=-1289145.48 | Rates: N=0.91653, AF=0.09613, OLD=0.06018, YOUNG=0.02851
A =
[[0.99668468 0.00146051 0.00185482]
 [0.00780376 0.98831272 0.00388352]
 [0.00604651 0.00227717 0.99167632]]
pi = [0.70030809 0.00669476 0.29299715]
Final Global Rates (lambdas): [0.91652948 0.09613281 0.06018454 0.0285114 ]
Final transition matrix A:
[[0.99668468 0.00146051 0.00185482]
 [0.00780376 0.98831272 0.00388352]
 [0.00604651 0.00227717 0.99167632]]
Final initial distribution pi:
[0.70030809 0.00669476 0.29299715]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4434,0.2754,0.3398,38988724.0,48945276.0,102563611.0
Archaic_young,0.5789,0.7440,0.6511,142983180.0,104018820.0,49211414.0
Modern,0.0000,0.0000,0.0000,0.0,665064000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         661427          804           1701
Archaic_old      1598        39092         101715
Archaic_young    2039        48038         143586

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4343  0.5275  0.4764
Archaic_young     0.5886  0.4980  0.5395

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         641331         1382           1129
Archaic_old      2004        79119          69378
Archaic_young    2339       101289         102029

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1567115.18 | Rates: N=0.91055, AF=0.09653, OLD=0.04609, YOUNG=0.03660
A =
[[0.99626269 0.00196388 0.00177342]
 [0.00703592 0.990907   0.00205709]
 [0.00684676 0.00222086 0.99093238]]
pi = [0.79892041 0.1024289  0.09865069]
Iter 2: LL=-1288920.95 | Rates: N=0.91079, AF=0.09633, OLD=0.04852, YOUNG=0.03397
A =
[[0.99626786 0.00194816 0.00178398]
 [0.00717198 0.99073365 0.00209437]
 [0.00665925 0.00213558 0.99120517]]
pi = [0.80122863 0.09028291 0.10848846]
Iter 3: LL=-1288860.83 | Rates: N=0.91079, AF=0.09632, OLD=0.05153, YOUNG=0.03176
A =
[[0.99626917 0.00192654 0.00180429]
 [0.00739046 0.99046041 0.00214913]
 [0.00646817 0.00203087 0.99150096]]
pi = [0.80120213 0.07517182 0.12362604]
Iter 4: LL=-1288804.36 | Rates: N=0.91079, AF=0.09630, OLD=0.05432, YOUNG=0.03029
A =
[[0.99627002 0.00189298 0.001837  ]
 [0.00763403 0.99013102 0.00223495]
 [0.00629509 0.00193392 0.99177099]]
pi = [0.80110246 0.05845629 0.14044126]
Iter 5: LL=-1288768.56 | Rates: N=0.91079, AF=0.09628, OLD=0.05659, YOUNG=0.02955
A =
[[0.99627037 0.00184942 0.00188021]
 [0.00785751 0.98978991 0.00235258]
 [0.00617291 0.00186545 0.99196164]]
pi = [0.80100312 0.04351204 0.15548484]
Iter 6: LL=-1288749.30 | Rates: N=0.91079, AF=0.09627, OLD=0.05840, YOUNG=0.02931
A =
[[0.99627043 0.00179806 0.00193151]
 [0.00804566 0.9894557  0.00249864]
 [0.0060997  0.00182245 0.99207785]]
pi = [0.80093444 0.03173449 0.16733107]
Iter 7: LL=-1288737.39 | Rates: N=0.91079, AF=0.09626, OLD=0.05991, YOUNG=0.02933
A =
[[0.99627041 0.00174111 0.00198848]
 [0.00820084 0.98913106 0.0026681 ]
 [0.0060627  0.0017952  0.9921421 ]]
pi = [0.80089622 0.02286065 0.17624313]
Iter 8: LL=-1288727.92 | Rates: N=0.91079, AF=0.09625, OLD=0.06127, YOUNG=0.02947
A =
[[0.99627043 0.00168056 0.00204902]
 [0.00832954 0.98881356 0.0028569 ]
 [0.00605046 0.00177629 0.99217325]]
pi = [0.80087786 0.0162303  0.18289184]
Iter 9: LL=-1288719.17 | Rates: N=0.91079, AF=0.09625, OLD=0.06259, YOUNG=0.02967
A =
[[0.99627049 0.00161796 0.00211154]
 [0.00843759 0.98849966 0.00306275]
 [0.00605482 0.00176144 0.99218374]]
pi = [0.80087101 0.01129563 0.18783336]
Iter 10: LL=-1288710.61 | Rates: N=0.91079, AF=0.09624, OLD=0.06389, YOUNG=0.02989
A =
[[0.99627061 0.00155446 0.00217492]
 [0.00852948 0.98818567 0.00328485]
 [0.00607029 0.0017484  0.99218131]]
pi = [0.80087087 0.00766438 0.19146475]
Iter 11: LL=-1288702.11 | Rates: N=0.91079, AF=0.09624, OLD=0.06523, YOUNG=0.03011
A =
[[0.99627078 0.00149087 0.00223835]
 [0.00860855 0.98786816 0.00352329]
 [0.00609313 0.00173604 0.99217084]]
pi = [0.80087482 0.00504654 0.19407864]
Iter 12: LL=-1288693.62 | Rates: N=0.91079, AF=0.09623, OLD=0.06662, YOUNG=0.03033
A =
[[0.996271   0.00142777 0.00230123]
 [0.00867731 0.98754404 0.00377865]
 [0.00612076 0.00172378 0.99215546]]
pi = [0.80088142 0.00321212 0.19590645]
Iter 13: LL=-1288685.15 | Rates: N=0.91079, AF=0.09623, OLD=0.06806, YOUNG=0.03055
A =
[[0.99627125 0.00136559 0.00236315]
 [0.00873759 0.98721061 0.0040518 ]
 [0.00615141 0.00171135 0.99213724]]
pi = [0.80088983 0.00197028 0.1971399 ]
Iter 14: LL=-1288676.68 | Rates: N=0.91079, AF=0.09622, OLD=0.06957, YOUNG=0.03077
A =
[[0.99627153 0.00130468 0.00242379]
 [0.00879075 0.98686559 0.00434366]
 [0.00618382 0.00169863 0.99211755]]
pi = [0.80089948 0.00116178 0.19793874]
Iter 15: LL=-1288668.25 | Rates: N=0.91079, AF=0.09622, OLD=0.07114, YOUNG=0.03098
A =
[[0.99627183 0.00124526 0.0024829 ]
 [0.00883779 0.98650703 0.00465518]
 [0.00621709 0.0016856  0.99209731]]
pi = [8.00910014e-01 6.57245589e-04 1.98432740e-01]
Final Global Rates (lambdas): [0.91078658 0.09621915 0.07113857 0.03098011]
Final transition matrix A:
[[0.99627183 0.00124526 0.0024829 ]
 [0.00883779 0.98650703 0.00465518]
 [0.00621709 0.0016856  0.99209731]]
Final initial distribution pi:
[8.00910014e-01 6.57245589e-04 1.98432740e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4717,0.1711,0.2511,25609112.0,28686888.0,124048052.0
Archaic_young,0.5809,0.8555,0.6920,174494557.0,125884443.0,29463325.0
Modern,0.0000,0.0000,0.0000,0.0,645325000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         641288          487           2067
Archaic_old      1886        25660         122955
Archaic_young    2151        28149         175357

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4470  0.4930  0.4688
Archaic_young     0.6239  0.5804  0.6014

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         629643         1376           1447
Archaic_old      2485        73359          73605
Archaic_young    2826        89197         126062

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1560407.05 | Rates: N=0.90079, AF=0.09612, OLD=0.04952, YOUNG=0.04046
A =
[[0.99584301 0.00213121 0.00202578]
 [0.00754174 0.99001244 0.00244581]
 [0.00720089 0.00245022 0.9903489 ]]
pi = [0.64928438 0.18012464 0.17059098]
Iter 2: LL=-1291076.96 | Rates: N=0.90105, AF=0.09597, OLD=0.05188, YOUNG=0.03766
A =
[[0.99585774 0.00211974 0.00202252]
 [0.00766234 0.98984607 0.00249159]
 [0.00701151 0.00237404 0.99061445]]
pi = [0.65109947 0.16877563 0.1801249 ]
Iter 3: LL=-1291013.49 | Rates: N=0.90105, AF=0.09595, OLD=0.05529, YOUNG=0.03502
A =
[[0.99585953 0.00211478 0.00202569]
 [0.00786526 0.98958853 0.0025462 ]
 [0.00683879 0.0022866  0.99087462]]
pi = [0.6511373 0.1544925 0.1943702]
Iter 4: LL=-1290939.91 | Rates: N=0.90105, AF=0.09592, OLD=0.05868, YOUNG=0.03293
A =
[[0.9958607  0.00210002 0.00203928]
 [0.00810002 0.98926234 0.00263764]
 [0.00666817 0.00220488 0.99112695]]
pi = [0.65107947 0.13778097 0.21113956]
Iter 5: LL=-1290885.47 | Rates: N=0.90105, AF=0.09589, OLD=0.06150, YOUNG=0.03165
A =
[[0.99586129 0.00207471 0.002064  ]
 [0.00831996 0.9889046  0.00277544]
 [0.00653721 0.00215783 0.99130497]]
pi = [0.65103377 0.12186342 0.22710281]
Iter 6: LL=-1290856.22 | Rates: N=0.90105, AF=0.09586, OLD=0.06366, YOUNG=0.03103
A =
[[0.99586143 0.00204041 0.00209816]
 [0.00850491 0.98853745 0.00295764]
 [0.00645166 0.00214768 0.99140066]]
pi = [0.65102645 0.10896422 0.24000933]
Iter 7: LL=-1290841.04 | Rates: N=0.90105, AF=0.09584, OLD=0.06534, YOUNG=0.03081
A =
[[0.9958614  0.00199938 0.00213922]
 [0.00865711 0.9881679  0.00317499]
 [0.00640078 0.00216243 0.99143679]]
pi = [0.65104805 0.09953717 0.24941478]
Iter 8: LL=-1290831.14 | Rates: N=0.90105, AF=0.09583, OLD=0.06674, YOUNG=0.03080
A =
[[0.99586139 0.00195383 0.00218478]
 [0.00878466 0.98779731 0.00341803]
 [0.00637318 0.00219057 0.99143626]]
pi = [0.65107615 0.09301667 0.25590718]
Iter 9: LL=-1290822.95 | Rates: N=0.90105, AF=0.09582, OLD=0.06799, YOUNG=0.03090
A =
[[0.99586144 0.00190554 0.00223301]
 [0.00889455 0.98742542 0.00368004]
 [0.0063608  0.00222477 0.99141443]]
pi = [0.65109568 0.08859923 0.26030509]
Iter 10: LL=-1290815.37 | Rates: N=0.90105, AF=0.09581, OLD=0.06918, YOUNG=0.03104
A =
[[0.99586156 0.0018558  0.00228264]
 [0.00899168 0.98705136 0.00395696]
 [0.00635848 0.00226102 0.9913805 ]]
pi = [0.65110194 0.08559692 0.26330114]
Iter 11: LL=-1290808.10 | Rates: N=0.90105, AF=0.09580, OLD=0.07034, YOUNG=0.03120
A =
[[0.99586173 0.00180547 0.0023328 ]
 [0.00907943 0.98667406 0.00424651]
 [0.00636288 0.0022972  0.99133992]]
pi = [0.65109611 0.08351141 0.26539249]
Iter 12: LL=-1290801.06 | Rates: N=0.90105, AF=0.09579, OLD=0.07150, YOUNG=0.03137
A =
[[0.99586195 0.00175516 0.00238289]
 [0.00916016 0.98629236 0.00454748]
 [0.00637181 0.00233222 0.99129598]]
pi = [0.65108128 0.08200702 0.2669117 ]
Iter 13: LL=-1290794.22 | Rates: N=0.90105, AF=0.09579, OLD=0.07267, YOUNG=0.03154
A =
[[0.9958622  0.00170532 0.00243248]
 [0.00923562 0.98590519 0.00485919]
 [0.00638375 0.00236548 0.99125077]]
pi = [0.65106053 0.08086573 0.26807374]
Iter 14: LL=-1290787.60 | Rates: N=0.90105, AF=0.09578, OLD=0.07386, YOUNG=0.03170
A =
[[0.99586247 0.00165623 0.00248129]
 [0.00930715 0.98551157 0.00518128]
 [0.00639767 0.00239667 0.99120566]]
pi = [0.65103629 0.07994895 0.26901476]
Iter 15: LL=-1290781.18 | Rates: N=0.90105, AF=0.09577, OLD=0.07506, YOUNG=0.03187
A =
[[0.99586276 0.00160814 0.0025291 ]
 [0.00937578 0.9851107  0.00551351]
 [0.00641281 0.00242563 0.99116156]]
pi = [0.65101023 0.07917007 0.2698197 ]
Final Global Rates (lambdas): [0.90104895 0.09577399 0.07505766 0.03186911]
Final transition matrix A:
[[0.99586276 0.00160814 0.0025291 ]
 [0.00937578 0.9851107  0.00551351]
 [0.00641281 0.00242563 0.99116156]]
Final initial distribution pi:
[0.65101023 0.07917007 0.2698197 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4549,0.2088,0.2862,31029312.0,37178688.0,117609410.0
Archaic_young,0.5992,0.8242,0.6939,178166161.0,119174839.0,38000622.0
Modern,0.0000,0.0000,0.0000,0.0,634451000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         629617          636           2213
Archaic_old      2319        31077         116053
Archaic_young    2515        36495         179075

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4894  0.4934  0.4914
Archaic_young     0.5814  0.5780  0.5797

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         639373         1517           1731
Archaic_old      2897        78825          78742
Archaic_young    3313        80331         113271

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1582335.78 | Rates: N=0.90586, AF=0.09869, OLD=0.05790, YOUNG=0.04757
A =
[[0.99552226 0.00228501 0.00219273]
 [0.00848184 0.98878565 0.00273251]
 [0.00824904 0.00276652 0.98898445]]
pi = [0.50499313 0.25244481 0.24256205]
Iter 2: LL=-1306797.73 | Rates: N=0.90613, AF=0.09857, OLD=0.06112, YOUNG=0.04385
A =
[[0.99555122 0.00226564 0.00218314]
 [0.00863623 0.98857714 0.00278663]
 [0.00797037 0.00265897 0.98937067]]
pi = [0.50029809 0.23343773 0.26626418]
Iter 3: LL=-1306702.02 | Rates: N=0.90613, AF=0.09854, OLD=0.06582, YOUNG=0.04036
A =
[[0.9955548  0.00225888 0.00218632]
 [0.0089297  0.98821886 0.00285144]
 [0.00771759 0.00252433 0.98975809]]
pi = [0.50010504 0.2043217  0.29557326]
Iter 4: LL=-1306591.98 | Rates: N=0.90613, AF=0.09849, OLD=0.07038, YOUNG=0.03778
A =
[[0.99555678 0.0022416  0.00220162]
 [0.00925401 0.98778634 0.00295965]
 [0.00748748 0.00240308 0.99010944]]
pi = [0.50012446 0.17508703 0.32478852]
Iter 5: LL=-1306518.39 | Rates: N=0.90613, AF=0.09845, OLD=0.07396, YOUNG=0.03637
A =
[[0.99555757 0.00221243 0.00223   ]
 [0.0095362  0.98733724 0.00312656]
 [0.0073292  0.00233743 0.99033337]]
pi = [0.50028366 0.15363785 0.34607849]
Iter 6: LL=-1306483.78 | Rates: N=0.90613, AF=0.09841, OLD=0.07659, YOUNG=0.03581
A =
[[0.99555761 0.00217287 0.00226952]
 [0.00976087 0.98688836 0.00335077]
 [0.00723631 0.00232197 0.99044173]]
pi = [0.50046319 0.14057411 0.35896269]
Iter 7: LL=-1306466.82 | Rates: N=0.90613, AF=0.09838, OLD=0.07862, YOUNG=0.03570
A =
[[0.99555748 0.00212559 0.00231693]
 [0.00994084 0.98643896 0.00362021]
 [0.00718703 0.00233623 0.99047673]]
pi = [0.50055575 0.13309951 0.36634474]
Iter 8: LL=-1306455.23 | Rates: N=0.90613, AF=0.09836, OLD=0.08035, YOUNG=0.03580
A =
[[0.9955574  0.00207324 0.00236936]
 [0.01009053 0.98598586 0.00392361]
 [0.00716479 0.00236513 0.99047008]]
pi = [0.50055062 0.12874992 0.37069947]
Iter 9: LL=-1306445.03 | Rates: N=0.90612, AF=0.09835, OLD=0.08196, YOUNG=0.03600
A =
[[0.99555743 0.0020178  0.00242478]
 [0.01021999 0.98552603 0.00425398]
 [0.0071594  0.00240048 0.99044012]]
pi = [0.50047842 0.12607355 0.37344803]
Iter 10: LL=-1306435.20 | Rates: N=0.90612, AF=0.09833, OLD=0.08353, YOUNG=0.03622
A =
[[0.99555754 0.00196061 0.00248185]
 [0.01033575 0.98505647 0.00460778]
 [0.0071647  0.00243826 0.99039704]]
pi = [0.50036773 0.1243162  0.37531607]
Iter 11: LL=-1306425.49 | Rates: N=0.90612, AF=0.09832, OLD=0.08512, YOUNG=0.03646
A =
[[0.99555772 0.00190256 0.00253973]
 [0.01044228 0.98457412 0.0049836 ]
 [0.00717685 0.00247652 0.99034663]]
pi = [0.50023628 0.12309687 0.37666685]
Iter 12: LL=-1306415.84 | Rates: N=0.90612, AF=0.09831, OLD=0.08675, YOUNG=0.03670
A =
[[0.99555794 0.00184424 0.00259782]
 [0.01054286 0.98407592 0.00538122]
 [0.0071933  0.0025143  0.99029239]]
pi = [0.50009378 0.12221919 0.37768703]
Iter 13: LL=-1306406.24 | Rates: N=0.90612, AF=0.09830, OLD=0.08843, YOUNG=0.03694
A =
[[0.99555818 0.00178609 0.00265573]
 [0.01064006 0.98355892 0.00580102]
 [0.00721234 0.00255112 0.99023654]]
pi = [0.49994543 0.12157702 0.37847756]
Iter 14: LL=-1306396.68 | Rates: N=0.90612, AF=0.09829, OLD=0.09016, YOUNG=0.03717
A =
[[0.99555842 0.0017284  0.00271318]
 [0.01073596 0.98302027 0.00624377]
 [0.00723276 0.0025867  0.99018054]]
pi = [0.49979408 0.12110913 0.37909679]
Iter 15: LL=-1306387.15 | Rates: N=0.90612, AF=0.09828, OLD=0.09197, YOUNG=0.03740
A =
[[0.99555866 0.00167141 0.00276993]
 [0.01083236 0.98245722 0.00671042]
 [0.00725372 0.00262089 0.9901254 ]]
pi = [0.49964131 0.12077761 0.37958108]
Final Global Rates (lambdas): [0.90612072 0.09827677 0.09196532 0.03740495]
Final transition matrix A:
[[0.99555866 0.00167141 0.00276993]
 [0.01083236 0.98245722 0.00671042]
 [0.00725372 0.00262089 0.9901254 ]]
Final initial distribution pi:
[0.49964131 0.12077761 0.37958108]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5426,0.2013,0.2937,32086226.0,27043774.0,127290625.0
Archaic_young,0.5631,0.8482,0.6769,165304758.0,128263242.0,29575182.0
Modern,0.0000,0.0000,0.0000,0.0,647302000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         639901          210           2510
Archaic_old      3561        32082         124821
Archaic_young    3840        26838         166237

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4791  0.4391  0.4582
Archaic_young     0.5736  0.6126  0.5924

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         626470         1504           1849
Archaic_old      3187        72174          89767
Archaic_young    3262        76709         125078

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1585341.40 | Rates: N=0.90370, AF=0.09846, OLD=0.06336, YOUNG=0.05351
A =
[[0.99517483 0.00243242 0.00239275]
 [0.0086081  0.98832735 0.00306455]
 [0.00840589 0.00305417 0.98853994]]
pi = [0.79272133 0.10731854 0.09996013]
Iter 2: LL=-1311610.44 | Rates: N=0.90397, AF=0.09837, OLD=0.06617, YOUNG=0.04999
A =
[[0.99523601 0.00239582 0.00236817]
 [0.00866484 0.98822866 0.0031065 ]
 [0.00811525 0.00297535 0.9889094 ]]
pi = [0.80351594 0.09754742 0.09893663]
Iter 3: LL=-1311533.77 | Rates: N=0.90396, AF=0.09836, OLD=0.07061, YOUNG=0.04646
A =
[[0.99524085 0.00238725 0.0023719 ]
 [0.00889941 0.98794835 0.00315224]
 [0.00790082 0.00287676 0.98922242]]
pi = [0.8041396  0.09224042 0.10361998]
Iter 4: LL=-1311431.68 | Rates: N=0.90396, AF=0.09832, OLD=0.07533, YOUNG=0.04344
A =
[[0.99524238 0.00236756 0.00239006]
 [0.00919314 0.98756613 0.00324073]
 [0.00767905 0.00277456 0.98954639]]
pi = [0.80423534 0.08770709 0.10805757]
Iter 5: LL=-1311346.63 | Rates: N=0.90396, AF=0.09827, OLD=0.07943, YOUNG=0.04150
A =
[[0.99524319 0.00233397 0.00242283]
 [0.00947716 0.98713106 0.00339178]
 [0.00750256 0.00271375 0.98978369]]
pi = [0.80436477 0.08508128 0.11055395]
Iter 6: LL=-1311298.48 | Rates: N=0.90396, AF=0.09822, OLD=0.08260, YOUNG=0.04053
A =
[[0.99524342 0.00228847 0.00246811]
 [0.00971653 0.98667486 0.00360861]
 [0.00738655 0.0027041  0.98990936]]
pi = [0.80448477 0.08439614 0.11111908]
Iter 7: LL=-1311274.03 | Rates: N=0.90396, AF=0.09819, OLD=0.08505, YOUNG=0.04017
A =
[[0.9952434  0.00223423 0.00252237]
 [0.00991127 0.98620829 0.00388045]
 [0.00731842 0.00272993 0.98995165]]
pi = [0.80452821 0.08497985 0.11049194]
Iter 8: LL=-1311258.85 | Rates: N=0.90396, AF=0.09816, OLD=0.08707, YOUNG=0.04014
A =
[[0.99524338 0.00217444 0.00258218]
 [0.0100723  0.98573376 0.00419394]
 [0.00728229 0.00277438 0.98994333]]
pi = [0.80449191 0.08619503 0.10931306]
Iter 9: LL=-1311246.61 | Rates: N=0.90395, AF=0.09815, OLD=0.08887, YOUNG=0.04026
A =
[[0.99524345 0.00211162 0.00264493]
 [0.01020971 0.98525103 0.00453926]
 [0.00726666 0.00282671 0.98990664]]
pi = [0.80440262 0.08763373 0.10796366]
Iter 10: LL=-1311235.33 | Rates: N=0.90395, AF=0.09813, OLD=0.09058, YOUNG=0.04045
A =
[[0.99524359 0.00204748 0.00270892]
 [0.01033067 0.98475872 0.00491062]
 [0.00726418 0.00288123 0.98985459]]
pi = [0.80428515 0.0890682  0.10664665]
Iter 11: LL=-1311224.48 | Rates: N=0.90395, AF=0.09812, OLD=0.09227, YOUNG=0.04067
A =
[[0.99524379 0.00198315 0.00277305]
 [0.01044011 0.9842549  0.00530499]
 [0.00727021 0.00293517 0.98979462]]
pi = [0.80415531 0.09037664 0.10546805]
Iter 12: LL=-1311213.90 | Rates: N=0.90395, AF=0.09810, OLD=0.09396, YOUNG=0.04090
A =
[[0.99524403 0.00191933 0.00283664]
 [0.01054152 0.9837375  0.00572097]
 [0.00728176 0.0029872  0.98973104]]
pi = [0.80402215 0.09149522 0.10448263]
Iter 13: LL=-1311203.56 | Rates: N=0.90395, AF=0.09809, OLD=0.09567, YOUNG=0.04113
A =
[[0.99524428 0.00185646 0.00289926]
 [0.01063744 0.98320451 0.00615805]
 [0.00729686 0.00303673 0.98966641]]
pi = [0.80389077 0.09239277 0.10371646]
Iter 14: LL=-1311193.44 | Rates: N=0.90395, AF=0.09808, OLD=0.09743, YOUNG=0.04136
A =
[[0.99524453 0.00179482 0.00296065]
 [0.01072979 0.98265409 0.00661612]
 [0.00731413 0.00308351 0.98960236]]
pi = [0.80376411 0.09305794 0.10317796]
Iter 15: LL=-1311183.53 | Rates: N=0.90395, AF=0.09806, OLD=0.09923, YOUNG=0.04159
A =
[[0.99524478 0.0017346  0.00302062]
 [0.01082009 0.98208459 0.00709532]
 [0.00733266 0.00312744 0.9895399 ]]
pi = [0.80364381 0.09349231 0.10286388]
Final Global Rates (lambdas): [0.90394843 0.09806483 0.0992265  0.0415894 ]
Final transition matrix A:
[[0.99524478 0.0017346  0.00302062]
 [0.01082009 0.98208459 0.00709532]
 [0.00733266 0.00312744 0.9895399 ]]
Final initial distribution pi:
[0.80364381 0.09349231 0.10286388]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4916,0.1931,0.2772,31678370.0,32762630.0,132407324.0
Archaic_young,0.5566,0.8252,0.6648,167420417.0,133363583.0,35460976.0
Modern,0.0000,0.0000,0.0000,0.0,634775000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         627064          211           2548
Archaic_old      3720        31657         129751
Archaic_young    3991        32573         168485

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4309  0.7477  0.5467
Archaic_young     0.5784  0.2560  0.3549

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         656436         1992            531
Archaic_old      2476       109753          35149
Archaic_young    1946       142330          49387

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1569729.48 | Rates: N=0.91266, AF=0.09656, OLD=0.04695, YOUNG=0.03100
A =
[[0.9965158  0.00215267 0.00133153]
 [0.00712223 0.99138517 0.0014926 ]
 [0.0066214  0.00224097 0.99113763]]
pi = [0.64840231 0.19418384 0.15741386]
Iter 2: LL=-1289351.85 | Rates: N=0.91290, AF=0.09635, OLD=0.04917, YOUNG=0.02887
A =
[[0.99651239 0.00212798 0.00135963]
 [0.00742985 0.99097519 0.00159497]
 [0.00622949 0.00208939 0.99168113]]
pi = [0.64903718 0.17840773 0.17255509]
Iter 3: LL=-1289305.71 | Rates: N=0.91290, AF=0.09633, OLD=0.05135, YOUNG=0.02767
A =
[[0.99651216 0.00209877 0.00138907]
 [0.00772189 0.99056393 0.00171419]
 [0.00596398 0.00199522 0.99204081]]
pi = [0.64903106 0.16412275 0.18684619]
Iter 4: LL=-1289278.09 | Rates: N=0.91290, AF=0.09631, OLD=0.05312, YOUNG=0.02712
A =
[[0.99651188 0.00206297 0.00142514]
 [0.00796725 0.99017367 0.00185908]
 [0.00579793 0.00195123 0.99225085]]
pi = [0.64901588 0.15119487 0.19978926]
Iter 5: LL=-1289262.63 | Rates: N=0.91290, AF=0.09630, OLD=0.05454, YOUNG=0.02698
A =
[[0.99651154 0.00202131 0.00146714]
 [0.00816734 0.98980397 0.00202869]
 [0.00570308 0.00194185 0.99235507]]
pi = [0.64900827 0.13945215 0.21153958]
Iter 6: LL=-1289252.02 | Rates: N=0.91290, AF=0.09629, OLD=0.05576, YOUNG=0.02704
A =
[[0.99651127 0.00197494 0.00151379]
 [0.00833529 0.98944381 0.0022209 ]
 [0.00565287 0.00195177 0.99239536]]
pi = [0.64900588 0.12850619 0.22248793]
Iter 7: LL=-1289242.83 | Rates: N=0.91290, AF=0.09628, OLD=0.05688, YOUNG=0.02720
A =
[[0.99651109 0.00192505 0.00156386]
 [0.00848283 0.98908311 0.00243406]
 [0.00563018 0.00197131 0.9923985 ]]
pi = [0.64900641 0.11803317 0.23296042]
Iter 8: LL=-1289233.91 | Rates: N=0.91290, AF=0.09628, OLD=0.05798, YOUNG=0.02740
A =
[[0.99651099 0.00187265 0.00161636]
 [0.00861776 0.98871474 0.0026675 ]
 [0.00562497 0.00199525 0.99237978]]
pi = [0.64900856 0.10781959 0.24317185]
Iter 9: LL=-1289224.91 | Rates: N=0.91290, AF=0.09627, OLD=0.05911, YOUNG=0.02762
A =
[[0.99651095 0.00181847 0.00167057]
 [0.00874493 0.9883336  0.00292147]
 [0.00563131 0.00202088 0.99234781]]
pi = [0.64901168 0.09774534 0.25324298]
Iter 10: LL=-1289215.73 | Rates: N=0.91290, AF=0.09626, OLD=0.06028, YOUNG=0.02783
A =
[[0.99651096 0.00176305 0.00172598]
 [0.00886742 0.9879358  0.00319677]
 [0.00564556 0.00204681 0.99230764]]
pi = [0.64901553 0.08776411 0.26322036]
Iter 11: LL=-1289206.34 | Rates: N=0.91290, AF=0.09626, OLD=0.06151, YOUNG=0.02804
A =
[[0.99651102 0.0017068  0.00178218]
 [0.0089873  0.98751811 0.00349459]
 [0.00566533 0.00207231 0.99226237]]
pi = [0.64902001 0.07788957 0.27309042]
Iter 12: LL=-1289196.73 | Rates: N=0.91290, AF=0.09625, OLD=0.06281, YOUNG=0.02825
A =
[[0.99651111 0.00165004 0.00183885]
 [0.00910603 0.98707766 0.00381631]
 [0.00568899 0.00209698 0.99221402]]
pi = [0.64902505 0.06818467 0.28279027]
Iter 13: LL=-1289186.88 | Rates: N=0.91290, AF=0.09624, OLD=0.06419, YOUNG=0.02846
A =
[[0.99651123 0.00159304 0.00189573]
 [0.00922472 0.98661183 0.00416346]
 [0.00571539 0.00212061 0.992164  ]]
pi = [0.64903061 0.05875161 0.29221779]
Iter 14: LL=-1289176.83 | Rates: N=0.91290, AF=0.09624, OLD=0.06565, YOUNG=0.02866
A =
[[0.99651138 0.00153602 0.0019526 ]
 [0.00934427 0.98611814 0.00453759]
 [0.00574363 0.00214309 0.99211328]]
pi = [0.64903658 0.04972038 0.30124304]
Iter 15: LL=-1289166.56 | Rates: N=0.91290, AF=0.09623, OLD=0.06721, YOUNG=0.02886
A =
[[0.99651156 0.00147919 0.00200926]
 [0.00946547 0.98559422 0.00494031]
 [0.00577304 0.00216436 0.9920626 ]]
pi = [0.64904283 0.04123526 0.30972191]
Final Global Rates (lambdas): [0.91290315 0.09622952 0.06721081 0.02885736]
Final transition matrix A:
[[0.99651156 0.00147919 0.00200926]
 [0.00946547 0.98559422 0.00494031]
 [0.00577304 0.00216436 0.9920626 ]]
Final initial distribution pi:
[0.64904283 0.04123526 0.30972191]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4968,0.2239,0.3087,32779272.0,33198728.0,113629146.0
Archaic_young,0.5802,0.8257,0.6815,158686340.0,114821660.0,33508254.0
Modern,0.0000,0.0000,0.0000,0.0,660514000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         656396          674           1889
Archaic_old      2232        32885         112261
Archaic_young    1886        32419         159358

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4709  0.7306  0.5727
Archaic_young     0.6759  0.4029  0.5049

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         640396         2125            735
Archaic_old      2776       109944          38367
Archaic_young    2460       120715          82482

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1566697.93 | Rates: N=0.90675, AF=0.09601, OLD=0.05127, YOUNG=0.03513
A =
[[0.99596503 0.00238654 0.00164843]
 [0.00781028 0.99033342 0.0018563 ]
 [0.00709489 0.00243951 0.9904656 ]]
pi = [0.70782146 0.15337996 0.13879858]
Iter 2: LL=-1291942.43 | Rates: N=0.90702, AF=0.09582, OLD=0.05387, YOUNG=0.03251
A =
[[0.99596993 0.00236049 0.00166958]
 [0.00814658 0.98989881 0.00195461]
 [0.00669211 0.00226862 0.99103926]]
pi = [0.71050691 0.13118589 0.1583072 ]
Iter 3: LL=-1291880.76 | Rates: N=0.90702, AF=0.09579, OLD=0.05660, YOUNG=0.03092
A =
[[0.99597009 0.00233575 0.00169416]
 [0.00848847 0.98945235 0.00205919]
 [0.0064137  0.00214623 0.99144007]]
pi = [0.71062165 0.10665262 0.18272573]
Iter 4: LL=-1291841.95 | Rates: N=0.90702, AF=0.09577, OLD=0.05880, YOUNG=0.03013
A =
[[0.99596962 0.00230225 0.00172814]
 [0.0087807  0.98903481 0.00218449]
 [0.00623358 0.00207288 0.99169353]]
pi = [0.71053682 0.08170473 0.20775845]
Iter 5: LL=-1291821.97 | Rates: N=0.90702, AF=0.09575, OLD=0.06049, YOUNG=0.02986
A =
[[0.99596893 0.0022607  0.00177037]
 [0.00901291 0.98865826 0.00232884]
 [0.00613163 0.00203864 0.99182973]]
pi = [0.71042325 0.0596233  0.22995344]
Iter 6: LL=-1291810.72 | Rates: N=0.90702, AF=0.09573, OLD=0.06183, YOUNG=0.02986
A =
[[0.99596833 0.00221295 0.00181872]
 [0.0091972  0.98831426 0.00248854]
 [0.00608068 0.00202815 0.99189117]]
pi = [0.71031409 0.04194736 0.24773856]
Iter 7: LL=-1291802.56 | Rates: N=0.90702, AF=0.09572, OLD=0.06297, YOUNG=0.02999
A =
[[0.99596788 0.00216105 0.00187108]
 [0.00934815 0.98799154 0.00266031]
 [0.00606101 0.00203053 0.99190845]]
pi = [0.71022426 0.02871658 0.26105916]
Iter 8: LL=-1291795.44 | Rates: N=0.90702, AF=0.09572, OLD=0.06402, YOUNG=0.03017
A =
[[0.99596757 0.00210659 0.00192584]
 [0.00947663 0.98768121 0.00284216]
 [0.00606045 0.00203955 0.9919    ]]
pi = [0.71015959 0.01925104 0.27058937]
Iter 9: LL=-1291788.73 | Rates: N=0.90702, AF=0.09571, OLD=0.06503, YOUNG=0.03038
A =
[[0.99596737 0.00205075 0.00198188]
 [0.00958995 0.98737686 0.0030332 ]
 [0.00607167 0.00205188 0.99187645]]
pi = [0.71011983 0.01269109 0.27718908]
Iter 10: LL=-1291782.24 | Rates: N=0.90702, AF=0.09570, OLD=0.06604, YOUNG=0.03058
A =
[[0.99596724 0.00199431 0.00203846]
 [0.00969298 0.98707379 0.00323323]
 [0.00609022 0.00206575 0.99184403]]
pi = [0.71010144 0.00825063 0.28164793]
Iter 11: LL=-1291775.88 | Rates: N=0.90702, AF=0.09570, OLD=0.06705, YOUNG=0.03079
A =
[[0.99596716 0.00193781 0.00209503]
 [0.00978906 0.98676849 0.00344245]
 [0.0061133  0.00208016 0.99180654]]
pi = [0.71009987 0.00529963 0.2846005 ]
Iter 12: LL=-1291769.64 | Rates: N=0.90702, AF=0.09569, OLD=0.06808, YOUNG=0.03099
A =
[[0.99596712 0.00188164 0.00215124]
 [0.00988054 0.98645824 0.00366123]
 [0.0061391  0.00209451 0.99176639]]
pi = [0.71011078 0.00336781 0.2865214 ]
Iter 13: LL=-1291763.49 | Rates: N=0.90702, AF=0.09569, OLD=0.06914, YOUNG=0.03118
A =
[[0.99596711 0.00182608 0.00220681]
 [0.00996908 0.98614095 0.00388997]
 [0.00616645 0.00210842 0.99172513]]
pi = [0.71013054 0.00211934 0.28775012]
Iter 14: LL=-1291757.43 | Rates: N=0.90702, AF=0.09568, OLD=0.07023, YOUNG=0.03137
A =
[[0.99596711 0.00177135 0.00226153]
 [0.01005588 0.98581502 0.0041291 ]
 [0.00619458 0.00212163 0.9916838 ]]
pi = [0.71015631 0.0013216  0.28852209]
Iter 15: LL=-1291751.47 | Rates: N=0.90702, AF=0.09568, OLD=0.07134, YOUNG=0.03156
A =
[[0.99596713 0.00171761 0.00231526]
 [0.01014179 0.98547924 0.00437897]
 [0.00622296 0.00213394 0.9916431 ]]
pi = [0.71018595 0.00081709 0.28899696]
Final Global Rates (lambdas): [0.90702105 0.09567999 0.07133975 0.03155707]
Final transition matrix A:
[[0.99596713 0.00171761 0.00231526]
 [0.01014179 0.98547924 0.00437897]
 [0.00622296 0.00213394 0.9916431 ]]
Final initial distribution pi:
[0.71018595 0.00081709 0.28899696]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5292,0.2706,0.3581,40595945.0,36115055.0,109449264.0
Archaic_young,0.6023,0.8217,0.6951,167590912.0,110643088.0,36366970.0
Modern,0.0000,0.0000,0.0000,0.0,645055000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         640353          861           2042
Archaic_old      2522        40746         107819
Archaic_young    2180        35104         168373

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4683  0.6760  0.5533
Archaic_young     0.6824  0.4718  0.5579

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         628510         1929            831
Archaic_old      3013       101427          46205
Archaic_young    3015       112663         102407

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1565069.46 | Rates: N=0.90250, AF=0.09570, OLD=0.05553, YOUNG=0.03833
A =
[[0.99563368 0.00248108 0.00188525]
 [0.00808255 0.9896762  0.00224125]
 [0.00733208 0.0026279  0.99004003]]
pi = [0.84969241 0.07153177 0.07877582]
Iter 2: LL=-1294263.48 | Rates: N=0.90278, AF=0.09554, OLD=0.05892, YOUNG=0.03479
A =
[[0.9956584  0.00243834 0.00190325]
 [0.00829447 0.98935509 0.00235044]
 [0.00702054 0.00243291 0.99054655]]
pi = [0.86306033 0.04693885 0.09000083]
Iter 3: LL=-1294167.59 | Rates: N=0.90278, AF=0.09550, OLD=0.06241, YOUNG=0.03258
A =
[[0.99566037 0.00240838 0.00193125]
 [0.00851188 0.9890107  0.00247742]
 [0.00685642 0.00229121 0.99085237]]
pi = [0.86303618 0.02698286 0.10998096]
Iter 4: LL=-1294110.44 | Rates: N=0.90278, AF=0.09547, OLD=0.06509, YOUNG=0.03144
A =
[[0.99566047 0.00237125 0.00196829]
 [0.00867173 0.988679   0.00264927]
 [0.0067732  0.00221004 0.99101677]]
pi = [0.86133599 0.01230931 0.1263547 ]
Iter 5: LL=-1294084.39 | Rates: N=0.90278, AF=0.09544, OLD=0.06704, YOUNG=0.03100
A =
[[0.99566018 0.00232821 0.00201161]
 [0.00877785 0.98836216 0.00285999]
 [0.00674516 0.00217769 0.99107715]]
pi = [0.86004283 0.00464858 0.13530859]
Iter 6: LL=-1294071.16 | Rates: N=0.90278, AF=0.09543, OLD=0.06853, YOUNG=0.03092
A =
[[0.99565993 0.00228105 0.00205902]
 [0.00885004 0.9880511  0.00309886]
 [0.00674658 0.00217408 0.99107934]]
pi = [0.85939056 0.00155424 0.1390552 ]
Iter 7: LL=-1294061.80 | Rates: N=0.90278, AF=0.09541, OLD=0.06980, YOUNG=0.03102
A =
[[0.99565981 0.00223132 0.00210887]
 [0.00890349 0.98773917 0.00335734]
 [0.00676209 0.00218547 0.99105245]]
pi = [8.59131944e-01 4.81802444e-04 1.40386254e-01]
Iter 8: LL=-1294053.57 | Rates: N=0.90278, AF=0.09540, OLD=0.07096, YOUNG=0.03119
A =
[[0.99565978 0.00218011 0.00216011]
 [0.00894697 0.98742284 0.00363019]
 [0.00678385 0.00220446 0.99101168]]
pi = [8.59059866e-01 1.41819964e-04 1.40798314e-01]
Iter 9: LL=-1294045.75 | Rates: N=0.90278, AF=0.09539, OLD=0.07209, YOUNG=0.03140
A =
[[0.99565981 0.00212814 0.00221205]
 [0.00898517 0.98710027 0.00391456]
 [0.00680803 0.00222733 0.99096463]]
pi = [8.59070908e-01 4.00923692e-05 1.40889000e-01]
Iter 10: LL=-1294038.17 | Rates: N=0.90278, AF=0.09538, OLD=0.07322, YOUNG=0.03162
A =
[[0.99565988 0.00207588 0.00226423]
 [0.00902069 0.98677028 0.00420904]
 [0.00683271 0.00225215 0.99091514]]
pi = [8.59121394e-01 1.09475725e-05 1.40867658e-01]
Iter 11: LL=-1294030.79 | Rates: N=0.90278, AF=0.09538, OLD=0.07435, YOUNG=0.03183
A =
[[0.99565999 0.00202365 0.00231637]
 [0.00905504 0.98643198 0.00451298]
 [0.0068569  0.00227788 0.99086523]]
pi = [8.59193607e-01 2.89694512e-06 1.40803496e-01]
Iter 12: LL=-1294023.59 | Rates: N=0.90278, AF=0.09537, OLD=0.07551, YOUNG=0.03205
A =
[[0.99566011 0.00197165 0.00236824]
 [0.00908919 0.9860846  0.00482621]
 [0.0068801  0.00230388 0.99081602]]
pi = [8.59279997e-01 7.44610092e-07 1.40719259e-01]
Iter 13: LL=-1294016.56 | Rates: N=0.90278, AF=0.09536, OLD=0.07669, YOUNG=0.03226
A =
[[0.99566026 0.00192004 0.0024197 ]
 [0.0091238  0.98572738 0.00514882]
 [0.00690206 0.00232976 0.99076818]]
pi = [8.59376884e-01 1.86250363e-07 1.40622930e-01]
Iter 14: LL=-1294009.67 | Rates: N=0.90278, AF=0.09535, OLD=0.07790, YOUNG=0.03247
A =
[[0.99566043 0.00186893 0.00247064]
 [0.00915937 0.98535956 0.00548107]
 [0.00692269 0.00235519 0.99072212]]
pi = [8.59482108e-01 4.54121042e-08 1.40517847e-01]
Iter 15: LL=-1294002.92 | Rates: N=0.90278, AF=0.09534, OLD=0.07914, YOUNG=0.03267
A =
[[0.99566062 0.00181841 0.00252098]
 [0.00919628 0.98498033 0.00582339]
 [0.00694196 0.00237996 0.99067808]]
pi = [8.59594156e-01 1.08101556e-08 1.40405833e-01]
Final Global Rates (lambdas): [0.9027816  0.0953411  0.0791387  0.03267487]
Final transition matrix A:
[[0.99566062 0.00181841 0.00252098]
 [0.00919628 0.98498033 0.00582339]
 [0.00694196 0.00237996 0.99067808]]
Final initial distribution pi:
[8.59594156e-01 1.08101556e-08 1.40405833e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5278,0.2857,0.3707,42759289.0,38247711.0,106900856.0
Archaic_young,0.6211,0.8188,0.7064,177002642.0,107972358.0,39164141.0
Modern,0.0000,0.0000,0.0000,0.0,634018000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         628464          746           2060
Archaic_old      2768        42882         104995
Archaic_young    2786        37379         177920

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4934  0.6856  0.5739
Archaic_young     0.6334  0.4323  0.5139

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         640292         2236           1030
Archaic_old      3302       108896          47329
Archaic_young    3339       108917          84659

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1586408.59 | Rates: N=0.90927, AF=0.09699, OLD=0.06447, YOUNG=0.04544
A =
[[0.99536128 0.00262618 0.00201255]
 [0.0089496  0.98856949 0.00248091]
 [0.00839564 0.00300796 0.9885964 ]]
pi = [0.61965955 0.21684092 0.16349954]
Iter 2: LL=-1308354.28 | Rates: N=0.90956, AF=0.09683, OLD=0.06887, YOUNG=0.04092
A =
[[0.99540306 0.00257093 0.00202601]
 [0.00923683 0.98814995 0.00261322]
 [0.00792025 0.0027705  0.98930926]]
pi = [0.61923183 0.21954338 0.16122479]
Iter 3: LL=-1308220.49 | Rates: N=0.90956, AF=0.09678, OLD=0.07364, YOUNG=0.03805
A =
[[0.99540596 0.0025322  0.00206185]
 [0.00957876 0.98764366 0.00277758]
 [0.00764968 0.00259245 0.98975788]]
pi = [0.61884711 0.22209713 0.15905576]
Iter 4: LL=-1308135.84 | Rates: N=0.90956, AF=0.09673, OLD=0.07743, YOUNG=0.03665
A =
[[0.9954057  0.00248165 0.00211265]
 [0.00984122 0.98714614 0.00301264]
 [0.00750963 0.00249575 0.98999461]]
pi = [0.6181263  0.22251357 0.15936013]
Iter 5: LL=-1308095.65 | Rates: N=0.90956, AF=0.09668, OLD=0.08031, YOUNG=0.03619
A =
[[0.99540504 0.00242116 0.0021738 ]
 [0.0100231  0.98665924 0.00331766]
 [0.00745944 0.00246161 0.99007895]]
pi = [0.61746625 0.22109965 0.16143409]
Iter 6: LL=-1308073.00 | Rates: N=0.90956, AF=0.09665, OLD=0.08267, YOUNG=0.03620
A =
[[0.99540458 0.0023541  0.00224132]
 [0.01015454 0.98616371 0.00368175]
 [0.00745715 0.00246068 0.99008217]]
pi = [0.61697624 0.21885404 0.16416972]
Iter 7: LL=-1308054.89 | Rates: N=0.90956, AF=0.09663, OLD=0.08483, YOUNG=0.03642
A =
[[0.99540436 0.00228333 0.00231231]
 [0.0102587  0.98564564 0.00409566]
 [0.00747831 0.00247468 0.99004701]]
pi = [0.61660571 0.21646745 0.16692684]
Iter 8: LL=-1308037.61 | Rates: N=0.90956, AF=0.09661, OLD=0.08695, YOUNG=0.03672
A =
[[0.99540429 0.00221077 0.00238494]
 [0.01034881 0.9850965  0.00455469]
 [0.00751056 0.0024947  0.98999474]]
pi = [0.61629246 0.21424809 0.16945946]
Iter 9: LL=-1308020.29 | Rates: N=0.90956, AF=0.09659, OLD=0.08913, YOUNG=0.03707
A =
[[0.99540433 0.00213757 0.0024581 ]
 [0.01043226 0.98451021 0.00505754]
 [0.00754763 0.00251671 0.98993566]]
pi = [0.61599944 0.21228277 0.17171779]
Iter 10: LL=-1308002.75 | Rates: N=0.90956, AF=0.09657, OLD=0.09142, YOUNG=0.03742
A =
[[0.99540443 0.00206444 0.00253113]
 [0.0105136  0.98388139 0.00560501]
 [0.00758613 0.00253898 0.98987489]]
pi = [0.61570906 0.21055876 0.17373218]
Iter 11: LL=-1307984.92 | Rates: N=0.90956, AF=0.09655, OLD=0.09385, YOUNG=0.03778
A =
[[0.99540458 0.00199184 0.00260358]
 [0.01059605 0.98320485 0.0061991 ]
 [0.00762413 0.00256077 0.98981511]]
pi = [0.61541391 0.20902563 0.17556046]
Iter 12: LL=-1307966.77 | Rates: N=0.90955, AF=0.09653, OLD=0.09644, YOUNG=0.03814
A =
[[0.99540477 0.00192004 0.00267519]
 [0.01068216 0.98247535 0.00684249]
 [0.00766046 0.00258175 0.98975779]]
pi = [0.61511122 0.20762303 0.17726575]
Iter 13: LL=-1307948.31 | Rates: N=0.90955, AF=0.09650, OLD=0.09922, YOUNG=0.03849
A =
[[0.995405   0.00184925 0.00274574]
 [0.01077409 0.98168758 0.00753833]
 [0.00769446 0.0026018  0.98970374]]
pi = [0.6148002  0.20629332 0.17890648]
Iter 14: LL=-1307929.49 | Rates: N=0.90955, AF=0.09648, OLD=0.10219, YOUNG=0.03884
A =
[[0.99540528 0.00177961 0.00281512]
 [0.01087384 0.9808361  0.00829006]
 [0.00772572 0.00262088 0.98965339]]
pi = [0.61448078 0.20498808 0.18053114]
Iter 15: LL=-1307910.31 | Rates: N=0.90955, AF=0.09645, OLD=0.10539, YOUNG=0.03919
A =
[[0.99540559 0.00171121 0.0028832 ]
 [0.01098327 0.97991535 0.00910138]
 [0.00775408 0.00263899 0.98960692]]
pi = [0.61415296 0.20367203 0.18217501]
Final Global Rates (lambdas): [0.90954894 0.09645116 0.10538862 0.03919242]
Final transition matrix A:
[[0.99540559 0.00171121 0.0028832 ]
 [0.01098327 0.97991535 0.00910138]
 [0.00775408 0.00263899 0.98960692]]
Final initial distribution pi:
[0.61415296 0.20367203 0.18217501]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5845,0.1916,0.2886,30351170.0,21575830.0,128021460.0
Archaic_young,0.5706,0.8799,0.6923,171467159.0,129035841.0,23412781.0
Modern,0.0000,0.0000,0.0000,0.0,647570000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         640635          387           2536
Archaic_old      3629        30379         125519
Archaic_young    3306        21161         172448

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4839  0.6412  0.5516
Archaic_young     0.6320  0.4469  0.5236

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         635015          397           1075
Archaic_old      6470       100728          51266
Archaic_young    6671       107263          91115

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1589016.25 | Rates: N=0.90516, AF=0.09741, OLD=0.06977, YOUNG=0.05097
A =
[[0.99504314 0.00274736 0.00220951]
 [0.00923535 0.9879579  0.00280675]
 [0.00878592 0.00329988 0.9879142 ]]
pi = [0.6538098  0.19336384 0.15282636]
Iter 2: LL=-1314194.29 | Rates: N=0.90545, AF=0.09731, OLD=0.07386, YOUNG=0.04634
A =
[[0.99511453 0.00267153 0.00221394]
 [0.00940931 0.98765416 0.00293653]
 [0.00832763 0.00308689 0.98858548]]
pi = [0.65894704 0.192639   0.14841396]
Iter 3: LL=-1314073.10 | Rates: N=0.90545, AF=0.09728, OLD=0.07867, YOUNG=0.04324
A =
[[0.99512081 0.00262807 0.00225112]
 [0.00970582 0.98719916 0.00309502]
 [0.00807048 0.00291918 0.98901034]]
pi = [0.65924346 0.198075   0.14268155]
Iter 4: LL=-1313986.95 | Rates: N=0.90544, AF=0.09722, OLD=0.08273, YOUNG=0.04154
A =
[[0.99512195 0.00257408 0.00230397]
 [0.00996876 0.98670871 0.00332253]
 [0.00790682 0.00281971 0.98927347]]
pi = [0.65898327 0.2054715  0.13554523]
Iter 5: LL=-1313941.35 | Rates: N=0.90544, AF=0.09717, OLD=0.08591, YOUNG=0.04085
A =
[[0.99512209 0.00250998 0.00236792]
 [0.0101736  0.9862077  0.0036187 ]
 [0.00782183 0.002784   0.98939418]]
pi = [0.65860621 0.2128262  0.12856759]
Iter 6: LL=-1313915.71 | Rates: N=0.90544, AF=0.09712, OLD=0.08853, YOUNG=0.04073
A =
[[0.99512213 0.00243809 0.00243978]
 [0.0103343  0.98569182 0.00397388]
 [0.00778664 0.00278609 0.98942727]]
pi = [0.65824525 0.21897755 0.1227772 ]
Iter 7: LL=-1313896.35 | Rates: N=0.90544, AF=0.09709, OLD=0.09088, YOUNG=0.04088
A =
[[0.99512229 0.00236082 0.00251689]
 [0.01046761 0.98515389 0.0043785 ]
 [0.00778027 0.00280568 0.98941405]]
pi = [0.65795002 0.22359976 0.11845023]
Iter 8: LL=-1313878.46 | Rates: N=0.90543, AF=0.09706, OLD=0.09315, YOUNG=0.04117
A =
[[0.99512256 0.00228018 0.00259726]
 [0.01058427 0.98458933 0.0048264 ]
 [0.00779079 0.00283146 0.98937775]]
pi = [0.65772536 0.22679107 0.11548357]
Iter 9: LL=-1313860.72 | Rates: N=0.90543, AF=0.09703, OLD=0.09546, YOUNG=0.04151
A =
[[0.9951229  0.00219766 0.00267945]
 [0.01069024 0.98399514 0.00531462]
 [0.00781166 0.00285781 0.98933053]]
pi = [0.6575616  0.22878037 0.11365802]
Iter 10: LL=-1313842.84 | Rates: N=0.90543, AF=0.09700, OLD=0.09784, YOUNG=0.04187
A =
[[0.99512326 0.00211436 0.00276239]
 [0.01078887 0.98336896 0.00584217]
 [0.00783905 0.00288208 0.98927887]]
pi = [0.6574476  0.22980358 0.11274882]
Iter 11: LL=-1313824.80 | Rates: N=0.90543, AF=0.09698, OLD=0.10034, YOUNG=0.04224
A =
[[0.99512362 0.00203111 0.00284528]
 [0.01088227 0.98270855 0.00640919]
 [0.00787053 0.00290302 0.98922645]]
pi = [0.65737401 0.2300651  0.11256089]
Iter 12: LL=-1313806.63 | Rates: N=0.90543, AF=0.09695, OLD=0.10298, YOUNG=0.04262
A =
[[0.99512396 0.00194855 0.00292749]
 [0.01097197 0.98201162 0.00701641]
 [0.00790438 0.0029201  0.98917552]]
pi = [0.65733342 0.22972993 0.11293665]
Iter 13: LL=-1313788.36 | Rates: N=0.90542, AF=0.09692, OLD=0.10576, YOUNG=0.04299
A =
[[0.99512429 0.00186717 0.00300854]
 [0.01105938 0.98127571 0.00766491]
 [0.00793934 0.0029331  0.98912756]]
pi = [0.65731989 0.22892479 0.11375532]
Iter 14: LL=-1313770.03 | Rates: N=0.90542, AF=0.09690, OLD=0.10871, YOUNG=0.04336
A =
[[0.99512458 0.00178738 0.00308804]
 [0.01114594 0.980498   0.00835606]
 [0.00797443 0.002942   0.98908357]]
pi = [0.65732848 0.22774168 0.11492985]
Iter 15: LL=-1313751.68 | Rates: N=0.90542, AF=0.09687, OLD=0.11184, YOUNG=0.04373
A =
[[0.99512483 0.00170945 0.00316572]
 [0.0112332  0.97967527 0.00909152]
 [0.00800888 0.00294686 0.98904426]]
pi = [0.65735485 0.22624227 0.11640288]
Final Global Rates (lambdas): [0.90542058 0.09686581 0.11183668 0.04372989]
Final transition matrix A:
[[0.99512483 0.00170945 0.00316572]
 [0.0112332  0.97967527 0.00909152]
 [0.00800888 0.00294686 0.98904426]]
Final initial distribution pi:
[0.65735485 0.22624227 0.11640288]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5456,0.1745,0.2645,27450864.0,22866136.0,129821035.0
Archaic_young,0.5756,0.8750,0.6944,177526791.0,130881209.0,25354602.0
Modern,0.0000,0.0000,0.0000,0.0,641275000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         633553          281           2653
Archaic_old      3839        27467         127158
Archaic_young    3883        22569         178597

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4838  0.8445  0.6151
Archaic_young     0.6960  0.2747  0.3939

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         645518         2273            371
Archaic_old      2636       133009          22530
Archaic_young    1795       138902          52966

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1564788.13 | Rates: N=0.90424, AF=0.09634, OLD=0.05215, YOUNG=0.03023
A =
[[0.99623979 0.00253831 0.0012219 ]
 [0.00743178 0.99123331 0.00133491]
 [0.00659842 0.00249997 0.99090162]]
pi = [0.60192644 0.23189735 0.16617621]
Iter 2: LL=-1291756.95 | Rates: N=0.90447, AF=0.09616, OLD=0.05433, YOUNG=0.02841
A =
[[0.99625142 0.00248368 0.0012649 ]
 [0.00774046 0.99080817 0.00145138]
 [0.00609958 0.00232879 0.99157164]]
pi = [0.6006268  0.21433246 0.18504074]
Iter 3: LL=-1291716.59 | Rates: N=0.90447, AF=0.09613, OLD=0.05623, YOUNG=0.02765
A =
[[0.9962513  0.00243928 0.00130942]
 [0.00800166 0.99042906 0.00156928]
 [0.00584746 0.00226922 0.99188332]]
pi = [0.60060311 0.19630187 0.20309501]
Iter 4: LL=-1291696.77 | Rates: N=0.90447, AF=0.09611, OLD=0.05767, YOUNG=0.02744
A =
[[0.99625066 0.00239065 0.00135869]
 [0.00819844 0.99010057 0.00170099]
 [0.0057138  0.00226894 0.99201726]]
pi = [0.60061148 0.1777223  0.22166621]
Iter 5: LL=-1291685.22 | Rates: N=0.90447, AF=0.09610, OLD=0.05881, YOUNG=0.02750
A =
[[0.99625017 0.00233811 0.00141171]
 [0.00835002 0.98980416 0.00184581]
 [0.005647   0.0022982  0.9920548 ]]
pi = [0.60063059 0.15880608 0.24056333]
Iter 6: LL=-1291676.22 | Rates: N=0.90447, AF=0.09609, OLD=0.05981, YOUNG=0.02767
A =
[[0.99624988 0.00228288 0.00146724]
 [0.0084737  0.98952391 0.00200239]
 [0.00561767 0.00233969 0.99204264]]
pi = [0.60065765 0.13991534 0.25942701]
Iter 7: LL=-1291667.98 | Rates: N=0.90447, AF=0.09608, OLD=0.06074, YOUNG=0.02789
A =
[[0.99624973 0.00222605 0.00152422]
 [0.00858038 0.98924979 0.00216984]
 [0.00561015 0.00238473 0.99200513]]
pi = [0.60068961 0.12144694 0.27786346]
Iter 8: LL=-1291660.02 | Rates: N=0.90447, AF=0.09607, OLD=0.06166, YOUNG=0.02813
A =
[[0.99624966 0.00216844 0.0015819 ]
 [0.00867636 0.98897583 0.0023478 ]
 [0.00561598 0.00242917 0.99195485]]
pi = [0.60072371 0.10377045 0.29550584]
Iter 9: LL=-1291652.22 | Rates: N=0.90447, AF=0.09606, OLD=0.06258, YOUNG=0.02837
A =
[[0.99624965 0.00211061 0.00163974]
 [0.00876531 0.98869837 0.00253632]
 [0.00563039 0.00247112 0.99189849]]
pi = [0.60075755 0.08719905 0.3120434 ]
Iter 10: LL=-1291644.53 | Rates: N=0.90447, AF=0.09606, OLD=0.06351, YOUNG=0.02861
A =
[[0.99624968 0.00205295 0.00169737]
 [0.00884939 0.98841502 0.00273558]
 [0.00565055 0.00250971 0.99183974]]
pi = [0.60078896 0.07197692 0.32723412]
Iter 11: LL=-1291636.95 | Rates: N=0.90447, AF=0.09605, OLD=0.06447, YOUNG=0.02884
A =
[[0.99624972 0.00199576 0.00175451]
 [0.00892993 0.98812417 0.00294589]
 [0.00567466 0.00254462 0.99178072]]
pi = [0.60081601 0.05827706 0.34090693]
Iter 12: LL=-1291629.46 | Rates: N=0.90447, AF=0.09604, OLD=0.06545, YOUNG=0.02907
A =
[[0.99624978 0.00193926 0.00181095]
 [0.00900777 0.98782467 0.00316755]
 [0.00570156 0.00257575 0.99172269]]
pi = [0.60083713 0.04620496 0.35295791]
Iter 13: LL=-1291622.09 | Rates: N=0.90447, AF=0.09604, OLD=0.06646, YOUNG=0.02929
A =
[[0.99624985 0.00188361 0.00186654]
 [0.00908343 0.98751569 0.00340088]
 [0.00573044 0.00260316 0.99166639]]
pi = [0.60085119 0.03580427 0.36334454]
Iter 14: LL=-1291614.81 | Rates: N=0.90448, AF=0.09603, OLD=0.06749, YOUNG=0.02951
A =
[[0.99624993 0.00182894 0.00192114]
 [0.00915725 0.98719658 0.00364616]
 [0.00576072 0.00262699 0.99161229]]
pi = [0.60085764 0.02706135 0.37208102]
Iter 15: LL=-1291607.66 | Rates: N=0.90448, AF=0.09602, OLD=0.06856, YOUNG=0.02973
A =
[[0.99625    0.00177535 0.00197465]
 [0.00922946 0.98686684 0.0039037 ]
 [0.00579198 0.00264739 0.99156063]]
pi = [0.60085647 0.01990876 0.37923477]
Final Global Rates (lambdas): [0.90447523 0.0960231  0.06855955 0.02973036]
Final transition matrix A:
[[0.99625    0.00177535 0.00197465]
 [0.00922946 0.98686684 0.0039037 ]
 [0.00579198 0.00264739 0.99156063]]
Final initial distribution pi:
[0.60085647 0.01990876 0.37923477]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5679  0.3795  0.4550   59607594.0   45347406.0  97442115.0
Archaic_young     0.5998  0.7661  0.6729  147246288.0   98231712.0  44948306.0
Modern            0.0000  0.0000  0.0000          0.0  649567000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         645481         1095           1586
Archaic_old      2323        59821          96031
Archaic_young    1763        44039         147861

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4865  0.7809  0.5995
Archaic_young     0.7174  0.3968  0.5109

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         638445         2483            619
Archaic_old      3015       118804          30977
Archaic_young    2257       122195          81205

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 18
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1567561.11 | Rates: N=0.90715, AF=0.09502, OLD=0.05539, YOUNG=0.03345
A =
[[0.99585265 0.00263459 0.00151276]
 [0.00821188 0.99002086 0.00176726]
 [0.00685697 0.00255605 0.99058698]]
pi = [0.69764659 0.19134    0.11101341]
Iter 2: LL=-1292847.03 | Rates: N=0.90743, AF=0.09485, OLD=0.05806, YOUNG=0.03125
A =
[[0.99587123 0.00257246 0.00155631]
 [0.00859537 0.98948105 0.00192358]
 [0.00639697 0.00234315 0.99125988]]
pi = [0.6997497  0.20048998 0.09976032]
Iter 3: LL=-1292792.06 | Rates: N=0.90743, AF=0.09482, OLD=0.06063, YOUNG=0.03031
A =
[[0.99587125 0.00252411 0.00160464]
 [0.00892661 0.98898795 0.00208544]
 [0.00617677 0.00223668 0.99158655]]
pi = [0.69973148 0.20819538 0.09207314]
Iter 4: LL=-1292762.87 | Rates: N=0.90743, AF=0.09479, OLD=0.06268, YOUNG=0.03002
A =
[[0.99587026 0.00246728 0.00166247]
 [0.00919013 0.98853296 0.00227691]
 [0.00606702 0.00218626 0.99174672]]
pi = [0.69967391 0.21125809 0.08906801]
Iter 5: LL=-1292745.09 | Rates: N=0.90743, AF=0.09476, OLD=0.06439, YOUNG=0.03008
A =
[[0.99586935 0.00240333 0.00172731]
 [0.00940209 0.98810269 0.00249521]
 [0.00602355 0.002167   0.99180945]]
pi = [0.69963541 0.21008821 0.09027638]
Iter 6: LL=-1292731.00 | Rates: N=0.90743, AF=0.09475, OLD=0.06593, YOUNG=0.03029
A =
[[0.99586868 0.00233464 0.00179668]
 [0.00957954 0.98768411 0.00273635]
 [0.00601865 0.002163   0.99181835]]
pi = [0.69961288 0.20552327 0.09486385]
Iter 7: LL=-1292718.01 | Rates: N=0.90743, AF=0.09473, OLD=0.06741, YOUNG=0.03055
A =
[[0.99586821 0.00226312 0.00186866]
 [0.00973413 0.98726829 0.00299759]
 [0.00603641 0.00216588 0.99179771]]
pi = [0.69959774 0.19841817 0.10198409]
Iter 8: LL=-1292705.41 | Rates: N=0.90744, AF=0.09472, OLD=0.06889, YOUNG=0.03084
A =
[[0.99586789 0.0021902  0.00194192]
 [0.00987309 0.98684941 0.00327751]
 [0.00606771 0.0021715  0.99176078]]
pi = [0.69958378 0.18961838 0.11079784]
Iter 9: LL=-1292693.03 | Rates: N=0.90744, AF=0.09471, OLD=0.07039, YOUNG=0.03113
A =
[[0.99586767 0.00211683 0.0020155 ]
 [0.01000097 0.98642349 0.00357553]
 [0.00610712 0.00217786 0.99171502]]
pi = [0.69956825 0.17995336 0.12047839]
Iter 10: LL=-1292680.83 | Rates: N=0.90744, AF=0.09470, OLD=0.07194, YOUNG=0.03141
A =
[[0.99586752 0.00204374 0.00208874]
 [0.01012082 0.98598761 0.00389156]
 [0.0061512  0.00218397 0.99166483]]
pi = [0.69955075 0.17017286 0.1302764 ]
Iter 11: LL=-1292668.83 | Rates: N=0.90744, AF=0.09469, OLD=0.07353, YOUNG=0.03169
A =
[[0.99586742 0.00197144 0.00216114]
 [0.01023479 0.98553945 0.00422576]
 [0.00619774 0.00218935 0.99161291]]
pi = [0.69953175 0.1608636  0.13960465]
Iter 12: LL=-1292657.06 | Rates: N=0.90744, AF=0.09468, OLD=0.07518, YOUNG=0.03196
A =
[[0.99586736 0.00190032 0.00223232]
 [0.01034452 0.98507707 0.00457841]
 [0.00624522 0.00219374 0.99156103]]
pi = [0.69951159 0.15240147 0.14808694]
Iter 13: LL=-1292645.53 | Rates: N=0.90744, AF=0.09467, OLD=0.07689, YOUNG=0.03222
A =
[[0.99586733 0.0018307  0.00230197]
 [0.01045137 0.98459874 0.00494988]
 [0.00629261 0.00219706 0.99151033]]
pi = [0.69949002 0.1449596  0.15555038]
Iter 14: LL=-1292634.24 | Rates: N=0.90743, AF=0.09466, OLD=0.07866, YOUNG=0.03248
A =
[[0.99586731 0.0017628  0.00236989]
 [0.01055653 0.98410292 0.00534055]
 [0.00633917 0.00219926 0.99146157]]
pi = [0.69946624 0.13855589 0.16197788]
Iter 15: LL=-1292623.22 | Rates: N=0.90743, AF=0.09465, OLD=0.08049, YOUNG=0.03274
A =
[[0.9958673  0.0016968  0.0024359 ]
 [0.01066107 0.98358812 0.0057508 ]
 [0.00638437 0.00220036 0.99141527]]
pi = [0.69943903 0.1331115  0.16744947]
Final Global Rates (lambdas): [0.90743485 0.09464949 0.08048799 0.03273924]
Final transition matrix A:
[[0.9958673  0.0016968  0.0024359 ]
 [0.01066107 0.98358812 0.0057508 ]
 [0.00638437 0.00220036 0.99141527]]
Final initial distribution pi:
[0.69943903 0.1331115  0.16744947]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.6317,0.2655,0.3739,40271193.0,23474807.0,111397792.0
Archaic_young,0.6151,0.8839,0.7254,180280161.0,112830839.0,23677721.0
Modern,0.0000,0.0000,0.0000,0.0,643143000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         638422          825           2300
Archaic_old      2685        40438         109673
Archaic_young    2036        22483         181138

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5109  0.7547  0.6093
Archaic_young     0.7378  0.4839  0.5845

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         620347         2512            800
Archaic_old      3366       118911          35979
Archaic_young    2500       110576         105009

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1567243.76 | Rates: N=0.89875, AF=0.09684, OLD=0.06137, YOUNG=0.03685
A =
[[0.99527484 0.00289798 0.00182718]
 [0.00875768 0.98911359 0.00212872]
 [0.00728065 0.00273302 0.98998633]]
pi = [0.55696355 0.25211707 0.19091939]
Iter 2: LL=-1299123.55 | Rates: N=0.89904, AF=0.09673, OLD=0.06549, YOUNG=0.03349
A =
[[0.99530921 0.00281633 0.00187446]
 [0.0091701  0.98849663 0.00233327]
 [0.00681448 0.00244625 0.99073927]]
pi = [0.55414281 0.24634819 0.199509  ]
Iter 3: LL=-1299015.18 | Rates: N=0.89904, AF=0.09669, OLD=0.06924, YOUNG=0.03202
A =
[[0.99531051 0.00275724 0.00193225]
 [0.00949258 0.9879523  0.00255512]
 [0.00664223 0.00230783 0.99104994]]
pi = [0.55400876 0.23779917 0.20819207]
Iter 4: LL=-1298965.17 | Rates: N=0.89903, AF=0.09665, OLD=0.07205, YOUNG=0.03157
A =
[[0.99531003 0.00268765 0.00200232]
 [0.00971382 0.98745948 0.00282671]
 [0.00658935 0.00225348 0.99115717]]
pi = [0.55398442 0.22574528 0.2202703 ]
Iter 5: LL=-1298939.06 | Rates: N=0.89903, AF=0.09662, OLD=0.07429, YOUNG=0.03162
A =
[[0.99530976 0.00260991 0.00208033]
 [0.00987381 0.98698838 0.00313782]
 [0.00659354 0.00224264 0.99116383]]
pi = [0.5539962  0.21103398 0.23496982]
Iter 6: LL=-1298919.49 | Rates: N=0.89903, AF=0.09660, OLD=0.07628, YOUNG=0.03187
A =
[[0.9953098  0.00252736 0.00216284]
 [0.0100027  0.9865198  0.0034775 ]
 [0.00662255 0.00225121 0.99112624]]
pi = [0.55403433 0.19485089 0.25111478]
Iter 7: LL=-1298901.70 | Rates: N=0.89903, AF=0.09658, OLD=0.07819, YOUNG=0.03219
A =
[[0.99531008 0.00244231 0.00224761]
 [0.01011623 0.98604523 0.00383854]
 [0.00666176 0.0022677  0.99107054]]
pi = [0.55408731 0.17819742 0.26771528]
Iter 8: LL=-1298884.67 | Rates: N=0.89903, AF=0.09656, OLD=0.08010, YOUNG=0.03255
A =
[[0.99531051 0.00235627 0.00233322]
 [0.01022183 0.98556155 0.00421662]
 [0.00670468 0.00228692 0.9910084 ]]
pi = [0.55414684 0.16178335 0.28406982]
Iter 9: LL=-1298868.21 | Rates: N=0.89903, AF=0.09654, OLD=0.08204, YOUNG=0.03290
A =
[[0.99531104 0.0022702  0.00241875]
 [0.01032297 0.98506798 0.00460905]
 [0.00674837 0.00230648 0.99094515]]
pi = [0.55420778 0.14605819 0.29973403]
Iter 10: LL=-1298852.34 | Rates: N=0.89903, AF=0.09653, OLD=0.08404, YOUNG=0.03325
A =
[[0.99531164 0.00218484 0.00250352]
 [0.01042118 0.98456492 0.00501391]
 [0.00679151 0.00232521 0.99088328]]
pi = [0.55426718 0.13127675 0.31445608]
Iter 11: LL=-1298837.09 | Rates: N=0.89902, AF=0.09651, OLD=0.08608, YOUNG=0.03359
A =
[[0.99531228 0.00210075 0.00258697]
 [0.010517   0.98405351 0.00542949]
 [0.00683352 0.00234251 0.99082397]]
pi = [0.55432343 0.11756397 0.3281126 ]
Iter 12: LL=-1298822.51 | Rates: N=0.89902, AF=0.09649, OLD=0.08816, YOUNG=0.03391
A =
[[0.99531292 0.00201845 0.00266863]
 [0.0106104  0.98353545 0.00585415]
 [0.00687415 0.0023581  0.99076775]]
pi = [0.55437579 0.10496531 0.3406589 ]
Iter 13: LL=-1298808.66 | Rates: N=0.89902, AF=0.09648, OLD=0.09028, YOUNG=0.03423
A =
[[0.99531355 0.00193836 0.00274809]
 [0.01070106 0.98301269 0.00628625]
 [0.00691331 0.00237187 0.99071481]]
pi = [0.55442395 0.09347938 0.35209667]
Iter 14: LL=-1298795.59 | Rates: N=0.89902, AF=0.09646, OLD=0.09242, YOUNG=0.03453
A =
[[0.99531416 0.00186085 0.002825  ]
 [0.01078861 0.98248725 0.00672414]
 [0.00695095 0.00238385 0.9906652 ]]
pi = [0.5544678 0.0830765 0.3624557]
Iter 15: LL=-1298783.33 | Rates: N=0.89902, AF=0.09645, OLD=0.09458, YOUNG=0.03482
A =
[[0.99531473 0.00178621 0.00289905]
 [0.01087278 0.98196086 0.00716637]
 [0.00698701 0.00239413 0.99061886]]
pi = [0.55450734 0.07370841 0.37178424]
Final Global Rates (lambdas): [0.89901868 0.09644597 0.09458249 0.03482446]
Final transition matrix A:
[[0.99531473 0.00178621 0.00289905]
 [0.01087278 0.98196086 0.00716637]
 [0.00698701 0.00239413 0.99061886]]
Final initial distribution pi:
[0.55450734 0.07370841 0.37178424]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.6368,0.2504,0.3595,39331652.0,22432348.0,117735456.0
Archaic_young,0.6195,0.8877,0.7297,191899074.0,117884926.0,24267709.0
Modern,0.0000,0.0000,0.0000,0.0,628452000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         621021          198           2440
Archaic_old      4428        39339         114489
Archaic_young    3003        22227         192855

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5221  0.7527  0.6165
Archaic_young     0.7061  0.4193  0.5261

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         641690          439            870
Archaic_old      7938       119377          32771
Archaic_young    5839       109005          82071

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1584191.02 | Rates: N=0.90697, AF=0.09558, OLD=0.06816, YOUNG=0.04362
A =
[[0.99512949 0.00294688 0.00192363]
 [0.0095715  0.98811262 0.00231588]
 [0.00855317 0.00320395 0.98824287]]
pi = [0.74499008 0.15202624 0.10298369]
Iter 2: LL=-1308766.79 | Rates: N=0.90730, AF=0.09543, OLD=0.07177, YOUNG=0.03981
A =
[[0.99518088 0.0028518  0.00196732]
 [0.009855   0.9876937  0.00245129]
 [0.00804186 0.00297747 0.98898067]]
pi = [0.75036137 0.15249821 0.09714042]
Iter 3: LL=-1308676.74 | Rates: N=0.90730, AF=0.09539, OLD=0.07532, YOUNG=0.03780
A =
[[0.99518278 0.00279055 0.00202667]
 [0.01013539 0.98727415 0.00259046]
 [0.00782195 0.00287709 0.98930096]]
pi = [0.75039102 0.1567404  0.09286858]
Iter 4: LL=-1308631.00 | Rates: N=0.90730, AF=0.09535, OLD=0.07799, YOUNG=0.03691
A =
[[0.99518138 0.00272345 0.00209517]
 [0.01034411 0.98688472 0.00277118]
 [0.0077138  0.00285567 0.98943053]]
pi = [0.75015515 0.16029663 0.08954822]
Iter 5: LL=-1308608.70 | Rates: N=0.90730, AF=0.09531, OLD=0.08003, YOUNG=0.03666
A =
[[0.99518015 0.00265112 0.00216873]
 [0.01050023 0.98650989 0.00298988]
 [0.00766742 0.00288027 0.98945231]]
pi = [0.74992381 0.16283515 0.08724104]
Iter 6: LL=-1308594.29 | Rates: N=0.90730, AF=0.09529, OLD=0.08173, YOUNG=0.03672
A =
[[0.99517939 0.00257583 0.00224479]
 [0.01062759 0.98613302 0.00323939]
 [0.00765241 0.00292583 0.98942176]]
pi = [0.74972426 0.16450144 0.0857743 ]
Iter 7: LL=-1308582.01 | Rates: N=0.90730, AF=0.09527, OLD=0.08327, YOUNG=0.03693
A =
[[0.99517894 0.00249932 0.00232174]
 [0.01074099 0.98574461 0.0035144 ]
 [0.00765326 0.00297854 0.9893682 ]]
pi = [0.74955189 0.16555101 0.08489711]
Iter 8: LL=-1308570.28 | Rates: N=0.90730, AF=0.09525, OLD=0.08477, YOUNG=0.03721
A =
[[0.99517866 0.00242272 0.00239862]
 [0.01084824 0.98533963 0.00381213]
 [0.00766252 0.00303173 0.98930575]]
pi = [0.74939669 0.16621389 0.08438941]
Iter 9: LL=-1308558.72 | Rates: N=0.90730, AF=0.09524, OLD=0.08627, YOUNG=0.03752
A =
[[0.99517847 0.00234671 0.00247482]
 [0.01095336 0.9849151  0.00413154]
 [0.00767657 0.00308235 0.98924108]]
pi = [0.74925033 0.16666027 0.0840894 ]
Iter 10: LL=-1308547.24 | Rates: N=0.90730, AF=0.09523, OLD=0.08781, YOUNG=0.03783
A =
[[0.99517832 0.00227169 0.00254999]
 [0.0110585  0.98446883 0.00447267]
 [0.00769351 0.00312911 0.98917737]]
pi = [0.74910707 0.16700517 0.08388777]
Iter 11: LL=-1308535.82 | Rates: N=0.90730, AF=0.09522, OLD=0.08940, YOUNG=0.03815
A =
[[0.99517819 0.00219793 0.00262388]
 [0.01116494 0.98399889 0.00483617]
 [0.00771232 0.00317151 0.98911617]]
pi = [0.74896312 0.16732208 0.08371479]
Iter 12: LL=-1308524.43 | Rates: N=0.90730, AF=0.09520, OLD=0.09105, YOUNG=0.03847
A =
[[0.99517807 0.00212562 0.00269631]
 [0.01127352 0.98350345 0.00522303]
 [0.00773235 0.00320941 0.98905824]]
pi = [0.74881602 0.16765535 0.08352862]
Iter 13: LL=-1308513.07 | Rates: N=0.90730, AF=0.09519, OLD=0.09277, YOUNG=0.03879
A =
[[0.99517794 0.00205488 0.00276718]
 [0.01138485 0.98298065 0.0056345 ]
 [0.0077532  0.00324283 0.98900397]]
pi = [0.7486641  0.16802945 0.08330645]
Iter 14: LL=-1308501.73 | Rates: N=0.90730, AF=0.09518, OLD=0.09456, YOUNG=0.03911
A =
[[0.99517781 0.00198581 0.00283638]
 [0.01149938 0.98242866 0.00607196]
 [0.00777462 0.00327189 0.98895349]]
pi = [0.74850615 0.1684555  0.08303835]
Iter 15: LL=-1308490.41 | Rates: N=0.90730, AF=0.09517, OLD=0.09643, YOUNG=0.03942
A =
[[0.99517767 0.00191849 0.00290384]
 [0.01161743 0.98184565 0.00653692]
 [0.00779645 0.00329671 0.98890684]]
pi = [0.74834129 0.16893569 0.08272302]
Final Global Rates (lambdas): [0.90730172 0.09516668 0.09643005 0.03942029]
Final transition matrix A:
[[0.99517767 0.00191849 0.00290384]
 [0.01161743 0.98184565 0.00653692]
 [0.00779645 0.00329671 0.98890684]]
Final initial distribution pi:
[0.74834129 0.16893569 0.08272302]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.6473,0.2985,0.4086,47367621.0,25805379.0,111338267.0
Archaic_young,0.6011,0.8563,0.7063,166875951.0,110753049.0,28003989.0
Modern,0.0000,0.0000,0.0000,0.0,649198000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         640359          242           2398
Archaic_old      5297        47371         107418
Archaic_young    3542        25560         167813

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5147  0.8753  0.6482
Archaic_young     0.7584  0.3046  0.4346

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         636983         2659            433
Archaic_old      3367       144848          18047
Archaic_young    1949       133005          58709

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1569209.31 | Rates: N=0.90655, AF=0.09583, OLD=0.05609, YOUNG=0.02892
A =
[[0.99584814 0.00295196 0.0011999 ]
 [0.0081203  0.99059474 0.00128496]
 [0.0066306  0.00261296 0.99075644]]
pi = [0.70264594 0.20563552 0.09171855]
Iter 2: LL=-1294471.75 | Rates: N=0.90683, AF=0.09565, OLD=0.05818, YOUNG=0.02745
A =
[[0.99585588 0.00288042 0.00126371]
 [0.00846027 0.9901061  0.00143362]
 [0.00614192 0.00244915 0.99140893]]
pi = [0.70633839 0.21766606 0.07599554]
Iter 3: LL=-1294435.62 | Rates: N=0.90683, AF=0.09562, OLD=0.05997, YOUNG=0.02703
A =
[[0.99585536 0.00282204 0.0013226 ]
 [0.00869701 0.98972472 0.00157827]
 [0.00594773 0.0024348  0.99161747]]
pi = [0.70665042 0.22919283 0.06415676]
Iter 4: LL=-1294417.77 | Rates: N=0.90683, AF=0.09560, OLD=0.06133, YOUNG=0.02703
A =
[[0.99585483 0.0027591  0.00138607]
 [0.00886781 0.98939466 0.00173752]
 [0.00586218 0.00247801 0.9916598 ]]
pi = [0.70677469 0.23729228 0.05593303]
Iter 5: LL=-1294405.10 | Rates: N=0.90683, AF=0.09559, OLD=0.06247, YOUNG=0.02722
A =
[[0.99585456 0.00269249 0.00145295]
 [0.00900139 0.98908826 0.00191035]
 [0.00583023 0.00254588 0.99162389]]
pi = [0.70689988 0.24270688 0.05039324]
Iter 6: LL=-1294393.82 | Rates: N=0.90683, AF=0.09558, OLD=0.06352, YOUNG=0.02746
A =
[[0.99585448 0.00262359 0.00152193]
 [0.00911458 0.98878973 0.00209569]
 [0.00582583 0.0026228  0.99155136]]
pi = [0.7070319  0.24617121 0.04679689]
Iter 7: LL=-1294382.98 | Rates: N=0.90683, AF=0.09557, OLD=0.06455, YOUNG=0.02773
A =
[[0.99585453 0.00255344 0.00159203]
 [0.00921644 0.98849035 0.0022932 ]
 [0.00583644 0.00270159 0.99146197]]
pi = [0.70716771 0.24817658 0.04465572]
Iter 8: LL=-1294372.36 | Rates: N=0.90683, AF=0.09556, OLD=0.06557, YOUNG=0.02800
A =
[[0.99585466 0.00248279 0.00166255]
 [0.00931182 0.98818509 0.00250309]
 [0.00585569 0.0027789  0.99136541]]
pi = [0.70730476 0.24903192 0.04366332]
Iter 9: LL=-1294361.91 | Rates: N=0.90683, AF=0.09555, OLD=0.06662, YOUNG=0.02826
A =
[[0.99585485 0.00241217 0.00173299]
 [0.0094034  0.98787081 0.00272578]
 [0.00588017 0.0028531  0.99126672]]
pi = [0.70744057 0.24892979 0.04362965]
Iter 10: LL=-1294351.60 | Rates: N=0.90683, AF=0.09554, OLD=0.06769, YOUNG=0.02852
A =
[[0.99585507 0.00234195 0.00180298]
 [0.00949275 0.9875454  0.00296185]
 [0.00590794 0.00292338 0.99116867]]
pi = [0.70757223 0.24799065 0.04443711]
Iter 11: LL=-1294341.43 | Rates: N=0.90683, AF=0.09554, OLD=0.06879, YOUNG=0.02878
A =
[[0.99585531 0.00227245 0.00187223]
 [0.00958079 0.98720737 0.00321184]
 [0.00593784 0.00298932 0.99107285]]
pi = [0.70769646 0.24629156 0.04601198]
Iter 12: LL=-1294331.41 | Rates: N=0.90683, AF=0.09553, OLD=0.06992, YOUNG=0.02903
A =
[[0.99585558 0.0022039  0.00194052]
 [0.00966808 0.98685562 0.00347631]
 [0.00596913 0.00305069 0.99098019]]
pi = [0.70780968 0.24388574 0.04830458]
Iter 13: LL=-1294321.52 | Rates: N=0.90683, AF=0.09552, OLD=0.07108, YOUNG=0.02928
A =
[[0.99585586 0.00213649 0.00200765]
 [0.00975495 0.98648932 0.00375574]
 [0.00600133 0.00310741 0.99089126]]
pi = [0.70790838 0.24081713 0.05127449]
Iter 14: LL=-1294311.78 | Rates: N=0.90683, AF=0.09552, OLD=0.07228, YOUNG=0.02952
A =
[[0.99585615 0.00207037 0.00207348]
 [0.00984159 0.98610785 0.00405056]
 [0.0060341  0.00315951 0.99080639]]
pi = [0.70798942 0.23713158 0.054879  ]
Iter 15: LL=-1294302.20 | Rates: N=0.90683, AF=0.09551, OLD=0.07351, YOUNG=0.02976
A =
[[0.99585645 0.00200567 0.00213789]
 [0.00992813 0.98571075 0.00436113]
 [0.00606721 0.00320703 0.99072576]]
pi = [0.70805045 0.23288496 0.05906459]
Final Global Rates (lambdas): [0.90682922 0.09551075 0.07351276 0.0297625 ]
Final transition matrix A:
[[0.99585645 0.00200567 0.00213789]
 [0.00992813 0.98571075 0.00436113]
 [0.00606721 0.00320703 0.99072576]]
Final initial distribution pi:
[0.70805045 0.23288496 0.05906459]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.6180  0.4249  0.5036   70080463.0   43310537.0  94848127.0
Archaic_young     0.6109  0.7778  0.6843  149485429.0   95208571.0  42709165.0
Modern            0.0000  0.0000  0.0000          0.0  641915000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         636957         1282           1836
Archaic_old      3138        70359          92765
Archaic_young    1820        41750         150093

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5126  0.8373  0.6359
Archaic_young     0.7784  0.4059  0.5335

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         635295         2493            631
Archaic_old      3340       129928          22656
Archaic_young    2236       120363          83058

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1566525.30 | Rates: N=0.90217, AF=0.09541, OLD=0.05978, YOUNG=0.03260
A =
[[0.99571986 0.00287509 0.00140505]
 [0.00851539 0.989801   0.00168361]
 [0.00663957 0.00268603 0.9906744 ]]
pi = [0.74695156 0.16073845 0.09230998]
Iter 2: LL=-1295877.68 | Rates: N=0.90244, AF=0.09531, OLD=0.06219, YOUNG=0.03079
A =
[[0.99576081 0.00278351 0.00145568]
 [0.00882641 0.98931954 0.00185405]
 [0.00619713 0.00248137 0.99132151]]
pi = [0.75087929 0.15978613 0.08933458]
Iter 3: LL=-1295836.40 | Rates: N=0.90244, AF=0.09528, OLD=0.06428, YOUNG=0.03020
A =
[[0.99576122 0.00272936 0.00150941]
 [0.00905913 0.98892719 0.00201368]
 [0.00606264 0.00241791 0.99151946]]
pi = [0.75091334 0.15935198 0.08973468]
Iter 4: LL=-1295817.61 | Rates: N=0.90244, AF=0.09525, OLD=0.06585, YOUNG=0.03012
A =
[[0.99575994 0.00267117 0.00156889]
 [0.00921999 0.98858865 0.00219136]
 [0.00602245 0.00240726 0.99157029]]
pi = [0.75087512 0.15749909 0.09162579]
Iter 5: LL=-1295805.60 | Rates: N=0.90244, AF=0.09523, OLD=0.06713, YOUNG=0.03026
A =
[[0.99575903 0.00260902 0.00163195]
 [0.00933873 0.98827724 0.00238403]
 [0.00602631 0.00242087 0.99155282]]
pi = [0.75085053 0.15514663 0.09400285]
Iter 6: LL=-1295795.46 | Rates: N=0.90245, AF=0.09521, OLD=0.06829, YOUNG=0.03049
A =
[[0.99575846 0.00254454 0.00169699]
 [0.00943475 0.9879766  0.00258865]
 [0.00605093 0.00244485 0.99150421]]
pi = [0.75083262 0.15276832 0.09639907]
Iter 7: LL=-1295785.93 | Rates: N=0.90245, AF=0.09520, OLD=0.06940, YOUNG=0.03076
A =
[[0.9957581  0.00247891 0.00176299]
 [0.00951873 0.98767772 0.00280355]
 [0.00608511 0.00247278 0.99144211]]
pi = [0.75081647 0.150534   0.09864953]
Iter 8: LL=-1295776.71 | Rates: N=0.90245, AF=0.09519, OLD=0.07049, YOUNG=0.03104
A =
[[0.99575784 0.00241288 0.00182928]
 [0.00959654 0.98737542 0.00302804]
 [0.0061233  0.00250172 0.99137498]]
pi = [0.75080005 0.14847672 0.10072323]
Iter 9: LL=-1295767.71 | Rates: N=0.90245, AF=0.09518, OLD=0.07160, YOUNG=0.03132
A =
[[0.99575765 0.00234692 0.00189543]
 [0.00967151 0.98706651 0.00326198]
 [0.00616268 0.00253028 0.99130704]]
pi = [0.75078279 0.14657886 0.10263835]
Iter 10: LL=-1295758.90 | Rates: N=0.90245, AF=0.09517, OLD=0.07274, YOUNG=0.03159
A =
[[0.9957575  0.00228134 0.00196116]
 [0.00974571 0.98674877 0.00350552]
 [0.00620173 0.0025578  0.99124047]]
pi = [0.75076466 0.14480961 0.10442573]
Iter 11: LL=-1295750.25 | Rates: N=0.90245, AF=0.09516, OLD=0.07390, YOUNG=0.03186
A =
[[0.99575737 0.00221638 0.00202626]
 [0.00982048 0.98642054 0.00375899]
 [0.00623967 0.00258391 0.99117642]]
pi = [0.75074584 0.14313921 0.10611495]
Iter 12: LL=-1295741.77 | Rates: N=0.90245, AF=0.09515, OLD=0.07509, YOUNG=0.03213
A =
[[0.99575725 0.00215218 0.00209057]
 [0.00989674 0.98608049 0.00402277]
 [0.0062761  0.00260841 0.99111549]]
pi = [0.75072651 0.1415435  0.10772998]
Iter 13: LL=-1295733.42 | Rates: N=0.90245, AF=0.09514, OLD=0.07632, YOUNG=0.03239
A =
[[0.99575714 0.00208888 0.00215398]
 [0.00997515 0.98572751 0.00429734]
 [0.00631087 0.00263118 0.99105795]]
pi = [0.75070684 0.14000452 0.10928863]
Iter 14: LL=-1295725.20 | Rates: N=0.90245, AF=0.09513, OLD=0.07759, YOUNG=0.03265
A =
[[0.99575703 0.00202658 0.00221639]
 [0.01005615 0.98536065 0.0045832 ]
 [0.00634395 0.00265212 0.99100393]]
pi = [0.75068694 0.13850981 0.11080325]
Iter 15: LL=-1295717.10 | Rates: N=0.90245, AF=0.09512, OLD=0.07891, YOUNG=0.03291
A =
[[0.99575693 0.00196535 0.00227772]
 [0.01014008 0.98497903 0.0048809 ]
 [0.0063754  0.0026712  0.9909534 ]]
pi = [0.75066687 0.13705132 0.11228181]
Final Global Rates (lambdas): [0.90244846 0.09512079 0.07890607 0.03290518]
Final transition matrix A:
[[0.99575693 0.00196535 0.00227772]
 [0.01014008 0.98497903 0.0048809 ]
 [0.0063754  0.0026712  0.9909534 ]]
Final initial distribution pi:
[0.75066687 0.13705132 0.11228181]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.6541  0.3920  0.4902   60654442.0   32069558.0  94086119.0
Archaic_young     0.6446  0.8422  0.7303  171779631.0   94702369.0  32178251.0
Modern            0.0000  0.0000  0.0000          0.0  640794000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         635334         1022           2063
Archaic_old      3230        60857          91837
Archaic_young    2230        30845         172582

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5151  0.7685  0.6168
Archaic_young     0.7814  0.4843  0.5980

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         630674          306            735
Archaic_old      7617       114405          28178
Archaic_young    5385       107618         105082

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1572999.87 | Rates: N=0.90109, AF=0.09740, OLD=0.06465, YOUNG=0.03556
A =
[[0.99532494 0.00300979 0.00166527]
 [0.00930973 0.98859071 0.00209956]
 [0.0069601  0.00276929 0.99027061]]
pi = [0.79734084 0.11918737 0.08347179]
Iter 2: LL=-1302540.05 | Rates: N=0.90136, AF=0.09742, OLD=0.06809, YOUNG=0.03288
A =
[[0.99538501 0.0029072  0.00170779]
 [0.00971466 0.98795969 0.00232565]
 [0.00648699 0.00250865 0.99100436]]
pi = [0.80225513 0.11482466 0.08292021]
Iter 3: LL=-1302467.65 | Rates: N=0.90136, AF=0.09737, OLD=0.07107, YOUNG=0.03190
A =
[[0.99538644 0.0028559  0.00175766]
 [0.00999113 0.98746856 0.0025403 ]
 [0.00636817 0.00242976 0.99120207]]
pi = [0.80235608 0.11249366 0.08515026]
Iter 4: LL=-1302437.73 | Rates: N=0.90136, AF=0.09733, OLD=0.07324, YOUNG=0.03166
A =
[[0.99538535 0.00279811 0.00181654]
 [0.01017479 0.98703343 0.00279179]
 [0.00634675 0.00241972 0.99123353]]
pi = [0.80235338 0.1090969  0.08854972]
Iter 5: LL=-1302420.73 | Rates: N=0.90136, AF=0.09730, OLD=0.07498, YOUNG=0.03175
A =
[[0.9953847  0.00273492 0.00188038]
 [0.01031027 0.98661655 0.00307318]
 [0.0063662  0.00244106 0.99119275]]
pi = [0.80235933 0.10524386 0.09239681]
Iter 6: LL=-1302407.01 | Rates: N=0.90136, AF=0.09727, OLD=0.07654, YOUNG=0.03198
A =
[[0.99538442 0.00266906 0.00194653]
 [0.01042294 0.98619932 0.00337774]
 [0.00640248 0.00247568 0.99112184]]
pi = [0.80237058 0.10131662 0.09631281]
Iter 7: LL=-1302394.23 | Rates: N=0.90136, AF=0.09726, OLD=0.07802, YOUNG=0.03226
A =
[[0.99538433 0.00260219 0.00201348]
 [0.0105251  0.985773   0.0037019 ]
 [0.00644521 0.00251544 0.99103935]]
pi = [0.80238401 0.09747771 0.10013829]
Iter 8: LL=-1302381.89 | Rates: N=0.90136, AF=0.09724, OLD=0.07951, YOUNG=0.03256
A =
[[0.99538436 0.00253524 0.0020804 ]
 [0.01062261 0.98533312 0.00404427]
 [0.00648986 0.00255676 0.99095338]]
pi = [0.80239806 0.0937794  0.10382254]
Iter 9: LL=-1302369.85 | Rates: N=0.90136, AF=0.09722, OLD=0.08101, YOUNG=0.03286
A =
[[0.99538444 0.00246874 0.00214682]
 [0.01071844 0.98487697 0.00440459]
 [0.00653441 0.002598   0.99086759]]
pi = [0.80241203 0.09022635 0.10736163]
Iter 10: LL=-1302358.07 | Rates: N=0.90136, AF=0.09721, OLD=0.08255, YOUNG=0.03316
A =
[[0.99538456 0.00240296 0.00221248]
 [0.01081419 0.9844026  0.0047832 ]
 [0.00657793 0.0026384  0.99078367]]
pi = [0.80242564 0.08680481 0.11076955]
Iter 11: LL=-1302346.51 | Rates: N=0.90136, AF=0.09719, OLD=0.08414, YOUNG=0.03345
A =
[[0.9953847  0.0023381  0.0022772 ]
 [0.01091084 0.98390851 0.00518065]
 [0.00662002 0.00267752 0.99070245]]
pi = [0.80243885 0.08349502 0.11406613]
Iter 12: LL=-1302335.16 | Rates: N=0.90136, AF=0.09718, OLD=0.08578, YOUNG=0.03373
A =
[[0.99538485 0.00227425 0.0023409 ]
 [0.01100893 0.98339353 0.00559753]
 [0.00666056 0.00271513 0.99062431]]
pi = [0.8024517  0.08027592 0.11727239]
Iter 13: LL=-1302323.99 | Rates: N=0.90136, AF=0.09716, OLD=0.08747, YOUNG=0.03401
A =
[[0.99538502 0.00221149 0.0024035 ]
 [0.01110876 0.98285686 0.00603438]
 [0.00669956 0.00275104 0.9905494 ]]
pi = [0.80246428 0.07712673 0.12040899]
Iter 14: LL=-1302313.00 | Rates: N=0.90136, AF=0.09714, OLD=0.08922, YOUNG=0.03428
A =
[[0.99538519 0.00214984 0.00246497]
 [0.0112104  0.98229799 0.00649161]
 [0.0067371  0.00278516 0.99047774]]
pi = [0.80247672 0.07402747 0.12349581]
Iter 15: LL=-1302302.18 | Rates: N=0.90136, AF=0.09713, OLD=0.09103, YOUNG=0.03455
A =
[[0.99538536 0.00208934 0.00252529]
 [0.01131376 0.98171675 0.0069695 ]
 [0.00677331 0.0028174  0.99040929]]
pi = [0.80248915 0.0709591  0.12655174]
Final Global Rates (lambdas): [0.90135703 0.09712817 0.09103185 0.0345504 ]
Final transition matrix A:
[[0.99538536 0.00208934 0.00252529]
 [0.01131376 0.98171675 0.0069695 ]
 [0.00677331 0.0028174  0.99040929]]
Final initial distribution pi:
[0.80248915 0.0709591  0.12655174]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.2_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.6485,0.3183,0.4270,47434068.0,25709932.0,101589802.0
Archaic_young,0.6524,0.8716,0.7462,188415995.0,100399005.0,27750788.0
Modern,0.0000,0.0000,0.0000,0.0,638041000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         629403          235           2077
Archaic_old      5361        47429          97410
Archaic_young    3277        25480         189328

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3231  0.2384  0.2744
Archaic_young     0.6809  0.7650  0.7205

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         559976          426           2078
Archaic_old      1515        32738         103653
Archaic_young    2709        68229         228676

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1510419.72 | Rates: N=0.86722, AF=0.09577, OLD=0.04695, YOUNG=0.03550
A =
[[0.9957633  0.0018182  0.00241849]
 [0.00544378 0.99218787 0.00236834]
 [0.00573537 0.00185789 0.99240674]]
pi = [0.40854272 0.27508733 0.31636995]
Iter 2: LL=-1269463.81 | Rates: N=0.86743, AF=0.09542, OLD=0.05083, YOUNG=0.03283
A =
[[0.99576013 0.00180612 0.00243374]
 [0.0054786  0.99212231 0.0023991 ]
 [0.00568221 0.00179773 0.99252006]]
pi = [0.40390731 0.2773963  0.31869639]
Iter 3: LL=-1269357.01 | Rates: N=0.86744, AF=0.09539, OLD=0.05471, YOUNG=0.03070
A =
[[0.99576201 0.00177623 0.00246176]
 [0.00558201 0.99191621 0.00250178]
 [0.00559722 0.0017188  0.99268399]]
pi = [0.40374988 0.27750257 0.31874756]
Iter 4: LL=-1269278.65 | Rates: N=0.86744, AF=0.09536, OLD=0.05796, YOUNG=0.02953
A =
[[0.99576344 0.00173516 0.00250141]
 [0.0057094  0.9916004  0.00269019]
 [0.00551005 0.00166244 0.99282751]]
pi = [0.40369809 0.27692348 0.31937844]
Iter 5: LL=-1269237.25 | Rates: N=0.86744, AF=0.09533, OLD=0.06055, YOUNG=0.02907
A =
[[0.99576423 0.00168583 0.00254993]
 [0.00583638 0.99120612 0.00295751]
 [0.0054399  0.00163782 0.99292227]]
pi = [0.40365303 0.27486486 0.32148211]
Iter 6: LL=-1269213.33 | Rates: N=0.86744, AF=0.09531, OLD=0.06275, YOUNG=0.02903
A =
[[0.99576469 0.00162946 0.00260585]
 [0.00595739 0.99075265 0.00328996]
 [0.00538732 0.00163513 0.99297755]]
pi = [0.40361813 0.27078738 0.32559448]
Iter 7: LL=-1269194.34 | Rates: N=0.86744, AF=0.09530, OLD=0.06481, YOUNG=0.02917
A =
[[0.99576502 0.00156739 0.00266759]
 [0.00607373 0.99024959 0.00367669]
 [0.00534845 0.0016445  0.99300705]]
pi = [0.40359386 0.26456557 0.33184057]
Iter 8: LL=-1269176.11 | Rates: N=0.86744, AF=0.09528, OLD=0.06688, YOUNG=0.02939
A =
[[0.99576534 0.00150105 0.00273361]
 [0.00618795 0.98970001 0.00411204]
 [0.00531969 0.00165993 0.99302038]]
pi = [0.40357917 0.2562825  0.34013833]
Iter 9: LL=-1269157.58 | Rates: N=0.86744, AF=0.09527, OLD=0.06905, YOUNG=0.02964
A =
[[0.99576567 0.00143177 0.00280256]
 [0.00630252 0.98910308 0.0045944 ]
 [0.00529835 0.00167808 0.99302357]]
pi = [0.40357319 0.24609008 0.35033673]
Iter 10: LL=-1269138.53 | Rates: N=0.86744, AF=0.09525, OLD=0.07136, YOUNG=0.02991
A =
[[0.99576604 0.0013607  0.00287326]
 [0.00641959 0.98845585 0.00512455]
 [0.00528248 0.00169703 0.9930205 ]]
pi = [0.40357547 0.23415875 0.36226578]
Iter 11: LL=-1269118.95 | Rates: N=0.86744, AF=0.09524, OLD=0.07386, YOUNG=0.03017
A =
[[0.99576645 0.00128886 0.00294469]
 [0.00654094 0.98775443 0.00570463]
 [0.00527073 0.00171549 0.99301378]]
pi = [0.40358582 0.2206678  0.37574638]
Iter 12: LL=-1269098.88 | Rates: N=0.86743, AF=0.09522, OLD=0.07656, YOUNG=0.03044
A =
[[0.99576691 0.00121716 0.00301593]
 [0.00666801 0.98699456 0.00633743]
 [0.00526216 0.00173251 0.99300533]]
pi = [0.40360423 0.2058076  0.39058817]
Iter 13: LL=-1269078.42 | Rates: N=0.86743, AF=0.09521, OLD=0.07948, YOUNG=0.03070
A =
[[0.99576741 0.00114645 0.00308615]
 [0.006802   0.986172   0.007026  ]
 [0.0052561  0.00174732 0.99299658]]
pi = [0.4036307  0.18978258 0.40658672]
Iter 14: LL=-1269057.69 | Rates: N=0.86743, AF=0.09519, OLD=0.08263, YOUNG=0.03096
A =
[[0.99576792 0.00107748 0.0031546 ]
 [0.00694387 0.98528285 0.00777328]
 [0.00525207 0.00175927 0.99298867]]
pi = [0.40366513 0.17281138 0.42352349]
Iter 15: LL=-1269036.84 | Rates: N=0.86743, AF=0.09518, OLD=0.08603, YOUNG=0.03121
A =
[[0.99576844 0.00101095 0.00322061]
 [0.00709418 0.98432417 0.00858165]
 [0.00524974 0.00176783 0.99298243]]
pi = [0.40370712 0.15512513 0.44116775]
Final Global Rates (lambdas): [0.86743242 0.0951777  0.08603429 0.03121449]
Final transition matrix A:
[[0.99576844 0.00101095 0.00322061]
 [0.00709418 0.98432417 0.00858165]
 [0.00524974 0.00176783 0.99298243]]
Final initial distribution pi:
[0.40370712 0.15512513 0.44116775]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.3147,0.0682,0.1121,9370546.0,20401454.0,128068999.0
Archaic_young,0.6787,0.9253,0.7830,275385486.0,130381514.0,22232788.0
Modern,0.0000,0.0000,0.0000,0.0,564461000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         560116           89           2275
Archaic_old      1559         9355         126992
Archaic_young    2786        20328         276500

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3707  0.1042  0.1627
Archaic_young     0.6692  0.9079  0.7705

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         540092          272           2818
Archaic_old      1630        15555         132697
Archaic_young    2866        26163         277907

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1509678.45 | Rates: N=0.86652, AF=0.09691, OLD=0.04664, YOUNG=0.03702
A =
[[0.99514463 0.00193797 0.0029174 ]
 [0.00609441 0.99084074 0.00306486]
 [0.00582477 0.0019595  0.99221573]]
pi = [0.57701846 0.18884588 0.23413566]
Iter 2: LL=-1270096.20 | Rates: N=0.86674, AF=0.09673, OLD=0.05003, YOUNG=0.03470
A =
[[0.9951522  0.00193788 0.00290992]
 [0.00619537 0.9907414  0.00306323]
 [0.0057275  0.00192229 0.9923502 ]]
pi = [0.57813946 0.19313868 0.22872186]
Iter 3: LL=-1270007.42 | Rates: N=0.86674, AF=0.09671, OLD=0.05409, YOUNG=0.03249
A =
[[0.99515419 0.00193803 0.00290779]
 [0.00635827 0.99057533 0.0030664 ]
 [0.00563095 0.00187828 0.99249077]]
pi = [0.57838341 0.20059224 0.22102436]
Iter 4: LL=-1269918.52 | Rates: N=0.86674, AF=0.09668, OLD=0.05772, YOUNG=0.03087
A =
[[0.99515566 0.00192542 0.00291893]
 [0.00655439 0.99032501 0.0031206 ]
 [0.00552806 0.00184196 0.99262998]]
pi = [0.57858265 0.20849852 0.21291883]
Iter 5: LL=-1269863.72 | Rates: N=0.86674, AF=0.09666, OLD=0.06049, YOUNG=0.02996
A =
[[0.99515656 0.00189942 0.00294402]
 [0.00674721 0.99001261 0.00324019]
 [0.00544163 0.00183047 0.9927279 ]]
pi = [0.57878659 0.21423429 0.20697912]
Iter 6: LL=-1269837.87 | Rates: N=0.86674, AF=0.09663, OLD=0.06254, YOUNG=0.02957
A =
[[0.99515715 0.00186275 0.0029801 ]
 [0.00691876 0.98966425 0.00341699]
 [0.00537816 0.00184138 0.99278045]]
pi = [0.57894973 0.21676877 0.2042815 ]
Iter 7: LL=-1269824.66 | Rates: N=0.86674, AF=0.09661, OLD=0.06415, YOUNG=0.02947
A =
[[0.9951576  0.00181881 0.00302359]
 [0.00706719 0.98929633 0.00363648]
 [0.00533476 0.0018654  0.99279984]]
pi = [0.5790587  0.21635809 0.20458321]
Iter 8: LL=-1269815.52 | Rates: N=0.86674, AF=0.09660, OLD=0.06551, YOUNG=0.02951
A =
[[0.99515798 0.00177051 0.00307151]
 [0.00719562 0.9889174  0.00388698]
 [0.0053067  0.00189537 0.99279793]]
pi = [0.57912613 0.21366024 0.20721363]
Iter 9: LL=-1269807.60 | Rates: N=0.86673, AF=0.09659, OLD=0.06677, YOUNG=0.02961
A =
[[0.99515835 0.00171992 0.00312173]
 [0.00730778 0.98853094 0.00416128]
 [0.00528989 0.00192728 0.99278283]]
pi = [0.5791685  0.20931238 0.21151911]
Iter 10: LL=-1269800.10 | Rates: N=0.86673, AF=0.09658, OLD=0.06798, YOUNG=0.02973
A =
[[0.99515872 0.00166841 0.00317286]
 [0.00740701 0.98813751 0.00445549]
 [0.00528123 0.00195909 0.99275967]]
pi = [0.57919722 0.20383008 0.2169727 ]
Iter 11: LL=-1269792.81 | Rates: N=0.86673, AF=0.09657, OLD=0.06919, YOUNG=0.02987
A =
[[0.99515911 0.00161686 0.00322404]
 [0.00749612 0.98773623 0.00476765]
 [0.00527844 0.00198984 0.99273171]]
pi = [0.57921827 0.19761354 0.2231682 ]
Iter 12: LL=-1269785.67 | Rates: N=0.86673, AF=0.09656, OLD=0.07041, YOUNG=0.03001
A =
[[0.9951595  0.0015658  0.0032747 ]
 [0.00757745 0.98732575 0.00509679]
 [0.00527986 0.00201907 0.99270107]]
pi = [0.57923426 0.19097188 0.22979387]
Iter 13: LL=-1269778.67 | Rates: N=0.86673, AF=0.09655, OLD=0.07165, YOUNG=0.03015
A =
[[0.9951599  0.00151561 0.00332449]
 [0.00765288 0.9869047  0.00544242]
 [0.00528425 0.00204658 0.99266917]]
pi = [0.5792461  0.18414322 0.23661069]
Iter 14: LL=-1269771.80 | Rates: N=0.86673, AF=0.09654, OLD=0.07292, YOUNG=0.03028
A =
[[0.9951603  0.00146653 0.00337318]
 [0.00772393 0.98647191 0.00580416]
 [0.00529073 0.00207227 0.992637  ]]
pi = [0.57925409 0.17730837 0.24343754]
Iter 15: LL=-1269765.07 | Rates: N=0.86673, AF=0.09654, OLD=0.07421, YOUNG=0.03042
A =
[[0.99516069 0.0014187  0.00342061]
 [0.00779181 0.9860265  0.00618168]
 [0.00529861 0.00209614 0.99260525]]
pi = [0.57925838 0.1706007  0.25014092]
Final Global Rates (lambdas): [0.86673207 0.09653749 0.07421251 0.03041525]
Final transition matrix A:
[[0.99516069 0.0014187  0.00342061]
 [0.00779181 0.9860265  0.00618168]
 [0.00529861 0.00209614 0.99260525]]
Final initial distribution pi:
[0.57925838 0.1706007  0.25014092]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.3804,0.1460,0.2110,21798360.0,35500640.0,127548079.0
Archaic_young,0.6728,0.8798,0.7625,268101636.0,130399364.0,36629517.0
Modern,0.0000,0.0000,0.0000,0.0,544200000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         540067          462           2653
Archaic_old      1497        21804         126581
Archaic_young    2636        35033         269267

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3333  0.0688  0.1140
Archaic_young     0.7067  0.9374  0.8059

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         540270          170           2962
Archaic_old      1618         9025         121045
Archaic_young    3393        17876         303641

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1512984.65 | Rates: N=0.86303, AF=0.09723, OLD=0.05010, YOUNG=0.04051
A =
[[0.99474645 0.00202255 0.003231  ]
 [0.00666968 0.98968133 0.003649  ]
 [0.00631845 0.00215157 0.99152999]]
pi = [0.55611263 0.18145331 0.26243406]
Iter 2: LL=-1276280.92 | Rates: N=0.86327, AF=0.09713, OLD=0.05380, YOUNG=0.03788
A =
[[0.99477059 0.00201933 0.00321008]
 [0.00670458 0.98963419 0.00366123]
 [0.0062361  0.00210619 0.99165771]]
pi = [0.55604351 0.1647875  0.27916899]
Iter 3: LL=-1276178.19 | Rates: N=0.86327, AF=0.09711, OLD=0.05864, YOUNG=0.03534
A =
[[0.99477357 0.00202719 0.00319924]
 [0.00680199 0.98951354 0.00368447]
 [0.00617877 0.00204667 0.99177455]]
pi = [0.55596812 0.13913535 0.30489653]
Iter 4: LL=-1276065.07 | Rates: N=0.86327, AF=0.09707, OLD=0.06313, YOUNG=0.03339
A =
[[0.99477555 0.0020214  0.00320305]
 [0.00694252 0.98926398 0.0037935 ]
 [0.00610833 0.00198264 0.99190903]]
pi = [0.55584349 0.10687285 0.33728366]
Iter 5: LL=-1275991.09 | Rates: N=0.86327, AF=0.09703, OLD=0.06666, YOUNG=0.03232
A =
[[0.99477652 0.00199951 0.00322397]
 [0.00709201 0.98889853 0.00400946]
 [0.00604716 0.00194074 0.9920121 ]]
pi = [0.55567469 0.07611116 0.36821415]
Iter 6: LL=-1275954.81 | Rates: N=0.86327, AF=0.09700, OLD=0.06935, YOUNG=0.03187
A =
[[0.99477674 0.00196437 0.0032589 ]
 [0.00722794 0.98845556 0.0043165 ]
 [0.00600477 0.00192432 0.99207091]]
pi = [0.55553251 0.05176025 0.39270724]
Iter 7: LL=-1275935.26 | Rates: N=0.86327, AF=0.09698, OLD=0.07153, YOUNG=0.03178
A =
[[0.99477673 0.00191973 0.00330354]
 [0.00734427 0.98796624 0.00468949]
 [0.00597952 0.00192506 0.99209542]]
pi = [0.55543577 0.03415319 0.41041104]
Iter 8: LL=-1275920.96 | Rates: N=0.86327, AF=0.09696, OLD=0.07345, YOUNG=0.03185
A =
[[0.99477675 0.0018689  0.00335435]
 [0.00744246 0.98744811 0.00510942]
 [0.00596703 0.00193526 0.99209771]]
pi = [0.55536899 0.02194327 0.42268774]
Iter 9: LL=-1275908.20 | Rates: N=0.86327, AF=0.09695, OLD=0.07528, YOUNG=0.03199
A =
[[0.99477685 0.00181435 0.0034088 ]
 [0.00752598 0.986909   0.00556502]
 [0.00596332 0.00195027 0.99208641]]
pi = [0.55531811 0.01370821 0.43097368]
Iter 10: LL=-1275896.01 | Rates: N=0.86326, AF=0.09693, OLD=0.07709, YOUNG=0.03217
A =
[[0.99477703 0.00175782 0.00346516]
 [0.00759838 0.98635135 0.00605027]
 [0.0059654  0.00196754 0.99206706]]
pi = [0.55527688 0.00830857 0.43641455]
Iter 11: LL=-1275884.16 | Rates: N=0.86326, AF=0.09692, OLD=0.07892, YOUNG=0.03235
A =
[[0.99477727 0.0017005  0.00352222]
 [0.00766282 0.98577502 0.00656216]
 [0.00597109 0.00198568 0.99204322]]
pi = [0.55524334 0.00487911 0.43987755]
Iter 12: LL=-1275872.60 | Rates: N=0.86326, AF=0.09691, OLD=0.08080, YOUNG=0.03253
A =
[[0.99477758 0.00164325 0.00357917]
 [0.00772196 0.98517888 0.00709915]
 [0.00597888 0.00200387 0.99201725]]
pi = [0.55521695 0.00277509 0.44200796]
Iter 13: LL=-1275861.31 | Rates: N=0.86326, AF=0.09690, OLD=0.08273, YOUNG=0.03271
A =
[[0.99477792 0.00158668 0.0036354 ]
 [0.00777793 0.98456163 0.00766044]
 [0.00598773 0.00202157 0.99199071]]
pi = [0.55519731 0.00152955 0.44327315]
Iter 14: LL=-1275850.31 | Rates: N=0.86326, AF=0.09688, OLD=0.08471, YOUNG=0.03289
A =
[[0.9947783  0.00153123 0.00369047]
 [0.00783239 0.9839222  0.0082454 ]
 [0.00599695 0.00203841 0.99196464]]
pi = [0.55518382 0.00081787 0.44399832]
Iter 15: LL=-1275839.62 | Rates: N=0.86326, AF=0.09687, OLD=0.08676, YOUNG=0.03307
A =
[[0.99477871 0.00147724 0.00374405]
 [0.00788656 0.98326004 0.0088534 ]
 [0.00600611 0.00205412 0.99193977]]
pi = [5.55175743e-01 4.24899470e-04 4.44399358e-01]
Final Global Rates (lambdas): [0.86326182 0.09687223 0.08676215 0.03306778]
Final transition matrix A:
[[0.99477871 0.00147724 0.00374405]
 [0.00788656 0.98326004 0.0088534 ]
 [0.00600611 0.00205412 0.99193977]]
Final initial distribution pi:
[5.55175743e-01 4.24899470e-04 4.44399358e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.3605,0.1106,0.1692,14502885.0,25725115.0,116684378.0
Archaic_young,0.7111,0.9125,0.7993,294194026.0,119513974.0,28221779.0
Modern,0.0000,0.0000,0.0000,0.0,546064000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         540520           74           2808
Archaic_old      1844        14494         115350
Archaic_young    3700        25660         295550

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3856  0.0747  0.1252
Archaic_young     0.6846  0.9380  0.7915

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         561313          155           3101
Archaic_old      2058        10099         123685
Archaic_young    3593        15957         280039

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1533318.04 | Rates: N=0.86785, AF=0.09695, OLD=0.05915, YOUNG=0.04866
A =
[[0.9946664  0.00204906 0.00328453]
 [0.00726846 0.98866408 0.00406746]
 [0.00708146 0.00244279 0.99047575]]
pi = [0.55077039 0.19409965 0.25512996]
Iter 2: LL=-1291546.11 | Rates: N=0.86809, AF=0.09682, OLD=0.06360, YOUNG=0.04560
A =
[[0.99471845 0.00204211 0.00323944]
 [0.00727724 0.98862491 0.00409784]
 [0.00694394 0.00238503 0.99067102]]
pi = [0.55164643 0.19278559 0.25556798]
Iter 3: LL=-1291427.10 | Rates: N=0.86809, AF=0.09679, OLD=0.06958, YOUNG=0.04244
A =
[[0.99472472 0.00205817 0.00321711]
 [0.00741198 0.98843453 0.00415349]
 [0.00685581 0.00230283 0.99084137]]
pi = [0.55166138 0.19070685 0.25763176]
Iter 4: LL=-1291286.25 | Rates: N=0.86808, AF=0.09674, OLD=0.07529, YOUNG=0.04000
A =
[[0.99472879 0.0020641  0.00320711]
 [0.00762024 0.98806208 0.00431768]
 [0.00674315 0.00221503 0.99104181]]
pi = [0.55165157 0.18625613 0.2620923 ]
Iter 5: LL=-1291190.27 | Rates: N=0.86808, AF=0.09669, OLD=0.07988, YOUNG=0.03866
A =
[[0.99473149 0.00205484 0.00321368]
 [0.00785397 0.98753154 0.00461449]
 [0.0066384  0.00216022 0.99120138]]
pi = [0.55162331 0.18084935 0.26752734]
Iter 6: LL=-1291142.31 | Rates: N=0.86807, AF=0.09665, OLD=0.08340, YOUNG=0.03814
A =
[[0.99473278 0.00203062 0.0032366 ]
 [0.00807562 0.98690119 0.00502319]
 [0.00656013 0.00214286 0.99129701]]
pi = [0.55158812 0.17572922 0.27268265]
Iter 7: LL=-1291116.21 | Rates: N=0.86807, AF=0.09662, OLD=0.08627, YOUNG=0.03804
A =
[[0.99473331 0.00199389 0.00327279]
 [0.00827087 0.98621675 0.00551238]
 [0.00650881 0.00215063 0.99134056]]
pi = [0.55155795 0.1712876  0.27715446]
Iter 8: LL=-1291097.19 | Rates: N=0.86807, AF=0.09659, OLD=0.08881, YOUNG=0.03815
A =
[[0.99473358 0.00194788 0.00331854]
 [0.00843799 0.98550337 0.00605864]
 [0.00647891 0.00217252 0.99134857]]
pi = [0.55153611 0.16755299 0.2809109 ]
Iter 9: LL=-1291080.44 | Rates: N=0.86807, AF=0.09656, OLD=0.09123, YOUNG=0.03834
A =
[[0.99473381 0.00189547 0.00337073]
 [0.00858003 0.98477135 0.00664862]
 [0.00646456 0.00220189 0.99133354]]
pi = [0.55152179 0.16445601 0.2840222 ]
Iter 10: LL=-1291064.61 | Rates: N=0.86806, AF=0.09654, OLD=0.09363, YOUNG=0.03855
A =
[[0.99473409 0.00183891 0.003427  ]
 [0.00870143 0.98402273 0.00727584]
 [0.00646104 0.00223504 0.99130392]]
pi = [0.55151342 0.16190639 0.2865802 ]
Iter 11: LL=-1291049.31 | Rates: N=0.86806, AF=0.09652, OLD=0.09605, YOUNG=0.03877
A =
[[0.99473444 0.00177987 0.00348569]
 [0.00880665 0.98325569 0.00793766]
 [0.0064648  0.00226984 0.99126536]]
pi = [0.55150956 0.15981438 0.28867606]
Iter 12: LL=-1291034.41 | Rates: N=0.86806, AF=0.09650, OLD=0.09854, YOUNG=0.03899
A =
[[0.99473485 0.00171958 0.00354558]
 [0.00889963 0.98246703 0.00863334]
 [0.00647333 0.00230496 0.99122172]]
pi = [0.5515091  0.15809797 0.29039293]
Iter 13: LL=-1291019.86 | Rates: N=0.86806, AF=0.09648, OLD=0.10109, YOUNG=0.03921
A =
[[0.9947353  0.00165894 0.00360576]
 [0.00898359 0.98165352 0.00936289]
 [0.00648484 0.00233952 0.99117564]]
pi = [0.55151115 0.15668503 0.29180382]
Iter 14: LL=-1291005.65 | Rates: N=0.86806, AF=0.09646, OLD=0.10373, YOUNG=0.03942
A =
[[0.99473578 0.00159865 0.00366557]
 [0.00906108 0.98081243 0.01012649]
 [0.00649812 0.0023729  0.99112898]]
pi = [0.55151502 0.15551299 0.29297199]
Iter 15: LL=-1290991.79 | Rates: N=0.86805, AF=0.09644, OLD=0.10645, YOUNG=0.03963
A =
[[0.99473627 0.00153925 0.00372448]
 [0.00913413 0.97994175 0.01092413]
 [0.00651232 0.00240467 0.99108301]]
pi = [0.55152013 0.15452728 0.2939526 ]
Final Global Rates (lambdas): [0.86805389 0.09644447 0.1064481  0.03962893]
Final transition matrix A:
[[0.99473627 0.00153925 0.00372448]
 [0.00913413 0.97994175 0.01092413]
 [0.00651232 0.00240467 0.99108301]]
Final initial distribution pi:
[0.55152013 0.15452728 0.2939526 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4267,0.1240,0.1922,16778178.0,22543822.0,118523124.0
Archaic_young,0.6920,0.9156,0.7883,271886860.0,121011140.0,25047622.0
Modern,0.0000,0.0000,0.0000,0.0,567780000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         561602          224           2743
Archaic_old      2229        16762         116851
Archaic_young    3949        22336         273304

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4227  0.0448  0.0810
Archaic_young     0.6565  0.9589  0.7794

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         539463          120           3416
Archaic_old      2515         6897         145184
Archaic_young    4205         9316         288884

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1534155.79 | Rates: N=0.86238, AF=0.09757, OLD=0.06451, YOUNG=0.05365
A =
[[0.99415499 0.00220035 0.00364467]
 [0.00734997 0.98806854 0.00458149]
 [0.00713422 0.00267791 0.99018787]]
pi = [0.20836318 0.35250048 0.43913634]
Iter 2: LL=-1296622.31 | Rates: N=0.86261, AF=0.09755, OLD=0.06950, YOUNG=0.05014
A =
[[0.9942477  0.00217422 0.00357808]
 [0.00732146 0.98809417 0.00458437]
 [0.00695602 0.00262858 0.9904154 ]]
pi = [0.19992525 0.3746242  0.42545055]
Iter 3: LL=-1296472.93 | Rates: N=0.86261, AF=0.09749, OLD=0.07660, YOUNG=0.04642
A =
[[0.99425943 0.00218599 0.00355458]
 [0.00744758 0.98797172 0.00458071]
 [0.00686283 0.00256112 0.99057605]]
pi = [0.19973872 0.39815776 0.40210352]
Iter 4: LL=-1296283.98 | Rates: N=0.86260, AF=0.09738, OLD=0.08349, YOUNG=0.04346
A =
[[0.99426579 0.002185   0.0035492 ]
 [0.00765999 0.98764616 0.00469385]
 [0.00674252 0.00248953 0.99076795]]
pi = [0.19971426 0.41283559 0.38745015]
Iter 5: LL=-1296152.72 | Rates: N=0.86260, AF=0.09729, OLD=0.08899, YOUNG=0.04183
A =
[[0.99426874 0.00216456 0.0035667 ]
 [0.00791211 0.98710859 0.00497931]
 [0.0066278  0.00245854 0.99091366]]
pi = [0.19969448 0.41211392 0.38819161]
Iter 6: LL=-1296088.62 | Rates: N=0.86259, AF=0.09721, OLD=0.09321, YOUNG=0.04118
A =
[[0.99426927 0.00212669 0.00360404]
 [0.00816345 0.98641654 0.00542   ]
 [0.0065388  0.00247244 0.99098876]]
pi = [0.19967541 0.40045916 0.39986543]
Iter 7: LL=-1296053.84 | Rates: N=0.86259, AF=0.09715, OLD=0.09671, YOUNG=0.04106
A =
[[0.99426891 0.00207552 0.00365558]
 [0.00839827 0.98562333 0.0059784 ]
 [0.00647603 0.00251422 0.99100975]]
pi = [0.19965754 0.384779   0.41556346]
Iter 8: LL=-1296027.35 | Rates: N=0.86259, AF=0.09709, OLD=0.09991, YOUNG=0.04119
A =
[[0.9942684  0.00201525 0.00371635]
 [0.00861464 0.98475846 0.0066269 ]
 [0.00643417 0.00256938 0.99099645]]
pi = [0.19964168 0.36921312 0.4311452 ]
Iter 9: LL=-1296002.80 | Rates: N=0.86259, AF=0.09705, OLD=0.10306, YOUNG=0.04141
A =
[[0.99426797 0.00194926 0.00378277]
 [0.00881529 0.98383406 0.00735064]
 [0.00640784 0.00262951 0.99096265]]
pi = [0.1996273  0.35542314 0.44494957]
Iter 10: LL=-1295978.62 | Rates: N=0.86258, AF=0.09700, OLD=0.10629, YOUNG=0.04166
A =
[[0.99426765 0.00187996 0.00385239]
 [0.009004   0.98285286 0.00814314]
 [0.00639273 0.00269011 0.99091716]]
pi = [0.19961335 0.3437754  0.45661126]
Iter 11: LL=-1295954.45 | Rates: N=0.86258, AF=0.09696, OLD=0.10966, YOUNG=0.04193
A =
[[0.99426743 0.00180899 0.00392358]
 [0.00918452 0.98181306 0.00900241]
 [0.00638567 0.00274865 0.99086568]]
pi = [0.19959898 0.33411112 0.4662899 ]
Iter 12: LL=-1295930.15 | Rates: N=0.86258, AF=0.09691, OLD=0.11324, YOUNG=0.04221
A =
[[0.99426729 0.00173749 0.00399523]
 [0.00936035 0.98071072 0.00992893]
 [0.00638431 0.00280355 0.99081213]]
pi = [0.19958367 0.32611434 0.474302  ]
Iter 13: LL=-1295905.66 | Rates: N=0.86257, AF=0.09686, OLD=0.11706, YOUNG=0.04248
A =
[[0.99426713 0.00166624 0.00406663]
 [0.00953498 0.97954026 0.01092475]
 [0.00638697 0.00285373 0.9907593 ]]
pi = [0.19956706 0.3194556  0.48097733]
Iter 14: LL=-1295880.82 | Rates: N=0.86257, AF=0.09680, OLD=0.12119, YOUNG=0.04276
A =
[[0.99426682 0.00159581 0.00413738]
 [0.0097126  0.97829371 0.01199369]
 [0.00639234 0.00289832 0.99070935]]
pi = [0.19954892 0.3138326  0.48661849]
Iter 15: LL=-1295855.34 | Rates: N=0.86257, AF=0.09672, OLD=0.12573, YOUNG=0.04304
A =
[[0.99426607 0.00152663 0.0042073 ]
 [0.00989913 0.97695847 0.0131424 ]
 [0.00639938 0.00293644 0.99066418]]
pi = [0.19952894 0.30896862 0.49150244]
Final Global Rates (lambdas): [0.86256527 0.09672272 0.12572648 0.04304279]
Final transition matrix A:
[[0.99426607 0.00152663 0.0042073 ]
 [0.00989913 0.97695847 0.0131424 ]
 [0.00639938 0.00293644 0.99066418]]
Final initial distribution pi:
[0.19952894 0.30896862 0.49150244]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4368,0.1044,0.1686,16091855.0,20746145.0,137973717.0
Archaic_young,0.6629,0.9220,0.7713,276189875.0,140457125.0,23362596.0
Modern,0.0000,0.0000,0.0000,0.0,546515000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         539563          393           3043
Archaic_old      2659        16076         135861
Archaic_young    4293        20369         277743

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3388  0.4861  0.3993
Archaic_young     0.6881  0.5470  0.6095

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         554999         1226           1460
Archaic_old      1923        69120          71658
Archaic_young    2567       133576         163471

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1520165.57 | Rates: N=0.87417, AF=0.09739, OLD=0.04940, YOUNG=0.03271
A =
[[0.99557268 0.00226237 0.00216494]
 [0.00577431 0.99213827 0.00208741]
 [0.00572138 0.00209965 0.99217897]]
pi = [0.45090094 0.24866585 0.30043321]
Iter 2: LL=-1273256.95 | Rates: N=0.87438, AF=0.09716, OLD=0.05200, YOUNG=0.03078
A =
[[0.99557645 0.0022383  0.00218525]
 [0.00590011 0.99191028 0.00218961]
 [0.00556661 0.00198255 0.99245083]]
pi = [0.44989071 0.21579632 0.33431297]
Iter 3: LL=-1273204.24 | Rates: N=0.87439, AF=0.09713, OLD=0.05431, YOUNG=0.02964
A =
[[0.9955772  0.00221022 0.00221257]
 [0.00603024 0.99164533 0.00232443]
 [0.00546405 0.00189475 0.9926412 ]]
pi = [0.44985558 0.18299628 0.36714813]
Iter 4: LL=-1273174.65 | Rates: N=0.87439, AF=0.09711, OLD=0.05614, YOUNG=0.02912
A =
[[0.99557742 0.00217441 0.00224817]
 [0.00614029 0.99136326 0.00249645]
 [0.00539517 0.00183856 0.99276628]]
pi = [0.44983966 0.15307198 0.39708836]
Iter 5: LL=-1273158.61 | Rates: N=0.87439, AF=0.09710, OLD=0.05759, YOUNG=0.02897
A =
[[0.99557743 0.002132   0.00229057]
 [0.00622989 0.99107118 0.00269894]
 [0.00535281 0.00180704 0.99284016]]
pi = [0.4498343  0.12691402 0.42325168]
Iter 6: LL=-1273147.71 | Rates: N=0.87439, AF=0.09709, OLD=0.05884, YOUNG=0.02901
A =
[[0.99557742 0.0020843  0.00233829]
 [0.00630409 0.99077066 0.00292526]
 [0.00532822 0.00179119 0.99288059]]
pi = [0.44983528 0.1044811  0.44568361]
Iter 7: LL=-1273138.39 | Rates: N=0.87439, AF=0.09708, OLD=0.05999, YOUNG=0.02915
A =
[[0.99557744 0.00203258 0.00238998]
 [0.00636753 0.99046166 0.00317081]
 [0.00531516 0.00178477 0.99290007]]
pi = [0.44983941 0.08542961 0.46473098]
Iter 8: LL=-1273129.51 | Rates: N=0.87439, AF=0.09707, OLD=0.06111, YOUNG=0.02933
A =
[[0.9955775  0.00197795 0.00244455]
 [0.00642345 0.99014357 0.00343298]
 [0.00530966 0.00178411 0.99290623]]
pi = [0.44984482 0.06935552 0.48079965]
Iter 9: LL=-1273120.75 | Rates: N=0.87439, AF=0.09706, OLD=0.06224, YOUNG=0.02952
A =
[[0.99557761 0.00192126 0.00250114]
 [0.006474   0.98981548 0.00371052]
 [0.00530923 0.00178709 0.99290368]]
pi = [0.44985054 0.05587361 0.49427586]
Iter 10: LL=-1273112.02 | Rates: N=0.87439, AF=0.09705, OLD=0.06340, YOUNG=0.02972
A =
[[0.99557775 0.00186319 0.00255906]
 [0.00652067 0.98947634 0.00400299]
 [0.00531222 0.00179248 0.9928953 ]]
pi = [0.44985607 0.04463806 0.50550588]
Iter 11: LL=-1273103.31 | Rates: N=0.87439, AF=0.09705, OLD=0.06459, YOUNG=0.02991
A =
[[0.99557793 0.0018043  0.00261777]
 [0.00656452 0.98912503 0.00431045]
 [0.00531753 0.00179949 0.99288298]]
pi = [0.4498612  0.03534308 0.51479572]
Iter 12: LL=-1273094.62 | Rates: N=0.87438, AF=0.09704, OLD=0.06583, YOUNG=0.03010
A =
[[0.99557814 0.00174504 0.00267681]
 [0.00660635 0.98876043 0.00463322]
 [0.00532438 0.00180757 0.99286805]]
pi = [0.44986586 0.02771782 0.52241632]
Iter 13: LL=-1273085.97 | Rates: N=0.87438, AF=0.09703, OLD=0.06711, YOUNG=0.03029
A =
[[0.99557838 0.00168581 0.00273581]
 [0.0066468  0.98838142 0.00497178]
 [0.00533223 0.00181632 0.99285144]]
pi = [0.44987006 0.02152087 0.52860907]
Iter 14: LL=-1273077.35 | Rates: N=0.87438, AF=0.09703, OLD=0.06844, YOUNG=0.03047
A =
[[0.99557863 0.00162693 0.00279444]
 [0.00668639 0.98798694 0.00532667]
 [0.00534067 0.00182545 0.99283387]]
pi = [0.44987384 0.01653622 0.53358994]
Iter 15: LL=-1273068.79 | Rates: N=0.87438, AF=0.09702, OLD=0.06983, YOUNG=0.03065
A =
[[0.99557891 0.00156868 0.00285241]
 [0.00672557 0.98757594 0.00569848]
 [0.00534941 0.00183471 0.99281588]]
pi = [0.44987727 0.01257059 0.53755214]
Final Global Rates (lambdas): [0.87438402 0.09701878 0.06982825 0.03064646]
Final transition matrix A:
[[0.99557891 0.00156868 0.00285241]
 [0.00672557 0.98757594 0.00569848]
 [0.00534941 0.00183471 0.99281588]]
Final initial distribution pi:
[0.44987727 0.01257059 0.53755214]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.3509,0.1665,0.2258,23659526.0,43773474.0,118447245.0
Archaic_young,0.6774,0.8500,0.7539,252976601.0,120481399.0,44641673.0
Modern,0.0000,0.0000,0.0000,0.0,559109000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         554978          484           2223
Archaic_old      1794        23693         117214
Archaic_young    2337        43256         254021

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4090  0.3733  0.3903
Archaic_young     0.7144  0.7450  0.7294

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         546673          916           2025
Archaic_old      2341        53333          87776
Archaic_young    2867        76086         227983

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1508670.27 | Rates: N=0.86141, AF=0.09648, OLD=0.05263, YOUNG=0.03514
A =
[[0.99503549 0.00232331 0.00264119]
 [0.00665144 0.99061392 0.00273464]
 [0.00592389 0.00217723 0.99189888]]
pi = [0.55458285 0.24218373 0.20323343]
Iter 2: LL=-1273202.00 | Rates: N=0.86163, AF=0.09632, OLD=0.05668, YOUNG=0.03252
A =
[[0.99505299 0.00228984 0.00265716]
 [0.00693809 0.99022923 0.00283269]
 [0.00568513 0.00207632 0.99223855]]
pi = [0.55605145 0.28335354 0.16059501]
Iter 3: LL=-1273098.09 | Rates: N=0.86163, AF=0.09628, OLD=0.06050, YOUNG=0.03095
A =
[[0.99505463 0.00225533 0.00269004]
 [0.00724411 0.98977936 0.00297653]
 [0.00552336 0.00201929 0.99245735]]
pi = [0.55540029 0.3245306  0.12006911]
Iter 4: LL=-1273037.65 | Rates: N=0.86163, AF=0.09624, OLD=0.06352, YOUNG=0.03021
A =
[[0.99505461 0.00220535 0.00274005]
 [0.00751866 0.98928775 0.00319359]
 [0.00541412 0.00200411 0.99258177]]
pi = [0.55467956 0.35523413 0.09008631]
Iter 5: LL=-1273006.42 | Rates: N=0.86163, AF=0.09621, OLD=0.06591, YOUNG=0.02997
A =
[[0.99505419 0.00214293 0.00280288]
 [0.00775273 0.98877339 0.00347387]
 [0.00534889 0.00201864 0.99263247]]
pi = [0.55416315 0.37550651 0.07033033]
Iter 6: LL=-1272986.37 | Rates: N=0.86163, AF=0.09619, OLD=0.06794, YOUNG=0.03000
A =
[[0.99505383 0.00207213 0.00287404]
 [0.00795363 0.9882431  0.00380326]
 [0.00531415 0.00204849 0.99263735]]
pi = [0.55382807 0.38863396 0.05753797]
Iter 7: LL=-1272969.71 | Rates: N=0.86163, AF=0.09617, OLD=0.06982, YOUNG=0.03014
A =
[[0.99505363 0.00199642 0.00294996]
 [0.00813037 0.98769817 0.00417147]
 [0.00529944 0.00208448 0.99261607]]
pi = [0.55359907 0.39739001 0.04901092]
Iter 8: LL=-1272954.08 | Rates: N=0.86163, AF=0.09616, OLD=0.07166, YOUNG=0.03033
A =
[[0.99505357 0.00191827 0.00302815]
 [0.00829006 0.98713734 0.0045726 ]
 [0.00529778 0.00212175 0.99258047]]
pi = [0.55342454 0.40348831 0.04308715]
Iter 9: LL=-1272938.90 | Rates: N=0.86163, AF=0.09614, OLD=0.07351, YOUNG=0.03054
A =
[[0.99505363 0.0018394  0.00310697]
 [0.00843801 0.98655828 0.00500371]
 [0.00530459 0.00215787 0.99253754]]
pi = [0.55327802 0.40791092 0.03881106]
Iter 10: LL=-1272924.01 | Rates: N=0.86163, AF=0.09613, OLD=0.07541, YOUNG=0.03075
A =
[[0.99505377 0.00176094 0.00318529]
 [0.00857817 0.9859584  0.00546343]
 [0.00531683 0.00219163 0.99249153]]
pi = [0.55314735 0.41122249 0.03563016]
Iter 11: LL=-1272909.39 | Rates: N=0.86163, AF=0.09612, OLD=0.07738, YOUNG=0.03096
A =
[[0.99505398 0.00168368 0.00326234]
 [0.00871353 0.9853354  0.00595107]
 [0.00533248 0.00222242 0.9924451 ]]
pi = [0.55302713 0.41375738 0.03321549]
Iter 12: LL=-1272895.06 | Rates: N=0.86163, AF=0.09610, OLD=0.07942, YOUNG=0.03117
A =
[[0.99505424 0.00160817 0.00333759]
 [0.00884635 0.98468754 0.00646612]
 [0.00535012 0.00224994 0.99239994]]
pi = [0.55291493 0.41572036 0.03136471]
Iter 13: LL=-1272881.04 | Rates: N=0.86163, AF=0.09609, OLD=0.08154, YOUNG=0.03137
A =
[[0.99505454 0.00153478 0.00341068]
 [0.00897835 0.98401363 0.00700802]
 [0.00536882 0.00227407 0.99235711]]
pi = [0.55280948 0.41724046 0.02995006]
Iter 14: LL=-1272867.36 | Rates: N=0.86163, AF=0.09607, OLD=0.08375, YOUNG=0.03158
A =
[[0.99505488 0.00146379 0.00348133]
 [0.00911085 0.9833131  0.00757605]
 [0.00538789 0.00229482 0.99231729]]
pi = [0.55270981 0.41840031 0.02888988]
Iter 15: LL=-1272854.05 | Rates: N=0.86163, AF=0.09606, OLD=0.08604, YOUNG=0.03178
A =
[[0.99505525 0.00139537 0.00354938]
 [0.00924491 0.98258576 0.00816933]
 [0.00540687 0.00231225 0.99228088]]
pi = [0.55261486 0.41925283 0.02813231]
Final Global Rates (lambdas): [0.8616314  0.09606049 0.08603508 0.03177657]
Final transition matrix A:
[[0.99505525 0.00139537 0.00354938]
 [0.00924491 0.98258576 0.00816933]
 [0.00540687 0.00231225 0.99228088]]
Final initial distribution pi:
[0.55261486 0.41925283 0.02813231]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4875,0.1410,0.2188,20140521.0,21173479.0,122670406.0
Archaic_young,0.6934,0.9238,0.7922,281500773.0,124447227.0,23230380.0
Modern,0.0000,0.0000,0.0000,0.0,552738000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         546944          136           2534
Archaic_old      2629        20128         120693
Archaic_young    3165        21050         282721

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4049  0.3178  0.3561
Archaic_young     0.7449  0.8110  0.7766

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         542775          826           2554
Archaic_old      2389        40789          85757
Archaic_young    3117        59109         262684

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1517239.33 | Rates: N=0.86394, AF=0.09728, OLD=0.05586, YOUNG=0.03886
A =
[[0.99464364 0.00237574 0.00298062]
 [0.00714534 0.98952724 0.00332743]
 [0.00630171 0.00233158 0.99136671]]
pi = [0.50365895 0.2200378  0.27630325]
Iter 2: LL=-1279600.32 | Rates: N=0.86417, AF=0.09723, OLD=0.05989, YOUNG=0.03596
A =
[[0.99468487 0.00234432 0.00297081]
 [0.00730594 0.9892977  0.00339636]
 [0.00611492 0.00222963 0.99165544]]
pi = [0.50294125 0.2109159  0.28614285]
Iter 3: LL=-1279495.60 | Rates: N=0.86417, AF=0.09719, OLD=0.06391, YOUNG=0.03405
A =
[[0.99468823 0.00232702 0.00298475]
 [0.00749791 0.98901514 0.00348695]
 [0.00601259 0.00216268 0.99182473]]
pi = [0.50290355 0.20020863 0.29688782]
Iter 4: LL=-1279430.99 | Rates: N=0.86417, AF=0.09715, OLD=0.06703, YOUNG=0.03300
A =
[[0.9946889  0.00229482 0.00301628]
 [0.00767737 0.98867087 0.00365176]
 [0.00593809 0.00212909 0.99193282]]
pi = [0.50289706 0.1878679  0.30923505]
Iter 5: LL=-1279400.00 | Rates: N=0.86417, AF=0.09712, OLD=0.06937, YOUNG=0.03255
A =
[[0.99468894 0.00225051 0.00306055]
 [0.00783254 0.98828374 0.00388373]
 [0.00589037 0.00212541 0.99198422]]
pi = [0.50289717 0.17456498 0.32253785]
Iter 6: LL=-1279383.70 | Rates: N=0.86417, AF=0.09709, OLD=0.07123, YOUNG=0.03244
A =
[[0.99468884 0.00219832 0.00311285]
 [0.00796603 0.98786757 0.0041664 ]
 [0.00586261 0.00214005 0.99199734]]
pi = [0.50290046 0.16073768 0.33636185]
Iter 7: LL=-1279372.03 | Rates: N=0.86417, AF=0.09707, OLD=0.07283, YOUNG=0.03249
A =
[[0.99468877 0.00214154 0.00316969]
 [0.00808325 0.98743028 0.00448647]
 [0.00584839 0.00216394 0.99198767]]
pi = [0.5029048  0.14670862 0.35038657]
Iter 8: LL=-1279361.67 | Rates: N=0.86417, AF=0.09706, OLD=0.07433, YOUNG=0.03263
A =
[[0.99468877 0.00208241 0.00322882]
 [0.00818867 0.98697559 0.00483574]
 [0.00584323 0.00219188 0.9919649 ]]
pi = [0.50290906 0.13273745 0.36435349]
Iter 9: LL=-1279351.72 | Rates: N=0.86417, AF=0.09704, OLD=0.07580, YOUNG=0.03279
A =
[[0.99468885 0.00202233 0.00328883]
 [0.00828556 0.98650454 0.0052099 ]
 [0.00584415 0.00222122 0.99193463]]
pi = [0.50291266 0.11903723 0.37805011]
Iter 10: LL=-1279341.95 | Rates: N=0.86417, AF=0.09703, OLD=0.07728, YOUNG=0.03297
A =
[[0.99468898 0.00196217 0.00334885]
 [0.00837638 0.98601669 0.00560694]
 [0.00584916 0.00225064 0.9919002 ]]
pi = [0.50291535 0.1057845  0.39130015]
Iter 11: LL=-1279332.31 | Rates: N=0.86417, AF=0.09701, OLD=0.07880, YOUNG=0.03314
A =
[[0.99468918 0.00190249 0.00340834]
 [0.00846305 0.98551082 0.00602613]
 [0.00585688 0.00227945 0.99186366]]
pi = [0.50291698 0.09312635 0.40395667]
Iter 12: LL=-1279322.77 | Rates: N=0.86417, AF=0.09700, OLD=0.08035, YOUNG=0.03332
A =
[[0.99468942 0.00184364 0.00346694]
 [0.00854717 0.98498536 0.00646747]
 [0.00586633 0.0023073  0.99182636]]
pi = [0.50291753 0.08118411 0.41589836]
Iter 13: LL=-1279313.34 | Rates: N=0.86416, AF=0.09699, OLD=0.08196, YOUNG=0.03350
A =
[[0.99468971 0.00178586 0.00352443]
 [0.00863006 0.98443861 0.00693133]
 [0.00587681 0.00233397 0.99178922]]
pi = [0.50291709 0.0700546  0.42702831]
Iter 14: LL=-1279303.99 | Rates: N=0.86416, AF=0.09697, OLD=0.08362, YOUNG=0.03367
A =
[[0.99469005 0.0017293  0.00358065]
 [0.00871283 0.98386888 0.00741829]
 [0.00588782 0.0023593  0.99175287]]
pi = [0.50291576 0.05981028 0.43727397]
Iter 15: LL=-1279294.73 | Rates: N=0.86416, AF=0.09696, OLD=0.08535, YOUNG=0.03384
A =
[[0.99469042 0.00167406 0.00363552]
 [0.00879643 0.98327449 0.00792908]
 [0.00589901 0.0023832  0.99171779]]
pi = [0.50291371 0.05049901 0.44658727]
Final Global Rates (lambdas): [0.86416344 0.09695683 0.08534822 0.03383655]
Final transition matrix A:
[[0.99469042 0.00167406 0.00363552]
 [0.00879643 0.98327449 0.00792908]
 [0.00589901 0.0023832  0.99171779]]
Final initial distribution pi:
[0.50291371 0.05049901 0.44658727]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4416,0.1783,0.2540,22880227.0,28932773.0,105475318.0
Archaic_young,0.7302,0.9063,0.8088,292216760.0,107958240.0,30199045.0
Modern,0.0000,0.0000,0.0000,0.0,548012000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         542755          538           2862
Archaic_old      2296        22901         103738
Archaic_young    2961        28374         293575

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4477  0.3133  0.3686
Archaic_young     0.7122  0.8135  0.7595

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         556965          771           2846
Archaic_old      2755        43567          93507
Archaic_young    3815        52973         242801

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1540663.88 | Rates: N=0.87084, AF=0.09859, OLD=0.06509, YOUNG=0.04555
A =
[[0.99438348 0.0024713  0.00314522]
 [0.00782268 0.98849482 0.00368249]
 [0.00715016 0.00265521 0.99019462]]
pi = [0.66734942 0.1620852  0.17056539]
Iter 2: LL=-1295837.66 | Rates: N=0.87108, AF=0.09856, OLD=0.07083, YOUNG=0.04157
A =
[[0.99444933 0.00242915 0.00312152]
 [0.00805679 0.98818651 0.0037567 ]
 [0.00685145 0.00251286 0.99063569]]
pi = [0.67612924 0.16948064 0.15439011]
Iter 3: LL=-1295666.58 | Rates: N=0.87107, AF=0.09848, OLD=0.07665, YOUNG=0.03900
A =
[[0.99445531 0.00240869 0.003136  ]
 [0.00837626 0.98775851 0.00386523]
 [0.00667196 0.00241024 0.9909178 ]]
pi = [0.67676193 0.17888481 0.14435326]
Iter 4: LL=-1295561.86 | Rates: N=0.87107, AF=0.09839, OLD=0.08116, YOUNG=0.03773
A =
[[0.99445578 0.00236983 0.0031744 ]
 [0.00867836 0.98724431 0.00407732]
 [0.00654376 0.00235874 0.9910975 ]]
pi = [0.67668386 0.1828156  0.14050054]
Iter 5: LL=-1295514.11 | Rates: N=0.87108, AF=0.09831, OLD=0.08455, YOUNG=0.03731
A =
[[0.99445491 0.00231406 0.00323103]
 [0.00893798 0.98668058 0.00438144]
 [0.0064644  0.00235065 0.99118495]]
pi = [0.67658529 0.18152913 0.14188559]
Iter 6: LL=-1295488.92 | Rates: N=0.87108, AF=0.09826, OLD=0.08729, YOUNG=0.03731
A =
[[0.99445392 0.00224645 0.00329963]
 [0.00915787 0.98608994 0.00475219]
 [0.00642066 0.00236734 0.991212  ]]
pi = [0.67653447 0.17642497 0.14704057]
Iter 7: LL=-1295470.20 | Rates: N=0.87108, AF=0.09821, OLD=0.08972, YOUNG=0.03749
A =
[[0.99445316 0.00217174 0.0033751 ]
 [0.00934675 0.98548226 0.00517099]
 [0.0064006  0.00239615 0.99120325]]
pi = [0.67653169 0.1686533  0.15481501]
Iter 8: LL=-1295453.33 | Rates: N=0.87108, AF=0.09818, OLD=0.09206, YOUNG=0.03774
A =
[[0.99445262 0.00209337 0.00345401]
 [0.00951301 0.98485885 0.00562814]
 [0.00639579 0.00243041 0.9911738 ]]
pi = [0.67656675 0.15908672 0.16434652]
Iter 9: LL=-1295437.12 | Rates: N=0.87108, AF=0.09815, OLD=0.09438, YOUNG=0.03801
A =
[[0.99445226 0.00201361 0.00353414]
 [0.00966361 0.98421657 0.00611982]
 [0.00640066 0.00246675 0.99113259]]
pi = [0.6766273  0.14847411 0.17489859]
Iter 10: LL=-1295421.24 | Rates: N=0.87107, AF=0.09812, OLD=0.09675, YOUNG=0.03828
A =
[[0.994452   0.0019339  0.0036141 ]
 [0.00980415 0.98355049 0.00664536]
 [0.00641153 0.00250335 0.99108512]]
pi = [0.67670157 0.13751854 0.18577989]
Iter 11: LL=-1295405.58 | Rates: N=0.87107, AF=0.09810, OLD=0.09921, YOUNG=0.03855
A =
[[0.99445181 0.00185521 0.00369298]
 [0.00993898 0.98285537 0.00720565]
 [0.006426   0.00253912 0.99103488]]
pi = [0.67677981 0.12686327 0.19635693]
Iter 12: LL=-1295390.08 | Rates: N=0.87107, AF=0.09807, OLD=0.10175, YOUNG=0.03881
A =
[[0.99445163 0.00177817 0.00377019]
 [0.01007145 0.98212618 0.00780238]
 [0.00644254 0.00257331 0.99098415]]
pi = [0.67685477 0.11702812 0.20611711]
Iter 13: LL=-1295374.71 | Rates: N=0.87107, AF=0.09805, OLD=0.10441, YOUNG=0.03907
A =
[[0.99445146 0.00170323 0.00384531]
 [0.0102042  0.98135819 0.00843761]
 [0.00646015 0.00260537 0.99093448]]
pi = [0.6769216  0.10835163 0.21472677]
Iter 14: LL=-1295359.42 | Rates: N=0.87107, AF=0.09802, OLD=0.10720, YOUNG=0.03933
A =
[[0.99445124 0.0016307  0.00391806]
 [0.01033944 0.98054678 0.00911378]
 [0.00647817 0.00263486 0.99088697]]
pi = [0.6769773  0.10097679 0.22204592]
Iter 15: LL=-1295344.19 | Rates: N=0.87107, AF=0.09799, OLD=0.11014, YOUNG=0.03958
A =
[[0.99445094 0.0015608  0.00398826]
 [0.01047928 0.97968703 0.00983369]
 [0.00649618 0.00266141 0.99084241]]
pi = [0.67702039 0.09488327 0.22809634]
Final Global Rates (lambdas): [0.87107206 0.09798849 0.11013715 0.03958147]
Final transition matrix A:
[[0.99445094 0.0015608  0.00398826]
 [0.01047928 0.97968703 0.00983369]
 [0.00649618 0.00266141 0.99084241]]
Final initial distribution pi:
[0.67702039 0.09488327 0.22809634]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5002,0.1635,0.2464,22737446.0,22723554.0,116335149.0
Archaic_young,0.6964,0.9154,0.7910,271820030.0,118512970.0,25114452.0
Modern,0.0000,0.0000,0.0000,0.0,564206000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         557133          421           3028
Archaic_old      3003        22737         114089
Archaic_young    4070        22303         273216

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3817  0.2544  0.3053
Archaic_young     0.7250  0.8233  0.7710

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         570591          741           2823
Archaic_old      2821        31245          89374
Archaic_young    4640        49816         247949

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1558821.62 | Rates: N=0.88035, AF=0.09770, OLD=0.07139, YOUNG=0.05146
A =
[[0.99418854 0.00250148 0.00330998]
 [0.00850697 0.9873474  0.00414563]
 [0.00790579 0.00292032 0.9891739 ]]
pi = [0.54462996 0.20602704 0.249343  ]
Iter 2: LL=-1305800.35 | Rates: N=0.88062, AF=0.09765, OLD=0.07758, YOUNG=0.04702
A =
[[0.99427671 0.00245497 0.00326832]
 [0.00869218 0.98709265 0.00421517]
 [0.00757668 0.00278195 0.98964136]]
pi = [0.54695612 0.20015515 0.25288872]
Iter 3: LL=-1305617.02 | Rates: N=0.88062, AF=0.09756, OLD=0.08424, YOUNG=0.04393
A =
[[0.99428503 0.00244019 0.00327478]
 [0.00900889 0.98667545 0.00431566]
 [0.00738717 0.00267435 0.98993848]]
pi = [0.54706549 0.19130954 0.26162497]
Iter 4: LL=-1305491.75 | Rates: N=0.88061, AF=0.09745, OLD=0.08957, YOUNG=0.04226
A =
[[0.99428565 0.00240705 0.00330729]
 [0.00932505 0.98613737 0.00453758]
 [0.00724523 0.00261519 0.99013958]]
pi = [0.54703424 0.17864638 0.27431938]
Iter 5: LL=-1305432.03 | Rates: N=0.88061, AF=0.09736, OLD=0.09357, YOUNG=0.04163
A =
[[0.99428447 0.00235602 0.00335951]
 [0.00959889 0.98552616 0.00487495]
 [0.00715561 0.0026044  0.99023999]]
pi = [0.54699771 0.16419975 0.28880254]
Iter 6: LL=-1305401.92 | Rates: N=0.88061, AF=0.09730, OLD=0.09675, YOUNG=0.04153
A =
[[0.99428309 0.0022923  0.00342461]
 [0.00982708 0.98487407 0.00529886]
 [0.00710654 0.00262265 0.99027081]]
pi = [0.5469743  0.14913449 0.30389122]
Iter 7: LL=-1305380.80 | Rates: N=0.88061, AF=0.09725, OLD=0.09954, YOUNG=0.04169
A =
[[0.99428201 0.00222096 0.00349702]
 [0.01001847 0.98419538 0.00578615]
 [0.00708475 0.00265476 0.99026048]]
pi = [0.54696465 0.13393375 0.31910159]
Iter 8: LL=-1305362.15 | Rates: N=0.88061, AF=0.09721, OLD=0.10218, YOUNG=0.04194
A =
[[0.99428124 0.00214574 0.00357302]
 [0.01018318 0.98349267 0.00632415]
 [0.00708043 0.00269247 0.9902271 ]]
pi = [0.54696502 0.11878022 0.33425476]
Iter 9: LL=-1305344.28 | Rates: N=0.88061, AF=0.09718, OLD=0.10481, YOUNG=0.04223
A =
[[0.99428069 0.00206905 0.00365026]
 [0.0103299  0.9827625  0.0069076 ]
 [0.00708693 0.00273172 0.99018135]]
pi = [0.54697174 0.10376011 0.34926814]
Iter 10: LL=-1305326.72 | Rates: N=0.88061, AF=0.09715, OLD=0.10750, YOUNG=0.04252
A =
[[0.99428028 0.00199243 0.00372729]
 [0.01046573 0.9819989  0.00753537]
 [0.00709985 0.00277048 0.99012967]]
pi = [0.54698218 0.08896791 0.36404991]
Iter 11: LL=-1305309.27 | Rates: N=0.88061, AF=0.09712, OLD=0.11029, YOUNG=0.04282
A =
[[0.99427995 0.0019168  0.00380325]
 [0.01059634 0.98119515 0.00820851]
 [0.0071163  0.00280772 0.99007598]]
pi = [0.54699455 0.07455963 0.37844582]
Iter 12: LL=-1305291.87 | Rates: N=0.88061, AF=0.09709, OLD=0.11321, YOUNG=0.04312
A =
[[0.99427967 0.00184275 0.00387758]
 [0.01072623 0.98034459 0.00892918]
 [0.0071344  0.0028428  0.9900228 ]]
pi = [0.54700764 0.06077352 0.39221884]
Iter 13: LL=-1305274.43 | Rates: N=0.88060, AF=0.09705, OLD=0.11630, YOUNG=0.04342
A =
[[0.99427941 0.00177063 0.00394995]
 [0.01085902 0.97944091 0.00970007]
 [0.00715292 0.00287537 0.98997171]]
pi = [0.54702055 0.04792234 0.40505711]
Iter 14: LL=-1305256.92 | Rates: N=0.88060, AF=0.09702, OLD=0.11955, YOUNG=0.04371
A =
[[0.99427917 0.00170067 0.00402016]
 [0.0109976  0.97847818 0.01052421]
 [0.00717112 0.00290515 0.98992373]]
pi = [0.54703256 0.03635522 0.41661222]
Iter 15: LL=-1305239.32 | Rates: N=0.88060, AF=0.09699, OLD=0.12300, YOUNG=0.04400
A =
[[0.99427893 0.00163301 0.00408806]
 [0.01114439 0.97745076 0.01140485]
 [0.00718852 0.00293197 0.98987951]]
pi = [0.54704306 0.02639225 0.42656469]
Final Global Rates (lambdas): [0.88060039 0.09698617 0.12299615 0.04400485]
Final transition matrix A:
[[0.99427893 0.00163301 0.00408806]
 [0.01114439 0.97745076 0.01140485]
 [0.00718852 0.00293197 0.98987951]]
Final initial distribution pi:
[0.54704306 0.02639225 0.42656469]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4064,0.141,0.2094,17311842.0,25285158.0,105441426.0
Archaic_young,0.7162,0.906,0.8000,271407147.0,107556853.0,28145324.0
Modern,0.0000,0.000,0.0000,0.0,578439000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         570720          481           2954
Archaic_old      2951        17322         103167
Archaic_young    4768        24794         272843

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3470  0.6385  0.4496
Archaic_young     0.7489  0.4754  0.5816

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         566037         1857           1108
Archaic_old      1998        83565          45821
Archaic_young    2596       155020         141998

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1521579.93 | Rates: N=0.87213, AF=0.09643, OLD=0.05304, YOUNG=0.03099
A =
[[0.99542199 0.0025955  0.00198251]
 [0.00649288 0.99161651 0.00189061]
 [0.00588378 0.00230904 0.99180718]]
pi = [0.60812813 0.2564655  0.13540637]
Iter 2: LL=-1276676.86 | Rates: N=0.87235, AF=0.09624, OLD=0.05537, YOUNG=0.02944
A =
[[0.99543279 0.0025274  0.00203982]
 [0.00670787 0.9913049  0.00198723]
 [0.00562999 0.00219844 0.99217157]]
pi = [0.60895665 0.29371128 0.09733206]
Iter 3: LL=-1276637.31 | Rates: N=0.87235, AF=0.09621, OLD=0.05731, YOUNG=0.02877
A =
[[0.99543352 0.00246583 0.00210064]
 [0.00688804 0.99102007 0.00209189]
 [0.00549907 0.00215368 0.99234725]]
pi = [0.60792257 0.32037581 0.07170162]
Iter 4: LL=-1276618.16 | Rates: N=0.87235, AF=0.09619, OLD=0.05877, YOUNG=0.02857
A =
[[0.99543361 0.0023996  0.0021668 ]
 [0.0070277  0.99075603 0.00221626]
 [0.00542412 0.00214339 0.99243249]]
pi = [0.60724039 0.33766807 0.05509154]
Iter 5: LL=-1276606.91 | Rates: N=0.87235, AF=0.09618, OLD=0.05994, YOUNG=0.02862
A =
[[0.99543365 0.00233015 0.0022362 ]
 [0.00713776 0.99050573 0.0023565 ]
 [0.00538372 0.00215128 0.992465  ]]
pi = [0.60680976 0.34900356 0.04418668]
Iter 6: LL=-1276598.15 | Rates: N=0.87235, AF=0.09617, OLD=0.06097, YOUNG=0.02877
A =
[[0.99543375 0.00225903 0.00230723]
 [0.00722808 0.99026265 0.00250928]
 [0.00536425 0.00216736 0.99246839]]
pi = [0.60651543 0.35663584 0.03684873]
Iter 7: LL=-1276590.20 | Rates: N=0.87235, AF=0.09617, OLD=0.06193, YOUNG=0.02896
A =
[[0.9954339  0.00218739 0.00237871]
 [0.00730518 0.99002222 0.00267261]
 [0.00535779 0.00218644 0.99245577]]
pi = [0.60629862 0.3618753  0.03182608]
Iter 8: LL=-1276582.59 | Rates: N=0.87235, AF=0.09616, OLD=0.06286, YOUNG=0.02917
A =
[[0.9954341  0.00211606 0.00244985]
 [0.00737314 0.98978131 0.00284555]
 [0.00535966 0.00220604 0.99243429]]
pi = [0.60613063 0.36548122 0.02838816]
Iter 9: LL=-1276575.20 | Rates: N=0.87235, AF=0.09615, OLD=0.06380, YOUNG=0.02938
A =
[[0.99543432 0.00204556 0.00252012]
 [0.00743456 0.98953763 0.00302781]
 [0.00536702 0.00222502 0.99240795]]
pi = [0.60599675 0.36790382 0.02609943]
Iter 10: LL=-1276567.97 | Rates: N=0.87235, AF=0.09615, OLD=0.06475, YOUNG=0.02958
A =
[[0.99543457 0.00197627 0.00258916]
 [0.00749118 0.98928944 0.00321938]
 [0.00537804 0.00224286 0.9923791 ]]
pi = [0.60588906 0.36941385 0.02469709]
Iter 11: LL=-1276560.90 | Rates: N=0.87235, AF=0.09614, OLD=0.06572, YOUNG=0.02978
A =
[[0.99543483 0.00190846 0.00265671]
 [0.00754419 0.98903541 0.0034204 ]
 [0.00539149 0.00225935 0.99234916]]
pi = [0.60580304 0.37017099 0.02402597]
Iter 12: LL=-1276553.97 | Rates: N=0.87235, AF=0.09614, OLD=0.06670, YOUNG=0.02998
A =
[[0.9954351  0.00184231 0.00272259]
 [0.00759446 0.9887745  0.00363105]
 [0.00540653 0.00227441 0.99231906]]
pi = [0.60573608 0.37026063 0.02400329]
Iter 13: LL=-1276547.18 | Rates: N=0.87235, AF=0.09613, OLD=0.06771, YOUNG=0.03017
A =
[[0.99543537 0.00177795 0.00278668]
 [0.00764257 0.98850593 0.0038515 ]
 [0.0054226  0.00228804 0.99228935]]
pi = [0.60568666 0.36971382 0.02459953]
Iter 14: LL=-1276540.53 | Rates: N=0.87235, AF=0.09613, OLD=0.06875, YOUNG=0.03035
A =
[[0.99543564 0.00171547 0.00284889]
 [0.00768897 0.98822915 0.00408188]
 [0.00543929 0.00230028 0.99226043]]
pi = [0.60565394 0.36851813 0.02582793]
Iter 15: LL=-1276534.02 | Rates: N=0.87235, AF=0.09612, OLD=0.06981, YOUNG=0.03053
A =
[[0.99543591 0.00165495 0.00290914]
 [0.00773394 0.98794376 0.0043223 ]
 [0.00545631 0.00231117 0.99223253]]
pi = [0.60563754 0.3666235  0.02773896]
Final Global Rates (lambdas): [0.87234657 0.09612095 0.06981047 0.03053341]
Final transition matrix A:
[[0.99543591 0.00165495 0.00290914]
 [0.00773394 0.98794376 0.0043223 ]
 [0.00545631 0.00231117 0.99223253]]
Final initial distribution pi:
[0.60563754 0.3666235  0.02773896]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3927  0.2698  0.3198   35246979.0   54511021.0  95416504.0
Archaic_young     0.7134  0.8148  0.7607  242487131.0   97432869.0  55131143.0
Modern            0.0000  0.0000  0.0000          0.0  570322000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         566019          774           2209
Archaic_old      1804        35317          94263
Archaic_young    2499        53667         243448

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4369  0.5863  0.5007
Archaic_young     0.7607  0.6361  0.6928

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         542117         1546           1473
Archaic_old      2763        86395          58770
Archaic_young    2850       109493         194593

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1512524.26 | Rates: N=0.86145, AF=0.09670, OLD=0.05700, YOUNG=0.03430
A =
[[0.99478406 0.00275334 0.0024626 ]
 [0.00704287 0.99042148 0.00253566]
 [0.00589226 0.00232743 0.99178031]]
pi = [0.69706366 0.17688949 0.12604686]
Iter 2: LL=-1276880.91 | Rates: N=0.86168, AF=0.09659, OLD=0.06017, YOUNG=0.03223
A =
[[0.99481378 0.00271485 0.00247137]
 [0.0073245  0.98998673 0.00268876]
 [0.00562711 0.00217652 0.99219636]]
pi = [0.70149128 0.20357255 0.09493617]
Iter 3: LL=-1276816.50 | Rates: N=0.86168, AF=0.09653, OLD=0.06288, YOUNG=0.03126
A =
[[0.99481487 0.00269365 0.00249147]
 [0.00756125 0.98958149 0.00285727]
 [0.0055003  0.00210454 0.99239516]]
pi = [0.70154997 0.2297315  0.06871853]
Iter 4: LL=-1276786.20 | Rates: N=0.86169, AF=0.09648, OLD=0.06491, YOUNG=0.03088
A =
[[0.99481406 0.00266143 0.00252451]
 [0.00774648 0.98918581 0.0030677 ]
 [0.00543002 0.00207534 0.99249464]]
pi = [0.70155734 0.24888419 0.04955847]
Iter 5: LL=-1276770.40 | Rates: N=0.86169, AF=0.09644, OLD=0.06650, YOUNG=0.03083
A =
[[0.99481318 0.00261941 0.0025674 ]
 [0.00789215 0.98879624 0.00331161]
 [0.00539592 0.00207145 0.99253264]]
pi = [0.70160267 0.26186775 0.03652958]
Iter 6: LL=-1276759.25 | Rates: N=0.86169, AF=0.09641, OLD=0.06787, YOUNG=0.03093
A =
[[0.9948125  0.00257036 0.00261714]
 [0.00801041 0.98840881 0.00358079]
 [0.00538434 0.00208114 0.99253452]]
pi = [0.7016751 0.2705285 0.0277964]
Iter 7: LL=-1276749.47 | Rates: N=0.86169, AF=0.09638, OLD=0.06913, YOUNG=0.03109
A =
[[0.994812   0.00251659 0.00267141]
 [0.0081101  0.9880197  0.0038702 ]
 [0.0053867  0.0020979  0.9925154 ]]
pi = [0.70176402 0.27634473 0.02189124]
Iter 8: LL=-1276740.13 | Rates: N=0.86169, AF=0.09636, OLD=0.07037, YOUNG=0.03127
A =
[[0.99481166 0.00245973 0.00272862]
 [0.00819733 0.98762517 0.0041775 ]
 [0.00539767 0.0021183  0.99248404]]
pi = [0.70186417 0.28029098 0.01784485]
Iter 9: LL=-1276730.92 | Rates: N=0.86169, AF=0.09634, OLD=0.07162, YOUNG=0.03147
A =
[[0.99481141 0.00240089 0.0027877 ]
 [0.00827645 0.98722156 0.00450199]
 [0.00541387 0.00214047 0.99244565]]
pi = [0.70197396 0.28297633 0.01504972]
Iter 10: LL=-1276721.76 | Rates: N=0.86169, AF=0.09632, OLD=0.07289, YOUNG=0.03166
A =
[[0.99481123 0.00234084 0.00284793]
 [0.00835065 0.98680542 0.00484393]
 [0.00543315 0.00216336 0.99240349]]
pi = [0.70209358 0.2847777  0.01312872]
Iter 11: LL=-1276712.59 | Rates: N=0.86169, AF=0.09630, OLD=0.07421, YOUNG=0.03185
A =
[[0.99481108 0.00228011 0.00290881]
 [0.00842233 0.98637353 0.00520413]
 [0.00545407 0.00218631 0.99235962]]
pi = [0.70222385 0.28592774 0.01184842]
Iter 12: LL=-1276703.38 | Rates: N=0.86169, AF=0.09628, OLD=0.07558, YOUNG=0.03204
A =
[[0.99481096 0.00221907 0.00296996]
 [0.00849339 0.9859229  0.00558371]
 [0.00547569 0.00220887 0.99231544]]
pi = [0.70236553 0.28656711 0.01106736]
Iter 13: LL=-1276694.11 | Rates: N=0.86169, AF=0.09626, OLD=0.07701, YOUNG=0.03224
A =
[[0.99481085 0.00215803 0.00303112]
 [0.00856527 0.98545076 0.00598397]
 [0.00549742 0.0022307  0.99227188]]
pi = [0.70251896 0.28677428 0.01070676]
Iter 14: LL=-1276684.75 | Rates: N=0.86169, AF=0.09624, OLD=0.07851, YOUNG=0.03242
A =
[[0.99481073 0.00209719 0.00309208]
 [0.00863916 0.9849545  0.00640633]
 [0.00551886 0.00225157 0.99222957]]
pi = [0.70268371 0.28658134 0.01073495]
Iter 15: LL=-1276675.29 | Rates: N=0.86170, AF=0.09622, OLD=0.08009, YOUNG=0.03261
A =
[[0.99481061 0.00203671 0.00315268]
 [0.00871601 0.98443164 0.00685235]
 [0.00553978 0.00227127 0.99218895]]
pi = [0.70285817 0.28598094 0.01116088]
Final Global Rates (lambdas): [0.86169513 0.09622166 0.08008523 0.03261213]
Final transition matrix A:
[[0.99481061 0.00203671 0.00315268]
 [0.00871601 0.98443164 0.00685235]
 [0.00553978 0.00227127 0.99218895]]
Final initial distribution pi:
[0.70285817 0.28598094 0.01116088]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5199,0.2466,0.3346,36292995.0,33510005.0,110858183.0
Archaic_young,0.7064,0.8873,0.7865,270375881.0,112402119.0,34355272.0
Modern,0.0000,0.0000,0.0000,0.0,547419000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         542132          706           2298
Archaic_old      2566        36374         108988
Archaic_young    2721        32723         271492

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4218  0.5005  0.4578
Archaic_young     0.7933  0.7387  0.7650

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         548987         1324           2121
Archaic_old      2600        61135          58923
Archaic_young    3474        82255         239181

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1524587.24 | Rates: N=0.86702, AF=0.09708, OLD=0.06158, YOUNG=0.03695
A =
[[0.99438503 0.00276911 0.00284587]
 [0.00803566 0.98880338 0.00316096]
 [0.00648794 0.00243353 0.99107852]]
pi = [0.59851221 0.17513506 0.22635273]
Iter 2: LL=-1284287.19 | Rates: N=0.86728, AF=0.09704, OLD=0.06650, YOUNG=0.03394
A =
[[0.99442823 0.00271375 0.00285802]
 [0.00836521 0.98826395 0.00337084]
 [0.00622545 0.00225923 0.99151532]]
pi = [0.60235971 0.15292495 0.24471533]
Iter 3: LL=-1284164.37 | Rates: N=0.86728, AF=0.09697, OLD=0.07078, YOUNG=0.03253
A =
[[0.99443009 0.0026768  0.00289311]
 [0.00862736 0.98773654 0.0036361 ]
 [0.00612924 0.00217587 0.99169489]]
pi = [0.60243734 0.13539282 0.26216984]
Iter 4: LL=-1284107.48 | Rates: N=0.86728, AF=0.09691, OLD=0.07400, YOUNG=0.03203
A =
[[0.99442936 0.00262243 0.00294821]
 [0.00882382 0.98717743 0.00399875]
 [0.00609558 0.00214296 0.99176146]]
pi = [0.60244922 0.12055164 0.27699915]
Iter 5: LL=-1284077.81 | Rates: N=0.86728, AF=0.09687, OLD=0.07660, YOUNG=0.03200
A =
[[0.99442873 0.00255518 0.00301609]
 [0.00897438 0.98658979 0.00443582]
 [0.00609705 0.00213856 0.99176438]]
pi = [0.60250095 0.10795622 0.28954283]
Iter 6: LL=-1284055.66 | Rates: N=0.86728, AF=0.09684, OLD=0.07893, YOUNG=0.03216
A =
[[0.99442843 0.00248019 0.00309138]
 [0.00909608 0.98597724 0.00492668]
 [0.00611712 0.00214788 0.991735  ]]
pi = [0.602568   0.09710922 0.30032279]
Iter 7: LL=-1284035.49 | Rates: N=0.86728, AF=0.09682, OLD=0.08118, YOUNG=0.03240
A =
[[0.99442838 0.00240092 0.0031707 ]
 [0.00919911 0.98534229 0.00545861]
 [0.00614678 0.00216337 0.99168985]]
pi = [0.60263564 0.08766828 0.30969608]
Iter 8: LL=-1284016.11 | Rates: N=0.86728, AF=0.09680, OLD=0.08344, YOUNG=0.03267
A =
[[0.99442851 0.00231956 0.00325193]
 [0.00928943 0.98468612 0.00602445]
 [0.0061811  0.00218149 0.99163741]]
pi = [0.60269791 0.07941903 0.31788306]
Iter 9: LL=-1283997.32 | Rates: N=0.86727, AF=0.09678, OLD=0.08575, YOUNG=0.03294
A =
[[0.99442876 0.00223752 0.00333372]
 [0.00937097 0.98400898 0.00662005]
 [0.00621721 0.0022005  0.99158229]]
pi = [0.60275244 0.07221733 0.32503023]
Iter 10: LL=-1283979.13 | Rates: N=0.86727, AF=0.09676, OLD=0.08813, YOUNG=0.03321
A =
[[0.9944291  0.00215575 0.00341515]
 [0.00944666 0.98331067 0.00724267]
 [0.00625332 0.0022195  0.99152718]]
pi = [0.60279811 0.06595189 0.33125   ]
Iter 11: LL=-1283961.56 | Rates: N=0.86727, AF=0.09674, OLD=0.09058, YOUNG=0.03348
A =
[[0.9944295  0.00207498 0.00349552]
 [0.00951892 0.98259082 0.00789025]
 [0.00628832 0.0022379  0.99147378]]
pi = [0.60283435 0.06052544 0.33664021]
Iter 12: LL=-1283944.65 | Rates: N=0.86727, AF=0.09673, OLD=0.09310, YOUNG=0.03373
A =
[[0.99442994 0.00199574 0.00357432]
 [0.00958981 0.98184913 0.00856105]
 [0.00632149 0.00225531 0.99142321]]
pi = [0.60286094 0.05584697 0.3412921 ]
Iter 13: LL=-1283928.43 | Rates: N=0.86727, AF=0.09671, OLD=0.09570, YOUNG=0.03398
A =
[[0.99443042 0.00191845 0.00365113]
 [0.00966114 0.98108536 0.0092535 ]
 [0.0063524  0.0022714  0.9913762 ]]
pi = [0.60287793 0.05182962 0.34529245]
Iter 14: LL=-1283912.89 | Rates: N=0.86727, AF=0.09669, OLD=0.09837, YOUNG=0.03423
A =
[[0.99443091 0.00184344 0.00372565]
 [0.00973447 0.98029934 0.00996619]
 [0.00638083 0.00228593 0.99133324]]
pi = [0.60288569 0.048391   0.34872331]
Iter 15: LL=-1283898.04 | Rates: N=0.86727, AF=0.09667, OLD=0.10112, YOUNG=0.03447
A =
[[0.9944314  0.00177096 0.00379764]
 [0.0098112  0.97949095 0.01069785]
 [0.00640669 0.00229869 0.99129462]]
pi = [0.60288479 0.04545417 0.35166104]
Final Global Rates (lambdas): [0.86726625 0.09666752 0.10111939 0.03447111]
Final transition matrix A:
[[0.9944314  0.00177096 0.00379764]
 [0.0098112  0.97949095 0.01069785]
 [0.00640669 0.00229869 0.99129462]]
Final initial distribution pi:
[0.60288479 0.04545417 0.35166104]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5713  0.1969  0.2928   24009004.0   18018996.0  97936551.0
Archaic_young     0.7517  0.9368  0.8341  302041402.0   99773598.0  20374403.0
Modern            0.0000  0.0000  0.0000          0.0  556157000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         549354          292           2786
Archaic_old      3007        24024          95627
Archaic_young    3796        17712         303402

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4114  0.4277  0.4194
Archaic_young     0.7534  0.7313  0.7422

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         573018          293           2272
Archaic_old      4078        53006          67744
Archaic_young    5724        75677         218188

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1545249.59 | Rates: N=0.87632, AF=0.09639, OLD=0.06866, YOUNG=0.04345
A =
[[0.99441927 0.00270036 0.00288037]
 [0.00858937 0.98792414 0.00348648]
 [0.00724811 0.00277864 0.98997325]]
pi = [0.74422531 0.10254112 0.15323357]
Iter 2: LL=-1296590.99 | Rates: N=0.87660, AF=0.09632, OLD=0.07371, YOUNG=0.04009
A =
[[0.99449417 0.0026307  0.00287512]
 [0.0089156  0.98746332 0.00362108]
 [0.00687693 0.00260536 0.99051771]]
pi = [0.75480808 0.07476986 0.17042206]
Iter 3: LL=-1296471.93 | Rates: N=0.87660, AF=0.09626, OLD=0.07826, YOUNG=0.03839
A =
[[0.99449776 0.00259412 0.00290812]
 [0.00926081 0.98696092 0.00377826]
 [0.00670635 0.00252216 0.99077149]]
pi = [0.75510494 0.05362489 0.19127017]
Iter 4: LL=-1296414.62 | Rates: N=0.87660, AF=0.09620, OLD=0.08163, YOUNG=0.03769
A =
[[0.99449632 0.00254207 0.00296161]
 [0.00955288 0.98643392 0.0040132 ]
 [0.00660638 0.00249288 0.99090074]]
pi = [0.75496647 0.03716671 0.20786681]
Iter 5: LL=-1296387.67 | Rates: N=0.87660, AF=0.09616, OLD=0.08422, YOUNG=0.03755
A =
[[0.99449481 0.00247726 0.00302793]
 [0.00979184 0.98589788 0.00431027]
 [0.00655439 0.00249542 0.99095019]]
pi = [0.75486336 0.02522509 0.21991155]
Iter 6: LL=-1296370.44 | Rates: N=0.87660, AF=0.09612, OLD=0.08641, YOUNG=0.03766
A =
[[0.99449376 0.0024047  0.00310153]
 [0.00998977 0.98535845 0.00465178]
 [0.00653374 0.0025125  0.99095375]]
pi = [0.75479247 0.01683911 0.22836841]
Iter 7: LL=-1296355.97 | Rates: N=0.87659, AF=0.09610, OLD=0.08843, YOUNG=0.03788
A =
[[0.99449312 0.00232823 0.00317865]
 [0.01015723 0.98481632 0.00502645]
 [0.00653335 0.00253475 0.9909319 ]]
pi = [0.75473945 0.01105745 0.2342031 ]
Iter 8: LL=-1296342.46 | Rates: N=0.87659, AF=0.09608, OLD=0.09038, YOUNG=0.03814
A =
[[0.99449274 0.00225035 0.00325691]
 [0.01030198 0.98426949 0.00542853]
 [0.00654607 0.00255769 0.99089624]]
pi = [0.75469745 0.00713382 0.23816873]
Iter 9: LL=-1296329.43 | Rates: N=0.87659, AF=0.09606, OLD=0.09234, YOUNG=0.03841
A =
[[0.99449255 0.00217262 0.00333483]
 [0.01042971 0.98371475 0.00585554]
 [0.00656726 0.00257931 0.99085342]]
pi = [0.75466333 0.00451562 0.24082106]
Iter 10: LL=-1296316.75 | Rates: N=0.87659, AF=0.09604, OLD=0.09433, YOUNG=0.03867
A =
[[0.99449246 0.00209603 0.00341151]
 [0.01054473 0.98314849 0.00630677]
 [0.00659381 0.00259873 0.99080746]]
pi = [0.75463541 0.00280085 0.24256374]
Iter 11: LL=-1296304.37 | Rates: N=0.87659, AF=0.09602, OLD=0.09638, YOUNG=0.03893
A =
[[0.99449245 0.00202114 0.00348641]
 [0.01065041 0.9825672  0.0067824 ]
 [0.0066236  0.00261556 0.99076084]]
pi = [0.75461262 0.00170046 0.24368692]
Iter 12: LL=-1296292.24 | Rates: N=0.87659, AF=0.09600, OLD=0.09850, YOUNG=0.03919
A =
[[0.9944925  0.0019483  0.0035592 ]
 [0.01074942 0.98196759 0.007283  ]
 [0.00665517 0.00262968 0.99071515]]
pi = [0.75459413 0.00100957 0.2443963 ]
Iter 13: LL=-1296280.32 | Rates: N=0.87659, AF=0.09598, OLD=0.10069, YOUNG=0.03944
A =
[[0.99449257 0.0018777  0.00362973]
 [0.01084393 0.98134668 0.00780938]
 [0.0066875  0.00264108 0.99067142]]
pi = [7.54579219e-01 5.85622696e-04 2.44835158e-01]
Iter 14: LL=-1296268.60 | Rates: N=0.87659, AF=0.09596, OLD=0.10297, YOUNG=0.03969
A =
[[0.99449267 0.00180942 0.00369791]
 [0.01093574 0.98070179 0.00836246]
 [0.0067199  0.00264978 0.99063032]]
pi = [7.54567287e-01 3.31619643e-04 2.45101093e-01]
Iter 15: LL=-1296257.03 | Rates: N=0.87659, AF=0.09594, OLD=0.10534, YOUNG=0.03994
A =
[[0.99449279 0.00174347 0.00376374]
 [0.01102636 0.98003045 0.00894319]
 [0.00675186 0.00265588 0.99059226]]
pi = [7.54557813e-01 1.83156614e-04 2.45259030e-01]
Final Global Rates (lambdas): [0.87658768 0.09593843 0.10533872 0.03993657]
Final transition matrix A:
[[0.99449279 0.00174347 0.00376374]
 [0.01102636 0.98003045 0.00894319]
 [0.00675186 0.00265588 0.99059226]]
Final initial distribution pi:
[7.54557813e-01 1.83156614e-04 2.45259030e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4434,0.1774,0.2534,22005725.0,27620275.0,102074369.0
Archaic_young,0.7195,0.8974,0.7987,266480174.0,103898826.0,30454308.0
Modern,0.0000,0.0000,0.0000,0.0,579995000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         572464          282           2837
Archaic_old      3060        22012          99756
Archaic_young    4471        27332         267786

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3670  0.7309  0.4886
Archaic_young     0.7863  0.4383  0.5629

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         563007         2065            856
Archaic_old      2404        97907          34147
Archaic_young    2498       166220         130896

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1529910.61 | Rates: N=0.87804, AF=0.09658, OLD=0.05593, YOUNG=0.03054
A =
[[0.99531689 0.00288183 0.00180129]
 [0.006833   0.99131118 0.00185582]
 [0.00558276 0.00245373 0.99196351]]
pi = [0.59886658 0.20904395 0.19208947]
Iter 2: LL=-1280080.21 | Rates: N=0.87827, AF=0.09644, OLD=0.05769, YOUNG=0.02976
A =
[[0.99534504 0.00281109 0.00184387]
 [0.00709401 0.9908698  0.00203619]
 [0.0052686  0.00236136 0.99237004]]
pi = [0.60172897 0.19987154 0.19839949]
Iter 3: LL=-1280055.15 | Rates: N=0.87827, AF=0.09641, OLD=0.05932, YOUNG=0.02957
A =
[[0.99534518 0.0027625  0.00189233]
 [0.00733244 0.9904448  0.00222276]
 [0.0051146  0.0023419  0.9925435 ]]
pi = [0.60181959 0.19499376 0.20318665]
Iter 4: LL=-1280038.67 | Rates: N=0.87827, AF=0.09639, OLD=0.06072, YOUNG=0.02964
A =
[[0.99534418 0.00270815 0.00194766]
 [0.00753864 0.99002853 0.00243283]
 [0.00502003 0.00234851 0.99263146]]
pi = [0.60181446 0.19101169 0.20717386]
Iter 5: LL=-1280025.23 | Rates: N=0.87827, AF=0.09637, OLD=0.06198, YOUNG=0.02982
A =
[[0.99534334 0.00264864 0.00200802]
 [0.00771887 0.98961792 0.0026632 ]
 [0.00496435 0.00236787 0.99266778]]
pi = [0.60180201 0.18723175 0.21096624]
Iter 6: LL=-1280012.97 | Rates: N=0.87827, AF=0.09635, OLD=0.06319, YOUNG=0.03004
A =
[[0.99534269 0.00258551 0.0020718 ]
 [0.00787889 0.98920985 0.00291127]
 [0.00493525 0.00239287 0.99267188]]
pi = [0.60178662 0.18323145 0.21498194]
Iter 7: LL=-1280001.28 | Rates: N=0.87827, AF=0.09634, OLD=0.06438, YOUNG=0.03027
A =
[[0.99534219 0.00252013 0.00213768]
 [0.00802285 0.98880174 0.00317541]
 [0.0049247  0.0024198  0.99265551]]
pi = [0.60177032 0.1787439  0.21948578]
Iter 8: LL=-1279989.99 | Rates: N=0.87827, AF=0.09633, OLD=0.06557, YOUNG=0.03050
A =
[[0.99534182 0.00245358 0.0022046 ]
 [0.00815381 0.98839146 0.00345473]
 [0.00492725 0.00244672 0.99262603]]
pi = [0.60175471 0.17361817 0.22462712]
Iter 9: LL=-1279979.02 | Rates: N=0.87827, AF=0.09631, OLD=0.06677, YOUNG=0.03072
A =
[[0.99534154 0.00238668 0.00227178]
 [0.00827411 0.98797709 0.0037488 ]
 [0.00493907 0.00247265 0.99258828]]
pi = [0.60174086 0.16779362 0.23046552]
Iter 10: LL=-1279968.35 | Rates: N=0.87827, AF=0.09630, OLD=0.06799, YOUNG=0.03093
A =
[[0.99534134 0.0023201  0.00233856]
 [0.00838567 0.98755688 0.00405745]
 [0.00495738 0.00249708 0.99254554]]
pi = [0.60172929 0.16128054 0.23699018]
Iter 11: LL=-1279957.98 | Rates: N=0.87827, AF=0.09629, OLD=0.06924, YOUNG=0.03114
A =
[[0.99534121 0.00225431 0.00240448]
 [0.00849012 0.9871292  0.00438068]
 [0.00498014 0.00251974 0.99250011]]
pi = [0.60172014 0.15414357 0.24413629]
Iter 12: LL=-1279947.91 | Rates: N=0.87827, AF=0.09628, OLD=0.07051, YOUNG=0.03134
A =
[[0.99534113 0.00218972 0.00246915]
 [0.00858883 0.9866926  0.00471857]
 [0.00500584 0.00254054 0.99245363]]
pi = [0.60171324 0.14648675 0.25180001]
Iter 13: LL=-1279938.14 | Rates: N=0.87827, AF=0.09627, OLD=0.07180, YOUNG=0.03154
A =
[[0.99534108 0.00212661 0.00253231]
 [0.008683   0.98624573 0.00507127]
 [0.00503333 0.00255945 0.99240721]]
pi = [0.60170823 0.13843951 0.25985226]
Iter 14: LL=-1279928.66 | Rates: N=0.87827, AF=0.09626, OLD=0.07313, YOUNG=0.03173
A =
[[0.99534107 0.0020652  0.00259373]
 [0.00877365 0.98578737 0.00543898]
 [0.00506179 0.00257653 0.99236168]]
pi = [0.60170468 0.13014402 0.26815131]
Iter 15: LL=-1279919.48 | Rates: N=0.87827, AF=0.09624, OLD=0.07448, YOUNG=0.03191
A =
[[0.99534108 0.00200563 0.00265329]
 [0.00886166 0.98531641 0.00582193]
 [0.0050906  0.00259185 0.99231756]]
pi = [0.60170209 0.12174404 0.27655387]
Final Global Rates (lambdas): [0.87827481 0.09624382 0.07447984 0.03191499]
Final transition matrix A:
[[0.99534108 0.00200563 0.00265329]
 [0.00886166 0.98531641 0.00582193]
 [0.0050906  0.00259185 0.99231756]]
Final initial distribution pi:
[0.60170209 0.12174404 0.27655387]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4844  0.2979  0.3689   39810824.0   42372176.0  93849485.0
Archaic_young     0.7275  0.8561  0.7866  254794226.0   95448774.0  42824048.0
Modern            0.0000  0.0000  0.0000          0.0  567574000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         563008          791           2129
Archaic_old      2199        39942          92317
Archaic_young    2367        41450         255797

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4282  0.6683  0.5219
Archaic_young     0.8217  0.6323  0.7147

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         562765         1881           1480
Archaic_old      2807        84476          39655
Archaic_young    3132       110443         193361

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1523555.23 | Rates: N=0.86972, AF=0.09656, OLD=0.05977, YOUNG=0.03226
A =
[[0.994937   0.0028268  0.00223621]
 [0.00783159 0.98967294 0.00249547]
 [0.00584636 0.00234897 0.99180467]]
pi = [0.78889671 0.120173   0.09093029]
Iter 2: LL=-1281078.52 | Rates: N=0.86995, AF=0.09654, OLD=0.06268, YOUNG=0.03047
A =
[[0.99498466 0.0027443  0.00227104]
 [0.00808108 0.98925993 0.00265899]
 [0.00560981 0.0022107  0.99217948]]
pi = [0.79871839 0.12869749 0.07258412]
Iter 3: LL=-1281030.35 | Rates: N=0.86995, AF=0.09650, OLD=0.06499, YOUNG=0.02978
A =
[[0.99498541 0.00269665 0.00231794]
 [0.00825298 0.98892022 0.0028268 ]
 [0.00555157 0.00217341 0.99227502]]
pi = [0.79875564 0.14135644 0.05988792]
Iter 4: LL=-1281010.61 | Rates: N=0.86995, AF=0.09647, OLD=0.06667, YOUNG=0.02959
A =
[[0.99498443 0.00264277 0.0023728 ]
 [0.00837138 0.98859789 0.00303073]
 [0.00553914 0.0021741  0.99228676]]
pi = [0.79858451 0.15100178 0.05041372]
Iter 5: LL=-1280999.24 | Rates: N=0.86996, AF=0.09645, OLD=0.06802, YOUNG=0.02962
A =
[[0.99498385 0.00258457 0.00243158]
 [0.00845853 0.98828134 0.00326013]
 [0.00554839 0.00219338 0.99225824]]
pi = [0.79844557 0.15788809 0.04366634]
Iter 6: LL=-1280990.11 | Rates: N=0.86996, AF=0.09643, OLD=0.06920, YOUNG=0.02975
A =
[[0.99498357 0.00252443 0.00249201]
 [0.00852824 0.9879646  0.00350716]
 [0.00556806 0.0022213  0.99221064]]
pi = [0.79834029 0.1626741  0.03898561]
Iter 7: LL=-1280981.70 | Rates: N=0.86996, AF=0.09642, OLD=0.07031, YOUNG=0.02991
A =
[[0.99498346 0.00246379 0.00255275]
 [0.0085881  0.98764444 0.00376746]
 [0.00559253 0.00225307 0.9921544 ]]
pi = [0.79826002 0.16589669 0.03584329]
Iter 8: LL=-1280973.67 | Rates: N=0.86996, AF=0.09640, OLD=0.07140, YOUNG=0.03009
A =
[[0.99498344 0.00240348 0.00261308]
 [0.00864235 0.98731889 0.00403876]
 [0.00561887 0.00228638 0.99209474]]
pi = [0.79819764 0.16792427 0.0338781 ]
Iter 9: LL=-1280965.93 | Rates: N=0.86996, AF=0.09639, OLD=0.07249, YOUNG=0.03027
A =
[[0.99498348 0.00234396 0.00267256]
 [0.00869351 0.98698662 0.00431987]
 [0.00564554 0.0023201  0.99203436]]
pi = [0.79814837 0.16899279 0.03285884]
Iter 10: LL=-1280958.45 | Rates: N=0.86996, AF=0.09638, OLD=0.07358, YOUNG=0.03045
A =
[[0.99498354 0.0022855  0.00273095]
 [0.00874319 0.98664668 0.00461013]
 [0.00567166 0.00235361 0.99197473]]
pi = [0.79810921 0.16924509 0.0326457 ]
Iter 11: LL=-1280951.22 | Rates: N=0.86996, AF=0.09637, OLD=0.07468, YOUNG=0.03063
A =
[[0.99498363 0.00222827 0.00278811]
 [0.00879246 0.98629839 0.00490916]
 [0.00569677 0.00238654 0.99191669]]
pi = [0.79807836 0.16875999 0.03316165]
Iter 12: LL=-1280944.24 | Rates: N=0.86996, AF=0.09636, OLD=0.07579, YOUNG=0.03080
A =
[[0.99498372 0.00217234 0.00284394]
 [0.00884208 0.98594127 0.00521665]
 [0.00572062 0.00241866 0.99186072]]
pi = [0.79805481 0.16757264 0.03437255]
Iter 13: LL=-1280937.49 | Rates: N=0.86996, AF=0.09635, OLD=0.07691, YOUNG=0.03097
A =
[[0.99498382 0.00211779 0.00289839]
 [0.00889258 0.98557504 0.00553238]
 [0.0057431  0.00244979 0.99180711]]
pi = [0.79803809 0.16568971 0.03627219]
Iter 14: LL=-1280930.97 | Rates: N=0.86996, AF=0.09634, OLD=0.07805, YOUNG=0.03114
A =
[[0.99498391 0.00206465 0.00295144]
 [0.00894436 0.98519952 0.00585612]
 [0.00576417 0.00247982 0.99175602]]
pi = [0.79802808 0.16310246 0.03886946]
Iter 15: LL=-1280924.68 | Rates: N=0.86996, AF=0.09634, OLD=0.07920, YOUNG=0.03130
A =
[[0.994984   0.00201294 0.00300306]
 [0.00899768 0.98481465 0.00618767]
 [0.00578385 0.00250864 0.99170751]]
pi = [0.79802489 0.15979928 0.04217583]
Final Global Rates (lambdas): [0.86995737 0.09633519 0.07920326 0.03130125]
Final transition matrix A:
[[0.994984   0.00201294 0.00300306]
 [0.00899768 0.98481465 0.00618767]
 [0.00578385 0.00250864 0.99170751]]
Final initial distribution pi:
[0.79802489 0.15979928 0.04217583]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5463  0.3439  0.4221   43363546.0   36009454.0  82712483.0
Archaic_young     0.7603  0.8787  0.8152  267780802.0   84425198.0  36950351.0
Modern            0.0000  0.0000  0.0000          0.0  568421000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         562792          781           2553
Archaic_old      2645        43496          80797
Archaic_young    2984        35096         268856

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.3, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4824  0.5945  0.5326
Archaic_young     0.7934  0.6978  0.7425

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         524307          472           1946
Archaic_old      5048        87568          55749
Archaic_young    5325        93698         225887

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1515921.37 | Rates: N=0.85567, AF=0.09873, OLD=0.06582, YOUNG=0.03632
A =
[[0.99394541 0.00320151 0.00285308]
 [0.00808437 0.98891782 0.0029978 ]
 [0.00603162 0.00258626 0.99138211]]
pi = [0.44924913 0.26822122 0.28252965]
Iter 2: LL=-1284551.51 | Rates: N=0.85590, AF=0.09884, OLD=0.06991, YOUNG=0.03382
A =
[[0.99401582 0.00307921 0.00290497]
 [0.00840023 0.98840254 0.00319723]
 [0.00575483 0.00247231 0.99177287]]
pi = [0.44805161 0.27084276 0.28110563]
Iter 3: LL=-1284462.63 | Rates: N=0.85590, AF=0.09878, OLD=0.07330, YOUNG=0.03281
A =
[[0.9940193  0.00300058 0.00298013]
 [0.0086426  0.98794078 0.00341661]
 [0.0056663  0.00247745 0.99185625]]
pi = [0.44795072 0.27528613 0.27676315]
Iter 4: LL=-1284424.01 | Rates: N=0.85590, AF=0.09873, OLD=0.07581, YOUNG=0.03249
A =
[[0.9940192  0.00291239 0.00306841]
 [0.00883783 0.98746124 0.00370093]
 [0.00562649 0.00252549 0.99184802]]
pi = [0.44787059 0.27711819 0.27501123]
Iter 5: LL=-1284401.48 | Rates: N=0.85590, AF=0.09869, OLD=0.07787, YOUNG=0.03251
A =
[[0.99401914 0.0028188  0.00316206]
 [0.00900634 0.98696097 0.00403269]
 [0.00561089 0.00259133 0.99179778]]
pi = [0.44780673 0.27633427 0.275859  ]
Iter 6: LL=-1284383.27 | Rates: N=0.85590, AF=0.09867, OLD=0.07971, YOUNG=0.03267
A =
[[0.9940193  0.00272379 0.00325691]
 [0.00916111 0.98644008 0.00439881]
 [0.00560802 0.0026619  0.99173008]]
pi = [0.44775673 0.27373171 0.27851156]
Iter 7: LL=-1284366.46 | Rates: N=0.85590, AF=0.09864, OLD=0.08149, YOUNG=0.03288
A =
[[0.99401959 0.00262958 0.00335083]
 [0.00930921 0.9858986  0.00479219]
 [0.00561218 0.00273124 0.99165658]]
pi = [0.44771558 0.27007738 0.28220704]
Iter 8: LL=-1284350.39 | Rates: N=0.85590, AF=0.09862, OLD=0.08326, YOUNG=0.03312
A =
[[0.99401995 0.00253731 0.00344274]
 [0.00945453 0.98533613 0.00520934]
 [0.00562043 0.00279685 0.99158272]]
pi = [0.44767928 0.26593865 0.28638207]
Iter 9: LL=-1284334.89 | Rates: N=0.85590, AF=0.09860, OLD=0.08505, YOUNG=0.03336
A =
[[0.99402035 0.00244752 0.00353213]
 [0.00959939 0.98475192 0.00564869]
 [0.00563113 0.00285773 0.99151114]]
pi = [0.44764515 0.26169902 0.29065582]
Iter 10: LL=-1284319.90 | Rates: N=0.85590, AF=0.09858, OLD=0.08689, YOUNG=0.03360
A =
[[0.99402076 0.00236048 0.00361876]
 [0.00974536 0.98414507 0.00610956]
 [0.00564331 0.00291354 0.99144316]]
pi = [0.44761135 0.2576045  0.29478415]
Iter 11: LL=-1284305.37 | Rates: N=0.85590, AF=0.09856, OLD=0.08878, YOUNG=0.03385
A =
[[0.99402117 0.00227628 0.00370255]
 [0.00989361 0.98351466 0.00659173]
 [0.00565635 0.00296419 0.99137946]]
pi = [0.44757659 0.25380386 0.29861955]
Iter 12: LL=-1284291.26 | Rates: N=0.85589, AF=0.09854, OLD=0.09072, YOUNG=0.03409
A =
[[0.99402158 0.00219494 0.00378348]
 [0.01004501 0.98285987 0.00709511]
 [0.00566988 0.0030097  0.99132041]]
pi = [0.4475399 0.2503788 0.3020813]
Iter 13: LL=-1284277.55 | Rates: N=0.85589, AF=0.09852, OLD=0.09272, YOUNG=0.03432
A =
[[0.99402198 0.00211642 0.0038616 ]
 [0.0102002  0.98218013 0.00761967]
 [0.00568368 0.00305014 0.99126618]]
pi = [0.44750059 0.24736555 0.30513386]
Iter 14: LL=-1284264.23 | Rates: N=0.85589, AF=0.09849, OLD=0.09479, YOUNG=0.03456
A =
[[0.99402237 0.00204067 0.00393696]
 [0.0103596  0.98147518 0.00816522]
 [0.00569762 0.00308558 0.9912168 ]]
pi = [0.44745812 0.24477036 0.30777152]
Iter 15: LL=-1284251.27 | Rates: N=0.85589, AF=0.09847, OLD=0.09691, YOUNG=0.03479
A =
[[0.99402274 0.00196765 0.00400961]
 [0.01052339 0.98074528 0.00873133]
 [0.00571163 0.00311613 0.99117224]]
pi = [0.44741213 0.24258014 0.31000773]
Final Global Rates (lambdas): [0.855891   0.0984706  0.09691276 0.03479292]
Final transition matrix A:
[[0.99402274 0.00196765 0.00400961]
 [0.01052339 0.98074528 0.00873133]
 [0.00571163 0.00311613 0.99117224]]
Final initial distribution pi:
[0.44741213 0.24258014 0.31000773]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.3_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.6200,0.2505,0.3568,36936724.0,22636276.0,110538448.0
Archaic_young,0.7268,0.9227,0.8131,297491262.0,111804738.0,24924543.0
Modern,0.0000,0.0000,0.0000,0.0,531131000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         523519          309           2897
Archaic_old      3876        36928         107561
Archaic_young    3736        22336         298838

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2295  0.0502  0.0824
Archaic_young     0.7551  0.9423  0.8383

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         478700          139           2662
Archaic_old      1042         6175         116107
Archaic_young    3001        20611         371563

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1464247.96 | Rates: N=0.83373, AF=0.09655, OLD=0.04599, YOUNG=0.03588
A =
[[0.99495634 0.00168546 0.0033582 ]
 [0.00483731 0.9919888  0.00317389]
 [0.00480951 0.00158881 0.99360168]]
pi = [0.45084559 0.22777317 0.32138124]
Iter 2: LL=-1251151.38 | Rates: N=0.83390, AF=0.09627, OLD=0.04950, YOUNG=0.03419
A =
[[0.99495732 0.00170285 0.00333983]
 [0.00492404 0.99191413 0.00316183]
 [0.0047466  0.00156922 0.99368417]]
pi = [0.45176318 0.24437895 0.30385788]
Iter 3: LL=-1251075.84 | Rates: N=0.83391, AF=0.09624, OLD=0.05329, YOUNG=0.03255
A =
[[0.99495865 0.00171711 0.00332423]
 [0.00508049 0.99173688 0.00318264]
 [0.00467036 0.00154307 0.99378658]]
pi = [0.4515271  0.26378221 0.28469069]
Iter 4: LL=-1251005.96 | Rates: N=0.83391, AF=0.09621, OLD=0.05663, YOUNG=0.03139
A =
[[0.99495939 0.00171958 0.00332103]
 [0.00528339 0.99144281 0.00327381]
 [0.0045819  0.00152267 0.99389543]]
pi = [0.45128976 0.28164821 0.26706203]
Iter 5: LL=-1250962.61 | Rates: N=0.83391, AF=0.09617, OLD=0.05930, YOUNG=0.03076
A =
[[0.9949595  0.00170753 0.00333297]
 [0.00550166 0.99105458 0.00344376]
 [0.00450005 0.00151713 0.99398283]]
pi = [0.45111687 0.29593299 0.25295014]
Iter 6: LL=-1250939.21 | Rates: N=0.83391, AF=0.09614, OLD=0.06143, YOUNG=0.03051
A =
[[0.99495929 0.00168238 0.00335833]
 [0.00571177 0.9906076  0.00368063]
 [0.00443464 0.00152497 0.99404038]]
pi = [0.45098626 0.30626842 0.24274533]
Iter 7: LL=-1250924.45 | Rates: N=0.83391, AF=0.09611, OLD=0.06324, YOUNG=0.03046
A =
[[0.99495902 0.00164715 0.00339383]
 [0.0059031  0.99012731 0.0039696 ]
 [0.00438708 0.00154115 0.99407176]]
pi = [0.45087901 0.31309836 0.23602263]
Iter 8: LL=-1250912.67 | Rates: N=0.83391, AF=0.09608, OLD=0.06491, YOUNG=0.03051
A =
[[0.99495879 0.00160493 0.00343628]
 [0.00607302 0.98962683 0.00430015]
 [0.00435506 0.0015616  0.99408334]]
pi = [0.45078604 0.31709283 0.23212112]
Iter 9: LL=-1250901.86 | Rates: N=0.83391, AF=0.09606, OLD=0.06652, YOUNG=0.03061
A =
[[0.99495864 0.00155822 0.00348314]
 [0.00622261 0.98911099 0.0046664 ]
 [0.00433541 0.00158384 0.99408076]]
pi = [0.45070338 0.31887932 0.23041729]
Iter 10: LL=-1250891.39 | Rates: N=0.83391, AF=0.09604, OLD=0.06814, YOUNG=0.03072
A =
[[0.99495857 0.00150886 0.00353257]
 [0.0063543  0.98858013 0.00506557]
 [0.00432522 0.00160644 0.99406834]]
pi = [0.45062912 0.31897092 0.23039996]
Iter 11: LL=-1250881.03 | Rates: N=0.83391, AF=0.09602, OLD=0.06980, YOUNG=0.03083
A =
[[0.99495857 0.00145819 0.00358324]
 [0.00647074 0.98803265 0.00549662]
 [0.00432213 0.0016286  0.99404927]]
pi = [0.45056205 0.31777058 0.23166737]
Iter 12: LL=-1250870.72 | Rates: N=0.83391, AF=0.09600, OLD=0.07151, YOUNG=0.03095
A =
[[0.99495862 0.00140717 0.00363421]
 [0.00657436 0.98746639 0.00595925]
 [0.0043243  0.00164985 0.99402585]]
pi = [0.45050125 0.31559239 0.23390636]
Iter 13: LL=-1250860.46 | Rates: N=0.83392, AF=0.09598, OLD=0.07328, YOUNG=0.03106
A =
[[0.99495871 0.0013565  0.00368479]
 [0.00666718 0.98687934 0.00645347]
 [0.00433032 0.00166994 0.99399974]]
pi = [0.45044597 0.31268123 0.2368728 ]
Iter 14: LL=-1250850.27 | Rates: N=0.83392, AF=0.09596, OLD=0.07512, YOUNG=0.03117
A =
[[0.99495884 0.00130669 0.00373448]
 [0.00675084 0.98626987 0.0069793 ]
 [0.00433913 0.00168873 0.99397213]]
pi = [0.45039558 0.30922791 0.24037651]
Iter 15: LL=-1250840.18 | Rates: N=0.83392, AF=0.09594, OLD=0.07703, YOUNG=0.03129
A =
[[0.99495899 0.00125807 0.00378293]
 [0.00682663 0.98563666 0.0075367 ]
 [0.00434991 0.00170619 0.99394391]]
pi = [0.45034954 0.30538037 0.24427009]
Final Global Rates (lambdas): [0.83391587 0.09593962 0.07702962 0.03128546]
Final transition matrix A:
[[0.99495899 0.00125807 0.00378293]
 [0.00682663 0.98563666 0.0075367 ]
 [0.00434991 0.00170619 0.99394391]]
Final initial distribution pi:
[0.45034954 0.30538037 0.24427009]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.2710,0.0785,0.1217,9656003.0,25975997.0,113403062.0
Archaic_young,0.7582,0.9300,0.8354,365427719.0,116518281.0,27484657.0
Modern,0.0000,0.0000,0.0000,0.0,482422000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         478673          284           2544
Archaic_old       975         9659         112690
Archaic_young    2774        25689         366712

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2797  0.0157  0.0298
Archaic_young     0.7707  0.9828  0.8639

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         473478           74           2836
Archaic_old      1075         1834         113886
Archaic_young    3341         4650         398826

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 10
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1459868.93 | Rates: N=0.83035, AF=0.09591, OLD=0.04599, YOUNG=0.03674
A =
[[0.99445222 0.0016891  0.00385868]
 [0.00547221 0.99040878 0.00411901]
 [0.00507866 0.00166919 0.99325215]]
pi = [0.45024126 0.21331838 0.33644036]
Iter 2: LL=-1250776.96 | Rates: N=0.83054, AF=0.09578, OLD=0.04967, YOUNG=0.03499
A =
[[0.99446648 0.0017031  0.00383043]
 [0.00551032 0.99039356 0.00409612]
 [0.00503167 0.00165277 0.99331556]]
pi = [0.45131324 0.23062787 0.3180589 ]
Iter 3: LL=-1250695.95 | Rates: N=0.83054, AF=0.09575, OLD=0.05416, YOUNG=0.03324
A =
[[0.99447013 0.00172544 0.00380443]
 [0.00558706 0.99033922 0.00407372]
 [0.00499534 0.00163243 0.99337223]]
pi = [0.45130289 0.25482737 0.29386974]
Iter 4: LL=-1250609.48 | Rates: N=0.83054, AF=0.09569, OLD=0.05823, YOUNG=0.03187
A =
[[0.99447371 0.00173561 0.00379068]
 [0.00571155 0.99015604 0.00413241]
 [0.00494468 0.00160665 0.99344867]]
pi = [0.4512516  0.27998906 0.26875933]
Iter 5: LL=-1250552.92 | Rates: N=0.83054, AF=0.09564, OLD=0.06143, YOUNG=0.03108
A =
[[0.99447644 0.00172825 0.00379531]
 [0.0058647  0.98984028 0.00429502]
 [0.00489215 0.00158775 0.9935201 ]]
pi = [0.45119384 0.30162392 0.24718224]
Iter 6: LL=-1250524.50 | Rates: N=0.83053, AF=0.09560, OLD=0.06387, YOUNG=0.03074
A =
[[0.99447825 0.00170502 0.00381673]
 [0.0060212  0.98943495 0.00454385]
 [0.00484834 0.0015796  0.99357206]]
pi = [0.45113864 0.31775958 0.23110178]
Iter 7: LL=-1250509.09 | Rates: N=0.83053, AF=0.09557, OLD=0.06585, YOUNG=0.03066
A =
[[0.99447952 0.00166968 0.00385081]
 [0.00616645 0.98898023 0.00485331]
 [0.0048165  0.00157952 0.99360398]]
pi = [0.45109296 0.32817112 0.22073592]
Iter 8: LL=-1250498.08 | Rates: N=0.83053, AF=0.09554, OLD=0.06760, YOUNG=0.03070
A =
[[0.99448055 0.00162584 0.00389361]
 [0.00629512 0.98850006 0.00520482]
 [0.00479579 0.00158411 0.9936201 ]]
pi = [0.4510598  0.33333103 0.21560917]
Iter 9: LL=-1250488.42 | Rates: N=0.83053, AF=0.09552, OLD=0.06925, YOUNG=0.03081
A =
[[0.99448155 0.00157625 0.00394221]
 [0.00640677 0.98800521 0.00558802]
 [0.00478409 0.001591   0.9936249 ]]
pi = [0.45103949 0.33379026 0.21517024]
Iter 10: LL=-1250479.18 | Rates: N=0.83053, AF=0.09550, OLD=0.07090, YOUNG=0.03094
A =
[[0.9944826  0.00152284 0.00399456]
 [0.00650307 0.98749858 0.00599835]
 [0.00477925 0.00159875 0.993622  ]]
pi = [0.45103137 0.32995274 0.2190159 ]
Iter 11: LL=-1250470.01 | Rates: N=0.83053, AF=0.09548, OLD=0.07259, YOUNG=0.03107
A =
[[0.99448376 0.00146695 0.00404929]
 [0.00658639 0.98697886 0.00643475]
 [0.00477947 0.00160642 0.99361411]]
pi = [0.45103437 0.32204408 0.22692156]
Iter 12: LL=-1250460.77 | Rates: N=0.83053, AF=0.09546, OLD=0.07436, YOUNG=0.03122
A =
[[0.99448505 0.0014095  0.00410545]
 [0.00665916 0.98644257 0.00689827]
 [0.00478336 0.00161341 0.99360324]]
pi = [0.45104731 0.31015245 0.23880024]
Iter 13: LL=-1250451.36 | Rates: N=0.83053, AF=0.09543, OLD=0.07623, YOUNG=0.03136
A =
[[0.99448648 0.00135114 0.00416238]
 [0.00672362 0.98588503 0.00739134]
 [0.00478986 0.00161923 0.99359091]]
pi = [0.45106893 0.29429788 0.25463318]
Iter 14: LL=-1250441.68 | Rates: N=0.83053, AF=0.09541, OLD=0.07823, YOUNG=0.03150
A =
[[0.99448803 0.00129238 0.00421959]
 [0.00678175 0.98530085 0.0079174 ]
 [0.00479823 0.00162351 0.99357826]]
pi = [0.45109788 0.27452264 0.27437948]
Iter 15: LL=-1250431.67 | Rates: N=0.83053, AF=0.09538, OLD=0.08037, YOUNG=0.03164
A =
[[0.99448968 0.00123362 0.0042767 ]
 [0.00683525 0.98468412 0.00848062]
 [0.00480789 0.00162594 0.99356617]]
pi = [0.4511326 0.2510035 0.2978639]
Final Global Rates (lambdas): [0.83052709 0.09538249 0.08036749 0.03164406]
Final transition matrix A:
[[0.99448968 0.00123362 0.0042767 ]
 [0.00683525 0.98468412 0.00848062]
 [0.00480789 0.00162594 0.99356617]]
Final initial distribution pi:
[0.4511326 0.2510035 0.2978639]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.2705,0.0691,0.1101,8056673.0,21724327.0,108524286.0
Archaic_young,0.7732,0.9423,0.8494,380984832.0,111765168.0,23321928.0
Modern,0.0000,0.0000,0.0000,0.0,477469000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         473456          304           2628
Archaic_old       992         8063         107740
Archaic_young    3021        21414         382382

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3429  0.0165  0.0314
Archaic_young     0.7822  0.9859  0.8723

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         465700           46           3021
Archaic_old      1661         1855         109397
Archaic_young    3454         3515         411351

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1470630.02 | Rates: N=0.83202, AF=0.09773, OLD=0.05027, YOUNG=0.04054
A =
[[0.99390691 0.00178352 0.00430958]
 [0.00591335 0.98922258 0.00486407]
 [0.00540313 0.00184114 0.99275574]]
pi = [0.49712644 0.18541076 0.3174628 ]
Iter 2: LL=-1259775.78 | Rates: N=0.83221, AF=0.09776, OLD=0.05491, YOUNG=0.03830
A =
[[0.99394201 0.0017999  0.00425809]
 [0.00596378 0.98923103 0.00480519]
 [0.00533011 0.00181985 0.99285005]]
pi = [0.49969246 0.19158516 0.30872238]
Iter 3: LL=-1259654.06 | Rates: N=0.83221, AF=0.09770, OLD=0.06100, YOUNG=0.03602
A =
[[0.99394837 0.00184017 0.00421146]
 [0.00605813 0.98924759 0.00469428]
 [0.00528274 0.00179759 0.99291966]]
pi = [0.49976377 0.19799921 0.30223702]
Iter 4: LL=-1259513.93 | Rates: N=0.83221, AF=0.09760, OLD=0.06645, YOUNG=0.03421
A =
[[0.99395377 0.0018667  0.00417952]
 [0.00622689 0.98908956 0.00468354]
 [0.00521343 0.00176883 0.99301775]]
pi = [0.49978676 0.19505377 0.30515947]
Iter 5: LL=-1259426.17 | Rates: N=0.83221, AF=0.09751, OLD=0.07055, YOUNG=0.03323
A =
[[0.99395723 0.00186901 0.00417376]
 [0.00644977 0.98871995 0.00483028]
 [0.00513868 0.00175191 0.99310941]]
pi = [0.49978603 0.18312988 0.31708409]
Iter 6: LL=-1259386.89 | Rates: N=0.83221, AF=0.09745, OLD=0.07357, YOUNG=0.03285
A =
[[0.99395879 0.00185031 0.0041909 ]
 [0.00668465 0.98820922 0.00510613]
 [0.00507546 0.0017516  0.99317294]]
pi = [0.4997566  0.16797659 0.33226681]
Iter 7: LL=-1259367.16 | Rates: N=0.83221, AF=0.09741, OLD=0.07600, YOUNG=0.03279
A =
[[0.99395941 0.00181664 0.00422395]
 [0.0069061  0.98762481 0.00546909]
 [0.00502887 0.00176273 0.9932084 ]]
pi = [0.49971902 0.15370697 0.34657401]
Iter 8: LL=-1259353.11 | Rates: N=0.83220, AF=0.09738, OLD=0.07814, YOUNG=0.03286
A =
[[0.99395974 0.00177308 0.00426718]
 [0.00710451 0.98700446 0.00589102]
 [0.00499768 0.00178023 0.99322209]]
pi = [0.49968782 0.14176553 0.35854665]
Iter 9: LL=-1259340.70 | Rates: N=0.83220, AF=0.09735, OLD=0.08019, YOUNG=0.03299
A =
[[0.99396006 0.00172327 0.00431667]
 [0.00727852 0.9863643  0.00635717]
 [0.00497889 0.00180107 0.99322004]]
pi = [0.49966606 0.13213565 0.3681983 ]
Iter 10: LL=-1259328.88 | Rates: N=0.83220, AF=0.09732, OLD=0.08222, YOUNG=0.03313
A =
[[0.99396048 0.00166968 0.00436985]
 [0.00743033 0.98570893 0.00686074]
 [0.00496949 0.00182356 0.99320695]]
pi = [0.49965197 0.12433054 0.37601749]
Iter 11: LL=-1259317.34 | Rates: N=0.83220, AF=0.09730, OLD=0.08429, YOUNG=0.03328
A =
[[0.993961   0.00161402 0.00442497]
 [0.00756339 0.98503763 0.00739898]
 [0.00496695 0.00184672 0.99318632]]
pi = [0.49964318 0.11783763 0.3825192 ]
Iter 12: LL=-1259305.98 | Rates: N=0.83220, AF=0.09728, OLD=0.08641, YOUNG=0.03343
A =
[[0.99396164 0.0015575  0.00448086]
 [0.00768134 0.98434768 0.00797099]
 [0.0049693  0.00186991 0.9931608 ]]
pi = [0.49963785 0.11224785 0.3881143 ]
Iter 13: LL=-1259294.74 | Rates: N=0.83220, AF=0.09726, OLD=0.08860, YOUNG=0.03357
A =
[[0.99396237 0.00150096 0.00453667]
 [0.00778756 0.98363583 0.00857662]
 [0.00497501 0.00189265 0.99313234]]
pi = [0.49963477 0.10726329 0.39310194]
Iter 14: LL=-1259283.62 | Rates: N=0.83220, AF=0.09723, OLD=0.09087, YOUNG=0.03370
A =
[[0.99396318 0.00144504 0.00459178]
 [0.00788502 0.98289899 0.00921599]
 [0.00498296 0.0019146  0.99310244]]
pi = [0.49963316 0.10267222 0.39769462]
Iter 15: LL=-1259272.62 | Rates: N=0.83220, AF=0.09721, OLD=0.09322, YOUNG=0.03384
A =
[[0.99396406 0.00139017 0.00464577]
 [0.00797631 0.9821344  0.00988929]
 [0.0049923  0.00193547 0.99307223]]
pi = [0.49963251 0.09832251 0.40204499]
Final Global Rates (lambdas): [0.83219741 0.09721215 0.09322458 0.03384024]
Final transition matrix A:
[[0.99396406 0.00139017 0.00464577]
 [0.00797631 0.9821344  0.00988929]
 [0.0049923  0.00193547 0.99307223]]
Final initial distribution pi:
[0.49963251 0.09832251 0.40204499]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.2812,0.0808,0.1255,9107977.0,23287023.0,103642329.0
Archaic_young,0.7854,0.9377,0.8548,389676511.0,106485489.0,25872117.0
Modern,0.0000,0.0000,0.0000,0.0,471443000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         465873           69           2825
Archaic_old      1743         9086         102084
Archaic_young    3827        23240         391253

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3925  0.0075  0.0148
Archaic_young     0.7458  0.9889  0.8503

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         462125            9           3410
Archaic_old      1839          994         129359
Archaic_young    4105         1534         396625

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1478529.50 | Rates: N=0.82631, AF=0.09794, OLD=0.05763, YOUNG=0.04747
A =
[[0.99337159 0.00191082 0.00471759]
 [0.00627352 0.98825099 0.00547549]
 [0.00586372 0.00207608 0.9920602 ]]
pi = [0.5522287  0.17171157 0.27605973]
Iter 2: LL=-1271422.11 | Rates: N=0.82649, AF=0.09801, OLD=0.06268, YOUNG=0.04503
A =
[[0.99344108 0.00191456 0.00464436]
 [0.00628141 0.98828175 0.00543684]
 [0.00576461 0.00206288 0.9921725 ]]
pi = [0.55408868 0.18919767 0.25671365]
Iter 3: LL=-1271291.84 | Rates: N=0.82649, AF=0.09793, OLD=0.06981, YOUNG=0.04236
A =
[[0.9934506  0.0019542  0.0045952 ]
 [0.00636087 0.98826936 0.00536977]
 [0.00571872 0.00205658 0.99222471]]
pi = [0.55388628 0.21845355 0.22766017]
Iter 4: LL=-1271117.85 | Rates: N=0.82649, AF=0.09778, OLD=0.07682, YOUNG=0.04005
A =
[[0.99345643 0.00198363 0.00455994]
 [0.00653084 0.9880148  0.00545437]
 [0.00564678 0.00204778 0.99230544]]
pi = [0.55356251 0.25452666 0.19191082]
Iter 5: LL=-1270987.90 | Rates: N=0.82649, AF=0.09766, OLD=0.08252, YOUNG=0.03868
A =
[[0.99345847 0.00198677 0.00455476]
 [0.00678343 0.98743886 0.00577771]
 [0.0055633  0.00205399 0.99238271]]
pi = [0.55323886 0.28865639 0.15810475]
Iter 6: LL=-1270919.66 | Rates: N=0.82649, AF=0.09757, OLD=0.08699, YOUNG=0.03811
A =
[[0.99345829 0.00196554 0.00457617]
 [0.00706552 0.9866246  0.00630988]
 [0.00549005 0.00208211 0.99242785]]
pi = [0.5529913  0.31527525 0.13173345]
Iter 7: LL=-1270880.44 | Rates: N=0.82649, AF=0.09751, OLD=0.09076, YOUNG=0.03797
A =
[[0.99345768 0.00192667 0.00461565]
 [0.00734094 0.98566482 0.00699425]
 [0.00543506 0.00212481 0.99244013]]
pi = [0.55282397 0.33389128 0.11328475]
Iter 8: LL=-1270850.22 | Rates: N=0.82649, AF=0.09746, OLD=0.09424, YOUNG=0.03803
A =
[[0.99345729 0.00187613 0.00466658]
 [0.00759569 0.98461427 0.00779004]
 [0.00539776 0.00217396 0.99242828]]
pi = [0.55271237 0.34622738 0.10106025]
Iter 9: LL=-1270822.79 | Rates: N=0.82648, AF=0.09742, OLD=0.09765, YOUNG=0.03818
A =
[[0.99345724 0.00181831 0.00472445]
 [0.00782668 0.98349996 0.00867336]
 [0.00537483 0.0022246  0.99240057]]
pi = [0.55263358 0.35411177 0.09325466]
Iter 10: LL=-1270796.63 | Rates: N=0.82648, AF=0.09737, OLD=0.10111, YOUNG=0.03835
A =
[[0.99345753 0.00175622 0.00478625]
 [0.00803527 0.98233404 0.00963068]
 [0.00536276 0.00227403 0.99236321]]
pi = [0.55257309 0.3588872  0.08853971]
Iter 11: LL=-1270771.41 | Rates: N=0.82648, AF=0.09733, OLD=0.10466, YOUNG=0.03854
A =
[[0.99345811 0.001692   0.00484989]
 [0.00822454 0.98112159 0.01065386]
 [0.00535853 0.00232075 0.99232072]]
pi = [0.55252286 0.36144953 0.08602761]
Iter 12: LL=-1270747.09 | Rates: N=0.82648, AF=0.09729, OLD=0.10833, YOUNG=0.03873
A =
[[0.99345894 0.00162717 0.00491389]
 [0.008398   0.97986478 0.01173722]
 [0.00535978 0.00236388 0.99227635]]
pi = [0.55247867 0.36239643 0.0851249 ]
Iter 13: LL=-1270723.74 | Rates: N=0.82647, AF=0.09726, OLD=0.11213, YOUNG=0.03891
A =
[[0.99345996 0.00156291 0.00497713]
 [0.00855905 0.97856485 0.01287609]
 [0.00536472 0.00240281 0.99223247]]
pi = [0.55243843 0.36214455 0.08541702]
Iter 14: LL=-1270701.40 | Rates: N=0.82647, AF=0.09722, OLD=0.11604, YOUNG=0.03910
A =
[[0.99346113 0.0015001  0.00503878]
 [0.00871089 0.97722292 0.01406619]
 [0.00537202 0.00243721 0.99219078]]
pi = [0.55240122 0.36100112 0.08659766]
Iter 15: LL=-1270680.13 | Rates: N=0.82646, AF=0.09718, OLD=0.12008, YOUNG=0.03928
A =
[[0.99346237 0.00143943 0.0050982 ]
 [0.00885648 0.97584016 0.01530336]
 [0.00538068 0.00246687 0.99215245]]
pi = [0.55236669 0.35920282 0.08843049]
Final Global Rates (lambdas): [0.82646476 0.09718418 0.1200795  0.03928289]
Final transition matrix A:
[[0.99346237 0.00143943 0.0050982 ]
 [0.00885648 0.97584016 0.01530336]
 [0.00538068 0.00246687 0.99215245]]
Final initial distribution pi:
[0.55236669 0.35920282 0.08843049]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.3359,0.0610,0.1033,8051152.0,15914848.0,123912858.0
Archaic_young,0.7498,0.9535,0.8395,380688537.0,127047463.0,18553987.0
Modern,0.0000,0.0000,0.0000,0.0,468298000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         462225          277           3042
Archaic_old      1850         8038         122304
Archaic_young    4223        15651         382390

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2831  0.0061  0.0118
Archaic_young     0.7597  0.9868  0.8585

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         479533           19           3470
Archaic_old      1952          721         117531
Archaic_young    4689         1824         390261

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1502498.72 | Rates: N=0.83584, AF=0.09791, OLD=0.06566, YOUNG=0.05416
A =
[[0.9932187  0.00193619 0.0048451 ]
 [0.00687134 0.98703984 0.00608882]
 [0.00647611 0.0022972  0.99122669]]
pi = [0.34420779 0.23354928 0.42224293]
Iter 2: LL=-1286936.49 | Rates: N=0.83604, AF=0.09791, OLD=0.07287, YOUNG=0.05094
A =
[[0.99332247 0.00194592 0.00473162]
 [0.00691346 0.98707079 0.00601576]
 [0.00631091 0.00227017 0.99141892]]
pi = [0.33968606 0.23071712 0.42959682]
Iter 3: LL=-1286722.25 | Rates: N=0.83603, AF=0.09782, OLD=0.08293, YOUNG=0.04726
A =
[[0.9933389  0.00200527 0.00465582]
 [0.00710909 0.9870202  0.0058707 ]
 [0.0062104  0.00223554 0.99155406]]
pi = [0.33956151 0.22402739 0.4364111 ]
Iter 4: LL=-1286448.49 | Rates: N=0.83603, AF=0.09768, OLD=0.09205, YOUNG=0.04442
A =
[[0.99334765 0.00204704 0.00460531]
 [0.00744402 0.98664296 0.00591302]
 [0.00607845 0.00219522 0.99172633]]
pi = [0.3396721  0.21231673 0.44801117]
Iter 5: LL=-1286282.54 | Rates: N=0.83602, AF=0.09755, OLD=0.09880, YOUNG=0.04305
A =
[[0.99335118 0.00205286 0.00459596]
 [0.00783947 0.98593094 0.00622959]
 [0.00595509 0.00218734 0.99185757]]
pi = [0.33978197 0.19759718 0.46262085]
Iter 6: LL=-1286212.32 | Rates: N=0.83601, AF=0.09746, OLD=0.10378, YOUNG=0.04262
A =
[[0.99335195 0.00202797 0.00462008]
 [0.0082153  0.98503042 0.00675428]
 [0.00586515 0.00221222 0.99192263]]
pi = [0.33984865 0.18257611 0.47757524]
Iter 7: LL=-1286175.90 | Rates: N=0.83600, AF=0.09739, OLD=0.10786, YOUNG=0.04262
A =
[[0.99335188 0.00198296 0.00466515]
 [0.0085434  0.9840432  0.0074134 ]
 [0.00580786 0.00225481 0.99193733]]
pi = [0.3398817  0.16840655 0.49171175]
Iter 8: LL=-1286148.68 | Rates: N=0.83600, AF=0.09733, OLD=0.11156, YOUNG=0.04277
A =
[[0.9933518  0.00192672 0.00472148]
 [0.00882255 0.98301351 0.00816394]
 [0.00577511 0.0023048  0.99192009]]
pi = [0.33989762 0.15526159 0.50484079]
Iter 9: LL=-1286124.43 | Rates: N=0.83600, AF=0.09727, OLD=0.11516, YOUNG=0.04298
A =
[[0.99335192 0.00186514 0.00478294]
 [0.0090608  0.98195316 0.00898604]
 [0.00575916 0.00235706 0.99188378]]
pi = [0.3399059  0.14300326 0.51709084]
Iter 10: LL=-1286101.57 | Rates: N=0.83599, AF=0.09722, OLD=0.11878, YOUNG=0.04320
A =
[[0.99335223 0.00180186 0.0048459 ]
 [0.00926827 0.98085966 0.00987207]
 [0.00575419 0.0024091  0.99183671]]
pi = [0.33991068 0.13147672 0.5286126 ]
Iter 11: LL=-1286079.52 | Rates: N=0.83599, AF=0.09717, OLD=0.12251, YOUNG=0.04342
A =
[[0.99335269 0.00173901 0.00490829]
 [0.00945464 0.97972516 0.0108202 ]
 [0.00575608 0.00245965 0.99178427]]
pi = [0.33991349 0.12058838 0.53949813]
Iter 12: LL=-1286058.02 | Rates: N=0.83598, AF=0.09712, OLD=0.12639, YOUNG=0.04364
A =
[[0.99335323 0.00167779 0.00496898]
 [0.00962847 0.97854006 0.01183147]
 [0.00576202 0.00250803 0.99172995]]
pi = [0.3399148  0.11030384 0.54978135]
Iter 13: LL=-1286036.85 | Rates: N=0.83597, AF=0.09706, OLD=0.13045, YOUNG=0.04385
A =
[[0.99335377 0.00161882 0.00502741]
 [0.00979705 0.97729437 0.01290857]
 [0.00577011 0.0025538  0.99167609]]
pi = [0.33991474 0.10062773 0.55945754]
Iter 14: LL=-1286015.88 | Rates: N=0.83597, AF=0.09700, OLD=0.13472, YOUNG=0.04405
A =
[[0.99335425 0.00156236 0.00508339]
 [0.00996648 0.97597843 0.01405509]
 [0.00577912 0.00259672 0.99162416]]
pi = [0.33991338 0.09158551 0.56850111]
Iter 15: LL=-1285995.02 | Rates: N=0.83596, AF=0.09693, OLD=0.13923, YOUNG=0.04426
A =
[[0.9933546  0.00150854 0.00513686]
 [0.01014195 0.97458297 0.01527508]
 [0.00578825 0.00263662 0.99157513]]
pi = [0.33991092 0.08320816 0.57688092]
Final Global Rates (lambdas): [0.83596164 0.09693267 0.13923139 0.04426014]
Final transition matrix A:
[[0.9933546  0.00150854 0.00513686]
 [0.01014195 0.97458297 0.01527508]
 [0.00578825 0.00263662 0.99157513]]
Final initial distribution pi:
[0.33991092 0.08320816 0.57688092]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.2729,0.0716,0.1134,8584479.0,22869521.0,111351278.0
Archaic_young,0.7627,0.9344,0.8398,367761460.0,114450540.0,25805496.0
Modern,0.0000,0.0000,0.0000,0.0,486334000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         479610          334           3078
Archaic_old      1995         8578         109631
Archaic_young    4729        22542         369503

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2555  0.3034  0.2774
Archaic_young     0.7741  0.7339  0.7535

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         484181          734           2208
Archaic_old      1230        35576          80896
Archaic_young    2803       103006         289366

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1471117.25 | Rates: N=0.83633, AF=0.09641, OLD=0.05134, YOUNG=0.03385
A =
[[0.99486379 0.00218439 0.00295183]
 [0.0050913  0.99227555 0.00263316]
 [0.00498568 0.00190881 0.99310551]]
pi = [0.15517858 0.38745404 0.45736738]
Iter 2: LL=-1255822.03 | Rates: N=0.83650, AF=0.09616, OLD=0.05457, YOUNG=0.03204
A =
[[0.99487669 0.00216386 0.00295945]
 [0.00522116 0.99206971 0.00270913]
 [0.00485804 0.0018526  0.99328936]]
pi = [0.14804264 0.40838813 0.44356923]
Iter 3: LL=-1255757.06 | Rates: N=0.83650, AF=0.09613, OLD=0.05729, YOUNG=0.03094
A =
[[0.99487908 0.00213663 0.00298429]
 [0.00537985 0.99178466 0.00283549]
 [0.00476148 0.00182073 0.99341779]]
pi = [0.14775435 0.42615616 0.42608949]
Iter 4: LL=-1255721.80 | Rates: N=0.83650, AF=0.09611, OLD=0.05940, YOUNG=0.03041
A =
[[0.99488014 0.00209822 0.00302164]
 [0.00553022 0.99145418 0.0030156 ]
 [0.00468568 0.00181472 0.9934996 ]]
pi = [0.14767802 0.44024912 0.41207286]
Iter 5: LL=-1255703.17 | Rates: N=0.83650, AF=0.09609, OLD=0.06106, YOUNG=0.03023
A =
[[0.99488066 0.00205119 0.00306815]
 [0.00566338 0.99109739 0.00323922]
 [0.00463124 0.00182694 0.99354182]]
pi = [0.14760536 0.4497669  0.40262774]
Iter 6: LL=-1255690.71 | Rates: N=0.83650, AF=0.09608, OLD=0.06248, YOUNG=0.03024
A =
[[0.99488095 0.00199822 0.00312083]
 [0.00577849 0.99072507 0.00349644]
 [0.00459456 0.00184898 0.99355647]]
pi = [0.14753618 0.45479874 0.39766508]
Iter 7: LL=-1255680.21 | Rates: N=0.83650, AF=0.09607, OLD=0.06377, YOUNG=0.03033
A =
[[0.99488117 0.00194154 0.00317729]
 [0.00587717 0.99034231 0.00378052]
 [0.00457161 0.00187535 0.99355304]]
pi = [0.14747314 0.45573095 0.39679591]
Iter 8: LL=-1255670.35 | Rates: N=0.83650, AF=0.09606, OLD=0.06502, YOUNG=0.03046
A =
[[0.99488139 0.0018828  0.0032358 ]
 [0.00596153 0.98995084 0.00408763]
 [0.00455905 0.00190302 0.99353793]]
pi = [0.1474171 0.4529586 0.3996243]
Iter 9: LL=-1255660.77 | Rates: N=0.83650, AF=0.09605, OLD=0.06626, YOUNG=0.03060
A =
[[0.99488163 0.00182318 0.00329518]
 [0.00603354 0.98955072 0.00441574]
 [0.00455428 0.00193038 0.99351534]]
pi = [0.14736826 0.44683339 0.40579835]
Iter 10: LL=-1255651.36 | Rates: N=0.83650, AF=0.09604, OLD=0.06752, YOUNG=0.03074
A =
[[0.9948819  0.00176349 0.00335461]
 [0.00609493 0.98914126 0.00476381]
 [0.00455533 0.00195661 0.99348806]]
pi = [0.14732666 0.43768117 0.41499216]
Iter 11: LL=-1255642.10 | Rates: N=0.83650, AF=0.09603, OLD=0.06880, YOUNG=0.03088
A =
[[0.99488219 0.0017043  0.00341351]
 [0.00614713 0.98872158 0.00513129]
 [0.00456072 0.00198126 0.99345802]]
pi = [0.14729231 0.42582793 0.42687976]
Iter 12: LL=-1255632.97 | Rates: N=0.83650, AF=0.09602, OLD=0.07012, YOUNG=0.03102
A =
[[0.9948825  0.00164601 0.0034715 ]
 [0.00619137 0.9882908  0.00551783]
 [0.00456931 0.0020041  0.99342659]]
pi = [0.14726516 0.41161827 0.44111656]
Iter 13: LL=-1255624.01 | Rates: N=0.83650, AF=0.09601, OLD=0.07147, YOUNG=0.03116
A =
[[0.99488282 0.0015889  0.00352829]
 [0.00622868 0.98784819 0.00592313]
 [0.0045802  0.00202504 0.99339476]]
pi = [0.14724514 0.39542373 0.45733113]
Iter 14: LL=-1255615.20 | Rates: N=0.83650, AF=0.09600, OLD=0.07286, YOUNG=0.03130
A =
[[0.99488314 0.00153317 0.00358368]
 [0.00625997 0.98739312 0.00634691]
 [0.00459271 0.00204403 0.99336326]]
pi = [0.14723204 0.37764128 0.47512668]
Iter 15: LL=-1255606.58 | Rates: N=0.83650, AF=0.09599, OLD=0.07429, YOUNG=0.03143
A =
[[0.99488347 0.00147897 0.00363755]
 [0.00628604 0.98692511 0.00678884]
 [0.00460629 0.0020611  0.9933326 ]]
pi = [0.14722552 0.35868375 0.49409073]
Final Global Rates (lambdas): [0.83649809 0.09598878 0.07428644 0.03142952]
Final transition matrix A:
[[0.99488347 0.00147897 0.00363755]
 [0.00628604 0.98692511 0.00678884]
 [0.00460629 0.0020611  0.9933326 ]]
Final initial distribution pi:
[0.14722552 0.35868375 0.49409073]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.2604,0.1201,0.1644,14083003.0,39990997.0,103215413.0
Archaic_young,0.7683,0.8953,0.8270,351784086.0,106098914.0,41128290.0
Modern,0.0000,0.0000,0.0000,0.0,488043000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         484140          491           2492
Archaic_old      1202        14099         102401
Archaic_young    2701        39484         352990

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3212  0.2162  0.2584
Archaic_young     0.8058  0.8775  0.8401

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         484392          467           2643
Archaic_old      1368        22779          81534
Archaic_young    3034        47674         356109

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1474816.66 | Rates: N=0.83699, AF=0.09771, OLD=0.05299, YOUNG=0.03544
A =
[[0.99439079 0.00210111 0.0035081 ]
 [0.00602836 0.99040401 0.00356763]
 [0.00519628 0.0018882  0.99291552]]
pi = [0.5526359  0.16277249 0.28459161]
Iter 2: LL=-1259521.85 | Rates: N=0.83717, AF=0.09761, OLD=0.05748, YOUNG=0.03315
A =
[[0.99441867 0.00209022 0.00349111]
 [0.00623517 0.99020421 0.00356062]
 [0.00505036 0.00183076 0.99311887]]
pi = [0.55565701 0.14179229 0.3025507 ]
Iter 3: LL=-1259418.08 | Rates: N=0.83717, AF=0.09757, OLD=0.06143, YOUNG=0.03174
A =
[[0.99442102 0.00207955 0.00349944]
 [0.00648806 0.98991466 0.00359728]
 [0.00494542 0.0017933  0.99326128]]
pi = [0.55564159 0.12514664 0.31921176]
Iter 4: LL=-1259362.78 | Rates: N=0.83717, AF=0.09753, OLD=0.06435, YOUNG=0.03107
A =
[[0.99442118 0.00205046 0.00352835]
 [0.00674261 0.98954137 0.00371602]
 [0.0048599  0.00177562 0.99336448]]
pi = [0.55558753 0.11311236 0.33130011]
Iter 5: LL=-1259338.07 | Rates: N=0.83717, AF=0.09750, OLD=0.06653, YOUNG=0.03085
A =
[[0.99442089 0.00200685 0.00357227]
 [0.00697711 0.98912281 0.00390008]
 [0.00479799 0.00177399 0.99342802]]
pi = [0.55556087 0.10471714 0.33972199]
Iter 6: LL=-1259324.57 | Rates: N=0.83718, AF=0.09747, OLD=0.06829, YOUNG=0.03086
A =
[[0.99442055 0.00195375 0.0036257 ]
 [0.00718598 0.98868478 0.00412924]
 [0.00475681 0.00178128 0.99346192]]
pi = [0.5555477  0.09865332 0.34579898]
Iter 7: LL=-1259314.44 | Rates: N=0.83718, AF=0.09746, OLD=0.06985, YOUNG=0.03097
A =
[[0.99442029 0.00189514 0.00368456]
 [0.00737036 0.98823973 0.00438991]
 [0.00473171 0.00179266 0.99347563]]
pi = [0.55554055 0.09407973 0.35037972]
Iter 8: LL=-1259305.41 | Rates: N=0.83718, AF=0.09744, OLD=0.07133, YOUNG=0.03112
A =
[[0.99442014 0.00183373 0.00374612]
 [0.00753357 0.98779174 0.0046747 ]
 [0.00471851 0.00180563 0.99347586]]
pi = [0.55553688 0.09052647 0.35393665]
Iter 9: LL=-1259296.86 | Rates: N=0.83718, AF=0.09743, OLD=0.07279, YOUNG=0.03128
A =
[[0.99442008 0.00177127 0.00380865]
 [0.00767937 0.98734066 0.00497996]
 [0.0047139  0.00181893 0.99346716]]
pi = [0.55553566 0.08771809 0.35674626]
Iter 10: LL=-1259288.60 | Rates: N=0.83718, AF=0.09741, OLD=0.07425, YOUNG=0.03144
A =
[[0.99442009 0.00170888 0.00387103]
 [0.00781135 0.98688456 0.00530409]
 [0.00471543 0.00183196 0.99345261]]
pi = [0.55553631 0.08547316 0.35899053]
Iter 11: LL=-1259280.56 | Rates: N=0.83718, AF=0.09740, OLD=0.07573, YOUNG=0.03160
A =
[[0.99442014 0.0016473  0.00393256]
 [0.00793265 0.98642098 0.00564638]
 [0.00472126 0.0018444  0.99343434]]
pi = [0.55553845 0.08365954 0.36080201]
Iter 12: LL=-1259272.72 | Rates: N=0.83718, AF=0.09739, OLD=0.07724, YOUNG=0.03175
A =
[[0.99442023 0.00158701 0.00399276]
 [0.0080459  0.98594756 0.00600654]
 [0.00473004 0.00185609 0.99341387]]
pi = [0.55554177 0.08217595 0.36228228]
Iter 13: LL=-1259265.06 | Rates: N=0.83718, AF=0.09738, OLD=0.07878, YOUNG=0.03190
A =
[[0.99442034 0.00152834 0.00405132]
 [0.00815331 0.98546226 0.00638443]
 [0.00474078 0.00186695 0.99339227]]
pi = [0.55554609 0.08094405 0.36350987]
Iter 14: LL=-1259257.57 | Rates: N=0.83718, AF=0.09737, OLD=0.08036, YOUNG=0.03205
A =
[[0.99442046 0.00147149 0.00410805]
 [0.00825666 0.98496341 0.00677993]
 [0.00475277 0.00187694 0.99337029]]
pi = [0.55555122 0.07990406 0.36454471]
Iter 15: LL=-1259250.28 | Rates: N=0.83718, AF=0.09736, OLD=0.08197, YOUNG=0.03219
A =
[[0.99442058 0.0014166  0.00416281]
 [0.00835742 0.98444966 0.00719292]
 [0.00476546 0.00188606 0.99334848]]
pi = [0.55555704 0.07901147 0.36543149]
Final Global Rates (lambdas): [0.83717595 0.09736006 0.08196997 0.03218796]
Final transition matrix A:
[[0.99442058 0.0014166  0.00416281]
 [0.00835742 0.98444966 0.00719292]
 [0.00476546 0.00188606 0.99334848]]
Final initial distribution pi:
[0.55555704 0.07901147 0.36543149]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3381  0.1396  0.1976   14712550.0   28801450.0  90649966.0
Archaic_young     0.7997  0.9255  0.8580  374193954.0   93706046.0  30112806.0
Modern            0.0000  0.0000  0.0000          0.0  488586000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         484346          466           2690
Archaic_old      1315        14730          89636
Archaic_young    2925        28318         375574

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3591  0.1397  0.2012
Archaic_young     0.7772  0.9208  0.8429

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         454240          287           3118
Archaic_old      1755        17258         105022
Archaic_young    3530        30594         384196

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 10
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1463745.05 | Rates: N=0.82279, AF=0.09779, OLD=0.05746, YOUNG=0.03946
A =
[[0.99360211 0.00225475 0.00414315]
 [0.0061784  0.9894908  0.0043308 ]
 [0.00528301 0.00204244 0.99267455]]
pi = [0.49770231 0.17810651 0.32419118]
Iter 2: LL=-1259929.95 | Rates: N=0.82297, AF=0.09778, OLD=0.06295, YOUNG=0.03665
A =
[[0.99366081 0.00224994 0.00408925]
 [0.00629094 0.98941327 0.00429579]
 [0.00515097 0.00200073 0.9928483 ]]
pi = [0.50181096 0.14897852 0.34921052]
Iter 3: LL=-1259781.20 | Rates: N=0.82297, AF=0.09773, OLD=0.06790, YOUNG=0.03474
A =
[[0.99366613 0.00225492 0.00407895]
 [0.00647283 0.9892029  0.00432426]
 [0.00507177 0.00198121 0.99294702]]
pi = [0.50189777 0.11420557 0.38389666]
Iter 4: LL=-1259696.98 | Rates: N=0.82297, AF=0.09768, OLD=0.07148, YOUNG=0.03374
A =
[[0.99366746 0.00223689 0.00409566]
 [0.00666868 0.98884756 0.00448376]
 [0.00500422 0.00198465 0.99301113]]
pi = [0.5018045  0.07938979 0.41880571]
Iter 5: LL=-1259661.44 | Rates: N=0.82297, AF=0.09764, OLD=0.07403, YOUNG=0.03334
A =
[[0.99366783 0.00220095 0.00413123]
 [0.00685005 0.98840418 0.00474578]
 [0.00495496 0.00200816 0.99303689]]
pi = [0.50170749 0.05089418 0.44739833]
Iter 6: LL=-1259644.09 | Rates: N=0.82297, AF=0.09762, OLD=0.07600, YOUNG=0.03325
A =
[[0.99366792 0.00215387 0.00417821]
 [0.00700866 0.98791629 0.00507505]
 [0.00492273 0.00204229 0.99303498]]
pi = [0.50163787 0.03066654 0.46769559]
Iter 7: LL=-1259631.88 | Rates: N=0.82297, AF=0.09760, OLD=0.07769, YOUNG=0.03330
A =
[[0.99366801 0.00210059 0.00423139]
 [0.0071448  0.9874069  0.00544829]
 [0.00490382 0.00208038 0.9930158 ]]
pi = [0.50159676 0.0176416  0.48076165]
Iter 8: LL=-1259621.21 | Rates: N=0.82296, AF=0.09758, OLD=0.07927, YOUNG=0.03341
A =
[[0.99366818 0.00204424 0.00428758]
 [0.00726138 0.98688577 0.00585286]
 [0.00489471 0.00211905 0.99298624]]
pi = [0.50157558 0.00979909 0.48862532]
Iter 9: LL=-1259611.18 | Rates: N=0.82296, AF=0.09757, OLD=0.08080, YOUNG=0.03353
A =
[[0.99366843 0.0019867  0.00434488]
 [0.0073618  0.98635582 0.00628238]
 [0.00489262 0.00215679 0.99295059]]
pi = [0.50156647 0.00529609 0.49313744]
Iter 10: LL=-1259601.56 | Rates: N=0.82296, AF=0.09756, OLD=0.08233, YOUNG=0.03366
A =
[[0.99366876 0.00192908 0.00440216]
 [0.00744931 0.98581697 0.00673371]
 [0.00489547 0.00219296 0.99291158]]
pi = [0.50156446 0.00279971 0.49563583]
Iter 11: LL=-1259592.26 | Rates: N=0.82296, AF=0.09754, OLD=0.08388, YOUNG=0.03379
A =
[[0.99366916 0.00187207 0.00445877]
 [0.00752677 0.98526798 0.00720524]
 [0.00490172 0.00222729 0.99287099]]
pi = [0.5015668  0.00145289 0.49698031]
Iter 12: LL=-1259583.23 | Rates: N=0.82296, AF=0.09753, OLD=0.08545, YOUNG=0.03392
A =
[[0.99366963 0.00181607 0.0045143 ]
 [0.0075966  0.98470734 0.00769606]
 [0.00491023 0.00225971 0.99283006]]
pi = [0.50157204 0.00074209 0.49768587]
Iter 13: LL=-1259574.46 | Rates: N=0.82296, AF=0.09752, OLD=0.08706, YOUNG=0.03405
A =
[[0.99367015 0.00176132 0.00456853]
 [0.0076608  0.98413362 0.00820557]
 [0.00492017 0.0022902  0.99278964]]
pi = [5.01579375e-01 3.73817514e-04 4.98046807e-01]
Iter 14: LL=-1259565.92 | Rates: N=0.82296, AF=0.09750, OLD=0.08870, YOUNG=0.03417
A =
[[0.99367072 0.00170793 0.00462134]
 [0.00772106 0.98354559 0.00873335]
 [0.00493091 0.00231877 0.99275032]]
pi = [5.01588331e-01 1.86014603e-04 4.98225655e-01]
Iter 15: LL=-1259557.60 | Rates: N=0.82296, AF=0.09749, OLD=0.09038, YOUNG=0.03429
A =
[[0.99367134 0.00165597 0.00467268]
 [0.00777876 0.98294216 0.00927907]
 [0.00494201 0.00234545 0.99271254]]
pi = [5.01598592e-01 9.15594167e-05 4.98309849e-01]
Final Global Rates (lambdas): [0.82295843 0.09748874 0.0903817  0.03429127]
Final transition matrix A:
[[0.99367134 0.00165597 0.00467268]
 [0.00777876 0.98294216 0.00927907]
 [0.00494201 0.00234545 0.99271254]]
Final initial distribution pi:
[5.01598592e-01 9.15594167e-05 4.98309849e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4113,0.1511,0.2210,18695919.0,26759081.0,105042979.0
Archaic_young,0.7815,0.9289,0.8488,385983846.0,107922154.0,29564782.0
Modern,0.0000,0.0000,0.0000,0.0,460639000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         454506          101           3038
Archaic_old      2022        18653         103360
Archaic_young    4111        26701         387508

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4567  0.1164  0.1855
Archaic_young     0.7619  0.9480  0.8448

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         463653          200           3204
Archaic_old      2063        15173         113443
Archaic_young    4283        17835         380146

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1484041.31 | Rates: N=0.83045, AF=0.09772, OLD=0.06382, YOUNG=0.04508
A =
[[0.99314827 0.00234559 0.00450614]
 [0.00684318 0.98817949 0.00497732]
 [0.00594783 0.00225419 0.99179798]]
pi = [0.5946443  0.16975032 0.23560538]
Iter 2: LL=-1273760.02 | Rates: N=0.83066, AF=0.09773, OLD=0.07016, YOUNG=0.04192
A =
[[0.99322532 0.00234584 0.00442884]
 [0.00699127 0.98802888 0.00497985]
 [0.00577891 0.00219627 0.99202481]]
pi = [0.60065097 0.19078559 0.20856344]
Iter 3: LL=-1273587.85 | Rates: N=0.83065, AF=0.09768, OLD=0.07631, YOUNG=0.03969
A =
[[0.9932341  0.00236292 0.00440298]
 [0.00724692 0.98770201 0.00505107]
 [0.00566987 0.00216366 0.99216647]]
pi = [0.60060782 0.21804983 0.18134234]
Iter 4: LL=-1273478.41 | Rates: N=0.83064, AF=0.09761, OLD=0.08107, YOUNG=0.03848
A =
[[0.9932375  0.00235171 0.00441079]
 [0.0075439  0.98716826 0.00528784]
 [0.00556949 0.00215879 0.99227172]]
pi = [0.60044261 0.23998828 0.1595691 ]
Iter 5: LL=-1273426.35 | Rates: N=0.83064, AF=0.09755, OLD=0.08469, YOUNG=0.03800
A =
[[0.99323898 0.00231487 0.00444615]
 [0.00783899 0.98649674 0.00566427]
 [0.00549143 0.00218036 0.99232821]]
pi = [0.60032325 0.25476595 0.1449108 ]
Iter 6: LL=-1273398.12 | Rates: N=0.83063, AF=0.09750, OLD=0.08765, YOUNG=0.03790
A =
[[0.99323965 0.00225999 0.00450036]
 [0.00811286 0.98574902 0.00613812]
 [0.00543711 0.00221703 0.99234585]]
pi = [0.60023747 0.26410485 0.13565768]
Iter 7: LL=-1273377.14 | Rates: N=0.83063, AF=0.09747, OLD=0.09031, YOUNG=0.03798
A =
[[0.99324013 0.00219376 0.00456611]
 [0.00836064 0.98496015 0.00667922]
 [0.00540246 0.00225988 0.99233765]]
pi = [0.60017179 0.26984139 0.12998682]
Iter 8: LL=-1273358.42 | Rates: N=0.83063, AF=0.09743, OLD=0.09286, YOUNG=0.03812
A =
[[0.99324063 0.00212105 0.00463832]
 [0.00858356 0.9841462  0.00727023]
 [0.0053827  0.00230391 0.99231339]]
pi = [0.60012068 0.2731828  0.12669652]
Iter 9: LL=-1273340.72 | Rates: N=0.83063, AF=0.09740, OLD=0.09539, YOUNG=0.03830
A =
[[0.99324124 0.00204514 0.00471361]
 [0.00878496 0.98331319 0.00790184]
 [0.00537379 0.00234655 0.99227966]]
pi = [0.60008199 0.27483668 0.12508133]
Iter 10: LL=-1273323.72 | Rates: N=0.83062, AF=0.09737, OLD=0.09795, YOUNG=0.03848
A =
[[0.99324196 0.00196826 0.00478978]
 [0.0089685  0.98246264 0.00856886]
 [0.00537268 0.00238646 0.99224087]]
pi = [0.60005443 0.27521057 0.124735  ]
Iter 11: LL=-1273307.35 | Rates: N=0.83062, AF=0.09735, OLD=0.10056, YOUNG=0.03866
A =
[[0.99324275 0.00189191 0.00486534]
 [0.00913748 0.9815945  0.00926802]
 [0.00537708 0.00242295 0.99219997]]
pi = [0.60003687 0.27454331 0.12541982]
Iter 12: LL=-1273291.63 | Rates: N=0.83062, AF=0.09732, OLD=0.10323, YOUNG=0.03885
A =
[[0.9932436  0.00181713 0.00493928]
 [0.00929465 0.98070845 0.0099969 ]
 [0.00538536 0.00245568 0.99215896]]
pi = [0.6000282  0.27297965 0.12699215]
Iter 13: LL=-1273276.57 | Rates: N=0.83062, AF=0.09729, OLD=0.10595, YOUNG=0.03902
A =
[[0.99324447 0.00174463 0.0050109 ]
 [0.00944222 0.97980437 0.01075341]
 [0.00539629 0.00248454 0.99211918]]
pi = [0.60002739 0.27061131 0.1293613 ]
Iter 14: LL=-1273262.18 | Rates: N=0.83062, AF=0.09727, OLD=0.10873, YOUNG=0.03920
A =
[[0.99324536 0.00167489 0.00507975]
 [0.00958195 0.97888243 0.01153562]
 [0.00540899 0.00250953 0.99208149]]
pi = [0.6000335  0.26749953 0.13246697]
Iter 15: LL=-1273248.47 | Rates: N=0.83061, AF=0.09724, OLD=0.11157, YOUNG=0.03937
A =
[[0.99324626 0.00160819 0.00514555]
 [0.00971526 0.97794293 0.01234181]
 [0.00542279 0.00253077 0.99204643]]
pi = [0.60004573 0.26368745 0.13626682]
Final Global Rates (lambdas): [0.83061351 0.09724171 0.11156576 0.03937193]
Final transition matrix A:
[[0.99324626 0.00160819 0.00514555]
 [0.00971526 0.97794293 0.01234181]
 [0.00542279 0.00253077 0.99204643]]
Final initial distribution pi:
[0.60004573 0.26368745 0.13626682]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.4512,0.1014,0.1656,13214798.0,16072202.0,117108812.0
Archaic_young,0.7602,0.9521,0.8454,380127188.0,119919812.0,19115336.0
Modern,0.0000,0.0000,0.0000,0.0,470666000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         463842          195           3020
Archaic_old      2196        13220         115263
Archaic_young    4628        15872         381764

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3553  0.0925  0.1468
Archaic_young     0.7731  0.9425  0.8495

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         483285          210           3577
Archaic_old      1952        10704         103498
Archaic_young    4777        19255         372742

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1507169.85 | Rates: N=0.83921, AF=0.09735, OLD=0.07220, YOUNG=0.05177
A =
[[0.9930331  0.00234756 0.00461934]
 [0.00739521 0.98711585 0.00548894]
 [0.00663172 0.00251528 0.99085301]]
pi = [0.40180998 0.23566745 0.36252257]
Iter 2: LL=-1289048.76 | Rates: N=0.83943, AF=0.09735, OLD=0.08008, YOUNG=0.04781
A =
[[0.9931458  0.00234437 0.00450983]
 [0.00753032 0.98703094 0.00543875]
 [0.006405   0.00244389 0.99115111]]
pi = [0.40079825 0.24166234 0.3575394 ]
Iter 3: LL=-1288817.24 | Rates: N=0.83942, AF=0.09724, OLD=0.08791, YOUNG=0.04490
A =
[[0.99315883 0.00237671 0.00446447]
 [0.00782484 0.98673579 0.00543937]
 [0.00626522 0.00239041 0.99134437]]
pi = [0.40073503 0.24275336 0.35651161]
Iter 4: LL=-1288665.15 | Rates: N=0.83941, AF=0.09711, OLD=0.09381, YOUNG=0.04332
A =
[[0.99316287 0.00238284 0.00445429]
 [0.00816833 0.98620473 0.00562695]
 [0.00613728 0.00236867 0.99149406]]
pi = [0.40075503 0.23661696 0.36262801]
Iter 5: LL=-1288599.02 | Rates: N=0.83940, AF=0.09702, OLD=0.09801, YOUNG=0.04271
A =
[[0.99316397 0.00236169 0.00447434]
 [0.00849547 0.98553075 0.00597379]
 [0.00604097 0.00238185 0.99157718]]
pi = [0.40079907 0.22613751 0.37306342]
Iter 6: LL=-1288568.92 | Rates: N=0.83940, AF=0.09695, OLD=0.10122, YOUNG=0.04259
A =
[[0.99316412 0.00232098 0.0045149 ]
 [0.00877955 0.98479635 0.0064241 ]
 [0.00597745 0.00241593 0.99160663]]
pi = [0.40084758 0.21427887 0.38487355]
Iter 7: LL=-1288549.45 | Rates: N=0.83939, AF=0.09691, OLD=0.10394, YOUNG=0.04268
A =
[[0.99316419 0.00226826 0.00456756]
 [0.00901728 0.98404375 0.00693896]
 [0.00593979 0.00245962 0.99160059]]
pi = [0.40089158 0.20259347 0.39651496]
Iter 8: LL=-1288533.29 | Rates: N=0.83939, AF=0.09687, OLD=0.10643, YOUNG=0.04285
A =
[[0.99316444 0.00220895 0.00462661]
 [0.00921426 0.98328809 0.00749765]
 [0.00592064 0.00250697 0.9915724 ]]
pi = [0.40092808 0.19162749 0.40744443]
Iter 9: LL=-1288518.56 | Rates: N=0.83939, AF=0.09684, OLD=0.10884, YOUNG=0.04304
A =
[[0.99316491 0.00214658 0.0046885 ]
 [0.00937834 0.98253124 0.00809043]
 [0.00591416 0.00255515 0.99153069]]
pi = [0.40095703 0.18145436 0.41758861]
Iter 10: LL=-1288504.71 | Rates: N=0.83939, AF=0.09681, OLD=0.11122, YOUNG=0.04323
A =
[[0.99316558 0.00208333 0.00475108]
 [0.0095171  0.98176969 0.00871321]
 [0.00591612 0.00260282 0.99148106]]
pi = [0.40097949 0.17196986 0.42705065]
Iter 11: LL=-1288491.51 | Rates: N=0.83938, AF=0.09678, OLD=0.11360, YOUNG=0.04342
A =
[[0.9931664  0.00202057 0.00481303]
 [0.00963712 0.98099826 0.00936462]
 [0.00592355 0.00264933 0.99142712]]
pi = [0.40099682 0.16302226 0.43598092]
Iter 12: LL=-1288478.83 | Rates: N=0.83938, AF=0.09675, OLD=0.11601, YOUNG=0.04360
A =
[[0.9931673  0.00195915 0.00487355]
 [0.00974375 0.98021162 0.01004462]
 [0.00593438 0.00269433 0.99137129]]
pi = [0.40101023 0.15446344 0.44452633]
Iter 13: LL=-1288466.59 | Rates: N=0.83938, AF=0.09673, OLD=0.11847, YOUNG=0.04378
A =
[[0.99316825 0.00189956 0.00493219]
 [0.00984135 0.97940481 0.01075384]
 [0.0059472  0.00273762 0.99131518]]
pi = [0.40102071 0.14616631 0.45281298]
Iter 14: LL=-1288454.71 | Rates: N=0.83937, AF=0.09670, OLD=0.12098, YOUNG=0.04395
A =
[[0.99316921 0.00184211 0.00498868]
 [0.00993343 0.97857322 0.01149335]
 [0.00596103 0.00277906 0.99125991]]
pi = [0.40102898 0.13802834 0.46094269]
Iter 15: LL=-1288443.13 | Rates: N=0.83937, AF=0.09667, OLD=0.12355, YOUNG=0.04412
A =
[[0.99317012 0.00178694 0.00504294]
 [0.01002291 0.97771249 0.0122646 ]
 [0.0059752  0.00281855 0.99120625]]
pi = [0.40103551 0.12996963 0.46899486]
Final Global Rates (lambdas): [0.83936799 0.09667011 0.12355151 0.04411595]
Final transition matrix A:
[[0.99317012 0.00178694 0.00504294]
 [0.01002291 0.97771249 0.0122646 ]
 [0.0059752  0.00281855 0.99120625]]
Final initial distribution pi:
[0.40103551 0.12996963 0.46899486]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.3500,0.1252,0.1844,14498585.0,26924415.0,101319347.0
Archaic_young,0.7769,0.9238,0.8440,363559084.0,104411916.0,30007872.0
Modern,0.0000,0.0000,0.0000,0.0,490606000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         483457          412           3203
Archaic_old      2178        14466          99510
Archaic_young    4971        26545         365258

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2659  0.4971  0.3465
Archaic_young     0.8191  0.6299  0.7121

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         495524         1219           1656
Archaic_old      1548        52679          52199
Archaic_young    2707       144201         248267

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1483696.08 | Rates: N=0.84591, AF=0.09629, OLD=0.05391, YOUNG=0.03212
A =
[[0.99483193 0.00253052 0.00263755]
 [0.00568    0.99189148 0.00242852]
 [0.00495443 0.00210164 0.99294394]]
pi = [0.39950273 0.26684798 0.33364929]
Iter 2: LL=-1260941.91 | Rates: N=0.84609, AF=0.09610, OLD=0.05632, YOUNG=0.03091
A =
[[0.99485396 0.00249207 0.00265397]
 [0.00592245 0.99152748 0.00255007]
 [0.00473602 0.00205719 0.99320679]]
pi = [0.3985476 0.253624  0.3478284]
Iter 3: LL=-1260905.11 | Rates: N=0.84609, AF=0.09607, OLD=0.05830, YOUNG=0.03033
A =
[[0.9948549  0.00245998 0.00268512]
 [0.00615871 0.99114478 0.00269651]
 [0.00460084 0.00205824 0.99334092]]
pi = [0.39852543 0.24234064 0.35913393]
Iter 4: LL=-1260885.44 | Rates: N=0.84609, AF=0.09605, OLD=0.05984, YOUNG=0.03012
A =
[[0.99485471 0.00241909 0.0027262 ]
 [0.00636606 0.99075668 0.00287726]
 [0.00450499 0.00208285 0.99341216]]
pi = [0.39852297 0.23219036 0.36928667]
Iter 5: LL=-1260872.91 | Rates: N=0.84609, AF=0.09604, OLD=0.06112, YOUNG=0.03011
A =
[[0.99485447 0.00237115 0.00277438]
 [0.00654656 0.9903667  0.00308674]
 [0.00443877 0.00211974 0.99344149]]
pi = [0.39852302 0.22266298 0.378814  ]
Iter 6: LL=-1260862.86 | Rates: N=0.84609, AF=0.09602, OLD=0.06226, YOUNG=0.03019
A =
[[0.99485431 0.00231835 0.00282735]
 [0.00670526 0.98997442 0.00332033]
 [0.00439438 0.00216161 0.99344402]]
pi = [0.39852423 0.21333932 0.38813645]
Iter 7: LL=-1260853.68 | Rates: N=0.84609, AF=0.09601, OLD=0.06334, YOUNG=0.03031
A =
[[0.99485424 0.0022624  0.00288336]
 [0.00684669 0.98957813 0.00357518]
 [0.00436608 0.00220445 0.99342947]]
pi = [0.39852639 0.20390194 0.39757166]
Iter 8: LL=-1260844.81 | Rates: N=0.84609, AF=0.09600, OLD=0.06440, YOUNG=0.03045
A =
[[0.99485425 0.00220456 0.00294119]
 [0.00697444 0.9891757  0.00384986]
 [0.00434977 0.00224622 0.99340401]]
pi = [0.39852994 0.19411877 0.40735129]
Iter 9: LL=-1260836.08 | Rates: N=0.84609, AF=0.09599, OLD=0.06547, YOUNG=0.03059
A =
[[0.99485435 0.00214566 0.00299999]
 [0.00709127 0.98876491 0.00414383]
 [0.00434251 0.00228589 0.99337159]]
pi = [0.39853558 0.18383033 0.41763409]
Iter 10: LL=-1260827.41 | Rates: N=0.84609, AF=0.09599, OLD=0.06657, YOUNG=0.03074
A =
[[0.99485451 0.00208629 0.0030592 ]
 [0.00719934 0.98834362 0.00445703]
 [0.00434213 0.00232298 0.99333489]]
pi = [0.39854402 0.17294177 0.42851421]
Iter 11: LL=-1260818.75 | Rates: N=0.84609, AF=0.09598, OLD=0.06770, YOUNG=0.03088
A =
[[0.99485473 0.00202687 0.0031184 ]
 [0.00730042 0.9879099  0.00478968]
 [0.00434701 0.00235723 0.99329576]]
pi = [0.39855583 0.16141762 0.44002655]
Iter 12: LL=-1260810.11 | Rates: N=0.84609, AF=0.09597, OLD=0.06888, YOUNG=0.03102
A =
[[0.994855   0.0019677  0.0031773 ]
 [0.00739592 0.987462   0.00514208]
 [0.0043559  0.00238854 0.99325555]]
pi = [0.39857137 0.14927815 0.45215049]
Iter 13: LL=-1260801.46 | Rates: N=0.84609, AF=0.09596, OLD=0.07010, YOUNG=0.03116
A =
[[0.99485531 0.00190898 0.00323571]
 [0.00748701 0.98699844 0.00551455]
 [0.00436785 0.00241688 0.99321527]]
pi = [0.39859073 0.13659663 0.46481264]
Iter 14: LL=-1260792.81 | Rates: N=0.84609, AF=0.09595, OLD=0.07136, YOUNG=0.03130
A =
[[0.99485566 0.00185089 0.00329345]
 [0.00757467 0.98651798 0.00590735]
 [0.0043821  0.00244222 0.99317568]]
pi = [0.39861379 0.12349662 0.47788959]
Iter 15: LL=-1260784.16 | Rates: N=0.84609, AF=0.09594, OLD=0.07268, YOUNG=0.03143
A =
[[0.99485604 0.00179355 0.00335041]
 [0.00765968 0.98601963 0.00632069]
 [0.00439807 0.00246457 0.99313736]]
pi = [0.39864016 0.11014836 0.49121149]
Final Global Rates (lambdas): [0.84608866 0.09594358 0.07267845 0.03143455]
Final transition matrix A:
[[0.99485604 0.00179355 0.00335041]
 [0.00765968 0.98601963 0.00632069]
 [0.00439807 0.00246457 0.99313736]]
Final initial distribution pi:
[0.39864016 0.11014836 0.49121149]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3134  0.1902  0.2367   20151521.0   44152479.0  85812046.0
Archaic_young     0.7976  0.8851  0.8391  347775470.0   88237530.0  45136906.0
Modern            0.0000  0.0000  0.0000          0.0  499683000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         495544          550           2305
Archaic_old      1440        20188          84798
Archaic_young    2699        43566         348910

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3774  0.3717  0.3745
Archaic_young     0.8008  0.8067  0.8037

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         463820          878           2164
Archaic_old      1684        46827          77810
Archaic_young    3196        76290         327331

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1463564.75 | Rates: N=0.82670, AF=0.09664, OLD=0.05771, YOUNG=0.03456
A =
[[0.99402315 0.00261445 0.0033624 ]
 [0.00617549 0.99051342 0.00331109]
 [0.00490746 0.00205513 0.99303741]]
pi = [0.45190244 0.18644186 0.3616557 ]
Iter 2: LL=-1256777.17 | Rates: N=0.82689, AF=0.09656, OLD=0.06166, YOUNG=0.03258
A =
[[0.99406873 0.00259689 0.00333438]
 [0.00642667 0.9901314  0.00344192]
 [0.00471964 0.00198574 0.99329462]]
pi = [0.4519967  0.13597585 0.41202745]
Iter 3: LL=-1256696.09 | Rates: N=0.82688, AF=0.09651, OLD=0.06486, YOUNG=0.03158
A =
[[0.99407084 0.0025882  0.00334095]
 [0.00667374 0.98969936 0.0036269 ]
 [0.00461993 0.00196933 0.99341074]]
pi = [0.45198445 0.09602027 0.45199528]
Iter 4: LL=-1256658.21 | Rates: N=0.82688, AF=0.09646, OLD=0.06722, YOUNG=0.03117
A =
[[0.9940704  0.00256001 0.0033696 ]
 [0.00688534 0.9892318  0.00388286]
 [0.0045561  0.0019831  0.9934608 ]]
pi = [0.45201101 0.06819144 0.47979756]
Iter 5: LL=-1256638.78 | Rates: N=0.82688, AF=0.09643, OLD=0.06906, YOUNG=0.03107
A =
[[0.99406989 0.00251706 0.00341305]
 [0.00706074 0.98875128 0.00418797]
 [0.00451901 0.00201454 0.99346645]]
pi = [0.45204801 0.04966146 0.49829053]
Iter 6: LL=-1256625.30 | Rates: N=0.82688, AF=0.09641, OLD=0.07062, YOUNG=0.03110
A =
[[0.99406958 0.00246481 0.00346561]
 [0.00720633 0.98826836 0.00452531]
 [0.00450045 0.00205459 0.99344496]]
pi = [0.45208111 0.03718304 0.51073585]
Iter 7: LL=-1256613.80 | Rates: N=0.82688, AF=0.09639, OLD=0.07205, YOUNG=0.03120
A =
[[0.99406947 0.00240719 0.00352333]
 [0.00732881 0.98778632 0.00488487]
 [0.00449426 0.00209819 0.99340755]]
pi = [0.45210628 0.02851737 0.51937635]
Iter 8: LL=-1256603.21 | Rates: N=0.82688, AF=0.09637, OLD=0.07342, YOUNG=0.03131
A =
[[0.99406953 0.00234684 0.00358363]
 [0.00743376 0.98730492 0.00526132]
 [0.00449621 0.0021427  0.99336109]]
pi = [0.45212399 0.02229811 0.5255779 ]
Iter 9: LL=-1256593.21 | Rates: N=0.82688, AF=0.09636, OLD=0.07476, YOUNG=0.03143
A =
[[0.99406971 0.00228544 0.00364485]
 [0.0075256  0.98682254 0.00565186]
 [0.00450342 0.00218676 0.99330981]]
pi = [0.45213582 0.01770257 0.53016161]
Iter 10: LL=-1256583.69 | Rates: N=0.82688, AF=0.09635, OLD=0.07610, YOUNG=0.03155
A =
[[0.99406998 0.0022241  0.00370591]
 [0.00760772 0.98633728 0.006055  ]
 [0.00451396 0.00222966 0.99325638]]
pi = [0.45214331 0.01422372 0.53363297]
Iter 11: LL=-1256574.62 | Rates: N=0.82688, AF=0.09634, OLD=0.07744, YOUNG=0.03167
A =
[[0.99407032 0.00216357 0.00376611]
 [0.00768272 0.98584743 0.00646985]
 [0.00452649 0.00227099 0.99320252]]
pi = [0.45214767 0.01153819 0.53631414]
Iter 12: LL=-1256565.96 | Rates: N=0.82688, AF=0.09633, OLD=0.07878, YOUNG=0.03178
A =
[[0.99407071 0.00210434 0.00382495]
 [0.0077526  0.98535161 0.00689579]
 [0.00454012 0.00231053 0.99314935]]
pi = [0.45214981 0.00943224 0.53841795]
Iter 13: LL=-1256557.70 | Rates: N=0.82688, AF=0.09631, OLD=0.08014, YOUNG=0.03190
A =
[[0.99407113 0.00204673 0.00388214]
 [0.00781888 0.98484875 0.00733237]
 [0.00455424 0.00234817 0.99309759]]
pi = [0.45215039 0.00775981 0.54008979]
Iter 14: LL=-1256549.83 | Rates: N=0.82688, AF=0.09630, OLD=0.08150, YOUNG=0.03201
A =
[[0.99407157 0.00199095 0.00393748]
 [0.00788275 0.98433805 0.00777919]
 [0.00456841 0.00238389 0.9930477 ]]
pi = [0.45214991 0.00641805 0.54143204]
Iter 15: LL=-1256542.32 | Rates: N=0.82688, AF=0.09629, OLD=0.08286, YOUNG=0.03212
A =
[[0.99407202 0.00193712 0.00399086]
 [0.00794514 0.98381893 0.00823592]
 [0.00458237 0.00241767 0.99299996]]
pi = [0.4521487  0.00533259 0.54251871]
Final Global Rates (lambdas): [0.82688041 0.09629258 0.08286272 0.03211774]
Final transition matrix A:
[[0.99407202 0.00193712 0.00399086]
 [0.00794514 0.98381893 0.00823592]
 [0.00458237 0.00241767 0.99299996]]
Final initial distribution pi:
[0.4521487  0.00533259 0.54251871]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4576  0.2149  0.2924   27050033.0   32068967.0  98848567.0
Archaic_young     0.7850  0.9172  0.8460  370824469.0  101546531.0  33482291.0
Modern            0.0000  0.0000  0.0000          0.0  468510000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         463815          506           2541
Archaic_old      1568        27112          97641
Archaic_young    3127        31501         372189

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3680  0.3062  0.3343
Archaic_young     0.8139  0.8528  0.8329

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         464728          610           2693
Archaic_old      2051        34648          76950
Archaic_young    3623        58958         355739

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1476137.73 | Rates: N=0.83077, AF=0.09760, OLD=0.06285, YOUNG=0.03810
A =
[[0.99348285 0.00264204 0.00387512]
 [0.00689172 0.98907327 0.004035  ]
 [0.00540232 0.0021748  0.99242289]]
pi = [0.59566289 0.17762557 0.22671153]
Iter 2: LL=-1265907.97 | Rates: N=0.83097, AF=0.09762, OLD=0.06820, YOUNG=0.03541
A =
[[0.99354873 0.00261662 0.00383465]
 [0.00714252 0.98873382 0.00412366]
 [0.00520749 0.00209287 0.99269964]]
pi = [0.60021748 0.18273533 0.21704719]
Iter 3: LL=-1265780.53 | Rates: N=0.83097, AF=0.09756, OLD=0.07256, YOUNG=0.03403
A =
[[0.99355354 0.00260756 0.0038389 ]
 [0.00741093 0.9883028  0.00428626]
 [0.00510639 0.00206962 0.99282399]]
pi = [0.60028425 0.18277239 0.21694336]
Iter 4: LL=-1265724.36 | Rates: N=0.83096, AF=0.09750, OLD=0.07569, YOUNG=0.03348
A =
[[0.99355384 0.0025769  0.00386927]
 [0.00766258 0.98777348 0.00456394]
 [0.00503656 0.00207983 0.99288361]]
pi = [0.60026036 0.17744357 0.22229607]
Iter 5: LL=-1265698.59 | Rates: N=0.83096, AF=0.09745, OLD=0.07809, YOUNG=0.03335
A =
[[0.99355362 0.00253036 0.00391602]
 [0.00788759 0.98718897 0.00492344]
 [0.00499189 0.0021097  0.99289841]]
pi = [0.60022605 0.16951445 0.2302595 ]
Iter 6: LL=-1265681.50 | Rates: N=0.83096, AF=0.09742, OLD=0.08015, YOUNG=0.03342
A =
[[0.99355348 0.00247414 0.00397238]
 [0.00808741 0.98657453 0.00533806]
 [0.00496582 0.0021486  0.99288558]]
pi = [0.60019278 0.16049847 0.23930874]
Iter 7: LL=-1265666.77 | Rates: N=0.83096, AF=0.09739, OLD=0.08206, YOUNG=0.03356
A =
[[0.99355352 0.00241245 0.00403403]
 [0.00826604 0.98594143 0.00579253]
 [0.00495292 0.00219082 0.99285627]]
pi = [0.60016484 0.1510082  0.24882696]
Iter 8: LL=-1265652.88 | Rates: N=0.83096, AF=0.09736, OLD=0.08394, YOUNG=0.03372
A =
[[0.99355376 0.00234794 0.0040983 ]
 [0.00842766 0.98529325 0.00627909]
 [0.00494919 0.00223363 0.99281718]]
pi = [0.60014271 0.1412298  0.25862749]
Iter 9: LL=-1265639.47 | Rates: N=0.83096, AF=0.09734, OLD=0.08582, YOUNG=0.03390
A =
[[0.99355417 0.00228224 0.00416359]
 [0.00857605 0.98462997 0.00679398]
 [0.0049518  0.00227571 0.99277248]]
pi = [0.60012573 0.13118825 0.26868603]
Iter 10: LL=-1265626.45 | Rates: N=0.83095, AF=0.09731, OLD=0.08774, YOUNG=0.03407
A =
[[0.99355471 0.00221637 0.00422892]
 [0.00871448 0.98395015 0.00733537]
 [0.00495876 0.00231635 0.99272489]]
pi = [0.60011314 0.12086907 0.27901779]
Iter 11: LL=-1265613.75 | Rates: N=0.83095, AF=0.09729, OLD=0.08970, YOUNG=0.03424
A =
[[0.99355536 0.002151   0.00429364]
 [0.00884565 0.98325197 0.00790239]
 [0.00496865 0.00235512 0.99267623]]
pi = [0.60010439 0.11027103 0.28962458]
Iter 12: LL=-1265601.38 | Rates: N=0.83095, AF=0.09726, OLD=0.09172, YOUNG=0.03440
A =
[[0.99355608 0.00208657 0.00435734]
 [0.00897177 0.98253372 0.00849451]
 [0.00498046 0.00239174 0.9926278 ]]
pi = [0.60009914 0.09942918 0.30047168]
Iter 13: LL=-1265589.30 | Rates: N=0.83095, AF=0.09724, OLD=0.09379, YOUNG=0.03457
A =
[[0.99355687 0.00202337 0.00441977]
 [0.00909464 0.98179397 0.00911139]
 [0.00499347 0.00242602 0.99258051]]
pi = [0.60009721 0.08842526 0.31147753]
Iter 14: LL=-1265577.52 | Rates: N=0.83095, AF=0.09721, OLD=0.09592, YOUNG=0.03473
A =
[[0.99355769 0.00196158 0.00448073]
 [0.00921567 0.98103157 0.00975276]
 [0.00500719 0.0024578  0.99253501]]
pi = [0.60009844 0.07739116 0.3225104 ]
Iter 15: LL=-1265566.02 | Rates: N=0.83094, AF=0.09719, OLD=0.09812, YOUNG=0.03488
A =
[[0.99355853 0.00190136 0.00454012]
 [0.00933601 0.98024567 0.01041832]
 [0.00502126 0.00248697 0.99249177]]
pi = [0.60010269 0.06650614 0.33339117]
Final Global Rates (lambdas): [0.83094497 0.09718748 0.09811804 0.03488428]
Final transition matrix A:
[[0.99355853 0.00190136 0.00454012]
 [0.00933601 0.98024567 0.01041832]
 [0.00502126 0.00248697 0.99249177]]
Final initial distribution pi:
[0.60010269 0.06650614 0.33339117]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4314  0.1676  0.2414   18977588.0   25014412.0  94248142.0
Archaic_young     0.8004  0.9333  0.8618  387849334.0   96744666.0  27699294.0
Modern            0.0000  0.0000  0.0000          0.0  471414000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         464992          129           2910
Archaic_old      2392        18949          92308
Archaic_young    4030        24914         389376

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3770  0.2955  0.3313
Archaic_young     0.8162  0.8647  0.8398

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         487170          768           2938
Archaic_old      2090        31467          73303
Archaic_young    4422        51159         346683

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1500302.55 | Rates: N=0.83855, AF=0.09878, OLD=0.07152, YOUNG=0.04333
A =
[[0.9933385  0.00264654 0.00401496]
 [0.00761062 0.98779833 0.00459105]
 [0.00614731 0.00239615 0.99145654]]
pi = [0.69088214 0.12337729 0.18574058]
Iter 2: LL=-1282604.21 | Rates: N=0.83876, AF=0.09883, OLD=0.07943, YOUNG=0.03967
A =
[[0.99343371 0.00263765 0.00392864]
 [0.00795677 0.98729222 0.00475101]
 [0.00587016 0.00223785 0.99189199]]
pi = [0.71396761 0.11348949 0.1725429 ]
Iter 3: LL=-1282388.39 | Rates: N=0.83875, AF=0.09872, OLD=0.08598, YOUNG=0.03794
A =
[[0.99344418 0.00264467 0.00391115]
 [0.00833404 0.98663466 0.0050313 ]
 [0.00573351 0.00215594 0.99211055]]
pi = [0.71598174 0.11627106 0.1677472 ]
Iter 4: LL=-1282295.00 | Rates: N=0.83874, AF=0.09861, OLD=0.09075, YOUNG=0.03737
A =
[[0.99344727 0.00261566 0.00393707]
 [0.00866741 0.98585728 0.0054753 ]
 [0.00565396 0.00212814 0.9922179 ]]
pi = [0.7158669  0.1214266  0.16270649]
Iter 5: LL=-1282252.28 | Rates: N=0.83873, AF=0.09853, OLD=0.09450, YOUNG=0.03735
A =
[[0.99344894 0.00255976 0.0039913 ]
 [0.0089421  0.98503275 0.00602515]
 [0.00561666 0.00213302 0.99225033]]
pi = [0.71543039 0.12657887 0.15799073]
Iter 6: LL=-1282223.48 | Rates: N=0.83873, AF=0.09847, OLD=0.09779, YOUNG=0.03753
A =
[[0.99345031 0.00248779 0.0040619 ]
 [0.00916479 0.98419612 0.00663909]
 [0.00560697 0.00215424 0.99223879]]
pi = [0.71493751 0.13092897 0.15413352]
Iter 7: LL=-1282199.06 | Rates: N=0.83872, AF=0.09842, OLD=0.10089, YOUNG=0.03777
A =
[[0.99345168 0.00240739 0.00414092]
 [0.00934602 0.98335906 0.00729491]
 [0.00561414 0.00218343 0.99220243]]
pi = [0.71446306 0.13430423 0.15123271]
Iter 8: LL=-1282176.87 | Rates: N=0.83872, AF=0.09838, OLD=0.10391, YOUNG=0.03803
A =
[[0.99345311 0.00232347 0.00422342]
 [0.00949584 0.98252228 0.00798189]
 [0.00563104 0.00221647 0.99215249]]
pi = [0.71402913 0.1367613  0.14920957]
Iter 9: LL=-1282156.33 | Rates: N=0.83871, AF=0.09834, OLD=0.10690, YOUNG=0.03828
A =
[[0.99345459 0.00223907 0.00430634]
 [0.0096228  0.98168228 0.00869492]
 [0.00565311 0.0022512  0.99209569]]
pi = [0.71363676 0.13842207 0.14794116]
Iter 10: LL=-1282137.22 | Rates: N=0.83871, AF=0.09831, OLD=0.10989, YOUNG=0.03852
A =
[[0.99345609 0.00215611 0.00438779]
 [0.0097338  0.9808346  0.0094316 ]
 [0.00567747 0.00228638 0.99203615]]
pi = [0.71327915 0.13941364 0.14730721]
Iter 11: LL=-1282119.40 | Rates: N=0.83871, AF=0.09828, OLD=0.11289, YOUNG=0.03875
A =
[[0.99345759 0.00207576 0.00446665]
 [0.00983423 0.979975   0.01019076]
 [0.00570233 0.00232125 0.99197642]]
pi = [0.71294727 0.13984882 0.14720392]
Iter 12: LL=-1282102.73 | Rates: N=0.83870, AF=0.09825, OLD=0.11591, YOUNG=0.03897
A =
[[0.99345905 0.00199868 0.00454227]
 [0.00992822 0.97909983 0.01097195]
 [0.00572663 0.00235531 0.99191806]]
pi = [0.7126321  0.13982166 0.14754624]
Iter 13: LL=-1282087.13 | Rates: N=0.83870, AF=0.09822, OLD=0.11896, YOUNG=0.03918
A =
[[0.99346047 0.0019252  0.00461432]
 [0.01001894 0.97820599 0.01177507]
 [0.00574975 0.00238824 0.99186201]]
pi = [0.71232534 0.13940821 0.14826644]
Iter 14: LL=-1282072.47 | Rates: N=0.83869, AF=0.09820, OLD=0.12204, YOUNG=0.03939
A =
[[0.99346184 0.00185546 0.0046827 ]
 [0.01010882 0.97729085 0.01260033]
 [0.00577137 0.00241984 0.99180879]]
pi = [0.71201951 0.13866892 0.14931157]
Iter 15: LL=-1282058.66 | Rates: N=0.83869, AF=0.09817, OLD=0.12515, YOUNG=0.03959
A =
[[0.99346313 0.00178942 0.00474745]
 [0.01019977 0.9763521  0.01344813]
 [0.00579135 0.00244996 0.99175869]]
pi = [0.71170776 0.13765134 0.1506409 ]
Final Global Rates (lambdas): [0.83869061 0.09817042 0.1251516  0.03958739]
Final transition matrix A:
[[0.99346313 0.00178942 0.00474745]
 [0.01019977 0.9763521  0.01344813]
 [0.00579135 0.00244996 0.99175869]]
Final initial distribution pi:
[0.71170776 0.13765134 0.1506409 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4639  0.1736  0.2526   18471813.0   21344187.0  87949552.0
Archaic_young     0.8053  0.9394  0.8672  375066143.0   90674857.0  24176381.0
Modern            0.0000  0.0000  0.0000          0.0  494443000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         487526          294           3056
Archaic_old      2335        18470          86055
Archaic_young    4582        21052         376630

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3330  0.6208  0.4335
Archaic_young     0.8243  0.5917  0.6889

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         471653         1581           1401
Archaic_old      2260        80514          47416
Archaic_young    2528       159436         233211

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1470130.14 | Rates: N=0.83154, AF=0.09695, OLD=0.05728, YOUNG=0.03097
A =
[[0.99426072 0.00309315 0.00264614]
 [0.00604925 0.99158753 0.00236322]
 [0.00470272 0.00220616 0.99309111]]
pi = [0.39956329 0.30560043 0.29483629]
Iter 2: LL=-1258926.89 | Rates: N=0.83173, AF=0.09687, OLD=0.05947, YOUNG=0.03020
A =
[[0.99429097 0.00303034 0.00267869]
 [0.00635808 0.99107541 0.00256651]
 [0.00445736 0.00215412 0.99338852]]
pi = [0.39945643 0.32287829 0.27766528]
Iter 3: LL=-1258894.82 | Rates: N=0.83173, AF=0.09683, OLD=0.06134, YOUNG=0.03000
A =
[[0.99429227 0.00298353 0.0027242 ]
 [0.00662445 0.99059562 0.00277993]
 [0.00432826 0.00216287 0.99350886]]
pi = [0.39938491 0.33960662 0.26100846]
Iter 4: LL=-1258875.19 | Rates: N=0.83173, AF=0.09680, OLD=0.06288, YOUNG=0.03003
A =
[[0.99429211 0.00292608 0.0027818 ]
 [0.00684979 0.99013    0.00302022]
 [0.00424782 0.00219294 0.99355924]]
pi = [0.39930246 0.35265531 0.24804223]
Iter 5: LL=-1258860.20 | Rates: N=0.83173, AF=0.09677, OLD=0.06424, YOUNG=0.03016
A =
[[0.99429197 0.00286029 0.00284774]
 [0.00704122 0.98967701 0.00328177]
 [0.00420025 0.0022328  0.99356695]]
pi = [0.39922563 0.36182108 0.23895329]
Iter 6: LL=-1258847.11 | Rates: N=0.83173, AF=0.09675, OLD=0.06550, YOUNG=0.03032
A =
[[0.99429199 0.00278898 0.00291903]
 [0.00720593 0.98923323 0.00356084]
 [0.00417522 0.00227636 0.99354842]]
pi = [0.39915806 0.36751828 0.23332367]
Iter 7: LL=-1258834.97 | Rates: N=0.83173, AF=0.09673, OLD=0.06673, YOUNG=0.03050
A =
[[0.99429219 0.00271435 0.00299347]
 [0.0073498  0.98879467 0.00385553]
 [0.00416577 0.00232043 0.9935138 ]]
pi = [0.39909949 0.37028396 0.23061655]
Iter 8: LL=-1258823.42 | Rates: N=0.83173, AF=0.09672, OLD=0.06795, YOUNG=0.03068
A =
[[0.99429254 0.00263797 0.00306949]
 [0.00747747 0.98835743 0.00416511]
 [0.00416714 0.00236339 0.99346948]]
pi = [0.39904859 0.37059942 0.23035198]
Iter 9: LL=-1258812.29 | Rates: N=0.83173, AF=0.09670, OLD=0.06917, YOUNG=0.03085
A =
[[0.99429303 0.00256096 0.00314601]
 [0.00759261 0.98791796 0.00448944]
 [0.00417603 0.00240438 0.99341959]]
pi = [0.39900403 0.36884545 0.23215052]
Iter 10: LL=-1258801.49 | Rates: N=0.83173, AF=0.09669, OLD=0.07042, YOUNG=0.03101
A =
[[0.99429362 0.00248411 0.00322227]
 [0.00769813 0.98747317 0.00482871]
 [0.00419013 0.00244297 0.9933669 ]]
pi = [0.39896476 0.36530668 0.23572856]
Iter 11: LL=-1258790.97 | Rates: N=0.83173, AF=0.09667, OLD=0.07169, YOUNG=0.03117
A =
[[0.99429429 0.00240798 0.00329773]
 [0.00779637 0.98702042 0.00518321]
 [0.00420777 0.00247895 0.99331329]]
pi = [0.39893012 0.36018998 0.2408799 ]
Iter 12: LL=-1258780.71 | Rates: N=0.83173, AF=0.09666, OLD=0.07299, YOUNG=0.03133
A =
[[0.99429501 0.00233298 0.003372  ]
 [0.00788922 0.98655748 0.00555329]
 [0.00422775 0.00251222 0.99326003]]
pi = [0.39889972 0.35364447 0.24745581]
Iter 13: LL=-1258770.68 | Rates: N=0.83172, AF=0.09665, OLD=0.07433, YOUNG=0.03148
A =
[[0.99429578 0.0022594  0.00344482]
 [0.00797822 0.98608252 0.00593926]
 [0.00424918 0.0025428  0.99320802]]
pi = [0.39887341 0.34577954 0.25534705]
Iter 14: LL=-1258760.87 | Rates: N=0.83172, AF=0.09663, OLD=0.07570, YOUNG=0.03163
A =
[[0.99429656 0.00218744 0.003516  ]
 [0.00806463 0.98559398 0.00634139]
 [0.00427142 0.00257072 0.99315787]]
pi = [0.39885126 0.33668023 0.26446852]
Iter 15: LL=-1258751.26 | Rates: N=0.83172, AF=0.09662, OLD=0.07710, YOUNG=0.03178
A =
[[0.99429736 0.00211725 0.00358539]
 [0.00814949 0.9850906  0.00675991]
 [0.00429397 0.00259606 0.99310997]]
pi = [0.39883341 0.32642035 0.27474624]
Final Global Rates (lambdas): [0.8317231  0.09661936 0.07710068 0.03178176]
Final transition matrix A:
[[0.99429736 0.00211725 0.00358539]
 [0.00814949 0.9850906  0.00675991]
 [0.00429397 0.00259606 0.99310997]]
Final initial distribution pi:
[0.39883341 0.32642035 0.27474624]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4469  0.2518  0.3221   32623369.0   40383631.0  96946617.0
Archaic_young     0.7806  0.8955  0.8341  351867516.0   98915484.0  41044860.0
Modern            0.0000  0.0000  0.0000          0.0  476210000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         471654          606           2375
Archaic_old      2138        32699          95353
Archaic_young    2418        39702         353055

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.4244  0.5197  0.4672
Archaic_young     0.8389  0.7835  0.8102

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         465497         1204           2185
Archaic_old      2348        64369          57580
Archaic_young    3057        85897         317863

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1471060.58 | Rates: N=0.82992, AF=0.09771, OLD=0.06146, YOUNG=0.03334
A =
[[0.99367506 0.00303694 0.003288  ]
 [0.00708883 0.98971971 0.00319146]
 [0.00490243 0.00210776 0.99298981]]
pi = [0.50322649 0.14667778 0.35009572]
Iter 2: LL=-1261515.84 | Rates: N=0.83012, AF=0.09773, OLD=0.06518, YOUNG=0.03186
A =
[[0.99372384 0.0029829  0.00329326]
 [0.00754556 0.98910035 0.0033541 ]
 [0.00465124 0.00201532 0.99333344]]
pi = [0.50502295 0.08412009 0.41085697]
Iter 3: LL=-1261451.55 | Rates: N=0.83012, AF=0.09768, OLD=0.06814, YOUNG=0.03133
A =
[[0.99372558 0.0029425  0.00333192]
 [0.00792419 0.98854082 0.00353499]
 [0.00452968 0.00199749 0.99347282]]
pi = [0.50472016 0.04516198 0.45011785]
Iter 4: LL=-1261422.29 | Rates: N=0.83011, AF=0.09764, OLD=0.07038, YOUNG=0.03123
A =
[[0.99372495 0.00288211 0.00339294]
 [0.00823507 0.98800215 0.00376278]
 [0.00446146 0.0020072  0.99353135]]
pi = [0.50457958 0.02343963 0.47198079]
Iter 5: LL=-1261404.96 | Rates: N=0.83011, AF=0.09760, OLD=0.07220, YOUNG=0.03131
A =
[[0.99372444 0.00280919 0.00346637]
 [0.00849052 0.9874881  0.00402138]
 [0.0044277  0.00202928 0.99354302]]
pi = [0.50454751 0.01199747 0.48345502]
Iter 6: LL=-1261391.68 | Rates: N=0.83011, AF=0.09758, OLD=0.07382, YOUNG=0.03146
A =
[[0.99372426 0.00273016 0.00354558]
 [0.00870313 0.98699767 0.0042992 ]
 [0.00441603 0.0020559  0.99352808]]
pi = [0.50455936 0.00609506 0.48934558]
Iter 7: LL=-1261380.20 | Rates: N=0.83011, AF=0.09756, OLD=0.07532, YOUNG=0.03163
A =
[[0.99372437 0.00264908 0.00362655]
 [0.00888291 0.98652756 0.00458954]
 [0.00441842 0.0020833  0.99349828]]
pi = [0.50458718 0.00307723 0.49233559]
Iter 8: LL=-1261369.84 | Rates: N=0.83011, AF=0.09754, OLD=0.07677, YOUNG=0.03181
A =
[[0.99372471 0.00256836 0.00370693]
 [0.00903743 0.98607392 0.00488865]
 [0.00442972 0.00210979 0.99346048]]
pi = [0.50462018 0.00154358 0.49383624]
Iter 9: LL=-1261360.37 | Rates: N=0.83011, AF=0.09753, OLD=0.07818, YOUNG=0.03197
A =
[[0.99372523 0.00248943 0.00378534]
 [0.00917242 0.98563324 0.00519434]
 [0.00444659 0.00213461 0.99341879]]
pi = [0.50465427 0.00076891 0.49457681]
Iter 10: LL=-1261351.64 | Rates: N=0.83011, AF=0.09751, OLD=0.07957, YOUNG=0.03213
A =
[[0.99372586 0.0024131  0.00386104]
 [0.0092922  0.98520266 0.00550514]
 [0.00446682 0.00215747 0.99337571]]
pi = [5.04687927e-01 3.80231872e-04 4.94931841e-01]
Iter 11: LL=-1261343.59 | Rates: N=0.83011, AF=0.09750, OLD=0.08094, YOUNG=0.03227
A =
[[0.99372659 0.0023398  0.00393362]
 [0.00940005 0.98477998 0.00581997]
 [0.00448894 0.00217829 0.99333276]]
pi = [5.04720572e-01 1.86620801e-04 4.95092808e-01]
Iter 12: LL=-1261336.15 | Rates: N=0.83011, AF=0.09749, OLD=0.08229, YOUNG=0.03242
A =
[[0.99372736 0.00226973 0.0040029 ]
 [0.00949846 0.98436359 0.00613795]
 [0.00451197 0.00219714 0.9932909 ]]
pi = [5.04752016e-01 9.09062199e-05 4.95157078e-01]
Iter 13: LL=-1261329.28 | Rates: N=0.83010, AF=0.09747, OLD=0.08363, YOUNG=0.03255
A =
[[0.99372817 0.00220296 0.00406886]
 [0.00958935 0.98395231 0.00645834]
 [0.00453523 0.00221411 0.99325066]]
pi = [5.04782216e-01 4.39518747e-05 4.95173832e-01]
Iter 14: LL=-1261322.91 | Rates: N=0.83010, AF=0.09746, OLD=0.08495, YOUNG=0.03268
A =
[[0.993729   0.00213945 0.00413155]
 [0.00967419 0.98354531 0.00678049]
 [0.00455829 0.00222935 0.99321236]]
pi = [5.04811187e-01 2.10945935e-05 4.95167718e-01]
Iter 15: LL=-1261317.02 | Rates: N=0.83010, AF=0.09745, OLD=0.08626, YOUNG=0.03281
A =
[[0.99372984 0.00207909 0.00419107]
 [0.00975416 0.98314198 0.00710387]
 [0.00458085 0.00224302 0.99317613]]
pi = [5.04838969e-01 1.00520499e-05 4.95150979e-01]
Final Global Rates (lambdas): [0.83010201 0.09745068 0.08626291 0.03280888]
Final transition matrix A:
[[0.99372984 0.00207909 0.00419107]
 [0.00975416 0.98314198 0.00710387]
 [0.00458085 0.00224302 0.99317613]]
Final initial distribution pi:
[5.04838969e-01 1.00520499e-05 4.95150979e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.5221  0.2544  0.3421   31465338.0   28797662.0  92238562.0
Archaic_young     0.7984  0.9260  0.8575  374379072.0   94531928.0  29927688.0
Modern            0.0000  0.0000  0.0000          0.0  470826000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         465530          628           2728
Archaic_old      2318        31554          90425
Archaic_young    2978        28081         375758

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.4, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3753  0.4256  0.3989
Archaic_young     0.8215  0.7907  0.8058

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         455899         1115           2371
Archaic_old      2676        51817          67802
Archaic_young    3445        85074         329801

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1478414.26 | Rates: N=0.82870, AF=0.09830, OLD=0.06845, YOUNG=0.03700
A =
[[0.99299259 0.00315819 0.00384922]
 [0.00736009 0.98882353 0.00381638]
 [0.00545754 0.00228796 0.99225449]]
pi = [0.45384071 0.21560184 0.33055746]
Iter 2: LL=-1269502.22 | Rates: N=0.82890, AF=0.09842, OLD=0.07377, YOUNG=0.03445
A =
[[0.99307178 0.00307467 0.00385354]
 [0.00758151 0.98838703 0.00403146]
 [0.00528404 0.00218115 0.99253481]]
pi = [0.45584308 0.18808555 0.35607137]
Iter 3: LL=-1269385.23 | Rates: N=0.82890, AF=0.09834, OLD=0.07784, YOUNG=0.03342
A =
[[0.99307496 0.00301885 0.0039062 ]
 [0.00776145 0.98791982 0.00431873]
 [0.00523908 0.00217193 0.99258899]]
pi = [0.45604432 0.15969797 0.38425771]
Iter 4: LL=-1269338.41 | Rates: N=0.82890, AF=0.09826, OLD=0.08082, YOUNG=0.03311
A =
[[0.99307416 0.00294479 0.00398105]
 [0.00790756 0.98738825 0.00470418]
 [0.00522506 0.00220174 0.99257319]]
pi = [0.45608125 0.13258556 0.41133319]
Iter 5: LL=-1269312.36 | Rates: N=0.82890, AF=0.09821, OLD=0.08325, YOUNG=0.03312
A =
[[0.99307382 0.00286043 0.00406576]
 [0.00802826 0.98681888 0.00515285]
 [0.00522731 0.00224843 0.99252426]]
pi = [0.45605743 0.10869686 0.43524571]
Iter 6: LL=-1269291.63 | Rates: N=0.82889, AF=0.09817, OLD=0.08544, YOUNG=0.03327
A =
[[0.99307398 0.00277199 0.00415403]
 [0.00813144 0.98622566 0.0056429 ]
 [0.00523855 0.00230061 0.99246084]]
pi = [0.45601756 0.08826732 0.45571511]
Iter 7: LL=-1269272.74 | Rates: N=0.82889, AF=0.09813, OLD=0.08755, YOUNG=0.03346
A =
[[0.99307446 0.00268291 0.00424263]
 [0.00822272 0.98561392 0.00616335]
 [0.00525464 0.00235321 0.99239216]]
pi = [0.45598124 0.07090538 0.47311338]
Iter 8: LL=-1269254.93 | Rates: N=0.82889, AF=0.09810, OLD=0.08965, YOUNG=0.03366
A =
[[0.99307513 0.00259498 0.00432989]
 [0.00830619 0.98498469 0.00670912]
 [0.00527314 0.00240403 0.99232283]]
pi = [0.45595397 0.05614956 0.48789647]
Iter 9: LL=-1269237.97 | Rates: N=0.82889, AF=0.09806, OLD=0.09177, YOUNG=0.03387
A =
[[0.9930759  0.00250912 0.00441498]
 [0.00838487 0.9843372  0.00727792]
 [0.00529258 0.00245209 0.99225533]]
pi = [0.45593593 0.04364785 0.50041622]
Iter 10: LL=-1269221.77 | Rates: N=0.82889, AF=0.09803, OLD=0.09392, YOUNG=0.03408
A =
[[0.99307673 0.0024258  0.00449747]
 [0.00846102 0.98367033 0.00786865]
 [0.00531208 0.00249692 0.99219099]]
pi = [0.45592593 0.0331698  0.51090427]
Iter 11: LL=-1269206.25 | Rates: N=0.82889, AF=0.09800, OLD=0.09611, YOUNG=0.03429
A =
[[0.99307759 0.00234525 0.00457716]
 [0.00853623 0.98298321 0.00848056]
 [0.00533114 0.00253828 0.99213058]]
pi = [0.45592265 0.02455897 0.51951838]
Iter 12: LL=-1269191.38 | Rates: N=0.82889, AF=0.09796, OLD=0.09836, YOUNG=0.03449
A =
[[0.99307846 0.0022676  0.00465394]
 [0.00861157 0.98227552 0.00911291]
 [0.00534948 0.00257602 0.9920745 ]]
pi = [0.45592492 0.01767538 0.5263997 ]
Iter 13: LL=-1269177.12 | Rates: N=0.82888, AF=0.09793, OLD=0.10065, YOUNG=0.03469
A =
[[0.99307932 0.00219289 0.00472779]
 [0.00868767 0.98154755 0.00976479]
 [0.00536699 0.00261007 0.99202294]]
pi = [0.4559316  0.01235342 0.53171498]
Iter 14: LL=-1269163.46 | Rates: N=0.82888, AF=0.09790, OLD=0.10299, YOUNG=0.03489
A =
[[0.99308016 0.00212113 0.00479871]
 [0.00876485 0.98080009 0.01043506]
 [0.00538362 0.00264043 0.99197595]]
pi = [0.45594159 0.00838665 0.53567176]
Iter 15: LL=-1269150.40 | Rates: N=0.82888, AF=0.09786, OLD=0.10538, YOUNG=0.03508
A =
[[0.99308099 0.00205231 0.0048667 ]
 [0.00884324 0.98003432 0.01112244]
 [0.00539941 0.00266711 0.99193348]]
pi = [0.45595377 0.00553812 0.53850811]
Final Global Rates (lambdas): [0.82888008 0.09786428 0.10538344 0.03508186]
Final transition matrix A:
[[0.99308099 0.00205231 0.0048667 ]
 [0.00884324 0.98003432 0.01112244]
 [0.00539941 0.00266711 0.99193348]]
Final initial distribution pi:
[0.45595377 0.00553812 0.53850811]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.4_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.4881  0.1996  0.2833   24290623.0   25477377.0  97405938.0
Archaic_young     0.7959  0.9336  0.8593  387948202.0   99460798.0  27600426.0
Modern            0.0000  0.0000  0.0000          0.0  462823000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         456146          309           2930
Archaic_old      2974        24277          95044
Archaic_young    3703        25182         389435

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1576  0.0098  0.0185
Archaic_young     0.8274  0.9855  0.8996

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         398989           16           2568
Archaic_old       754          976          98063
Archaic_young    2864         5222         490548

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 10
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1414439.40 | Rates: N=0.79783, AF=0.09636, OLD=0.04673, YOUNG=0.03634
A =
[[0.99424516 0.00149349 0.00426135]
 [0.00404333 0.99205741 0.00389926]
 [0.00395039 0.00134986 0.99469975]]
pi = [0.34725046 0.23625284 0.4164967 ]
Iter 2: LL=-1229679.96 | Rates: N=0.79796, AF=0.09607, OLD=0.05097, YOUNG=0.03482
A =
[[0.99426094 0.00150697 0.00423208]
 [0.00401225 0.99218298 0.00380477]
 [0.00393256 0.00136462 0.99470281]]
pi = [0.34874095 0.25611025 0.3951488 ]
Iter 3: LL=-1229589.38 | Rates: N=0.79796, AF=0.09601, OLD=0.05537, YOUNG=0.03323
A =
[[0.9942674  0.00151763 0.00421497]
 [0.00403116 0.99221406 0.00375477]
 [0.00391831 0.00137695 0.99470474]]
pi = [0.34877238 0.28299503 0.3682326 ]
Iter 4: LL=-1229507.98 | Rates: N=0.79796, AF=0.09596, OLD=0.05902, YOUNG=0.03209
A =
[[0.99427231 0.00151338 0.00421431]
 [0.00410432 0.99207383 0.00382185]
 [0.00388744 0.00138973 0.99472283]]
pi = [0.34874782 0.31050246 0.34074973]
Iter 5: LL=-1229461.69 | Rates: N=0.79795, AF=0.09592, OLD=0.06179, YOUNG=0.03147
A =
[[0.9942752  0.00149372 0.00423107]
 [0.00421411 0.99177661 0.00400928]
 [0.00384909 0.0014095  0.9947414 ]]
pi = [0.34872499 0.33266624 0.31860876]
Iter 6: LL=-1229438.71 | Rates: N=0.79795, AF=0.09590, OLD=0.06392, YOUNG=0.03122
A =
[[0.99427673 0.00146225 0.00426101]
 [0.00433716 0.99137679 0.00428604]
 [0.00381256 0.00143613 0.9947513 ]]
pi = [0.3487011  0.34758668 0.30371223]
Iter 7: LL=-1229424.50 | Rates: N=0.79795, AF=0.09588, OLD=0.06571, YOUNG=0.03117
A =
[[0.99427763 0.00142269 0.00429969]
 [0.00445936 0.9909174  0.00462324]
 [0.0037819  0.00146646 0.99475164]]
pi = [0.34867211 0.35629109 0.2950368 ]
Iter 8: LL=-1229412.95 | Rates: N=0.79795, AF=0.09586, OLD=0.06735, YOUNG=0.03120
A =
[[0.99427826 0.00137796 0.00434379]
 [0.00457445 0.99042305 0.00500251]
 [0.00375784 0.00149787 0.99474429]]
pi = [0.34863887 0.36046658 0.29089455]
Iter 9: LL=-1229402.29 | Rates: N=0.79795, AF=0.09585, OLD=0.06893, YOUNG=0.03128
A =
[[0.9942788  0.00133016 0.00439104]
 [0.00468042 0.9899059  0.00541368]
 [0.00373976 0.00152885 0.9947314 ]]
pi = [0.34860445 0.36150071 0.28989483]
Iter 10: LL=-1229392.07 | Rates: N=0.79795, AF=0.09583, OLD=0.07051, YOUNG=0.03137
A =
[[0.99427933 0.00128078 0.00443988]
 [0.00477726 0.98937131 0.00585144]
 [0.00372664 0.00155856 0.9947148 ]]
pi = [0.34857159 0.36035199 0.29107642]
Iter 11: LL=-1229382.18 | Rates: N=0.79795, AF=0.09582, OLD=0.07210, YOUNG=0.03147
A =
[[0.99427989 0.00123088 0.00448923]
 [0.00486581 0.98882112 0.00631307]
 [0.00371746 0.00158657 0.99469596]]
pi = [0.34854189 0.35764669 0.29381141]
Iter 12: LL=-1229372.58 | Rates: N=0.79795, AF=0.09581, OLD=0.07373, YOUNG=0.03158
A =
[[0.99428049 0.00118121 0.0045383 ]
 [0.00494727 0.9882555  0.00679723]
 [0.00371135 0.00161262 0.99467603]]
pi = [0.34851599 0.35378808 0.29769593]
Iter 13: LL=-1229363.24 | Rates: N=0.79795, AF=0.09579, OLD=0.07541, YOUNG=0.03168
A =
[[0.99428114 0.00113233 0.00458653]
 [0.0050229  0.98767376 0.00730333]
 [0.00370757 0.00163654 0.9946559 ]]
pi = [0.34849391 0.3490357  0.30247039]
Iter 14: LL=-1229354.16 | Rates: N=0.79795, AF=0.09578, OLD=0.07713, YOUNG=0.03178
A =
[[0.99428184 0.00108463 0.00463353]
 [0.00509398 0.98707472 0.0078313 ]
 [0.00370553 0.00165823 0.99463624]]
pi = [0.3484753  0.34355748 0.30796722]
Iter 15: LL=-1229345.33 | Rates: N=0.79795, AF=0.09576, OLD=0.07891, YOUNG=0.03188
A =
[[0.99428259 0.00103839 0.00467903]
 [0.00516171 0.9864569  0.00838139]
 [0.00370479 0.00167764 0.99461757]]
pi = [0.34845962 0.33746327 0.3140771 ]
Final Global Rates (lambdas): [0.79794998 0.0957592  0.07890682 0.03187843]
Final transition matrix A:
[[0.99428259 0.00103839 0.00467903]
 [0.00516171 0.9864569  0.00838139]
 [0.00370479 0.00167764 0.99461757]]
Final initial distribution pi:
[0.34845962 0.33746327 0.3140771 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1700  0.0469  0.0736    4682589.0   22857411.0  95095272.0
Archaic_young     0.8277  0.9508  0.8850  471899881.0   98245119.0  24404082.0
Modern            0.0000  0.0000  0.0000          0.0  402315000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         398947          180           2446
Archaic_old       685         4677          94431
Archaic_young    2683        22683         473268

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1644  0.0047  0.0091
Archaic_young     0.8145  0.9905  0.8939

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         381208           29           2687
Archaic_old       937          520         109167
Archaic_young    3161         2616         499675

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1415038.50 | Rates: N=0.79440, AF=0.09845, OLD=0.04948, YOUNG=0.03841
A =
[[0.99341039 0.00156946 0.00502015]
 [0.00448868 0.99050742 0.0050039 ]
 [0.00412818 0.00142819 0.99444363]]
pi = [0.64748228 0.1117273  0.24079042]
Iter 2: LL=-1233272.81 | Rates: N=0.79452, AF=0.09839, OLD=0.05584, YOUNG=0.03631
A =
[[0.9934423  0.00160732 0.00495038]
 [0.00445553 0.99066066 0.0048838 ]
 [0.00409935 0.00143213 0.99446852]]
pi = [0.65634088 0.10515483 0.2385043 ]
Iter 3: LL=-1233094.69 | Rates: N=0.79452, AF=0.09830, OLD=0.06291, YOUNG=0.03416
A =
[[0.99345294 0.0016546  0.00489246]
 [0.00448589 0.99069336 0.00482075]
 [0.00407814 0.00143501 0.99448685]]
pi = [0.65661523 0.09896181 0.24442296]
Iter 4: LL=-1232932.43 | Rates: N=0.79452, AF=0.09821, OLD=0.06869, YOUNG=0.03277
A =
[[0.99346007 0.00167379 0.00486614]
 [0.004619   0.99037001 0.00501099]
 [0.00403477 0.00143667 0.99452855]]
pi = [0.65651742 0.09079149 0.25269109]
Iter 5: LL=-1232849.42 | Rates: N=0.79451, AF=0.09813, OLD=0.07308, YOUNG=0.03217
A =
[[0.99346356 0.00166219 0.00487425]
 [0.00480757 0.989751   0.00544143]
 [0.00398807 0.00144999 0.99456194]]
pi = [0.65636245 0.08177025 0.2618673 ]
Iter 6: LL=-1232807.73 | Rates: N=0.79451, AF=0.09808, OLD=0.07670, YOUNG=0.03203
A =
[[0.99346501 0.00162764 0.00490735]
 [0.005008   0.9889555  0.00603651]
 [0.0039501  0.00147354 0.99457636]]
pi = [0.6562211  0.0726038  0.27117509]
Iter 7: LL=-1232778.01 | Rates: N=0.79451, AF=0.09803, OLD=0.08001, YOUNG=0.03208
A =
[[0.99346574 0.00157803 0.00495623]
 [0.00520231 0.98805501 0.00674267]
 [0.00392269 0.00150213 0.99457519]]
pi = [0.65610883 0.06367827 0.2802129 ]
Iter 8: LL=-1232751.48 | Rates: N=0.79451, AF=0.09799, OLD=0.08328, YOUNG=0.03222
A =
[[0.99346631 0.00151935 0.00501434]
 [0.00538695 0.98708068 0.00753238]
 [0.00390395 0.00153221 0.99456384]]
pi = [0.65602229 0.0552174  0.28876031]
Iter 9: LL=-1232726.18 | Rates: N=0.79451, AF=0.09796, OLD=0.08662, YOUNG=0.03238
A =
[[0.9934669  0.00145578 0.00507733]
 [0.00556389 0.98604319 0.00839292]
 [0.00389149 0.00156178 0.99454673]]
pi = [0.65595598 0.04732811 0.2967159 ]
Iter 10: LL=-1232701.67 | Rates: N=0.79451, AF=0.09792, OLD=0.09009, YOUNG=0.03255
A =
[[0.99346754 0.00139019 0.00514227]
 [0.00573651 0.98494535 0.00931814]
 [0.00388337 0.00158965 0.99452698]]
pi = [0.65590546 0.04003606 0.30405849]
Iter 11: LL=-1232677.92 | Rates: N=0.79451, AF=0.09789, OLD=0.09372, YOUNG=0.03272
A =
[[0.99346823 0.00132457 0.0052072 ]
 [0.00590788 0.98378824 0.01030388]
 [0.00387819 0.00161512 0.99450669]]
pi = [0.65586736 0.03332681 0.31080583]
Iter 12: LL=-1232655.01 | Rates: N=0.79451, AF=0.09785, OLD=0.09751, YOUNG=0.03289
A =
[[0.99346894 0.00126033 0.00527072]
 [0.0060803  0.98257374 0.01134596]
 [0.003875   0.00163777 0.99448723]]
pi = [0.65583925 0.02718413 0.31697662]
Iter 13: LL=-1232633.08 | Rates: N=0.79451, AF=0.09782, OLD=0.10145, YOUNG=0.03305
A =
[[0.99346965 0.00119843 0.00533192]
 [0.00625535 0.98130506 0.01243959]
 [0.00387314 0.00165742 0.99446945]]
pi = [0.65581947 0.02161574 0.32256479]
Iter 14: LL=-1232612.23 | Rates: N=0.79451, AF=0.09778, OLD=0.10554, YOUNG=0.03321
A =
[[0.99347034 0.0011395  0.00539016]
 [0.00643417 0.97998612 0.0135797 ]
 [0.00387217 0.00167398 0.99445385]]
pi = [0.65580702 0.01666089 0.32753209]
Iter 15: LL=-1232592.54 | Rates: N=0.79450, AF=0.09774, OLD=0.10976, YOUNG=0.03337
A =
[[0.993471   0.0010839  0.0054451 ]
 [0.00661771 0.97862076 0.01476153]
 [0.00387176 0.00168749 0.99444076]]
pi = [0.65580132 0.01237846 0.33182022]
Final Global Rates (lambdas): [0.79450433 0.09774406 0.10976406 0.03336745]
Final transition matrix A:
[[0.993471   0.0010839  0.0054451 ]
 [0.00661771 0.97862076 0.01476153]
 [0.00387176 0.00168749 0.99444076]]
Final initial distribution pi:
[0.65580132 0.01237846 0.33182022]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.2282,0.0403,0.0685,4457625.0,15079375.0,106183406.0
Archaic_young,0.8163,0.9663,0.8850,485885059.0,109336941.0,16951717.0
Modern,0.0000,0.0000,0.0000,0.0,385241000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         381211          156           2557
Archaic_old       949         4445         105230
Archaic_young    3081        14936         487435

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5203  0.0022  0.0044
Archaic_young     0.8250  0.9944  0.9018

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         369962            1           2966
Archaic_old      1096          233         104637
Archaic_young    3813          213         517079

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1412263.70 | Rates: N=0.78859, AF=0.09741, OLD=0.05148, YOUNG=0.04139
A =
[[0.99271669 0.00163368 0.00564963]
 [0.0048923  0.98905673 0.00605097]
 [0.00437049 0.00154304 0.99408647]]
pi = [0.20124417 0.26577962 0.53297622]
Iter 2: LL=-1235629.42 | Rates: N=0.78872, AF=0.09754, OLD=0.05741, YOUNG=0.03944
A =
[[0.99277108 0.00167704 0.00555189]
 [0.00486042 0.98920369 0.00593589]
 [0.00432775 0.00153862 0.99413362]]
pi = [0.19920077 0.29749412 0.50330511]
Iter 3: LL=-1235474.85 | Rates: N=0.78871, AF=0.09744, OLD=0.06516, YOUNG=0.03722
A =
[[0.99278462 0.00175955 0.00545583]
 [0.00483662 0.98940435 0.00575903]
 [0.00431658 0.00153965 0.99414377]]
pi = [0.19912844 0.34723826 0.4536333 ]
Iter 4: LL=-1235285.88 | Rates: N=0.78871, AF=0.09727, OLD=0.07200, YOUNG=0.03544
A =
[[0.99279734 0.00182276 0.0053799 ]
 [0.00489623 0.98930745 0.00579632]
 [0.00428636 0.00153132 0.99418232]]
pi = [0.19906607 0.40584061 0.39509332]
Iter 5: LL=-1235170.87 | Rates: N=0.78871, AF=0.09714, OLD=0.07713, YOUNG=0.03453
A =
[[0.99280458 0.00184626 0.00534916]
 [0.00504316 0.98883023 0.00612661]
 [0.00424491 0.00152703 0.99422807]]
pi = [0.19897837 0.45727771 0.34374392]
Iter 6: LL=-1235118.88 | Rates: N=0.78870, AF=0.09704, OLD=0.08110, YOUNG=0.03423
A =
[[0.99280774 0.00183683 0.00535544]
 [0.00522785 0.98809985 0.0066723 ]
 [0.00420658 0.00153327 0.99426015]]
pi = [0.19887397 0.49406791 0.30705812]
Iter 7: LL=-1235088.46 | Rates: N=0.78870, AF=0.09698, OLD=0.08455, YOUNG=0.03422
A =
[[0.99280931 0.00180519 0.00538549]
 [0.00541765 0.98722513 0.00735722]
 [0.00417686 0.00154706 0.99427608]]
pi = [0.19876371 0.51712138 0.28411491]
Iter 8: LL=-1235063.35 | Rates: N=0.78870, AF=0.09693, OLD=0.08787, YOUNG=0.03434
A =
[[0.99281045 0.00175951 0.00543004]
 [0.00559966 0.98626154 0.0081388 ]
 [0.00415584 0.0015648  0.99427936]]
pi = [0.19865249 0.52962421 0.2717233 ]
Iter 9: LL=-1235039.68 | Rates: N=0.78870, AF=0.09688, OLD=0.09122, YOUNG=0.03450
A =
[[0.99281153 0.00170528 0.00548319]
 [0.00577057 0.98523302 0.00899641]
 [0.00414196 0.00158421 0.99427383]]
pi = [0.19854144 0.53434238 0.26711618]
Iter 10: LL=-1235016.68 | Rates: N=0.78870, AF=0.09683, OLD=0.09469, YOUNG=0.03467
A =
[[0.99281268 0.00164616 0.00554116]
 [0.00593086 0.98414938 0.00991976]
 [0.00413345 0.00160395 0.9942626 ]]
pi = [0.19843026 0.53328291 0.26828683]
Iter 11: LL=-1234994.27 | Rates: N=0.78870, AF=0.09679, OLD=0.09830, YOUNG=0.03484
A =
[[0.99281392 0.00158471 0.00560137]
 [0.00608235 0.98301524 0.0109024 ]
 [0.0041288  0.00162313 0.99424807]]
pi = [0.19831836 0.52791559 0.27376606]
Iter 12: LL=-1234972.55 | Rates: N=0.78869, AF=0.09675, OLD=0.10205, YOUNG=0.03501
A =
[[0.99281523 0.00152275 0.00566202]
 [0.00622717 0.98183414 0.0119387 ]
 [0.00412683 0.00164114 0.99423203]]
pi = [0.19820549 0.51938313 0.28241138]
Iter 13: LL=-1234951.69 | Rates: N=0.78869, AF=0.09671, OLD=0.10594, YOUNG=0.03517
A =
[[0.99281657 0.00146163 0.0057218 ]
 [0.00636741 0.98060997 0.01302263]
 [0.00412665 0.00165752 0.99421583]]
pi = [0.19809199 0.50862353 0.29328448]
Iter 14: LL=-1234931.84 | Rates: N=0.78869, AF=0.09666, OLD=0.10994, YOUNG=0.03533
A =
[[0.9928179  0.00140234 0.00577976]
 [0.00650503 0.97934738 0.01414759]
 [0.00412758 0.00167197 0.99420044]]
pi = [0.1979785  0.49643286 0.30558864]
Iter 15: LL=-1234913.15 | Rates: N=0.78868, AF=0.09662, OLD=0.11404, YOUNG=0.03548
A =
[[0.99281917 0.0013456  0.00583524]
 [0.00664185 0.97805147 0.01530668]
 [0.00412915 0.00168432 0.99418653]]
pi = [0.19786568 0.4834942  0.31864012]
Final Global Rates (lambdas): [0.78868466 0.09662316 0.11404464 0.03548017]
Final transition matrix A:
[[0.99281917 0.0013456  0.00583524]
 [0.00664185 0.97805147 0.01530668]
 [0.00412915 0.00168432 0.99418653]]
Final initial distribution pi:
[0.19786568 0.4834942  0.31864012]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.2210,0.0426,0.0714,4517051.0,15924949.0,101486509.0
Archaic_young,0.8268,0.9645,0.8903,499864848.0,104749152.0,18380699.0
Modern,0.0000,0.0000,0.0000,0.0,374944000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         369957          247           2725
Archaic_old      1078         4515         100373
Archaic_young    3909        15680         501516

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old        0.981  0.0017  0.0034
Archaic_young      0.835  0.9936  0.9074

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         392548            2           3493
Archaic_old       997          164          93929
Archaic_young    4505            0         504362

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1434290.13 | Rates: N=0.79544, AF=0.09603, OLD=0.05776, YOUNG=0.04723
A =
[[0.99235837 0.00166745 0.00597418]
 [0.00559281 0.98756493 0.00684226]
 [0.00507524 0.00172612 0.99319865]]
pi = [0.59168675 0.11951724 0.288796  ]
Iter 2: LL=-1252204.99 | Rates: N=0.79560, AF=0.09609, OLD=0.06454, YOUNG=0.04504
A =
[[0.9924306  0.00169685 0.00587255]
 [0.0055421  0.9877755  0.0066824 ]
 [0.00501602 0.00173068 0.9932533 ]]
pi = [0.60105329 0.10361574 0.29533098]
Iter 3: LL=-1252030.28 | Rates: N=0.79560, AF=0.09599, OLD=0.07383, YOUNG=0.04238
A =
[[0.99244501 0.00177112 0.00578388]
 [0.00551862 0.98805915 0.00642223]
 [0.00500192 0.00174767 0.99325041]]
pi = [0.60128071 0.08270913 0.31601016]
Iter 4: LL=-1251796.73 | Rates: N=0.79559, AF=0.09581, OLD=0.08227, YOUNG=0.04013
A =
[[0.99245789 0.00183359 0.00570852]
 [0.00562013 0.98796645 0.00641342]
 [0.00495761 0.00175781 0.99328458]]
pi = [0.60122479 0.05724227 0.34153294]
Iter 5: LL=-1251646.32 | Rates: N=0.79558, AF=0.09566, OLD=0.08867, YOUNG=0.03894
A =
[[0.99246656 0.00185868 0.00567476]
 [0.00584198 0.98738852 0.0067695 ]
 [0.00489333 0.00177537 0.9933313 ]]
pi = [0.60110705 0.03491949 0.36397346]
Iter 6: LL=-1251576.96 | Rates: N=0.79557, AF=0.09554, OLD=0.09364, YOUNG=0.03851
A =
[[0.99247214 0.00184933 0.00567853]
 [0.00610568 0.986507   0.00738733]
 [0.00483334 0.00180672 0.99335993]]
pi = [0.60100907 0.01931521 0.37967572]
Iter 7: LL=-1251537.06 | Rates: N=0.79556, AF=0.09544, OLD=0.09793, YOUNG=0.03845
A =
[[0.99247613 0.00181512 0.00570875]
 [0.00636362 0.98547288 0.0081635 ]
 [0.00478751 0.00184603 0.99336646]]
pi = [0.60095283 0.00984134 0.38920583]
Iter 8: LL=-1251505.68 | Rates: N=0.79556, AF=0.09536, OLD=0.10193, YOUNG=0.03854
A =
[[0.99247945 0.00176462 0.00575592]
 [0.00659686 0.98436646 0.00903668]
 [0.00475616 0.00188786 0.99335599]]
pi = [0.60092627 0.00466782 0.39440591]
Iter 9: LL=-1251477.68 | Rates: N=0.79555, AF=0.09529, OLD=0.10587, YOUNG=0.03868
A =
[[0.9924825  0.0017042  0.0058133 ]
 [0.00680121 0.98322378 0.00997501]
 [0.00473651 0.00192915 0.99333434]]
pi = [0.60091623 0.00208006 0.3970037 ]
Iter 10: LL=-1251451.85 | Rates: N=0.79555, AF=0.09522, OLD=0.10980, YOUNG=0.03885
A =
[[0.99248537 0.00163837 0.00587626]
 [0.00697911 0.98205857 0.01096231]
 [0.00472548 0.00196822 0.9933063 ]]
pi = [0.60091467 0.00087793 0.3982074 ]
Iter 11: LL=-1251427.85 | Rates: N=0.79554, AF=0.09516, OLD=0.11377, YOUNG=0.03902
A =
[[0.99248802 0.00157039 0.00594159]
 [0.00713536 0.98087511 0.01198953]
 [0.00472052 0.00200409 0.99327539]]
pi = [6.00917409e-01 3.53437863e-04 3.98729153e-01]
Iter 12: LL=-1251405.54 | Rates: N=0.79553, AF=0.09511, OLD=0.11778, YOUNG=0.03919
A =
[[0.9924904  0.00150264 0.00600697]
 [0.00727494 0.97967456 0.01305049]
 [0.00471965 0.00203625 0.9932441 ]]
pi = [6.00922482e-01 1.36548239e-04 3.98940970e-01]
Iter 13: LL=-1251384.86 | Rates: N=0.79553, AF=0.09506, OLD=0.12183, YOUNG=0.03935
A =
[[0.99249246 0.00143679 0.00607075]
 [0.0074023  0.97845747 0.01414023]
 [0.00472145 0.00206449 0.99321407]]
pi = [6.00928921e-01 5.09023943e-05 3.99020177e-01]
Iter 14: LL=-1251365.75 | Rates: N=0.79552, AF=0.09501, OLD=0.12592, YOUNG=0.03952
A =
[[0.99249423 0.00137396 0.00613181]
 [0.00752123 0.97722415 0.01525462]
 [0.00472485 0.00208885 0.9931863 ]]
pi = [6.00936202e-01 1.83976183e-05 3.99045400e-01]
Iter 15: LL=-1251348.11 | Rates: N=0.79552, AF=0.09496, OLD=0.13005, YOUNG=0.03968
A =
[[0.99249572 0.00131482 0.00618946]
 [0.00763499 0.97597435 0.01639066]
 [0.0047291  0.00210953 0.99316138]]
pi = [6.00943991e-01 6.47426992e-06 3.99049535e-01]
Final Global Rates (lambdas): [0.79551945 0.09495771 0.13004689 0.03968007]
Final transition matrix A:
[[0.99249572 0.00131482 0.00618946]
 [0.00763499 0.97597435 0.01639066]
 [0.0047291  0.00210953 0.99316138]]
Final initial distribution pi:
[6.00943991e-01 6.47426992e-06 3.99049535e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.1833  0.0448  0.0720    4261081.0   18980919.0  90809067.0
Archaic_young     0.8361  0.9570  0.8925  483971615.0   94853385.0  21733142.0
Modern            0.0000  0.0000  0.0000          0.0  397933000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         392537          243           3263
Archaic_old      1048         4253          89789
Archaic_young    4348        18746         485773

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.0000  0.0000  0.0000
Archaic_young     0.8258  0.9919  0.9013

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         390470            3           3632
Archaic_old      1273            0          99365
Archaic_young    4854          583         499820

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1452481.89 | Rates: N=0.79890, AF=0.09734, OLD=0.06507, YOUNG=0.05379
A =
[[0.99189207 0.00173745 0.00637048]
 [0.00583776 0.98653278 0.00762945]
 [0.00538753 0.00191048 0.99270199]]
pi = [0.21907321 0.23220351 0.54872329]
Iter 2: LL=-1266769.91 | Rates: N=0.79905, AF=0.09744, OLD=0.07333, YOUNG=0.05119
A =
[[0.99201823 0.0017613  0.00622048]
 [0.00571988 0.98684903 0.00743109]
 [0.00530179 0.00191868 0.99277953]]
pi = [0.20958565 0.21809129 0.57232305]
Iter 3: LL=-1266538.08 | Rates: N=0.79904, AF=0.09737, OLD=0.08476, YOUNG=0.04781
A =
[[0.99203713 0.00184704 0.00611583]
 [0.00564626 0.98726622 0.00708752]
 [0.0052982  0.00193805 0.99276375]]
pi = [0.20867616 0.19017314 0.6011507 ]
Iter 4: LL=-1266223.82 | Rates: N=0.79903, AF=0.09723, OLD=0.09467, YOUNG=0.04505
A =
[[0.99204867 0.00191687 0.00603446]
 [0.0057263  0.98721959 0.00705411]
 [0.00526109 0.00194197 0.99279695]]
pi = [0.20868743 0.15196522 0.63934735]
Iter 5: LL=-1266041.45 | Rates: N=0.79902, AF=0.09711, OLD=0.10169, YOUNG=0.04372
A =
[[0.99205378 0.00194488 0.00600134]
 [0.00593348 0.98661822 0.0074483 ]
 [0.00520193 0.00195604 0.99284203]]
pi = [0.20884237 0.11434108 0.67681655]
Iter 6: LL=-1265969.15 | Rates: N=0.79902, AF=0.09701, OLD=0.10682, YOUNG=0.04329
A =
[[0.99205511 0.00193878 0.00600611]
 [0.00617023 0.98570463 0.00812514]
 [0.00514869 0.00198923 0.99286208]]
pi = [0.20904044 0.08309676 0.7078628 ]
Iter 7: LL=-1265931.35 | Rates: N=0.79901, AF=0.09695, OLD=0.11105, YOUNG=0.04325
A =
[[0.99205529 0.00191038 0.00603433]
 [0.00639023 0.9846467  0.00896307]
 [0.00510962 0.00203432 0.99285605]]
pi = [0.20923107 0.05853376 0.73223517]
Iter 8: LL=-1265902.27 | Rates: N=0.79901, AF=0.09689, OLD=0.11493, YOUNG=0.04336
A =
[[0.99205533 0.00186863 0.00607604]
 [0.00658303 0.98351686 0.00990011]
 [0.00508324 0.00208503 0.99283173]]
pi = [0.20937948 0.03970569 0.75091483]
Iter 9: LL=-1265876.21 | Rates: N=0.79901, AF=0.09684, OLD=0.11871, YOUNG=0.04352
A =
[[0.99205552 0.00181946 0.00612502]
 [0.00675179 0.98233961 0.0109086 ]
 [0.00506601 0.00213785 0.99279614]]
pi = [0.20947629 0.02574226 0.76478145]
Iter 10: LL=-1265851.85 | Rates: N=0.79900, AF=0.09679, OLD=0.12251, YOUNG=0.04369
A =
[[0.99205588 0.0017667  0.00617742]
 [0.00690332 0.98112035 0.01197634]
 [0.00505478 0.00219081 0.99275441]]
pi = [0.20952735 0.01587258 0.77460006]
Iter 11: LL=-1265828.77 | Rates: N=0.79900, AF=0.09674, OLD=0.12637, YOUNG=0.04386
A =
[[0.99205638 0.00171278 0.00623084]
 [0.00704429 0.97985856 0.01309715]
 [0.00504726 0.00224263 0.99271011]]
pi = [0.20954471 0.00929693 0.78115836]
Iter 12: LL=-1265806.81 | Rates: N=0.79899, AF=0.09669, OLD=0.13033, YOUNG=0.04403
A =
[[0.99205696 0.00165932 0.00628372]
 [0.00718012 0.97855312 0.01426676]
 [0.00504194 0.00229239 0.99266567]]
pi = [0.2095411  0.00518458 0.78527432]
Iter 13: LL=-1265785.88 | Rates: N=0.79899, AF=0.09663, OLD=0.13438, YOUNG=0.04419
A =
[[0.99205757 0.00160733 0.0063351 ]
 [0.00731481 0.977204   0.0154812 ]
 [0.00503786 0.00233942 0.99262272]]
pi = [0.209527   0.00276589 0.7877071 ]
Iter 14: LL=-1265765.97 | Rates: N=0.79898, AF=0.09658, OLD=0.13853, YOUNG=0.04435
A =
[[0.99205813 0.00155751 0.00638436]
 [0.00745117 0.97581251 0.01673632]
 [0.00503444 0.00238323 0.99258233]]
pi = [0.2095096  0.00142019 0.78907021]
Iter 15: LL=-1265747.07 | Rates: N=0.79898, AF=0.09652, OLD=0.14278, YOUNG=0.04451
A =
[[0.99205859 0.00151026 0.00643114]
 [0.00759118 0.97438095 0.01802787]
 [0.00503135 0.00242346 0.99254519]]
pi = [2.09493010e-01 7.06397959e-04 7.89800592e-01]
Final Global Rates (lambdas): [0.79897892 0.09652346 0.1427761  0.04450612]
Final transition matrix A:
[[0.99205859 0.00151026 0.00643114]
 [0.00759118 0.97438095 0.01802787]
 [0.00503135 0.00242346 0.99254519]]
Final initial distribution pi:
[2.09493010e-01 7.06397959e-04 7.89800592e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2242  0.0573  0.0912    5767505.0   19959495.0  94924576.0
Archaic_young     0.8289  0.9537  0.8869  478627274.0   98811726.0  23254911.0
Modern            0.0000  0.0000  0.0000          0.0  396834000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         390556          248           3301
Archaic_old      1284         5758          93596
Archaic_young    4994        19721         480542

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.1715  0.1482  0.1590
Archaic_young     0.8389  0.8624  0.8505

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         405196          321           2160
Archaic_old      1024        13854          78811
Archaic_young    2719        66692         429223

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 10
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1427691.51 | Rates: N=0.80553, AF=0.09870, OLD=0.05185, YOUNG=0.03388
A =
[[0.99411631 0.00205588 0.00382781]
 [0.00443894 0.99229236 0.0032687 ]
 [0.00403122 0.00160385 0.99436493]]
pi = [0.39623156 0.24591754 0.3578509 ]
Iter 2: LL=-1236585.20 | Rates: N=0.80565, AF=0.09853, OLD=0.05593, YOUNG=0.03219
A =
[[0.99413923 0.0020593  0.00380147]
 [0.00458987 0.9920673  0.00334284]
 [0.00392994 0.00157449 0.99449557]]
pi = [0.40091163 0.25645856 0.34262981]
Iter 3: LL=-1236500.59 | Rates: N=0.80565, AF=0.09846, OLD=0.05945, YOUNG=0.03116
A =
[[0.99414355 0.00205226 0.00380419]
 [0.0047848  0.99170627 0.00350893]
 [0.00385091 0.00156197 0.99458712]]
pi = [0.40094227 0.2665144  0.33254333]
Iter 4: LL=-1236452.33 | Rates: N=0.80565, AF=0.09840, OLD=0.06227, YOUNG=0.03068
A =
[[0.99414541 0.00202432 0.00383027]
 [0.00498391 0.99124234 0.00377375]
 [0.00378677 0.00156708 0.99464615]]
pi = [0.40077337 0.27227973 0.3269469 ]
Iter 5: LL=-1236424.68 | Rates: N=0.80565, AF=0.09835, OLD=0.06461, YOUNG=0.03054
A =
[[0.99414614 0.00197944 0.00387442]
 [0.00517138 0.99071184 0.00411678]
 [0.00374068 0.00158511 0.99467421]]
pi = [0.40062721 0.27404729 0.3253255 ]
Iter 6: LL=-1236404.63 | Rates: N=0.80565, AF=0.09832, OLD=0.06670, YOUNG=0.03056
A =
[[0.99414645 0.00192277 0.00393078]
 [0.00534175 0.99013996 0.00451829]
 [0.00371044 0.00161014 0.99467942]]
pi = [0.4005072 0.2728106 0.3266822]
Iter 7: LL=-1236387.07 | Rates: N=0.80565, AF=0.09829, OLD=0.06868, YOUNG=0.03066
A =
[[0.9941467  0.00185856 0.00399474]
 [0.0054944  0.98954084 0.00496476]
 [0.00369258 0.00163812 0.9946693 ]]
pi = [0.40040738 0.26945664 0.33013598]
Iter 8: LL=-1236370.54 | Rates: N=0.80565, AF=0.09826, OLD=0.07064, YOUNG=0.03078
A =
[[0.99414699 0.00178998 0.00406303]
 [0.00563055 0.98892167 0.00544777]
 [0.00368395 0.00166671 0.99464934]]
pi = [0.40032388 0.26462838 0.33504775]
Iter 9: LL=-1236354.68 | Rates: N=0.80565, AF=0.09824, OLD=0.07262, YOUNG=0.03092
A =
[[0.99414736 0.00171926 0.00413338]
 [0.00575203 0.98828596 0.00596201]
 [0.00368204 0.0016946  0.99462335]]
pi = [0.40025433 0.25877082 0.34097485]
Iter 10: LL=-1236339.44 | Rates: N=0.80565, AF=0.09822, OLD=0.07462, YOUNG=0.03106
A =
[[0.99414781 0.00164806 0.00420413]
 [0.00586073 0.9876354  0.00650387]
 [0.00368493 0.00172104 0.99459402]]
pi = [0.40019713 0.25219374 0.34760913]
Iter 11: LL=-1236324.86 | Rates: N=0.80565, AF=0.09820, OLD=0.07667, YOUNG=0.03119
A =
[[0.99414833 0.0015776  0.00427407]
 [0.00595843 0.98697086 0.0070707 ]
 [0.00369117 0.00174558 0.99456325]]
pi = [0.40015096 0.24511774 0.35473129]
Iter 12: LL=-1236310.95 | Rates: N=0.80565, AF=0.09818, OLD=0.07875, YOUNG=0.03133
A =
[[0.99414892 0.00150882 0.00434226]
 [0.00604676 0.9862929  0.00766035]
 [0.00369966 0.00176797 0.99453237]]
pi = [0.40011469 0.23770429 0.36218102]
Iter 13: LL=-1236297.76 | Rates: N=0.80565, AF=0.09817, OLD=0.08086, YOUNG=0.03146
A =
[[0.99414955 0.0014424  0.00440805]
 [0.00612713 0.98560189 0.00827098]
 [0.00370959 0.00178809 0.99450232]]
pi = [0.40008731 0.23007482 0.36983787]
Iter 14: LL=-1236285.31 | Rates: N=0.80565, AF=0.09815, OLD=0.08300, YOUNG=0.03158
A =
[[0.99415023 0.00137883 0.00447094]
 [0.00620079 0.9848982  0.00890101]
 [0.00372037 0.00180591 0.99447372]]
pi = [0.40006789 0.22232292 0.37760918]
Iter 15: LL=-1236273.58 | Rates: N=0.80565, AF=0.09813, OLD=0.08518, YOUNG=0.03171
A =
[[0.99415094 0.00131842 0.00453064]
 [0.00626883 0.9841821  0.00954907]
 [0.00373157 0.00182145 0.99444698]]
pi = [0.40005566 0.21452206 0.38542228]
Final Global Rates (lambdas): [0.80565069 0.09812993 0.08517604 0.03170958]
Final transition matrix A:
[[0.99415094 0.00131842 0.00453064]
 [0.00626883 0.9841821  0.00954907]
 [0.00373157 0.00182145 0.99444698]]
Final initial distribution pi:
[0.40005566 0.21452206 0.38542228]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2489  0.0869  0.1288    8130815.0   24540185.0  85442798.0
Archaic_young     0.8423  0.9480  0.8920  470500269.0   88105731.0  25803694.0
Modern            0.0000  0.0000  0.0000          0.0  408723000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         405171          281           2225
Archaic_old       971         8140          84578
Archaic_young    2581        24250         471803

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2157  0.0765  0.1130
Archaic_young     0.8370  0.9427  0.8867

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         394988          180           2603
Archaic_old      1131         7390          88256
Archaic_young    3210        26738         475504

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1426348.77 | Rates: N=0.80239, AF=0.09860, OLD=0.05492, YOUNG=0.03614
A =
[[0.99338457 0.00201899 0.00459644]
 [0.00512284 0.99050509 0.00437208]
 [0.00425633 0.001608   0.99413567]]
pi = [0.64355269 0.10431526 0.25213205]
Iter 2: LL=-1238531.49 | Rates: N=0.80252, AF=0.09856, OLD=0.06077, YOUNG=0.03393
A =
[[0.99342379 0.00203994 0.00453627]
 [0.00526675 0.99039429 0.00433896]
 [0.00416255 0.00157423 0.99426322]]
pi = [0.6562958  0.07070653 0.27299767]
Iter 3: LL=-1238393.22 | Rates: N=0.80252, AF=0.09849, OLD=0.06564, YOUNG=0.03262
A =
[[0.99342788 0.00204967 0.00452245]
 [0.00549473 0.9900838  0.00442147]
 [0.00409118 0.00155029 0.99435852]]
pi = [0.65662073 0.04160985 0.30176942]
Iter 4: LL=-1238324.55 | Rates: N=0.80252, AF=0.09844, OLD=0.06922, YOUNG=0.03207
A =
[[0.99342825 0.00202853 0.00454322]
 [0.00575671 0.98959054 0.00465275]
 [0.00402868 0.00153914 0.99443218]]
pi = [0.65636238 0.02111778 0.32251984]
Iter 5: LL=-1238293.41 | Rates: N=0.80252, AF=0.09839, OLD=0.07200, YOUNG=0.03195
A =
[[0.99342781 0.00198472 0.00458747]
 [0.00601498 0.98899517 0.00498985]
 [0.00398267 0.00153893 0.9944784 ]]
pi = [0.65615556 0.00967462 0.33416983]
Iter 6: LL=-1238273.81 | Rates: N=0.80252, AF=0.09836, OLD=0.07442, YOUNG=0.03203
A =
[[0.99342736 0.00192679 0.00464585]
 [0.00625384 0.98834905 0.00539711]
 [0.00395282 0.00154455 0.99450263]]
pi = [0.65604953 0.00416172 0.33978875]
Iter 7: LL=-1238257.42 | Rates: N=0.80252, AF=0.09833, OLD=0.07670, YOUNG=0.03217
A =
[[0.99342707 0.00186084 0.00471209]
 [0.00646942 0.98767618 0.0058544 ]
 [0.00393603 0.00155266 0.99451131]]
pi = [0.65601459 0.00172463 0.34226078]
Iter 8: LL=-1238242.21 | Rates: N=0.80252, AF=0.09831, OLD=0.07897, YOUNG=0.03235
A =
[[0.99342697 0.00179077 0.00478226]
 [0.0066628  0.98698544 0.00635176]
 [0.00392901 0.00156154 0.99450944]]
pi = [0.65601885 0.00069881 0.34328235]
Iter 9: LL=-1238227.65 | Rates: N=0.80252, AF=0.09828, OLD=0.08127, YOUNG=0.03252
A =
[[0.99342704 0.00171913 0.00485383]
 [0.00683682 0.9862787  0.00688449]
 [0.00392903 0.0015703  0.99450066]]
pi = [6.56042782e-01 2.79226347e-04 3.43677991e-01]
Iter 10: LL=-1238213.60 | Rates: N=0.80252, AF=0.09826, OLD=0.08362, YOUNG=0.03269
A =
[[0.99342724 0.00164759 0.00492517]
 [0.00699475 0.98555489 0.00745036]
 [0.00393398 0.00157845 0.99448757]]
pi = [6.56076186e-01 1.10598630e-04 3.43813215e-01]
Iter 11: LL=-1238200.03 | Rates: N=0.80252, AF=0.09824, OLD=0.08604, YOUNG=0.03285
A =
[[0.99342754 0.00157731 0.00499515]
 [0.0071398  0.98481188 0.00804832]
 [0.00394227 0.00158569 0.99447204]]
pi = [6.56113883e-01 4.35747613e-05 3.43842542e-01]
Iter 12: LL=-1238186.91 | Rates: N=0.80252, AF=0.09822, OLD=0.08854, YOUNG=0.03301
A =
[[0.99342792 0.00150908 0.005063  ]
 [0.00727485 0.98404729 0.00867786]
 [0.00395273 0.00159184 0.99445543]]
pi = [6.56153166e-01 1.71199112e-05 3.43829714e-01]
Iter 13: LL=-1238174.24 | Rates: N=0.80252, AF=0.09820, OLD=0.09112, YOUNG=0.03316
A =
[[0.99342836 0.00144346 0.00512818]
 [0.00740238 0.98325891 0.00933871]
 [0.00396451 0.0015968  0.99443869]]
pi = [6.56192530e-01 6.72049787e-06 3.43800749e-01]
Iter 14: LL=-1238162.02 | Rates: N=0.80252, AF=0.09818, OLD=0.09378, YOUNG=0.03331
A =
[[0.99342885 0.0013808  0.00519035]
 [0.00752447 0.9824449  0.01003063]
 [0.00397699 0.00160048 0.99442252]]
pi = [6.56231083e-01 2.64020523e-06 3.43766277e-01]
Iter 15: LL=-1238150.25 | Rates: N=0.80252, AF=0.09816, OLD=0.09651, YOUNG=0.03345
A =
[[0.99342936 0.00132133 0.0052493 ]
 [0.00764282 0.98160393 0.01075325]
 [0.00398975 0.00160284 0.99440741]]
pi = [6.56268268e-01 1.03946515e-06 3.43730692e-01]
Final Global Rates (lambdas): [0.80251729 0.09816049 0.09651491 0.03345427]
Final transition matrix A:
[[0.99342936 0.00132133 0.0052493 ]
 [0.00764282 0.98160393 0.01075325]
 [0.00398975 0.00160284 0.99440741]]
Final initial distribution pi:
[6.56268268e-01 1.03946515e-06 3.43730692e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2632  0.0685  0.1087    6623504.0   18539496.0  90081930.0
Archaic_young     0.8384  0.9588  0.8946  482127060.0   92920940.0  20709716.0
Modern            0.0000  0.0000  0.0000          0.0  399789000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         395139          112           2520
Archaic_old      1250         6602          88925
Archaic_young    3400        18449         483603

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2230  0.0471  0.0777
Archaic_young     0.8495  0.9672  0.9045

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         386189          119           3040
Archaic_old      1232         4211          84104
Archaic_young    3592        14562         502951

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1425946.73 | Rates: N=0.79624, AF=0.09798, OLD=0.05909, YOUNG=0.04014
A =
[[0.99283022 0.00202496 0.00514482]
 [0.00548918 0.98915594 0.00535488]
 [0.00446091 0.00172435 0.99381474]]
pi = [0.42699339 0.24658366 0.32642295]
Iter 2: LL=-1243081.63 | Rates: N=0.79636, AF=0.09806, OLD=0.06606, YOUNG=0.03758
A =
[[0.99290546 0.00205921 0.00503534]
 [0.00559299 0.9891355  0.0052715 ]
 [0.00435317 0.0017091  0.99393774]]
pi = [0.4406677  0.31418033 0.24515198]
Iter 3: LL=-1242901.00 | Rates: N=0.79636, AF=0.09795, OLD=0.07228, YOUNG=0.03582
A =
[[0.9929183  0.00209686 0.00498484]
 [0.00579767 0.98888636 0.00531597]
 [0.0042797  0.001708   0.99401231]]
pi = [0.44046261 0.3757705  0.1837669 ]
Iter 4: LL=-1242798.77 | Rates: N=0.79635, AF=0.09785, OLD=0.07687, YOUNG=0.03496
A =
[[0.99292406 0.00209874 0.0049772 ]
 [0.00606632 0.98835373 0.00557995]
 [0.00420929 0.00171932 0.99407138]]
pi = [0.43912189 0.41418981 0.1466883 ]
Iter 5: LL=-1242753.17 | Rates: N=0.79635, AF=0.09778, OLD=0.08036, YOUNG=0.03467
A =
[[0.99292667 0.00207184 0.00500149]
 [0.00635117 0.98764398 0.00600484]
 [0.00415308 0.00174269 0.99410423]]
pi = [0.43778057 0.43568784 0.1265316 ]
Iter 6: LL=-1242727.04 | Rates: N=0.79635, AF=0.09772, OLD=0.08330, YOUNG=0.03466
A =
[[0.99292796 0.00202612 0.00504592]
 [0.00662542 0.98684284 0.00653174]
 [0.00411317 0.00177204 0.99411479]]
pi = [0.4365056  0.44723083 0.11626357]
Iter 7: LL=-1242706.38 | Rates: N=0.79635, AF=0.09768, OLD=0.08601, YOUNG=0.03477
A =
[[0.99292885 0.00196897 0.00510218]
 [0.00687923 0.98599492 0.00712585]
 [0.00408725 0.00180297 0.99410978]]
pi = [0.43526938 0.45294524 0.11178538]
Iter 8: LL=-1242687.65 | Rates: N=0.79634, AF=0.09764, OLD=0.08867, YOUNG=0.03491
A =
[[0.99292971 0.00190524 0.00516505]
 [0.00711116 0.98511909 0.00776974]
 [0.00407218 0.00183317 0.99409465]]
pi = [0.43403283 0.45509012 0.11087705]
Iter 9: LL=-1242669.98 | Rates: N=0.79634, AF=0.09760, OLD=0.09134, YOUNG=0.03507
A =
[[0.99293062 0.00183811 0.00523126]
 [0.00732327 0.98422149 0.00845524]
 [0.00406517 0.00186149 0.99407334]]
pi = [0.43275617 0.45497091 0.11227292]
Iter 10: LL=-1242653.12 | Rates: N=0.79634, AF=0.09757, OLD=0.09406, YOUNG=0.03524
A =
[[0.9929316  0.00176973 0.00529866]
 [0.0075187  0.98330288 0.00917842]
 [0.00406403 0.00188731 0.99404866]]
pi = [0.43140036 0.4534183  0.11518134]
Iter 11: LL=-1242636.96 | Rates: N=0.79634, AF=0.09754, OLD=0.09685, YOUNG=0.03540
A =
[[0.99293262 0.0017016  0.00536578]
 [0.00770061 0.98236229 0.0099371 ]
 [0.0040671  0.00191028 0.99402261]]
pi = [0.42992744 0.45101473 0.11905783]
Iter 12: LL=-1242621.49 | Rates: N=0.79634, AF=0.09751, OLD=0.09971, YOUNG=0.03555
A =
[[0.99293364 0.00163477 0.0054316 ]
 [0.00787178 0.98139855 0.01072967]
 [0.00407315 0.00193023 0.99399662]]
pi = [0.42830146 0.4481998  0.12349874]
Iter 13: LL=-1242606.66 | Rates: N=0.79633, AF=0.09748, OLD=0.10264, YOUNG=0.03571
A =
[[0.99293465 0.00156995 0.0054954 ]
 [0.00803452 0.98041082 0.01155465]
 [0.00408127 0.00194705 0.99397167]]
pi = [0.42649102 0.44531844 0.12819054]
Iter 14: LL=-1242592.48 | Rates: N=0.79633, AF=0.09745, OLD=0.10566, YOUNG=0.03586
A =
[[0.99293565 0.00150762 0.00555673]
 [0.00819079 0.97939862 0.01241059]
 [0.00409076 0.00196076 0.99394848]]
pi = [0.42447359 0.44264103 0.13288538]
Iter 15: LL=-1242578.91 | Rates: N=0.79633, AF=0.09742, OLD=0.10876, YOUNG=0.03601
A =
[[0.99293663 0.00144808 0.00561529]
 [0.00834224 0.97836164 0.01329611]
 [0.00410112 0.00197138 0.9939275 ]]
pi = [0.42224169 0.44036866 0.13738965]
Final Global Rates (lambdas): [0.79632938 0.09741635 0.10875788 0.03600702]
Final transition matrix A:
[[0.99293663 0.00144808 0.00561529]
 [0.00834224 0.97836164 0.01329611]
 [0.00410112 0.00197138 0.9939275 ]]
Final initial distribution pi:
[0.42224169 0.44036866 0.13738965]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2361  0.0645  0.1014    5776882.0   18688118.0  83747129.0
Archaic_young     0.8512  0.9596  0.9021  497282933.0   86949067.0  20962614.0
Modern            0.0000  0.0000  0.0000          0.0  391303000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         386312          192           2844
Archaic_old      1306         5768          82473
Archaic_young    3685        18505         498915

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2494  0.0318  0.0564
Archaic_young     0.8420  0.9769  0.9044

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         395918           64           3433
Archaic_old      1394         2909          87415
Archaic_young    4277         8715         495875

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1442045.15 | Rates: N=0.79904, AF=0.09827, OLD=0.06485, YOUNG=0.04519
A =
[[0.99225835 0.00210115 0.0056405 ]
 [0.00612619 0.9876718  0.00620201]
 [0.00508188 0.00188354 0.99303458]]
pi = [0.49665804 0.18048555 0.32285641]
Iter 2: LL=-1256624.72 | Rates: N=0.79919, AF=0.09841, OLD=0.07309, YOUNG=0.04213
A =
[[0.99235143 0.00216177 0.0054868 ]
 [0.00616488 0.98772071 0.00611441]
 [0.00497576 0.00186372 0.99316051]]
pi = [0.50304684 0.1892517  0.30770146]
Iter 3: LL=-1256395.84 | Rates: N=0.79918, AF=0.09830, OLD=0.08078, YOUNG=0.03982
A =
[[0.99236357 0.0022416  0.00539483]
 [0.00631339 0.98752638 0.00616023]
 [0.00491491 0.00186572 0.99321937]]
pi = [0.50323515 0.19322417 0.30354068]
Iter 4: LL=-1256253.02 | Rates: N=0.79917, AF=0.09819, OLD=0.08641, YOUNG=0.03857
A =
[[0.99236862 0.00228053 0.00535085]
 [0.00654124 0.98696906 0.00648971]
 [0.00485015 0.00188717 0.99326268]]
pi = [0.5032629  0.18855292 0.30818418]
Iter 5: LL=-1256190.88 | Rates: N=0.79917, AF=0.09810, OLD=0.09050, YOUNG=0.03808
A =
[[0.99237071 0.002282   0.00534728]
 [0.00678674 0.98618193 0.00703133]
 [0.00479707 0.00192874 0.99327418]]
pi = [0.50325653 0.17724207 0.31950141]
Iter 6: LL=-1256158.82 | Rates: N=0.79916, AF=0.09804, OLD=0.09380, YOUNG=0.03797
A =
[[0.99237153 0.00225739 0.00537108]
 [0.00701645 0.98528006 0.00770349]
 [0.0047601  0.00198173 0.99325817]]
pi = [0.50323066 0.16138503 0.33538431]
Iter 7: LL=-1256135.04 | Rates: N=0.79916, AF=0.09799, OLD=0.09676, YOUNG=0.03802
A =
[[0.992372   0.00221597 0.00541203]
 [0.00722046 0.98432166 0.00845787]
 [0.00473707 0.00203919 0.99322375]]
pi = [0.50319778 0.14267074 0.35413148]
Iter 8: LL=-1256113.87 | Rates: N=0.79916, AF=0.09794, OLD=0.09961, YOUNG=0.03812
A =
[[0.99237249 0.002164   0.0054635 ]
 [0.00739951 0.98332941 0.00927108]
 [0.00472451 0.00209726 0.99317823]]
pi = [0.50316426 0.12253921 0.37429653]
Iter 9: LL=-1256093.91 | Rates: N=0.79916, AF=0.09790, OLD=0.10246, YOUNG=0.03825
A =
[[0.9923731  0.00210565 0.00552125]
 [0.0075581  0.98230894 0.01013296]
 [0.00471932 0.00215388 0.9931268 ]]
pi = [0.50313273 0.10227174 0.39459553]
Iter 10: LL=-1256074.74 | Rates: N=0.79915, AF=0.09786, OLD=0.10537, YOUNG=0.03839
A =
[[0.99237383 0.0020437  0.00558247]
 [0.00770155 0.98125896 0.01103949]
 [0.00471913 0.00220782 0.99307305]]
pi = [0.50310424 0.08296273 0.41393303]
Iter 11: LL=-1256056.19 | Rates: N=0.79915, AF=0.09782, OLD=0.10836, YOUNG=0.03853
A =
[[0.99237464 0.00198013 0.00564523]
 [0.0078348  0.98017595 0.01198924]
 [0.00472219 0.00225831 0.9930195 ]]
pi = [0.50307921 0.06544486 0.43147593]
Iter 12: LL=-1256038.17 | Rates: N=0.79915, AF=0.09778, OLD=0.11147, YOUNG=0.03867
A =
[[0.99237548 0.00191637 0.00570815]
 [0.00796203 0.9790563  0.01298167]
 [0.00472727 0.0023048  0.99296793]]
pi = [0.5030577  0.05023874 0.44670356]
Iter 13: LL=-1256020.65 | Rates: N=0.79914, AF=0.09774, OLD=0.11469, YOUNG=0.03882
A =
[[0.99237632 0.00185345 0.00577022]
 [0.00808662 0.97789701 0.01401637]
 [0.0047335  0.00234693 0.99291957]]
pi = [0.50303953 0.03755814 0.45940233]
Iter 14: LL=-1256003.60 | Rates: N=0.79914, AF=0.09769, OLD=0.11804, YOUNG=0.03896
A =
[[0.99237715 0.00179213 0.00583072]
 [0.00821122 0.97669589 0.01509289]
 [0.0047403  0.00238445 0.99287525]]
pi = [0.50302438 0.02736345 0.46961217]
Iter 15: LL=-1255986.99 | Rates: N=0.79914, AF=0.09764, OLD=0.12153, YOUNG=0.03910
A =
[[0.99237794 0.00173292 0.00588913]
 [0.00833789 0.97545146 0.01621064]
 [0.00474724 0.00241726 0.9928355 ]]
pi = [0.50301187 0.01943889 0.47754924]
Final Global Rates (lambdas): [0.79913569 0.09764439 0.1215274  0.03910467]
Final transition matrix A:
[[0.99237794 0.00173292 0.00588913]
 [0.00833789 0.97545146 0.01621064]
 [0.00474724 0.00241726 0.9928355 ]]
Final initial distribution pi:
[0.50301187 0.01943889 0.47754924]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2722  0.0790  0.1225    7243381.0   19370619.0  84405678.0
Archaic_young     0.8461  0.9559  0.8977  483423085.0   87930915.0  22281672.0
Modern            0.0000  0.0000  0.0000          0.0  402032000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         396051          195           3169
Archaic_old      1510         7227          82981
Archaic_young    4471        19192         485204

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2689  0.0245  0.0449
Archaic_young     0.8182  0.9793  0.8915

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         383408           93           3513
Archaic_old      1374         2632         103723
Archaic_young    4716         7077         493464

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1445744.06 | Rates: N=0.79126, AF=0.09708, OLD=0.07315, YOUNG=0.05216
A =
[[0.99171884 0.00218613 0.00609503]
 [0.00611172 0.98704151 0.00684676]
 [0.00521838 0.00210693 0.99267468]]
pi = [0.21589252 0.22959629 0.55451119]
Iter 2: LL=-1265607.00 | Rates: N=0.79140, AF=0.09717, OLD=0.08285, YOUNG=0.04867
A =
[[0.99187619 0.00222514 0.00589867]
 [0.0061492  0.9871816  0.0066692 ]
 [0.0050602  0.00209938 0.99284043]]
pi = [0.20990063 0.1838849  0.60621447]
Iter 3: LL=-1265323.07 | Rates: N=0.79138, AF=0.09699, OLD=0.09217, YOUNG=0.04591
A =
[[0.99190048 0.00229322 0.00580631]
 [0.00634264 0.98701925 0.00663812]
 [0.00497344 0.00210886 0.9929177 ]]
pi = [0.20965917 0.1269696  0.66337123]
Iter 4: LL=-1265135.41 | Rates: N=0.79137, AF=0.09679, OLD=0.09921, YOUNG=0.04443
A =
[[0.99191286 0.00231364 0.0057735 ]
 [0.00662375 0.98641894 0.00695732]
 [0.00488648 0.00213699 0.99297653]]
pi = [0.20967426 0.07672526 0.71360049]
Iter 5: LL=-1265050.76 | Rates: N=0.79135, AF=0.09665, OLD=0.10451, YOUNG=0.04388
A =
[[0.99191958 0.00229012 0.0057903 ]
 [0.00693249 0.98551315 0.00755436]
 [0.0048159  0.0021864  0.99299771]]
pi = [0.20973941 0.04228277 0.74797782]
Iter 6: LL=-1265005.24 | Rates: N=0.79135, AF=0.09655, OLD=0.10892, YOUNG=0.04379
A =
[[0.99192349 0.00223746 0.00583905]
 [0.00723317 0.98443647 0.00833036]
 [0.00476564 0.00224723 0.99298714]]
pi = [0.20983393 0.02172427 0.7684418 ]
Iter 7: LL=-1264970.18 | Rates: N=0.79134, AF=0.09648, OLD=0.11299, YOUNG=0.04390
A =
[[0.99192636 0.00216755 0.00590609]
 [0.00751317 0.98326315 0.00922368]
 [0.0047324  0.00231144 0.99295616]]
pi = [0.20992144 0.01048363 0.77959493]
Iter 8: LL=-1264938.39 | Rates: N=0.79133, AF=0.09642, OLD=0.11699, YOUNG=0.04407
A =
[[0.99192897 0.00208818 0.00598284]
 [0.0077708  0.98202747 0.01020173]
 [0.00471185 0.00237467 0.99291348]]
pi = [0.20998486 0.004774   0.78524114]
Iter 9: LL=-1264908.37 | Rates: N=0.79132, AF=0.09636, OLD=0.12103, YOUNG=0.04427
A =
[[0.99193162 0.00200427 0.00606411]
 [0.00800828 0.980745   0.01124673]
 [0.00470036 0.00243469 0.99286495]]
pi = [0.21002361 0.00206174 0.78791465]
Iter 10: LL=-1264879.87 | Rates: N=0.79132, AF=0.09631, OLD=0.12515, YOUNG=0.04447
A =
[[0.99193436 0.00191901 0.00614663]
 [0.00822872 0.97942398 0.0123473 ]
 [0.00469525 0.00249031 0.99281444]]
pi = [0.21004344 0.00084893 0.78910763]
Iter 11: LL=-1264852.93 | Rates: N=0.79131, AF=0.09627, OLD=0.12934, YOUNG=0.04467
A =
[[0.99193718 0.00183454 0.00622828]
 [0.00843521 0.97807008 0.01349471]
 [0.00469456 0.00254091 0.99276453]]
pi = [2.10050721e-01 3.35031319e-04 7.89614247e-01]
Iter 12: LL=-1264827.61 | Rates: N=0.79130, AF=0.09622, OLD=0.13361, YOUNG=0.04487
A =
[[0.99194002 0.00175234 0.00630764]
 [0.00863049 0.97668811 0.01468141]
 [0.00469688 0.00258623 0.99271689]]
pi = [2.10050412e-01 1.27373313e-04 7.89822215e-01]
Iter 13: LL=-1264803.98 | Rates: N=0.79130, AF=0.09618, OLD=0.13794, YOUNG=0.04506
A =
[[0.99194282 0.00167343 0.00638375]
 [0.00881697 0.97528255 0.01590048]
 [0.00470117 0.00262624 0.99267259]]
pi = [2.10045813e-01 4.68732970e-05 7.89907314e-01]
Iter 14: LL=-1264782.05 | Rates: N=0.79129, AF=0.09614, OLD=0.14231, YOUNG=0.04525
A =
[[0.99194552 0.00159851 0.00645597]
 [0.00899672 0.97385775 0.01714553]
 [0.00470668 0.00266108 0.99263224]]
pi = [2.10038958e-01 1.67696266e-05 7.89944272e-01]
Iter 15: LL=-1264761.80 | Rates: N=0.79128, AF=0.09610, OLD=0.14672, YOUNG=0.04543
A =
[[0.99194807 0.001528   0.00652392]
 [0.00917148 0.97241788 0.01841064]
 [0.00471289 0.00269099 0.99259612]]
pi = [2.10031038e-01 5.85535596e-06 7.89963107e-01]
Final Global Rates (lambdas): [0.79128311 0.09609947 0.146721   0.04542985]
Final transition matrix A:
[[0.99194807 0.001528   0.00652392]
 [0.00917148 0.97241788 0.01841064]
 [0.00471289 0.00269099 0.99259612]]
Final initial distribution pi:
[2.10031038e-01 5.85535596e-06 7.89963107e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.3004,0.0705,0.1142,7592924.0,17680076.0,100142946.0
Archaic_young,0.8224,0.9583,0.8852,480974493.0,103841507.0,20907692.0
Modern,0.0000,0.0000,0.0000,0.0,389911000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         383559          225           3230
Archaic_old      1445         7587          98697
Archaic_young    4907        17461         482889

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2359  0.3436  0.2797
Archaic_young     0.8340  0.7511  0.7904

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         388358          649           1900
Archaic_old      1331        37851          71277
Archaic_young    2804       122023         373807

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1422422.91 | Rates: N=0.79810, AF=0.09927, OLD=0.05604, YOUNG=0.03240
A =
[[0.99355756 0.00272958 0.00371286]
 [0.00463217 0.99243922 0.0029286 ]
 [0.0040312  0.00179883 0.99416997]]
pi = [0.40424335 0.23101769 0.36473896]
Iter 2: LL=-1236845.27 | Rates: N=0.79822, AF=0.09919, OLD=0.05938, YOUNG=0.03106
A =
[[0.99358942 0.0026921  0.00371849]
 [0.00473164 0.99214099 0.00312736]
 [0.00394665 0.00173078 0.99432257]]
pi = [0.40653117 0.20679011 0.38667872]
Iter 3: LL=-1236786.82 | Rates: N=0.79822, AF=0.09913, OLD=0.06202, YOUNG=0.03050
A =
[[0.99359223 0.00265151 0.00375626]
 [0.00482954 0.99177573 0.00339473]
 [0.00391231 0.00170109 0.9943866 ]]
pi = [0.40662097 0.18553247 0.40784656]
Iter 4: LL=-1236756.89 | Rates: N=0.79822, AF=0.09908, OLD=0.06414, YOUNG=0.03036
A =
[[0.99359338 0.0025938  0.00381282]
 [0.00491044 0.99136574 0.00372382]
 [0.00389524 0.00169287 0.9944119 ]]
pi = [0.40667243 0.16696911 0.42635846]
Iter 5: LL=-1236736.38 | Rates: N=0.79822, AF=0.09905, OLD=0.06599, YOUNG=0.03042
A =
[[0.9935944  0.00252367 0.00388193]
 [0.00497645 0.99092648 0.00409707]
 [0.00388954 0.00169653 0.99441393]]
pi = [0.40672237 0.1511192  0.44215844]
Iter 6: LL=-1236718.53 | Rates: N=0.79822, AF=0.09902, OLD=0.06774, YOUNG=0.03057
A =
[[0.99359544 0.00244538 0.00395918]
 [0.00503106 0.99046497 0.00450397]
 [0.00389114 0.00170623 0.99440264]]
pi = [0.40676724 0.13761418 0.45561858]
Iter 7: LL=-1236701.53 | Rates: N=0.79822, AF=0.09899, OLD=0.06948, YOUNG=0.03075
A =
[[0.99359655 0.00236198 0.00404147]
 [0.00507734 0.98998315 0.00493951]
 [0.00389716 0.00171888 0.99438396]]
pi = [0.40680582 0.12602385 0.46717033]
Iter 8: LL=-1236684.91 | Rates: N=0.79821, AF=0.09897, OLD=0.07126, YOUNG=0.03094
A =
[[0.99359772 0.00227565 0.00412663]
 [0.0051179  0.98948028 0.00540182]
 [0.0039057  0.00173282 0.99436148]]
pi = [0.4068381  0.11596665 0.47719526]
Iter 9: LL=-1236668.54 | Rates: N=0.79821, AF=0.09895, OLD=0.07311, YOUNG=0.03114
A =
[[0.99359897 0.00218796 0.00421307]
 [0.00515486 0.98895452 0.00589062]
 [0.00391546 0.00174705 0.99433749]]
pi = [0.40686453 0.10713024 0.48600524]
Iter 10: LL=-1236652.38 | Rates: N=0.79821, AF=0.09892, OLD=0.07503, YOUNG=0.03133
A =
[[0.99360028 0.00210008 0.00429964]
 [0.00518991 0.98840395 0.00640614]
 [0.00392563 0.0017609  0.99431347]]
pi = [0.40688575 0.0992647  0.49384955]
Iter 11: LL=-1236636.43 | Rates: N=0.79821, AF=0.09890, OLD=0.07703, YOUNG=0.03152
A =
[[0.99360164 0.00201293 0.00438543]
 [0.00522431 0.98782715 0.00694854]
 [0.0039357  0.00177387 0.99429043]]
pi = [0.4069024  0.09217028 0.50092731]
Iter 12: LL=-1236620.73 | Rates: N=0.79821, AF=0.09888, OLD=0.07912, YOUNG=0.03170
A =
[[0.99360302 0.00192724 0.00446974]
 [0.00525895 0.98722351 0.00751755]
 [0.00394537 0.00178559 0.99426904]]
pi = [0.40691512 0.08568621 0.50739867]
Iter 13: LL=-1236605.35 | Rates: N=0.79821, AF=0.09886, OLD=0.08129, YOUNG=0.03189
A =
[[0.99360441 0.00184362 0.00455198]
 [0.00529442 0.98659333 0.00811224]
 [0.00395449 0.00179577 0.99424974]]
pi = [0.40692447 0.0796821  0.51339343]
Iter 14: LL=-1236590.37 | Rates: N=0.79821, AF=0.09884, OLD=0.08354, YOUNG=0.03207
A =
[[0.99360578 0.00176256 0.00463166]
 [0.0053311  0.9859379  0.00873099]
 [0.00396298 0.00180422 0.9942328 ]]
pi = [0.40693094 0.074052   0.51901706]
Iter 15: LL=-1236575.88 | Rates: N=0.79821, AF=0.09882, OLD=0.08587, YOUNG=0.03224
A =
[[0.99360714 0.00168447 0.0047084 ]
 [0.00536921 0.98525931 0.00937149]
 [0.0039708  0.00181083 0.99421837]]
pi = [0.40693493 0.06871035 0.52435472]
Final Global Rates (lambdas): [0.798207   0.09881843 0.08586959 0.0322418 ]
Final transition matrix A:
[[0.99360714 0.00168447 0.0047084 ]
 [0.00536921 0.98525931 0.00937149]
 [0.0039708  0.00181083 0.99421837]]
Final initial distribution pi:
[0.40693493 0.06871035 0.52435472]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.2808  0.1088  0.1569   11993020.0   30714980.0  98201186.0
Archaic_young     0.8215  0.9352  0.8746  464137485.0  100876515.0  32166478.0
Modern            0.0000  0.0000  0.0000          0.0  392278000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         388336          263           2308
Archaic_old      1179        12000          97280
Archaic_young    2763        30445         465426

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3031  0.2433  0.2699
Archaic_young     0.8595  0.8930  0.8759

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         397791          470           2523
Archaic_old      1496        22777          69491
Archaic_young    3185        51849         450418

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1425870.43 | Rates: N=0.80054, AF=0.09821, OLD=0.05851, YOUNG=0.03465
A =
[[0.99327174 0.0024378  0.00429047]
 [0.00568849 0.99029198 0.00401953]
 [0.0041854  0.00174138 0.99407322]]
pi = [0.5519216 0.1268457 0.3212327]
Iter 2: LL=-1239618.75 | Rates: N=0.80067, AF=0.09825, OLD=0.06313, YOUNG=0.03279
A =
[[0.99332618 0.0024373  0.00423652]
 [0.0059423  0.99001442 0.00404328]
 [0.00403913 0.00171309 0.99424778]]
pi = [0.55862375 0.08644051 0.35493575]
Iter 3: LL=-1239528.41 | Rates: N=0.80066, AF=0.09819, OLD=0.06663, YOUNG=0.03185
A =
[[0.99332846 0.00243677 0.00423477]
 [0.00621214 0.98963801 0.00414984]
 [0.00395327 0.00172129 0.99432544]]
pi = [0.5585898  0.05910263 0.38230757]
Iter 4: LL=-1239490.19 | Rates: N=0.80066, AF=0.09813, OLD=0.06910, YOUNG=0.03147
A =
[[0.99332736 0.00241083 0.00426181]
 [0.00646295 0.98918468 0.00435237]
 [0.00389142 0.00174769 0.99436089]]
pi = [0.55850614 0.04174455 0.39974931]
Iter 5: LL=-1239472.34 | Rates: N=0.80067, AF=0.09809, OLD=0.07098, YOUNG=0.03138
A =
[[0.99332628 0.00236751 0.00430621]
 [0.0066847  0.98869865 0.00461665]
 [0.00384958 0.00178366 0.99436675]]
pi = [0.55852989 0.03086107 0.41060904]
Iter 6: LL=-1239460.55 | Rates: N=0.80067, AF=0.09806, OLD=0.07256, YOUNG=0.03142
A =
[[0.99332557 0.00231418 0.00436026]
 [0.00687857 0.98820236 0.00491907]
 [0.00382289 0.00182326 0.99435384]]
pi = [0.55859507 0.02377321 0.41763172]
Iter 7: LL=-1239450.67 | Rates: N=0.80067, AF=0.09803, OLD=0.07400, YOUNG=0.03150
A =
[[0.99332518 0.00225565 0.00441917]
 [0.00704897 0.98770405 0.00524698]
 [0.00380709 0.00186339 0.99432952]]
pi = [0.5586676  0.01892451 0.42240789]
Iter 8: LL=-1239441.61 | Rates: N=0.80067, AF=0.09801, OLD=0.07539, YOUNG=0.03160
A =
[[0.99332505 0.00219487 0.00448009]
 [0.00720076 0.98720495 0.00559429]
 [0.00379897 0.00190258 0.99429845]]
pi = [0.55873586 0.0154535  0.42581064]
Iter 9: LL=-1239433.06 | Rates: N=0.80067, AF=0.09799, OLD=0.07677, YOUNG=0.03171
A =
[[0.99332511 0.00213356 0.00454134]
 [0.00733828 0.98670346 0.00595826]
 [0.00379625 0.00194013 0.99426362]]
pi = [0.5587969 0.0128715 0.4283316]
Iter 10: LL=-1239424.87 | Rates: N=0.80067, AF=0.09796, OLD=0.07815, YOUNG=0.03181
A =
[[0.99332531 0.00207276 0.00460193]
 [0.00746516 0.98619708 0.00633776]
 [0.00379732 0.0019757  0.99422698]]
pi = [0.55885055 0.01088887 0.43026058]
Iter 11: LL=-1239416.98 | Rates: N=0.80067, AF=0.09794, OLD=0.07955, YOUNG=0.03191
A =
[[0.99332561 0.0020131  0.00466129]
 [0.00758432 0.98568328 0.0067324 ]
 [0.00380105 0.00200912 0.99418984]]
pi = [0.55889745 0.00932589 0.43177665]
Iter 12: LL=-1239409.34 | Rates: N=0.80066, AF=0.09792, OLD=0.08097, YOUNG=0.03202
A =
[[0.99332599 0.0019549  0.00471911]
 [0.00769805 0.98515983 0.00714211]
 [0.00380664 0.0020403  0.99415307]]
pi = [0.55893841 0.00806639 0.4329952 ]
Iter 13: LL=-1239401.93 | Rates: N=0.80066, AF=0.09790, OLD=0.08242, YOUNG=0.03212
A =
[[0.99332642 0.00189835 0.00477523]
 [0.00780815 0.98462487 0.00756698]
 [0.00381355 0.0020692  0.99411725]]
pi = [0.5589742  0.00703242 0.43399338]
Iter 14: LL=-1239394.71 | Rates: N=0.80066, AF=0.09788, OLD=0.08390, YOUNG=0.03222
A =
[[0.99332688 0.00184355 0.00482958]
 [0.007916   0.98407688 0.00800712]
 [0.00382137 0.00209582 0.99408281]]
pi = [0.55900548 0.00617009 0.43482443]
Iter 15: LL=-1239387.66 | Rates: N=0.80066, AF=0.09785, OLD=0.08541, YOUNG=0.03232
A =
[[0.99332734 0.00179049 0.00488216]
 [0.00802266 0.98351469 0.00846264]
 [0.00382984 0.00212018 0.99404999]]
pi = [0.55903284 0.00544103 0.43552613]
Final Global Rates (lambdas): [0.8006634  0.09785408 0.08541374 0.03231895]
Final transition matrix A:
[[0.99332734 0.00179049 0.00488216]
 [0.00802266 0.98351469 0.00846264]
 [0.00382984 0.00212018 0.99404999]]
Final initial distribution pi:
[0.55903284 0.00544103 0.43552613]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3287  0.1607  0.2158   15033999.0   30702001.0  78546297.0
Archaic_young     0.8526  0.9358  0.8923  470552837.0   81364163.0  32283939.0
Modern            0.0000  0.0000  0.0000          0.0  402347000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         397770          371           2643
Archaic_old      1445        15059          77260
Archaic_young    3132        30306         472014

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3425  0.1847  0.2400
Archaic_young     0.8541  0.9294  0.8902

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         378224          337           2827
Archaic_old      1643        17960          77904
Archaic_young    3726        34154         483225

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1429416.83 | Rates: N=0.79456, AF=0.10169, OLD=0.06453, YOUNG=0.03846
A =
[[0.99233398 0.00255199 0.00511402]
 [0.00609273 0.9889647  0.00494257]
 [0.00444133 0.00183232 0.99372636]]
pi = [0.43514821 0.18066119 0.3841906 ]
Iter 2: LL=-1246916.57 | Rates: N=0.79467, AF=0.10196, OLD=0.07118, YOUNG=0.03601
A =
[[0.99242092 0.00254793 0.00503116]
 [0.00634654 0.98867897 0.0049745 ]
 [0.00429321 0.00177647 0.99393032]]
pi = [0.4463983  0.15635377 0.39724792]
Iter 3: LL=-1246765.78 | Rates: N=0.79466, AF=0.10188, OLD=0.07637, YOUNG=0.03486
A =
[[0.99242916 0.00254185 0.00502899]
 [0.00663656 0.98820764 0.0051558 ]
 [0.00421603 0.00176004 0.99402392]]
pi = [0.44730952 0.14055271 0.41213777]
Iter 4: LL=-1246703.05 | Rates: N=0.79466, AF=0.10180, OLD=0.08015, YOUNG=0.03448
A =
[[0.99243039 0.00250009 0.00506952]
 [0.00691935 0.98756757 0.00551308]
 [0.00416701 0.00176345 0.99406954]]
pi = [0.44748329 0.12876243 0.42375427]
Iter 5: LL=-1246672.58 | Rates: N=0.79466, AF=0.10175, OLD=0.08319, YOUNG=0.03445
A =
[[0.99243056 0.00243592 0.00513352]
 [0.00717089 0.98684219 0.00598692]
 [0.00414142 0.00177802 0.99408056]]
pi = [0.44756452 0.11959959 0.43283589]
Iter 6: LL=-1246650.43 | Rates: N=0.79465, AF=0.10171, OLD=0.08593, YOUNG=0.03457
A =
[[0.99243078 0.00236    0.00520922]
 [0.00738667 0.98607408 0.00653926]
 [0.00413302 0.00179745 0.99406954]]
pi = [0.44760455 0.11220744 0.44018801]
Iter 7: LL=-1246630.59 | Rates: N=0.79465, AF=0.10167, OLD=0.08858, YOUNG=0.03473
A =
[[0.99243133 0.00227876 0.00528991]
 [0.00756975 0.98527836 0.00715189]
 [0.00413636 0.00181863 0.99404502]]
pi = [0.44761872 0.10611313 0.44626816]
Iter 8: LL=-1246611.69 | Rates: N=0.79465, AF=0.10164, OLD=0.09126, YOUNG=0.03490
A =
[[0.99243223 0.00219593 0.00537184]
 [0.00772549 0.98445719 0.00781732]
 [0.00414743 0.00184015 0.99401242]]
pi = [0.44761571 0.10103575 0.45134854]
Iter 9: LL=-1246593.34 | Rates: N=0.79465, AF=0.10161, OLD=0.09400, YOUNG=0.03508
A =
[[0.99243344 0.00211366 0.00545289]
 [0.00785943 0.98360764 0.00853294]
 [0.00416338 0.00186131 0.99397531]]
pi = [0.44760054 0.09678271 0.45561675]
Iter 10: LL=-1246575.43 | Rates: N=0.79465, AF=0.10158, OLD=0.09683, YOUNG=0.03524
A =
[[0.99243492 0.00203324 0.00553184]
 [0.00797655 0.98272545 0.009298  ]
 [0.00418222 0.00188173 0.99393605]]
pi = [0.44757639 0.09320805 0.45921555]
Iter 11: LL=-1246557.90 | Rates: N=0.79464, AF=0.10155, OLD=0.09976, YOUNG=0.03540
A =
[[0.9924366  0.00195544 0.00560796]
 [0.00808106 0.9818067  0.01011223]
 [0.00420256 0.00190114 0.99389629]]
pi = [0.44754563 0.09019703 0.46225734]
Iter 12: LL=-1246540.76 | Rates: N=0.79464, AF=0.10151, OLD=0.10281, YOUNG=0.03556
A =
[[0.99243842 0.00188072 0.00568086]
 [0.00817637 0.98084848 0.01097515]
 [0.00422346 0.00191935 0.99385719]]
pi = [0.44751015 0.08766019 0.46482966]
Iter 13: LL=-1246524.02 | Rates: N=0.79464, AF=0.10148, OLD=0.10597, YOUNG=0.03571
A =
[[0.99244034 0.00180935 0.00575032]
 [0.00826523 0.97984895 0.01188582]
 [0.00424426 0.0019362  0.99381954]]
pi = [0.44747155 0.08553041 0.46699805]
Iter 14: LL=-1246507.72 | Rates: N=0.79463, AF=0.10144, OLD=0.10925, YOUNG=0.03586
A =
[[0.9924423  0.00174147 0.00581623]
 [0.00834993 0.97880725 0.01284282]
 [0.00426449 0.00195156 0.99378395]]
pi = [0.44743106 0.08376064 0.46880831]
Iter 15: LL=-1246491.88 | Rates: N=0.79463, AF=0.10141, OLD=0.11265, YOUNG=0.03601
A =
[[0.99244427 0.00167714 0.00587858]
 [0.00843247 0.97772306 0.01384446]
 [0.00428384 0.00196532 0.99375083]]
pi = [0.44738961 0.08232133 0.47028906]
Final Global Rates (lambdas): [0.79462973 0.1014062  0.11265481 0.03601103]
Final transition matrix A:
[[0.99244427 0.00167714 0.00587858]
 [0.00843247 0.97772306 0.01384446]
 [0.00428384 0.00196532 0.99375083]]
Final initial distribution pi:
[0.44738961 0.08232133 0.47028906]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3728  0.1040  0.1626   10114753.0   17017247.0  87172064.0
Archaic_young     0.8470  0.9621  0.9009  498628171.0   90099829.0  19617376.0
Modern            0.0000  0.0000  0.0000          0.0  384140000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         378373          142           2873
Archaic_old      1764        10118          85625
Archaic_young    4003        16872         500230

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2766  0.1353  0.1817
Archaic_young     0.8481  0.9297  0.8871

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         394224          328           3139
Archaic_old      1557        12609          79276
Archaic_young    4188        32737         471942

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1444258.73 | Rates: N=0.80093, AF=0.09632, OLD=0.07196, YOUNG=0.04408
A =
[[0.99231063 0.00246773 0.00522164]
 [0.00621892 0.98819337 0.00558771]
 [0.00487931 0.00205771 0.99306297]]
pi = [0.59544591 0.14404644 0.26050765]
Iter 2: LL=-1257561.01 | Rates: N=0.80109, AF=0.09635, OLD=0.08003, YOUNG=0.04084
A =
[[0.99243768 0.00248222 0.0050801 ]
 [0.00626753 0.98817303 0.00555944]
 [0.00473778 0.00201622 0.993246  ]]
pi = [0.61162926 0.13759941 0.25077133]
Iter 3: LL=-1257352.76 | Rates: N=0.80108, AF=0.09625, OLD=0.08613, YOUNG=0.03911
A =
[[0.99245201 0.00250426 0.00504372]
 [0.00642718 0.98783053 0.00574229]
 [0.00467733 0.00201121 0.99331145]]
pi = [0.61243364 0.13481378 0.25275258]
Iter 4: LL=-1257269.00 | Rates: N=0.80107, AF=0.09616, OLD=0.09029, YOUNG=0.03843
A =
[[0.99245617 0.00249063 0.0050532 ]
 [0.00660941 0.98724893 0.00614166]
 [0.00463332 0.00203336 0.99333332]]
pi = [0.61244243 0.13019129 0.25736628]
Iter 5: LL=-1257234.59 | Rates: N=0.80106, AF=0.09609, OLD=0.09343, YOUNG=0.03827
A =
[[0.99245821 0.00245234 0.00508945]
 [0.00677946 0.98655346 0.00666709]
 [0.00460515 0.00207235 0.9933225 ]]
pi = [0.61245225 0.12438816 0.26315959]
Iter 6: LL=-1257212.67 | Rates: N=0.80106, AF=0.09604, OLD=0.09609, YOUNG=0.03833
A =
[[0.99245961 0.00239924 0.00514116]
 [0.00692874 0.98580942 0.00726183]
 [0.00458967 0.00211869 0.99329165]]
pi = [0.61248869 0.11812229 0.26938902]
Iter 7: LL=-1257194.22 | Rates: N=0.80106, AF=0.09600, OLD=0.09855, YOUNG=0.03846
A =
[[0.99246084 0.00233778 0.00520137]
 [0.00705754 0.98504527 0.0078972 ]
 [0.00458321 0.0021674  0.99324939]]
pi = [0.61254091 0.11188198 0.27557711]
Iter 8: LL=-1257177.38 | Rates: N=0.80105, AF=0.09597, OLD=0.10093, YOUNG=0.03861
A =
[[0.99246209 0.00227198 0.00526593]
 [0.00716909 0.98427119 0.00855973]
 [0.0045828  0.0022161  0.9932011 ]]
pi = [0.61259973 0.10597358 0.28142669]
Iter 9: LL=-1257161.67 | Rates: N=0.80105, AF=0.09594, OLD=0.10329, YOUNG=0.03877
A =
[[0.99246341 0.00220432 0.00533227]
 [0.00726725 0.98348957 0.00924318]
 [0.00458626 0.00226354 0.9931502 ]]
pi = [0.61265818 0.10057787 0.28676394]
Iter 10: LL=-1257146.94 | Rates: N=0.80105, AF=0.09592, OLD=0.10565, YOUNG=0.03892
A =
[[0.9924648  0.00213642 0.00539877]
 [0.00735551 0.98270003 0.00994445]
 [0.00459209 0.00230902 0.99309888]]
pi = [0.61271099 0.09578882 0.29150019]
Iter 11: LL=-1257133.09 | Rates: N=0.80105, AF=0.09589, OLD=0.10801, YOUNG=0.03908
A =
[[0.99246624 0.00206938 0.00546437]
 [0.00743672 0.98190154 0.01066174]
 [0.00459929 0.00235214 0.99304857]]
pi = [0.61275428 0.09164034 0.29560538]
Iter 12: LL=-1257120.05 | Rates: N=0.80104, AF=0.09587, OLD=0.11039, YOUNG=0.03922
A =
[[0.99246771 0.00200392 0.00552837]
 [0.00751304 0.98109329 0.01139366]
 [0.00460719 0.00239263 0.99300017]]
pi = [0.61278547 0.08812612 0.29908841]
Iter 13: LL=-1257107.78 | Rates: N=0.80104, AF=0.09585, OLD=0.11278, YOUNG=0.03937
A =
[[0.99246919 0.0019405  0.00559031]
 [0.00758611 0.98027497 0.01213892]
 [0.00461536 0.00243037 0.99295427]]
pi = [0.61280315 0.08521448 0.30198236]
Iter 14: LL=-1257096.22 | Rates: N=0.80104, AF=0.09582, OLD=0.11518, YOUNG=0.03951
A =
[[0.99247064 0.00187945 0.0056499 ]
 [0.00765707 0.9794468  0.01289614]
 [0.00462351 0.0024653  0.99291119]]
pi = [0.61280691 0.0828591  0.30433399]
Iter 15: LL=-1257085.35 | Rates: N=0.80103, AF=0.09580, OLD=0.11760, YOUNG=0.03965
A =
[[0.99247207 0.00182096 0.00570698]
 [0.00772673 0.97860948 0.01366379]
 [0.00463148 0.00249742 0.9928711 ]]
pi = [0.61279711 0.08100637 0.30619653]
Final Global Rates (lambdas): [0.80103318 0.09579984 0.11760151 0.0396469 ]
Final transition matrix A:
[[0.99247207 0.00182096 0.00570698]
 [0.00772673 0.97860948 0.01366379]
 [0.00463148 0.00249742 0.9928711 ]]
Final initial distribution pi:
[0.61279711 0.08100637 0.30619653]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3313  0.1292  0.1859   12060169.0   24341831.0  81270852.0
Archaic_young     0.8498  0.9463  0.8955  478570796.0   84567204.0  27133961.0
Modern            0.0000  0.0000  0.0000          0.0  400460000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         394382          282           3027
Archaic_old      1630        12038          79774
Archaic_young    4448        24082         480337

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2427  0.4719  0.3206
Archaic_young     0.8693  0.7095  0.7813

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         400653          997           1772
Archaic_old      1662        46055          50227
Archaic_young    2904       142656         353074

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1427272.20 | Rates: N=0.80107, AF=0.09831, OLD=0.05787, YOUNG=0.03146
A =
[[0.99364856 0.00300165 0.00334979]
 [0.00519458 0.99195376 0.00285166]
 [0.00392419 0.00191238 0.99416343]]
pi = [0.24982338 0.31165481 0.43852181]
Iter 2: LL=-1239892.97 | Rates: N=0.80120, AF=0.09830, OLD=0.06013, YOUNG=0.03078
A =
[[0.99369685 0.00294158 0.00336157]
 [0.00536905 0.99153917 0.00309179]
 [0.00379906 0.00187397 0.99432698]]
pi = [0.24819479 0.29718534 0.45461987]
Iter 3: LL=-1239864.30 | Rates: N=0.80120, AF=0.09827, OLD=0.06204, YOUNG=0.03057
A =
[[0.99369947 0.0028979  0.00340263]
 [0.00553075 0.99110706 0.00336219]
 [0.00374822 0.0018753  0.99437648]]
pi = [0.24811588 0.28395797 0.46792615]
Iter 4: LL=-1239845.75 | Rates: N=0.80120, AF=0.09824, OLD=0.06366, YOUNG=0.03057
A =
[[0.99369972 0.00284284 0.00345744]
 [0.00566825 0.99065921 0.00367253]
 [0.0037212  0.001891   0.99438781]]
pi = [0.24808394 0.27125463 0.48066143]
Iter 5: LL=-1239830.48 | Rates: N=0.80120, AF=0.09822, OLD=0.06513, YOUNG=0.03066
A =
[[0.99369994 0.00277931 0.00352075]
 [0.00578497 0.99020087 0.00401416]
 [0.00370977 0.00191394 0.99437629]]
pi = [0.24805973 0.25903738 0.49290289]
Iter 6: LL=-1239816.38 | Rates: N=0.80120, AF=0.09820, OLD=0.06655, YOUNG=0.03080
A =
[[0.99370029 0.00271033 0.00358938]
 [0.00588498 0.98973319 0.00438183]
 [0.00370896 0.00194034 0.9943507 ]]
pi = [0.24804097 0.24723691 0.50472212]
Iter 7: LL=-1239802.84 | Rates: N=0.80120, AF=0.09818, OLD=0.06796, YOUNG=0.03094
A =
[[0.99370078 0.00263806 0.00366115]
 [0.00597176 0.98925535 0.00477289]
 [0.00371532 0.00196821 0.99431648]]
pi = [0.24802656 0.23579619 0.51617726]
Iter 8: LL=-1239789.67 | Rates: N=0.80120, AF=0.09816, OLD=0.06938, YOUNG=0.03109
A =
[[0.99370141 0.00256405 0.00373454]
 [0.00604821 0.98876561 0.00518617]
 [0.00372642 0.00199646 0.99427712]]
pi = [0.24801571 0.22468474 0.52729955]
Iter 9: LL=-1239776.79 | Rates: N=0.80120, AF=0.09815, OLD=0.07083, YOUNG=0.03124
A =
[[0.99370215 0.00248938 0.00380847]
 [0.00611676 0.98826193 0.00562131]
 [0.00374053 0.00202448 0.99423499]]
pi = [0.24800778 0.21389391 0.53809831]
Iter 10: LL=-1239764.19 | Rates: N=0.80120, AF=0.09813, OLD=0.07232, YOUNG=0.03138
A =
[[0.99370299 0.00241487 0.00388214]
 [0.00617946 0.98774226 0.00607828]
 [0.00375642 0.00205187 0.99419171]]
pi = [0.24800221 0.20342579 0.54857201]
Iter 11: LL=-1239751.86 | Rates: N=0.80120, AF=0.09812, OLD=0.07384, YOUNG=0.03153
A =
[[0.9937039  0.0023411  0.00395499]
 [0.00623804 0.98720473 0.00655723]
 [0.0037732  0.00207837 0.99414843]]
pi = [0.2479985  0.19328281 0.55871869]
Iter 12: LL=-1239739.80 | Rates: N=0.80119, AF=0.09810, OLD=0.07541, YOUNG=0.03167
A =
[[0.99370487 0.00226854 0.00402659]
 [0.00629394 0.98664772 0.00705833]
 [0.00379024 0.00210378 0.99410598]]
pi = [0.24799628 0.18346057 0.56854316]
Iter 13: LL=-1239728.02 | Rates: N=0.80119, AF=0.09809, OLD=0.07702, YOUNG=0.03180
A =
[[0.99370589 0.00219751 0.0040966 ]
 [0.00634836 0.98606988 0.00758176]
 [0.0038071  0.00212798 0.99406493]]
pi = [0.24799528 0.1739441  0.57806062]
Iter 14: LL=-1239716.51 | Rates: N=0.80119, AF=0.09807, OLD=0.07867, YOUNG=0.03194
A =
[[0.99370694 0.00212826 0.00416481]
 [0.00640228 0.98547002 0.00812769]
 [0.00382347 0.00215085 0.99402567]]
pi = [0.24799539 0.16470721 0.5872974 ]
Iter 15: LL=-1239705.29 | Rates: N=0.80119, AF=0.09806, OLD=0.08037, YOUNG=0.03207
A =
[[0.99370801 0.00206095 0.00423104]
 [0.00645653 0.98484717 0.00869629]
 [0.00383917 0.00217233 0.99398849]]
pi = [0.24799666 0.15571372 0.59628961]
Final Global Rates (lambdas): [0.80119099 0.09805827 0.08037482 0.03207271]
Final transition matrix A:
[[0.99370801 0.00206095 0.00423104]
 [0.00645653 0.98484717 0.00869629]
 [0.00383917 0.00217233 0.99398849]]
Final initial distribution pi:
[0.24799666 0.15571372 0.59628961]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3149  0.1647  0.2163   16069753.0   34957247.0  81519283.0
Archaic_young     0.8459  0.9268  0.8845  459954641.0   83763359.0  36349322.0
Modern            0.0000  0.0000  0.0000          0.0  405255000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         400687          412           2323
Archaic_old      1669        16097          80178
Archaic_young    2899        34518         461217

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.2866  0.3519  0.3159
Archaic_young     0.8741  0.8400  0.8567

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         400896          763           2309
Archaic_old      1534        31792          57254
Archaic_young    3501        78315         423636

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 19
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1431722.03 | Rates: N=0.80236, AF=0.09841, OLD=0.06279, YOUNG=0.03386
A =
[[0.99309707 0.0028388  0.00406412]
 [0.00612228 0.99006034 0.00381738]
 [0.00419497 0.00185846 0.99394657]]
pi = [0.54611531 0.13259528 0.32128942]
Iter 2: LL=-1243921.48 | Rates: N=0.80250, AF=0.09852, OLD=0.06676, YOUNG=0.03233
A =
[[0.99316513 0.00278049 0.00405437]
 [0.00633691 0.9896726  0.00399049]
 [0.00406593 0.00182621 0.99410787]]
pi = [0.55281777 0.08623724 0.36094499]
Iter 3: LL=-1243857.48 | Rates: N=0.80249, AF=0.09846, OLD=0.06979, YOUNG=0.03173
A =
[[0.99316849 0.00273195 0.00409956]
 [0.00653218 0.98923396 0.00423387]
 [0.00401919 0.0018463  0.9941345 ]]
pi = [0.55295124 0.05336403 0.39368472]
Iter 4: LL=-1243828.94 | Rates: N=0.80249, AF=0.09842, OLD=0.07209, YOUNG=0.03155
A =
[[0.99316858 0.00266352 0.0041679 ]
 [0.00670236 0.98874125 0.00455639]
 [0.00399563 0.00188384 0.99412053]]
pi = [0.55295164 0.03185842 0.41518994]
Iter 5: LL=-1243810.72 | Rates: N=0.80249, AF=0.09838, OLD=0.07402, YOUNG=0.03156
A =
[[0.99316877 0.00258456 0.00424667]
 [0.00684917 0.98822159 0.00492924]
 [0.00398654 0.00192812 0.99408534]]
pi = [0.5529627  0.01870648 0.42833082]
Iter 6: LL=-1243795.50 | Rates: N=0.80249, AF=0.09836, OLD=0.07580, YOUNG=0.03165
A =
[[0.9931692  0.00250164 0.00432916]
 [0.00697651 0.98768839 0.0053351 ]
 [0.0039869  0.00197375 0.99403935]]
pi = [0.55297764 0.0108921  0.43613025]
Iter 7: LL=-1243781.57 | Rates: N=0.80249, AF=0.09833, OLD=0.07750, YOUNG=0.03176
A =
[[0.99316981 0.00241844 0.00441175]
 [0.0070881  0.98714706 0.00576484]
 [0.00399336 0.00201832 0.99398832]]
pi = [0.55299173 0.00630661 0.44070166]
Iter 8: LL=-1243768.56 | Rates: N=0.80249, AF=0.09831, OLD=0.07918, YOUNG=0.03189
A =
[[0.99317056 0.00233698 0.00449246]
 [0.00718712 0.98659931 0.00621358]
 [0.00400371 0.0020608  0.99393549]]
pi = [0.55300371 0.00363387 0.44336242]
Iter 9: LL=-1243756.34 | Rates: N=0.80249, AF=0.09829, OLD=0.08085, YOUNG=0.03201
A =
[[0.99317139 0.00225839 0.00457021]
 [0.0072762  0.98604535 0.00667845]
 [0.00401643 0.0021008  0.99388277]]
pi = [0.55301367 0.00208396 0.44490236]
Iter 10: LL=-1243744.88 | Rates: N=0.80249, AF=0.09828, OLD=0.08251, YOUNG=0.03213
A =
[[0.99317229 0.00218326 0.00464445]
 [0.00735753 0.98548496 0.00715751]
 [0.00403049 0.0021382  0.9938313 ]]
pi = [0.55302208 0.00118952 0.4457884 ]
Iter 11: LL=-1243734.14 | Rates: N=0.80249, AF=0.09826, OLD=0.08417, YOUNG=0.03225
A =
[[0.99317323 0.00211186 0.00471491]
 [0.00743288 0.98491791 0.00764921]
 [0.00404517 0.00217303 0.9937818 ]]
pi = [0.55302935 0.00067587 0.44629478]
Iter 12: LL=-1243724.08 | Rates: N=0.80249, AF=0.09824, OLD=0.08583, YOUNG=0.03237
A =
[[0.9931742  0.00204427 0.00478153]
 [0.00750371 0.98434409 0.0081522 ]
 [0.00405996 0.00220538 0.99373466]]
pi = [5.53035794e-01 3.82330905e-04 4.46581875e-01]
Iter 13: LL=-1243714.67 | Rates: N=0.80248, AF=0.09823, OLD=0.08748, YOUNG=0.03248
A =
[[0.99317518 0.00198046 0.00484436]
 [0.00757119 0.98376356 0.00866525]
 [0.00407452 0.00223537 0.99369011]]
pi = [5.53041633e-01 2.15386849e-04 4.46742980e-01]
Iter 14: LL=-1243705.88 | Rates: N=0.80248, AF=0.09821, OLD=0.08914, YOUNG=0.03259
A =
[[0.99317617 0.00192031 0.00490352]
 [0.0076363  0.98317653 0.00918717]
 [0.00408863 0.00226312 0.99364825]]
pi = [5.53047010e-01 1.20875125e-04 4.46832115e-01]
Iter 15: LL=-1243697.65 | Rates: N=0.80248, AF=0.09819, OLD=0.09079, YOUNG=0.03270
A =
[[0.99317715 0.00186364 0.00495921]
 [0.00769981 0.98258336 0.00971683]
 [0.00410213 0.00228879 0.99360908]]
pi = [5.53052020e-01 6.75989265e-05 4.46880382e-01]
Final Global Rates (lambdas): [0.80248166 0.09819375 0.09078896 0.03270151]
Final transition matrix A:
[[0.99317715 0.00186364 0.00495921]
 [0.00769981 0.98258336 0.00971683]
 [0.00410213 0.00228879 0.99360908]]
Final initial distribution pi:
[5.53052020e-01 6.75989265e-05 4.46880382e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3784  0.1949  0.2573   17598281.0   28908719.0  72695576.0
Archaic_young     0.8625  0.9370  0.8982  471166858.0   75145142.0  31669918.0
Modern            0.0000  0.0000  0.0000          0.0  407181000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         401189          120           2659
Archaic_old      1952        17576          71052
Archaic_young    4040        28811         472601

================================================================================
RUN: {'p_old': 0.2, 'p_young': 0.5, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.3127  0.2692  0.2893
Archaic_young     0.8643  0.8876  0.8758

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         379925          658           2596
Archaic_old      1861        25712          68143
Archaic_young    3763        55871         461471

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1426024.37 | Rates: N=0.79330, AF=0.09812, OLD=0.06884, YOUNG=0.03750
A =
[[0.99243081 0.00285778 0.00471141]
 [0.00636042 0.98888085 0.00475873]
 [0.0042568  0.0019204  0.99382281]]
pi = [0.40758508 0.21282647 0.37958845]
Iter 2: LL=-1245284.91 | Rates: N=0.79343, AF=0.09831, OLD=0.07475, YOUNG=0.03539
A =
[[0.99254882 0.00282163 0.00462956]
 [0.00655739 0.9884853  0.00495731]
 [0.0041104  0.00186939 0.9940202 ]]
pi = [0.41166474 0.20153639 0.38679887]
Iter 3: LL=-1245171.07 | Rates: N=0.79342, AF=0.09823, OLD=0.07915, YOUNG=0.03454
A =
[[0.99255507 0.0027986  0.00464633]
 [0.00677419 0.98792695 0.00529886]
 [0.00406475 0.00187625 0.994059  ]]
pi = [0.41168073 0.19104433 0.39727493]
Iter 4: LL=-1245124.62 | Rates: N=0.79342, AF=0.09815, OLD=0.08244, YOUNG=0.03430
A =
[[0.9925546  0.00274534 0.00470007]
 [0.00697303 0.98724673 0.00578024]
 [0.00404482 0.00190503 0.99405015]]
pi = [0.41166005 0.18024083 0.40809912]
Iter 5: LL=-1245097.20 | Rates: N=0.79342, AF=0.09809, OLD=0.08521, YOUNG=0.03432
A =
[[0.99255414 0.00267435 0.00477151]
 [0.00714655 0.98650735 0.0063461 ]
 [0.00404059 0.00194296 0.99401645]]
pi = [0.41167136 0.17016237 0.41816627]
Iter 6: LL=-1245074.78 | Rates: N=0.79342, AF=0.09805, OLD=0.08777, YOUNG=0.03444
A =
[[0.99255409 0.00259488 0.00485104]
 [0.00729615 0.98573936 0.00696449]
 [0.00404644 0.00198331 0.99397025]]
pi = [0.41169028 0.16121042 0.4270993 ]
Iter 7: LL=-1245054.40 | Rates: N=0.79342, AF=0.09801, OLD=0.09024, YOUNG=0.03459
A =
[[0.99255437 0.0025122  0.00493343]
 [0.00742531 0.98495549 0.0076192 ]
 [0.0040586  0.00202305 0.99391835]]
pi = [0.41170598 0.15345068 0.43484333]
Iter 8: LL=-1245035.44 | Rates: N=0.79342, AF=0.09798, OLD=0.09270, YOUNG=0.03475
A =
[[0.99255492 0.00242932 0.00501577]
 [0.00753782 0.98416039 0.00830179]
 [0.00407454 0.0020608  0.99386466]]
pi = [0.4117143  0.14679885 0.44148685]
Iter 9: LL=-1245017.74 | Rates: N=0.79342, AF=0.09795, OLD=0.09516, YOUNG=0.03491
A =
[[0.99255565 0.00234798 0.00509637]
 [0.00763715 0.9833556  0.00900725]
 [0.00409255 0.00209594 0.99381151]]
pi = [0.41171427 0.14110807 0.44717765]
Iter 10: LL=-1245001.23 | Rates: N=0.79341, AF=0.09792, OLD=0.09763, YOUNG=0.03507
A =
[[0.99255653 0.00226924 0.00517423]
 [0.00772622 0.98254182 0.00973196]
 [0.00411148 0.00212818 0.99376034]]
pi = [0.41170664 0.13621286 0.45208049]
Iter 11: LL=-1244985.86 | Rates: N=0.79341, AF=0.09789, OLD=0.10011, YOUNG=0.03522
A =
[[0.99255751 0.00219372 0.00524876]
 [0.00780741 0.9817198  0.01047279]
 [0.00413057 0.00215739 0.99371204]]
pi = [0.4116931  0.13195205 0.45635485]
Iter 12: LL=-1244971.58 | Rates: N=0.79341, AF=0.09786, OLD=0.10260, YOUNG=0.03537
A =
[[0.99255857 0.00212179 0.00531964]
 [0.00788262 0.98089059 0.01122679]
 [0.00414932 0.00218358 0.9936671 ]]
pi = [0.41167571 0.12818037 0.46014392]
Iter 13: LL=-1244958.35 | Rates: N=0.79341, AF=0.09784, OLD=0.10509, YOUNG=0.03551
A =
[[0.99255967 0.00205362 0.00538672]
 [0.00795335 0.98005548 0.01199117]
 [0.0041674  0.00220682 0.99362578]]
pi = [0.41165658 0.1247734  0.46357003]
Iter 14: LL=-1244946.12 | Rates: N=0.79341, AF=0.09781, OLD=0.10758, YOUNG=0.03565
A =
[[0.99256079 0.00198927 0.00544995]
 [0.00802082 0.97921594 0.01276325]
 [0.0041846  0.00222726 0.99358814]]
pi = [0.4116376  0.12162852 0.46673387]
Iter 15: LL=-1244934.84 | Rates: N=0.79341, AF=0.09779, OLD=0.11007, YOUNG=0.03579
A =
[[0.99256191 0.00192871 0.00550938]
 [0.008086   0.9783734  0.01354061]
 [0.00420081 0.00224507 0.99355411]]
pi = [0.41162036 0.11866375 0.46971588]
Final Global Rates (lambdas): [0.79340575 0.09778752 0.11007349 0.03578826]
Final transition matrix A:
[[0.99256191 0.00192871 0.00550938]
 [0.008086   0.9783734  0.01354061]
 [0.00420081 0.00224507 0.99355411]]
Final initial distribution pi:
[0.41162036 0.11866375 0.46971588]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.2_pyoung_0.5_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.3563  0.1217  0.1814   11626759.0   21002241.0  83928526.0
Archaic_young     0.8511  0.9544  0.8998  494599294.0   86529706.0  23646253.0
Modern            0.0000  0.0000  0.0000          0.0  386242000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         380104          194           2881
Archaic_old      2052        11616          82048
Archaic_young    4086        20819         496200

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old        0.746  0.9925  0.8518
Archaic_young      0.000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         627301         2416              0
Archaic_old      3023       275815              0
Archaic_young     854        90591              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1546857.87 | Rates: N=0.89673, AF=0.09583, OLD=0.04141, YOUNG=0.03234
A =
[[9.96424512e-01 2.84723193e-03 7.28256047e-04]
 [6.24044621e-03 9.92911777e-01 8.47777165e-04]
 [6.31972377e-03 3.34175870e-03 9.90338518e-01]]
pi = [0.5996723  0.30286759 0.09746011]
Iter 2: LL=-1280950.94 | Rates: N=0.89695, AF=0.09559, OLD=0.04231, YOUNG=0.02936
A =
[[9.96424687e-01 2.82626385e-03 7.49049568e-04]
 [6.30041941e-03 9.92815485e-01 8.84095230e-04]
 [6.02215998e-03 3.14614400e-03 9.90831696e-01]]
pi = [0.59912238 0.28088104 0.11999658]
Iter 3: LL=-1280916.84 | Rates: N=0.89695, AF=0.09558, OLD=0.04357, YOUNG=0.02672
A =
[[9.96424928e-01 2.79227155e-03 7.82800033e-04]
 [6.41140857e-03 9.92649246e-01 9.39345410e-04]
 [5.69940308e-03 2.89871362e-03 9.91401883e-01]]
pi = [0.59908072 0.24598231 0.15493697]
Iter 4: LL=-1280879.33 | Rates: N=0.89695, AF=0.09557, OLD=0.04492, YOUNG=0.02484
A =
[[9.96425053e-01 2.74691449e-03 8.28032584e-04]
 [6.52977458e-03 9.92460052e-01 1.01017379e-03]
 [5.44871315e-03 2.67419261e-03 9.91877094e-01]]
pi = [0.59905277 0.20022788 0.20071935]
Iter 5: LL=-1280850.92 | Rates: N=0.89695, AF=0.09556, OLD=0.04611, YOUNG=0.02378
A =
[[9.96424954e-01 2.69569565e-03 8.79350343e-04]
 [6.62025349e-03 9.92288943e-01 1.09080323e-03]
 [5.32386039e-03 2.52263057e-03 9.92153509e-01]]
pi = [0.59908111 0.1519467  0.24897219]
Iter 6: LL=-1280833.99 | Rates: N=0.89695, AF=0.09555, OLD=0.04707, YOUNG=0.02329
A =
[[9.96424783e-01 2.64186819e-03 9.33348721e-04]
 [6.67458788e-03 9.92145918e-01 1.17949383e-03]
 [5.29486498e-03 2.43705702e-03 9.92268078e-01]]
pi = [0.59917298 0.10977771 0.29104931]
Iter 7: LL=-1280823.58 | Rates: N=0.89695, AF=0.09554, OLD=0.04784, YOUNG=0.02315
A =
[[9.96424672e-01 2.58678446e-03 9.88543270e-04]
 [6.70318616e-03 9.92020758e-01 1.27605600e-03]
 [5.31636133e-03 2.39303024e-03 9.92290608e-01]]
pi = [0.59928582 0.0771892  0.32352498]
Iter 8: LL=-1280815.72 | Rates: N=0.89695, AF=0.09554, OLD=0.04850, YOUNG=0.02319
A =
[[0.99642464 0.0025311  0.00104426]
 [0.0067182  0.99190151 0.00138029]
 [0.00535793 0.00237161 0.99227046]]
pi = [0.59937873 0.05351899 0.34710229]
Iter 9: LL=-1280808.72 | Rates: N=0.89695, AF=0.09553, OLD=0.04911, YOUNG=0.02333
A =
[[0.99642466 0.00247516 0.00110018]
 [0.00672779 0.99178026 0.00149194]
 [0.00540387 0.00236185 0.99223428]]
pi = [0.59943759 0.03678588 0.36377653]
Iter 10: LL=-1280802.01 | Rates: N=0.89695, AF=0.09553, OLD=0.04970, YOUNG=0.02353
A =
[[0.9964247  0.00241916 0.00115614]
 [0.00673649 0.99165262 0.00161089]
 [0.00544724 0.00235805 0.99219471]]
pi = [0.5994659  0.0251     0.37543411]
Iter 11: LL=-1280795.41 | Rates: N=0.89695, AF=0.09553, OLD=0.05029, YOUNG=0.02376
A =
[[0.99642475 0.00236319 0.00121207]
 [0.00674658 0.99151631 0.00173711]
 [0.00548552 0.00235734 0.99215714]]
pi = [0.59947235 0.01700004 0.3835276 ]
Iter 12: LL=-1280788.85 | Rates: N=0.89695, AF=0.09553, OLD=0.05089, YOUNG=0.02399
A =
[[0.99642479 0.00230728 0.00126793]
 [0.00675918 0.99137013 0.00187069]
 [0.00551816 0.00235827 0.99212357]]
pi = [0.59946509 0.01142414 0.38911076]
Iter 13: LL=-1280782.30 | Rates: N=0.89695, AF=0.09552, OLD=0.05151, YOUNG=0.02424
A =
[[0.99642483 0.00225143 0.00132373]
 [0.00677479 0.9912134  0.00201181]
 [0.0055455  0.00236006 0.99209444]]
pi = [0.59945014 0.00761421 0.39293565]
Iter 14: LL=-1280775.76 | Rates: N=0.89695, AF=0.09552, OLD=0.05216, YOUNG=0.02449
A =
[[0.99642487 0.00219566 0.00137947]
 [0.00679362 0.9910457  0.00216068]
 [0.00556818 0.00236226 0.99206956]]
pi = [0.59943151 0.00503199 0.3955365 ]
Iter 15: LL=-1280769.19 | Rates: N=0.89695, AF=0.09552, OLD=0.05282, YOUNG=0.02474
A =
[[0.9964249  0.00213996 0.00143513]
 [0.00681576 0.99086668 0.00231757]
 [0.00558688 0.00236458 0.99204854]]
pi = [0.59941173 0.00329688 0.39729139]
Final Global Rates (lambdas): [0.89695282 0.09551703 0.05282383 0.02474313]
Final transition matrix A:
[[0.9964249  0.00213996 0.00143513]
 [0.00681576 0.99086668 0.00231757]
 [0.00558688 0.00236458 0.99204854]]
Final initial distribution pi:
[0.59941173 0.00329688 0.39729139]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7582,0.5209,0.6175,144410248.0,46058752.0,132809867.0
Archaic_young,0.2584,0.5095,0.3429,46200220.0,132608780.0,44482423.0
Modern,0.0000,0.0000,0.0000,0.0,630722000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         627230         1401           1086
Archaic_old      2717       144809         131312
Archaic_young     775        44259          46411

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6984  0.9913  0.8194
Archaic_young     0.0000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         612894         2727              0
Archaic_old      3358       267697              0
Archaic_young    1284       112040              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1553579.48 | Rates: N=0.89721, AF=0.09719, OLD=0.04505, YOUNG=0.03614
A =
[[9.95943355e-01 3.18665065e-03 8.69994700e-04]
 [6.71779753e-03 9.92239819e-01 1.04238310e-03]
 [6.61242535e-03 3.70011776e-03 9.89687457e-01]]
pi = [0.60005997 0.30866676 0.09127327]
Iter 2: LL=-1286974.64 | Rates: N=0.89744, AF=0.09702, OLD=0.04592, YOUNG=0.03284
A =
[[9.95954236e-01 3.16093613e-03 8.84827699e-04]
 [6.77619564e-03 9.92133450e-01 1.09035424e-03]
 [6.28798846e-03 3.46580025e-03 9.90246211e-01]]
pi = [0.59994246 0.30354308 0.09651446]
Iter 3: LL=-1286934.83 | Rates: N=0.89744, AF=0.09701, OLD=0.04740, YOUNG=0.02989
A =
[[9.95954787e-01 3.13335395e-03 9.11859380e-04]
 [6.90633004e-03 9.91934087e-01 1.15958297e-03]
 [5.95536784e-03 3.16525576e-03 9.90879376e-01]]
pi = [0.59994561 0.29661961 0.10343478]
Iter 4: LL=-1286888.71 | Rates: N=0.89745, AF=0.09698, OLD=0.04900, YOUNG=0.02775
A =
[[9.95954480e-01 3.09549046e-03 9.50029911e-04]
 [7.04753979e-03 9.91703890e-01 1.24856990e-03]
 [5.69422253e-03 2.87376385e-03 9.91432014e-01]]
pi = [0.59994171 0.2877851  0.11227319]
Iter 5: LL=-1286853.40 | Rates: N=0.89745, AF=0.09694, OLD=0.05040, YOUNG=0.02654
A =
[[9.95953793e-01 3.05181225e-03 9.94394767e-04]
 [7.15439456e-03 9.91496497e-01 1.34910816e-03]
 [5.56871115e-03 2.65745603e-03 9.91773833e-01]]
pi = [0.59993564 0.2772436  0.12282077]
Iter 6: LL=-1286833.36 | Rates: N=0.89746, AF=0.09691, OLD=0.05150, YOUNG=0.02599
A =
[[0.99595312 0.00300478 0.0010421 ]
 [0.0072154  0.99132666 0.00145795]
 [0.00554918 0.00251568 0.99193514]]
pi = [0.59993163 0.26522665 0.13484172]
Iter 7: LL=-1286822.10 | Rates: N=0.89746, AF=0.09689, OLD=0.05236, YOUNG=0.02584
A =
[[0.9959527  0.00295522 0.00109209]
 [0.00724321 0.99118256 0.00157423]
 [0.00558629 0.00242364 0.99199007]]
pi = [0.59993168 0.25204363 0.14802469]
Iter 8: LL=-1286814.18 | Rates: N=0.89746, AF=0.09688, OLD=0.05308, YOUNG=0.02590
A =
[[0.99595249 0.00290366 0.00114385]
 [0.00725286 0.99104982 0.00169732]
 [0.00564644 0.002361   0.99199257]]
pi = [0.59993426 0.23802959 0.16203616]
Iter 9: LL=-1286807.28 | Rates: N=0.89746, AF=0.09687, OLD=0.05373, YOUNG=0.02607
A =
[[0.99595242 0.00285046 0.00119712]
 [0.00725441 0.99091888 0.00182671]
 [0.00571205 0.00231574 0.99197222]]
pi = [0.59993724 0.22347907 0.17658369]
Iter 10: LL=-1286800.68 | Rates: N=0.89746, AF=0.09686, OLD=0.05435, YOUNG=0.02629
A =
[[0.99595243 0.00279586 0.00125171]
 [0.00725347 0.9907844  0.00196213]
 [0.00577507 0.00228146 0.99194348]]
pi = [0.59993924 0.20863299 0.19142777]
Iter 11: LL=-1286794.15 | Rates: N=0.89746, AF=0.09685, OLD=0.05497, YOUNG=0.02654
A =
[[0.99595246 0.00273999 0.00130755]
 [0.00725296 0.99064345 0.00210359]
 [0.0058323  0.00225475 0.99191295]]
pi = [0.59993959 0.19368886 0.20637155]
Iter 12: LL=-1286787.62 | Rates: N=0.89746, AF=0.09684, OLD=0.05560, YOUNG=0.02680
A =
[[0.99595252 0.00268291 0.00136457]
 [0.00725439 0.99049431 0.0022513 ]
 [0.00588277 0.00223374 0.99188348]]
pi = [0.59993804 0.17881184 0.22125012]
Iter 13: LL=-1286781.04 | Rates: N=0.89746, AF=0.09684, OLD=0.05626, YOUNG=0.02707
A =
[[0.99595258 0.00262466 0.00142276]
 [0.00725858 0.9903358  0.00240562]
 [0.00592655 0.00221727 0.99185618]]
pi = [0.59993456 0.16414163 0.23592382]
Iter 14: LL=-1286774.39 | Rates: N=0.89746, AF=0.09683, OLD=0.05694, YOUNG=0.02733
A =
[[0.99595265 0.00256526 0.00148209]
 [0.007266   0.99016694 0.00256706]
 [0.00596407 0.00220456 0.99183136]]
pi = [0.59992923 0.14979628 0.25027449]
Iter 15: LL=-1286767.65 | Rates: N=0.89747, AF=0.09682, OLD=0.05765, YOUNG=0.02760
A =
[[0.99595272 0.00250473 0.00154255]
 [0.00727697 0.98998681 0.00273622]
 [0.00599597 0.002195   0.99180903]]
pi = [0.59992221 0.13587462 0.26420317]
Final Global Rates (lambdas): [0.89746547 0.09682295 0.0576519  0.02759961]
Final transition matrix A:
[[0.99595272 0.00250473 0.00154255]
 [0.00727697 0.98998681 0.00273622]
 [0.00599597 0.002195   0.99180903]]
Final initial distribution pi:
[0.59992221 0.13587462 0.26420317]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7072,0.5061,0.5900,136380008.0,56462992.0,133078914.0
Archaic_young,0.3024,0.5120,0.3802,57480638.0,132592362.0,54780656.0
Modern,0.0000,0.0000,0.0000,0.0,617084000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         612747         1753           1121
Archaic_old      3147       136765         131143
Archaic_young    1190        54325          57809

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7051  0.9904  0.8237
Archaic_young     0.0000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         595377         3229              0
Archaic_old      3845       282529              0
Archaic_young    1100       113920              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1545364.74 | Rates: N=0.88468, AF=0.09637, OLD=0.04973, YOUNG=0.04069
A =
[[0.99525901 0.0036897  0.00105129]
 [0.00732959 0.99145122 0.00121919]
 [0.00717059 0.00414427 0.98868514]]
pi = [0.64904377 0.26742403 0.0835322 ]
Iter 2: LL=-1289908.42 | Rates: N=0.88494, AF=0.09624, OLD=0.05060, YOUNG=0.03692
A =
[[0.99527431 0.00365861 0.00106708]
 [0.00738927 0.99133986 0.00127086]
 [0.00683014 0.00392408 0.98924577]]
pi = [0.64951023 0.25908918 0.09140059]
Iter 3: LL=-1289860.54 | Rates: N=0.88494, AF=0.09623, OLD=0.05233, YOUNG=0.03338
A =
[[0.99527587 0.00362568 0.00109845]
 [0.00753769 0.99111368 0.00134863]
 [0.00645842 0.00363259 0.98990899]]
pi = [0.6495163  0.24772175 0.10276195]
Iter 4: LL=-1289798.72 | Rates: N=0.88494, AF=0.09620, OLD=0.05432, YOUNG=0.03064
A =
[[0.99527708 0.00357637 0.00114655]
 [0.0077153  0.99082832 0.00145638]
 [0.00612977 0.00334191 0.99052833]]
pi = [0.64951738 0.23359604 0.11688658]
Iter 5: LL=-1289746.38 | Rates: N=0.88494, AF=0.09617, OLD=0.05614, YOUNG=0.02899
A =
[[0.99527802 0.00351711 0.00120487]
 [0.00786338 0.99055186 0.00158476]
 [0.00594525 0.00314211 0.99091263]]
pi = [0.64952167 0.21858852 0.13188981]
Iter 6: LL=-1289715.12 | Rates: N=0.88494, AF=0.09614, OLD=0.05760, YOUNG=0.02819
A =
[[0.99527868 0.00345267 0.00126866]
 [0.00795845 0.99031221 0.00172934]
 [0.00588821 0.00303903 0.99107277]]
pi = [0.64952948 0.20370438 0.14676614]
Iter 7: LL=-1289697.58 | Rates: N=0.88494, AF=0.09611, OLD=0.05876, YOUNG=0.02791
A =
[[0.9952792  0.00338495 0.00133585]
 [0.00801243 0.99009865 0.00188892]
 [0.00590378 0.00299913 0.99109709]]
pi = [0.6495395  0.18919963 0.16126087]
Iter 8: LL=-1289685.40 | Rates: N=0.88494, AF=0.09610, OLD=0.05972, YOUNG=0.02790
A =
[[0.9952797  0.00331496 0.00140534]
 [0.00804323 0.98989428 0.00206249]
 [0.0059518  0.00299314 0.99105506]]
pi = [0.6495504 0.1751958 0.1752538]
Iter 9: LL=-1289674.80 | Rates: N=0.88494, AF=0.09608, OLD=0.06060, YOUNG=0.02803
A =
[[0.9952802  0.00324333 0.00147647]
 [0.00806314 0.98968763 0.00224922]
 [0.00601091 0.00300369 0.9909854 ]]
pi = [0.6495614  0.16183345 0.18860515]
Iter 10: LL=-1289664.58 | Rates: N=0.88494, AF=0.09608, OLD=0.06145, YOUNG=0.02824
A =
[[0.99528069 0.00317047 0.00154885]
 [0.00807891 0.98947236 0.00244873]
 [0.00607128 0.00302177 0.99090695]]
pi = [0.64957208 0.14924442 0.2011835 ]
Iter 11: LL=-1289654.40 | Rates: N=0.88494, AF=0.09607, OLD=0.06229, YOUNG=0.02848
A =
[[0.99528117 0.0030966  0.00162223]
 [0.00809391 0.98924506 0.00266103]
 [0.00612885 0.00304288 0.99082827]]
pi = [0.64958221 0.13751819 0.2128996 ]
Iter 12: LL=-1289644.15 | Rates: N=0.88494, AF=0.09606, OLD=0.06316, YOUNG=0.02875
A =
[[0.99528164 0.00302187 0.00169649]
 [0.00810976 0.98900381 0.00288643]
 [0.00618221 0.00306478 0.99075301]]
pi = [0.64959164 0.12669024 0.22371812]
Iter 13: LL=-1289633.79 | Rates: N=0.88493, AF=0.09605, OLD=0.06407, YOUNG=0.02902
A =
[[0.9952821  0.00294639 0.00177151]
 [0.00812726 0.9887473  0.00312545]
 [0.00623111 0.00308631 0.99068258]]
pi = [0.64960026 0.11674642 0.23365332]
Iter 14: LL=-1289623.31 | Rates: N=0.88493, AF=0.09604, OLD=0.06501, YOUNG=0.02929
A =
[[0.99528255 0.00287024 0.00184722]
 [0.00814678 0.98847452 0.0033787 ]
 [0.00627574 0.00310684 0.99061742]]
pi = [0.64960801 0.10763491 0.24275708]
Iter 15: LL=-1289612.69 | Rates: N=0.88493, AF=0.09604, OLD=0.06599, YOUNG=0.02957
A =
[[0.99528299 0.0027935  0.00192351]
 [0.00816855 0.98818454 0.00364691]
 [0.00631646 0.00312599 0.99055755]]
pi = [0.64961486 0.09927999 0.25110515]
Final Global Rates (lambdas): [0.88493416 0.0960361  0.06599179 0.02957366]
Final transition matrix A:
[[0.99528299 0.0027935  0.00192351]
 [0.00816855 0.98818454 0.00364691]
 [0.00631646 0.00312599 0.99055755]]
Final initial distribution pi:
[0.64961486 0.09927999 0.25110515]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7568,0.5052,0.6060,143758989.0,46188011.0,140780396.0
Archaic_young,0.3307,0.6092,0.4287,69364594.0,140388406.0,44498793.0
Modern,0.0000,0.0000,0.0000,0.0,600300000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         595431         1599           1576
Archaic_old      3793       144196         138385
Archaic_young    1076        44152          69792

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7043  0.9857  0.8215
Archaic_young     0.0000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         621273         3246              0
Archaic_old      5081       262756              0
Archaic_young    1605       106039              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 10
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1577027.61 | Rates: N=0.90116, AF=0.09778, OLD=0.05683, YOUNG=0.04726
A =
[[0.99515    0.00375977 0.00109023]
 [0.00840784 0.99022232 0.00136983]
 [0.00829288 0.00466333 0.98704379]]
pi = [0.79697926 0.15361487 0.04940587]
Iter 2: LL=-1306078.10 | Rates: N=0.90144, AF=0.09764, OLD=0.05781, YOUNG=0.04289
A =
[[0.99518263 0.00371428 0.00110309]
 [0.00845843 0.99012072 0.00142084]
 [0.00783682 0.00444176 0.98772142]]
pi = [0.80119584 0.14368267 0.05512149]
Iter 3: LL=-1306025.62 | Rates: N=0.90144, AF=0.09763, OLD=0.05986, YOUNG=0.03871
A =
[[0.99518518 0.00367685 0.00113797]
 [0.00865898 0.98983779 0.00150323]
 [0.00732855 0.00412434 0.9885471 ]]
pi = [0.80124312 0.13268727 0.06606961]
Iter 4: LL=-1305953.74 | Rates: N=0.90144, AF=0.09760, OLD=0.06231, YOUNG=0.03548
A =
[[0.99518574 0.00361971 0.00119455]
 [0.00892693 0.98944808 0.00162499]
 [0.00684515 0.00379068 0.98936416]]
pi = [0.80115185 0.11689153 0.08195662]
Iter 5: LL=-1305889.61 | Rates: N=0.90144, AF=0.09757, OLD=0.06467, YOUNG=0.03362
A =
[[0.99518541 0.00354886 0.00126573]
 [0.00918511 0.9890375  0.00177739]
 [0.00653416 0.00355773 0.98990811]]
pi = [0.80102445 0.09812364 0.10085191]
Iter 6: LL=-1305849.03 | Rates: N=0.90144, AF=0.09754, OLD=0.06666, YOUNG=0.03281
A =
[[0.9951846  0.00346976 0.00134564]
 [0.00939092 0.98865278 0.0019563 ]
 [0.00638782 0.00343868 0.9901735 ]]
pi = [0.80091118 0.07960805 0.11948078]
Iter 7: LL=-1305824.20 | Rates: N=0.90144, AF=0.09751, OLD=0.06832, YOUNG=0.03261
A =
[[0.99518387 0.00338461 0.00143152]
 [0.00954963 0.98828961 0.00216076]
 [0.00634157 0.00339381 0.99026462]]
pi = [0.80084035 0.06339014 0.13576951]
Iter 8: LL=-1305805.35 | Rates: N=0.90144, AF=0.09749, OLD=0.06980, YOUNG=0.03272
A =
[[0.99518339 0.00329491 0.0015217 ]
 [0.00967957 0.98793086 0.00238957]
 [0.00634665 0.00338791 0.99026544]]
pi = [0.80080471 0.04989326 0.14930203]
Iter 9: LL=-1305788.09 | Rates: N=0.90144, AF=0.09747, OLD=0.07121, YOUNG=0.03297
A =
[[0.99518313 0.00320189 0.00161498]
 [0.00979486 0.98756348 0.00264166]
 [0.00637653 0.00340054 0.99022293]]
pi = [0.80078862 0.03883145 0.16037992]
Iter 10: LL=-1305771.06 | Rates: N=0.90144, AF=0.09746, OLD=0.07261, YOUNG=0.03329
A =
[[0.995183   0.0031065  0.00171049]
 [0.00990375 0.98717966 0.00291659]
 [0.00641813 0.00342134 0.99016052]]
pi = [0.80078192 0.02981159 0.16940649]
Iter 11: LL=-1305753.89 | Rates: N=0.90144, AF=0.09744, OLD=0.07405, YOUNG=0.03363
A =
[[0.99518297 0.00300943 0.0018076 ]
 [0.01001073 0.98677474 0.00321454]
 [0.00646512 0.00344528 0.9900896 ]]
pi = [0.80077968 0.02250445 0.17671587]
Iter 12: LL=-1305736.50 | Rates: N=0.90144, AF=0.09743, OLD=0.07555, YOUNG=0.03399
A =
[[0.99518299 0.00291121 0.0019058 ]
 [0.01011823 0.98634568 0.00353609]
 [0.00651435 0.00346987 0.99001579]]
pi = [0.80077977 0.0166525  0.18256772]
Iter 13: LL=-1305718.89 | Rates: N=0.90144, AF=0.09741, OLD=0.07713, YOUNG=0.03435
A =
[[0.99518305 0.00281228 0.00200467]
 [0.01022768 0.98589023 0.00388209]
 [0.00656417 0.00349382 0.98994202]]
pi = [0.80078134 0.01204469 0.18717397]
Iter 14: LL=-1305701.07 | Rates: N=0.90144, AF=0.09740, OLD=0.07879, YOUNG=0.03470
A =
[[0.99518315 0.00271303 0.00210383]
 [0.01033993 0.98540654 0.00425353]
 [0.0066137  0.00351638 0.98986991]]
pi = [0.80078412 0.0084948  0.19072107]
Iter 15: LL=-1305683.07 | Rates: N=0.90144, AF=0.09739, OLD=0.08054, YOUNG=0.03505
A =
[[0.99518327 0.00261383 0.0022029 ]
 [0.01045555 0.98489302 0.00465142]
 [0.00666246 0.00353708 0.98980046]]
pi = [0.80078811 0.00582973 0.19338216]
Final Global Rates (lambdas): [0.90143659 0.09738542 0.08054266 0.0350542 ]
Final transition matrix A:
[[0.99518327 0.00261383 0.0022029 ]
 [0.01045555 0.98489302 0.00465142]
 [0.00666246 0.00353708 0.98980046]]
Final initial distribution pi:
[0.80078811 0.00582973 0.19338216]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1          TP           FP           FN
Archaic_old       0.7534  0.3724  0.4984  98979239.0   32405761.0  166843194.0
Archaic_young     0.3112  0.7048  0.4318  74996383.0  165963617.0   31416992.0
Modern            0.0000  0.0000  0.0000         0.0  627655000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         621273         1399           1847
Archaic_old      4873        99344         163620
Archaic_young    1509        30642          75493

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6973  0.9851  0.8166
Archaic_young     0.0000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         639840         3386              0
Archaic_old      5002       247289              0
Archaic_young    1693       102790              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1582090.53 | Rates: N=0.90123, AF=0.09677, OLD=0.06123, YOUNG=0.05205
A =
[[0.99517986 0.00371294 0.0011072 ]
 [0.00908671 0.98936633 0.00154696]
 [0.00891725 0.00510128 0.98598147]]
pi = [0.56877016 0.33703496 0.09419488]
Iter 2: LL=-1311143.14 | Rates: N=0.90152, AF=0.09669, OLD=0.06195, YOUNG=0.04774
A =
[[0.99523986 0.00365047 0.00110968]
 [0.00907153 0.98933523 0.00159324]
 [0.00845554 0.00490899 0.98663547]]
pi = [0.56356857 0.34865545 0.08777598]
Iter 3: LL=-1311101.22 | Rates: N=0.90152, AF=0.09669, OLD=0.06388, YOUNG=0.04343
A =
[[0.99524396 0.00362068 0.00113536]
 [0.00923925 0.98909807 0.00166267]
 [0.00800645 0.00463397 0.98735957]]
pi = [0.56331937 0.36088544 0.07579519]
Iter 4: LL=-1311039.17 | Rates: N=0.90152, AF=0.09666, OLD=0.06631, YOUNG=0.03961
A =
[[0.99524472 0.00357484 0.00118044]
 [0.00947883 0.98875255 0.00176863]
 [0.00753273 0.00430975 0.98815752]]
pi = [0.56317889 0.3763824  0.06043871]
Iter 5: LL=-1310974.21 | Rates: N=0.90152, AF=0.09663, OLD=0.06880, YOUNG=0.03698
A =
[[0.99524479 0.00351554 0.00123967]
 [0.00972247 0.9883734  0.00190413]
 [0.00718746 0.00405534 0.9887572 ]]
pi = [0.56287207 0.39249704 0.04463089]
Iter 6: LL=-1310928.22 | Rates: N=0.90152, AF=0.09659, OLD=0.07094, YOUNG=0.03551
A =
[[0.99524446 0.00344933 0.00130621]
 [0.00991316 0.98802446 0.00206238]
 [0.00701061 0.00392152 0.98906787]]
pi = [0.56244536 0.40617835 0.03137629]
Iter 7: LL=-1310901.88 | Rates: N=0.90152, AF=0.09656, OLD=0.07263, YOUNG=0.03484
A =
[[0.99524414 0.00337955 0.00137631]
 [0.01004437 0.98771465 0.00224099]
 [0.00695209 0.00388302 0.9891649 ]]
pi = [0.56203821 0.41625979 0.021702  ]
Iter 8: LL=-1310885.74 | Rates: N=0.90151, AF=0.09654, OLD=0.07400, YOUNG=0.03463
A =
[[0.99524404 0.00330783 0.00144813]
 [0.01013493 0.98742699 0.00243808]
 [0.00695666 0.0038999  0.98914344]]
pi = [0.56172629 0.42317009 0.01510362]
Iter 9: LL=-1310873.42 | Rates: N=0.90151, AF=0.09652, OLD=0.07517, YOUNG=0.03468
A =
[[0.99524415 0.00323522 0.00152063]
 [0.01020334 0.98714505 0.00265161]
 [0.00698998 0.00394394 0.98906609]]
pi = [0.56150659 0.42779368 0.01069973]
Iter 10: LL=-1310862.37 | Rates: N=0.90151, AF=0.09651, OLD=0.07625, YOUNG=0.03486
A =
[[0.99524438 0.00316238 0.00159324]
 [0.01026127 0.98685877 0.00287996]
 [0.00703452 0.00399927 0.98896621]]
pi = [0.56135044 0.43089423 0.00775533]
Iter 11: LL=-1310851.81 | Rates: N=0.90151, AF=0.09650, OLD=0.07729, YOUNG=0.03510
A =
[[0.99524466 0.0030897  0.00166564]
 [0.010315   0.98656286 0.00312214]
 [0.0070822  0.00405778 0.98886002]]
pi = [0.56123253 0.43300455 0.00576292]
Iter 12: LL=-1310841.48 | Rates: N=0.90151, AF=0.09649, OLD=0.07832, YOUNG=0.03538
A =
[[0.99524498 0.00301738 0.00173765]
 [0.01036769 0.98625471 0.0033776 ]
 [0.00712954 0.00411553 0.98875493]]
pi = [0.56113643 0.43447024 0.00439333]
Iter 13: LL=-1310831.32 | Rates: N=0.90151, AF=0.09648, OLD=0.07936, YOUNG=0.03568
A =
[[0.99524529 0.00294551 0.0018092 ]
 [0.01042085 0.98593297 0.00364618]
 [0.0071752  0.00417066 0.98865414]]
pi = [0.56105256 0.43551099 0.00343645]
Iter 14: LL=-1310821.30 | Rates: N=0.90151, AF=0.09647, OLD=0.08041, YOUNG=0.03599
A =
[[0.99524561 0.00287415 0.00188024]
 [0.01047521 0.98559689 0.0039279 ]
 [0.00721877 0.00422234 0.98855889]]
pi = [0.56097557 0.43626666 0.00275777]
Iter 15: LL=-1310811.39 | Rates: N=0.90151, AF=0.09646, OLD=0.08150, YOUNG=0.03629
A =
[[0.99524592 0.00280333 0.00195076]
 [0.01053112 0.98524597 0.00422291]
 [0.00726022 0.00427026 0.98846952]]
pi = [0.56090245 0.43682729 0.00227025]
Final Global Rates (lambdas): [0.90150957 0.09646326 0.0814991  0.03629407]
Final transition matrix A:
[[0.99524592 0.00280333 0.00195076]
 [0.01053112 0.98524597 0.00422291]
 [0.00726022 0.00427026 0.98846952]]
Final initial distribution pi:
[0.56090245 0.43682729 0.00227025]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7270,0.4870,0.5833,121855977.0,45750023.0,128341853.0
Archaic_young,0.3173,0.5718,0.4081,59049349.0,127066651.0,44215624.0
Modern,0.0000,0.0000,0.0000,0.0,646278000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         639825         1821           1580
Archaic_old      4857       122350         125084
Archaic_young    1596        43435          59452

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7412  0.9866  0.8464
Archaic_young     0.0163  0.0002  0.0004

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         630603         2786              0
Archaic_old      3701       270396           1069
Archaic_young     876        90550             19

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1558293.55 | Rates: N=0.90181, AF=0.09644, OLD=0.04490, YOUNG=0.02959
A =
[[9.96046173e-01 3.29745822e-03 6.56368507e-04]
 [7.14854331e-03 9.92077809e-01 7.73647466e-04]
 [6.57345602e-03 3.61233020e-03 9.89814214e-01]]
pi = [0.59912532 0.3339199  0.06695479]
Iter 2: LL=-1287849.09 | Rates: N=0.90206, AF=0.09624, OLD=0.04596, YOUNG=0.02666
A =
[[9.96044410e-01 3.25838758e-03 6.97202166e-04]
 [7.33981212e-03 9.91817832e-01 8.42356148e-04]
 [5.86953174e-03 3.23473762e-03 9.90895731e-01]]
pi = [0.59894672 0.3456116  0.05544168]
Iter 3: LL=-1287807.33 | Rates: N=0.90206, AF=0.09623, OLD=0.04732, YOUNG=0.02496
A =
[[9.96043860e-01 3.21297197e-03 7.43167966e-04]
 [7.54790167e-03 9.91537623e-01 9.14475588e-04]
 [5.40560417e-03 2.96812282e-03 9.91626273e-01]]
pi = [0.59889042 0.35802225 0.04308734]
Iter 4: LL=-1287780.01 | Rates: N=0.90207, AF=0.09621, OLD=0.04846, YOUNG=0.02418
A =
[[9.96043168e-01 3.16395832e-03 7.92873299e-04]
 [7.71552856e-03 9.91295004e-01 9.89467185e-04]
 [5.16033829e-03 2.82386878e-03 9.92015793e-01]]
pi = [0.59879091 0.36891001 0.03229908]
Iter 5: LL=-1287765.76 | Rates: N=0.90207, AF=0.09619, OLD=0.04933, YOUNG=0.02395
A =
[[9.96042509e-01 3.11298298e-03 8.44507960e-04]
 [7.83648606e-03 9.91095750e-01 1.06776440e-03]
 [5.05596509e-03 2.76339870e-03 9.92180636e-01]]
pi = [0.59869    0.37739102 0.02391898]
Iter 6: LL=-1287757.25 | Rates: N=0.90207, AF=0.09618, OLD=0.05002, YOUNG=0.02400
A =
[[9.96042067e-01 3.06028185e-03 8.97650891e-04]
 [7.92589814e-03 9.90923349e-01 1.15075286e-03]
 [5.02488121e-03 2.74595214e-03 9.92229167e-01]]
pi = [0.59860819 0.38361622 0.01777559]
Iter 7: LL=-1287750.48 | Rates: N=0.90207, AF=0.09618, OLD=0.05061, YOUNG=0.02419
A =
[[9.96041818e-01 3.00609508e-03 9.52086577e-04]
 [7.99793613e-03 9.90762908e-01 1.23915568e-03]
 [5.02963600e-03 2.74739457e-03 9.92222969e-01]]
pi = [0.59854605 0.38809219 0.01336176]
Iter 8: LL=-1287744.15 | Rates: N=0.90207, AF=0.09617, OLD=0.05117, YOUNG=0.02443
A =
[[0.99604169 0.00295067 0.00100764]
 [0.00806117 0.99060551 0.00133332]
 [0.00505206 0.00275581 0.99219213]]
pi = [0.59849817 0.3913066  0.01019522]
Iter 9: LL=-1287737.90 | Rates: N=0.90207, AF=0.09617, OLD=0.05171, YOUNG=0.02470
A =
[[0.99604163 0.00289421 0.00106416]
 [0.00812011 0.99044641 0.00143348]
 [0.00508362 0.00276574 0.99215064]]
pi = [0.59845965 0.39363203 0.00790832]
Iter 10: LL=-1287731.63 | Rates: N=0.90207, AF=0.09616, OLD=0.05227, YOUNG=0.02497
A =
[[0.99604161 0.00283682 0.00112157]
 [0.00817702 0.99028307 0.00153991]
 [0.00512024 0.00277482 0.99210494]]
pi = [0.59842721 0.39533237 0.00624041]
Iter 11: LL=-1287725.32 | Rates: N=0.90207, AF=0.09616, OLD=0.05283, YOUNG=0.02524
A =
[[0.99604161 0.00277861 0.00117978]
 [0.00823303 0.99011406 0.00165291]
 [0.00515987 0.0027821  0.99205804]]
pi = [0.59839885 0.39659021 0.00501093]
Iter 12: LL=-1287718.94 | Rates: N=0.90207, AF=0.09615, OLD=0.05342, YOUNG=0.02552
A =
[[0.99604163 0.00271964 0.00123873]
 [0.00828876 0.98993842 0.00177282]
 [0.0052014  0.00278727 0.99201133]]
pi = [0.59837335 0.39753148 0.00409518]
Iter 13: LL=-1287712.49 | Rates: N=0.90207, AF=0.09615, OLD=0.05403, YOUNG=0.02578
A =
[[0.99604167 0.00265994 0.00129839]
 [0.00834456 0.98975541 0.00190004]
 [0.00524419 0.00279029 0.99196552]]
pi = [0.59834995 0.39824342 0.00340663]
Iter 14: LL=-1287705.95 | Rates: N=0.90207, AF=0.09614, OLD=0.05466, YOUNG=0.02605
A =
[[0.99604171 0.00259958 0.00135871]
 [0.00840066 0.98956435 0.00203498]
 [0.00528778 0.00279124 0.99192098]]
pi = [0.59832818 0.398787   0.00288483]
Iter 15: LL=-1287699.32 | Rates: N=0.90207, AF=0.09614, OLD=0.05533, YOUNG=0.02630
A =
[[0.99604177 0.00253859 0.00141965]
 [0.00845727 0.98936459 0.00217814]
 [0.00533185 0.00279026 0.99187789]]
pi = [0.59830771 0.39920514 0.00248715]
Final Global Rates (lambdas): [0.90206817 0.0961386  0.05532563 0.02630408]
Final transition matrix A:
[[0.99604177 0.00253859 0.00141965]
 [0.00845727 0.98936459 0.00217814]
 [0.00533185 0.00279026 0.99187789]]
Final initial distribution pi:
[0.59830771 0.39920514 0.00248715]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7729,0.5738,0.6586,156789542.0,46074458.0,116461581.0
Archaic_young,0.2891,0.5173,0.3709,46908678.0,115353322.0,43773965.0
Modern,0.0000,0.0000,0.0000,0.0,634874000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         630577         1945            867
Archaic_old      3483       157402         114281
Archaic_young     814        43517          47114

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7059  0.9884  0.8236
Archaic_young     0.5083  0.0050  0.0100

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         601384         3072              1
Archaic_old      3823       277856            540
Archaic_young    1091       111663            570

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1552282.86 | Rates: N=0.89116, AF=0.09693, OLD=0.05008, YOUNG=0.03407
A =
[[9.95413720e-01 3.77005484e-03 8.16224668e-04]
 [7.32024342e-03 9.91735190e-01 9.44566177e-04]
 [6.77039727e-03 4.02911221e-03 9.89200491e-01]]
pi = [0.74373611 0.19676649 0.0594974 ]
Iter 2: LL=-1290969.26 | Rates: N=0.89142, AF=0.09679, OLD=0.05136, YOUNG=0.03030
A =
[[9.95428450e-01 3.70881084e-03 8.62739525e-04]
 [7.48866575e-03 9.91481295e-01 1.03003885e-03]
 [6.08775227e-03 3.58758993e-03 9.90324658e-01]]
pi = [0.7490351  0.17932854 0.07163636]
Iter 3: LL=-1290907.36 | Rates: N=0.89142, AF=0.09677, OLD=0.05316, YOUNG=0.02797
A =
[[9.95429213e-01 3.65022746e-03 9.20559112e-04]
 [7.70241198e-03 9.91172482e-01 1.12510623e-03]
 [5.64573658e-03 3.24867187e-03 9.91105592e-01]]
pi = [0.74924586 0.16278906 0.08796508]
Iter 4: LL=-1290863.38 | Rates: N=0.89142, AF=0.09674, OLD=0.05472, YOUNG=0.02682
A =
[[9.95428923e-01 3.58558526e-03 9.85491417e-04]
 [7.87109642e-03 9.90900347e-01 1.22855684e-03]
 [5.43257526e-03 3.05277447e-03 9.91514650e-01]]
pi = [0.74932919 0.14563385 0.10503696]
Iter 5: LL=-1290839.89 | Rates: N=0.89142, AF=0.09671, OLD=0.05592, YOUNG=0.02639
A =
[[0.9954285  0.00351757 0.00105392]
 [0.00798137 0.99067939 0.00133924]
 [0.00537231 0.00296513 0.99166257]]
pi = [0.74942599 0.12981798 0.12075603]
Iter 6: LL=-1290826.25 | Rates: N=0.89142, AF=0.09670, OLD=0.05687, YOUNG=0.02634
A =
[[0.99542827 0.00344735 0.00112437]
 [0.00805105 0.9904913  0.00145765]
 [0.00538872 0.0029367  0.99167458]]
pi = [0.74951707 0.1159865  0.13449643]
Iter 7: LL=-1290815.86 | Rates: N=0.89142, AF=0.09668, OLD=0.05768, YOUNG=0.02647
A =
[[0.99542824 0.00337585 0.00119591]
 [0.00809786 0.99031843 0.00158372]
 [0.00543865 0.00293703 0.99162432]]
pi = [0.74959067 0.10402018 0.14638915]
Iter 8: LL=-1290806.48 | Rates: N=0.89142, AF=0.09667, OLD=0.05843, YOUNG=0.02667
A =
[[0.99542834 0.0033038  0.00126786]
 [0.00813255 0.99015024 0.00171721]
 [0.00550147 0.00295079 0.99154773]]
pi = [0.74964573 0.09359422 0.15676005]
Iter 9: LL=-1290797.53 | Rates: N=0.89142, AF=0.09667, OLD=0.05915, YOUNG=0.02691
A =
[[0.9954285  0.00323172 0.00133978]
 [0.00816077 0.98998124 0.00185799]
 [0.00556788 0.00297078 0.99146134]]
pi = [0.74968523 0.08439527 0.1659195 ]
Iter 10: LL=-1290788.84 | Rates: N=0.89142, AF=0.09666, OLD=0.05986, YOUNG=0.02716
A =
[[0.9954287  0.00315994 0.00141136]
 [0.00818536 0.98980857 0.00200607]
 [0.00563379 0.00299364 0.99137257]]
pi = [0.74971261 0.07617233 0.17411506]
Iter 11: LL=-1290780.37 | Rates: N=0.89142, AF=0.09665, OLD=0.06057, YOUNG=0.02742
A =
[[0.99542891 0.0030887  0.00148239]
 [0.00820777 0.98963068 0.00216155]
 [0.00569747 0.00301779 0.99128474]]
pi = [0.74973067 0.06873568 0.18153365]
Iter 12: LL=-1290772.10 | Rates: N=0.89142, AF=0.09665, OLD=0.06129, YOUNG=0.02767
A =
[[0.99542914 0.00301815 0.0015527 ]
 [0.00822876 0.98944662 0.00232461]
 [0.00575822 0.00304247 0.9911993 ]]
pi = [0.7497415  0.06194485 0.18831365]
Iter 13: LL=-1290764.01 | Rates: N=0.89142, AF=0.09664, OLD=0.06202, YOUNG=0.02792
A =
[[0.99542938 0.00294842 0.0016222 ]
 [0.0082488  0.98925573 0.00249547]
 [0.00581584 0.00306729 0.99111687]]
pi = [0.74974663 0.05569701 0.19455635]
Iter 14: LL=-1290756.11 | Rates: N=0.89142, AF=0.09663, OLD=0.06276, YOUNG=0.02816
A =
[[0.99542962 0.00287957 0.0016908 ]
 [0.00826817 0.98905747 0.00267436]
 [0.00587031 0.00309202 0.99103767]]
pi = [0.74974717 0.04991789 0.20033493]
Iter 15: LL=-1290748.36 | Rates: N=0.89142, AF=0.09663, OLD=0.06352, YOUNG=0.02840
A =
[[0.99542987 0.00281169 0.00175845]
 [0.00828708 0.98885137 0.00286155]
 [0.00592173 0.00311651 0.99096175]]
pi = [0.74974394 0.04455486 0.2057012 ]
Final Global Rates (lambdas): [0.89142167 0.09662889 0.06351605 0.02840353]
Final transition matrix A:
[[0.99542987 0.00281169 0.00175845]
 [0.00828708 0.98885137 0.00286155]
 [0.00592173 0.00311651 0.99096175]]
Final initial distribution pi:
[0.74974394 0.04455486 0.2057012 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7308,0.5547,0.6307,155529488.0,57287512.0,124841950.0
Archaic_young,0.3146,0.5073,0.3883,56953417.0,124097583.0,55307877.0
Modern,0.0000,0.0000,0.0000,0.0,606132000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         601374         1804           1279
Archaic_old      3679       156058         122482
Archaic_young    1079        54955          57290

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6869  0.9874  0.8102
Archaic_young     0.0000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         617832         3285              0
Archaic_old      4448       259415              0
Archaic_young    1224       113796              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1568638.97 | Rates: N=0.90068, AF=0.09617, OLD=0.05492, YOUNG=0.03861
A =
[[9.95298283e-01 3.81631773e-03 8.85399437e-04]
 [8.11011490e-03 9.90775284e-01 1.11460115e-03]
 [7.45129523e-03 4.47520085e-03 9.88073504e-01]]
pi = [0.69599425 0.2425286  0.06147716]
Iter 2: LL=-1299098.11 | Rates: N=0.90096, AF=0.09604, OLD=0.05629, YOUNG=0.03421
A =
[[9.95333445e-01 3.73802520e-03 9.28529658e-04]
 [8.27061974e-03 9.90529170e-01 1.20021010e-03]
 [6.68754850e-03 4.04676117e-03 9.89265690e-01]]
pi = [0.70004452 0.23959298 0.0603625 ]
Iter 3: LL=-1299029.16 | Rates: N=0.90096, AF=0.09603, OLD=0.05833, YOUNG=0.03133
A =
[[9.95335412e-01 3.67573962e-03 9.88848532e-04]
 [8.51496230e-03 9.90193173e-01 1.29186450e-03]
 [6.18716785e-03 3.72550699e-03 9.90087325e-01]]
pi = [0.70017183 0.23902037 0.0608078 ]
Iter 4: LL=-1298978.05 | Rates: N=0.90096, AF=0.09600, OLD=0.06011, YOUNG=0.02977
A =
[[0.9953353  0.00360537 0.00105933]
 [0.0087156  0.9898926  0.0013918 ]
 [0.00592186 0.00356459 0.99051355]]
pi = [0.70012564 0.23735973 0.06251464]
Iter 5: LL=-1298950.59 | Rates: N=0.90096, AF=0.09598, OLD=0.06149, YOUNG=0.02908
A =
[[0.99533498 0.00353029 0.00113473]
 [0.00885466 0.9896446  0.00150074]
 [0.00581795 0.00353105 0.99065101]]
pi = [0.70007691 0.23500381 0.06491928]
Iter 6: LL=-1298935.26 | Rates: N=0.90096, AF=0.09596, OLD=0.06257, YOUNG=0.02888
A =
[[0.99533484 0.00345247 0.00121269]
 [0.00895241 0.98942717 0.00162042]
 [0.00579495 0.00356766 0.99063739]]
pi = [0.70004243 0.23241354 0.06754403]
Iter 7: LL=-1298923.94 | Rates: N=0.90096, AF=0.09595, OLD=0.06348, YOUNG=0.02892
A =
[[0.9953349  0.00337319 0.0012919 ]
 [0.00902957 0.98921915 0.00175128]
 [0.00580669 0.00363638 0.99055693]]
pi = [0.70001918 0.22984305 0.07013778]
Iter 8: LL=-1298913.72 | Rates: N=0.90096, AF=0.09594, OLD=0.06431, YOUNG=0.02909
A =
[[0.99533508 0.0032933  0.00137162]
 [0.00909845 0.98900823 0.00189331]
 [0.00583175 0.0037173  0.99045094]]
pi = [0.7000018 0.2273905 0.0726077]
Iter 9: LL=-1298903.80 | Rates: N=0.90096, AF=0.09594, OLD=0.06512, YOUNG=0.02931
A =
[[0.99533531 0.00321332 0.00145137]
 [0.0091651  0.98878832 0.00204658]
 [0.00586119 0.0038009  0.9903379 ]]
pi = [0.69998704 0.22507362 0.07493934]
Iter 10: LL=-1298893.97 | Rates: N=0.90096, AF=0.09593, OLD=0.06593, YOUNG=0.02956
A =
[[0.99533556 0.00313359 0.00153086]
 [0.00923219 0.98855651 0.0022113 ]
 [0.00589164 0.00388281 0.99022555]]
pi = [0.69997344 0.2228765  0.07715006]
Iter 11: LL=-1298884.18 | Rates: N=0.90096, AF=0.09592, OLD=0.06676, YOUNG=0.02983
A =
[[0.99533581 0.00305431 0.00160988]
 [0.00930075 0.98831141 0.00238783]
 [0.00592202 0.00396112 0.99011686]]
pi = [0.69996049 0.22077239 0.07926712]
Iter 12: LL=-1298874.42 | Rates: N=0.90096, AF=0.09592, OLD=0.06761, YOUNG=0.03009
A =
[[0.99533606 0.00297565 0.0016883 ]
 [0.00937108 0.98805228 0.00257664]
 [0.00595217 0.00403505 0.99001277]]
pi = [0.69994811 0.21873332 0.08131857]
Iter 13: LL=-1298864.69 | Rates: N=0.90096, AF=0.09591, OLD=0.06848, YOUNG=0.03037
A =
[[0.9953363  0.00289771 0.00176599]
 [0.00944316 0.98777861 0.00277823]
 [0.00598222 0.00410439 0.98991339]]
pi = [0.69993637 0.21673372 0.08332991]
Iter 14: LL=-1298854.99 | Rates: N=0.90096, AF=0.09591, OLD=0.06938, YOUNG=0.03064
A =
[[0.99533654 0.00282059 0.00184287]
 [0.00951684 0.98749001 0.00299315]
 [0.00601235 0.00416915 0.9898185 ]]
pi = [0.69992543 0.21475129 0.08532328]
Iter 15: LL=-1298845.30 | Rates: N=0.90096, AF=0.09590, OLD=0.07031, YOUNG=0.03090
A =
[[0.99533677 0.00274438 0.00191885]
 [0.00959196 0.98718609 0.00322195]
 [0.00604271 0.00422946 0.98972783]]
pi = [0.69991539 0.21276695 0.08731766]
Final Global Rates (lambdas): [0.90095947 0.09589941 0.0703106  0.03090318]
Final transition matrix A:
[[0.99533677 0.00274438 0.00191885]
 [0.00959196 0.98718609 0.00322195]
 [0.00604271 0.00422946 0.98972783]]
Final initial distribution pi:
[0.69991539 0.21276695 0.08731766]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_50000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7645,0.5535,0.6421,144985043.0,44654957.0,116945323.0
Archaic_young,0.3810,0.6257,0.4736,71240275.0,115733725.0,42623112.0
Modern,0.0000,0.0000,0.0000,0.0,623386000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         617822         1917           1378
Archaic_old      4361       145537         113965
Archaic_young    1203        42186          71631

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 55000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7101  0.9835  0.8247
Archaic_young     0.0000  0.0000  0.0000

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         611458         3554              0
Archaic_old      5259       271461            624
Archaic_young    1469       106175              0

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1576647.90 | Rates: N=0.89766, AF=0.09733, OLD=0.06204, YOUNG=0.04485
A =
[[9.94871271e-01 4.14650648e-03 9.82222487e-04]
 [8.60606733e-03 9.90130520e-01 1.26341308e-03]
 [8.10875505e-03 5.01657000e-03 9.86874675e-01]]
pi = [0.79694731 0.16548774 0.03756495]
Iter 2: LL=-1308793.09 | Rates: N=0.89795, AF=0.09723, OLD=0.06355, YOUNG=0.03969
A =
[[0.99492483 0.00405807 0.0010171 ]
 [0.00875096 0.98987481 0.00137422]
 [0.00724936 0.00452361 0.98822703]]
pi = [0.80614441 0.16384796 0.03000763]
Iter 3: LL=-1308709.16 | Rates: N=0.89795, AF=0.09721, OLD=0.06604, YOUNG=0.03615
A =
[[0.99492856 0.0039994  0.00107204]
 [0.00903428 0.98945603 0.00150969]
 [0.00664543 0.00410897 0.9892456 ]]
pi = [0.80651173 0.17083833 0.02264994]
Iter 4: LL=-1308639.80 | Rates: N=0.89795, AF=0.09716, OLD=0.06834, YOUNG=0.03421
A =
[[0.99492857 0.00393501 0.00113642]
 [0.00928385 0.98904603 0.00167011]
 [0.00630974 0.00386862 0.98982165]]
pi = [0.80624975 0.17789485 0.0158554 ]
Iter 5: LL=-1308600.58 | Rates: N=0.89795, AF=0.09712, OLD=0.07016, YOUNG=0.03338
A =
[[0.99492802 0.00386702 0.00120496]
 [0.00945799 0.98868957 0.00185244]
 [0.00618143 0.00378428 0.9900343 ]]
pi = [0.80593498 0.1833833  0.01068173]
Iter 6: LL=-1308578.92 | Rates: N=0.89795, AF=0.09709, OLD=0.07158, YOUNG=0.03315
A =
[[0.99492766 0.00379611 0.00127623]
 [0.0095748  0.98836871 0.00205648]
 [0.00616344 0.00378948 0.99004708]]
pi = [0.80568294 0.18715836 0.0071587 ]
Iter 7: LL=-1308563.23 | Rates: N=0.89795, AF=0.09707, OLD=0.07279, YOUNG=0.03322
A =
[[0.99492761 0.00372291 0.00134947]
 [0.00965994 0.98805874 0.00228132]
 [0.00619538 0.00383736 0.98996726]]
pi = [0.80550599 0.18963172 0.00486228]
Iter 8: LL=-1308549.09 | Rates: N=0.89795, AF=0.09705, OLD=0.07390, YOUNG=0.03343
A =
[[0.99492779 0.00364807 0.00142414]
 [0.00972996 0.98774404 0.002526  ]
 [0.00624774 0.0039034  0.98984886]]
pi = [0.80538387 0.19123962 0.00337651]
Iter 9: LL=-1308535.25 | Rates: N=0.89795, AF=0.09704, OLD=0.07500, YOUNG=0.03370
A =
[[0.99492808 0.00357201 0.00149991]
 [0.00979362 0.9874163  0.00279009]
 [0.00630722 0.00397593 0.98971685]]
pi = [0.80529661 0.1922968  0.00240659]
Iter 10: LL=-1308521.40 | Rates: N=0.89795, AF=0.09702, OLD=0.07610, YOUNG=0.03400
A =
[[0.99492844 0.00349497 0.00157659]
 [0.0098553  0.98707109 0.00307361]
 [0.00636803 0.00404955 0.98958242]]
pi = [0.80523113 0.1930053  0.00176358]
Iter 11: LL=-1308507.47 | Rates: N=0.89794, AF=0.09701, OLD=0.07724, YOUNG=0.03432
A =
[[0.99492883 0.00341709 0.00165409]
 [0.00991722 0.98670585 0.00337693]
 [0.00642769 0.00412175 0.98945056]]
pi = [0.80517985 0.19349024 0.00132992]
Iter 12: LL=-1308493.41 | Rates: N=0.89794, AF=0.09700, OLD=0.07842, YOUNG=0.03464
A =
[[0.99492925 0.00333842 0.00173233]
 [0.00998056 0.98631889 0.00370054]
 [0.00648519 0.00419135 0.98932346]]
pi = [0.80513861 0.19382879 0.0010326 ]
Iter 13: LL=-1308479.23 | Rates: N=0.89794, AF=0.09698, OLD=0.07965, YOUNG=0.03496
A =
[[0.99492968 0.00325903 0.00181129]
 [0.01004602 0.9859089  0.00404508]
 [0.00654016 0.00425774 0.98920211]]
pi = [0.80510518 0.19406894 0.00082588]
Iter 14: LL=-1308464.91 | Rates: N=0.89794, AF=0.09697, OLD=0.08093, YOUNG=0.03528
A =
[[0.99493012 0.00317896 0.00189092]
 [0.01011406 0.98547475 0.00441119]
 [0.00659253 0.00432057 0.9890869 ]]
pi = [8.05078436e-01 1.94240796e-01 6.80768008e-04]
Iter 15: LL=-1308450.46 | Rates: N=0.89794, AF=0.09695, OLD=0.08228, YOUNG=0.03561
A =
[[0.99493056 0.00309827 0.00197117]
 [0.01018501 0.98501543 0.00479956]
 [0.00664235 0.00437963 0.98897802]]
pi = [8.05057873e-01 1.94363499e-01 5.78628426e-04]
Final Global Rates (lambdas): [0.89794116 0.09695161 0.08227942 0.03560953]
Final transition matrix A:
[[0.99493056 0.00309827 0.00197117]
 [0.01018501 0.98501543 0.00479956]
 [0.00664235 0.00437963 0.98897802]]
Final initial distribution pi:
[8.05057873e-01 1.94363499e-01 5.78628426e-04]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_55000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7657,0.5006,0.6054,137765933.0,42163067.0,137456517.0
Archaic_young,0.3274,0.6214,0.4288,66121306.0,135858694.0,40292069.0
Modern,0.0000,0.0000,0.0000,0.0,618091000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         611492         1983           1537
Archaic_old      5182       138273         133889
Archaic_young    1417        39673          66554

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 50000, 't_old_kya': 60000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7304  0.9848  0.8387
Archaic_young     0.9403  0.0033  0.0066

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         595609         3510              0
Archaic_old      5911       290467             20
Archaic_young    1664       102478            341

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1575603.53 | Rates: N=0.88875, AF=0.09734, OLD=0.06912, YOUNG=0.05066
A =
[[0.99438937 0.00451277 0.00109786]
 [0.00883863 0.98974987 0.0014115 ]
 [0.00843413 0.00552894 0.98603693]]
pi = [0.60119263 0.30760023 0.09120714]
Iter 2: LL=-1314962.29 | Rates: N=0.88905, AF=0.09725, OLD=0.07114, YOUNG=0.04434
A =
[[0.99448283 0.00438348 0.00113369]
 [0.008948   0.98951566 0.00153634]
 [0.00746485 0.00494005 0.98759509]]
pi = [0.60111337 0.29292803 0.1059586 ]
Iter 3: LL=-1314842.14 | Rates: N=0.88904, AF=0.09723, OLD=0.07433, YOUNG=0.03996
A =
[[0.99448932 0.0043038  0.00120689]
 [0.00926233 0.98904354 0.00169412]
 [0.00681488 0.00442206 0.98876306]]
pi = [0.60110499 0.27253894 0.12635607]
Iter 4: LL=-1314741.98 | Rates: N=0.88904, AF=0.09718, OLD=0.07725, YOUNG=0.03766
A =
[[0.99448924 0.00421447 0.00129629]
 [0.00953039 0.98859232 0.00187729]
 [0.00649354 0.00413585 0.98937061]]
pi = [0.60108786 0.24792207 0.15099008]
Iter 5: LL=-1314687.96 | Rates: N=0.88904, AF=0.09714, OLD=0.07951, YOUNG=0.03675
A =
[[0.99448834 0.00411848 0.00139319]
 [0.00970483 0.98821283 0.00208234]
 [0.00640235 0.00404643 0.98955122]]
pi = [0.6010522  0.22149081 0.17745699]
Iter 6: LL=-1314658.91 | Rates: N=0.88903, AF=0.09711, OLD=0.08127, YOUNG=0.03656
A =
[[0.99448775 0.00401805 0.0014942 ]
 [0.00981632 0.98787348 0.0023102 ]
 [0.00641823 0.00406016 0.98952162]]
pi = [0.60100747 0.1947481  0.20424443]
Iter 7: LL=-1314637.64 | Rates: N=0.88903, AF=0.09708, OLD=0.08278, YOUNG=0.03671
A =
[[0.99448759 0.00391515 0.00159726]
 [0.00989743 0.98754254 0.00256003]
 [0.00647444 0.00411777 0.98940779]]
pi = [0.60096255 0.16854445 0.230493  ]
Iter 8: LL=-1314618.40 | Rates: N=0.88903, AF=0.09707, OLD=0.08419, YOUNG=0.03701
A =
[[0.99448769 0.00381125 0.00170106]
 [0.00996645 0.98720288 0.00283067]
 [0.00654251 0.00419063 0.98926685]]
pi = [0.60092161 0.14342841 0.25564998]
Iter 9: LL=-1314599.76 | Rates: N=0.88903, AF=0.09705, OLD=0.08559, YOUNG=0.03739
A =
[[0.9944879  0.00370727 0.00180484]
 [0.01003177 0.98684672 0.00312151]
 [0.00661159 0.00426604 0.98912238]]
pi = [0.60088603 0.11981956 0.27929441]
Iter 10: LL=-1314581.42 | Rates: N=0.88903, AF=0.09704, OLD=0.08699, YOUNG=0.03780
A =
[[0.99448815 0.00360373 0.00190812]
 [0.0100969  0.98647074 0.00343236]
 [0.00667806 0.00433847 0.98898346]]
pi = [0.60085599 0.09807289 0.30107112]
Iter 11: LL=-1314563.29 | Rates: N=0.88903, AF=0.09703, OLD=0.08844, YOUNG=0.03822
A =
[[0.99448843 0.00350099 0.00201058]
 [0.01016303 0.98607367 0.0037633 ]
 [0.00674115 0.00440562 0.98885323]]
pi = [0.60083127 0.07848888 0.32067985]
Iter 12: LL=-1314545.38 | Rates: N=0.88902, AF=0.09701, OLD=0.08993, YOUNG=0.03864
A =
[[0.99448871 0.00339931 0.00211198]
 [0.01023038 0.98565512 0.0041145 ]
 [0.00680105 0.00446653 0.98873242]]
pi = [0.60081151 0.06129697 0.33789153]
Iter 13: LL=-1314527.71 | Rates: N=0.88902, AF=0.09700, OLD=0.09147, YOUNG=0.03906
A =
[[0.994489   0.0032989  0.0022121 ]
 [0.0102987  0.98521516 0.00448614]
 [0.00685826 0.00452087 0.98862086]]
pi = [0.60079631 0.04662947 0.35257422]
Iter 14: LL=-1314510.29 | Rates: N=0.88902, AF=0.09698, OLD=0.09307, YOUNG=0.03948
A =
[[0.99448928 0.00319993 0.00231078]
 [0.01036759 0.98475404 0.00487837]
 [0.00691329 0.00456861 0.9885181 ]]
pi = [0.60078527 0.03450023 0.3647145 ]
Iter 15: LL=-1314493.15 | Rates: N=0.88902, AF=0.09696, OLD=0.09471, YOUNG=0.03990
A =
[[0.99448958 0.00310258 0.00240785]
 [0.01043656 0.98427212 0.00529132]
 [0.00696656 0.00460983 0.98842361]]
pi = [0.60077799 0.02479863 0.37442338]
Final Global Rates (lambdas): [0.88902018 0.09696409 0.09471379 0.03989661]
Final transition matrix A:
[[0.99448958 0.00310258 0.00240785]
 [0.01043656 0.98427212 0.00529132]
 [0.00696656 0.00460983 0.98842361]]
Final initial distribution pi:
[0.60077799 0.02479863 0.37442338]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_60000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.8071,0.4352,0.5655,127954776.0,30579224.0,166064059.0
Archaic_young,0.3067,0.6905,0.4247,71305166.0,161200834.0,31959807.0
Modern,0.0000,0.0000,0.0000,0.0,608960000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         596897          377           1845
Archaic_old      9560       128003         158835
Archaic_young    2503        30154          71826

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 45000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7465  0.9822  0.8483
Archaic_young     0.5435  0.0275  0.0524

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         627433         3018              8
Archaic_old      3999       272014           2083
Archaic_young     728        88217           2500

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1564257.00 | Rates: N=0.90086, AF=0.09682, OLD=0.05053, YOUNG=0.02865
A =
[[9.95837584e-01 3.59794152e-03 5.64474702e-04]
 [7.47496438e-03 9.91809636e-01 7.15399188e-04]
 [6.49626523e-03 3.85899384e-03 9.89644741e-01]]
pi = [0.65278272 0.28464001 0.06257727]
Iter 2: LL=-1294195.87 | Rates: N=0.90110, AF=0.09666, OLD=0.05193, YOUNG=0.02590
A =
[[9.95860749e-01 3.52540919e-03 6.13841624e-04]
 [7.66447979e-03 9.91504424e-01 8.31096087e-04]
 [5.63523980e-03 3.28234359e-03 9.91082417e-01]]
pi = [0.65270207 0.27856953 0.06872841]
Iter 3: LL=-1294146.83 | Rates: N=0.90111, AF=0.09664, OLD=0.05344, YOUNG=0.02478
A =
[[9.95861382e-01 3.47391476e-03 6.64702906e-04]
 [7.85206746e-03 9.91197215e-01 9.50718025e-04]
 [5.29387495e-03 2.98651529e-03 9.91719610e-01]]
pi = [0.65264382 0.27175848 0.0755977 ]
Iter 4: LL=-1294121.82 | Rates: N=0.90111, AF=0.09661, OLD=0.05460, YOUNG=0.02451
A =
[[9.95860817e-01 3.42242127e-03 7.16761650e-04]
 [7.97314370e-03 9.90949115e-01 1.07774089e-03]
 [5.20421544e-03 2.85670953e-03 9.91939075e-01]]
pi = [0.65259199 0.26355504 0.08385298]
Iter 5: LL=-1294107.55 | Rates: N=0.90111, AF=0.09660, OLD=0.05550, YOUNG=0.02463
A =
[[9.95860419e-01 3.36924337e-03 7.70338113e-04]
 [8.05035416e-03 9.90736888e-01 1.21275822e-03]
 [5.22235112e-03 2.80744978e-03 9.91970199e-01]]
pi = [0.65253428 0.25383031 0.09363541]
Iter 6: LL=-1294096.28 | Rates: N=0.90111, AF=0.09659, OLD=0.05629, YOUNG=0.02491
A =
[[9.95860239e-01 3.31418921e-03 8.25572186e-04]
 [8.10638849e-03 9.90537762e-01 1.35584924e-03]
 [5.27957338e-03 2.79444124e-03 9.91925985e-01]]
pi = [0.65246793 0.2427036  0.10482847]
Iter 7: LL=-1294085.78 | Rates: N=0.90111, AF=0.09658, OLD=0.05703, YOUNG=0.02525
A =
[[9.95860185e-01 3.25744926e-03 8.82366159e-04]
 [8.15373039e-03 9.90339504e-01 1.50676559e-03]
 [5.34754281e-03 2.79829281e-03 9.91854164e-01]]
pi = [0.6523933  0.23044375 0.11716295]
Iter 8: LL=-1294075.57 | Rates: N=0.90111, AF=0.09657, OLD=0.05777, YOUNG=0.02561
A =
[[9.95860191e-01 3.19923958e-03 9.40569258e-04]
 [8.19828942e-03 9.90136466e-01 1.66524410e-03]
 [5.41531249e-03 2.81071741e-03 9.91773970e-01]]
pi = [0.65231292 0.21739518 0.1302919 ]
Iter 9: LL=-1294065.53 | Rates: N=0.90111, AF=0.09657, OLD=0.05851, YOUNG=0.02597
A =
[[0.99586023 0.00313974 0.00100003]
 [0.00824273 0.98992619 0.00183107]
 [0.00547901 0.00282803 0.99169296]]
pi = [0.65223048 0.20392822 0.1438413 ]
Iter 10: LL=-1294055.65 | Rates: N=0.90111, AF=0.09656, OLD=0.05927, YOUNG=0.02632
A =
[[0.99586027 0.00307912 0.0010606 ]
 [0.00828822 0.98970769 0.00200409]
 [0.00553762 0.00284843 0.99161395]]
pi = [0.65214975 0.19039477 0.15745548]
Iter 11: LL=-1294045.93 | Rates: N=0.90111, AF=0.09655, OLD=0.06005, YOUNG=0.02667
A =
[[0.99586033 0.00301754 0.00112213]
 [0.00833521 0.98948063 0.00218416]
 [0.00559122 0.00287092 0.99153786]]
pi = [0.65207397 0.17709159 0.17083445]
Iter 12: LL=-1294036.37 | Rates: N=0.90111, AF=0.09655, OLD=0.06085, YOUNG=0.02701
A =
[[0.99586039 0.00295515 0.00118446]
 [0.00838381 0.98924501 0.00237118]
 [0.0056403  0.00289487 0.99146483]]
pi = [0.65200542 0.16423833 0.18375625]
Iter 13: LL=-1294026.98 | Rates: N=0.90111, AF=0.09654, OLD=0.06166, YOUNG=0.02733
A =
[[0.99586046 0.00289213 0.00124741]
 [0.00843396 0.98900095 0.00256508]
 [0.00568548 0.00291979 0.99139473]]
pi = [0.65194541 0.15197282 0.19608178]
Iter 14: LL=-1294017.77 | Rates: N=0.90111, AF=0.09654, OLD=0.06250, YOUNG=0.02765
A =
[[0.99586054 0.00282864 0.00131082]
 [0.00848554 0.98874864 0.00276583]
 [0.00572733 0.0029453  0.99132738]]
pi = [0.65189435 0.14036022 0.20774543]
Iter 15: LL=-1294008.75 | Rates: N=0.90111, AF=0.09653, OLD=0.06336, YOUNG=0.02796
A =
[[0.99586062 0.00276488 0.0013745 ]
 [0.00853836 0.98848824 0.00297341]
 [0.00576637 0.00297107 0.99126256]]
pi = [0.65185205 0.12940995 0.218738  ]
Final Global Rates (lambdas): [0.90110664 0.09653006 0.06335547 0.02795571]
Final transition matrix A:
[[0.99586062 0.00276488 0.0013745 ]
 [0.00853836 0.98848824 0.00297341]
 [0.00576637 0.00297107 0.99126256]]
Final initial distribution pi:
[0.65185205 0.12940995 0.218738  ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_45000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7940,0.5817,0.6715,160581498.0,41657502.0,115483768.0
Archaic_young,0.3113,0.5691,0.4024,51604065.0,114186935.0,39078578.0
Modern,0.0000,0.0000,0.0000,0.0,631970000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         627423         2124            912
Archaic_old      3850       161201         113045
Archaic_young     697        38914          51834

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 50000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7021  0.9829  0.8191
Archaic_young     0.7824  0.0356  0.0681

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         613238         3108             24
Archaic_old      4806       264427           1073
Archaic_young    1342       107971           4011

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1561942.96 | Rates: N=0.89338, AF=0.09708, OLD=0.05456, YOUNG=0.03294
A =
[[9.95218293e-01 4.05213716e-03 7.29569457e-04]
 [8.12603563e-03 9.90993397e-01 8.80567197e-04]
 [7.09763268e-03 4.27877263e-03 9.88623595e-01]]
pi = [0.70225898 0.23757297 0.06016805]
Iter 2: LL=-1298415.27 | Rates: N=0.89367, AF=0.09698, OLD=0.05574, YOUNG=0.02971
A =
[[9.95243714e-01 3.96403438e-03 7.92252074e-04]
 [8.30482349e-03 9.90712517e-01 9.82659015e-04]
 [6.32288483e-03 3.75676389e-03 9.89920351e-01]]
pi = [0.70427248 0.22501787 0.07070965]
Iter 3: LL=-1298366.87 | Rates: N=0.89367, AF=0.09697, OLD=0.05728, YOUNG=0.02816
A =
[[9.95244739e-01 3.89698441e-03 8.58276935e-04]
 [8.48950330e-03 9.90431163e-01 1.07933320e-03]
 [5.97267558e-03 3.47183376e-03 9.90555491e-01]]
pi = [0.70434463 0.21225004 0.08340533]
Iter 4: LL=-1298339.97 | Rates: N=0.89367, AF=0.09695, OLD=0.05852, YOUNG=0.02756
A =
[[9.95244492e-01 3.82770268e-03 9.27805541e-04]
 [8.61860933e-03 9.90201735e-01 1.17965536e-03]
 [5.84265368e-03 3.33901505e-03 9.90818331e-01]]
pi = [0.70438202 0.19963211 0.09598587]
Iter 5: LL=-1298324.95 | Rates: N=0.89367, AF=0.09693, OLD=0.05949, YOUNG=0.02746
A =
[[0.99524433 0.00375619 0.00099948]
 [0.00870479 0.99001032 0.00128489]
 [0.0058242  0.00329121 0.99088459]]
pi = [0.70442186 0.18854393 0.10703421]
Iter 6: LL=-1298314.08 | Rates: N=0.89367, AF=0.09692, OLD=0.06031, YOUNG=0.02761
A =
[[0.99524436 0.00368293 0.0010727 ]
 [0.00876752 0.98983672 0.00139575]
 [0.00585353 0.00328397 0.9908625 ]]
pi = [0.70445255 0.17925216 0.11629528]
Iter 7: LL=-1298304.43 | Rates: N=0.89367, AF=0.09691, OLD=0.06105, YOUNG=0.02787
A =
[[0.99524453 0.0036084  0.00114707]
 [0.00881954 0.98966797 0.00151249]
 [0.00590045 0.00329455 0.990805  ]]
pi = [0.7044696  0.17149262 0.12403778]
Iter 8: LL=-1298295.16 | Rates: N=0.89367, AF=0.09690, OLD=0.06177, YOUNG=0.02818
A =
[[0.99524476 0.00353297 0.00122227]
 [0.0088675  0.98949729 0.00163521]
 [0.00595198 0.00331236 0.99073566]]
pi = [0.70447421 0.16489121 0.13063458]
Iter 9: LL=-1298286.07 | Rates: N=0.89366, AF=0.09689, OLD=0.06248, YOUNG=0.02852
A =
[[0.99524502 0.00345692 0.00129806]
 [0.00891461 0.98932135 0.00176404]
 [0.00600296 0.00333258 0.99066446]]
pi = [0.70446944 0.15912315 0.13640741]
Iter 10: LL=-1298277.11 | Rates: N=0.89366, AF=0.09689, OLD=0.06320, YOUNG=0.02886
A =
[[0.99524529 0.00338045 0.00137425]
 [0.00896238 0.98913844 0.00189917]
 [0.00605152 0.00335305 0.99059543]]
pi = [0.70445829 0.1539454  0.14159631]
Iter 11: LL=-1298268.25 | Rates: N=0.89366, AF=0.09688, OLD=0.06394, YOUNG=0.02921
A =
[[0.99524557 0.00330374 0.00145069]
 [0.00901152 0.98894761 0.00204087]
 [0.00609718 0.00337279 0.99053003]]
pi = [0.70444309 0.149187   0.14636991]
Iter 12: LL=-1298259.48 | Rates: N=0.89366, AF=0.09687, OLD=0.06469, YOUNG=0.02955
A =
[[0.99524585 0.00322692 0.00152723]
 [0.00906236 0.98874819 0.00218945]
 [0.00613998 0.00339136 0.99046866]]
pi = [0.70442554 0.14473082 0.15084364]
Iter 13: LL=-1298250.79 | Rates: N=0.89366, AF=0.09687, OLD=0.06547, YOUNG=0.02989
A =
[[0.99524612 0.00315012 0.00160375]
 [0.00911508 0.98853968 0.00234524]
 [0.00618015 0.00340854 0.9904113 ]]
pi = [0.7044068  0.14049742 0.15509578]
Iter 14: LL=-1298242.18 | Rates: N=0.89366, AF=0.09686, OLD=0.06627, YOUNG=0.03022
A =
[[0.9952464  0.00307347 0.00168014]
 [0.00916978 0.98832157 0.00250866]
 [0.006218   0.00342424 0.99035776]]
pi = [0.70438768 0.13643299 0.15917934]
Iter 15: LL=-1298233.64 | Rates: N=0.89366, AF=0.09685, OLD=0.06709, YOUNG=0.03055
A =
[[0.99524667 0.00299705 0.00175628]
 [0.00922651 0.98809338 0.00268011]
 [0.0062538  0.0034384  0.9903078 ]]
pi = [0.70436871 0.13250097 0.16313032]
Final Global Rates (lambdas): [0.89366282 0.0968535  0.06708846 0.0305477 ]
Final transition matrix A:
[[0.99524667 0.00299705 0.00175628]
 [0.00922651 0.98809338 0.00268011]
 [0.0062538  0.0034384  0.9903078 ]]
Final initial distribution pi:
[0.70436871 0.13250097 0.16313032]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_50000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall     F1           TP           FP           FN
Archaic_old       0.7694  0.6108  0.681  163833834.0   49105166.0  104392238.0
Archaic_young     0.3880  0.5801  0.465   65128119.0  102741881.0   47133175.0
Modern            0.0000  0.0000  0.000          0.0  619191000.0          0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         613218         1967           1185
Archaic_old      4659       164420         101227
Archaic_young    1314        46552          65458

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 55000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7033  0.9831  0.8200
Archaic_young     0.8370  0.0312  0.0601

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         603584         3419             14
Archaic_old      5353       271939            671
Archaic_young    1299       110168           3553

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1561693.61 | Rates: N=0.88652, AF=0.09710, OLD=0.06042, YOUNG=0.03770
A =
[[9.94839652e-01 4.32687590e-03 8.33472157e-04]
 [8.47845837e-03 9.90481584e-01 1.03995748e-03]
 [7.33175403e-03 4.76080605e-03 9.87907440e-01]]
pi = [0.79371613 0.16274362 0.04354024]
Iter 2: LL=-1303795.88 | Rates: N=0.88680, AF=0.09703, OLD=0.06205, YOUNG=0.03360
A =
[[9.94898338e-01 4.20582268e-03 8.95839782e-04]
 [8.68148361e-03 9.90155336e-01 1.16317994e-03]
 [6.34555040e-03 4.19553405e-03 9.89458916e-01]]
pi = [0.80078822 0.15075733 0.04845445]
Iter 3: LL=-1303722.62 | Rates: N=0.88680, AF=0.09701, OLD=0.06411, YOUNG=0.03153
A =
[[9.94900653e-01 4.12968813e-03 9.69659215e-04]
 [8.94669684e-03 9.89769515e-01 1.28378852e-03]
 [5.87107002e-03 3.91468876e-03 9.90214241e-01]]
pi = [0.80098904 0.14338795 0.055623  ]
Iter 4: LL=-1303681.66 | Rates: N=0.88680, AF=0.09698, OLD=0.06574, YOUNG=0.03067
A =
[[0.99489924 0.00405238 0.00104838]
 [0.00914156 0.98944706 0.00141138]
 [0.00567191 0.00383537 0.99049273]]
pi = [0.80095935 0.13559587 0.06344478]
Iter 5: LL=-1303660.49 | Rates: N=0.88680, AF=0.09696, OLD=0.06697, YOUNG=0.03046
A =
[[0.99489805 0.00397261 0.00112934]
 [0.00927602 0.98917539 0.00154859]
 [0.00561248 0.00386446 0.99052306]]
pi = [0.8009304  0.12783391 0.07123569]
Iter 6: LL=-1303646.14 | Rates: N=0.88680, AF=0.09694, OLD=0.06798, YOUNG=0.03054
A =
[[0.9948974  0.00389121 0.0012114 ]
 [0.00937698 0.98892646 0.00169656]
 [0.00561471 0.00393964 0.99044565]]
pi = [0.8009106  0.12054604 0.07854336]
Iter 7: LL=-1303633.71 | Rates: N=0.88680, AF=0.09693, OLD=0.06889, YOUNG=0.03077
A =
[[0.9948971  0.00380908 0.00129382]
 [0.00946211 0.9886825  0.00185539]
 [0.00564278 0.00403018 0.99032704]]
pi = [0.80089806 0.11396163 0.0851403 ]
Iter 8: LL=-1303621.91 | Rates: N=0.88680, AF=0.09692, OLD=0.06975, YOUNG=0.03105
A =
[[0.99489698 0.00372689 0.00137614]
 [0.00954038 0.98843456 0.00202506]
 [0.00568143 0.00412253 0.99019604]]
pi = [0.80089052 0.10814047 0.09096901]
Iter 9: LL=-1303610.43 | Rates: N=0.88680, AF=0.09692, OLD=0.07061, YOUNG=0.03136
A =
[[0.99489694 0.00364503 0.00145802]
 [0.009616   0.98817835 0.00220565]
 [0.00572426 0.00421109 0.99006465]]
pi = [0.80088627 0.10304171 0.09607202]
Iter 10: LL=-1303599.19 | Rates: N=0.88680, AF=0.09691, OLD=0.07148, YOUNG=0.03167
A =
[[0.99489694 0.00356377 0.00153928]
 [0.0096909  0.98791175 0.00239735]
 [0.00576859 0.00429377 0.98993764]]
pi = [0.80088414 0.09857749 0.10053836]
Iter 11: LL=-1303588.15 | Rates: N=0.88680, AF=0.09690, OLD=0.07236, YOUNG=0.03199
A =
[[0.99489696 0.00348325 0.00161978]
 [0.00976599 0.98763354 0.00260047]
 [0.00581326 0.00436999 0.98981675]]
pi = [0.80088337 0.09464613 0.1044705 ]
Iter 12: LL=-1303577.29 | Rates: N=0.88680, AF=0.09689, OLD=0.07326, YOUNG=0.03231
A =
[[0.99489699 0.00340358 0.00169944]
 [0.00984173 0.9873429  0.00281537]
 [0.00585774 0.00443981 0.98970245]]
pi = [0.80088347 0.0911496  0.10796694]
Iter 13: LL=-1303566.59 | Rates: N=0.88680, AF=0.09688, OLD=0.07418, YOUNG=0.03263
A =
[[0.99489701 0.00332481 0.00177818]
 [0.00991839 0.98703917 0.00304244]
 [0.00590178 0.00450353 0.98959469]]
pi = [0.80088411 0.08800133 0.11111456]
Iter 14: LL=-1303556.03 | Rates: N=0.88680, AF=0.09688, OLD=0.07513, YOUNG=0.03295
A =
[[0.99489703 0.003247   0.00185597]
 [0.00999617 0.9867217  0.00328213]
 [0.00594522 0.00456155 0.98949323]]
pi = [0.80088512 0.08512842 0.11398647]
Iter 15: LL=-1303545.59 | Rates: N=0.88679, AF=0.09687, OLD=0.07611, YOUNG=0.03326
A =
[[0.99489704 0.00317016 0.0019328 ]
 [0.01007525 0.98638987 0.00353489]
 [0.00598798 0.00461428 0.98939774]]
pi = [0.80088635 0.08247116 0.11664249]
Final Global Rates (lambdas): [0.88679491 0.09686701 0.07611016 0.03325577]
Final transition matrix A:
[[0.99489704 0.00317016 0.0019328 ]
 [0.01007525 0.98638987 0.00353489]
 [0.00598798 0.00461428 0.98939774]]
Final initial distribution pi:
[0.80088635 0.08247116 0.11664249]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_55000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.7943,0.5936,0.6794,163712006.0,42402994.0,112071397.0
Archaic_young,0.4009,0.6470,0.4951,73673727.0,110094273.0,40189660.0
Modern,0.0000,0.0000,0.0000,0.0,610117000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         603572         2162           1283
Archaic_old      5234       164321         108408
Archaic_young    1311        39632          74077

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 45000, 't_old_kya': 60000, 'delta_kya': 15000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7067  0.9820  0.8219
Archaic_young     0.5647  0.0056  0.0111

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         615859         3790              7
Archaic_old      5865       266386            449
Archaic_young    1612       105433            599

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1584559.54 | Rates: N=0.89683, AF=0.09825, OLD=0.06783, YOUNG=0.04329
A =
[[9.94577583e-01 4.51927566e-03 9.03141493e-04]
 [9.38376407e-03 9.89437103e-01 1.17913256e-03]
 [8.41984307e-03 5.32724227e-03 9.86252915e-01]]
pi = [0.7518725  0.21615394 0.03197357]
Iter 2: LL=-1316692.89 | Rates: N=0.89712, AF=0.09822, OLD=0.06986, YOUNG=0.03806
A =
[[9.94654789e-01 4.37483384e-03 9.70377359e-04]
 [9.60655515e-03 9.89051731e-01 1.34171387e-03]
 [7.21843674e-03 4.62705138e-03 9.88154512e-01]]
pi = [0.75846153 0.21989811 0.02164036]
Iter 3: LL=-1316590.86 | Rates: N=0.89712, AF=0.09819, OLD=0.07267, YOUNG=0.03540
A =
[[0.99465879 0.00428438 0.00105683]
 [0.00994761 0.98853447 0.00151791]
 [0.00661915 0.00423926 0.98914159]]
pi = [0.75840796 0.22632176 0.01527028]
Iter 4: LL=-1316527.57 | Rates: N=0.89712, AF=0.09814, OLD=0.07504, YOUNG=0.03434
A =
[[0.99465734 0.00419053 0.00115213]
 [0.01021308 0.98807281 0.00171412]
 [0.0063722  0.00410301 0.98952479]]
pi = [0.75810613 0.23058097 0.0113129 ]
Iter 5: LL=-1316492.26 | Rates: N=0.89712, AF=0.09810, OLD=0.07693, YOUNG=0.03411
A =
[[0.99465593 0.00409157 0.0012525 ]
 [0.01040184 0.98766675 0.00193141]
 [0.00630946 0.00410572 0.98958482]]
pi = [0.75788154 0.23314573 0.00897273]
Iter 6: LL=-1316467.25 | Rates: N=0.89712, AF=0.09807, OLD=0.07853, YOUNG=0.03427
A =
[[0.99465516 0.00398888 0.00135596]
 [0.0105445  0.98728561 0.00216989]
 [0.00632978 0.00416773 0.9895025 ]]
pi = [0.75772911 0.23459037 0.00768052]
Iter 7: LL=-1316445.27 | Rates: N=0.89712, AF=0.09805, OLD=0.08001, YOUNG=0.03460
A =
[[0.99465486 0.00388413 0.00146101]
 [0.01066301 0.98690819 0.0024288 ]
 [0.00638608 0.00424972 0.9893642 ]]
pi = [0.757626 0.235279 0.007095]
Iter 8: LL=-1316424.35 | Rates: N=0.89712, AF=0.09803, OLD=0.08145, YOUNG=0.03500
A =
[[0.99465484 0.00377858 0.00156659]
 [0.01076904 0.98652337 0.00270759]
 [0.00645774 0.00433438 0.98920787]]
pi = [0.75755702 0.23539224 0.00705074]
Iter 9: LL=-1316404.04 | Rates: N=0.89712, AF=0.09802, OLD=0.08288, YOUNG=0.03542
A =
[[0.99465496 0.00367305 0.00167199]
 [0.01086835 0.98612559 0.00300607]
 [0.00653563 0.00441447 0.9890499 ]]
pi = [0.75751398 0.23497976 0.00750626]
Iter 10: LL=-1316384.20 | Rates: N=0.89712, AF=0.09800, OLD=0.08435, YOUNG=0.03586
A =
[[0.99465516 0.00356809 0.00177675]
 [0.01096383 0.98571188 0.00332429]
 [0.00661545 0.00448716 0.98889739]]
pi = [0.75749257 0.2339872  0.00852022]
Iter 11: LL=-1316364.80 | Rates: N=0.89712, AF=0.09799, OLD=0.08585, YOUNG=0.03629
A =
[[0.99465541 0.00346408 0.00188051]
 [0.01105705 0.98528053 0.00366243]
 [0.00669508 0.00455152 0.98875341]]
pi = [0.75749016 0.23225663 0.01025321]
Iter 12: LL=-1316345.81 | Rates: N=0.89711, AF=0.09797, OLD=0.08739, YOUNG=0.03673
A =
[[0.9946557  0.00336127 0.00198303]
 [0.01114897 0.98483035 0.00402068]
 [0.00677334 0.00460744 0.98861922]]
pi = [0.75750445 0.2295088  0.01298675]
Iter 13: LL=-1316327.22 | Rates: N=0.89711, AF=0.09796, OLD=0.08899, YOUNG=0.03716
A =
[[0.994656   0.00325985 0.00208414]
 [0.01124028 0.9843605  0.00439922]
 [0.00684957 0.00465517 0.98849526]]
pi = [0.75753269 0.22532312 0.01714419]
Iter 14: LL=-1316308.99 | Rates: N=0.89711, AF=0.09794, OLD=0.09063, YOUNG=0.03760
A =
[[0.99465633 0.00315996 0.00218371]
 [0.01133154 0.98387026 0.0047982 ]
 [0.00692332 0.00469512 0.98838156]]
pi = [0.75757161 0.21915411 0.02327428]
Iter 15: LL=-1316291.12 | Rates: N=0.89711, AF=0.09792, OLD=0.09234, YOUNG=0.03802
A =
[[0.99465666 0.00306169 0.00228165]
 [0.01142326 0.98335904 0.0052177 ]
 [0.00699434 0.00472773 0.98827793]]
pi = [0.75761896 0.21046142 0.03191963]
Final Global Rates (lambdas): [0.89711087 0.09792258 0.09233652 0.03802236]
Final transition matrix A:
[[0.99465666 0.00306169 0.00228165]
 [0.01142326 0.98335904 0.0052177 ]
 [0.00699434 0.00472773 0.98827793]]
Final initial distribution pi:
[0.75761896 0.21046142 0.03191963]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_60000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.8032,0.4499,0.5767,121592940.0,29798060.0,148693342.0
Archaic_young,0.3437,0.7080,0.4627,75338326.0,143868674.0,31075049.0
Modern,0.0000,0.0000,0.0000,0.0,629402000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         617368          386           1902
Archaic_old      9523       121694         141483
Archaic_young    2511        29311          75822

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 30000, 't_old_kya': 50000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7328  0.9726  0.8359
Archaic_young     0.6400  0.0675  0.1221

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         654539         2849             40
Archaic_old      4691       243051           3385
Archaic_young     799        84507           6139

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1584695.70 | Rates: N=0.91559, AF=0.09638, OLD=0.05431, YOUNG=0.02740
A =
[[9.95935261e-01 3.57991384e-03 4.84825225e-04]
 [8.37104814e-03 9.90931293e-01 6.97658812e-04]
 [6.28169637e-03 3.91518625e-03 9.89803117e-01]]
pi = [0.79990015 0.15002372 0.05007613]
Iter 2: LL=-1301597.85 | Rates: N=0.91585, AF=0.09624, OLD=0.05590, YOUNG=0.02543
A =
[[9.95973123e-01 3.48740538e-03 5.39472037e-04]
 [8.65613957e-03 9.90517120e-01 8.26740400e-04]
 [5.22543117e-03 3.32248169e-03 9.91452087e-01]]
pi = [0.80255624 0.12200075 0.075443  ]
Iter 3: LL=-1301551.49 | Rates: N=0.91586, AF=0.09622, OLD=0.05744, YOUNG=0.02505
A =
[[9.95973367e-01 3.43477729e-03 5.91856072e-04]
 [8.91768599e-03 9.90142178e-01 9.40136050e-04]
 [4.87221118e-03 3.12814701e-03 9.91999642e-01]]
pi = [0.80256173 0.09485031 0.10258796]
Iter 4: LL=-1301530.83 | Rates: N=0.91586, AF=0.09620, OLD=0.05855, YOUNG=0.02524
A =
[[9.95971986e-01 3.38185120e-03 6.46163105e-04]
 [9.09758488e-03 9.89849861e-01 1.05255429e-03]
 [4.76816010e-03 3.08901660e-03 9.92142823e-01]]
pi = [0.8025327  0.07046727 0.12700004]
Iter 5: LL=-1301517.91 | Rates: N=0.91586, AF=0.09619, OLD=0.05944, YOUNG=0.02561
A =
[[9.95971082e-01 3.32610936e-03 7.02808479e-04]
 [9.22907140e-03 9.89604453e-01 1.16647555e-03]
 [4.76535279e-03 3.10853264e-03 9.92126115e-01]]
pi = [0.80249671 0.05046917 0.14703413]
Iter 6: LL=-1301507.15 | Rates: N=0.91586, AF=0.09618, OLD=0.06021, YOUNG=0.02603
A =
[[9.95970571e-01 3.26803174e-03 7.61397115e-04]
 [9.33480696e-03 9.89382800e-01 1.28239353e-03]
 [4.80598719e-03 3.14823684e-03 9.92045776e-01]]
pi = [0.80245216 0.0349462  0.16260164]
Iter 7: LL=-1301497.29 | Rates: N=0.91586, AF=0.09617, OLD=0.06094, YOUNG=0.02644
A =
[[9.95970284e-01 3.20831848e-03 8.21397935e-04]
 [9.42593613e-03 9.89173692e-01 1.40037142e-03]
 [4.86654396e-03 3.19336880e-03 9.91940087e-01]]
pi = [0.80240312 0.02340402 0.17419286]
Iter 8: LL=-1301488.05 | Rates: N=0.91586, AF=0.09617, OLD=0.06165, YOUNG=0.02683
A =
[[9.95970124e-01 3.14753737e-03 8.82338490e-04]
 [9.50777227e-03 9.88971780e-01 1.52044818e-03]
 [4.93664090e-03 3.23820852e-03 9.91825151e-01]]
pi = [0.8023536  0.01516098 0.18248542]
Iter 9: LL=-1301479.32 | Rates: N=0.91586, AF=0.09616, OLD=0.06235, YOUNG=0.02719
A =
[[9.95970045e-01 3.08612842e-03 9.43827061e-04]
 [9.58301623e-03 9.88774281e-01 1.64270236e-03]
 [5.01122524e-03 3.28051150e-03 9.91708263e-01]]
pi = [0.80230631 0.0095042  0.18818948]
Iter 10: LL=-1301471.04 | Rates: N=0.91586, AF=0.09616, OLD=0.06305, YOUNG=0.02754
A =
[[0.99597002 0.00302444 0.00100554]
 [0.00965319 0.98857956 0.00176725]
 [0.00508759 0.00331942 0.99159298]]
pi = [0.80226282 0.00577124 0.19196594]
Iter 11: LL=-1301463.18 | Rates: N=0.91586, AF=0.09615, OLD=0.06376, YOUNG=0.02787
A =
[[0.99597003 0.00296276 0.00106721]
 [0.00971928 0.98838651 0.00189421]
 [0.00516418 0.00335467 0.99148115]]
pi = [0.8022238  0.00339884 0.19437736]
Iter 12: LL=-1301455.69 | Rates: N=0.91586, AF=0.09615, OLD=0.06446, YOUNG=0.02818
A =
[[0.99597007 0.00290131 0.00112862]
 [0.00978193 0.98819432 0.00202374]
 [0.00524004 0.00338624 0.99137372]]
pi = [0.80218938 0.00194394 0.19586668]
Iter 13: LL=-1301448.54 | Rates: N=0.91586, AF=0.09614, OLD=0.06516, YOUNG=0.02849
A =
[[0.99597013 0.00284029 0.00118958]
 [0.00984168 0.98800234 0.00215598]
 [0.00531456 0.00341427 0.99127117]]
pi = [0.80215935 0.00108113 0.19675952]
Iter 14: LL=-1301441.72 | Rates: N=0.91586, AF=0.09614, OLD=0.06587, YOUNG=0.02878
A =
[[0.99597021 0.00277986 0.00124993]
 [0.0098989  0.98781003 0.00229107]
 [0.00538738 0.00343892 0.99117371]]
pi = [8.02133352e-01 5.85333123e-04 1.97281315e-01]
Iter 15: LL=-1301435.20 | Rates: N=0.91586, AF=0.09613, OLD=0.06658, YOUNG=0.02906
A =
[[0.99597029 0.00272016 0.00130955]
 [0.00995392 0.98761692 0.00242915]
 [0.00545823 0.00346041 0.99108136]]
pi = [8.02110969e-01 3.08797915e-04 1.97580233e-01]
Final Global Rates (lambdas): [0.91585705 0.0961334  0.06658015 0.02906241]
Final transition matrix A:
[[0.99597029 0.00272016 0.00130955]
 [0.00995392 0.98761692 0.00242915]
 [0.00545823 0.00346041 0.99108136]]
Final initial distribution pi:
[8.02110969e-01 3.08797915e-04 1.97580233e-01]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_50000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

               Precision  Recall      F1           TP           FP          FN
Archaic_old       0.8102  0.6331  0.7108  157600738.0   36929262.0  91345817.0
Archaic_young     0.3862  0.6202  0.4760   56239276.0   89369724.0  34443367.0
Modern            0.0000  0.0000  0.0000          0.0  659861000.0         0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         654497         2034            897
Archaic_old      4551       158338          88238
Archaic_young     813        34158          56474

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 35000, 't_old_kya': 55000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.6993  0.9756  0.8147
Archaic_young     0.7671  0.0661  0.1216

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         621829         3318             30
Archaic_old      5446       253853           2200
Archaic_young    1291       104596           7437

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1574415.22 | Rates: N=0.90056, AF=0.09660, OLD=0.05985, YOUNG=0.03140
A =
[[9.95155853e-01 4.19006535e-03 6.54081390e-04]
 [8.71136733e-03 9.90437606e-01 8.51026346e-04]
 [6.87517017e-03 4.34692923e-03 9.88777901e-01]]
pi = [0.40634436 0.47570706 0.11794858]
Iter 2: LL=-1304529.24 | Rates: N=0.90086, AF=0.09653, OLD=0.06173, YOUNG=0.02856
A =
[[9.95206585e-01 4.05097147e-03 7.42443826e-04]
 [8.98484680e-03 9.90011631e-01 1.00352219e-03]
 [5.87960701e-03 3.65582510e-03 9.90464568e-01]]
pi = [0.39722918 0.45292962 0.14984119]
Iter 3: LL=-1304462.32 | Rates: N=0.90086, AF=0.09651, OLD=0.06375, YOUNG=0.02783
A =
[[9.95208266e-01 3.96099142e-03 8.30742216e-04]
 [9.24014919e-03 9.89616961e-01 1.14288991e-03]
 [5.58323876e-03 3.38969847e-03 9.91027063e-01]]
pi = [0.39702229 0.42262208 0.18035563]
Iter 4: LL=-1304429.30 | Rates: N=0.90086, AF=0.09648, OLD=0.06532, YOUNG=0.02792
A =
[[9.95207312e-01 3.86989077e-03 9.22797181e-04]
 [9.41547216e-03 9.89295510e-01 1.28901745e-03]
 [5.53232243e-03 3.29827493e-03 9.91169403e-01]]
pi = [0.3971379  0.39456652 0.20829559]
Iter 5: LL=-1304406.90 | Rates: N=0.90086, AF=0.09645, OLD=0.06663, YOUNG=0.02831
A =
[[0.99520669 0.00377492 0.00101839]
 [0.00954463 0.98901024 0.00144512]
 [0.00557564 0.00327773 0.99114662]]
pi = [0.39727385 0.37001459 0.23271157]
Iter 6: LL=-1304387.23 | Rates: N=0.90086, AF=0.09644, OLD=0.06784, YOUNG=0.02881
A =
[[0.99520644 0.00367686 0.0011167 ]
 [0.00965159 0.98873653 0.00161188]
 [0.00565346 0.0032849  0.99106164]]
pi = [0.39739448 0.34874584 0.25385967]
Iter 7: LL=-1304368.49 | Rates: N=0.90086, AF=0.09642, OLD=0.06903, YOUNG=0.02933
A =
[[0.9952064  0.00357669 0.00121691]
 [0.00974826 0.98846223 0.00178951]
 [0.00574241 0.00330265 0.99095494]]
pi = [0.39749119 0.33020093 0.27230788]
Iter 8: LL=-1304350.30 | Rates: N=0.90086, AF=0.09641, OLD=0.07023, YOUNG=0.02985
A =
[[0.99520648 0.00347521 0.00131831]
 [0.00984031 0.9881814  0.00197829]
 [0.00583307 0.00332408 0.99084285]]
pi = [0.39756488 0.31382911 0.28860602]
Iter 9: LL=-1304332.57 | Rates: N=0.90086, AF=0.09640, OLD=0.07145, YOUNG=0.03036
A =
[[0.99520662 0.00337305 0.00142032]
 [0.00993055 0.98789093 0.00217852]
 [0.00592155 0.00334622 0.99073223]]
pi = [0.39761924 0.29918773 0.30319302]
Iter 10: LL=-1304315.24 | Rates: N=0.90086, AF=0.09638, OLD=0.07272, YOUNG=0.03085
A =
[[0.99520681 0.00327072 0.00152247]
 [0.01002047 0.98758897 0.00239056]
 [0.0060063  0.00336773 0.99062598]]
pi = [0.39765807 0.28595262 0.3163893 ]
Iter 11: LL=-1304298.31 | Rates: N=0.90086, AF=0.09637, OLD=0.07402, YOUNG=0.03132
A =
[[0.99520704 0.00316863 0.00162433]
 [0.01011091 0.98727434 0.00261476]
 [0.00608678 0.00338792 0.9905253 ]]
pi = [0.39768441 0.27389891 0.32841667]
Iter 12: LL=-1304281.77 | Rates: N=0.90086, AF=0.09636, OLD=0.07536, YOUNG=0.03179
A =
[[0.9952073  0.00306713 0.00172558]
 [0.01020232 0.98694621 0.00285147]
 [0.00616296 0.00340646 0.99043058]]
pi = [0.39770043 0.26287527 0.3394243 ]
Iter 13: LL=-1304265.59 | Rates: N=0.90085, AF=0.09635, OLD=0.07675, YOUNG=0.03224
A =
[[0.99520758 0.00296653 0.00182589]
 [0.01029496 0.986604   0.00310104]
 [0.00623505 0.00342317 0.99034178]]
pi = [0.39770756 0.25277992 0.34951253]
Iter 14: LL=-1304249.78 | Rates: N=0.90085, AF=0.09633, OLD=0.07818, YOUNG=0.03268
A =
[[0.99520789 0.00286709 0.00192502]
 [0.01038894 0.98624721 0.00336386]
 [0.00630334 0.00343798 0.99025868]]
pi = [0.39770666 0.24354117 0.35875217]
Iter 15: LL=-1304234.32 | Rates: N=0.90085, AF=0.09632, OLD=0.07966, YOUNG=0.03310
A =
[[0.99520822 0.00276904 0.00202274]
 [0.01048429 0.98587538 0.00364034]
 [0.00636815 0.00345087 0.99018098]]
pi = [0.39769825 0.23510308 0.36719867]
Final Global Rates (lambdas): [0.90085303 0.09631802 0.07965818 0.03310344]
Final transition matrix A:
[[0.99520822 0.00276904 0.00202274]
 [0.01048429 0.98587538 0.00364034]
 [0.00636815 0.00345087 0.99018098]]
Final initial distribution pi:
[0.39769825 0.23510308 0.36719867]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_55000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.8021,0.4892,0.6077,126861639.0,31296361.0,132467666.0
Archaic_young,0.3873,0.7359,0.5075,82610434.0,130705566.0,29650860.0
Modern,0.0000,0.0000,0.0000,0.0,628526000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         621848         1730           1599
Archaic_old      5396       127410         128693
Archaic_young    1282        29018          83024

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.1, 't_young_kya': 40000, 't_old_kya': 60000, 'delta_kya': 20000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.7010  0.9737  0.8151
Archaic_young     0.7615  0.0721  0.1317

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         614156         3598             30
Archaic_old      5846       258832           2518
Archaic_young    1275       105516           8229

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 16
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1575454.82 | Rates: N=0.89311, AF=0.09757, OLD=0.06575, YOUNG=0.03545
A =
[[9.94674932e-01 4.55844041e-03 7.66627213e-04]
 [9.28706013e-03 9.89694918e-01 1.01802182e-03]
 [7.38711042e-03 4.70755081e-03 9.87905339e-01]]
pi = [0.60204446 0.34353057 0.05442498]
Iter 2: LL=-1311396.73 | Rates: N=0.89342, AF=0.09759, OLD=0.06803, YOUNG=0.03152
A =
[[9.94748505e-01 4.39363922e-03 8.57855501e-04]
 [9.55957518e-03 9.89236003e-01 1.20442167e-03]
 [6.35310113e-03 3.88865172e-03 9.89758247e-01]]
pi = [0.60075899 0.36313551 0.0361055 ]
Iter 3: LL=-1311306.48 | Rates: N=0.89341, AF=0.09756, OLD=0.07039, YOUNG=0.03023
A =
[[9.94751972e-01 4.29908369e-03 9.48943980e-04]
 [9.78746286e-03 9.88841309e-01 1.37122771e-03]
 [6.13469515e-03 3.58335641e-03 9.90281948e-01]]
pi = [0.60031197 0.37831231 0.02137572]
Iter 4: LL=-1311268.05 | Rates: N=0.89341, AF=0.09752, OLD=0.07211, YOUNG=0.03003
A =
[[0.99475161 0.00420595 0.00104244]
 [0.00990912 0.98854387 0.00154701]
 [0.00617212 0.00348624 0.99034163]]
pi = [0.59997846 0.3875472  0.01247434]
Iter 5: LL=-1311245.19 | Rates: N=0.89341, AF=0.09749, OLD=0.07348, YOUNG=0.03028
A =
[[0.9947516  0.00411059 0.00113781]
 [0.00997955 0.98828461 0.00173584]
 [0.00628727 0.00347012 0.99024261]]
pi = [0.59977196 0.39279578 0.00743227]
Iter 6: LL=-1311225.96 | Rates: N=0.89341, AF=0.09747, OLD=0.07471, YOUNG=0.03071
A =
[[0.99475192 0.00401376 0.00123432]
 [0.01003133 0.98803087 0.0019378 ]
 [0.00641635 0.00348404 0.9900996 ]]
pi = [0.59964723 0.3957858  0.00456697]
Iter 7: LL=-1311207.78 | Rates: N=0.89341, AF=0.09746, OLD=0.07591, YOUNG=0.03122
A =
[[0.99475239 0.00391616 0.00133145]
 [0.01007857 0.9877688  0.00215263]
 [0.00653861 0.0035086  0.9899528 ]]
pi = [0.59956496 0.39753639 0.00289866]
Iter 8: LL=-1311190.12 | Rates: N=0.89340, AF=0.09744, OLD=0.07711, YOUNG=0.03175
A =
[[0.99475288 0.00381821 0.0014289 ]
 [0.01012685 0.98749286 0.0023803 ]
 [0.00664861 0.00353629 0.9898151 ]]
pi = [0.59950382 0.39859767 0.00189851]
Iter 9: LL=-1311172.85 | Rates: N=0.89340, AF=0.09743, OLD=0.07834, YOUNG=0.03228
A =
[[0.99475338 0.00372016 0.00152646]
 [0.01017824 0.98720078 0.00262098]
 [0.00674618 0.00356412 0.98968971]]
pi = [0.59945358 0.3992651  0.00128132]
Iter 10: LL=-1311155.90 | Rates: N=0.89340, AF=0.09742, OLD=0.07961, YOUNG=0.03281
A =
[[0.99475387 0.00362218 0.00162395]
 [0.01023336 0.98689167 0.00287496]
 [0.00683277 0.00359075 0.98957647]]
pi = [0.59940945 0.39970063 0.00088991]
Iter 11: LL=-1311139.26 | Rates: N=0.89340, AF=0.09740, OLD=0.08093, YOUNG=0.03334
A =
[[0.99475434 0.00352443 0.00172123]
 [0.01029223 0.9865652  0.00314257]
 [0.00691018 0.00361558 0.98947424]]
pi = [0.59936927 0.39999539 0.00063534]
Iter 12: LL=-1311122.90 | Rates: N=0.89340, AF=0.09739, OLD=0.08228, YOUNG=0.03386
A =
[[0.99475481 0.00342704 0.00181816]
 [0.0103546  0.98622122 0.00342417]
 [0.00698007 0.00363828 0.98938165]]
pi = [5.99332122e-01 4.00202039e-01 4.65839023e-04]
Iter 13: LL=-1311106.79 | Rates: N=0.89340, AF=0.09738, OLD=0.08369, YOUNG=0.03437
A =
[[0.99475527 0.00333016 0.00191458]
 [0.01042016 0.98585969 0.00372015]
 [0.00704384 0.00365868 0.98929748]]
pi = [5.99297685e-01 4.00351782e-01 3.50533411e-04]
Iter 14: LL=-1311090.95 | Rates: N=0.89340, AF=0.09736, OLD=0.08514, YOUNG=0.03486
A =
[[0.99475572 0.00323393 0.00201034]
 [0.01048858 0.98548052 0.0040309 ]
 [0.00710263 0.00367666 0.98922071]]
pi = [5.99265939e-01 4.00463526e-01 2.70535775e-04]
Iter 15: LL=-1311075.36 | Rates: N=0.89340, AF=0.09735, OLD=0.08665, YOUNG=0.03535
A =
[[0.99475618 0.00313851 0.0021053 ]
 [0.01055962 0.98508352 0.00435686]
 [0.00715728 0.0036922  0.98915051]]
pi = [5.99236981e-01 4.00548976e-01 2.14043105e-04]
Final Global Rates (lambdas): [0.89339696 0.09734929 0.08664814 0.03534867]
Final transition matrix A:
[[0.99475618 0.00313851 0.0021053 ]
 [0.01055962 0.98508352 0.00435686]
 [0.00715728 0.0036922  0.98915051]]
Final initial distribution pi:
[5.99236981e-01 4.00548976e-01 2.14043105e-04]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.1_told_60000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.8280,0.5276,0.6445,139765508.0,29025492.0,125128883.0
Archaic_young,0.4131,0.7617,0.5357,86734797.0,123213203.0,27128590.0
Modern,0.0000,0.0000,0.0000,0.0,621261000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         614156         1910           1718
Archaic_old      5823       140356         121017
Archaic_young    1282        26525          87213

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 35000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old        0.535   0.976  0.6912
Archaic_young      0.525   0.022  0.0423

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         577899         2629             33
Archaic_old      2308       219681           3787
Archaic_young    1802       187617           4244

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1531615.77 | Rates: N=0.88562, AF=0.09658, OLD=0.04332, YOUNG=0.03404
A =
[[0.99585898 0.00267318 0.00146784]
 [0.00584761 0.99250174 0.00165065]
 [0.00596338 0.00306126 0.99097536]]
pi = [0.65085769 0.22897165 0.12017066]
Iter 2: LL=-1275179.75 | Rates: N=0.88584, AF=0.09631, OLD=0.04483, YOUNG=0.03161
A =
[[0.99585663 0.00265672 0.00148665]
 [0.0059219  0.9923836  0.0016945 ]
 [0.00579404 0.00295247 0.99125349]]
pi = [0.65284418 0.22793696 0.11921885]
Iter 3: LL=-1275135.30 | Rates: N=0.88584, AF=0.09630, OLD=0.04662, YOUNG=0.02943
A =
[[0.99585719 0.00262703 0.00151578]
 [0.00603659 0.99220133 0.00176209]
 [0.00561304 0.0028216  0.99156536]]
pi = [0.65288749 0.22994285 0.11716967]
Iter 4: LL=-1275091.44 | Rates: N=0.88584, AF=0.09629, OLD=0.04837, YOUNG=0.02783
A =
[[0.99585771 0.00258698 0.00155531]
 [0.00615716 0.99198694 0.0018559 ]
 [0.00545589 0.00270679 0.99183732]]
pi = [0.65287564 0.23452482 0.11259955]
Iter 5: LL=-1275060.29 | Rates: N=0.88584, AF=0.09628, OLD=0.04986, YOUNG=0.02687
A =
[[0.99585795 0.0025406  0.00160145]
 [0.00626086 0.9917646  0.00197454]
 [0.00534889 0.00263335 0.99201776]]
pi = [0.65284274 0.24068567 0.10647159]
Iter 6: LL=-1275041.90 | Rates: N=0.88584, AF=0.09627, OLD=0.05107, YOUNG=0.02639
A =
[[0.99585802 0.00249033 0.00165165]
 [0.00634212 0.99154163 0.00211625]
 [0.00528624 0.00259903 0.99211473]]
pi = [0.652797   0.24691626 0.10028674]
Iter 7: LL=-1275030.49 | Rates: N=0.88584, AF=0.09626, OLD=0.05208, YOUNG=0.02622
A =
[[0.99585804 0.00243736 0.0017046 ]
 [0.00640616 0.99131515 0.00227869]
 [0.00525269 0.0025909  0.99215641]]
pi = [0.65275055 0.25239086 0.09485859]
Iter 8: LL=-1275021.75 | Rates: N=0.88584, AF=0.09625, OLD=0.05296, YOUNG=0.02623
A =
[[0.99585806 0.00238234 0.00175959]
 [0.00645985 0.99108052 0.00245962]
 [0.00523601 0.00259729 0.9921667 ]]
pi = [0.65270896 0.25696358 0.09032746]
Iter 9: LL=-1275013.75 | Rates: N=0.88584, AF=0.09624, OLD=0.05379, YOUNG=0.02633
A =
[[0.99585811 0.00232573 0.00181616]
 [0.00650829 0.99083424 0.00265747]
 [0.00522877 0.00261055 0.99216068]]
pi = [0.65267234 0.26078658 0.08654109]
Iter 10: LL=-1275005.83 | Rates: N=0.88584, AF=0.09624, OLD=0.05460, YOUNG=0.02648
A =
[[0.99585817 0.00226782 0.00187401]
 [0.00655455 0.99057413 0.00287133]
 [0.00522692 0.00262629 0.99214679]]
pi = [0.65263912 0.2640662  0.08329468]
Iter 11: LL=-1274997.77 | Rates: N=0.88584, AF=0.09624, OLD=0.05543, YOUNG=0.02666
A =
[[0.99585824 0.00220886 0.00193291]
 [0.00660031 0.99029884 0.00310085]
 [0.00522839 0.00264211 0.9921295 ]]
pi = [0.65260789 0.26697399 0.08041813]
Iter 12: LL=-1274989.51 | Rates: N=0.88584, AF=0.09623, OLD=0.05628, YOUNG=0.02685
A =
[[0.99585832 0.00214901 0.00199267]
 [0.00664646 0.99000754 0.003346  ]
 [0.00523212 0.00265669 0.99211118]]
pi = [0.65257772 0.26963087 0.0777914 ]
Iter 13: LL=-1274981.06 | Rates: N=0.88584, AF=0.09623, OLD=0.05718, YOUNG=0.02705
A =
[[0.99585841 0.00208844 0.00205315]
 [0.0066934  0.98969963 0.00360697]
 [0.00523756 0.00266937 0.99209307]]
pi = [0.65254813 0.272115   0.07533687]
Iter 14: LL=-1274972.43 | Rates: N=0.88584, AF=0.09622, OLD=0.05812, YOUNG=0.02725
A =
[[0.99585851 0.00202729 0.0021142 ]
 [0.00674129 0.98937469 0.00388401]
 [0.00524439 0.00267976 0.99207585]]
pi = [0.65251885 0.27447358 0.07300757]
Iter 15: LL=-1274963.62 | Rates: N=0.88584, AF=0.09622, OLD=0.05910, YOUNG=0.02746
A =
[[0.99585861 0.00196572 0.00217567]
 [0.00679015 0.98903242 0.00417743]
 [0.00525245 0.00268766 0.99205989]]
pi = [0.65248982 0.276733   0.07077718]
Final Global Rates (lambdas): [0.88583858 0.09621651 0.05909936 0.02745752]
Final transition matrix A:
[[0.99585861 0.00196572 0.00217567]
 [0.00679015 0.98903242 0.00417743]
 [0.00525245 0.00268766 0.99205989]]
Final initial distribution pi:
[0.65248982 0.276733   0.07077718]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.2_told_35000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5561,0.3069,0.3955,68958190.0,55036810.0,155753863.0
Archaic_young,0.4668,0.7149,0.5648,137403142.0,156929858.0,54791452.0
Modern,0.0000,0.0000,0.0000,0.0,581672000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         577816          964           1781
Archaic_old      2172        69095         154509
Archaic_young    1684        53936         138043

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 40000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5318  0.9615  0.6848
Archaic_young     0.5297  0.0401  0.0746

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         555575         3001             44
Archaic_old      2631       225898           7194
Archaic_young    2100       195350           8207

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1517397.75 | Rates: N=0.86920, AF=0.09745, OLD=0.04532, YOUNG=0.03658
A =
[[0.99527653 0.00294396 0.0017795 ]
 [0.00623126 0.99170739 0.00206135]
 [0.00601998 0.00333594 0.99064408]]
pi = [0.69234416 0.20686082 0.10079502]
Iter 2: LL=-1275159.69 | Rates: N=0.86941, AF=0.09731, OLD=0.04680, YOUNG=0.03405
A =
[[0.99528979 0.002916   0.00179421]
 [0.00632357 0.9915754  0.00210103]
 [0.0058084  0.00323422 0.99095738]]
pi = [0.70040746 0.21470123 0.08489132]
Iter 3: LL=-1275110.61 | Rates: N=0.86941, AF=0.09729, OLD=0.04886, YOUNG=0.03176
A =
[[0.99529185 0.00288573 0.00182242]
 [0.0064821  0.99136321 0.00215469]
 [0.00560066 0.00311163 0.99128771]]
pi = [0.70049287 0.22872678 0.07078035]
Iter 4: LL=-1275056.86 | Rates: N=0.86941, AF=0.09727, OLD=0.05097, YOUNG=0.02998
A =
[[0.99529337 0.00284172 0.00186491]
 [0.00666412 0.99110303 0.00223284]
 [0.00540422 0.00299135 0.99160443]]
pi = [0.70016724 0.24068274 0.05915001]
Iter 5: LL=-1275014.99 | Rates: N=0.86941, AF=0.09724, OLD=0.05284, YOUNG=0.02887
A =
[[0.99529443 0.00278679 0.00191878]
 [0.00683828 0.99082602 0.00233569]
 [0.00525461 0.00290558 0.99183981]]
pi = [0.69982287 0.24917305 0.05100408]
Iter 6: LL=-1274989.24 | Rates: N=0.86941, AF=0.09722, OLD=0.05438, YOUNG=0.02829
A =
[[0.99529508 0.00272404 0.00198088]
 [0.00699005 0.99054713 0.00246281]
 [0.00515491 0.00285941 0.99198568]]
pi = [0.69953243 0.2545995  0.04586807]
Iter 7: LL=-1274973.77 | Rates: N=0.86941, AF=0.09720, OLD=0.05565, YOUNG=0.02808
A =
[[0.99529551 0.00265572 0.00204877]
 [0.00712076 0.99026674 0.0026125 ]
 [0.00509266 0.00284192 0.99206542]]
pi = [0.69930575 0.25778051 0.04291374]
Iter 8: LL=-1274962.71 | Rates: N=0.86941, AF=0.09718, OLD=0.05676, YOUNG=0.02808
A =
[[0.99529585 0.00258356 0.00212059]
 [0.0072369  0.98998076 0.00278234]
 [0.00505514 0.0028409  0.99210396]]
pi = [0.69912864 0.25938183 0.04148953]
Iter 9: LL=-1274953.10 | Rates: N=0.86941, AF=0.09717, OLD=0.05778, YOUNG=0.02818
A =
[[0.99529618 0.00250886 0.00219496]
 [0.00734433 0.98968539 0.00297028]
 [0.00503361 0.00284782 0.99211857]]
pi = [0.69898503 0.25983563 0.04117934]
Iter 10: LL=-1274943.83 | Rates: N=0.86941, AF=0.09716, OLD=0.05877, YOUNG=0.02835
A =
[[0.99529651 0.00243255 0.00227094]
 [0.00744703 0.98937788 0.00317509]
 [0.00502269 0.00285769 0.99211961]]
pi = [0.69886352 0.25939947 0.04173702]
Iter 11: LL=-1274934.54 | Rates: N=0.86941, AF=0.09715, OLD=0.05976, YOUNG=0.02854
A =
[[0.99529687 0.00235529 0.00234785]
 [0.0075475  0.98905626 0.00339625]
 [0.00501917 0.00286784 0.99211298]]
pi = [0.69875718 0.2582224  0.04302041]
Iter 12: LL=-1274925.12 | Rates: N=0.86941, AF=0.09715, OLD=0.06079, YOUNG=0.02875
A =
[[0.99529724 0.00227755 0.00242521]
 [0.00764724 0.98871896 0.0036338 ]
 [0.00502106 0.0028769  0.99210204]]
pi = [0.69866209 0.25639226 0.04494565]
Iter 13: LL=-1274915.54 | Rates: N=0.86941, AF=0.09714, OLD=0.06185, YOUNG=0.02896
A =
[[0.99529764 0.0021997  0.00250266]
 [0.00774724 0.98836463 0.00388813]
 [0.00502708 0.00288416 0.99208876]]
pi = [0.69857602 0.25396655 0.04745744]
Iter 14: LL=-1274905.79 | Rates: N=0.86941, AF=0.09713, OLD=0.06297, YOUNG=0.02918
A =
[[0.99529807 0.00212199 0.00257995]
 [0.00784815 0.98799201 0.00415984]
 [0.00503633 0.00288933 0.99207435]]
pi = [0.69849767 0.25099278 0.05050955]
Iter 15: LL=-1274895.86 | Rates: N=0.86941, AF=0.09712, OLD=0.06413, YOUNG=0.02939
A =
[[0.99529851 0.00204465 0.00265684]
 [0.00795043 0.98759991 0.00444966]
 [0.00504817 0.00289225 0.99205958]]
pi = [0.69842618 0.24752209 0.05405173]
Final Global Rates (lambdas): [0.8694087  0.09712077 0.06413402 0.02938926]
Final transition matrix A:
[[0.99529851 0.00204465 0.00265684]
 [0.00795043 0.98759991 0.00444966]
 [0.00504817 0.00289225 0.99205958]]
Final initial distribution pi:
[0.69842618 0.24752209 0.05405173]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.2_told_40000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5607,0.2725,0.3668,63942147.0,50099853.0,170700785.0
Archaic_young,0.4721,0.7545,0.5808,153876389.0,172083611.0,50081493.0
Modern,0.0000,0.0000,0.0000,0.0,559998000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         555536          972           2112
Archaic_old      2497        64055         169171
Archaic_young    1965        49015         154677

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 45000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5189  0.9552  0.6725
Archaic_young     0.6852  0.0796  0.1427

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         549412         3136             64
Archaic_old      3254       218264           7785
Archaic_young    2112       198696          17277

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...
   📊 Processed lines: 100000...
 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1518524.44 | Rates: N=0.86580, AF=0.09650, OLD=0.04951, YOUNG=0.04014
A =
[[0.99476285 0.00320545 0.0020317 ]
 [0.00679212 0.99076502 0.00244286]
 [0.00647093 0.00367019 0.98985888]]
pi = [0.55382458 0.29234544 0.15382997]
Iter 2: LL=-1279535.86 | Rates: N=0.86604, AF=0.09640, OLD=0.05163, YOUNG=0.03667
A =
[[0.99479074 0.00317241 0.00203685]
 [0.00689659 0.99059934 0.00250408]
 [0.00622118 0.00351537 0.99026345]]
pi = [0.55404273 0.30948345 0.13647381]
Iter 3: LL=-1279444.24 | Rates: N=0.86604, AF=0.09637, OLD=0.05478, YOUNG=0.03344
A =
[[0.99479349 0.00314254 0.00206397]
 [0.00709904 0.99031661 0.00258435]
 [0.00598536 0.00331729 0.99069735]]
pi = [0.55390658 0.33213689 0.11395652]
Iter 4: LL=-1279338.76 | Rates: N=0.86604, AF=0.09633, OLD=0.05795, YOUNG=0.03103
A =
[[0.99479491 0.00309331 0.00211177]
 [0.00731738 0.98998345 0.00269917]
 [0.00578569 0.00313218 0.99108212]]
pi = [0.55370044 0.35461554 0.09168401]
Iter 5: LL=-1279263.68 | Rates: N=0.86605, AF=0.09629, OLD=0.06058, YOUNG=0.02966
A =
[[0.99479561 0.00302976 0.00217463]
 [0.00749622 0.98965242 0.00285136]
 [0.00566552 0.00301709 0.99131739]]
pi = [0.55348989 0.37314188 0.07336823]
Iter 6: LL=-1279224.90 | Rates: N=0.86605, AF=0.09625, OLD=0.06259, YOUNG=0.02906
A =
[[0.99479588 0.00295712 0.002247  ]
 [0.00762674 0.98933229 0.00304096]
 [0.00560994 0.00296834 0.99142173]]
pi = [0.55333036 0.38702326 0.05964638]
Iter 7: LL=-1279204.69 | Rates: N=0.86605, AF=0.09622, OLD=0.06417, YOUNG=0.02890
A =
[[0.99479605 0.00287905 0.0023249 ]
 [0.00772472 0.98901223 0.00326306]
 [0.00559137 0.00296044 0.99144819]]
pi = [0.55322485 0.39707021 0.04970494]
Iter 8: LL=-1279190.77 | Rates: N=0.86605, AF=0.09621, OLD=0.06551, YOUNG=0.02896
A =
[[0.99479626 0.00279808 0.00240565]
 [0.00780582 0.98868238 0.0035118 ]
 [0.00559106 0.00297307 0.99143587]]
pi = [0.55315689 0.4042749  0.0425682 ]
Iter 9: LL=-1279178.58 | Rates: N=0.86605, AF=0.09619, OLD=0.06675, YOUNG=0.02913
A =
[[0.99479652 0.00271583 0.00248764]
 [0.00787975 0.98833723 0.00378302]
 [0.0055992  0.00299453 0.99140627]]
pi = [0.55311245 0.40940458 0.03748296]
Iter 10: LL=-1279166.80 | Rates: N=0.86605, AF=0.09618, OLD=0.06796, YOUNG=0.02936
A =
[[0.99479681 0.00263326 0.00256992]
 [0.00795161 0.98797397 0.00407442]
 [0.00561114 0.00301886 0.99137   ]]
pi = [0.55308313 0.41298265 0.03393422]
Iter 11: LL=-1279155.10 | Rates: N=0.86605, AF=0.09617, OLD=0.06919, YOUNG=0.02961
A =
[[0.99479712 0.00255096 0.00265192]
 [0.00802396 0.98759106 0.00438497]
 [0.00562475 0.00304316 0.99133209]]
pi = [0.55306434 0.41534902 0.03158664]
Iter 12: LL=-1279143.41 | Rates: N=0.86604, AF=0.09616, OLD=0.07045, YOUNG=0.02986
A =
[[0.99479744 0.00246928 0.00273328]
 [0.00809805 0.98718757 0.00471437]
 [0.00563908 0.00306601 0.99129491]]
pi = [0.55305363 0.41671364 0.03023273]
Iter 13: LL=-1279131.71 | Rates: N=0.86604, AF=0.09615, OLD=0.07175, YOUNG=0.03012
A =
[[0.99479777 0.00238849 0.00281373]
 [0.0081745  0.98676282 0.00506268]
 [0.0056537  0.00308671 0.99125959]]
pi = [0.55304958 0.41719132 0.0297591 ]
Iter 14: LL=-1279120.02 | Rates: N=0.86604, AF=0.09614, OLD=0.07311, YOUNG=0.03038
A =
[[0.99479811 0.0023088  0.00289309]
 [0.00825358 0.9863163  0.00543011]
 [0.00566844 0.00310489 0.99122667]]
pi = [0.5530513  0.41682127 0.03012744]
Iter 15: LL=-1279108.35 | Rates: N=0.86604, AF=0.09612, OLD=0.07452, YOUNG=0.03063
A =
[[0.99479844 0.00223038 0.00297118]
 [0.00833544 0.98584764 0.00581692]
 [0.00568323 0.00312034 0.99119643]]
pi = [0.55305807 0.4155759  0.03136602]
Final Global Rates (lambdas): [0.86604414 0.09612434 0.07452271 0.03063272]
Final transition matrix A:
[[0.99479844 0.00223038 0.00297118]
 [0.00833544 0.98584764 0.00581692]
 [0.00568323 0.00312034 0.99119643]]
Final initial distribution pi:
[0.55305807 0.4155759  0.03136602]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.2_told_45000k_tyoung_40000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5694,0.2666,0.3632,60849477.0,46015523.0,167370452.0
Archaic_young,0.5023,0.7869,0.6132,170110364.0,168585636.0,46056419.0
Modern,0.0000,0.0000,0.0000,0.0,554439000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         549371          933           2308
Archaic_old      3001        60989         165313
Archaic_young    2067        44943         171075

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.2, 't_young_kya': 45000, 't_old_kya': 50000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5453  0.9758  0.6997
Archaic_young     0.7162  0.0371  0.0705

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         563658         3408             46
Archaic_old      3891       229293           2789
Archaic_young    2483       187178           7254

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1538460.77 | Rates: N=0.87405, AF=0.09671, OLD=0.05545, YOUNG=0.04615
A =
[[0.99453815 0.00331377 0.00214808]
 [0.00754709 0.98968527 0.00276764]
 [0.00729679 0.00410299 0.98860021]]
pi = [0.392977   0.37328108 0.23374192]
Iter 2: LL=-1291981.41 | Rates: N=0.87431, AF=0.09662, OLD=0.05737, YOUNG=0.04267
A =
[[0.99458653 0.00327461 0.00213886]
 [0.00759637 0.98956936 0.00283426]
 [0.00704777 0.00395794 0.98899429]]
pi = [0.38503057 0.36244877 0.25252066]
Iter 3: LL=-1291907.55 | Rates: N=0.87431, AF=0.09661, OLD=0.06044, YOUNG=0.03932
A =
[[0.99459045 0.00325688 0.00215267]
 [0.0077716  0.98929959 0.00292882]
 [0.0068286  0.00376481 0.98940659]]
pi = [0.38455129 0.339267   0.27618172]
Iter 4: LL=-1291813.98 | Rates: N=0.87431, AF=0.09658, OLD=0.06375, YOUNG=0.03656
A =
[[0.99459188 0.00322514 0.00218298]
 [0.00798633 0.98894033 0.00307333]
 [0.00661382 0.00355991 0.98982627]]
pi = [0.38454274 0.30867214 0.30678512]
Iter 5: LL=-1291735.76 | Rates: N=0.87431, AF=0.09654, OLD=0.06671, YOUNG=0.03479
A =
[[0.99459259 0.0031802  0.00222721]
 [0.00818315 0.98854902 0.00326783]
 [0.00646177 0.00340988 0.99012835]]
pi = [0.38464704 0.27579805 0.33955491]
Iter 6: LL=-1291688.88 | Rates: N=0.87430, AF=0.09650, OLD=0.06909, YOUNG=0.03388
A =
[[0.99459281 0.00312505 0.00228214]
 [0.00833568 0.98815543 0.00350889]
 [0.00637913 0.00332988 0.99029099]]
pi = [0.3848581  0.24551661 0.36962529]
Iter 7: LL=-1291663.22 | Rates: N=0.87430, AF=0.09647, OLD=0.07098, YOUNG=0.03353
A =
[[0.99459288 0.00306218 0.00234493]
 [0.00844854 0.98776126 0.00379019]
 [0.00634502 0.003301   0.99035398]]
pi = [0.3851238  0.21996293 0.39491327]
Iter 8: LL=-1291646.50 | Rates: N=0.87430, AF=0.09644, OLD=0.07257, YOUNG=0.03348
A =
[[0.99459301 0.00299379 0.0024132 ]
 [0.00853499 0.98736036 0.00410466]
 [0.00633926 0.00330144 0.9903593 ]]
pi = [0.38537871 0.19907215 0.41554914]
Iter 9: LL=-1291632.72 | Rates: N=0.87430, AF=0.09643, OLD=0.07401, YOUNG=0.03360
A =
[[0.99459323 0.00292165 0.00248512]
 [0.00860573 0.98694739 0.00444688]
 [0.00634897 0.0033165  0.99033453]]
pi = [0.38558869 0.18194222 0.43246909]
Iter 10: LL=-1291619.77 | Rates: N=0.87430, AF=0.09641, OLD=0.07538, YOUNG=0.03379
A =
[[0.99459355 0.00284706 0.00255939]
 [0.00866754 0.98651877 0.00481369]
 [0.00636694 0.00333785 0.99029521]]
pi = [0.38574823 0.16760876 0.446643  ]
Iter 11: LL=-1291607.04 | Rates: N=0.87430, AF=0.09639, OLD=0.07675, YOUNG=0.03402
A =
[[0.99459392 0.00277092 0.00263516]
 [0.00872438 0.98607196 0.00520366]
 [0.00638927 0.00336107 0.99024966]]
pi = [0.38586464 0.1552923  0.45884306]
Iter 12: LL=-1291594.31 | Rates: N=0.87430, AF=0.09638, OLD=0.07816, YOUNG=0.03427
A =
[[0.99459435 0.00269382 0.00271183]
 [0.00877865 0.9856048  0.00561655]
 [0.00641378 0.00338387 0.99020235]]
pi = [0.38594797 0.14442011 0.46963192]
Iter 13: LL=-1291581.54 | Rates: N=0.87430, AF=0.09637, OLD=0.07961, YOUNG=0.03453
A =
[[0.99459482 0.00261622 0.00278897]
 [0.00883185 0.98511531 0.00605285]
 [0.00643923 0.00340499 0.99015578]]
pi = [0.38600725 0.13458563 0.47940712]
Iter 14: LL=-1291568.69 | Rates: N=0.87430, AF=0.09635, OLD=0.08112, YOUNG=0.03479
A =
[[0.99459531 0.00253841 0.00286627]
 [0.00888503 0.98460154 0.00651344]
 [0.00646489 0.00342376 0.99011135]]
pi = [0.38604954 0.12550336 0.4884471 ]
Iter 15: LL=-1291555.74 | Rates: N=0.87430, AF=0.09634, OLD=0.08270, YOUNG=0.03506
A =
[[0.99459583 0.00246067 0.0029435 ]
 [0.00893895 0.98406159 0.00699946]
 [0.0064903  0.00343977 0.99006993]]
pi = [0.38608016 0.1169733  0.49694654]
Final Global Rates (lambdas): [0.87429517 0.09633505 0.08270359 0.03505625]
Final transition matrix A:
[[0.99459583 0.00246067 0.0029435 ]
 [0.00893895 0.98406159 0.00699946]
 [0.0064903  0.00343977 0.99006993]]
Final initial distribution pi:
[0.38608016 0.1169733  0.49694654]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.2_told_50000k_tyoung_45000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.5993,0.2509,0.3537,58879781.0,39366219.0,175779706.0
Archaic_young,0.4676,0.7961,0.5891,155140493.0,176654507.0,39739447.0
Modern,0.0000,0.0000,0.0000,0.0,569959000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         563685          946           2481
Archaic_old      3770        59005         173198
Archaic_young    2504        38295         156116

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.2, 't_young_kya': 50000, 't_old_kya': 55000, 'delta_kya': 5000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5422  0.9624  0.6936
Archaic_young     0.5060  0.0316  0.0596

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         544407         3590             56
Archaic_old      4069       236652           6177
Archaic_young    2782       195813           6454

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1540087.78 | Rates: N=0.86248, AF=0.09858, OLD=0.06416, YOUNG=0.05358
A =
[[0.99406267 0.0035916  0.00234572]
 [0.00752621 0.98941836 0.00305544]
 [0.00740517 0.00458448 0.98801035]]
pi = [0.73637154 0.16068784 0.10294062]
Iter 2: LL=-1301795.21 | Rates: N=0.86269, AF=0.09857, OLD=0.06688, YOUNG=0.04903
A =
[[0.99416193 0.0035155  0.00232257]
 [0.00753401 0.98933568 0.00313031]
 [0.00707199 0.00440064 0.98852737]]
pi = [0.74779409 0.14354825 0.10865766]
Iter 3: LL=-1301674.49 | Rates: N=0.86269, AF=0.09854, OLD=0.07116, YOUNG=0.04461
A =
[[0.99417106 0.00347725 0.00235169]
 [0.00774711 0.98900559 0.0032473 ]
 [0.00679439 0.00413178 0.98907383]]
pi = [0.74814044 0.12772738 0.12413218]
Iter 4: LL=-1301521.84 | Rates: N=0.86269, AF=0.09846, OLD=0.07575, YOUNG=0.04129
A =
[[0.9941742  0.00341456 0.00241124]
 [0.00801377 0.98855538 0.00343086]
 [0.00653781 0.00385587 0.98960632]]
pi = [0.74809622 0.10850238 0.1434014 ]
Iter 5: LL=-1301404.44 | Rates: N=0.86269, AF=0.09838, OLD=0.07978, YOUNG=0.03948
A =
[[0.99417579 0.00333028 0.00249393]
 [0.00825302 0.98806312 0.00368386]
 [0.00637374 0.00366794 0.98995832]]
pi = [0.74803759 0.08968449 0.16227792]
Iter 6: LL=-1301338.94 | Rates: N=0.86268, AF=0.09831, OLD=0.08306, YOUNG=0.03878
A =
[[0.99417652 0.00323046 0.00259302]
 [0.00844204 0.98755187 0.00400609]
 [0.00629337 0.00356945 0.99013718]]
pi = [0.7480025  0.07357365 0.17842384]
Iter 7: LL=-1301300.63 | Rates: N=0.86268, AF=0.09826, OLD=0.08581, YOUNG=0.03871
A =
[[0.99417704 0.00312005 0.00270292]
 [0.00859428 0.98701505 0.00439067]
 [0.00626371 0.0035253  0.99021099]]
pi = [0.74798999 0.06044962 0.19156039]
Iter 8: LL=-1301271.09 | Rates: N=0.86268, AF=0.09822, OLD=0.08832, YOUNG=0.03894
A =
[[0.9941776  0.00300312 0.00281928]
 [0.00872626 0.98644431 0.00482943]
 [0.00626109 0.00350757 0.99023135]]
pi = [0.74798947 0.04980368 0.20220685]
Iter 9: LL=-1301243.56 | Rates: N=0.86268, AF=0.09819, OLD=0.09078, YOUNG=0.03931
A =
[[0.99417828 0.00288264 0.00293908]
 [0.00884855 0.98583438 0.00531707]
 [0.00627272 0.00350085 0.99022644]]
pi = [0.74799399 0.04106031 0.2109457 ]
Iter 10: LL=-1301216.19 | Rates: N=0.86267, AF=0.09816, OLD=0.09330, YOUNG=0.03973
A =
[[0.99417908 0.00276065 0.00306028]
 [0.0089669  0.98518161 0.00585149]
 [0.00629207 0.0034977  0.99021024]]
pi = [0.74800042 0.03377207 0.2182275 ]
Iter 11: LL=-1301188.55 | Rates: N=0.86267, AF=0.09813, OLD=0.09594, YOUNG=0.04018
A =
[[0.99417998 0.00263852 0.0031815 ]
 [0.00908452 0.98448266 0.00643282]
 [0.00631571 0.00349466 0.99018963]]
pi = [0.74800756 0.02762384 0.22436861]
Iter 12: LL=-1301160.57 | Rates: N=0.86267, AF=0.09810, OLD=0.09873, YOUNG=0.04064
A =
[[0.99418098 0.00251728 0.00330174]
 [0.00920337 0.9837341  0.00706253]
 [0.00634168 0.00349015 0.99016816]]
pi = [0.74801498 0.02239937 0.22958565]
Iter 13: LL=-1301132.26 | Rates: N=0.86266, AF=0.09807, OLD=0.10171, YOUNG=0.04109
A =
[[0.99418205 0.0023977  0.00342026]
 [0.00932487 0.98293232 0.00774281]
 [0.00636879 0.00348343 0.99014779]]
pi = [0.74802259 0.01795061 0.2340268 ]
Iter 14: LL=-1301103.68 | Rates: N=0.86266, AF=0.09804, OLD=0.10488, YOUNG=0.04153
A =
[[0.99418316 0.00228041 0.00353643]
 [0.00945022 0.98207372 0.00847607]
 [0.00639623 0.00347411 0.99012966]]
pi = [0.7480304  0.01417478 0.23779482]
Iter 15: LL=-1301074.88 | Rates: N=0.86266, AF=0.09800, OLD=0.10827, YOUNG=0.04197
A =
[[0.99418428 0.00216597 0.00364975]
 [0.00958043 0.98115494 0.00926463]
 [0.00642349 0.00346201 0.9901145 ]]
pi = [0.74803845 0.01099771 0.24096384]
Final Global Rates (lambdas): [0.86265807 0.09800281 0.10826974 0.04197285]
Final transition matrix A:
[[0.99418428 0.00216597 0.00364975]
 [0.00958043 0.98115494 0.00926463]
 [0.00642349 0.00346201 0.9901145 ]]
Final initial distribution pi:
[0.74803845 0.01099771 0.24096384]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.2_told_55000k_tyoung_50000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.6338,0.1821,0.2830,44745779.0,25848221.0,200928349.0
Archaic_young,0.4653,0.8644,0.6049,175367088.0,201562912.0,27514305.0
Modern,0.0000,0.0000,0.0000,0.0,552476000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         544721          502           2830
Archaic_old      4610        44751         197537
Archaic_young    3145        25341         176563

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.2, 't_young_kya': 30000, 't_old_kya': 40000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5541  0.9366  0.6963
Archaic_young     0.5786  0.0920  0.1588

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         566491         2966             76
Archaic_old      3003       221056          12745
Archaic_young    1748       174162          17753

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 17
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 11
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1520588.42 | Rates: N=0.87545, AF=0.09594, OLD=0.04576, YOUNG=0.03022
A =
[[0.99548821 0.00317168 0.00134011]
 [0.00630208 0.9921832  0.00151472]
 [0.00576771 0.00329429 0.990938  ]]
pi = [0.59955146 0.25968161 0.14076693]
Iter 2: LL=-1273486.83 | Rates: N=0.87568, AF=0.09573, OLD=0.04753, YOUNG=0.02785
A =
[[0.99549482 0.00312693 0.00137825]
 [0.0065123  0.99187056 0.00161714]
 [0.00535627 0.00303905 0.99160468]]
pi = [0.60072345 0.24389635 0.1553802 ]
Iter 3: LL=-1273432.01 | Rates: N=0.87568, AF=0.09571, OLD=0.04937, YOUNG=0.02645
A =
[[0.99549509 0.00308388 0.00142104]
 [0.00673179 0.99153675 0.00173146]
 [0.00508425 0.00285932 0.99205643]]
pi = [0.60079896 0.2288177  0.17038334]
Iter 4: LL=-1273397.96 | Rates: N=0.87568, AF=0.09569, OLD=0.05088, YOUNG=0.02576
A =
[[0.99549472 0.0030357  0.00146958]
 [0.00691124 0.99122684 0.00186192]
 [0.00492435 0.00275666 0.99231898]]
pi = [0.60086278 0.21363515 0.18550207]
Iter 5: LL=-1273379.64 | Rates: N=0.87568, AF=0.09567, OLD=0.05205, YOUNG=0.02553
A =
[[0.99549425 0.00298271 0.00152305]
 [0.00704757 0.99094546 0.00200697]
 [0.00484366 0.00271015 0.99244619]]
pi = [0.60092512 0.1982515  0.20082338]
Iter 6: LL=-1273368.30 | Rates: N=0.87568, AF=0.09566, OLD=0.05301, YOUNG=0.02554
A =
[[0.99549388 0.00292552 0.00158061]
 [0.00715235 0.99068286 0.00216479]
 [0.00481034 0.00269575 0.9924939 ]]
pi = [0.60098398 0.18256428 0.21645175]
Iter 7: LL=-1273359.29 | Rates: N=0.87568, AF=0.09565, OLD=0.05385, YOUNG=0.02567
A =
[[0.99549365 0.00286501 0.00164134]
 [0.0072369  0.99042944 0.00233366]
 [0.00480416 0.00269764 0.99249821]]
pi = [0.60103991 0.16657932 0.23238077]
Iter 8: LL=-1273350.98 | Rates: N=0.87568, AF=0.09565, OLD=0.05464, YOUNG=0.02585
A =
[[0.99549353 0.00280201 0.00170446]
 [0.00730879 0.99017884 0.00251236]
 [0.00481369 0.00270702 0.99247929]]
pi = [0.6010937  0.15039831 0.24850799]
Iter 9: LL=-1273342.87 | Rates: N=0.87568, AF=0.09564, OLD=0.05541, YOUNG=0.02605
A =
[[0.99549349 0.00273717 0.00176933]
 [0.00737257 0.9899272  0.00270023]
 [0.0048326  0.00271936 0.99244805]]
pi = [0.60114547 0.13419134 0.26466319]
Iter 10: LL=-1273334.84 | Rates: N=0.87568, AF=0.09564, OLD=0.05619, YOUNG=0.02626
A =
[[0.99549351 0.00267101 0.00183548]
 [0.00743092 0.98967215 0.00289693]
 [0.00485725 0.00273229 0.99241045]]
pi = [0.60119465 0.11817455 0.2806308 ]
Iter 11: LL=-1273326.83 | Rates: N=0.87568, AF=0.09563, OLD=0.05698, YOUNG=0.02647
A =
[[0.99549357 0.00260391 0.00190252]
 [0.00748547 0.98941215 0.00310237]
 [0.00488549 0.00274461 0.9923699 ]]
pi = [0.60124008 0.1025902  0.29616972]
Iter 12: LL=-1273318.86 | Rates: N=0.87568, AF=0.09562, OLD=0.05780, YOUNG=0.02667
A =
[[0.99549366 0.00253619 0.00197015]
 [0.00753725 0.98914621 0.00331654]
 [0.00491592 0.00275565 0.99232843]]
pi = [0.6012803  0.08768704 0.31103266]
Iter 13: LL=-1273310.91 | Rates: N=0.87568, AF=0.09562, OLD=0.05863, YOUNG=0.02687
A =
[[0.99549379 0.00246812 0.00203809]
 [0.00758693 0.98887361 0.00353946]
 [0.00494765 0.00276505 0.9922873 ]]
pi = [0.60131371 0.07370136 0.32498492]
Iter 14: LL=-1273303.00 | Rates: N=0.87568, AF=0.09561, OLD=0.05950, YOUNG=0.02707
A =
[[0.99549393 0.00239996 0.00210611]
 [0.00763495 0.9885939  0.00377115]
 [0.00498006 0.0027726  0.99224734]]
pi = [0.60133887 0.06083978 0.33782135]
Iter 15: LL=-1273295.15 | Rates: N=0.87568, AF=0.09561, OLD=0.06039, YOUNG=0.02727
A =
[[0.9954941  0.0023319  0.002174  ]
 [0.00768161 0.98830679 0.0040116 ]
 [0.00501272 0.0027782  0.99220908]]
pi = [0.60135464 0.04926492 0.34938044]
Final Global Rates (lambdas): [0.87568214 0.09560874 0.06038743 0.02726962]
Final transition matrix A:
[[0.9954941  0.0023319  0.002174  ]
 [0.00768161 0.98830679 0.0040116 ]
 [0.00501272 0.0027782  0.99220908]]
Final initial distribution pi:
[0.60135464 0.04926492 0.34938044]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.2_told_40000k_tyoung_30000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.6010,0.3608,0.4509,84994813.0,56435187.0,150574385.0
Archaic_young,0.4744,0.7101,0.5688,136475171.0,151225829.0,55719423.0
Modern,0.0000,0.0000,0.0000,0.0,570869000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         566484         1281           1768
Archaic_old      2758        85236         148810
Archaic_young    1627        54913         137123

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.2, 't_young_kya': 35000, 't_old_kya': 45000, 'delta_kya': 10000}
Начались симуляции...
Закончились симуляции.
Начался запуск WITHOUT EM...
Закончился запуск WITHOUT EM.

WITHOUT EM — метрики по классам

               Precision  Recall      F1
Archaic_old       0.5380  0.9052  0.6749
Archaic_young     0.5679  0.1275  0.2082

WITHOUT EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         556947         3021            183
Archaic_old      3493       211182          19517
Archaic_young    1874       177694          26089

Начался запуск WITH EM...
Loading 10 files for Global EM & Inference...
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 15
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 14
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 12
 [obs.py] Loading BED windows...
[obs.py] Loaded 50000 windows. Processing TSV...

 [obs.py] Processing done. Aggregating results...
 Observation sequences for HMM created successfully!
Max differences in 1000bp window: 13
Data loaded. Starting Global EM optimization...
Iter 1: LL=-1524011.02 | Rates: N=0.86955, AF=0.09753, OLD=0.05076, YOUNG=0.03446
A =
[[0.99493753 0.0034522  0.00161027]
 [0.00688302 0.99124978 0.0018672 ]
 [0.00618894 0.00362794 0.99018312]]
pi = [0.54702763 0.28417815 0.16879422]
Iter 2: LL=-1281259.68 | Rates: N=0.86979, AF=0.09742, OLD=0.05298, YOUNG=0.03138
A =
[[0.9949576  0.0033918  0.0016506 ]
 [0.00713935 0.99087535 0.0019853 ]
 [0.00572394 0.00333206 0.990944  ]]
pi = [0.54884209 0.25608892 0.19506899]
Iter 3: LL=-1281177.82 | Rates: N=0.86979, AF=0.09738, OLD=0.05550, YOUNG=0.02953
A =
[[0.9949592  0.00333942 0.00170137]
 [0.00742035 0.99046707 0.00211258]
 [0.00541936 0.00312026 0.99146038]]
pi = [0.54887847 0.22437931 0.22674221]
Iter 4: LL=-1281124.42 | Rates: N=0.86979, AF=0.09734, OLD=0.05760, YOUNG=0.02862
A =
[[0.99495919 0.00327734 0.00176346]
 [0.00765807 0.99007867 0.00226326]
 [0.00523833 0.00299658 0.99176509]]
pi = [0.54882388 0.19018313 0.26099299]
Iter 5: LL=-1281095.62 | Rates: N=0.86979, AF=0.09731, OLD=0.05926, YOUNG=0.02831
A =
[[0.99495875 0.00320665 0.0018346 ]
 [0.00784514 0.98971745 0.00243741]
 [0.00514677 0.00293913 0.99191409]]
pi = [0.54882266 0.15642801 0.29474933]
Iter 6: LL=-1281078.09 | Rates: N=0.86979, AF=0.09728, OLD=0.06064, YOUNG=0.02832
A =
[[0.99495833 0.00312925 0.00191242]
 [0.00799512 0.98937225 0.00263263]
 [0.00510882 0.00291901 0.99197217]]
pi = [0.54887926 0.12544965 0.32567109]
Iter 7: LL=-1281064.28 | Rates: N=0.86979, AF=0.09726, OLD=0.06186, YOUNG=0.02848
A =
[[0.99495806 0.00304716 0.00199478]
 [0.00812171 0.98903225 0.00284604]
 [0.00510153 0.00291704 0.99198143]]
pi = [0.54897094 0.09855886 0.3524702 ]
Iter 8: LL=-1281051.55 | Rates: N=0.86979, AF=0.09725, OLD=0.06301, YOUNG=0.02872
A =
[[0.99495793 0.002962   0.00208008]
 [0.00823391 0.98869045 0.00307564]
 [0.00511208 0.00292296 0.99196496]]
pi = [0.54907357 0.07614256 0.37478388]
Iter 9: LL=-1281039.15 | Rates: N=0.86979, AF=0.09724, OLD=0.06416, YOUNG=0.02898
A =
[[0.9949579  0.00287496 0.00216714]
 [0.00833701 0.98834261 0.00332038]
 [0.00513339 0.00293174 0.99193487]]
pi = [0.54917045 0.05799262 0.39283693]
Iter 10: LL=-1281026.88 | Rates: N=0.86979, AF=0.09723, OLD=0.06531, YOUNG=0.02925
A =
[[0.99495795 0.0027869  0.00225514]
 [0.00843411 0.98798599 0.00357989]
 [0.0051614  0.00294094 0.99189766]]
pi = [0.5492528  0.04361027 0.40713693]
Iter 11: LL=-1281014.70 | Rates: N=0.86979, AF=0.09722, OLD=0.06650, YOUNG=0.02951
A =
[[0.99495807 0.0026985  0.00234344]
 [0.00852713 0.98761863 0.00385424]
 [0.00519359 0.00294945 0.99185696]]
pi = [0.54931741 0.03240479 0.41827779]
Iter 12: LL=-1281002.59 | Rates: N=0.86979, AF=0.09721, OLD=0.06773, YOUNG=0.02978
A =
[[0.99495823 0.00261024 0.00243152]
 [0.00861731 0.987239   0.00414369]
 [0.00522835 0.00295672 0.99181493]]
pi = [0.54936446 0.02379915 0.42683639]
Iter 13: LL=-1280990.57 | Rates: N=0.86979, AF=0.09720, OLD=0.06900, YOUNG=0.03003
A =
[[0.99495845 0.00252256 0.00251899]
 [0.00870553 0.98684585 0.00444862]
 [0.00526459 0.0029625  0.99177291]]
pi = [0.54939581 0.01727641 0.43332778]
Iter 14: LL=-1280978.65 | Rates: N=0.86979, AF=0.09719, OLD=0.07032, YOUNG=0.03029
A =
[[0.99495869 0.0024358  0.0026055 ]
 [0.0087924  0.98643818 0.00476942]
 [0.00530156 0.00296666 0.99173178]]
pi = [0.54941406 0.01239462 0.43819133]
Iter 15: LL=-1280966.84 | Rates: N=0.86979, AF=0.09718, OLD=0.07168, YOUNG=0.03054
A =
[[0.99495898 0.00235027 0.00269075]
 [0.00887835 0.98601513 0.00510652]
 [0.00533872 0.00296917 0.99169211]]
pi = [0.54942186 0.00878664 0.4417915 ]
Final Global Rates (lambdas): [0.86979088 0.09717899 0.07168444 0.03053588]
Final transition matrix A:
[[0.99495898 0.00235027 0.00269075]
 [0.00887835 0.98601513 0.00510652]
 [0.00533872 0.00296917 0.99169211]]
Final initial distribution pi:
[0.54942186 0.00878664 0.4417915 ]
Starting Inference on all files...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Calculating emission scores...
Running Viterbi...
Processing gaps...
Done! Processed 10 files.
Saving merged results to grid_runs/pold_0.3_pyoung_0.2_told_45000k_tyoung_35000k/all.inferred.EM.tsv...
Закончился запуск WITH EM.

WITH EM — метрики по классам

,Precision,Recall,F1,TP,FP,FN
Archaic_old,0.6241,0.3030,0.4079,70578503.0,42516497.0,162344071.0
Archaic_young,0.4981,0.7935,0.6120,161835502.0,163057498.0,42122380.0
Modern,0.0000,0.0000,0.0000,0.0,562012000.0,0.0

WITH EM — confusion matrix

               Modern  Archaic_old  Archaic_young
Modern         556934         1123           2094
Archaic_old      3275        70777         160140
Archaic_young    1803        41195         162659

================================================================================
RUN: {'p_old': 0.3, 'p_young': 0.2, 't_young_kya': 40000, 't_old_kya': 50000, 'delta_kya': 10000}
Начались симуляции...

/Users/dana/Desktop/курсач 3 курс/DAIseg/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

OSError: [Errno 28] No space left on device

In [41]:
results_df = pd.DataFrame(all_rows)
results_df.to_csv("grid_runs/summary_table.tsv", sep="\t", index=False)
results_df

,p_old,p_young,t_young_kya,t_old_kya,delta_kya,noem_old_precision,noem_old_recall,noem_old_f1,noem_young_precision,noem_young_recall,...,em_old_f1,em_young_precision,em_young_recall,em_young_f1,learned_lambda_n,learned_lambda_af,learned_lambda_old,learned_lambda_young,summary_json,out_dir
0,0.1,0.1,30000,35000,5000,0.5029,0.7774,0.6107,0.4881,0.2123,...,0.1871,0.4863,0.8758,0.6253,0.984283,0.095302,0.081148,0.030535,grid_runs/pold_0.1_pyoung_0.1_told_35000k_tyou...,grid_runs/pold_0.1_pyoung_0.1_told_35000k_tyou...
1,0.1,0.1,35000,40000,5000,0.4490,0.6424,0.5286,0.5802,0.3845,...,0.2575,0.5382,0.7524,0.6275,0.980678,0.095911,0.066724,0.029470,grid_runs/pold_0.1_pyoung_0.1_told_40000k_tyou...,grid_runs/pold_0.1_pyoung_0.1_told_40000k_tyou...
2,0.1,0.1,40000,45000,5000,0.4856,0.6100,0.5407,0.5813,0.4573,...,0.2743,0.5461,0.8464,0.6639,0.969394,0.096317,0.076757,0.032989,grid_runs/pold_0.1_pyoung_0.1_told_45000k_tyou...,grid_runs/pold_0.1_pyoung_0.1_told_45000k_tyou...
3,0.1,0.1,45000,50000,5000,0.4829,0.6621,0.5585,0.5952,0.4070,...,0.2892,0.5495,0.8243,0.6594,0.979030,0.094520,0.092577,0.038408,grid_runs/pold_0.1_pyoung_0.1_told_50000k_tyou...,grid_runs/pold_0.1_pyoung_0.1_told_50000k_tyou...
4,0.1,0.1,50000,55000,5000,0.4753,0.6053,0.5325,0.5714,0.4081,...,0.1889,0.5358,0.8609,0.6605,0.981834,0.095902,0.119426,0.043791,grid_runs/pold_0.1_pyoung_0.1_told_55000k_tyou...,grid_runs/pold_0.1_pyoung_0.1_told_55000k_tyou...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,0.3,0.2,40000,45000,5000,0.5189,0.9552,0.6725,0.6852,0.0796,...,0.3632,0.5023,0.7869,0.6132,0.866044,0.096124,0.074523,0.030633,grid_runs/pold_0.3_pyoung_0.2_told_45000k_tyou...,grid_runs/pold_0.3_pyoung_0.2_told_45000k_tyou...
190,0.3,0.2,45000,50000,5000,0.5453,0.9758,0.6997,0.7162,0.0371,...,0.3537,0.4676,0.7961,0.5891,0.874295,0.096335,0.082704,0.035056,grid_runs/pold_0.3_pyoung_0.2_told_50000k_tyou...,grid_runs/pold_0.3_pyoung_0.2_told_50000k_tyou...
191,0.3,0.2,50000,55000,5000,0.5422,0.9624,0.6936,0.5060,0.0316,...,0.2830,0.4653,0.8644,0.6049,0.862658,0.098003,0.108270,0.041973,grid_runs/pold_0.3_pyoung_0.2_told_55000k_tyou...,grid_runs/pold_0.3_pyoung_0.2_told_55000k_tyou...
192,0.3,0.2,30000,40000,10000,0.5541,0.9366,0.6963,0.5786,0.0920,...,0.4509,0.4744,0.7101,0.5688,0.875682,0.095609,0.060387,0.027270,grid_runs/pold_0.3_pyoung_0.2_told_40000k_tyou...,grid_runs/pold_0.3_pyoung_0.2_told_40000k_tyou...
193,0.3,0.2,35000,45000,10000,0.5380,0.9052,0.6749,0.5679,0.1275,...,0.4079,0.4981,0.7935,0.6120,0.869791,0.097179,0.071684,0.030536,grid_runs/pold_0.3_pyoung_0.2_told_45000k_tyou...,grid_runs/pold_0.3_pyoung_0.2_told_45000k_tyou...

In [ ]:
# results = Parallel(n_jobs=N_JOBS)(
#     delayed(sims.process_one_chromosome)(seed, params, Ne, t, p_admix, OUTPUT_DIR)
#     for seed in random_seeds
# )
# print(f"All simulations are finished...All trees are in {OUTPUT_DIR}/")

# final_df = pd.concat(results, ignore_index=True)
# csv_path = os.path.join(OUTPUT_DIR, "all.tracts.summary.csv")
# final_df.to_csv(csv_path, index=False, sep='\t')

# print(f"Nd in EU tract table in {csv_path}")

In [ ]:
# # DAIseg — это готовый пайплайн/скрипт, который использует HMM внутри

# print(f"Running DAIseg in parallel for {len(random_seeds)} chromosomes...")
# # Run in parallel
# results = Parallel(n_jobs=N_JOBS)(
#     delayed(sims.run_daiseg_task)(seed, OUTPUT_DIR) 
#     for seed in random_seeds
# )

# valid_dfs = [res for res in results if res is not None]
# if valid_dfs:
#     final_df = pd.concat(valid_dfs, ignore_index=True)    
#     final_output = os.path.join(OUTPUT_DIR, "all.inferred.tracts.tsv")
#     final_df.to_csv(final_output, sep='\t', index=False)    
#     print(f"Done! Saved to {final_output}\n")
# else:
#     print("No tracts found.")

# print("Performance per Class without usin EM...\n\n")
# res = sims.calculate_class_metrics(
#     os.path.join(OUTPUT_DIR, "all.tracts.summary.csv"),
#     os.path.join(OUTPUT_DIR, "all.inferred.tracts.tsv"),
#     params['chrom_length']
#     )

# print(f"Total Analyzed Genome: {res['Total_BP']:,} bp")
# print("-" * 50)
# print(f"{'CLASS':<13} | {'PRECISION':<10} | {'RECALL':<7} | {'F1-SCORE':<10}")
# print("-" * 50)
# for cls, stats in res["Per_class"].items():
#     if cls == "Modern":
#         continue
#     print(f"{cls:<13} | {stats['Precision']:<10.2%} | {stats['Recall']:<7.2%} | {stats['F1']:<10.4f}")
# print("-" * 50)

In [ ]:
# ! python ../daiseg.py run.with.EM -jsons sims/config_seed_*.json -out ./sims/all.inferred.EM.tsv

In [ ]:
# gt_path = os.path.join(OUTPUT_DIR, "all.tracts.summary.csv")
# inf_path = os.path.join(OUTPUT_DIR, "all.inferred.EM.tsv")

# res = sims.calculate_class_metrics(gt_path, inf_path, params['chrom_length'])

# print(f"Total Analyzed Genome: {res['Total_BP']:,} bp")
# print("-" * 55)
# print(f"{'CLASS':<15} | {'PRECISION':<10} | {'RECALL':<10} | {'F1-SCORE':<10}")
# print("-" * 55)

# for cls in ["Archaic_old", "Archaic_young"]:
#     stats = res["Per_class"][cls]
#     print(f"{cls:<15} | {stats['Precision']:<10.2%} | {stats['Recall']:<10.2%} | {stats['F1']:<10.4f}")

# print("-" * 55)

In [ ]:
# gt_df = pd.read_csv(gt_path, sep='\t')
# inf_df = pd.read_csv(inf_path, sep='\t')

# cm, labels = sims.build_confusion_matrix(gt_df, inf_df, chrom_length=int(params['chrom_length']), window_size=1000)
# print(labels)
# print(cm)